(()=>{
'use strict';
const W=window.WorldForgeWorldbuilding,R=window.WorldForgePixelRenderer;if(!W||!R)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(n,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d}),pct=n=>`${fmt(Number(n||0)*100,1)}%`;
const state={world:null,settlement:'0',last:null,raf:0,force:false};
function world(){return state.world||window.WorldForgeWorldOrderUI?.state?.world||window.WorldForgeDiplomacyUI?.state?.world||window.WorldForgeReleaseUI?.state?.world||null}
function ensure(){if($('#worldbuildingPanel'))return;const anchor=$('#worldOrderPanel')||$('#diplomacyPanel')||$('.architecture-panel');if(!anchor)return;anchor.insertAdjacentHTML('afterend',`<section id="worldbuildingPanel" class="panel worldbuilding-panel"><div class="panel-head"><div><span class="eyebrow">SETTLEMENTS · ARCHITECTURE · LANDMARKS · PIXEL CIVILIZATION</span><h2>Worldbuilding Atelier</h2></div><span class="status-ready">v4.1</span></div><div id="worldbuildingKpis" class="worldbuilding-kpis"></div><div class="worldbuilding-toolbar"><label>Settlement<select id="worldbuildingSettlement"></select></label><button id="worldbuildingExport">Export Worldbuilding Ledger</button></div><div class="worldbuilding-layout"><div><div id="worldbuildingPreview" class="worldbuilding-preview"></div><div class="labor-head"><span>DISTRICT PLAN</span><b>POPULATION · WEALTH · CONDITION · STRUCTURES</b></div><div id="worldbuildingDistricts" class="worldbuilding-districts"></div><div class="labor-head"><span>HISTORICAL LANDSCAPE</span><b>RUINS · BATTLEFIELDS · GREAT WORKS · INFRASTRUCTURE</b></div><div id="worldbuildingLandmarks" class="worldbuilding-landmarks"></div></div><aside><div class="labor-head"><span>VISUAL IDENTITY</span></div><div id="worldbuildingIdentity" class="worldbuilding-identity"></div><div class="labor-head"><span>ARCHITECTURAL LANGUAGE</span></div><div id="worldbuildingArchitecture" class="worldbuilding-architecture"></div><div class="labor-head"><span>STRUCTURE INVENTORY</span></div><div id="worldbuildingStructures" class="worldbuilding-structures"></div></aside></div><p class="worldbuilding-note">Pixel settlement previews are deterministic and simulation-driven. v4.1 adds culture-specific architectural forms plus landmarks derived from Adventure sites, Great Works, major historical events and settlement infrastructure.</p></section>`);$('#worldbuildingSettlement').onchange=e=>{state.settlement=e.target.value;state.last=null;schedule(true)};$('#worldbuildingExport').onclick=exportLedger}
function render(force=false){if(document.hidden&&!force)return;const w=world();if(!w)return;state.world=w;ensure();if(!$('#worldbuildingPanel'))return;const S=W.initialize(w);if(S.profiles.some(p=>p.lastYear==null))W.simulateWorldbuildingYear(w,W.absYear(w));const sum=W.summary(w),profiles=S.profiles.slice().sort((a,b)=>b.importanceIndex-a.importanceIndex||a.settlementId-b.settlementId);if(!profiles.length)return;if(!profiles.some(p=>String(p.settlementId)===String(state.settlement)))state.settlement=String(profiles[0].settlementId);const p=W.settlementView(w,Number(state.settlement)),key=`${sum.revision}|${p.settlementId}|${sum.year}|${p.landmarks?.length||0}`;if(!force&&key===state.last)return;state.last=key;
$('#worldbuildingKpis').innerHTML=[['SETTLEMENTS',sum.settlements],['DISTRICTS',sum.districts],['STRUCTURES',fmt(sum.structureUnits)],['LANDMARKS',sum.landmarks],['RUINS',sum.ruins],['BATTLEFIELDS',sum.battlefields],['GREAT WORKS',sum.greatWorks],['MEAN CONDITION',pct(sum.meanCondition)]].map(([k,v])=>`<div><span>${k}</span><b>${esc(v)}</b></div>`).join('');
const sel=$('#worldbuildingSettlement');sel.innerHTML=profiles.map(v=>`<option value="${v.settlementId}" ${String(v.settlementId)===String(p.settlementId)?'selected':''}>${esc(v.name)} · ${esc(v.settlementType.replaceAll('_',' '))}</option>`).join('');
$('#worldbuildingPreview').innerHTML=R.renderSettlement(p,{width:760,height:460});
$('#worldbuildingIdentity').innerHTML=`<article><small>${esc(p.importanceTier.replaceAll('_',' ').toUpperCase())} · ${esc(p.wealthTier.toUpperCase())} · ${esc(p.defenseTier.toUpperCase())}</small><h3>${esc(p.name)}</h3><p>${esc(p.visualIdentity)}</p><div class="worldbuilding-mini"><span><i>POPULATION</i><b>${fmt(p.population)}</b></span><span><i>WEALTH</i><b>${pct(p.wealthIndex)}</b></span><span><i>DEFENSE</i><b>${pct(p.defenseIndex)}</b></span><span><i>CONDITION</i><b>${pct(p.condition)}</b></span><span><i>SERVICES</i><b>${pct(p.serviceIndex)}</b></span><span><i>HOUSING PRESSURE</i><b>${pct(p.housingPressure)}</b></span></div><small>${Object.entries(p.flags).filter(([,v])=>v).map(([k])=>k.replaceAll('_',' ').toUpperCase()).join(' · ')||'INLAND SETTLEMENT'}</small></article>`;
const a=p.architectureStyle||{};$('#worldbuildingArchitecture').innerHTML=`<article><small>${esc(String(a.adaptation||'').replaceAll('-',' ').toUpperCase())}</small><h3>${esc(a.label||p.cultureStyle)}</h3><p>${esc(a.signature||'Locally adapted settlement architecture.')}</p><div class="worldbuilding-mini"><span><i>PRIMARY</i><b>${esc(a.primary||'mixed')}</b></span><span><i>ROOF</i><b>${esc(a.roof||'local')}</b></span><span><i>STREETS</i><b>${esc(a.streetPattern||'organic')}</b></span><span><i>FAMILY</i><b>${esc(a.id||p.cultureStyle)}</b></span></div></article>`;
$('#worldbuildingDistricts').innerHTML=p.districts.map(d=>`<article class="district-${d.kind}"><div><small>${esc(d.kind.replaceAll('_',' ').toUpperCase())}</small><h3>${esc(d.name)}</h3></div><div class="worldbuilding-mini"><span><i>POP SHARE</i><b>${pct(d.populationShare)}</b></span><span><i>WEALTH</i><b>${pct(d.wealth)}</b></span><span><i>CONDITION</i><b>${pct(d.condition)}</b></span><span><i>STRUCTURES</i><b>${(d.structures||[]).reduce((n,x)=>n+x.count,0)}</b></span></div><small>${(d.structures||[]).slice(0,5).map(x=>`${esc(x.type.replaceAll('_',' '))} ×${x.count}`).join(' · ')}</small></article>`).join('');
$('#worldbuildingLandmarks').innerHTML=(p.landmarks||[]).length?p.landmarks.map(l=>`<article class="landmark-${l.type}"><div><small>${esc(l.type.replaceAll('_',' ').toUpperCase())} · ${esc(l.sourceType.replaceAll('_',' ').toUpperCase())}</small><h3>${esc(l.name)}</h3></div><div class="worldbuilding-mini"><span><i>IMPORTANCE</i><b>${pct(l.importance)}</b></span><span><i>CONDITION</i><b>${pct(l.condition)}</b></span><span><i>ORIGIN</i><b>${l.originYear==null?'UNKNOWN':fmt(l.originYear)}</b></span><span><i>AGE</i><b>${l.ageYears==null?'—':`${fmt(l.ageYears)}y`}</b></span></div></article>`).join(''):'<article><small>NO MAJOR LANDMARKS</small><p>This settlement has no major historical or infrastructural landmark in the current aggregate profile.</p></article>';
$('#worldbuildingStructures').innerHTML=p.structureSummary.map(s=>`<article><span>${esc(s.category.toUpperCase())}</span><b>${esc(s.label)}</b><strong>×${fmt(s.count)}</strong></article>`).join('');
const pill=$('.version-pill');if(pill)pill.textContent='v4.1 · HISTORICAL LANDSCAPE';const foot=document.querySelector('footer span');if(foot)foot.textContent='WorldForge v4.1 · Historical Landscape & Architecture';document.title=`${w.name} · Worldbuilding Atelier · WorldForge v4.1`}
function schedule(force=false){state.force=state.force||force;if(state.raf)return;state.raf=requestAnimationFrame(()=>{const f=state.force;state.force=false;state.raf=0;render(f)})}
function exportLedger(){const w=world();if(!w)return;const data={version:'4.1',world:w.name,year:W.absYear(w),summary:W.summary(w),profiles:w.worldbuilding.profiles,annual:w.worldbuilding.annual.slice(-500),performance:W.performance(w)};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${String(w.name||'worldforge').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-worldbuilding-ledger-y${W.absYear(w)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const api={state,render,schedule};window.WorldForgeWorldbuildingUI=api;const observer=new MutationObserver(()=>schedule());observer.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule(true)});setInterval(()=>{if(!document.hidden)schedule()},6500);setTimeout(()=>schedule(true),1200);
})();