(() => {
'use strict';
const C=window.WorldForgeCulture,S=window.WorldForgeSociety;
if(!C||!S||!window.WorldRenderer)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c])),fmt=(n,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const ui={world:null,viewYear:null,selectedCultureId:null,selectedReligionId:null};
const baseSim=S.simulateYears.bind(S),baseTo=S.simulateTo?.bind(S);C.setBaseSimulator(baseSim);S.simulateYears=function(world,years,options){C.simulateYears(world,years,options);return world.society};S.simulateTo=function(world,target,options){C.simulateTo(world,target,options);return world.society};S.__worldforgeV07BaseSimulate=baseSim;S.__worldforgeV07BaseTo=baseTo;
function install(){document.title='WorldForge · v0.7 Cultures & Religions';const v=$('.version-pill');if(v)v.textContent='v0.7 · CULTURES & RELIGIONS';const f=document.querySelector('footer span');if(f)f.textContent='WorldForge v0.7 · Cultures & Religions';const sim=$('#simState');if(sim)sim.textContent='LIVING WORLD + CULTURE SIMULATION READY';const arch=$('.architecture-panel');if(arch){arch.querySelector('h2').textContent='v0.7 Cultures & Religions State Contract';arch.querySelector('.status-ready').textContent='CULTURE READY';arch.querySelector('.architecture-grid').innerHTML='<div><b>Cultures</b><span>Languages · traditions · values · prestige · cohesion · divergence</span></div><div><b>Religions</b><span>Doctrines · tenets · holy sites · fervor · authority · schisms</span></div><div><b>Diffusion</b><span>Migration · trade routes · political assimilation · conversion · local identity</span></div><div><b>Historical Integration</b><span>Cultural shifts and religious schisms become persistent chronicle events</span></div>';arch.querySelector('.help').textContent='v0.8 will add guilds, orders, cults, mercenary companies and political factions that recruit these persistent people and interact with culture, religion and state power.'}
 const marker=$('.history-charts-panel');if(marker&&!$('#culturePanel'))marker.insertAdjacentHTML('beforebegin',`<section id="culturePanel" class="panel culture-panel"><div class="panel-head"><div><span class="eyebrow">CULTURE & FAITH</span><h2>Civilizations Beyond Borders</h2></div><span id="cultureYear" class="badge">YEAR 0</span></div><div class="culture-kpis"><div><span>ACTIVE CULTURES</span><b id="cultureCount">—</b></div><div><span>ACTIVE RELIGIONS</span><b id="religionCount">—</b></div><div><span>CULTURAL SHIFTS</span><b id="cultureShifts">—</b></div><div><span>CONVERSIONS</span><b id="religionConversions">—</b></div><div><span>SCHISMS</span><b id="religionSchisms">—</b></div></div><p class="culture-note">Borders can change without erasing identity. Trade, migration, state pressure, tolerance and religious fervor shape cultures over centuries.</p></section><section class="panel culture-panel"><div class="panel-head"><div><span class="eyebrow">CULTURAL LEDGER</span><h2>Languages, Traditions & Values</h2></div></div><div class="culture-grid"><div id="cultureList" class="culture-list"></div><div id="cultureDetail" class="culture-detail"></div></div></section><section class="panel culture-panel"><div class="panel-head"><div><span class="eyebrow">RELIGIOUS LANDSCAPE</span><h2>Faiths, Holy Sites & Schisms</h2></div></div><div class="culture-grid"><div id="religionList" class="culture-list"></div><div id="religionDetail" class="culture-detail"></div></div></section>`);
 const ef=$('#eventFilter');if(ef){[['culture_shift','Cultural shifts'],['cultural_revival','Cultural revivals'],['conversion','Conversions'],['religious_schism','Religious schisms']].forEach(([value,text])=>{if(![...ef.options].some(o=>o.value===value)){const o=document.createElement('option');o.value=value;o.textContent=text;ef.appendChild(o)}})}
 $('#cultureList')?.addEventListener('click',e=>{const b=e.target.closest('[data-culture]');if(b){ui.selectedCultureId=Number(b.dataset.culture);render()}});$('#religionList')?.addEventListener('click',e=>{const b=e.target.closest('[data-religion]');if(b){ui.selectedReligionId=Number(b.dataset.religion);render()}})
}
function view(){if(!ui.world)return null;const y=ui.viewYear;return y==null||y>=ui.world.culture.currentYear?C.currentView(ui.world):C.viewAt(ui.world,y)}
function settlementCount(ids,id){let n=0;for(const x of ids)if(x===id)n++;return n}
function followers(v,id,kind){const ids=kind==='culture'?v.settlementCultureIds:v.settlementReligionIds;let p=0;ids.forEach((x,i)=>{if(x===id)p+=ui.world.history.current.settlementPopulation[i]||0});return p}
function render(){const v=view();if(!v||!$('#culturePanel'))return;$('#cultureYear').textContent=`YEAR ${v.year}`;$('#cultureCount').textContent=v.cultures.filter(x=>x.active).length;$('#religionCount').textContent=v.religions.filter(x=>x.active).length;$('#cultureShifts').textContent=fmt(v.stats.cultureShifts);$('#religionConversions').textContent=fmt(v.stats.conversions);$('#religionSchisms').textContent=fmt(v.stats.schisms);const cultures=v.cultures.filter(x=>x.active).sort((a,b)=>followers(v,b.id,'culture')-followers(v,a.id,'culture'));if(ui.selectedCultureId==null||!cultures.some(x=>x.id===ui.selectedCultureId))ui.selectedCultureId=cultures[0]?.id??null;$('#cultureList').innerHTML=cultures.map(x=>`<button data-culture="${x.id}" class="culture-card ${x.id===ui.selectedCultureId?'active':''}"><i style="background:${x.color}"></i><div><span>${esc(x.languageFamily)}</span><h3>${esc(x.name)}</h3><small>${fmt(followers(v,x.id,'culture'))} people · ${settlementCount(v.settlementCultureIds,x.id)} settlements</small></div><strong>${fmt(x.prestige)}</strong></button>`).join('');const c=cultures.find(x=>x.id===ui.selectedCultureId);$('#cultureDetail').innerHTML=c?`<span class="eyebrow">${esc(c.languageFamily.toUpperCase())}</span><h2>${esc(c.name)}</h2><p><b>Language:</b> ${esc(c.language)}</p><div class="culture-stat-grid"><div><span>Prestige</span><b>${fmt(c.prestige)}/160</b></div><div><span>Cohesion</span><b>${fmt(c.cohesion)}/100</b></div><div><span>Founded</span><b>Year ${c.foundedYear}</b></div><div><span>Parent</span><b>${c.parentId==null?'Independent':esc(v.cultures[c.parentId]?.name||'Unknown')}</b></div></div><h3>Traditions</h3><div class="culture-tags">${c.traditions.map(x=>`<span>${esc(x)}</span>`).join('')}</div><h3>Core values</h3><div class="culture-tags">${c.values.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:'<div class="empty">No culture selected.</div>';
 const religions=v.religions.filter(x=>x.active).sort((a,b)=>followers(v,b.id,'religion')-followers(v,a.id,'religion'));if(ui.selectedReligionId==null||!religions.some(x=>x.id===ui.selectedReligionId))ui.selectedReligionId=religions[0]?.id??null;$('#religionList').innerHTML=religions.map(x=>`<button data-religion="${x.id}" class="culture-card ${x.id===ui.selectedReligionId?'active':''}"><i style="background:${x.color}"></i><div><span>${esc(x.doctrine)}</span><h3>${esc(x.name)}</h3><small>${fmt(followers(v,x.id,'religion'))} followers · ${settlementCount(v.settlementReligionIds,x.id)} settlements</small></div><strong>${fmt(x.fervor)}</strong></button>`).join('');const r=religions.find(x=>x.id===ui.selectedReligionId);$('#religionDetail').innerHTML=r?`<span class="eyebrow">${esc(r.doctrine.toUpperCase())}</span><h2>${esc(r.name)}</h2><div class="culture-stat-grid"><div><span>Fervor</span><b>${fmt(r.fervor)}/100</b></div><div><span>Authority</span><b>${fmt(r.authority)}/100</b></div><div><span>Founded</span><b>Year ${r.foundedYear}</b></div><div><span>Parent faith</span><b>${r.parentId==null?'Independent':esc(v.religions[r.parentId]?.name||'Unknown')}</b></div></div><h3>Tenets</h3><div class="culture-tags">${r.tenets.map(x=>`<span>${esc(x)}</span>`).join('')}</div><h3>Holy sites</h3><div class="culture-tags">${r.holySiteIds.map(id=>`<span>${esc(ui.world.settlements[id]?.name||`Site ${id}`)}</span>`).join('')}</div>`:'<div class="empty">No religion selected.</div>'}
install();const proto=window.WorldRenderer.prototype,oldSetWorld=proto.setWorld,oldSetHistoryView=proto.setHistoryView;proto.setWorld=function(world){ui.world=world;C.initialize(world);const r=oldSetWorld.call(this,world);ui.viewYear=null;render();return r};proto.setHistoryView=function(v){const r=oldSetHistoryView.call(this,v);if(this.world){ui.world=this.world;ui.viewYear=v?.year??null;render()}return r};window.WorldForgeCultureUI={version:'0.7.0',render,state:ui};
})();