(function(root,factory){
  const api=factory(root&&root.WorldForgeEngine,root&&root.WorldForgeHistory,root&&root.WorldForgeSociety,root&&root.WorldForgeCity);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeAdventure=api;
})(typeof window!=='undefined'?window:globalThis,function(Core,History,Society,City){
'use strict';
const VERSION='0.5.0',ADVENTURE_SCHEMA=1;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=1)=>Number(Number(v).toFixed(d));
const capturedCitySimulate=City&&City.simulateYears?City.simulateYears.bind(City):null;
const KINDS=['Ancient Ruin','Forgotten Crypt','Cavern','Abandoned Mine','Ruined Keep','Sunken Shrine','Bandit Den','Gang Hideout','Buried Temple','Battlefield Catacomb'];
const ROOM_KINDS=['Passage','Guard Post','Chamber','Collapsed Hall','Store Room','Shrine','Trap Room','Barracks','Flooded Room','Library','Workshop'];
const ENEMIES=['bandits','grave robbers','feral beasts','restless dead','cultists','mercenaries','smugglers','cave predators','deserters','ancient guardians'];
const LOOT=['Coin Cache','Old Arms','Trade Goods','Dynastic Seal','Relic Fragment','Gemstones','Contraband Crate','Ancient Manuscript','Ceremonial Blade','Lost Charter','Silver Idol','Masterwork Tool'];
function fallbackRng(seed){let h=2166136261>>>0;for(const ch of String(seed)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return function(){h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function rngFor(world,year,salt=''){return(Core?.rngFromSeed||fallbackRng)(`${world.settings.seed}|ADVENTURE|${year}|${salt}`)}
function pick(rng,a){return a[Math.floor(rng()*a.length)]}
function history(world){if(!History)throw new Error('WorldForgeHistory required');return History.initialize(world)}
function city(world){if(!City)throw new Error('WorldForgeCity required');return City.initialize(world)}
function society(world){if(!Society)throw new Error('WorldForgeSociety required');return Society.initialize(world)}
function fullName(world,id){const p=world.society?.people?.[id];return p?Society.fullName(world.society,p):null}
function ownerAt(world,sid){return world.history.current.settlementKingdomIds[sid]}
function eventOrigin(world,e){if(!e)return null;const sid=e.settlementIds?.[0];return Number.isInteger(sid)?sid:null}
function suitableEvent(e){return ['war','conquest','collapse','realm_formed','famine','gang_formed','gang_war','gang_dissolved','smuggling','crackdown','succession_crisis'].includes(e.type)}
function eventKind(e,rng){if(!e)return pick(rng,KINDS);if(e.type==='gang_formed'||e.type==='gang_war'||e.type==='smuggling'||e.type==='gang_dissolved')return'Gang Hideout';if(e.type==='war'||e.type==='conquest')return pick(rng,['Ruined Keep','Battlefield Catacomb','Forgotten Crypt']);if(e.type==='collapse'||e.type==='realm_formed'||e.type==='succession_crisis')return pick(rng,['Ruined Keep','Buried Temple','Forgotten Crypt']);if(e.type==='famine')return pick(rng,['Abandoned Mine','Forgotten Crypt']);return pick(rng,KINDS)}
function siteName(world,kind,sid,rng){const place=world.settlements[sid]?.name||'Unknown';const a=['Black','Ashen','Silent','Broken','Old','Hollow','Forgotten','Gilded','Drowned','Iron','Moonlit','Grim'];const b=kind==='Gang Hideout'?['Cellar','Den','Vault','Warren']:kind.includes('Keep')?['Keep','Fort','Hold']:kind.includes('Mine')?['Mine','Shaft','Delve']:kind.includes('Crypt')||kind.includes('Catacomb')?['Crypt','Tombs','Catacombs']:kind.includes('Temple')||kind.includes('Shrine')?['Shrine','Sanctum','Temple']:kind==='Cavern'?['Caverns','Hollows','Caves']:['Ruin','Vault','Halls'];return`${pick(rng,a)} ${pick(rng,b)} of ${place}`}
function roomGraph(rng,danger){const n=clamp(5+Math.floor(rng()*7)+Math.floor(danger/35),5,14),rooms=[];for(let i=0;i<n;i++){let kind=i===0?'Entrance':i===n-1?'Boss Chamber':pick(rng,ROOM_KINDS);rooms.push({id:i,kind,name:kind,depth:i===0?0:Math.floor(1+Math.log2(i+1)),danger:round(clamp(danger+(rng()-.5)*26+(i/n)*18,1,100)),secret:false,trap:false,lootIds:[],encounter:null})}const edges=[];for(let i=1;i<n;i++){const parent=Math.max(0,Math.floor(rng()*i));edges.push([parent,i])}for(let i=2;i<n-1;i++)if(rng()<.22)edges.push([i,Math.floor(rng()*i)]);for(const r of rooms.slice(1,-1)){r.secret=rng()<.13;r.trap=rng()<.18;if(rng()<.68)r.encounter=pick(rng,ENEMIES)}rooms[n-1].encounter=pick(rng,ENEMIES);return{rooms,edges}}
function buildLoot(rng,danger,roomCount){const count=clamp(2+Math.floor(roomCount/3)+Math.floor(rng()*3),3,9),out=[];for(let i=0;i<count;i++){const rarityRoll=rng()+danger/170,rarity=rarityRoll>1.25?'legendary':rarityRoll>.93?'rare':rarityRoll>.58?'uncommon':'common';out.push({id:i,name:pick(rng,LOOT),rarity,value:Math.round((30+rng()*110)*(1+danger/70)*(rarity==='legendary'?3.2:rarity==='rare'?2:rarity==='uncommon'?1.35:1)),roomId:null})}return out}
function placeLoot(rng,graph,loot){const candidates=graph.rooms.filter(r=>r.id!==0);for(const item of loot){const r=pick(rng,candidates);item.roomId=r.id;r.lootIds.push(item.id)}}
function loreFor(world,e,kind,sid,gangId){const place=world.settlements[sid]?.name||'the region',year=e?.year??0;if(gangId!=null){const g=world.cities?.gangs?.[gangId];return`Rumors tie this site near ${place} to the ${g?.name||'local underworld'}, whose activity was recorded around Year ${year}.`}if(e)return`The site is linked to the Year ${year} chronicle entry “${e.title}”. Later generations turned that memory into warnings, scavenger tales and half-preserved local lore.`;return`A remote site near ${place}, older than reliable local records. Its surviving structure hints at repeated occupation and abandonment.`}
function createSite(world,a,{sid,event=null,gangId=null,year=null,salt=''}){const y=year??world.history.currentYear,rng=rngFor(world,y,`site-${a.sites.length}-${sid}-${event?.id??'seed'}-${salt}`),kind=eventKind(event,rng),danger=round(clamp(18+rng()*48+(event?.importance||0)*8+(kind==='Gang Hideout'?8:0),5,96)),graph=roomGraph(rng,danger),loot=buildLoot(rng,danger,graph.rooms.length);placeLoot(rng,graph,loot);const sourcePersonIds=(event?.personIds||[]).slice(0,3);const site={id:a.sites.length,name:siteName(world,kind,sid,rng),kind,settlementId:sid,realmId:ownerAt(world,sid),originYear:event?.year??Math.max(0,y-Math.floor(rng()*180)),sourceEventId:event?.id??null,gangId,active:true,discovered:rng()<.38,danger,depth:Math.max(...graph.rooms.map(r=>r.depth)),rumor:round(rng()*100),rooms:graph.rooms,edges:graph.edges,loot,sourcePersonIds,lore:loreFor(world,event,kind,sid,gangId),visits:0,clears:0,lastChangeYear:y};a.sites.push(site);a.stats.sitesCreated++;a.stats.roomsGenerated+=site.rooms.length;a.stats.lootGenerated+=site.loot.length;return site}
function seedSites(world,a,year){const rng=rngFor(world,year,'seed-sites'),events=world.history.events.filter(suitableEvent);const used=new Set();for(const e of events.slice(-18)){const sid=eventOrigin(world,e);if(Number.isInteger(sid)&&!used.has(e.id)){createSite(world,a,{sid,event:e,gangId:e.gangIds?.[0]??null,year});used.add(e.id)}}for(const c of world.cities.cities){const urban=['Capital','City'].includes(c.type),chance=urban?.42:c.type==='Town'?.24:.10;if(rng()<chance)createSite(world,a,{sid:c.id,year,salt:'seed'});}for(const g of world.cities.gangs.filter(g=>g.active))if(!a.sites.some(s=>s.gangId===g.id)&&rng()<.55)createSite(world,a,{sid:g.cityId,gangId:g.id,year,salt:'gang'})}
function initialize(world,options={}){history(world);society(world);city(world);if(world.adventure&&world.adventure.schemaVersion===ADVENTURE_SCHEMA){normalize(world,world.adventure);return world.adventure}const year=world.history.currentYear,a={schemaVersion:ADVENTURE_SCHEMA,engineVersion:VERSION,startYear:year,currentYear:year,sites:[],snapshots:[],processedEventIds:[],stats:{sitesCreated:0,sitesLost:0,roomsGenerated:0,lootGenerated:0,discoveries:0,rumors:0,expeditions:0,clears:0}};world.adventure=a;seedSites(world,a,year);a.processedEventIds=world.history.events.filter(suitableEvent).map(e=>e.id);recompute(world,a,year);takeSnapshot(world,a,true);return a}
function normalize(world,a){a.engineVersion=VERSION;a.sites=a.sites||[];a.snapshots=a.snapshots||[];a.processedEventIds=a.processedEventIds||[];a.stats={sitesCreated:0,sitesLost:0,roomsGenerated:0,lootGenerated:0,discoveries:0,rumors:0,expeditions:0,clears:0,...a.stats};return a}
function pushEvent(world,e){const h=history(world);h.events.push({id:h.events.length,year:h.currentYear,...e})}
function processNewHistory(world,a,year){const known=new Set(a.processedEventIds);for(const e of world.history.events){if(known.has(e.id)||!suitableEvent(e))continue;a.processedEventIds.push(e.id);known.add(e.id);const sid=eventOrigin(world,e);if(!Number.isInteger(sid))continue;const rng=rngFor(world,year,`event-site-${e.id}`),chance=e.importance>=3?.72:e.type.startsWith('gang')?.48:.28;if(rng()<chance){const s=createSite(world,a,{sid,event:e,gangId:e.gangIds?.[0]??null,year});if(s.discovered)pushEvent(world,{type:'site_discovered',importance:1,settlementIds:[sid],personIds:s.sourcePersonIds,siteIds:[s.id],title:`Rumors spread of ${s.name}`,text:`Travelers near ${world.settlements[sid].name} begin speaking openly of ${s.kind.toLowerCase()} remains.`})}}}
function updateSites(world,a,year){for(const s of a.sites){if(!s.active)continue;const rng=rngFor(world,year,`site-update-${s.id}`),cv=world.cities.cities[s.settlementId],gang=s.gangId!=null?world.cities.gangs[s.gangId]:null;if(s.gangId!=null&&gang&&!gang.active&&rng()<.18){s.active=false;s.lastChangeYear=year;a.stats.sitesLost++;continue}s.realmId=ownerAt(world,s.settlementId);const pressure=(cv?.crimeRate||20)*.12+(cv?.blackMarket||20)*.08+(world.history.current.activeWarIds.length?3:0);s.danger=round(clamp(s.danger*.94+(15+pressure+rng()*30)*.06,3,100));s.rumor=round(clamp(s.rumor+(rng()-.45)*7+(s.discovered?1.2:0),0,100));if(!s.discovered&&s.rumor>58&&rng()<.09){s.discovered=true;s.lastChangeYear=year;a.stats.discoveries++;pushEvent(world,{type:'site_discovered',importance:1,realmIds:[s.realmId],settlementIds:[s.settlementId],siteIds:[s.id],title:`${s.name} is charted`,text:`Local guides confirm the location of the ${s.kind.toLowerCase()} near ${world.settlements[s.settlementId].name}.`})}if(s.discovered&&rng()<.025){a.stats.expeditions++;s.visits++;if(rng()<clamp(.18+(80-s.danger)/180,.08,.55)){s.clears++;a.stats.clears++;s.danger=round(Math.max(2,s.danger-(8+rng()*16)));pushEvent(world,{type:'expedition',importance:1,realmIds:[s.realmId],settlementIds:[s.settlementId],siteIds:[s.id],title:`Expedition returns from ${s.name}`,text:`A local expedition survives the site and reduces its immediate danger.`})}}}}
function recompute(world,a,year){a.currentYear=year;for(const s of a.sites)if(s.active)s.realmId=ownerAt(world,s.settlementId)}
function metric(a){const active=a.sites.filter(s=>s.active),known=active.filter(s=>s.discovered);return{sites:active.length,known:known.length,meanDanger:round(active.reduce((n,s)=>n+s.danger,0)/Math.max(1,active.length)),rooms:active.reduce((n,s)=>n+s.rooms.length,0),legendaryLoot:active.reduce((n,s)=>n+s.loot.filter(i=>i.rarity==='legendary').length,0),expeditions:a.stats.expeditions,clears:a.stats.clears}}
function takeSnapshot(world,a,force=false){const interval=world.history.snapshotInterval||5;if(!force&&a.currentYear%interval!==0)return null;const snap={year:a.currentYear,sites:a.sites.map(s=>[s.id,s.active?1:0,s.discovered?1:0,round(s.danger),round(s.rumor),s.realmId,s.visits,s.clears]),stats:metric(a),eventIndex:world.history.events.length};const last=a.snapshots[a.snapshots.length-1];if(last?.year===snap.year)a.snapshots[a.snapshots.length-1]=snap;else a.snapshots.push(snap);return snap}
function simulateAdventureYear(world,a,year){a.currentYear=year;processNewHistory(world,a,year);updateSites(world,a,year);recompute(world,a,year);takeSnapshot(world,a,false)}
function compactSnapshots(world,a){const interval=world.history.snapshotInterval||5,current=a.currentYear,by=new Map();for(const s of a.snapshots)if(s.year===a.startYear||s.year%interval===0||s.year===current)by.set(s.year,s);a.snapshots=[...by.values()].sort((x,y)=>x.year-y.year)}
function simulateYears(world,years,options={}){const a=initialize(world,options),h=history(world),n=clamp(Math.round(Number(years)||0),0,5000),target=clamp(h.currentYear+n,0,5000);if(!capturedCitySimulate)throw new Error('City simulation unavailable');if(a.currentYear!==h.currentYear){a.currentYear=h.currentYear;takeSnapshot(world,a,true)}while(h.currentYear<target){capturedCitySimulate(world,1,options);simulateAdventureYear(world,a,h.currentYear)}compactSnapshots(world,a);takeSnapshot(world,a,true);return a}
function simulateTo(world,targetYear,options={}){const h=history(world),target=clamp(Math.round(Number(targetYear)||0),h.currentYear,5000);return simulateYears(world,target-h.currentYear,options)}
function snapshotAt(world,year){const a=initialize(world),target=clamp(Math.round(Number(year)||0),a.startYear,a.currentYear);let best=a.snapshots[0];for(const s of a.snapshots)if(s.year<=target&&s.year>=best.year)best=s;return best}
function viewFromSnapshot(world,a,snap){const sites=snap.sites.map(r=>{const b=a.sites[r[0]];return{id:b.id,name:b.name,kind:b.kind,settlementId:b.settlementId,originYear:b.originYear,sourceEventId:b.sourceEventId,gangId:b.gangId,active:!!r[1],discovered:!!r[2],danger:r[3],rumor:r[4],realmId:r[5],visits:r[6],clears:r[7],roomCount:b.rooms.length,depth:b.depth,lore:b.lore,sourcePersonIds:b.sourcePersonIds}});return{year:snap.year,isPresent:snap.year===a.currentYear,sites,stats:{...snap.stats}}}
function currentView(world){const a=initialize(world),snap={year:a.currentYear,sites:a.sites.map(s=>[s.id,s.active?1:0,s.discovered?1:0,round(s.danger),round(s.rumor),s.realmId,s.visits,s.clears]),stats:metric(a)};return viewFromSnapshot(world,a,snap)}
function viewAt(world,year){const a=initialize(world);if(year>=a.currentYear)return currentView(world);return viewFromSnapshot(world,a,snapshotAt(world,year))}
function dungeonDetail(world,id,year=null){const a=initialize(world),view=year==null?currentView(world):viewAt(world,year),v=view.sites.find(s=>s.id===Number(id)),base=a.sites[Number(id)];if(!v||!base)return null;return{...base,...v,rooms:base.rooms.map(r=>({...r})),edges:base.edges.map(e=>[...e]),loot:base.loot.map(x=>({...x})),sourcePeople:base.sourcePersonIds.map(id=>fullName(world,id)).filter(Boolean)}}
function adventureFingerprint(world){const a=initialize(world),rows=a.sites.map(s=>`${s.id}:${s.active?1:0}:${s.discovered?1:0}:${Math.round(s.danger)}:${s.rooms.length}:${s.loot.length}:${s.clears}`).join('|');let h=2166136261>>>0;for(const ch of`${a.currentYear}|${a.stats.sitesCreated}|${a.stats.discoveries}|${a.stats.expeditions}|${a.stats.clears}|${rows}`){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function validateAdventure(world){const errors=[],a=world?.adventure;if(!a||a.schemaVersion!==ADVENTURE_SCHEMA)return['adventure schema'];if(a.currentYear!==world.history?.currentYear)errors.push('adventure/history year mismatch');if(a.currentYear!==world.cities?.currentYear)errors.push('adventure/city year mismatch');for(const s of a.sites){if(!world.settlements[s.settlementId])errors.push('site settlement');if(!s.rooms?.length||s.rooms[0]?.kind!=='Entrance')errors.push('site rooms');if(!s.edges?.length)errors.push('room graph');const ids=new Set(s.rooms.map(r=>r.id));for(const [x,y] of s.edges)if(!ids.has(x)||!ids.has(y))errors.push('room edge');for(const l of s.loot||[])if(!ids.has(l.roomId))errors.push('loot room')}if(!a.snapshots.length||a.snapshots[a.snapshots.length-1].year!==a.currentYear)errors.push('adventure present snapshot');return[...new Set(errors)]}
return{VERSION,ADVENTURE_SCHEMA,initialize,simulateYears,simulateTo,currentView,viewAt,snapshotAt,dungeonDetail,adventureFingerprint,validateAdventure};
});