(() => {
'use strict';
const E=window.WorldForgeEngine,H=window.WorldForgeHistory,S=window.WorldForgeSociety;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const state={world:null,renderer:null,mode:'political',viewYear:null,charts:{},playing:false,playTimer:null,selectedPersonId:null};

function toast(text){const t=$('#toast');t.textContent=text;t.style.opacity='1';clearTimeout(t._x);t._x=setTimeout(()=>t.style.opacity='0',1800)}
function settingsFromUI(){return{seed:$('#seedInput').value.trim()||'WORLD',width:Number($('#widthInput').value),height:Number($('#heightInput').value),seaLevel:Number($('#seaLevelInput').value),age:$('#ageInput').value,settlementTarget:Number($('#settlementInput').value),kingdomTarget:Number($('#kingdomInput').value)}}
function randomSeed(){const a=['ASH','EMBER','IVORY','THORN','SILVER','RAVEN','MOON','CINDER','FROST','GOLDEN','HOLLOW','STAR'],b=['CROWN','VALE','SPIRE','REACH','WILD','MARCH','REALM','FALL','WATCH','TIDE','STONE','DAWN'];return`${a[Math.floor(Math.random()*a.length)]}-${b[Math.floor(Math.random()*b.length)]}-${Math.floor(10+Math.random()*90)}`}
function updateRangeLabels(){$('#seaLevelValue').textContent=Number($('#seaLevelInput').value).toFixed(2);$('#settlementValue').textContent=$('#settlementInput').value;$('#kingdomValue').textContent=$('#kingdomInput').value}
function ensureSystems(){if(!state.world)return;H.initialize(state.world);S.initialize(state.world)}
function getView(){if(!state.world)return null;ensureSystems();return state.viewYear==null?H.currentView(state.world):H.viewAt(state.world,state.viewYear)}
function getSocietyView(){if(!state.world)return null;ensureSystems();return state.viewYear==null?S.currentView(state.world):S.viewAt(state.world,state.viewYear)}
function getRealm(view,id){return view?.realms?.find(r=>r.id===id)||null}
function eraName(year){if(year<100)return'Founding Age';if(year<250)return'Age of Roads';if(year<500)return'Age of Crowns';if(year<1000)return'High Chronicle';if(year<1500)return'Late Age';return'Age of Legends'}
function personName(id){const p=state.world?.society?.people?.[id];return p?S.fullName(state.world.society,p):'Unknown'}
function narrative(w,view,sv){const b=E.BIOMES[w.summary.dominantBiome]?.label||w.summary.dominantBiome,largest=[...view.realms].filter(r=>r.active).sort((a,b)=>b.population-a.population)[0],tense=view.isPresent?'stands':'stood';return`<b>${esc(w.name)}</b> ${tense} in <b>Year ${view.year}</b> of the ${esc(eraName(view.year))}. ${fmt(view.metrics.population)} recorded inhabitants occupy ${w.settlements.length} tracked settlements across ${view.metrics.activeRealms} active realms. The largest realm by population is <b>${esc(largest?.name||'none')}</b>. ${fmt(sv.stats.livingNotables)} notable people and ${fmt(sv.stats.houses)} active dynastic houses are tracked. Trade index: <b>${fmt(view.metrics.trade,0)}</b>; active wars: <b>${view.metrics.activeWars}</b>. The world remains geographically dominated by <b>${esc(b)}</b>.`}
function renderBiomeBars(w){const host=$('#biomeBars'),land=w.summary.landTiles,rows=Object.entries(w.summary.biomes).filter(([k])=>!['ocean','deepOcean'].includes(k)).sort((a,b)=>b[1]-a[1]).slice(0,7);host.innerHTML=rows.map(([k,v])=>{const p=v/land*100;return`<div class="biome-row"><span>${esc(E.BIOMES[k]?.label||k)}</span><i><b style="width:${p.toFixed(1)}%"></b></i><strong>${p.toFixed(1)}%</strong></div>`}).join('')}
function renderKingdoms(view,sv){const w=state.world;$('#kingdomList').innerHTML=view.realms.filter(r=>r.formedYear<=view.year).sort((a,b)=>(b.active-a.active)||b.population-a.population).map(k=>{const c=w.settlements[k.capitalId],status=k.active?'ACTIVE':`ENDED ${k.collapsedYear??'?'}`,t=sv.titles.find(t=>t.realmId===k.id&&t.active),ruler=t?.holderId!=null?personName(t.holderId):'—';return`<article class="kingdom-card ${k.active?'':'realm-ended'}" data-settlement="${c?.id??''}"><h3><i class="realm-dot" style="background:${k.color}"></i>${esc(k.name)}</h3><dl><dt>Status</dt><dd>${status}</dd><dt>Ruler</dt><dd>${esc(ruler)}</dd><dt>Capital</dt><dd>${esc(c?.name||'—')}</dd><dt>Settlements</dt><dd>${k.settlementCount}</dd><dt>Population</dt><dd>${fmt(k.population)}</dd><dt>Stability</dt><dd>${fmt(k.stability,0)}/100</dd></dl></article>`}).join('')||'<div class="empty">No realms at this date.</div>';const old=$('#settlementFilter').value;$('#settlementFilter').innerHTML='<option value="all">All realms</option>'+view.realms.filter(r=>r.formedYear<=view.year).map(k=>`<option value="${k.id}">${esc(k.shortName)}</option>`).join('');if([...$('#settlementFilter').options].some(o=>o.value===old))$('#settlementFilter').value=old}
function renderSettlements(view=getView()){const w=state.world;if(!w||!view)return;const filter=$('#settlementFilter').value,sort=$('#settlementSort').value;let rows=[...w.settlements];if(filter!=='all')rows=rows.filter(s=>view.settlementKingdomIds[s.id]===Number(filter));rows.sort(sort==='population'?(a,b)=>view.settlementPopulation[b.id]-view.settlementPopulation[a.id]:sort==='name'?(a,b)=>a.name.localeCompare(b.name):(a,b)=>view.settlementProsperity[b.id]-view.settlementProsperity[a.id]);$('#settlementTable').innerHTML=rows.map(s=>{const kid=view.settlementKingdomIds[s.id],k=getRealm(view,kid),biome=E.BIOMES[w.layers.biome[s.y*w.settings.width+s.x]]?.label||'—',capital=view.realms.some(r=>r.active&&r.capitalId===s.id);return`<tr data-settlement="${s.id}"><td class="place-name">${capital?'★ ':''}${esc(s.name)}</td><td><span style="color:${k?.color||'#aaa'}">●</span> ${esc(k?.shortName||'Unruled')}</td><td>${capital?'Capital':s.type}</td><td>${esc(biome)}</td><td>${fmt(view.settlementPopulation[s.id])}</td><td>${fmt(view.settlementProsperity[s.id]*100,0)}%</td></tr>`}).join('')||'<tr><td colspan="6" class="empty">No settlements match this filter.</td></tr>'}
function renderLegend(view=getView()){const host=$('#legend');if(!state.world||!view)return;if(state.mode==='political')host.innerHTML=view.realms.filter(r=>r.active).map(k=>`<span><i style="background:${k.color}"></i>${esc(k.shortName)}</span>`).join('')+'<span><i style="background:#e5e0c7;border-radius:50%"></i>Settlement</span><span><i style="background:#6ba3b5"></i>River</span>';else if(state.mode==='biome')host.innerHTML=Object.values(E.BIOMES).map(b=>`<span><i style="background:${b.color}"></i>${esc(b.label)}</span>`).join('');else if(state.mode==='elevation')host.innerHTML='<span><i style="background:#143346"></i>Deep</span><span><i style="background:#2f7684"></i>Shallow</span><span><i style="background:#53713f"></i>Lowland</span><span><i style="background:#eef1ea"></i>Peak</span>';else if(state.mode==='temperature')host.innerHTML='<span><i style="background:#4d7fb7"></i>Cold</span><span><i style="background:#a9897e"></i>Temperate</span><span><i style="background:#d86b48"></i>Hot</span>';else if(state.mode==='moisture')host.innerHTML='<span><i style="background:#c7a55a"></i>Dry</span><span><i style="background:#7c9470"></i>Moderate</span><span><i style="background:#3d7f6f"></i>Wet</span>';else if(state.mode==='population')host.innerHTML='<span><i style="background:#263632"></i>Lower realm density</span><span><i style="background:#e1a657"></i>Higher realm density</span>';else if(state.mode==='prosperity')host.innerHTML='<span><i style="background:#6a3f35"></i>Stressed</span><span><i style="background:#63a86c"></i>Prosperous</span>';else host.innerHTML='<span><i style="background:#6f5a34"></i>Low trade</span><span><i style="background:#f7cb69"></i>High road trade</span>'}
function renderHistoryKPIs(view){$('#currentYear').textContent=`YEAR ${view.year}`;$('#eraLabel').textContent=eraName(view.year);$('#historyPopulation').textContent=fmt(view.metrics.population);$('#historyTrade').textContent=fmt(view.metrics.trade,0);$('#historyWars').textContent=view.metrics.activeWars;$('#historyRealms').textContent=view.metrics.activeRealms;$('#historyProsperity').textContent=fmt(view.metrics.meanProsperity*100,0)+'%';$('#timelineYear').textContent=`Year ${view.year}`;$('#timelineSlider').max=state.world.history.currentYear;$('#timelineSlider').step=state.world.history.snapshotInterval;$('#timelineSlider').value=view.year;$('#presentBtn').disabled=view.isPresent;$('#viewModeBadge').textContent=view.isPresent?'PRESENT':'HISTORICAL VIEW';$('#viewModeBadge').className='badge '+(view.isPresent?'':'historical')}
function eventIcon(t){return({war:'⚔',peace:'☮',conquest:'⚑',alliance:'◆',realm_formed:'✦',collapse:'✕',crisis:'!',famine:'⌁',trade_boom:'↑',era:'◷',founding:'◎',diplomacy:'◇',succession:'♛',succession_crisis:'⚡',marriage:'♡',death:'†',birth:'✧',dynasty_founded:'♜'}[t]||'•')}
function renderChronicle(view){const filter=$('#eventFilter').value,events=H.eventsThrough(state.world,view.year,320).filter(e=>filter==='all'||e.type===filter).slice().reverse();$('#chronicleList').innerHTML=events.map(e=>{const figures=(e.personIds||[]).slice(0,4).map(personName).filter(Boolean);return`<article class="event-card importance-${e.importance||1}"><div class="event-icon">${eventIcon(e.type)}</div><div><span>YEAR ${e.year} · ${esc(String(e.type).replaceAll('_',' ').toUpperCase())}</span><h3>${esc(e.title)}</h3><p>${esc(e.text)}</p>${figures.length?`<small class="event-figures">Figures: ${figures.map(esc).join(' · ')}</small>`:''}</div></article>`}).join('')||'<div class="empty">No matching events in the chronicle yet.</div>'}
function renderWars(view){const wars=state.world.history.wars.filter(w=>w.startYear<=view.year&&(w.endYear==null||w.endYear>=view.year));$('#warList').innerHTML=wars.length?wars.map(w=>{const a=getRealm(view,w.attackerId)||state.world.history.realms[w.attackerId],b=getRealm(view,w.defenderId)||state.world.history.realms[w.defenderId],status=w.endYear==null||w.endYear>view.year?'ACTIVE':`ENDED ${w.endYear}`;return`<div class="war-row"><div><b>${esc(a?.shortName||'?')} <span>vs</span> ${esc(b?.shortName||'?')}</b><small>${esc(w.cause)} · ${status}</small></div><strong>${w.captures.length} captures</strong></div>`}).join(''):'<div class="empty">No wars active in this viewed year.</div>'}
function renderDiplomacy(view){const realms=view.realms.filter(r=>r.active).slice(0,12),pairs=[];for(let i=0;i<realms.length;i++)for(let j=i+1;j<realms.length;j++){const a=realms[i],b=realms[j],key=a.id<b.id?`${a.id}:${b.id}`:`${b.id}:${a.id}`,rel=Number(view.relations[key]??0),war=view.activeWars.some(w=>((w.attackerId===a.id&&w.defenderId===b.id)||(w.attackerId===b.id&&w.defenderId===a.id))),allied=view.alliances.includes(key);pairs.push({a,b,rel,war,allied})}pairs.sort((x,y)=>(y.war-x.war)||Math.abs(y.rel)-Math.abs(x.rel));$('#diplomacyList').innerHTML=pairs.slice(0,18).map(p=>`<div class="relation-row"><span><i style="background:${p.a.color}"></i>${esc(p.a.shortName)}</span><b class="${p.war?'hostile':p.allied?'allied':p.rel<-35?'hostile':p.rel>45?'friendly':''}">${p.war?'WAR':p.allied?'ALLIANCE':p.rel>0?`+${fmt(p.rel,0)}`:fmt(p.rel,0)}</b><span><i style="background:${p.b.color}"></i>${esc(p.b.shortName)}</span></div>`).join('')||'<div class="empty">Not enough active realms for diplomacy.</div>'}
function chartOptions(label){return{responsive:true,maintainAspectRatio:false,animation:false,interaction:{mode:'index',intersect:false},plugins:{legend:{labels:{color:'#c9d3c3',boxWidth:12}}},scales:{x:{ticks:{color:'#7f9081'},grid:{color:'rgba(160,180,150,.09)'},title:{display:true,text:'Year',color:'#78877a'}},y:{ticks:{color:'#7f9081'},grid:{color:'rgba(160,180,150,.09)'},title:{display:true,text:label,color:'#78877a'}}}}}
function renderCharts(view){if(!window.Chart)return;const series=H.metricsSeries(state.world),labels=series.map(s=>s.year),pop=series.map(s=>s.population),trade=series.map(s=>s.trade),wars=series.map(s=>s.activeWars),marker=series.map(s=>s.year===view.year?s.population:null);if(!state.charts.population)state.charts.population=new Chart($('#populationChart'),{type:'line',data:{labels,datasets:[{label:'Population',data:pop,borderColor:'#d7b36c',backgroundColor:'rgba(215,179,108,.11)',fill:true,tension:.2,pointRadius:0},{label:'Viewed year',data:marker,borderColor:'#f4efe0',backgroundColor:'#f4efe0',pointRadius:5,showLine:false}]},options:chartOptions('Population')});else{const c=state.charts.population;c.data.labels=labels;c.data.datasets[0].data=pop;c.data.datasets[1].data=marker;c.update('none')}if(!state.charts.trade){const opt=chartOptions('Trade index');opt.scales.y2={position:'right',ticks:{color:'#9b7f7b',precision:0},grid:{display:false},title:{display:true,text:'Active wars',color:'#9b7f7b'},min:0};state.charts.trade=new Chart($('#tradeChart'),{data:{labels,datasets:[{type:'line',label:'Trade index',data:trade,borderColor:'#72a983',backgroundColor:'rgba(114,169,131,.1)',fill:true,tension:.2,pointRadius:0,yAxisID:'y'},{type:'bar',label:'Active wars',data:wars,backgroundColor:'rgba(196,86,75,.46)',yAxisID:'y2'}]},options:opt})}else{const c=state.charts.trade;c.data.labels=labels;c.data.datasets[0].data=trade;c.data.datasets[1].data=wars;c.update('none')}}
function societyPersonInView(sv,id){return sv.living.find(p=>p.id===id)||null}
function renderSocietyKPIs(sv){$('#societyLiving').textContent=fmt(sv.stats.livingNotables);$('#societyHouses').textContent=fmt(sv.stats.houses);$('#societyRulers').textContent=fmt(sv.stats.activeTitles);$('#societySuccessions').textContent=fmt(sv.stats.successions);$('#societyCrises').textContent=fmt(sv.stats.crises);$('#societyYearBadge').textContent=`YEAR ${sv.year}`}
function realmNameFallback(id){return state.world.history.realms[id]?.shortName||`Realm ${id}`}
function renderThrones(view,sv){$('#throneList').innerHTML=sv.titles.filter(t=>t.active).sort((a,b)=>a.realmId-b.realmId).map(t=>{const realm=getRealm(view,t.realmId),holder=state.world.society.people[t.holderId],heir=state.world.society.people[t.heirId],h=sv.houses.find(x=>x.id===t.houseId),claims=(state.world.society.titles[t.id]?.claims||[]).slice(0,3),label=holder?t.style[holder.gender==='M'?'m':holder.gender==='F'?'f':'n']:'Ruler';return`<article class="throne-card"><div class="throne-crown">♛</div><div><span>${esc(t.name)}</span><h3>${esc(holder?`${label} ${personName(holder.id)}`:personName(t.holderId))}</h3><p><b>${esc(h?.name||'No house')}</b> · ${esc(t.law)}</p><dl><dt>Realm</dt><dd>${esc(realm?.shortName||realmNameFallback(t.realmId))}</dd><dt>Heir</dt><dd>${esc(heir?personName(heir.id):'Unsettled')}</dd><dt>Claimants</dt><dd>${claims.length}</dd></dl></div></article>`}).join('')||'<div class="empty">No active thrones at this date.</div>'}
function updateSocietyFilters(view,sv){const rf=$('#peopleRealmFilter'),oldR=rf.value;rf.innerHTML='<option value="all">All realms</option>'+view.realms.filter(r=>r.active).map(r=>`<option value="${r.id}">${esc(r.shortName)}</option>`).join('');if([...rf.options].some(o=>o.value===oldR))rf.value=oldR;const of=$('#peopleOccupationFilter'),oldO=of.value,occ=[...new Set(sv.living.map(p=>p.occupation))].sort();of.innerHTML='<option value="all">All occupations</option>'+occ.map(o=>`<option value="${esc(o)}">${esc(o)}</option>`).join('');if([...of.options].some(o=>o.value===oldO))of.value=oldO}
function renderPeople(view,sv){updateSocietyFilters(view,sv);const realm=$('#peopleRealmFilter').value,occ=$('#peopleOccupationFilter').value,sort=$('#peopleSort').value;let rows=[...sv.living];if(realm!=='all')rows=rows.filter(p=>p.realmId===Number(realm));if(occ!=='all')rows=rows.filter(p=>p.occupation===occ);rows.sort(sort==='wealth'?(a,b)=>b.wealth-a.wealth:sort==='age'?(a,b)=>(sv.year-a.birthYear)-(sv.year-b.birthYear):sort==='name'?(a,b)=>personName(a.id).localeCompare(personName(b.id)):(a,b)=>b.prestige-a.prestige);$('#peopleTable').innerHTML=rows.slice(0,220).map(p=>{const h=sv.houses.find(x=>x.id===p.houseId),realmRow=getRealm(view,p.realmId);return`<tr data-person="${p.id}" class="${state.selectedPersonId===p.id?'selected-row':''}"><td class="place-name">${esc(personName(p.id))}</td><td>${fmt(sv.year-p.birthYear)}</td><td>${esc(p.occupation)}</td><td>${esc(h?.shortName||'—')}</td><td>${esc(realmRow?.shortName||'—')}</td><td>${fmt(p.prestige,0)}</td><td>${fmt(p.wealth,0)}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No notable people match these filters.</td></tr>';if(state.selectedPersonId==null||!sv.living.some(p=>p.id===state.selectedPersonId)){const ruler=sv.titles.find(t=>t.active)?.holderId;state.selectedPersonId=ruler??sv.living[0]?.id??null}renderPersonDossier(view,sv)}
function relationNames(ids,limit=4){return(ids||[]).map(personName).filter(x=>x!=='Unknown').slice(0,limit).map(esc).join(' · ')||'—'}
function renderPersonDossier(view,sv){const id=state.selectedPersonId,master=state.world.society.people[id],pv=societyPersonInView(sv,id),host=$('#personDossier');if(!master){host.innerHTML='<div class="empty">Select a person to inspect their life and family.</div>';$('#familyGraph').innerHTML='';return}const y=sv.year,alive=master.birthYear<=y&&(master.deathYear==null||master.deathYear>y),h=state.world.society.houses[master.houseId],realm=getRealm(view,pv?.realmId??master.realmId),sett=state.world.settlements[pv?.settlementId??master.settlementId],held=sv.titles.filter(t=>t.holderId===id),sp=master.spouseId!=null?personName(master.spouseId):'—';host.innerHTML=`<div class="dossier-title"><div class="portrait-seal">${esc(master.firstName.slice(0,1))}</div><div><span>${alive?`AGE ${y-master.birthYear}`:`${master.birthYear}–${master.deathYear}`}</span><h3>${esc(personName(id))}</h3><p>${held.length?esc(`${held[0].style[master.gender==='M'?'m':master.gender==='F'?'f':'n']} · ${held[0].name}`):esc(pv?.occupation||master.occupation)}</p></div></div><div class="dossier-grid"><div><span>House</span><b>${esc(h?.name||'Unaffiliated')}</b></div><div><span>Realm</span><b>${esc(realm?.name||realmNameFallback(master.realmId))}</b></div><div><span>Residence</span><b>${esc(sett?.name||'—')}</b></div><div><span>Status</span><b>${esc(alive?(pv?.status||master.status):'Deceased')}</b></div><div><span>Prestige</span><b>${fmt(pv?.prestige??master.prestige,0)}</b></div><div><span>Wealth</span><b>${fmt(pv?.wealth??master.wealth,0)}</b></div></div><div class="dossier-copy"><p><span>Traits</span>${master.traits.map(esc).join(' · ')}</p><p><span>Ambition</span>${esc(master.ambition)}</p><p><span>Spouse</span>${esc(sp)}</p><p><span>Friends</span>${relationNames(master.friendIds)}</p><p><span>Rivals</span>${relationNames(master.rivalIds)}</p></div>`;renderFamily(id,y)}
function renderFamily(id,year){const g=S.familyGraph(state.world,id,year),host=$('#familyGraph');if(!g){host.innerHTML='';return}host.innerHTML=g.people.map(p=>`<button class="family-node ${p.relation.toLowerCase()} ${p.alive?'':'deceased'}" data-person="${p.id}"><span>${esc(p.relation)}</span><b>${esc(p.name)}</b><small>${p.alive?`${esc(p.occupation)} · age ${year-p.birthYear}`:`${p.birthYear}–${p.deathYear??'?'}`}</small></button>`).join('')}
function renderDynasties(view,sv){$('#dynastyList').innerHTML=[...sv.houses].sort((a,b)=>(b.status==='Ruling')-(a.status==='Ruling')||b.prestige-a.prestige).slice(0,36).map(h=>{const head=h.headId!=null?personName(h.headId):'Extinct',realm=getRealm(view,h.realmId);return`<article class="dynasty-card ${h.status==='Ruling'?'ruling':''}"><div><span>${esc(h.status.toUpperCase())}</span><h3>${esc(h.name)}</h3></div><dl><dt>House head</dt><dd>${esc(head)}</dd><dt>Realm</dt><dd>${esc(realm?.shortName||realmNameFallback(h.realmId))}</dd><dt>Living members</dt><dd>${h.livingMembers}</dd><dt>Prestige</dt><dd>${fmt(h.prestige,0)}</dd><dt>Founded</dt><dd>Year ${h.foundingYear}</dd></dl></article>`}).join('')||'<div class="empty">No dynastic houses at this date.</div>'}
function renderSociety(view,sv){renderSocietyKPIs(sv);renderThrones(view,sv);renderPeople(view,sv);renderDynasties(view,sv)}
function renderWorld(resetMap=false){const w=state.world;if(!w)return;ensureSystems();const view=getView(),sv=getSocietyView();$('#worldName').textContent=w.name;$('#landPct').textContent=fmt(w.summary.landPercent,1)+'%';$('#riverCount').textContent=w.rivers.length;$('#settlementCount').textContent=w.settlements.length;$('#kingdomCount').textContent=view.metrics.activeRealms;$('#landBadge').textContent=`${w.settings.seed} · Y${view.year}`;$('#worldNarrative').innerHTML=narrative(w,view,sv);renderBiomeBars(w);renderKingdoms(view,sv);renderSettlements(view);renderLegend(view);renderHistoryKPIs(view);renderChronicle(view);renderWars(view);renderDiplomacy(view);renderCharts(view);renderSociety(view,sv);if(resetMap)state.renderer.setWorld(w);state.renderer.setHistoryView(view);updateZoom()}
function forge(){stopPlay();const settings=settingsFromUI();$('#generateBtn').disabled=true;$('#generateBtn').textContent='FORGING…';requestAnimationFrame(()=>setTimeout(()=>{try{state.world=E.generateWorld(settings);H.initialize(state.world);S.initialize(state.world);state.viewYear=null;state.selectedPersonId=null;renderWorld(true);toast(`World forged · ${E.fingerprint(state.world)} · society ${S.societyFingerprint(state.world)}`)}catch(err){console.error(err);toast('World generation failed')}finally{$('#generateBtn').disabled=false;$('#generateBtn').textContent='FORGE WORLD'}},20))}
function updateZoom(){$('#zoomLabel').textContent=Math.round((state.renderer?.camera.zoom||1)*100)+'%'}
function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}
function setHistoricalYear(raw){if(!state.world)return;const current=state.world.history.currentYear,target=Number(raw);state.viewYear=target>=current?null:H.snapshotAt(state.world,target).year;renderWorld(false)}
function advanceYears(years){if(!state.world)return;stopPlay();const n=Math.max(0,Math.round(Number(years)||0));if(!n)return;const buttons=$$('.history-action');buttons.forEach(b=>b.disabled=true);$('#simState').textContent=`SIMULATING +${n} YEARS…`;requestAnimationFrame(()=>setTimeout(()=>{try{S.simulateYears(state.world,n);state.viewYear=null;renderWorld(false);toast(`Year ${state.world.history.currentYear} · history ${H.historyFingerprint(state.world)} · society ${S.societyFingerprint(state.world)}`)}catch(e){console.error(e);toast('Integrated history simulation failed')}finally{buttons.forEach(b=>b.disabled=false);$('#simState').textContent='HISTORY + SOCIETY READY'}},10))}
function runToTarget(){const y=Math.min(5000,Math.max(0,Math.round(Number($('#targetYearInput').value)||0))),now=state.world?.history?.currentYear||0;if(y<=now)return toast('Target year must be later than the present');advanceYears(y-now)}
function stopPlay(){state.playing=false;clearInterval(state.playTimer);state.playTimer=null;if($('#playBtn'))$('#playBtn').textContent='▶ Auto 5y/tick'}
function togglePlay(){if(state.playing){stopPlay();return}state.playing=true;$('#playBtn').textContent='■ Stop';state.playTimer=setInterval(()=>{if(!state.world||state.world.history.currentYear>=5000){stopPlay();return}S.simulateYears(state.world,5);state.viewYear=null;renderWorld(false)},650)}
function syncControls(){const s=state.world.settings;$('#seedInput').value=s.seed;$('#widthInput').value=s.width;$('#heightInput').value=s.height;$('#seaLevelInput').value=s.seaLevel;$('#ageInput').value=s.age;$('#settlementInput').value=s.settlementTarget;$('#kingdomInput').value=s.kingdomTarget;updateRangeLabels()}
function bind(){state.renderer=new WorldRenderer($('#worldCanvas'));state.renderer.onHover=(s,p)=>{const tip=$('#mapTooltip');if(!s||!p){tip.classList.add('hidden');return}const view=getView(),kid=view.settlementKingdomIds[s.id],k=getRealm(view,kid),biome=E.BIOMES[state.world.layers.biome[s.y*state.world.settings.width+s.x]]?.label,capital=view.realms.some(r=>r.active&&r.capitalId===s.id);tip.innerHTML=`<b>${esc(s.name)}</b>${capital?'Capital · ':''}${esc(s.type)}<br>${esc(k?.name||'Unruled')}<br>${esc(biome)} · pop. ${fmt(view.settlementPopulation[s.id])}<br>Prosperity ${fmt(view.settlementProsperity[s.id]*100,0)}% · Year ${view.year}`;tip.style.left=Math.min(p.x+14,$('#mapWrap').clientWidth-255)+'px';tip.style.top=Math.max(12,p.y-20)+'px';tip.classList.remove('hidden')};state.renderer.onSelectSettlement=s=>{const row=document.querySelector(`[data-settlement="${s.id}"]`);row?.scrollIntoView({behavior:'smooth',block:'center'});toast(`${s.name} selected`)};
  $('#generateBtn').addEventListener('click',forge);$('#randomSeedBtn').addEventListener('click',()=>{$('#seedInput').value=randomSeed();forge()});$('#copySeedBtn').addEventListener('click',async()=>{await navigator.clipboard?.writeText($('#seedInput').value);toast('Seed copied')});['seaLevelInput','settlementInput','kingdomInput'].forEach(id=>$('#'+id).addEventListener('input',updateRangeLabels));$$('.map-mode').forEach(b=>b.addEventListener('click',()=>{$$('.map-mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;state.renderer.setMode(state.mode);renderLegend()}));$('#zoomInBtn').addEventListener('click',()=>{state.renderer.camera.zoom=Math.min(8,state.renderer.camera.zoom*1.3);state.renderer.draw();updateZoom()});$('#zoomOutBtn').addEventListener('click',()=>{state.renderer.camera.zoom=Math.max(.75,state.renderer.camera.zoom/1.3);state.renderer.draw();updateZoom()});$('#centerBtn').addEventListener('click',()=>{state.renderer.center();updateZoom()});$('#worldCanvas').addEventListener('wheel',()=>setTimeout(updateZoom,0),{passive:true});
  $('#kingdomList').addEventListener('click',e=>{const card=e.target.closest('[data-settlement]');if(card&&card.dataset.settlement!=='')state.renderer.focusSettlement(Number(card.dataset.settlement))});$('#settlementTable').addEventListener('click',e=>{const tr=e.target.closest('[data-settlement]');if(tr)state.renderer.focusSettlement(Number(tr.dataset.settlement))});$('#settlementFilter').addEventListener('change',()=>renderSettlements());$('#settlementSort').addEventListener('change',()=>renderSettlements());
  $('#saveBtn').addEventListener('click',()=>{if(!state.world)return toast('Forge a world first');localStorage.setItem('worldforge-main',E.serialize(state.world));toast(`World + history + society saved at Year ${state.world.history.currentYear}`)});$('#loadBtn').addEventListener('click',()=>{const raw=localStorage.getItem('worldforge-main')||localStorage.getItem('worldforge-v01');if(!raw)return toast('No local save found');try{stopPlay();state.world=E.deserialize(raw);H.initialize(state.world);S.initialize(state.world);state.viewYear=null;state.selectedPersonId=null;syncControls();renderWorld(true);toast('World, chronicle and society loaded')}catch(e){console.error(e);toast('Save could not be loaded')}});$('#exportBtn').addEventListener('click',()=>{if(!state.world)return toast('Forge a world first');download(`${state.world.name.replace(/\W+/g,'-').toLowerCase()}.worldforge.json`,E.serialize(state.world))});$('#importInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{stopPlay();state.world=E.deserialize(await f.text());H.initialize(state.world);S.initialize(state.world);state.viewYear=null;state.selectedPersonId=null;syncControls();renderWorld(true);toast('World imported')}catch(err){console.error(err);toast('Invalid WorldForge file')}e.target.value=''});
  $$('[data-years]').forEach(b=>b.addEventListener('click',()=>advanceYears(Number(b.dataset.years))));$('#runTargetBtn').addEventListener('click',runToTarget);$('#playBtn').addEventListener('click',togglePlay);$('#presentBtn').addEventListener('click',()=>{state.viewYear=null;renderWorld(false)});$('#timelineSlider').addEventListener('input',e=>setHistoricalYear(e.target.value));$('#eventFilter').addEventListener('change',()=>renderChronicle(getView()));
  ['peopleRealmFilter','peopleOccupationFilter','peopleSort'].forEach(id=>$('#'+id).addEventListener('change',()=>renderPeople(getView(),getSocietyView())));$('#peopleTable').addEventListener('click',e=>{const tr=e.target.closest('[data-person]');if(!tr)return;state.selectedPersonId=Number(tr.dataset.person);renderPeople(getView(),getSocietyView())});$('#familyGraph').addEventListener('click',e=>{const b=e.target.closest('[data-person]');if(!b)return;state.selectedPersonId=Number(b.dataset.person);renderPersonDossier(getView(),getSocietyView())});
}
updateRangeLabels();bind();forge();
})();