(function(root,factory){
  const api=factory(root&&root.WorldForgeWorldbuilding);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeArchaeology=api;
})(typeof window!=='undefined'?window:globalThis,function(Worldbuilding){
'use strict';
if(!Worldbuilding)throw new Error('WorldForge v4.2 Archaeology requires WorldForgeWorldbuilding');
const VERSION='4.2.0',SCHEMA=1;
const STAGES=Object.freeze(['pristine','damaged','ruined','overgrown','excavated']);
const SITE_TYPES=Object.freeze(['ruin','battlefield','great_work','monument','infrastructure']);
const ARTIFACT_TYPES=Object.freeze(['ceramic','coin','tool','weapon_fragment','seal','tablet','religious_token','trade_weight','glasswork','ornament']);
const MATERIALS=Object.freeze(['stone','bronze','iron','clay','glass','bone','silver','wood']);
const baseInitialize=Worldbuilding.initialize.bind(Worldbuilding),baseSimulate=Worldbuilding.simulateWorldbuildingYear.bind(Worldbuilding),baseSettlementView=Worldbuilding.settlementView.bind(Worldbuilding),baseSummary=Worldbuilding.summary.bind(Worldbuilding);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=4)=>Number(Number(v).toFixed(d));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function year(world){return Worldbuilding.absYear(world)}
function eventSettlementIds(e){const ids=[];if(Number.isInteger(e?.settlementId))ids.push(e.settlementId);for(const id of e?.settlementIds||[])if(Number.isInteger(id))ids.push(id);return[...new Set(ids)]}
function state(world){
 if(!world.archaeology||world.archaeology.schemaVersion!==SCHEMA)world.archaeology={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:year(world),settlements:[],annual:[],revision:0,lastAppliedYear:null,settings:{maxSitesPerSettlement:8,maxArtifactsPerSite:4,maxLayersPerSettlement:5,layerSpanYears:50},stats:{settlements:0,sites:0,pristine:0,damaged:0,ruined:0,overgrown:0,excavated:0,artifacts:0,inscriptions:0,historicalLayers:0,reconstructions:0}};
 const S=world.archaeology;S.engineVersion=VERSION;S.settlements=S.settlements||[];S.annual=S.annual||[];S.revision=Number(S.revision||0);S.settings={maxSitesPerSettlement:8,maxArtifactsPerSite:4,maxLayersPerSettlement:5,layerSpanYears:50,...S.settings};S.stats={settlements:0,sites:0,pristine:0,damaged:0,ruined:0,overgrown:0,excavated:0,artifacts:0,inscriptions:0,historicalLayers:0,reconstructions:0,...S.stats};return S
}
function siteType(l){if(l.type==='ruin')return'ruin';if(l.type==='battlefield')return'battlefield';if(l.type==='great_work')return'great_work';if(l.type==='monument')return'monument';return'infrastructure'}
function eligible(l){const age=Number(l.ageYears||0),condition=Number(l.condition??1);return l.type==='ruin'||l.type==='battlefield'||(l.type==='great_work'&&(age>=35||condition<.72))||(l.type==='monument'&&(age>=70||condition<.62))||(['bridge','canal','fortified_port','lighthouse'].includes(l.type)&&age>=110&&condition<.7)}
function stageFor(profile,l){
 const age=Math.max(0,Number(l.ageYears||0)),condition=clamp(Number(l.condition??.7),0,1),biome=String(profile.biomeStyle||''),h=hash(`${profile.previewSeed}|${l.id}|stage`),discovered=!!l.details?.discovered;
 if(discovered&&age>=30&&h%5===0)return'excavated';
 if((biome==='forest'||biome==='tropical')&&age>=70&&condition<.72)return'overgrown';
 if(l.type==='ruin'&&age>=90&&h%3===0)return'overgrown';
 if(l.type==='battlefield'&&age>=120&&h%4===0)return'overgrown';
 if(l.type==='ruin'||condition<.45)return'ruined';
 if(condition<.76||age>=80)return'damaged';
 return'pristine'
}
function siteIntegrity(stage,condition,age){const base={pristine:.94,damaged:.7,ruined:.48,overgrown:.42,excavated:.58}[stage]||.5;return round(clamp(base*.65+Number(condition||0)*.35-Math.min(.18,age/1400),.12,.99),3)}
function artifactPool(type){if(type==='battlefield')return['weapon_fragment','coin','ornament','tool'];if(type==='great_work'||type==='monument')return['tablet','seal','ornament','ceramic','coin'];if(type==='infrastructure')return['trade_weight','tool','coin','ceramic'];return ARTIFACT_TYPES}
function artifactsFor(profile,l,stage,originYear){
 const type=siteType(l),pool=artifactPool(type),h=hash(`${profile.previewSeed}|${l.id}|artifacts`),max=stage==='excavated'?4:stage==='overgrown'||stage==='ruined'?3:2,count=Math.max(1,Math.min(max,1+(h%max))),out=[];
 for(let i=0;i<count;i++){const x=hash(`${h}|${i}`),kind=pool[x%pool.length],material=MATERIALS[(x>>>5)%MATERIALS.length],offset=((x>>>9)%19)-9;out.push({id:`${l.id}:artifact:${i}`,kind,material,estimatedYear:Number.isFinite(originYear)?Math.max(0,originYear+offset):null,condition:round(clamp(.35+((x>>>13)%55)/100-(stage==='overgrown'?.08:0),.18,.95),3),significance:round(clamp(Number(l.importance||.5)*.65+((x>>>19)%30)/100,.2,1),3),catalogued:stage==='excavated'})}
 return out
}
function inscriptionsFor(profile,l,stage,originYear){
 const h=hash(`${profile.previewSeed}|${l.id}|inscription`),chance=Number(l.importance||0)+(siteType(l)==='great_work'?.2:0)+(stage==='excavated'?.15:0);if(chance<.55||h%4===0)return[];
 const subjects=['foundation dedication','merchant tally','victory record','funerary text','boundary decree','ritual invocation','builder mark','dynastic titulary'];const scripts=['lapidary capitals','merchant cipher','temple hand','court script','local runic hand','seal script'];const n=chance>.9&&h%3===0?2:1,out=[];
 for(let i=0;i<n;i++){const x=hash(`${h}|${i}`);out.push({id:`${l.id}:inscription:${i}`,subject:subjects[x%subjects.length],script:scripts[(x>>>6)%scripts.length],estimatedYear:Number.isFinite(originYear)?Math.max(0,originYear+(((x>>>11)%15)-7)):null,legibility:round(clamp(.35+Number(l.condition||0)*.45+(stage==='excavated'?.12:0)-((x>>>17)%12)/100,.18,.98),3),translated:stage==='excavated'&&x%3!==0})}
 return out
}
function reconstruction(profile,l,stage){const oy=Number.isFinite(Number(l.originYear))?Number(l.originYear):null;return{available:true,thenYear:oy,nowYear:profile.lastYear??null,then:{stage:'pristine',label:oy==null?'Reconstructed original state':`Reconstructed state around Year ${oy}`,architectureFamily:profile.architectureStyle?.id||profile.cultureStyle,landmarkType:l.type},now:{stage,label:`Current ${stage.replaceAll('_',' ')} state`,condition:round(Number(l.condition||0),3)},confidence:round(clamp(.48+Number(l.importance||0)*.32+(l.sourceType==='history_event'?.08:0)+(l.sourceType==='institution'?.08:0),.35,.96),3)}}
function buildSite(profile,l){
 const stage=stageFor(profile,l),age=Math.max(0,Number(l.ageYears||0)),originYear=Number.isFinite(Number(l.originYear))?Number(l.originYear):null,h=hash(`${profile.previewSeed}|${l.id}|archaeology`),vegetation=round(clamp((profile.biomeStyle==='forest'||profile.biomeStyle==='tropical'?.48:.14)+(stage==='overgrown'?.38:0)-Number(l.condition||0)*.12+((h>>>8)%12)/100,0,1),3),integrity=siteIntegrity(stage,l.condition,age),excavation=stage==='excavated'?round(.35+((h>>>14)%60)/100,3):0;
 return{id:`arch:${profile.settlementId}:${l.id}`,settlementId:profile.settlementId,landmarkId:l.id,name:l.name,siteType:siteType(l),landmarkType:l.type,sourceType:l.sourceType,originYear,ageYears:age,lifecycleStage:stage,integrity,vegetation,burialDepthMeters:round(clamp(.15+age/130*((h%7)+2)/10,.15,5.5),2),surveyConfidence:round(clamp(.42+Number(l.importance||0)*.34+(l.details?.discovered?.15:0),.35,.98),3),excavationProgress:excavation,x:l.x,y:l.y,artifacts:artifactsFor(profile,l,stage,originYear),inscriptions:inscriptionsFor(profile,l,stage,originYear),reconstruction:reconstruction(profile,l,stage),details:{landmarkCondition:l.condition,landmarkImportance:l.importance,sourceId:l.sourceId,sourceEventId:l.details?.sourceEventId??null}}
}
function layerDominant(items){const text=items.map(x=>`${x.type||''} ${x.landmarkType||''} ${x.eventType||''}`).join(' ').toLowerCase();if(/battle|war|siege|fort/.test(text))return'defensive';if(/harbor|bridge|canal|trade|merchant/.test(text))return'maritime_trade';if(/temple|ritual|great_work|monument/.test(text))return'ceremonial';if(/fire|collapse|ruin/.test(text))return'destruction_horizon';return'urban_occupation'}
function historicalLayers(world,profile,sites){
 const span=Math.max(25,Number(state(world).settings.layerSpanYears||50)),items=[];
 for(const l of profile.landmarks||[])if(Number.isFinite(Number(l.originYear)))items.push({year:Number(l.originYear),type:'landmark',landmarkType:l.type,ref:`historical_landmark:${profile.settlementId}:${l.id}`});
 for(const e of world.history?.events||[]){if(!eventSettlementIds(e).includes(profile.settlementId))continue;const y=Number(e.absoluteYear??e.year);if(Number.isFinite(y))items.push({year:y,type:'event',eventType:e.type,ref:`event:${e.id}`})}
 if(!items.length)return[];const buckets=new Map;for(const it of items){const start=Math.floor(it.year/span)*span;if(!buckets.has(start))buckets.set(start,[]);buckets.get(start).push(it)}
 const now=Number(profile.lastYear??year(world)),ordered=[...buckets.entries()].sort((a,b)=>a[0]-b[0]).slice(-state(world).settings.maxLayersPerSettlement);
 return ordered.map(([start,arr],i)=>{const end=start+span-1,age=Math.max(0,now-end),siteRefs=sites.filter(s=>s.originYear!=null&&s.originYear>=start&&s.originYear<=end).map(s=>s.id),survival=round(clamp(.82-Math.min(.5,age/900)+siteRefs.length*.04,.2,.95),3),h=hash(`${profile.previewSeed}|layer|${start}`);return{id:`layer:${profile.settlementId}:${start}`,periodStart:start,periodEnd:end,label:`${start}–${end} historical layer`,dominantUse:layerDominant(arr),buried:age>span,depthMeters:round(clamp(.12+age/95*.28+((h>>>5)%12)/20,.12,6),2),survival,sourceRefs:[...new Set(arr.map(x=>x.ref))].slice(0,12),siteRefs,sequence:i+1}})
}
function buildSettlement(world,profile){const sites=(profile.landmarks||[]).filter(eligible).map(l=>buildSite(profile,l)).sort((a,b)=>{const order=STAGES.indexOf(b.lifecycleStage)-STAGES.indexOf(a.lifecycleStage);return order||Number(b.details.landmarkImportance||0)-Number(a.details.landmarkImportance||0)}).slice(0,state(world).settings.maxSitesPerSettlement),layers=historicalLayers(world,profile,sites);return{settlementId:profile.settlementId,name:profile.name,lastYear:profile.lastYear,sites,layers,artifactCount:sites.reduce((n,s)=>n+s.artifacts.length,0),inscriptionCount:sites.reduce((n,s)=>n+s.inscriptions.length,0),excavatedSites:sites.filter(s=>s.lifecycleStage==='excavated').length,reconstructionCount:sites.filter(s=>s.reconstruction?.available).length}}
function refreshStats(world){const S=state(world),ss=S.settlements,sites=ss.flatMap(x=>x.sites||[]);S.stats.settlements=ss.length;S.stats.sites=sites.length;for(const k of STAGES)S.stats[k]=sites.filter(s=>s.lifecycleStage===k).length;S.stats.artifacts=sites.reduce((n,s)=>n+(s.artifacts||[]).length,0);S.stats.inscriptions=sites.reduce((n,s)=>n+(s.inscriptions||[]).length,0);S.stats.historicalLayers=ss.reduce((n,s)=>n+(s.layers||[]).length,0);S.stats.reconstructions=sites.filter(s=>s.reconstruction?.available).length;return S.stats}
function sync(world,force=false){baseInitialize(world);const S=state(world),y=year(world),sig=`${y}|${world.worldbuilding?.revision||0}|${world.history?.events?.length||0}|${world.adventure?.sites?.length||0}|${world.institutions?.facilities?.length||0}`;if(!force&&S._signature===sig)return S;S.settlements=(world.worldbuilding?.profiles||[]).filter(p=>p.lastYear!=null).map(p=>buildSettlement(world,JSON.parse(JSON.stringify(p))));S.currentYear=y;S._signature=sig;S.revision++;refreshStats(world);return S}
function settlementState(world,sid){const S=sync(world),id=Number(sid);return S.settlements.find(x=>Number(x.settlementId)===id)||{settlementId:id,name:baseSettlementView(world,id)?.name||`Settlement ${id}`,lastYear:year(world),sites:[],layers:[],artifactCount:0,inscriptionCount:0,excavatedSites:0,reconstructionCount:0}}
function settlementView(world,sid){return JSON.parse(JSON.stringify(settlementState(world,sid)))}
function decorateProfile(world,profile){const a=settlementView(world,profile.settlementId),by=new Map((a.sites||[]).map(s=>[String(s.landmarkId),s]));profile.archaeology=a;profile.landmarks=(profile.landmarks||[]).map(l=>{const s=by.get(String(l.id));return s?{...l,lifecycleStage:s.lifecycleStage,archaeologySiteId:s.id,excavationProgress:s.excavationProgress}:l});return profile}
function summary(world){sync(world);return{year:state(world).currentYear,revision:state(world).revision,...refreshStats(world)}}
function simulateArchaeologyYear(world,y=year(world)){const S=sync(world,true),n=Math.floor(Number(y));if(S.lastAppliedYear===n)return S;S.currentYear=n;S.lastAppliedYear=n;const stats=refreshStats(world);S.annual.push({year:n,sites:stats.sites,excavated:stats.excavated,artifacts:stats.artifacts,inscriptions:stats.inscriptions,historicalLayers:stats.historicalLayers});if(S.annual.length>1000)S.annual.splice(0,S.annual.length-1000);return S}
function fingerprint(world){const S=sync(world),data={year:S.currentYear,settlements:S.settlements.map(s=>[s.settlementId,(s.sites||[]).map(x=>[x.id,x.lifecycleStage,x.integrity,x.vegetation,x.burialDepthMeters,x.excavationProgress,(x.artifacts||[]).map(a=>[a.kind,a.material,a.estimatedYear,a.condition,a.significance]),(x.inscriptions||[]).map(i=>[i.subject,i.script,i.estimatedYear,i.legibility,i.translated])]),(s.layers||[]).map(l=>[l.id,l.periodStart,l.periodEnd,l.dominantUse,l.depthMeters,l.survival])]),stats:S.stats};return hash(JSON.stringify(data)).toString(16).padStart(8,'0')}
function validate(world){const S=sync(world),e=[],ids=new Set;for(const s of S.settlements){for(const site of s.sites||[]){if(ids.has(site.id))e.push(`duplicate archaeology site ${site.id}`);ids.add(site.id);if(!SITE_TYPES.includes(site.siteType))e.push(`site type ${site.id}`);if(!STAGES.includes(site.lifecycleStage))e.push(`lifecycle stage ${site.id}`);for(const k of['integrity','vegetation','surveyConfidence','excavationProgress'])if(!Number.isFinite(Number(site[k]))||Number(site[k])<0||Number(site[k])>1)e.push(`${k} ${site.id}`);if(!Number.isFinite(Number(site.x))||site.x<0||site.x>1||!Number.isFinite(Number(site.y))||site.y<0||site.y>1)e.push(`site position ${site.id}`);for(const a of site.artifacts||[])if(!ARTIFACT_TYPES.includes(a.kind)||!MATERIALS.includes(a.material))e.push(`artifact ${a.id}`)}for(const l of s.layers||[])if(!Number.isFinite(Number(l.depthMeters))||l.depthMeters<0)e.push(`historical layer ${l.id}`)}return[...new Set(e)]}
function installBridge(){if(Worldbuilding.__archaeologyBridge)return;Worldbuilding.__archaeologyBridge=true;Worldbuilding.initialize=function(world){const out=baseInitialize(world);sync(world);return out};Worldbuilding.simulateWorldbuildingYear=function(world,y=Worldbuilding.absYear(world)){const out=baseSimulate(world,y);simulateArchaeologyYear(world,y);return out};Worldbuilding.settlementView=function(world,sid){return decorateProfile(world,baseSettlementView(world,sid))};Worldbuilding.summary=function(world){const base=baseSummary(world),a=summary(world);return{...base,archaeologicalSites:a.sites,excavatedSites:a.excavated,artifactFinds:a.artifacts,inscriptions:a.inscriptions,historicalLayers:a.historicalLayers,reconstructions:a.reconstructions}};Worldbuilding.ARCHAEOLOGY_VERSION=VERSION}
installBridge();return{VERSION,SCHEMA,STAGES,SITE_TYPES,ARTIFACT_TYPES,MATERIALS,initialize:sync,simulateArchaeologyYear,settlementState,settlementView,decorateProfile,summary,fingerprint,validate,stageFor,buildSite,historicalLayers,installBridge};
});