(function(root,factory){
  const api=factory(root&&root.WorldForgeHistory,root&&root.WorldForgeSociety,root&&root.WorldForgeAdventure,root&&root.WorldForgeKnowledge,root&&root.WorldForgeCulture,root&&root.WorldForgeFactions);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeArtifacts=api;
})(typeof window!=='undefined'?window:globalThis,function(History,Society,Adventure,Knowledge,Culture,Factions){
'use strict';
const VERSION='1.6.0',SCHEMA=1;
const WRITTEN=new Set(['treaty','chronicle','letter','map','inscription','codex','charter','journal','ledger']);
const EVENT_KINDS={war:['weapon','banner','chronicle','journal'],peace:['treaty','chronicle'],alliance:['treaty','charter'],diplomacy:['letter','treaty'],conquest:['weapon','banner','chronicle','map'],realm_formed:['charter','crown','coin'],collapse:['crown','chronicle','relic'],succession:['crown','charter','coin'],succession_crisis:['crown','letter','weapon'],religious_schism:['relic','codex','inscription'],conversion:['codex','relic'],cultural_revival:['codex','banner','chronicle'],faction_formed:['charter','banner','ledger'],uprising:['banner','weapon','letter'],gang_war:['weapon','ledger','letter'],site_discovered:['map','journal','relic'],expedition:['journal','map','relic'],quest_resolved:['relic','journal','map'],famine:['chronicle','letter','ledger'],trade_boom:['ledger','coin','letter'],drought:['chronicle','letter'],flood:['chronicle','inscription'],eclipse:['chronicle','inscription'],comet:['chronicle','codex']};
const MATERIAL={crown:'gilded metal',weapon:'forged steel',banner:'dyed cloth',relic:'mixed sacred materials',coin:'struck metal',treaty:'parchment',chronicle:'bound vellum',letter:'paper',map:'parchment',inscription:'carved stone',codex:'bound parchment',charter:'illuminated vellum',journal:'stitched paper',ledger:'bound paper'};
const ICON={crown:'♛',weapon:'⚔',banner:'⚑',relic:'✦',coin:'◉',treaty:'⌘',chronicle:'▤',letter:'✉',map:'⌖',inscription:'◆',codex:'▥',charter:'§',journal:'✎',ledger:'▦'};
let baseSimulator=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed);return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function seedOf(w){return w.endless?.baseSeed||String(w.settings?.seed||'WORLD').split('|EPOCH:')[0]}
function random(w,key){return rng(`${seedOf(w)}|ARTIFACT|${key}`)}
function absYear(w,e=null){if(e&&Number.isFinite(Number(e.absoluteYear)))return Number(e.absoluteYear);return(w.endless?.epochOffset||0)+Number(e?.year??w.history?.currentYear??0)}
function eventKey(w,e){return Knowledge?.eventKey?Knowledge.eventKey(w,e):`${absYear(w,e)}|${e.type||'event'}|${e.title||''}|${(e.realmIds||[]).join(',')}|${(e.settlementIds||[]).join(',')}`}
function setBaseSimulator(fn){if(typeof fn==='function')baseSimulator=fn;return api}
function initialize(w){
 if(!w)throw new Error('World required');History?.initialize?.(w);Society?.initialize?.(w);Adventure?.initialize?.(w);Culture?.initialize?.(w);Factions?.initialize?.(w);Knowledge?.initialize?.(w);
 if(!w.artifacts||w.artifacts.schemaVersion!==SCHEMA)w.artifacts={schemaVersion:SCHEMA,engineVersion:VERSION,nextId:0,items:[],archives:[],processedEventKeys:[],settings:{maxDetailedItems:850,retainDetailedYears:1500,maxProvenance:18,maxCirculation:5000},stats:{created:0,writtenWorks:0,transfers:0,lost:0,rediscovered:0,destroyed:0,copiesMade:0,knowledgeSources:0,archived:0}};
 const a=w.artifacts;a.engineVersion=VERSION;a.items=a.items||[];a.archives=a.archives||[];a.processedEventKeys=a.processedEventKeys||[];a.nextId=Math.max(Number(a.nextId)||0,...a.items.map(x=>(Number(x.id)||0)+1),0);a.settings={maxDetailedItems:850,retainDetailedYears:1500,maxProvenance:18,maxCirculation:5000,...a.settings};a.stats={created:0,writtenWorks:0,transfers:0,lost:0,rediscovered:0,destroyed:0,copiesMade:0,knowledgeSources:0,archived:0,...a.stats};return a
}
function eventRefs(e){const out=[];for(const [k,t] of [['realmIds','realm'],['settlementIds','settlement'],['personIds','person'],['houseIds','house'],['gangIds','gang'],['siteIds','site'],['questIds','quest'],['organizationIds','organization']])for(const id of e?.[k]||[])out.push(`${t}:${id}`);if(e?.id!=null)out.push(`event:${e.id}`);return[...new Set(out)]}
function personName(w,id){const p=w.society?.people?.[id];return p&&Society?.fullName?Society.fullName(w.society,p):p?`${p.firstName||''} ${p.surname||''}`.trim():null}
function realmName(w,id){return w.history?.realms?.[id]?.shortName||w.history?.realms?.[id]?.name||null}
function placeName(w,id){return w.settlements?.[id]?.name||null}
function holderRef(type,id){return type&&id!=null?`${type}:${id}`:null}
function ownerLabel(w,item){if(item.ownerType==='person')return personName(w,item.ownerId)||'Unknown bearer';if(item.ownerType==='realm')return realmName(w,item.ownerId)||'Unknown realm';if(item.ownerType==='organization')return w.factions?.organizations?.find(x=>x.id===item.ownerId)?.name||'Unknown organization';if(item.ownerType==='site')return w.adventure?.sites?.find(x=>x.id===item.ownerId)?.name||'Lost site';if(item.ownerType==='settlement')return placeName(w,item.ownerId)||'Unknown settlement';return item.status==='destroyed'?'Destroyed':'Unclaimed'}
function sourceKind(kind){if(kind==='treaty'||kind==='charter')return'official';if(kind==='letter'||kind==='ledger')return'merchant';if(kind==='inscription')return'inscription';if(kind==='journal')return'witness';if(kind==='codex'||kind==='chronicle'||kind==='map')return'scholar';if(kind==='relic')return'temple';return'scholar'}
function itemName(w,kind,e,r){const rid=e?.realmIds?.[0],sid=e?.settlementIds?.[0],pid=e?.personIds?.[0],realm=realmName(w,rid)||'Nameless Realm',place=placeName(w,sid)||realm,person=personName(w,pid)||place,title=String(e?.title||place).replace(/^(The|A)\s+/i,'');const adj=['Ashen','Ivory','Silver','Red','Gilded','Black','Star','River','Iron','Moonlit'][Math.floor(r()*10)];
 if(kind==='crown')return`${realm} Crown of ${place}`;if(kind==='weapon')return`${adj} Blade of ${title}`;if(kind==='banner')return`${realm} Banner of ${title}`;if(kind==='relic')return`${adj} Relic of ${place}`;if(kind==='coin')return`${realm} Commemorative Coin`;if(kind==='treaty')return`Treaty of ${place}`;if(kind==='chronicle')return`Chronicle of ${title}`;if(kind==='letter')return`Letter of ${person}`;if(kind==='map')return`Survey Map of ${place}`;if(kind==='inscription')return`Stone Record of ${title}`;if(kind==='codex')return`${adj} Codex of ${place}`;if(kind==='charter')return`Founding Charter of ${realm}`;if(kind==='journal')return`Journal of ${person}`;return`${place} Trade Ledger`}
function defaultOwner(w,e){const pid=e?.personIds?.find(id=>w.society?.people?.[id]&&!w.society.people[id].archived);if(pid!=null)return['person',pid];const rid=e?.realmIds?.[0];if(rid!=null)return['realm',rid];const sid=e?.settlementIds?.[0];if(sid!=null)return['settlement',sid];return['settlement',0]}
function claimForEvent(w,e){if(!Knowledge)return null;Knowledge.sync(w);const key=eventKey(w,e);return w.knowledge?.claims?.find(c=>c.key===key)||null}
function attachKnowledge(w,item,claimKey,year=null,rediscovery=false){if(!Knowledge||!claimKey)return null;const k=Knowledge.initialize(w),claim=k.claims.find(c=>c.key===claimKey);if(!claim)return null;if(k.sources.some(s=>s.artifactId===item.id&&s.claimKey===claimKey&&!!s.rediscovery===!!rediscovery))return null;const kind=sourceKind(item.kind),reliability=clamp(item.authenticity*(rediscovery?.93:.84),.18,.98),text=rediscovery?`The rediscovered ${item.name} provides physical evidence concerning ${claim.trueTitle}.`:`${item.name} preserves a material account connected to ${claim.trueTitle}.`;const s=Knowledge.addSource(w,claimKey,{kind,originRealmId:item.originRealmId,originSettlementId:item.originSettlementId,authorPersonId:item.creatorPersonId,createdYear:year??item.createdYear,reliability,archiveStrength:clamp(item.durability,.2,.99),text});s.artifactId=item.id;s.rediscovery=!!rediscovery;s.materialEvidence=true;w.artifacts.stats.knowledgeSources++;return s}
function provenance(item,year,action,from=null,to=null,note=''){item.provenance=item.provenance||[];item.provenance.push({year,action,from,to,note});if(item.provenance.length>30)item.provenance=item.provenance.slice(-30)}
function createArtifact(w,data={}){const a=initialize(w),year=Number.isFinite(Number(data.createdYear))?Number(data.createdYear):absYear(w),kind=String(data.kind||'relic').toLowerCase(),r=random(w,`${a.nextId}|${year}|${kind}|${data.name||''}`),ownerType=data.ownerType||'settlement',ownerId=data.ownerId??0,written=WRITTEN.has(kind),item={id:a.nextId++,name:String(data.name||itemName(w,kind,data.event||null,r)),kind,written,material:String(data.material||MATERIAL[kind]||'mixed material'),createdYear:year,creatorPersonId:Number.isInteger(data.creatorPersonId)?data.creatorPersonId:null,originSettlementId:Number.isInteger(data.originSettlementId)?data.originSettlementId:0,originRealmId:Number.isInteger(data.originRealmId)?data.originRealmId:null,cultureId:Number.isInteger(data.cultureId)?data.cultureId:null,religionId:Number.isInteger(data.religionId)?data.religionId:null,sourceEventKey:data.sourceEventKey||null,claimKeys:[...(data.claimKeys||[])],refs:[...(data.refs||[])],ownerType,ownerId,status:data.status||'held',siteId:Number.isInteger(data.siteId)?data.siteId:null,prestige:round(clamp(Number(data.prestige??(35+r()*60)),1,100),1),authenticity:round(clamp(Number(data.authenticity??(.72+r()*.27)),.05,1),3),durability:round(clamp(Number(data.durability??(written?.45+r()*.38:.68+r()*.30)),.08,1),3),condition:round(clamp(Number(data.condition??(.78+r()*.22)),0,1),3),forgery:!!data.forgery,contents:String(data.contents||''),language:String(data.language||'Common'),copies:written?Math.max(1,Math.round(Number(data.copies)||1)):1,circulationRealms:[...(data.circulationRealms||[])],copyMilestones:[...(data.copyMilestones||[])],provenance:[],discoveredYear:data.discoveredYear??null,lastChangeYear:year};provenance(item,year,'created',null,holderRef(ownerType,ownerId),data.note||`Created in ${placeName(w,item.originSettlementId)||'an unknown place'}.`);a.items.push(item);a.stats.created++;if(written)a.stats.writtenWorks++;for(const key of item.claimKeys)attachKnowledge(w,item,key,year,false);return item}
function shouldCreate(w,e){if(e.type?.startsWith('artifact_'))return false;const kinds=EVENT_KINDS[e.type];if(!kinds)return false;const r=random(w,`event-create|${eventKey(w,e)}`),importance=Number(e.importance||1);return importance>=3||r()<(importance>=2?.62:.22)}
function createFromEvent(w,e){const a=initialize(w),key=eventKey(w,e);if(a.items.some(x=>x.sourceEventKey===key))return null;const r=random(w,`event|${key}`),kinds=EVENT_KINDS[e.type]||['relic'],kind=kinds[Math.floor(r()*kinds.length)],claim=claimForEvent(w,e),[ownerType,ownerId]=defaultOwner(w,e),sid=Number.isInteger(e.settlementIds?.[0])?e.settlementIds[0]:(w.history.realms?.[e.realmIds?.[0]]?.capitalId??0),rid=e.realmIds?.[0]??w.history.current.settlementKingdomIds?.[sid]??null,cultureId=w.culture?.settlementCultureIds?.[sid]??null,religionId=w.culture?.settlementReligionIds?.[sid]??null,forgery=(kind==='letter'||kind==='chronicle'||kind==='charter')&&r()<.055,auth=forgery?.28+r()*.28:.72+r()*.27,item=createArtifact(w,{kind,event:e,createdYear:absYear(w,e),originSettlementId:sid,originRealmId:rid,cultureId,religionId,creatorPersonId:e.personIds?.[0]??null,ownerType,ownerId,sourceEventKey:key,claimKeys:claim?[claim.key]:[],refs:eventRefs(e),prestige:clamp(25+(e.importance||1)*18+r()*28,10,100),authenticity:auth,forgery,contents:WRITTEN.has(kind)?String(e.text||e.title||''):'',language:w.culture?.cultures?.[cultureId]?.language||'Common'});if((e.importance||1)>=3||item.prestige>88)pushHistory(w,{type:'artifact_created',importance:1,realmIds:rid==null?[]:[rid],settlementIds:[sid],personIds:item.creatorPersonId==null?[]:[item.creatorPersonId],title:`${item.name} enters the record`,text:`A ${item.kind} associated with ${e.title||'a major event'} becomes a recognized historical object.`,artifactIds:[item.id]});return item}
function pushHistory(w,e){const h=History.initialize(w);h.events.push({id:h.events.length,year:h.currentYear,absoluteYear:absYear(w),...e})}
function sync(w){const a=initialize(w);Knowledge?.sync?.(w);const known=new Set(a.processedEventKeys);for(const e of [...(w.history?.events||[])]){const key=eventKey(w,e);if(known.has(key))continue;known.add(key);a.processedEventKeys.push(key);if(shouldCreate(w,e))createFromEvent(w,e)}if(a.processedEventKeys.length>5000)a.processedEventKeys=a.processedEventKeys.slice(-5000);compact(w);return a}
function find(w,id){return initialize(w).items.find(x=>x.id===Number(id))||null}
function transfer(w,id,toType,toId,reason='transfer',year=absYear(w)){const a=initialize(w),item=find(w,id);if(!item||item.status==='destroyed')return null;const from=holderRef(item.ownerType,item.ownerId),to=holderRef(toType,toId);item.ownerType=toType;item.ownerId=toId;item.status=toType==='site'?'lost':'held';if(toType!=='site')item.siteId=null;item.lastChangeYear=year;provenance(item,year,reason,from,to,reason);a.stats.transfers++;return item}
function lose(w,id,siteId=null,reason='lost in upheaval',year=absYear(w)){const a=initialize(w),item=find(w,id);if(!item||item.status==='destroyed'||item.status==='lost')return item;const from=holderRef(item.ownerType,item.ownerId);item.status='lost';item.siteId=Number.isInteger(siteId)?siteId:null;item.ownerType=item.siteId!=null?'site':null;item.ownerId=item.siteId;item.lastChangeYear=year;provenance(item,year,'lost',from,item.siteId!=null?`site:${item.siteId}`:null,reason);a.stats.lost++;if(item.prestige>72)pushHistory(w,{type:'artifact_lost',importance:1,settlementIds:[item.originSettlementId],realmIds:item.originRealmId==null?[]:[item.originRealmId],title:`${item.name} is lost`,text:`The historical ${item.kind} disappears from reliable custody.`,artifactIds:[item.id],siteIds:item.siteId==null?[]:[item.siteId]});return item}
function rediscover(w,id,holderType='realm',holderId=null,year=absYear(w),reason='rediscovered'){const a=initialize(w),item=find(w,id);if(!item||item.status==='destroyed')return null;const oldSite=item.siteId;if(holderId==null){holderId=item.originRealmId??w.history.current.settlementKingdomIds?.[item.originSettlementId]??0}item.status='held';item.discoveredYear=year;item.siteId=null;item.ownerType=holderType;item.ownerId=holderId;item.condition=round(clamp(item.condition+.08,.05,1));item.lastChangeYear=year;provenance(item,year,'rediscovered',oldSite==null?null:`site:${oldSite}`,holderRef(holderType,holderId),reason);a.stats.rediscovered++;let attached=0;for(const key of item.claimKeys)if(attachKnowledge(w,item,key,year,true))attached++;pushHistory(w,{type:'artifact_rediscovered',importance:item.prestige>80?2:1,realmIds:holderType==='realm'?[holderId]:item.originRealmId==null?[]:[item.originRealmId],settlementIds:[item.originSettlementId],siteIds:oldSite==null?[]:[oldSite],title:`${item.name} is rediscovered`,text:`The recovered ${item.kind} returns to public study${attached?' and adds material evidence to an older historical claim':''}.`,artifactIds:[item.id]});Knowledge?.sync?.(w);return item}
function siteForLoss(w,item,r){const sites=(w.adventure?.sites||[]).filter(s=>s&&s.active!==false&&(s.settlementId===item.originSettlementId||s.realmId===item.originRealmId));return sites.length&&r()<.7?sites[Math.floor(r()*sites.length)].id:null}
function ownerDeath(w,item,year){if(item.ownerType!=='person')return false;const p=w.society?.people?.[item.ownerId];if(!p||p.deathYear==null)return false;const rid=p.realmId??item.originRealmId;if(rid!=null)transfer(w,item.id,'realm',rid,'inherited after bearer death',year);else transfer(w,item.id,'settlement',p.settlementId??item.originSettlementId,'returned after bearer death',year);return true}
function spreadWrittenWork(w,item,year,r){if(!item.written||item.status!=='held'||item.condition<.15)return;const holderRealm=item.ownerType==='realm'?item.ownerId:item.ownerType==='person'?w.society?.people?.[item.ownerId]?.realmId:item.originRealmId,pros=w.history.current.settlementProsperity?.[item.originSettlementId]??.5,trade=(w.history.current.tradeVolumes||[]).reduce((a,x)=>a+Number(x||0),0)/Math.max(1,(w.history.current.tradeVolumes||[]).length),growth=Math.max(0,Math.floor((pros*.8+Math.log1p(trade)/18+r()*.65)));if(growth){const old=item.copies;item.copies=Math.min(w.artifacts.settings.maxCirculation,item.copies+growth);w.artifacts.stats.copiesMade+=item.copies-old}if(holderRealm!=null&&!item.circulationRealms.includes(holderRealm))item.circulationRealms.push(holderRealm);for(const mark of[10,50,200,1000])if(item.copies>=mark&&!item.copyMilestones.includes(mark)){item.copyMilestones.push(mark);const key=item.claimKeys[0],claim=w.knowledge?.claims?.find(c=>c.key===key);if(claim&&Knowledge){const s=Knowledge.addSource(w,key,{kind:mark>=200?'scholar':'merchant',originRealmId:holderRealm,originSettlementId:item.originSettlementId,createdYear:year,reliability:clamp(item.authenticity*(mark>=200?.84:.7),.2,.95),archiveStrength:clamp(item.durability+.12,.2,.99),text:`Copies of ${item.name} circulate widely and repeat its account of ${claim.trueTitle}.`});s.artifactId=item.id;s.copyEdition=mark;w.artifacts.stats.knowledgeSources++}}}
function recentConquest(w,year,item,r){const local=w.history.currentYear,ev=[...(w.history.events||[])].reverse().find(e=>e.year===local&&['conquest','war','uprising','collapse'].includes(e.type)&&(e.settlementIds||[]).includes(item.originSettlementId));if(!ev||r()>.075)return false;const victor=ev.realmIds?.[0];if(victor!=null&&item.ownerType!=='realm'){transfer(w,item.id,'realm',victor,'taken as war booty',year);return true}return false}
function maybeLoseOrRecover(w,item,year,r){if(item.status==='destroyed')return;if(item.status==='lost'){const site=item.siteId!=null?w.adventure?.sites?.find(s=>s.id===item.siteId):null;if((site?.discovered&&r()<.075)||r()<.0015*(1+item.prestige/100))rediscover(w,item.id,'realm',site?.realmId??item.originRealmId??0,year,site?`Recovered during exploration of ${site.name}`:'Recovered by antiquarians');return}const age=Math.max(0,year-item.createdYear),risk=.00045+age/180000+(1-item.durability)*.0014;if(age>12&&r()<risk)lose(w,item.id,siteForLoss(w,item,r),'custody breaks during generations of transfer',year)}
function decay(w,item,year,r){if(item.status==='destroyed')return;const age=Math.max(0,year-item.createdYear),loss=(1-item.durability)*.00013*(item.status==='lost'?2.2:1)*(1+Math.min(2,age/1800));item.condition=round(clamp(item.condition-loss-r()*.00003,0,1));if(item.condition<=.015&&item.prestige<82){item.status='destroyed';item.ownerType=null;item.ownerId=null;item.siteId=null;item.lastChangeYear=year;provenance(item,year,'destroyed',null,null,'Material decay ends the object’s physical history.');w.artifacts.stats.destroyed++}}
function simulateArtifactYear(w,year){sync(w);const items=[...w.artifacts.items];for(const item of items){const r=random(w,`${year}|life|${item.id}`);ownerDeath(w,item,year);recentConquest(w,year,item,r);spreadWrittenWork(w,item,year,r);maybeLoseOrRecover(w,item,year,r);decay(w,item,year,r)}compact(w)}
function simulateYears(w,years,options={}){initialize(w);if(!baseSimulator)throw new Error('Artifact base simulation unavailable');const n=Math.max(0,Math.floor(Number(years)||0));for(let i=0;i<n;i++){baseSimulator(w,1,options);simulateArtifactYear(w,absYear(w))}sync(w);return w.artifacts}
function simulateTo(w,target,options={}){const now=absYear(w),t=Math.floor(Number(target)||0);if(t<now)throw new Error('Artifacts cannot simulate backward');return simulateYears(w,t-now,options)}
function archiveBucket(a,year){const start=Math.floor(year/250)*250;let b=a.archives.find(x=>x.startYear===start);if(!b){b={startYear:start,endYear:start+249,total:0,kinds:{},notable:[]};a.archives.push(b);a.archives.sort((x,y)=>x.startYear-y.startYear)}return b}
function compact(w){const a=initialize(w),now=absYear(w),cut=now-a.settings.retainDetailedYears;if(a.items.length<=a.settings.maxDetailedItems&&cut<=0)return a;const removable=a.items.filter(x=>x.createdYear<cut&&(x.status==='destroyed'||x.status==='lost')&&x.prestige<75).sort((x,y)=>x.createdYear-y.createdYear);const need=Math.max(0,a.items.length-a.settings.maxDetailedItems),take=Math.max(need,Math.min(removable.length,Math.floor(removable.length*.45)));if(!take)return a;const ids=new Set(removable.slice(0,take).map(x=>x.id));for(const item of removable.slice(0,take)){const b=archiveBucket(a,item.createdYear);b.total++;b.kinds[item.kind]=(b.kinds[item.kind]||0)+1;if(item.prestige>60&&b.notable.length<12)b.notable.push({id:item.id,name:item.name,kind:item.kind,createdYear:item.createdYear,status:item.status})}a.items=a.items.filter(x=>!ids.has(x.id));a.stats.archived+=ids.size;return a}
function detail(w,id){const item=find(w,id);if(!item)return null;const viewer=w.knowledge?.viewerRealmId??null,claims=item.claimKeys.map(key=>Knowledge?.viewClaim?.(w,key,viewer)).filter(Boolean);return{...item,icon:ICON[item.kind]||'◆',ownerLabel:ownerLabel(w,item),claims}}
function list(w,options={}){sync(w);const year=Number.isFinite(Number(options.year))?Number(options.year):absYear(w),q=String(options.query||'').toLowerCase(),kind=options.kind||'all',status=options.status||'all';return w.artifacts.items.filter(x=>x.createdYear<=year&&(kind==='all'||x.kind===kind)&&(status==='all'||x.status===status)&&(!q||`${x.name} ${x.kind} ${x.contents} ${ownerLabel(w,x)}`.toLowerCase().includes(q))).sort((a,b)=>b.prestige-a.prestige||b.createdYear-a.createdYear)}
function summary(w){sync(w);const a=w.artifacts,items=a.items;return{total:items.length,written:items.filter(x=>x.written).length,lost:items.filter(x=>x.status==='lost').length,held:items.filter(x=>x.status==='held').length,destroyed:items.filter(x=>x.status==='destroyed').length,notable:items.filter(x=>x.prestige>=80).length,copies:items.filter(x=>x.written).reduce((n,x)=>n+x.copies,0),archives:a.archives.length,rediscovered:a.stats.rediscovered,transfers:a.stats.transfers}}
function fingerprint(w){sync(w);const a=w.artifacts;let h=2166136261>>>0;const raw=[a.nextId,a.archives.length,a.stats.created,a.stats.rediscovered,...a.items.slice(-300).map(x=>`${x.id}:${x.kind}:${x.status}:${x.ownerType}:${x.ownerId}:${x.copies}:${x.condition}:${x.provenance.length}`)].join('|');for(const ch of raw){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function validate(w){const a=w?.artifacts;if(!a||a.schemaVersion!==SCHEMA)return['artifact schema'];const errors=[],ids=new Set();for(const x of a.items){if(ids.has(x.id))errors.push('duplicate artifact id');ids.add(x.id);if(!x.name||!x.kind)errors.push('invalid artifact');if(x.written!==WRITTEN.has(x.kind))errors.push('written classification');if(x.condition<0||x.condition>1)errors.push('artifact condition');if(x.status==='lost'&&x.ownerType==='site'&&x.siteId==null)errors.push('lost site link');if((x.provenance||[]).length>30)errors.push('provenance budget')}if(a.items.length>a.settings.maxDetailedItems+120)errors.push('artifact detail budget');return[...new Set(errors)]}
const api={VERSION,SCHEMA,WRITTEN,EVENT_KINDS,ICON,initialize,setBaseSimulator,sync,createArtifact,createFromEvent,transfer,lose,rediscover,find,detail,list,summary,compact,simulateYears,simulateTo,fingerprint,validate,absYear,ownerLabel,holderRef};
return api;
});