(function(root,factory){
 const api=factory(root&&root.WorldForgeEngine,root&&root.WorldForgeHistory,root&&root.WorldForgeCity,root&&root.WorldForgeCulture);
 if(typeof module!=='undefined'&&module.exports)module.exports=api;
 if(root)root.WorldForgeCalendar=api;
})(typeof window!=='undefined'?window:globalThis,function(Core,History,City,Culture){
'use strict';
const VERSION='1.5.0',SCHEMA=1;
const MONTH_NAMES=['Firstdawn','Thawrise','Rainmoot','Greenwake','Highsun','Goldtide','Embercrest','Harvestwane','Redleaf','Mistfall','Frostcall','Longnight'];
const WEEKDAYS=['Moonday','Tideday','Wyrmday','Kingsday','Hearthday','Starday','Sunsday'];
const BIOME_YIELD={grassland:1.08,forest:1.02,temperateForest:1.02,savanna:.95,rainforest:.9,desert:.42,tundra:.5,taiga:.72,swamp:.76,shrubland:.85,alpine:.48};
let baseSimulator=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed);return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function baseSeed(w){return w.endless?.baseSeed||String(w.settings?.seed||'WORLD').split('|EPOCH:')[0]}
function rand(w,year,salt){return rng(`${baseSeed(w)}|CALENDAR|${year}|${salt}`)}
function absoluteYear(w){return(w.endless?.epochOffset||0)+(w.history?.currentYear||0)}
function setBaseSimulator(fn){if(typeof fn==='function')baseSimulator=fn;return api}
function calendar(){return{months:MONTH_NAMES.map((name,i)=>({id:i,name,days:i===11?35:30,northernSeason:i<2||i===11?'Winter':i<5?'Spring':i<8?'Summer':'Autumn',southernSeason:i<2||i===11?'Summer':i<5?'Autumn':i<8?'Winter':'Spring'})),weekdays:[...WEEKDAYS],daysPerYear:365,epoch:'Founding Reckoning'}}
function tileIndex(w,s){return s.y*w.settings.width+s.x}
function isWaterBiome(b){return b==='ocean'||b==='deepOcean'}
function coastal(w,s){const r=3;for(let y=Math.max(0,s.y-r);y<=Math.min(w.settings.height-1,s.y+r);y++)for(let x=Math.max(0,s.x-r);x<=Math.min(w.settings.width-1,s.x+r);x++)if(isWaterBiome(w.layers.biome[y*w.settings.width+x]))return true;return false}
function profile(w,s){const i=tileIndex(w,s),lat=90-(s.y/Math.max(1,w.settings.height-1))*180,temp=Number(w.layers.temperature[i]||.5),moist=Number(w.layers.moisture[i]||.5),elev=Number(w.layers.elevation[i]||.5),biome=w.layers.biome[i],river=(w.rivers||[]).some(r=>(r.points||[]).some(p=>Math.abs(p.x-s.x)<=2&&Math.abs(p.y-s.y)<=2)),coast=coastal(w,s);return{id:s.id,latitude:round(lat,2),elevation:round(elev,3),biome,coastal:coast,river,baseTempC:round(-13+temp*43-elev*5,1),baseRainMm:round(180+moist*1850+(coast?110:0),0),seasonAmplitude:round(6+Math.abs(lat)/90*19+(coast?-3:2),1),growingPotential:round(clamp((BIOME_YIELD[biome]||.82)*(1-Math.max(0,elev-.72)*1.6),.2,1.2),3)} }
function initialize(w){if(!w)throw new Error('World required');History?.initialize?.(w);if(w.calendarClimate&&w.calendarClimate.schemaVersion===SCHEMA){w.calendarClimate.engineVersion=VERSION;return w.calendarClimate}const profiles=w.settlements.map(s=>profile(w,s)),y=absoluteYear(w),c={schemaVersion:SCHEMA,engineVersion:VERSION,calendar:calendar(),profiles,current:null,yearSummaries:[],phenomena:[],archives:[],settings:{retainDetailedYears:320,maxPhenomena:420},stats:{years:0,droughts:0,floods:0,storms:0,harshWinters:0,heatwaves:0,goodHarvests:0,eclipses:0,comets:0,auroras:0}};w.calendarClimate=c;c.current=computeYear(w,y,false);recordSummary(w,c.current,true);return c}
function seasonalTemp(p,month){const theta=((month+0.5)/12)*Math.PI*2-Math.PI/2,hemi=p.latitude>=0?1:-1;return p.baseTempC+Math.sin(theta)*p.seasonAmplitude*hemi}
function monthlyWeather(w,sid,year,month){const c=initialize(w),p=c.profiles[sid],r=rand(w,year,`month:${sid}:${month}`),temp=seasonalTemp(p,month)+(r()+r()+r()-1.5)*3.2+climateOscillation(w,year).temp,wetSeason=.82+Math.sin((month/12)*Math.PI*2+(p.latitude>=0?0:Math.PI))*.2,rain=Math.max(2,(p.baseRainMm/12)*wetSeason*(.55+r()*.95)*(1+climateOscillation(w,year).rain*.01));let condition='Fair';if(temp<-8)condition=rain>55?'Snowstorm':'Hard frost';else if(temp<1)condition=rain>65?'Snow':'Cold';else if(rain>180)condition='Torrential rain';else if(rain>105)condition=p.coastal&&r()>.68?'Coastal storm':'Heavy rain';else if(rain<22&&temp>25)condition='Dry heat';else if(temp>34)condition='Heatwave';else if(rain>65)condition='Rain';else if(r()>.78)condition='Cloudy';return{month,monthName:c.calendar.months[month].name,season:p.latitude>=0?c.calendar.months[month].northernSeason:c.calendar.months[month].southernSeason,tempC:round(temp,1),rainMm:round(rain,0),condition,daylightHours:round(daylightHours(p.latitude,month),1)}}
function daylightHours(lat,month){const decl=-23.44*Math.cos(2*Math.PI*(month+.5)/12),phi=lat*Math.PI/180,d=decl*Math.PI/180,x=clamp(-Math.tan(phi)*Math.tan(d),-1,1);return clamp(24*Math.acos(x)/Math.PI,0,24)}
function climateOscillation(w,year){const r=rand(w,year,'global'),temp=.7*Math.sin(year*Math.PI*2/71)+.35*Math.sin(year*Math.PI*2/19)+(r()+r()-1)*1.15,rain=9*Math.sin(year*Math.PI*2/37)+(r()+r()-1)*18;return{temp:round(temp,3),rain:round(rain,2)}}
function celestial(w,year){const r=rand(w,year,'sky'),events=[];if(r()<.065){const m=Math.floor(r()*12),d=1+Math.floor(r()*28);events.push({type:'eclipse',month:m,day:d,title:'Solar eclipse',importance:2,text:`A solar eclipse crosses parts of the known world during ${MONTH_NAMES[m]}.`})}if(r()<.022){const m=Math.floor(r()*12);events.push({type:'comet',month:m,day:4+Math.floor(r()*22),title:'Great comet',importance:3,text:`A bright comet remains visible for several nights above the world.`})}if(r()<.13){events.push({type:'aurora',month:r()<.5?0:11,day:8+Math.floor(r()*17),title:'Great aurora',importance:1,text:'Unusually strong auroral lights are reported at high latitudes.'})}return{events,majorMoon:'Silver Moon',synodicDays:29.53}}
function computeSettlementYear(w,p,year,osc){const r=rand(w,year,`settlement:${p.id}`),annualTemp=p.baseTempC+osc.temp+(r()+r()-1)*1.4,annualRain=Math.max(40,p.baseRainMm*(1+osc.rain/100+(r()+r()-1)*.18)),summer=annualTemp+p.seasonAmplitude*.62,winter=annualTemp-p.seasonAmplitude*.62,drought=clamp((p.baseRainMm*.72-annualRain)/Math.max(150,p.baseRainMm*.65)+(summer>31?(summer-31)/18:0),0,1),flood=clamp((annualRain-p.baseRainMm*1.32)/Math.max(180,p.baseRainMm*.55)+(p.river?.18:0),0,1),storm=clamp((p.coastal?.18:0)+(annualRain>p.baseRainMm*1.25?.2:0)+(r()>.88?.22:0),0,1),winterSeverity=clamp((-winter-2)/25+(r()>.92?.18:0),0,1),heat=clamp((summer-31)/18,0,1),tempSuit=clamp(1-Math.abs(annualTemp-13)/25,.15,1),rainSuit=clamp(1-Math.abs(Math.log(Math.max(80,annualRain)/760))*.48,.15,1.08),crop=clamp(p.growingPotential*tempSuit*rainSuit*(1-drought*.55-flood*.28-storm*.12-winterSeverity*.12),.12,1.35),foodStress=clamp((.78-crop)/.72,0,1);return{id:p.id,tempC:round(annualTemp,1),rainMm:round(annualRain,0),drought:round(drought),flood:round(flood),storm:round(storm),winterSeverity:round(winterSeverity),heat:round(heat),cropYield:round(crop),foodStress:round(foodStress)}}
function computeYear(w,year,withEvents=true){const c=w.calendarClimate||initialize(w),osc=climateOscillation(w,year),settlement=c.profiles.map(p=>computeSettlementYear(w,p,year,osc)),sky=celestial(w,year),mean=k=>settlement.reduce((a,x)=>a+Number(x[k]||0),0)/Math.max(1,settlement.length),extremes=settlement.filter(x=>Math.max(x.drought,x.flood,x.storm,x.winterSeverity,x.heat)>.62).length;const out={absoluteYear:year,globalTempAnomaly:osc.temp,globalRainAnomaly:osc.rain,meanCropYield:round(mean('cropYield')),meanFoodStress:round(mean('foodStress')),extremeCount:extremes,settlement,celestial:sky};if(withEvents)emitEvents(w,out);return out}
function pushHistory(w,e){const h=History.initialize(w);h.events.push({id:h.events.length,year:h.currentYear,absoluteYear:absoluteYear(w),...e})}
function emitEvents(w,y){const c=w.calendarClimate,candidates=[];for(const x of y.settlement){const s=w.settlements[x.id],rid=w.history.current.settlementKingdomIds[x.id];if(x.drought>.76)candidates.push({sev:x.drought,type:'drought',title:`Drought grips ${s.name}`,text:`Rainfall failure cuts the harvest around ${s.name}.`,sid:x.id,rid,stat:'droughts'});if(x.flood>.78)candidates.push({sev:x.flood,type:'flood',title:`Floods strike ${s.name}`,text:`Rivers and saturated ground inundate fields around ${s.name}.`,sid:x.id,rid,stat:'floods'});if(x.storm>.82)candidates.push({sev:x.storm,type:'great_storm',title:`Great storm at ${s.name}`,text:`Severe weather disrupts roads, markets and local harvests.`,sid:x.id,rid,stat:'storms'});if(x.winterSeverity>.78)candidates.push({sev:x.winterSeverity,type:'harsh_winter',title:`The hard winter of ${s.name}`,text:`Cold and frost damage stores and winter crops.`,sid:x.id,rid,stat:'harshWinters'});if(x.heat>.8)candidates.push({sev:x.heat,type:'heatwave',title:`Heatwave in ${s.name}`,text:`Extreme summer heat strains wells, livestock and crops.`,sid:x.id,rid,stat:'heatwaves'});if(x.cropYield>1.22)candidates.push({sev:x.cropYield-1,type:'good_harvest',title:`Bountiful harvest at ${s.name}`,text:`Favorable weather produces an exceptional harvest.`,sid:x.id,rid,stat:'goodHarvests'})}candidates.sort((a,b)=>b.sev-a.sev);for(const e of candidates.slice(0,Math.min(5,1+Math.floor(candidates.length/10)))){c.stats[e.stat]++;const importance=e.sev>.9?2:1;pushHistory(w,{type:e.type,importance,settlementIds:[e.sid],realmIds:[e.rid],title:e.title,text:e.text});c.phenomena.push({year:y.absoluteYear,type:e.type,title:e.title,settlementId:e.sid,severity:round(e.sev),importance})}for(const e of y.celestial.events){if(e.type==='eclipse')c.stats.eclipses++;if(e.type==='comet')c.stats.comets++;if(e.type==='aurora')c.stats.auroras++;pushHistory(w,{type:e.type,importance:e.importance,title:e.title,text:e.text});c.phenomena.push({year:y.absoluteYear,type:e.type,title:e.title,settlementId:null,severity:e.importance/3,importance:e.importance})}c.phenomena=c.phenomena.slice(-c.settings.maxPhenomena)}
function applyFeedback(w,y){const h=History.initialize(w),realmShock=new Map();for(const x of y.settlement){const sid=x.id,old=h.current.settlementProsperity[sid]??.5,delta=clamp((x.cropYield-1)*.048,-.035,.018);h.current.settlementProsperity[sid]=round(clamp(old+delta,.05,.98),4);if(x.foodStress>.58){const loss=clamp((x.foodStress-.58)*.014,0,.0075);h.current.settlementPopulation[sid]=Math.max(20,Math.round(h.current.settlementPopulation[sid]*(1-loss)))}const rid=h.current.settlementKingdomIds[sid];realmShock.set(rid,(realmShock.get(rid)||0)+(x.foodStress-.25));const city=w.cities?.cities?.[sid];if(city){city.prosperity=round(clamp((city.prosperity??old)+delta*.7,.05,.98),4);city.priceIndex=round(clamp((city.priceIndex||100)+(x.foodStress-.2)*4-(x.cropYield-1)*2,45,260),2);city.unemployment=round(clamp((city.unemployment||.08)+Math.max(0,x.foodStress-.5)*.004,0,.6),4);city.crimeRate=round(clamp((city.crimeRate||0)+Math.max(0,x.foodStress-.65)*.7,0,100),2)}}for(const [rid,raw] of realmShock){const r=h.current.realmState[rid];if(!r)continue;const count=h.current.settlementKingdomIds.filter(x=>x===rid).length||1,stress=raw/count;r.stability=round(clamp((r.stability??50)-Math.max(0,stress)*.7+Math.max(0,-stress)*.18,0,100),2)}const tradeFactor=clamp(1-y.meanFoodStress*.035-y.extremeCount/Math.max(1,w.settlements.length)*.025,.91,1.01);h.current.tradeVolumes=h.current.tradeVolumes.map(v=>round(Number(v||0)*tradeFactor,2));if(y.celestial.events.some(e=>e.type==='eclipse'||e.type==='comet')&&w.culture?.religions){for(const rel of w.culture.religions.filter(x=>x.active!==false))rel.fervor=round(clamp((rel.fervor||50)+.35,0,100),1)}}
function recordSummary(w,y,force=false){const c=w.calendarClimate;if(!force&&c.yearSummaries.at(-1)?.absoluteYear===y.absoluteYear)return;c.yearSummaries.push({absoluteYear:y.absoluteYear,globalTempAnomaly:y.globalTempAnomaly,globalRainAnomaly:y.globalRainAnomaly,meanCropYield:y.meanCropYield,meanFoodStress:y.meanFoodStress,extremeCount:y.extremeCount,celestial:y.celestial.events.map(e=>e.type)});compact(w)}
function compact(w){const c=w.calendarClimate,now=c.current?.absoluteYear??absoluteYear(w),cut=now-c.settings.retainDetailedYears;if(c.yearSummaries.length>c.settings.retainDetailedYears+80){const old=c.yearSummaries.filter(x=>x.absoluteYear<cut),keep=c.yearSummaries.filter(x=>x.absoluteYear>=cut);for(const x of old){const start=Math.floor(x.absoluteYear/250)*250;let a=c.archives.find(z=>z.startYear===start);if(!a){a={startYear:start,endYear:start+249,years:0,tempSum:0,rainSum:0,cropSum:0,stressSum:0,extremes:0,celestial:0};c.archives.push(a)}a.years++;a.tempSum+=x.globalTempAnomaly;a.rainSum+=x.globalRainAnomaly;a.cropSum+=x.meanCropYield;a.stressSum+=x.meanFoodStress;a.extremes+=x.extremeCount;a.celestial+=x.celestial.length}c.yearSummaries=keep;c.archives.sort((a,b)=>a.startYear-b.startYear);if(c.archives.length>220)c.archives=c.archives.slice(-220)}}
function simulateClimateYear(w){const c=initialize(w),year=absoluteYear(w),y=computeYear(w,year,true);c.current=y;c.stats.years++;applyFeedback(w,y);recordSummary(w,y);return y}
function simulateYears(w,years,options={}){initialize(w);const n=Math.max(0,Math.floor(Number(years)||0));if(!baseSimulator)throw new Error('Calendar base simulator unavailable');for(let i=0;i<n;i++){baseSimulator(w,1,options);simulateClimateYear(w)}return w.calendarClimate}
function simulateTo(w,target,options={}){const t=Math.floor(Number(target)||0),now=absoluteYear(w);if(t<now)throw new Error('Calendar simulation cannot run backward');return simulateYears(w,t-now,options)}
function almanac(w,sid,year=absoluteYear(w)){initialize(w);sid=clamp(Math.floor(Number(sid)||0),0,w.settlements.length-1);return{year,settlement:w.settlements[sid],profile:w.calendarClimate.profiles[sid],months:Array.from({length:12},(_,m)=>monthlyWeather(w,sid,year,m)),celestial:celestial(w,year)}}
function dateInfo(w,sid,year,month,day){const a=almanac(w,sid,year),m=clamp(Math.floor(month),0,11),d=clamp(Math.floor(day),1,a.months[m].month===11?35:30),ordinal=m*30+d,moonAge=((year*365+ordinal)%29.53+29.53)%29.53,phase=moonAge<1.85?'New Moon':moonAge<7.38?'Waxing Crescent':moonAge<9.23?'First Quarter':moonAge<14.77?'Waxing Gibbous':moonAge<16.61?'Full Moon':moonAge<22.15?'Waning Gibbous':moonAge<23.99?'Last Quarter':'Waning Crescent';return{...a.months[m],day,ordinal,weekday:WEEKDAYS[(year*365+ordinal)%7],moonPhase:phase,moonIllumination:round((1-Math.cos(2*Math.PI*moonAge/29.53))/2,2),events:a.celestial.events.filter(e=>e.month===m&&Math.abs(e.day-d)<=2)}}
function summary(w){const c=initialize(w),y=c.current;return{year:y.absoluteYear,tempAnomaly:y.globalTempAnomaly,rainAnomaly:y.globalRainAnomaly,cropYield:y.meanCropYield,foodStress:y.meanFoodStress,extremes:y.extremeCount,phenomena:c.phenomena.length,archives:c.archives.length,stats:{...c.stats}}}
function fingerprint(w){const c=initialize(w),s=summary(w),str=`${s.year}|${s.tempAnomaly}|${s.rainAnomaly}|${s.cropYield}|${s.foodStress}|${c.stats.droughts}|${c.stats.floods}|${c.stats.eclipses}|${c.yearSummaries.slice(-12).map(x=>`${x.absoluteYear}:${x.meanCropYield}`).join(',')}`;return hash(str).toString(16).padStart(8,'0')}
function validate(w){const c=w.calendarClimate,errors=[];if(!c||c.schemaVersion!==SCHEMA)return['calendar climate schema'];if(c.profiles.length!==w.settlements.length)errors.push('climate profiles');if(c.current?.settlement?.length!==w.settlements.length)errors.push('current climate settlements');if(!c.calendar||c.calendar.months.length!==12||c.calendar.daysPerYear!==365)errors.push('calendar structure');if(c.yearSummaries.some((x,i,a)=>i&&x.absoluteYear<=a[i-1].absoluteYear))errors.push('climate chronology');return errors}
const api={VERSION,SCHEMA,MONTH_NAMES,WEEKDAYS,initialize,setBaseSimulator,absoluteYear,monthlyWeather,almanac,dateInfo,summary,fingerprint,validate,simulateYears,simulateTo,computeYear,climateOscillation};
return api;
});