(function(root,factory){
  const api=factory(root&&root.WorldForgeEngine,root&&root.WorldForgeHistory,root&&root.WorldForgeSociety);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeCity=api;
})(typeof window!=='undefined'?window:globalThis,function(Core,History,Society){
'use strict';

const VERSION='0.4.0';
const CITY_SCHEMA=1;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const round=(v,d=2)=>Number(Number(v).toFixed(d));
const capturedSocietySimulate=Society&&Society.simulateYears?Society.simulateYears.bind(Society):null;
const GANG_COLORS=['#b85b53','#8c6ac4','#d28a42','#4c9a86','#ba668d','#718bc1','#8fa04f','#aa7357'];
const GANG_A=['Black','Ash','Gilded','Red','Pale','Iron','Night','Broken','Silver','Hollow','Velvet','Grim','Cinder','Glass','Crooked','Silent'];
const GANG_B=['Lanterns','Knives','Crows','Hounds','Serpents','Coins','Hands','Wolves','Rooks','Hooks','Masks','Rats','Vipers','Keys','Sashes','Bells'];
const BUSINESS_A=['Copper','Golden','Moon','River','Crown','Oak','Black','Silver','Red','Dawn','Lantern','Three','Old','West','Iron','Velvet'];
const BUSINESS_B=['Kettle','Fox','Hammer','Cup','Stag','Wheel','Quill','Gate','Anvil','Lily','Boar','Cask','Needle','Bell','Mason','Heron'];
const SPECIALTIES=['Smuggling','Extortion','Contraband','Protection rackets','Burglary','Forgery','Fence network','Black-market trade'];
const SECTORS=['Food','Crafts','Trade','Lodging','Services','Luxury','Warehousing'];

function fallbackRng(seed){let h=2166136261>>>0;for(const ch of String(seed)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return function(){h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function rngFor(world,year,salt=''){return (Core?.rngFromSeed||fallbackRng)(`${world.settings.seed}|CITY|${year}|${salt}`)}
function pick(rng,a){return a[Math.floor(rng()*a.length)]}
function history(world){if(!History)throw new Error('WorldForgeHistory is required');return History.initialize(world)}
function society(world){if(!Society)throw new Error('WorldForgeSociety is required');return Society.initialize(world)}
function aliveAt(p,year){return !!p&&p.birthYear<=year&&(p.deathYear==null||p.deathYear>year)}
function fullName(world,id){const p=world.society?.people?.[id];return p?Society.fullName(world.society,p):'Unknown'}
function ownerAt(world,sid){return world.history.current.settlementKingdomIds[sid]}
function activeWarForRealm(world,rid){return world.history.current.activeWarIds.some(id=>{const w=world.history.wars[id];return w&&(w.attackerId===rid||w.defenderId===rid)})}
function coastAt(world,s){const W=world.settings.width,H=world.settings.height,sea=world.settings.seaLevel,E=world.layers.elevation;for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){if(!ox&&!oy)continue;const y=s.y+oy;if(y<0||y>=H)continue;const x=(s.x+ox+W)%W;if(E[y*W+x]<sea)return true}return false}
function riverNear(world,s,max=2.4){for(const r of world.rivers)for(const p of r.path){let dx=Math.abs(p.x-s.x);dx=Math.min(dx,world.settings.width-dx);if(Math.hypot(dx,p.y-s.y)<=max)return true}return false}
function cityClass(settlement){return settlement.capital?'Capital':settlement.type}
function districtKinds(world,s){
  const type=cityClass(s);let kinds=type==='Capital'?['Government','Old Town','Market','Residential','Crafts','Temple','Wealthy Quarter','Slums','Outskirts']:
    type==='City'?['Old Town','Market','Residential','Crafts','Temple','Wealthy Quarter','Slums','Outskirts']:
    type==='Town'?['Market','Residential','Crafts','Temple','Outskirts','Low Quarter']:
    ['Village Green','Homes','Fields','Shrine'];
  if(coastAt(world,s)&&!kinds.includes('Docks'))kinds.splice(Math.min(3,kinds.length),0,'Docks');
  if(riverNear(world,s)&&!kinds.includes('River Ward'))kinds.splice(Math.min(4,kinds.length),0,'River Ward');
  return kinds
}
function districtAttraction(kind){return ({Slums:.95,'Low Quarter':.78,Docks:.72,Market:.62,'Old Town':.55,Crafts:.50,'River Ward':.48,Outskirts:.44,Residential:.34,'Village Green':.20,Homes:.18,Temple:.12,Government:.08,'Wealthy Quarter':.26,Fields:.09,Shrine:.05}[kind]??.30)}
function districtWealth(kind){return ({'Wealthy Quarter':.92,Government:.84,Market:.72,Temple:.62,'Old Town':.58,Docks:.56,Crafts:.54,'River Ward':.50,Residential:.48,Outskirts:.34,'Low Quarter':.25,Slums:.18,'Village Green':.40,Homes:.38,Fields:.31,Shrine:.42}[kind]??.45)}
function buildDistricts(world,sid,rng){
  const s=world.settlements[sid],kinds=districtKinds(world,s),n=kinds.length,out=[];
  const coreIndex=Math.max(0,kinds.findIndex(k=>k==='Market'||k==='Government'||k==='Village Green'));
  for(let i=0;i<n;i++){
    const angle=(i-coreIndex)*Math.PI*2/n+(rng()-.5)*.22,radius=i===coreIndex?0:.22+.13*(i%3)+rng()*.08;
    out.push({id:`${sid}:${i}`,index:i,name:kinds[i],kind:kinds[i],x:clamp(.5+Math.cos(angle)*radius,.08,.92),y:clamp(.5+Math.sin(angle)*radius,.08,.92),w:round(.15+rng()*.08,3),h:round(.12+rng()*.08,3),populationShare:0,wealth:round(districtWealth(kinds[i]),3),criminalAttraction:round(districtAttraction(kinds[i]),3)});
  }
  const weights=out.map(d=>.35+(['Residential','Homes'].includes(d.kind)?1.30:['Slums','Low Quarter'].includes(d.kind)?1.00:['Outskirts','Fields'].includes(d.kind)?.75:.55)+rng()*.30),sum=weights.reduce((a,b)=>a+b,0);
  out.forEach((d,i)=>d.populationShare=round(weights[i]/sum,4));return out
}
function buildRoads(city){const d=city.districts,core=d.find(x=>['Market','Government','Village Green'].includes(x.kind))||d[0],edges=[];for(const q of d)if(q.id!==core.id)edges.push([core.id,q.id]);for(let i=0;i<d.length;i++){const a=d[i],b=d[(i+1)%d.length];if(a.id!==core.id&&b.id!==core.id)edges.push([a.id,b.id])}return edges}
function roleCandidate(world,sid,year,roles,used=new Set()){
  const owner=ownerAt(world,sid),alive=world.society.people.filter(p=>aliveAt(p,year)&&!used.has(p.id));
  const score=p=>(p.settlementId===sid?50:0)+(p.realmId===owner?20:0)+(roles.includes(p.occupation)?35:0)+p.prestige*.20+p.wealth*.05;
  alive.sort((a,b)=>score(b)-score(a)||a.id-b.id);return alive[0]||null
}
function makeBusinessName(rng,sector){return `${pick(rng,BUSINESS_A)} ${pick(rng,BUSINESS_B)} ${sector==='Lodging'?'Inn':sector==='Food'?'House':sector==='Crafts'?'Works':sector==='Trade'?'Company':sector==='Warehousing'?'Warehouse':'Guild'}`}
function buildBusinesses(world,city,rng,year){
  const pop=world.history.current.settlementPopulation[city.id],count=clamp(Math.round(3+Math.sqrt(pop)/18+(city.type==='Capital'?7:city.type==='City'?4:0)),3,26),usedOwners=new Set(),out=[];
  for(let i=0;i<count;i++){
    const sector=pick(rng,SECTORS),districtPool=city.districts.filter(d=>sector==='Luxury'?['Wealthy Quarter','Market','Old Town'].includes(d.kind):sector==='Warehousing'?['Docks','Market','River Ward','Outskirts'].includes(d.kind):sector==='Crafts'?['Crafts','Market','Old Town'].includes(d.kind):true),d=pick(rng,districtPool.length?districtPool:city.districts),owner=roleCandidate(world,city.id,year,sector==='Trade'?['Merchant','Diplomat']:sector==='Crafts'?['Artisan','Architect']:['Merchant','Artisan','Steward'],usedOwners);
    if(owner)usedOwners.add(owner.id);
    out.push({id:`${city.id}:B${i}`,cityId:city.id,name:makeBusinessName(rng,sector),sector,districtId:d.id,ownerId:owner?.id??null,foundedYear:year,active:true,tier:1+Math.floor(rng()*3),health:round(.45+rng()*.45,3)});
  }
  return out
}
function gangName(rng){return `${pick(rng,GANG_A)} ${pick(rng,GANG_B)}`}
function chooseGangLeader(world,city,year,used){
  const candidates=world.society.people.filter(p=>aliveAt(p,year)&&!used.has(p.id)&&(p.settlementId===city.id||p.realmId===ownerAt(world,city.id)));
  const score=p=>(p.settlementId===city.id?35:0)+(p.traits?.includes('cunning')?28:0)+(p.traits?.includes('ambitious')?20:0)+(p.traits?.includes('pragmatic')?12:0)+(['Merchant','Soldier','Explorer','Artisan'].includes(p.occupation)?10:0)+p.prestige*.15;
  candidates.sort((a,b)=>score(b)-score(a)||a.id-b.id);return candidates[0]||roleCandidate(world,city.id,year,['Merchant','Soldier'],used)
}
function addGang(world,c,city,year,rng,usedLeaders=new Set()){
  const id=c.gangs.length,leader=chooseGangLeader(world,city,year,usedLeaders);if(leader)usedLeaders.add(leader.id);
  const attractive=[...city.districts].sort((a,b)=>b.criminalAttraction-a.criminalAttraction),territory=attractive.slice(0,1+Math.floor(rng()*Math.min(2,attractive.length))).map(d=>d.id);
  const g={id,cityId:city.id,name:gangName(rng),color:GANG_COLORS[id%GANG_COLORS.length],leaderId:leader?.id??null,foundedYear:year,dissolvedYear:null,active:true,specialty:pick(rng,SPECIALTIES),members:Math.round(12+rng()*45),influence:round(18+rng()*35,1),heat:round(8+rng()*24,1),treasury:round(20+rng()*90,1),territoryIds:territory,rivalIds:[]};
  c.gangs.push(g);c.stats.gangsFormed++;return g
}
function linkRivals(c){for(const city of c.cities){const gs=c.gangs.filter(g=>g.cityId===city.id&&g.active);for(const g of gs)g.rivalIds=gs.filter(x=>x.id!==g.id).map(x=>x.id)}}
function createCity(world,sid,year){
  const rng=rngFor(world,year,`city-${sid}`),s=world.settlements[sid],districts=buildDistricts(world,sid,rng),city={id:sid,settlementId:sid,name:s.name,type:cityClass(s),coastal:coastAt(world,s),river:riverNear(world,s),districts,roads:[],businesses:[],officials:{magistrateId:null,watchCaptainId:null,merchantPatronId:null},population:0,prosperity:0,wealth:0,trade:0,unemployment:0,guardStrength:0,corruption:0,crimeRate:0,blackMarket:0,priceIndex:100,businessHealth:.6};
  city.roads=buildRoads(city);city.businesses=buildBusinesses(world,city,rng,year);refreshOfficials(world,city,year);seedCityDynamics(world,city,year,rng);return city
}
function refreshOfficials(world,city,year){const used=new Set(),choose=roles=>{const p=roleCandidate(world,city.id,year,roles,used);if(p)used.add(p.id);return p?.id??null};if(!aliveAt(world.society.people[city.officials.magistrateId],year))city.officials.magistrateId=choose(['Magistrate','Steward','Ruler','Diplomat']);if(!aliveAt(world.society.people[city.officials.watchCaptainId],year))city.officials.watchCaptainId=choose(['Soldier','Magistrate','Ruler']);if(!aliveAt(world.society.people[city.officials.merchantPatronId],year))city.officials.merchantPatronId=choose(['Merchant','Artisan','Steward'])}
function cityTrade(world,sid){let total=0;world.roads.forEach((r,i)=>{if(r.from===sid||r.to===sid)total+=world.history.current.tradeVolumes[i]||0});return total}
function seedCityDynamics(world,city,year,rng){const h=world.history.current,pop=h.settlementPopulation[city.id],pros=h.settlementProsperity[city.id],wealth=h.settlementWealth[city.id],trade=cityTrade(world,city.id),urban=city.type==='Capital'?1:city.type==='City'?.85:city.type==='Town'?.58:.24;city.population=pop;city.prosperity=round(pros,4);city.wealth=round(wealth,2);city.trade=round(trade,1);city.unemployment=round(clamp(.20-pros*.12+(rng()-.5)*.04,.02,.34),3);city.guardStrength=round(clamp(38+pros*35+urban*9+rng()*14,10,95),1);city.corruption=round(clamp(18+urban*12+(1-pros)*26+rng()*18,3,88),1);city.crimeRate=round(clamp(12+city.unemployment*45+city.corruption*.28+(100-city.guardStrength)*.17+urban*7,2,95),1);city.blackMarket=round(clamp(city.crimeRate*.55+city.corruption*.28+urban*9,1,100),1);city.priceIndex=round(94+(1-pros)*12+urban*3+(rng()-.5)*3,1);city.businessHealth=round(clamp(.35+pros*.55-city.crimeRate*.0025,.15,1.15),3)}
function seedGangs(world,c,year){const used=new Set();for(const city of c.cities){const rng=rngFor(world,year,`seed-gangs-${city.id}`),pop=world.history.current.settlementPopulation[city.id],base=city.type==='Capital'?2:city.type==='City'?1:city.type==='Town'&&pop>3500?1:0,count=base+(pop>18000&&rng()<.70?1:0);for(let i=0;i<count;i++)addGang(world,c,city,year,rng,used)}linkRivals(c)}
function initialize(world,options={}){
  history(world);society(world);if(world.cities&&world.cities.schemaVersion===CITY_SCHEMA){normalize(world,world.cities);return world.cities}
  const year=world.history.currentYear,c={schemaVersion:CITY_SCHEMA,engineVersion:VERSION,startYear:year,currentYear:year,cities:[],gangs:[],snapshots:[],stats:{gangsFormed:0,gangsDissolved:0,gangWars:0,crackdowns:0,smugglingEvents:0,extortionEvents:0,arrests:0,crimeEvents:0,businessBooms:0}};world.cities=c;
  for(let sid=0;sid<world.settlements.length;sid++)c.cities.push(createCity(world,sid,year));seedGangs(world,c,year);recompute(world,c,year);takeSnapshot(world,c,true);return c
}
function normalize(world,c){c.engineVersion=VERSION;c.stats={gangsFormed:0,gangsDissolved:0,gangWars:0,crackdowns:0,smugglingEvents:0,extortionEvents:0,arrests:0,crimeEvents:0,businessBooms:0,...c.stats};c.snapshots=c.snapshots||[];c.gangs=c.gangs||[];for(const city of c.cities||[]){city.businesses=city.businesses||[];city.officials=city.officials||{magistrateId:null,watchCaptainId:null,merchantPatronId:null}}return c}
function pushEvent(world,e){const h=history(world);h.events.push({id:h.events.length,year:h.currentYear,...e})}
function gangPressure(c,cityId){const gs=c.gangs.filter(g=>g.active&&g.cityId===cityId);return gs.reduce((n,g)=>n+g.influence,0)/Math.max(1,gs.length)}
function counters(world){return world.cities.stats}
function updateBusinesses(world,city,year,rng){for(const b of city.businesses){if(!b.active)continue;const sectorBoost=b.sector==='Trade'?Math.log1p(city.trade)*.008:b.sector==='Luxury'?city.prosperity*.06:b.sector==='Warehousing'?Math.log1p(city.trade)*.006:.03,pressure=city.crimeRate*.0009;b.health=round(clamp(b.health+(city.prosperity-.5)*.025+sectorBoost-pressure+(rng()-.5)*.045,.05,1.35),3);if(b.health<.09&&rng()<.12)b.active=false;else if(b.health>1.12&&b.tier<5&&rng()<.08)b.tier++}if(city.businessHealth>.82&&rng()<.018){const active=city.businesses.filter(b=>b.active),b=active.length?pick(rng,active):null;if(b){counters(world).businessBooms++;pushEvent(world,{type:'business_boom',importance:1,realmIds:[ownerAt(world,city.id)],settlementIds:[city.id],personIds:[b.ownerId].filter(Number.isInteger),title:`Commercial boom in ${city.name}`,text:`${b.name} expands as local trade and demand rise.`})}}}
function updateCity(world,c,city,year){const rng=rngFor(world,year,`city-update-${city.id}`),h=world.history.current,pop=h.settlementPopulation[city.id],pros=h.settlementProsperity[city.id],wealth=h.settlementWealth[city.id],trade=cityTrade(world,city.id),rid=ownerAt(world,city.id),war=activeWarForRealm(world,rid),urban=city.type==='Capital'?1:city.type==='City'?.85:city.type==='Town'?.58:.24,pressure=gangPressure(c,city.id);city.population=pop;city.prosperity=round(pros,4);city.wealth=round(wealth,2);city.trade=round(trade,1);const unemploymentTarget=clamp(.19-pros*.13-Math.min(.06,Math.log1p(trade)*.004)+(war?.07:0),.02,.45);city.unemployment=round(clamp(city.unemployment*.78+unemploymentTarget*.22+(rng()-.5)*.008,.01,.50),3);const corruptionTarget=clamp(12+urban*10+(1-pros)*30+pressure*.28+(war?7:0),2,96);city.corruption=round(clamp(city.corruption*.86+corruptionTarget*.14+(rng()-.5)*2.2,0,100),1);const guardTarget=clamp(34+pros*35+(100-city.corruption)*.18+urban*10+(war?8:0),8,98);city.guardStrength=round(clamp(city.guardStrength*.84+guardTarget*.16+(rng()-.5)*2,5,100),1);const crimeTarget=clamp(8+city.unemployment*62+city.corruption*.30+(100-city.guardStrength)*.20+pressure*.24+urban*6+(war?9:0),1,100);city.crimeRate=round(clamp(city.crimeRate*.80+crimeTarget*.20+(rng()-.5)*1.8,0,100),1);city.blackMarket=round(clamp(city.blackMarket*.78+(city.crimeRate*.56+city.corruption*.28+pressure*.22+urban*7)*.22,0,100),1);city.priceIndex=round(clamp(city.priceIndex*.88+(96+(1-pros)*14+city.unemployment*18+(war?8:0))*.12+(rng()-.5)*.7,75,180),1);city.businessHealth=round(clamp(city.businessHealth*.85+(.35+pros*.57-city.crimeRate*.0028+Math.min(.12,Math.log1p(trade)*.006))*.15,.08,1.25),3);refreshOfficials(world,city,year);updateBusinesses(world,city,year,rng)}
function refreshGangLeader(world,c,g,year,rng){const current=world.society.people[g.leaderId];if(aliveAt(current,year))return;const used=new Set(c.gangs.filter(x=>x.active&&x.id!==g.id).map(x=>x.leaderId).filter(Number.isInteger)),city=c.cities[g.cityId],next=chooseGangLeader(world,city,year,used);g.leaderId=next?.id??null;if(next)pushEvent(world,{type:'gang_succession',importance:1,realmIds:[ownerAt(world,g.cityId)],settlementIds:[g.cityId],personIds:[next.id],gangIds:[g.id],title:`New leader of the ${g.name}`,text:`${fullName(world,next.id)} takes control of the ${g.name} in ${city.name}.`})}
function dissolveGang(world,c,g,year,reason){if(!g.active)return;g.active=false;g.dissolvedYear=year;c.stats.gangsDissolved++;pushEvent(world,{type:'gang_dissolved',importance:1,realmIds:[ownerAt(world,g.cityId)],settlementIds:[g.cityId],personIds:[g.leaderId].filter(Number.isInteger),gangIds:[g.id],title:`${g.name} broken`,text:reason})}
function expandTerritory(city,g,rng){const candidates=city.districts.filter(d=>!g.territoryIds.includes(d.id)).sort((a,b)=>b.criminalAttraction-a.criminalAttraction);if(candidates.length){const pickFrom=candidates.slice(0,Math.min(3,candidates.length));g.territoryIds.push(pick(rng,pickFrom).id)}}
function updateGang(world,c,g,year){if(!g.active)return;const rng=rngFor(world,year,`gang-${g.id}`),city=c.cities[g.cityId];refreshGangLeader(world,c,g,year,rng);const attract=(city.crimeRate+city.blackMarket+city.corruption)/300;g.members=Math.max(3,Math.round(g.members*(.985+attract*.035)+(rng()-.5)*5));g.influence=round(clamp(g.influence+(attract-.36)*4+(rng()-.5)*5-city.guardStrength*.008,0,100),1);g.heat=round(clamp(g.heat+g.influence*.018+city.crimeRate*.012-city.guardStrength*.018+(rng()-.5)*4,0,100),1);g.treasury=round(Math.max(0,g.treasury+g.members*(.10+attract*.26)-g.heat*.025+(rng()-.5)*8),1);if(g.influence>52&&rng()<.035)expandTerritory(city,g,rng);
  if(rng()<.055+city.blackMarket*.00045){c.stats.smugglingEvents++;c.stats.crimeEvents++;g.treasury=round(g.treasury+12+rng()*35,1);g.heat=round(clamp(g.heat+4+rng()*8,0,100),1);pushEvent(world,{type:'smuggling',importance:1,realmIds:[ownerAt(world,g.cityId)],settlementIds:[g.cityId],personIds:[g.leaderId].filter(Number.isInteger),gangIds:[g.id],title:`Smuggling ring in ${city.name}`,text:`The ${g.name} move contraband through the ${pick(rng,g.territoryIds.map(id=>city.districts.find(d=>d.id===id)?.name).filter(Boolean))||'city'}.`})}
  if(rng()<.045+city.crimeRate*.00035){c.stats.extortionEvents++;c.stats.crimeEvents++;g.influence=round(clamp(g.influence+2+rng()*4,0,100),1);pushEvent(world,{type:'extortion',importance:1,realmIds:[ownerAt(world,g.cityId)],settlementIds:[g.cityId],personIds:[g.leaderId].filter(Number.isInteger),gangIds:[g.id],title:`Protection racket spreads in ${city.name}`,text:`The ${g.name} pressure merchants and workshops for payments.`})}
  if(g.heat>55&&city.guardStrength>45&&rng()<.035+(g.heat-55)*.0012){const arrests=Math.max(2,Math.round(g.members*(.05+rng()*.12)));g.members=Math.max(2,g.members-arrests);g.influence=round(Math.max(0,g.influence-(4+rng()*9)),1);g.heat=round(Math.max(5,g.heat-(12+rng()*20)),1);c.stats.crackdowns++;c.stats.arrests+=arrests;pushEvent(world,{type:'crackdown',importance:g.influence>55?2:1,realmIds:[ownerAt(world,g.cityId)],settlementIds:[g.cityId],personIds:[city.officials.watchCaptainId,g.leaderId].filter(Number.isInteger),gangIds:[g.id],title:`Watch crackdown on the ${g.name}`,text:`City officers arrest ${arrests} associates after a coordinated operation in ${city.name}.`})}
  if((g.members<5||g.influence<2)&&rng()<.18)dissolveGang(world,c,g,year,`The ${g.name} lose their remaining territory and cease to function as an organized faction.`)
}
function updateGangWars(world,c,city,year){const gs=c.gangs.filter(g=>g.active&&g.cityId===city.id);if(gs.length<2)return;for(let i=0;i<gs.length;i++)for(let j=i+1;j<gs.length;j++){const a=gs[i],b=gs[j],rng=rngFor(world,year,`gangwar-${a.id}-${b.id}`),overlap=a.territoryIds.some(x=>b.territoryIds.includes(x));if(rng()>(overlap?.055:.018)+(a.influence+b.influence)*.00018)continue;const pa=a.members*(.6+a.influence/100),pb=b.members*(.6+b.influence/100),winner=rng()<(pa/(pa+pb))?a:b,loser=winner===a?b:a,lossW=Math.max(1,Math.round(2+rng()*winner.members*.05)),lossL=Math.max(2,Math.round(3+rng()*loser.members*.09));winner.members=Math.max(3,winner.members-lossW);loser.members=Math.max(2,loser.members-lossL);winner.influence=round(clamp(winner.influence+3+rng()*6,0,100),1);loser.influence=round(clamp(loser.influence-(4+rng()*8),0,100),1);winner.heat=round(clamp(winner.heat+7,0,100),1);loser.heat=round(clamp(loser.heat+8,0,100),1);if(loser.territoryIds.length>1&&rng()<.65){const taken=loser.territoryIds.pop();if(!winner.territoryIds.includes(taken))winner.territoryIds.push(taken)}c.stats.gangWars++;c.stats.crimeEvents++;pushEvent(world,{type:'gang_war',importance:2,realmIds:[ownerAt(world,city.id)],settlementIds:[city.id],personIds:[winner.leaderId,loser.leaderId].filter(Number.isInteger),gangIds:[winner.id,loser.id],title:`Gang war in ${city.name}`,text:`The ${winner.name} defeat the ${loser.name} in a violent struggle for territory.`})}}
function maybeFormGang(world,c,city,year){const active=c.gangs.filter(g=>g.active&&g.cityId===city.id),max=city.type==='Capital'?4:city.type==='City'?3:city.type==='Town'?2:1;if(active.length>=max||city.crimeRate<42)return;const rng=rngFor(world,year,`new-gang-${city.id}`);if(rng()<.025+(city.crimeRate-42)*.0012){const used=new Set(c.gangs.filter(g=>g.active).map(g=>g.leaderId).filter(Number.isInteger)),g=addGang(world,c,city,year,rng,used);linkRivals(c);pushEvent(world,{type:'gang_formed',importance:1,realmIds:[ownerAt(world,city.id)],settlementIds:[city.id],personIds:[g.leaderId].filter(Number.isInteger),gangIds:[g.id],title:`${g.name} emerge in ${city.name}`,text:`A new criminal faction forms around ${g.specialty.toLowerCase()} and claims part of the city.`})}}
function citySnapshotRows(c){return c.cities.map(city=>[city.id,Math.round(city.population),round(city.prosperity,4),round(city.wealth,2),round(city.trade,1),round(city.unemployment,3),round(city.guardStrength,1),round(city.corruption,1),round(city.crimeRate,1),round(city.blackMarket,1),round(city.priceIndex,1),round(city.businessHealth,3),city.officials.magistrateId??-1,city.officials.watchCaptainId??-1,city.officials.merchantPatronId??-1,city.businesses.filter(b=>b.active).length])}
function gangSnapshotRows(c){return c.gangs.map(g=>[g.id,g.cityId,g.active?1:0,g.leaderId??-1,Math.round(g.members),round(g.influence,1),round(g.heat,1),round(g.treasury,1),g.dissolvedYear??-1,[...g.territoryIds]])}
function currentMetrics(c){const urban=c.cities.filter(x=>['Capital','City','Town'].includes(x.type)),activeGangs=c.gangs.filter(g=>g.active),avg=a=>a.length?a.reduce((n,x)=>n+x,0)/a.length:0;return{urbanCenters:urban.length,activeGangs:activeGangs.length,businesses:c.cities.reduce((n,x)=>n+x.businesses.filter(b=>b.active).length,0),meanCrime:round(avg(urban.map(x=>x.crimeRate)),1),meanCorruption:round(avg(urban.map(x=>x.corruption)),1),blackMarket:round(avg(urban.map(x=>x.blackMarket)),1),gangWars:c.stats.gangWars,arrests:c.stats.arrests}}
function takeSnapshot(world,c,force=false){const interval=world.history?.snapshotInterval||5;if(!force&&c.currentYear%interval!==0)return null;const snap={year:c.currentYear,cities:citySnapshotRows(c),gangs:gangSnapshotRows(c),stats:{...currentMetrics(c)},eventIndex:world.history.events.length};const last=c.snapshots[c.snapshots.length-1];if(last?.year===snap.year)c.snapshots[c.snapshots.length-1]=snap;else c.snapshots.push(snap);return snap}
function recompute(world,c,year){for(const city of c.cities)refreshOfficials(world,city,year);linkRivals(c)}
function simulateCityYear(world,c,year){c.currentYear=year;for(const city of c.cities)updateCity(world,c,city,year);for(const g of c.gangs)updateGang(world,c,g,year);for(const city of c.cities){updateGangWars(world,c,city,year);maybeFormGang(world,c,city,year)}recompute(world,c,year);takeSnapshot(world,c,false)}
function compactSnapshots(world,c){const interval=world.history?.snapshotInterval||5,current=c.currentYear,by=new Map();for(const x of c.snapshots)if(x.year===c.startYear||x.year%interval===0||x.year===current)by.set(x.year,x);c.snapshots=[...by.values()].sort((a,b)=>a.year-b.year)}
function simulateYears(world,years,options={}){const c=initialize(world,options),h=history(world),n=clamp(Math.round(Number(years)||0),0,5000),target=clamp(h.currentYear+n,0,5000);if(!capturedSocietySimulate)throw new Error('Society simulation unavailable');if(c.currentYear!==h.currentYear){c.currentYear=h.currentYear;takeSnapshot(world,c,true)}while(h.currentYear<target){capturedSocietySimulate(world,1,options);simulateCityYear(world,c,h.currentYear)}compactSnapshots(world,c);takeSnapshot(world,c,true);return c}
function simulateTo(world,targetYear,options={}){const h=history(world),target=clamp(Math.round(Number(targetYear)||0),h.currentYear,5000);return simulateYears(world,target-h.currentYear,options)}
function snapshotAt(world,year){const c=initialize(world),target=clamp(Math.round(Number(year)||0),c.startYear,c.currentYear);let best=c.snapshots[0];for(const s of c.snapshots)if(s.year<=target&&s.year>=best.year)best=s;return best}
function viewFromSnapshot(world,c,snap){const cities=snap.cities.map(row=>{const base=c.cities[row[0]];return{id:row[0],name:base.name,type:base.type,coastal:base.coastal,river:base.river,districts:base.districts,roads:base.roads,businesses:base.businesses,population:row[1],prosperity:row[2],wealth:row[3],trade:row[4],unemployment:row[5],guardStrength:row[6],corruption:row[7],crimeRate:row[8],blackMarket:row[9],priceIndex:row[10],businessHealth:row[11],officials:{magistrateId:row[12]<0?null:row[12],watchCaptainId:row[13]<0?null:row[13],merchantPatronId:row[14]<0?null:row[14]},activeBusinesses:row[15]}});const gangs=snap.gangs.map(row=>{const base=c.gangs[row[0]];return{id:row[0],cityId:row[1],name:base.name,color:base.color,active:!!row[2],leaderId:row[3]<0?null:row[3],members:row[4],influence:row[5],heat:row[6],treasury:row[7],dissolvedYear:row[8]<0?null:row[8],territoryIds:[...row[9]],specialty:base.specialty,foundedYear:base.foundedYear,rivalIds:[...base.rivalIds]}});return{year:snap.year,isPresent:snap.year===c.currentYear,cities,gangs,stats:{...snap.stats},eventIndex:snap.eventIndex}}
function currentView(world){const c=initialize(world),snap={year:c.currentYear,cities:citySnapshotRows(c),gangs:gangSnapshotRows(c),stats:currentMetrics(c),eventIndex:world.history.events.length};return viewFromSnapshot(world,c,snap)}
function viewAt(world,year){const c=initialize(world);if(year>=c.currentYear)return currentView(world);return viewFromSnapshot(world,c,snapshotAt(world,year))}
function cityDetail(world,cityId,year=null){const v=year==null?currentView(world):viewAt(world,year),city=v.cities[cityId];if(!city)return null;return{...city,gangs:v.gangs.filter(g=>g.cityId===cityId&&g.foundedYear<=v.year&&(g.active||g.dissolvedYear==null||g.dissolvedYear>=v.year)),officialNames:{magistrate:fullName(world,city.officials.magistrateId),watchCaptain:fullName(world,city.officials.watchCaptainId),merchantPatron:fullName(world,city.officials.merchantPatronId)}}}
function cityFingerprint(world){const c=initialize(world),cities=c.cities.map(x=>`${x.id}:${Math.round(x.crimeRate)}:${Math.round(x.corruption)}:${Math.round(x.guardStrength)}:${Math.round(x.blackMarket)}:${x.businesses.filter(b=>b.active).length}`).join('|'),gangs=c.gangs.map(g=>`${g.id}:${g.active?1:0}:${g.cityId}:${g.leaderId}:${g.members}:${Math.round(g.influence)}:${Math.round(g.heat)}:${g.territoryIds.length}`).join('|');let x=2166136261>>>0;for(const ch of`${c.currentYear}|${c.stats.gangWars}|${c.stats.crackdowns}|${c.stats.arrests}|${cities}|${gangs}`){x^=ch.charCodeAt(0);x=Math.imul(x,16777619)}return(x>>>0).toString(16).padStart(8,'0')}
function validateCities(world){const errors=[],c=world?.cities;if(!c||c.schemaVersion!==CITY_SCHEMA)return['city schema'];if(c.currentYear!==world.history?.currentYear)errors.push('city/history year mismatch');if(c.currentYear!==world.society?.currentYear)errors.push('city/society year mismatch');if(c.cities.length!==world.settlements.length)errors.push('city count');for(let i=0;i<c.cities.length;i++){const city=c.cities[i];if(city.id!==i||city.settlementId!==i)errors.push('city id');if(!city.districts?.length)errors.push('districts');const ids=new Set(city.districts.map(d=>d.id));for(const e of city.roads||[])if(!ids.has(e[0])||!ids.has(e[1]))errors.push('district road');for(const b of city.businesses||[])if(!ids.has(b.districtId))errors.push('business district')}for(const g of c.gangs){if(!c.cities[g.cityId])errors.push('gang city');if(g.leaderId!=null&&!world.society.people[g.leaderId])errors.push('gang leader');const ids=new Set(c.cities[g.cityId]?.districts.map(d=>d.id)||[]);if(g.territoryIds.some(id=>!ids.has(id)))errors.push('gang territory')}if(!c.snapshots.length||c.snapshots[c.snapshots.length-1].year!==c.currentYear)errors.push('city present snapshot');return[...new Set(errors)]}

return{VERSION,CITY_SCHEMA,initialize,simulateYears,simulateTo,currentView,viewAt,snapshotAt,cityDetail,cityFingerprint,validateCities,fullName};
});