(function(root,factory){
  const api=factory(
    root&&root.WorldForgeHistory,
    root&&root.WorldForgeCity,
    root&&root.WorldForgeKnowledge,
    root&&root.WorldForgeArtifacts,
    root&&root.WorldForgeTechnology,
    root&&root.WorldForgeResources
  );
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeCivic=api;
})(typeof window!=='undefined'?window:globalThis,function(History,City,Knowledge,Artifacts,Technology,Resources){
'use strict';

const VERSION='1.9.0',SCHEMA=1;
const PRODUCTS=[
  {id:'flour',name:'Flour',category:'Food',unit:'sacks'},
  {id:'bread',name:'Bread',category:'Food',unit:'lots'},
  {id:'lumber',name:'Lumber',category:'Material',unit:'loads'},
  {id:'steel',name:'Steel',category:'Metal',unit:'ingots'},
  {id:'tools',name:'Tools',category:'Industrial',unit:'sets'},
  {id:'weapons',name:'Weapons',category:'Military',unit:'sets'},
  {id:'ships',name:'Ships',category:'Strategic',unit:'hulls'},
  {id:'medicine',name:'Prepared Medicine',category:'Health',unit:'lots'},
  {id:'manuscripts',name:'Manuscripts',category:'Knowledge',unit:'volumes'}
];
const PRODUCT_MAP=new Map(PRODUCTS.map(x=>[x.id,x]));
const TYPES=[
  {id:'farm',name:'Managed Farms',category:'Extraction',priority:10},
  {id:'ranch',name:'Ranches',category:'Extraction',priority:11},
  {id:'fishery',name:'Fisheries',category:'Extraction',priority:12},
  {id:'lumber_camp',name:'Lumber Camps',category:'Extraction',priority:13},
  {id:'mine',name:'Mines',category:'Extraction',priority:14},
  {id:'granary',name:'Granary',category:'Logistics',priority:20},
  {id:'warehouse',name:'Warehouse',category:'Logistics',priority:21},
  {id:'market_hall',name:'Market Hall',category:'Civic',priority:22},
  {id:'mill',name:'Mill',category:'Industry',priority:30},
  {id:'bakery',name:'Bakery Quarter',category:'Industry',priority:31},
  {id:'sawmill',name:'Sawmill',category:'Industry',priority:32},
  {id:'foundry',name:'Foundry',category:'Industry',priority:33},
  {id:'smithy',name:'Smithy Complex',category:'Industry',priority:34},
  {id:'shipyard',name:'Shipyard',category:'Industry',priority:35},
  {id:'hospital',name:'Hospital',category:'Institution',priority:40},
  {id:'library',name:'Library',category:'Institution',priority:41},
  {id:'university',name:'University',category:'Institution',priority:42},
  {id:'museum',name:'Museum',category:'Institution',priority:43},
  {id:'temple_archive',name:'Temple Archive',category:'Institution',priority:44},
  {id:'observatory',name:'Observatory',category:'Institution',priority:45}
];
const TYPE_MAP=new Map(TYPES.map(x=>[x.id,x]));
const GREAT_WORKS=[
  {id:'great_library',name:'Great Library',baseType:'library',requirements:{timber:60,iron:16,copper:8,lumber:40,steel:8},prestige:96},
  {id:'grand_university',name:'Grand University',baseType:'university',requirements:{timber:52,iron:22,copper:10,lumber:34,steel:10},prestige:94},
  {id:'royal_hospital',name:'Royal Hospital',baseType:'hospital',requirements:{timber:44,iron:18,copper:10,lumber:28,steel:7},prestige:88},
  {id:'imperial_shipyard',name:'Imperial Shipyard',baseType:'shipyard',requirements:{timber:88,iron:38,copper:8,lumber:58,steel:22},prestige:93},
  {id:'national_museum',name:'National Museum',baseType:'museum',requirements:{timber:40,iron:14,copper:14,lumber:28,steel:7},prestige:90},
  {id:'sacred_archive',name:'Sacred Archive',baseType:'temple_archive',requirements:{timber:36,iron:10,copper:12,lumber:24,steel:5},prestige:89},
  {id:'great_observatory',name:'Great Observatory',baseType:'observatory',requirements:{timber:36,iron:24,copper:22,lumber:22,steel:12},prestige:92},
  {id:'great_granary',name:'Great Granary',baseType:'granary',requirements:{timber:54,iron:14,lumber:32,steel:5},prestige:84}
];
const GREAT_MAP=new Map(GREAT_WORKS.map(x=>[x.id,x]));
let baseSimulator=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const round=(v,d=3)=>Number(Number(v).toFixed(d));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed);return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function seedOf(w){return w.endless?.baseSeed||String(w.settings?.seed||'WORLD').split('|EPOCH:')[0]}
function keyed(w,y,salt){return rng(`${seedOf(w)}|CIVIC|${y}|${salt}`)}
function absYear(w){return(w.endless?.epochOffset||0)+Number(w.history?.currentYear||0)}
function setBaseSimulator(fn){if(typeof fn==='function')baseSimulator=fn;return api}
function realmId(w,sid){return w.history?.current?.settlementKingdomIds?.[sid]??w.settlements?.[sid]?.kingdomId??null}
function population(w,sid){return Math.max(20,Number(w.history?.current?.settlementPopulation?.[sid]||w.settlements?.[sid]?.population||200))}
function prosperity(w,sid){return Number(w.history?.current?.settlementProsperity?.[sid]??w.cities?.cities?.[sid]?.prosperity??.45)}
function activeWarForRealm(w,rid){for(const wid of w.history?.current?.activeWarIds||[]){const q=w.history?.wars?.[wid];if(q&&(q.attackerId===rid||q.defenderId===rid))return true}return false}
function techAdoption(w,rid,id){const r=w.technology?.realms?.find(x=>x.realmId===rid);return Number(r?.known?.[id]?.adoption||0)}
function techEffects(w,rid){try{return Technology?.realmView?.(w,rid)?.effects||{}}catch{return{}}}
function pushHistory(w,e){const h=History.initialize(w);h.events.push({id:h.events.length,year:h.currentYear,absoluteYear:absYear(w),...e});return h.events.at(-1)}
function ensureState(w){if(!w.civic||w.civic.schemaVersion!==SCHEMA)w.civic={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:absYear(w),nextId:1,facilities:[],greatWorks:[],incidents:[],annual:[],archives:[],realmAssets:{},settings:{maxIncidents:900,retainDetailedYears:1200,greatWorkMinYear:55},stats:{built:0,destroyed:0,greatWorksStarted:0,greatWorksCompleted:0,processed:0,research:0,knowledgePreserved:0,knowledgeLost:0,artifactsProtected:0,shipsBuilt:0,weaponsMade:0,archivedYears:0}};const C=w.civic;C.engineVersion=VERSION;C.facilities=C.facilities||[];C.greatWorks=C.greatWorks||[];C.incidents=C.incidents||[];C.annual=C.annual||[];C.archives=C.archives||[];C.realmAssets=C.realmAssets||{};C.nextId=C.nextId||1;C.settings={maxIncidents:900,retainDetailedYears:1200,greatWorkMinYear:55,...C.settings};C.stats={built:0,destroyed:0,greatWorksStarted:0,greatWorksCompleted:0,processed:0,research:0,knowledgePreserved:0,knowledgeLost:0,artifactsProtected:0,shipsBuilt:0,weaponsMade:0,archivedYears:0,...C.stats};return C}
function market(w,sid){return Resources?.market?.(w,sid)||null}
function prepareMarket(w,sid){const m=market(w,sid);if(!m)return null;m.processed=m.processed||{};m.processedProduction=m.processedProduction||{};m.processedConsumption=m.processedConsumption||{};for(const p of PRODUCTS)if(m.processed[p.id]==null)m.processed[p.id]=0;return m}
function baseHave(w,sid,id){return Math.max(0,Number(market(w,sid)?.inventory?.[id]||0))}
function productHave(w,sid,id){return Math.max(0,Number(prepareMarket(w,sid)?.processed?.[id]||0))}
function takeBase(w,sid,id,q){const m=market(w,sid);if(!m)return 0;q=Math.min(Math.max(0,q),baseHave(w,sid,id));m.inventory[id]=round(baseHave(w,sid,id)-q);return q}
function giveBase(w,sid,id,q){const m=market(w,sid);if(!m)return 0;m.inventory[id]=round(baseHave(w,sid,id)+Math.max(0,q));return q}
function takeProduct(w,sid,id,q){const m=prepareMarket(w,sid);if(!m)return 0;q=Math.min(Math.max(0,q),productHave(w,sid,id));m.processed[id]=round(productHave(w,sid,id)-q);m.processedConsumption[id]=round(Number(m.processedConsumption[id]||0)+q);return q}
function giveProduct(w,sid,id,q){const m=prepareMarket(w,sid);if(!m)return 0;q=Math.max(0,q);m.processed[id]=round(productHave(w,sid,id)+q);m.processedProduction[id]=round(Number(m.processedProduction[id]||0)+q);w.civic.stats.processed+=q;return q}
function _makeFacility(w,C,typeId,sid,year,opts={}){const type=TYPE_MAP.get(typeId);if(!type||!w.settlements?.[sid])return null;const rid=realmId(w,sid),same=C.facilities.filter(x=>x.settlementId===sid&&x.typeId===typeId&&x.status!=='destroyed').length,id=C.nextId++;const f={id,typeId,settlementId:sid,realmId:rid,foundedYear:year,name:opts.name||`${w.settlements[sid].name} ${type.name}${same?` ${same+1}`:''}`,status:opts.status||'active',condition:opts.condition??1,level:opts.level||1,prestige:opts.prestige||20+Math.round(prosperity(w,sid)*30),workers:opts.workers||Math.max(6,Math.round(Math.pow(population(w,sid),.45)*(2+type.priority/40))),throughput:0,reserve:{grain:0,rice:0},collection:{sourceIds:[],artifactIds:[]},foundedByRealmId:rid,greatWorkId:opts.greatWorkId||null,construction:opts.construction||null,lastYear:-1};C.facilities.push(f);C.stats.built++;return f}
function seedFacilities(w,C){for(const s of w.settlements||[]){const m=market(w,s.id),pop=population(w,s.id),cap=!!s.capital,urban=['Capital','City','Town'].includes(s.type),u=m?.suitability||{},add=id=>_makeFacility(w,C,id,s.id,0);add('market_hall');add('granary');if((u.grain||0)>.2||(u.rice||0)>.25)add('farm');if((u.livestock||0)>.28)add('ranch');if((u.fish||0)>.34)add('fishery');if((u.timber||0)>.28)add('lumber_camp');if(Math.max(u.iron||0,u.copper||0,u.coal||0)>.23)add('mine');if((u.grain||0)>.2||(u.rice||0)>.22)add('mill');if(pop>700)add('bakery');if((u.timber||0)>.3)add('sawmill');if((u.iron||0)>.18)add('smithy');if(urban)add('warehouse');if(pop>3000&&((u.iron||0)>.25||(u.coal||0)>.2))add('foundry');if(pop>3200&&(u.fish||0)>.45)add('shipyard');if(cap||pop>5000)add('hospital');if(cap||pop>6500)add('library');if(cap&&pop>5000)add('university');if(cap&&pop>6500)add('museum');if(cap)add('temple_archive');if(cap&&pop>7500)add('observatory')}C.seeded=true}
function initialize(w){if(!w)throw new Error('World required');History?.initialize?.(w);City?.initialize?.(w);Knowledge?.initialize?.(w);Artifacts?.initialize?.(w);Technology?.initialize?.(w);Resources?.initialize?.(w);const C=ensureState(w);for(const s of w.settlements||[])prepareMarket(w,s.id);if(!C.seeded){C.seeded=true;seedFacilities(w,C)}return C}
function makeFacility(w,typeId,sid,year=absYear(w),opts={}){const C=initialize(w);return _makeFacility(w,C,typeId,Number(sid),year,opts)}
function facility(w,id){return initialize(w).facilities.find(x=>x.id===Number(id))||null}
function facilitiesAt(w,sid,{activeOnly=false}={}){return initialize(w).facilities.filter(x=>x.settlementId===Number(sid)&&(!activeOnly||x.status==='active'))}
function factor(w,f){const fx=techEffects(w,f.realmId),cond=clamp(f.condition,0,1),level=1+(f.level-1)*.18,pros=.76+prosperity(w,f.settlementId)*.44,tech=1+Number(fx.engineering||0)*.7+Number(fx.food||0)*.3;return cond*level*pros*tech*(f.greatWorkId?1.45:1)}
function extraction(w,f,year){const m=market(w,f.settlementId),rr=keyed(w,year,`extract:${f.id}`);if(!m)return 0;const q=(.55+rr()*.45)*factor(w,f),u=m.suitability||{};if(f.typeId==='farm'){const id=(u.rice||0)>(u.grain||0)*1.15?'rice':'grain';return giveBase(w,f.settlementId,id,q*(.6+Number(u[id]||0)))}if(f.typeId==='ranch')return giveBase(w,f.settlementId,'livestock',q*(.5+Number(u.livestock||0)));if(f.typeId==='fishery')return giveBase(w,f.settlementId,'fish',q*(.5+Number(u.fish||0)));if(f.typeId==='lumber_camp')return giveBase(w,f.settlementId,'timber',q*(.5+Number(u.timber||0)));if(f.typeId==='mine'){const id=['iron','copper','coal'].sort((a,b)=>(u[b]||0)-(u[a]||0))[0];return giveBase(w,f.settlementId,id,q*(.45+Number(u[id]||0)))}return 0}
function granary(w,f){const m=market(w,f.settlementId);if(!m)return 0;let moved=0,cap=18*f.level*(f.greatWorkId?4:1);for(const id of ['grain','rice']){const short=Number(m.shortages?.[id]||0),stock=baseHave(w,f.settlementId,id),reserve=Number(f.reserve[id]||0);if(short<.12&&stock>6&&reserve<cap){const q=Math.min(stock*.035,cap-reserve);takeBase(w,f.settlementId,id,q);f.reserve[id]=round(reserve+q);moved+=q}else if(short>.4&&reserve>.05){const q=Math.min(reserve,2.5+short*8*f.level);f.reserve[id]=round(reserve-q);giveBase(w,f.settlementId,id,q);m.shortages[id]=round(short*.62);const c=Resources.MAP?.get?.(id);if(c)m.prices[id]=round(c.basePrice*(1+m.shortages[id]*2.2),2);m.foodSecurity=round(Math.max(Number(m.foodSecurity||0),.55+q*.02));m.foodDays=round(Math.max(Number(m.foodDays||0),80+q*7),1);moved+=q}}return moved}
function preserveKnowledge(w,f){const K=Knowledge?.initialize?.(w);if(!K)return 0;const pool=(K.sources||[]).filter(s=>!s.destroyedYear&&!f.collection.sourceIds.includes(s.id)&&(s.originRealmId===f.realmId||realmId(w,s.originSettlementId)===f.realmId)).sort((a,b)=>(b.reliability||0)-(a.reliability||0)||a.id-b.id),n=Math.min(f.greatWorkId?8:3,pool.length);for(const s of pool.slice(0,n)){f.collection.sourceIds.push(s.id);s.archiveStrength=Math.max(Number(s.archiveStrength||0),f.greatWorkId?.98:.82);s.preservedByInstitutionId=f.id;w.civic.stats.knowledgePreserved++}return n}
function preserveArtifacts(w,f){const A=Artifacts?.initialize?.(w);if(!A)return 0;const pool=(A.items||[]).filter(a=>a.status!=='destroyed'&&a.status!=='lost'&&!f.collection.artifactIds.includes(a.id)&&(a.originRealmId===f.realmId||a.ownerId===f.realmId)).sort((a,b)=>(b.prestige||0)-(a.prestige||0)||a.id-b.id),n=Math.min(f.greatWorkId?5:2,pool.length);for(const a of pool.slice(0,n)){f.collection.artifactIds.push(a.id);a.preservedByInstitutionId=f.id;a.condition=round(Math.min(1,Number(a.condition||.7)+.01));w.civic.stats.artifactsProtected++}return n}
function research(w,f,year){const r=w.technology?.realms?.find(x=>x.realmId===f.realmId);if(!r)return 0;const rows=Technology?.realmView?.(w,f.realmId)?.rows||[],candidate=rows.filter(x=>!x.known&&x.unlocked).sort((a,b)=>a.tech.tier-b.tech.tier||a.tech.id.localeCompare(b.tech.id))[0],boost=(f.typeId==='observatory'?1.15:.9)*factor(w,f)*(f.greatWorkId?1.7:1);r.innovationScore=Number(r.innovationScore||0)+boost*.35;if(candidate){r.progress[candidate.tech.id]=round(Number(r.progress[candidate.tech.id]||0)+boost);w.civic.stats.research+=boost}if(f.typeId==='university'&&keyed(w,year,`manuscript:${f.id}`)()<.35)giveProduct(w,f.settlementId,'manuscripts',.4*factor(w,f));return boost}
function processFacility(w,f,year){const sid=f.settlementId,cap=(.7+f.level*.45)*factor(w,f);let out=0;if(['farm','ranch','fishery','lumber_camp','mine'].includes(f.typeId))out=extraction(w,f,year);else if(f.typeId==='granary')out=granary(w,f);else if(f.typeId==='mill'){let q=Math.min(cap,baseHave(w,sid,'grain')+baseHave(w,sid,'rice'));const g=takeBase(w,sid,'grain',q),r=takeBase(w,sid,'rice',q-g);out=giveProduct(w,sid,'flour',(g+r)*.82)}else if(f.typeId==='bakery'){const q=Math.min(cap,productHave(w,sid,'flour'),baseHave(w,sid,'salt')/.08);if(q>0){takeProduct(w,sid,'flour',q);takeBase(w,sid,'salt',q*.08);out=giveProduct(w,sid,'bread',q*.96)}}else if(f.typeId==='sawmill'){const q=Math.min(cap,baseHave(w,sid,'timber'));takeBase(w,sid,'timber',q);out=giveProduct(w,sid,'lumber',q*.76)}else if(f.typeId==='foundry'){const q=Math.min(cap,baseHave(w,sid,'iron'),baseHave(w,sid,'coal')/.45);if(q>0){takeBase(w,sid,'iron',q);takeBase(w,sid,'coal',q*.45);out=giveProduct(w,sid,'steel',q*.72)}}else if(f.typeId==='smithy'){const q=Math.min(cap,productHave(w,sid,'steel')/.65,productHave(w,sid,'lumber')/.2);if(q>0){takeProduct(w,sid,'steel',q*.65);takeProduct(w,sid,'lumber',q*.2);const tools=giveProduct(w,sid,'tools',q*.38),weapons=giveProduct(w,sid,'weapons',q*.28);out=tools+weapons;w.civic.stats.weaponsMade+=weapons}}else if(f.typeId==='shipyard'){const q=Math.min(cap,productHave(w,sid,'lumber')/1.8,productHave(w,sid,'steel')/.5);if(q>0){takeProduct(w,sid,'lumber',q*1.8);takeProduct(w,sid,'steel',q*.5);out=giveProduct(w,sid,'ships',q*.07);w.civic.stats.shipsBuilt+=out}}else if(f.typeId==='hospital'){const q=Math.min(cap*.2,baseHave(w,sid,'wine'),baseHave(w,sid,'salt'));if(q>0){takeBase(w,sid,'wine',q*.6);takeBase(w,sid,'salt',q*.4);out=giveProduct(w,sid,'medicine',q*.8)}const h=w.history?.current;if(h?.settlementProsperity)h.settlementProsperity[sid]=round(clamp(Number(h.settlementProsperity[sid]||.4)+.0007*factor(w,f),.05,.98),4)}else if(f.typeId==='market_hall'){const m=market(w,sid);if(m)m.marketStress=round(Math.max(0,Number(m.marketStress||0)-.007*factor(w,f)))}else if(f.typeId==='warehouse'){const m=market(w,sid);if(m)m.marketStress=round(Math.max(0,Number(m.marketStress||0)-.0035*factor(w,f)))}else if(f.typeId==='library'||f.typeId==='temple_archive')out=preserveKnowledge(w,f);else if(f.typeId==='museum')out=preserveArtifacts(w,f);else if(f.typeId==='university'||f.typeId==='observatory')out=research(w,f,year);f.throughput=round(out);f.lastYear=year;return out}
function applyBread(w){for(const s of w.settlements||[]){const m=prepareMarket(w,s.id),bread=productHave(w,s.id,'bread');if(!m||bread<=0)continue;const use=Math.min(bread,Math.max(.12,population(w,s.id)*.00007));takeProduct(w,s.id,'bread',use);m.foodSecurity=round(Math.min(1.6,Math.max(Number(m.foodSecurity||0),Number(m.foodSecurity||0)+use*.022)));m.foodDays=round(Math.min(720,Number(m.foodDays||0)+use*2.4),1);m.marketStress=round(Math.max(0,Number(m.marketStress||0)-use*.0015))}}
function beginGreatWork(w,rid,greatWorkId,sid=null,year=absYear(w)){const C=initialize(w),g=GREAT_MAP.get(greatWorkId);if(!g||C.greatWorks.some(x=>x.realmId===rid&&x.greatWorkId===greatWorkId&&x.status!=='destroyed'))return null;const realm=w.history?.realms?.[rid],target=sid??realm?.capitalId??w.history?.current?.settlementKingdomIds?.findIndex(x=>x===rid);if(target==null||target<0)return null;const name=`${realm?.shortName||'Royal'} ${g.name}`,f=_makeFacility(w,C,g.baseType,target,year,{name,status:'constructing',condition:1,level:3,prestige:g.prestige,greatWorkId,construction:{required:{...g.requirements},delivered:{},progress:0,startedYear:year}}),rec={facilityId:f.id,greatWorkId,realmId:rid,settlementId:target,name,status:'constructing',startedYear:year,completedYear:null};C.greatWorks.push(rec);C.stats.greatWorksStarted++;pushHistory(w,{type:'great_work_started',importance:2,realmIds:[rid],settlementIds:[target],title:`Construction begins on ${name}`,text:`${realm?.shortName||'The realm'} begins a generational civic project: ${name}.`,institutionIds:[f.id]});return rec}
function progressConstruction(w,f,year){const c=f.construction;if(!c||f.status!=='constructing')return;let total=0,done=0;for(const [id,need] of Object.entries(c.required)){total+=need;const have=Number(c.delivered[id]||0),left=Math.max(0,need-have);if(left<=0){done+=need;continue}const q=PRODUCT_MAP.has(id)?takeProduct(w,f.settlementId,id,Math.min(left,2+f.level)):takeBase(w,f.settlementId,id,Math.min(left,2.5+f.level));c.delivered[id]=round(have+q);done+=Math.min(need,c.delivered[id])}c.progress=round(done/Math.max(1,total),4);if(c.progress>=.999){f.status='active';f.condition=1;const rec=w.civic.greatWorks.find(x=>x.facilityId===f.id);if(rec){rec.status='active';rec.completedYear=year}w.civic.stats.greatWorksCompleted++;pushHistory(w,{type:'great_work_completed',importance:3,realmIds:[f.realmId],settlementIds:[f.settlementId],title:`${f.name} is completed`,text:`After years of material investment, ${f.name} opens as a lasting institution.`,institutionIds:[f.id]})}}
function maybeStartGreatWork(w,year){const C=initialize(w);if(year<C.settings.greatWorkMinYear||year%17!==0)return;for(const rs of w.history?.current?.realmState||[]){if(!rs||rs.active===false)continue;const rid=rs.id;if(C.greatWorks.filter(x=>x.realmId===rid&&x.status!=='destroyed').length>=2)continue;const rr=keyed(w,year,`great:${rid}`),cap=w.history?.realms?.[rid]?.capitalId??0;if(rr()>.22+prosperity(w,cap)*.24)continue;const pool=GREAT_WORKS.filter(g=>!C.greatWorks.some(x=>x.realmId===rid&&x.greatWorkId===g.id&&x.status!=='destroyed')).filter(g=>g.baseType!=='shipyard'||techAdoption(w,rid,'shipbuilding')>.15);if(pool.length)beginGreatWork(w,rid,pool[Math.floor(rr()*pool.length)].id,null,year)}}
function knowledgeLoss(w,f,year,cause){const K=Knowledge?.initialize?.(w);if(!K)return 0;let lost=0;for(const id of f.collection?.sourceIds||[]){const s=K.sources?.find(x=>x.id===id);if(!s||s.destroyedYear)continue;s.destroyedYear=year;s.destroyedBy=cause;s.archiveStrength=0;const claim=K.claims?.find(x=>x.key===s.claimKey);if(claim)claim.sourceIds=(claim.sourceIds||[]).filter(x=>x!==id);lost++}w.civic.stats.knowledgeLost+=lost;return lost}
function artifactLoss(w,f,year,cause){const A=Artifacts?.initialize?.(w);if(!A)return 0;let lost=0;for(const id of f.collection?.artifactIds||[]){const a=A.items?.find(x=>x.id===id);if(!a||a.status==='destroyed')continue;a.status='lost';a.lostYear=year;a.preservedByInstitutionId=null;a.provenance=a.provenance||[];a.provenance.push({year,action:'lost',note:`Lost when ${f.name} suffered ${cause}.`});lost++}return lost}
function damageInstitution(w,id,severity=.35,cause='fire',year=absYear(w)){const f=facility(w,id);if(!f||f.status==='destroyed')return null;const C=initialize(w);f.condition=round(clamp(f.condition-Math.abs(severity),0,1));if(f.condition<=.12){f.status='destroyed';C.stats.destroyed++;const knowledgeLost=['library','temple_archive','university'].includes(f.typeId)?knowledgeLoss(w,f,year,cause):0,artifactsLost=f.typeId==='museum'?artifactLoss(w,f,year,cause):0,g=C.greatWorks.find(x=>x.facilityId===f.id);if(g)g.status='destroyed';C.incidents.push({id:C.incidents.length,year,type:'institution_destroyed',facilityId:f.id,settlementId:f.settlementId,realmId:f.realmId,cause,severity:1,knowledgeLost,artifactsLost,title:`${f.name} is destroyed`});pushHistory(w,{type:'institution_destroyed',importance:f.greatWorkId?3:2,realmIds:[f.realmId],settlementIds:[f.settlementId],title:`${f.name} is destroyed`,text:`${cause} destroys ${f.name}${knowledgeLost?`, erasing ${knowledgeLost} preserved sources`:''}${artifactsLost?`, scattering ${artifactsLost} artifacts`:''}.`,institutionIds:[f.id]})}else{f.status='damaged';C.incidents.push({id:C.incidents.length,year,type:'institution_damaged',facilityId:f.id,settlementId:f.settlementId,realmId:f.realmId,cause,severity,knowledgeLost:0,artifactsLost:0,title:`${f.name} is damaged`})}return f}
function incidents(w,year){const C=initialize(w);for(const f of C.facilities.filter(x=>x.status==='active')){const war=activeWarForRealm(w,f.realmId),crime=Number(w.cities?.cities?.[f.settlementId]?.crimeRate||0)/100,rr=keyed(w,year,`incident:${f.id}`),risk=.0006+crime*.0012+(war?.005:0);if(rr()<risk)damageInstitution(w,f.id,.22+rr()*(war?.55:.3),war&&rr()<.7?'wartime destruction':crime>.65&&rr()<.45?'arson':'fire',year)}if(C.incidents.length>C.settings.maxIncidents)C.incidents.splice(0,C.incidents.length-C.settings.maxIncidents)}
function repair(w){for(const f of initialize(w).facilities.filter(x=>x.status==='damaged')){const q=Math.min(baseHave(w,f.settlementId,'timber')/.35,baseHave(w,f.settlementId,'iron')/.12,.8*f.level);if(q>.05){takeBase(w,f.settlementId,'timber',q*.35);takeBase(w,f.settlementId,'iron',q*.12);f.condition=round(Math.min(1,f.condition+.035+q*.018));if(f.condition>.72)f.status='active'}}}
function buildExpansion(w,year){if(year%12!==0)return;for(const s of w.settlements||[]){const sid=s.id,pop=population(w,sid),rid=realmId(w,sid),types=new Set(facilitiesAt(w,sid,{activeOnly:true}).map(x=>x.typeId)),add=id=>{if(!types.has(id)){makeFacility(w,id,sid,year);types.add(id)}};if(pop>2200)add('warehouse');if(pop>3200)add('hospital');if(pop>4500&&techAdoption(w,rid,'writing')>.2)add('library');if(pop>6500&&techAdoption(w,rid,'universities')>.15)add('university');if(pop>7000&&techAdoption(w,rid,'shipbuilding')>.2&&(market(w,sid)?.suitability?.fish||0)>.35)add('shipyard');if(pop>6000&&techAdoption(w,rid,'ironworking')>.2)add('foundry');if(pop>8000&&techAdoption(w,rid,'navigation')>.25)add('observatory')}}
function updateAssets(w){const C=initialize(w);C.realmAssets={};for(const f of C.facilities.filter(x=>x.status==='active')){const key=String(f.realmId),a=C.realmAssets[key]||(C.realmAssets[key]={weapons:0,ships:0,tools:0,research:0,health:0,logistics:0}),m=prepareMarket(w,f.settlementId);a.weapons+=Number(m?.processed?.weapons||0);a.ships+=Number(m?.processed?.ships||0);a.tools+=Number(m?.processed?.tools||0);if(f.typeId==='university'||f.typeId==='observatory')a.research+=f.level*(f.greatWorkId?2:1);if(f.typeId==='hospital')a.health+=f.level*(f.greatWorkId?2:1);if(['granary','warehouse','market_hall','shipyard'].includes(f.typeId))a.logistics+=f.level*(f.greatWorkId?2:1)}for(const a of Object.values(C.realmAssets))for(const k of Object.keys(a))a[k]=round(a[k],2)}
function productTotals(w){initialize(w);const out={};for(const p of PRODUCTS)out[p.id]={stock:0,production:0,consumption:0};for(const m of w.resources?.markets||[])for(const p of PRODUCTS){out[p.id].stock+=Number(m.processed?.[p.id]||0);out[p.id].production+=Number(m.processedProduction?.[p.id]||0);out[p.id].consumption+=Number(m.processedConsumption?.[p.id]||0)}for(const v of Object.values(out))for(const k of Object.keys(v))v[k]=round(v[k]);return out}
function simulateCivicYear(w,year=absYear(w)){const C=initialize(w);C.currentYear=year;for(const m of w.resources?.markets||[]){prepareMarket(w,m.settlementId);m.processedProduction={};m.processedConsumption={}}for(const f of C.facilities.filter(x=>x.status==='constructing'))progressConstruction(w,f,year);for(const f of C.facilities.filter(x=>x.status==='active').sort((a,b)=>(TYPE_MAP.get(a.typeId)?.priority||99)-(TYPE_MAP.get(b.typeId)?.priority||99)||a.id-b.id))processFacility(w,f,year);applyBread(w);repair(w);buildExpansion(w,year);maybeStartGreatWork(w,year);incidents(w,year);updateAssets(w);const totals=productTotals(w),rec={year,active:C.facilities.filter(x=>x.status==='active').length,greatWorks:C.greatWorks.filter(x=>x.status==='active').length,underConstruction:C.greatWorks.filter(x=>x.status==='constructing').length,processed:round(Object.values(totals).reduce((n,x)=>n+x.stock,0)),knowledgePreserved:C.stats.knowledgePreserved,shipsBuilt:round(C.stats.shipsBuilt),weaponsMade:round(C.stats.weaponsMade)};C.annual.push(rec);compact(w);return rec}
function simulateYears(w,years=1,opts={}){initialize(w);const n=Math.max(0,Math.floor(Number(years)||0));for(let i=0;i<n;i++){if(baseSimulator)baseSimulator(w,1,opts);else Resources?.simulateYears?.(w,1,opts);simulateCivicYear(w,absYear(w))}return w.civic}
function simulateTo(w,target,opts={}){const y=absYear(w),t=Math.max(y,Math.floor(Number(target)||y));return simulateYears(w,t-y,opts)}
function settlementView(w,sid){const fs=facilitiesAt(w,sid),m=prepareMarket(w,sid);return{settlement:w.settlements?.[sid],realmId:realmId(w,sid),facilities:fs,active:fs.filter(x=>x.status==='active'),products:PRODUCTS.map(p=>({product:p,stock:Number(m?.processed?.[p.id]||0),production:Number(m?.processedProduction?.[p.id]||0),consumption:Number(m?.processedConsumption?.[p.id]||0)})),greatWorks:w.civic.greatWorks.filter(x=>x.settlementId===sid),baseMarket:Resources?.settlementView?.(w,sid)||null}}
function summary(w){const C=initialize(w),p=productTotals(w);return{facilities:C.facilities.length,active:C.facilities.filter(x=>x.status==='active').length,destroyed:C.facilities.filter(x=>x.status==='destroyed').length,greatWorks:C.greatWorks.filter(x=>x.status==='active').length,underConstruction:C.greatWorks.filter(x=>x.status==='constructing').length,products:PRODUCTS.length,processed:round(Object.values(p).reduce((n,x)=>n+x.stock,0),2),knowledgePreserved:C.stats.knowledgePreserved,knowledgeLost:C.stats.knowledgeLost,artifactsProtected:C.stats.artifactsProtected,shipsBuilt:round(C.stats.shipsBuilt,2),weaponsMade:round(C.stats.weaponsMade,2),archives:C.archives.length}}
function compact(w){const C=initialize(w),cut=C.currentYear-C.settings.retainDetailedYears;if(cut<=0)return;const old=C.annual.filter(x=>x.year<cut);if(!old.length)return;const buckets=new Map();for(const x of old){const start=Math.floor(x.year/250)*250,b=buckets.get(start)||{start,end:start+249,years:0,active:0,greatWorks:0,processed:0};b.years++;b.active+=x.active;b.greatWorks=Math.max(b.greatWorks,x.greatWorks);b.processed+=x.processed;buckets.set(start,b)}for(const b of buckets.values()){const row={start:b.start,end:b.end,years:b.years,meanActive:round(b.active/b.years,2),greatWorks:b.greatWorks,processed:round(b.processed,2)},ex=C.archives.find(x=>x.start===b.start);if(ex)Object.assign(ex,row);else C.archives.push(row)}C.stats.archivedYears+=old.length;C.annual=C.annual.filter(x=>x.year>=cut);C.archives.sort((a,b)=>a.start-b.start)}
function validate(w){const C=initialize(w),e=[];for(const f of C.facilities){if(!TYPE_MAP.has(f.typeId))e.push(`type:${f.id}`);if(!w.settlements?.[f.settlementId])e.push(`settlement:${f.id}`);if(f.condition<0||f.condition>1)e.push(`condition:${f.id}`)}for(const m of w.resources?.markets||[])for(const p of PRODUCTS)if(Number(m.processed?.[p.id]||0)<0)e.push(`negative:${m.settlementId}:${p.id}`);return[...new Set(e)]}
function fingerprint(w){const C=initialize(w),fac=C.facilities.map(f=>`${f.id}:${f.typeId}:${f.settlementId}:${f.status}:${round(f.condition,2)}:${f.level}:${f.greatWorkId||''}:${round(f.construction?.progress||0,2)}`).join('|'),p=Object.entries(productTotals(w)).map(([k,v])=>`${k}:${round(v.stock,2)}`).join('|'),g=C.greatWorks.map(x=>`${x.greatWorkId}:${x.realmId}:${x.status}:${x.completedYear||''}`).join('|');return hash(`${seedOf(w)}|${C.currentYear}|${fac}|${p}|${g}|${C.stats.knowledgeLost}|${round(C.stats.shipsBuilt,2)}`).toString(16).padStart(8,'0')}
const api={VERSION,SCHEMA,TYPES,TYPE_MAP,PRODUCTS,PRODUCT_MAP,GREAT_WORKS,GREAT_MAP,initialize,setBaseSimulator,absYear,makeFacility,facility,facilitiesAt,beginGreatWork,damageInstitution,simulateCivicYear,simulateYears,simulateTo,productTotals,settlementView,summary,compact,validate,fingerprint};
return api;
});