(function(root,factory){
  const api=factory(root&&root.WorldForgeEngine,root&&root.WorldForgeHistory,root&&root.WorldForgeSociety);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeCulture=api;
})(typeof window!=='undefined'?window:globalThis,function(Core,History,Society){
'use strict';
const VERSION='0.7.0',SCHEMA=1;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=2)=>Number(Number(v).toFixed(d));
let baseSimulator=Society?.simulateYears?Society.simulateYears.bind(Society):null;
const CULT_A=['Aurel','Veyr','Thorn','Khar','Myr','Eld','Saren','Orin','Cael','Dren','Val','Ruun','Ilyr','Namar','Sol','Bryn'];
const CULT_B=['ic','ian','ari','ene','ish','ori','ite','an','ethi','wyn','ari','oss','ean','orn'];
const LANG_FAMILIES=['High Speech','River Tongues','Old Steppe','Coastal Cant','Mountain Speech','Forest Tongues','Sun Languages','Northern Branch'];
const TRADITIONS=['Warrior Poets','River Traders','Ancestor Keepers','Stone Builders','Horse Clans','Forest Wardens','Courtly Etiquette','Sacred Hospitality','Guild Crafts','Oral Histories','Frontier Settlers','Scholarly Houses','Seasonal Festivals','Pilgrim Roads','Seafaring Kin','Communal Granaries'];
const VALUES=['Honor','Learning','Prosperity','Piety','Liberty','Order','Kinship','Valor','Hospitality','Tradition','Craft','Exploration'];
const REL_A=['Radiant','Old','Veiled','Sacred','Eternal','Ashen','Golden','Silent','Sevenfold','Dawn','Moonlit','Verdant','Iron','Celestial'];
const REL_B=['Path','Flame','Covenant','Wheel','Choir','Way','Temple','Light','Oath','Mysteries','Faith','Doctrine'];
const DOCTRINES=['Monotheist','Polytheist','Ancestor veneration','Animist','Dualist','Mystery cult','Philosophical','Solar','Chthonic'];
const TENETS=['Charity','Pilgrimage','Asceticism','Ancestor rites','Sacred law','Mysticism','Martial duty','Stewardship','Learning','Ritual feasts','Missionary zeal','Tolerance','Monasticism','Holy craftsmanship'];
function fallbackRng(seed){let h=2166136261>>>0;for(const c of String(seed)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return function(){h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function rngFor(world,year,s=''){return(Core?.rngFromSeed||fallbackRng)(`${world.settings.seed}|CULTURE|${year}|${s}`)}
function pick(r,a){return a[Math.floor(r()*a.length)]}
function shuffle(r,a){const b=[...a];for(let i=b.length-1;i;i--){const j=Math.floor(r()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function history(world){if(!History)throw new Error('WorldForgeHistory required');return History.initialize(world)}
function uniqueName(existing,r,kind){for(let i=0;i<80;i++){const n=kind==='religion'?`${pick(r,REL_A)} ${pick(r,REL_B)}`:`${pick(r,CULT_A)}${pick(r,CULT_B)}`;if(!existing.some(x=>x.name===n))return n}return`${kind==='religion'?'Faith':'Culture'} ${existing.length+1}`}
function colorFor(i){const hue=(i*137.508+27)%360;return`hsl(${hue.toFixed(0)} 42% 56%)`}
function activeRealmIds(world){return world.history.current.realmState.filter(Boolean).filter(x=>x.active).map(x=>x.id)}
function realmSettlements(world,rid){const o=[];world.history.current.settlementKingdomIds.forEach((x,i)=>{if(x===rid)o.push(i)});return o}
function pop(world,sid){return world.history.current.settlementPopulation[sid]||1}
function createCulture(world,c,data={}){const r=data.rng||rngFor(world,c.currentYear,`culture-${c.cultures.length}`),id=c.cultures.length,name=data.name||uniqueName(c.cultures,r,'culture');const x={id,name,color:colorFor(id),language:data.language||`${name} Speech`,languageFamily:data.languageFamily||pick(r,LANG_FAMILIES),traditions:data.traditions||shuffle(r,TRADITIONS).slice(0,3),values:data.values||shuffle(r,VALUES).slice(0,2),originRealmId:data.originRealmId??null,originSettlementId:data.originSettlementId??null,foundedYear:data.foundedYear??c.currentYear,parentId:data.parentId??null,active:true,prestige:round(data.prestige??(35+r()*35),1),cohesion:round(data.cohesion??(55+r()*30),1)};c.cultures.push(x);c.stats.culturesFormed++;return x}
function createReligion(world,c,data={}){const r=data.rng||rngFor(world,c.currentYear,`religion-${c.religions.length}`),id=c.religions.length,name=data.name||uniqueName(c.religions,r,'religion'),holy=data.holySiteIds||[Math.floor(r()*world.settlements.length)];const x={id,name,color:colorFor(id+31),doctrine:data.doctrine||pick(r,DOCTRINES),tenets:data.tenets||shuffle(r,TENETS).slice(0,3),holySiteIds:holy,originSettlementId:data.originSettlementId??holy[0],foundedYear:data.foundedYear??c.currentYear,parentId:data.parentId??null,active:true,fervor:round(data.fervor??(45+r()*40),1),authority:round(data.authority??(38+r()*35),1)};c.religions.push(x);c.stats.religionsFormed++;return x}
function weightedDominant(world,ids,values){const score=new Map();for(let i=0;i<values.length;i++){const id=values[i];score.set(id,(score.get(id)||0)+pop(world,i)*(ids?.[i]??1))}return[...score.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]??0}
function recomputeRealms(world,c){c.realmCultureIds={};c.realmReligionIds={};for(const rid of activeRealmIds(world)){const sids=realmSettlements(world,rid),cs=new Map(),rs=new Map();for(const sid of sids){const p=pop(world,sid);cs.set(c.settlementCultureIds[sid],(cs.get(c.settlementCultureIds[sid])||0)+p);rs.set(c.settlementReligionIds[sid],(rs.get(c.settlementReligionIds[sid])||0)+p)}c.realmCultureIds[rid]=[...cs.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]??0;c.realmReligionIds[rid]=[...rs.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]??0}}
function seed(world,c){const r=rngFor(world,c.currentYear,'seed'),realms=activeRealmIds(world),cultureCount=clamp(Math.max(4,Math.ceil(realms.length*.85)),4,12);for(let i=0;i<cultureCount;i++){const rid=realms[i%Math.max(1,realms.length)],sid=world.history.realms[rid]?.capitalId??i%world.settlements.length;createCulture(world,c,{rng:r,originRealmId:rid,originSettlementId:sid})}const relCount=clamp(Math.ceil(cultureCount*.65),3,9);for(let i=0;i<relCount;i++)createReligion(world,c,{rng:r,holySiteIds:[(i*7+Math.floor(r()*5))%world.settlements.length]});for(let sid=0;sid<world.settlements.length;sid++){const rid=world.history.current.settlementKingdomIds[sid],base=Math.abs(Number(rid)||0)%cultureCount;c.settlementCultureIds[sid]=(base+(r()<.14?1:0))%cultureCount;c.settlementReligionIds[sid]=(base+(r()<.28?Math.floor(r()*relCount):0))%relCount;c.identity[sid]=round(.58+r()*.36,3);c.fervor[sid]=round(.35+r()*.5,3);c.tolerance[sid]=round(.25+r()*.6,3)}recomputeRealms(world,c)}
function initialize(world){history(world);if(world.culture&&world.culture.schemaVersion===SCHEMA){world.culture.engineVersion=VERSION;return world.culture}const y=world.history.currentYear,c={schemaVersion:SCHEMA,engineVersion:VERSION,startYear:y,currentYear:y,cultures:[],religions:[],settlementCultureIds:new Array(world.settlements.length).fill(0),settlementReligionIds:new Array(world.settlements.length).fill(0),identity:new Array(world.settlements.length).fill(.7),fervor:new Array(world.settlements.length).fill(.6),tolerance:new Array(world.settlements.length).fill(.5),realmCultureIds:{},realmReligionIds:{},snapshots:[],stats:{culturesFormed:0,religionsFormed:0,cultureShifts:0,conversions:0,schisms:0,revivals:0}};world.culture=c;seed(world,c);takeSnapshot(world,c,true);return c}
function pushEvent(world,e){const h=history(world);h.events.push({id:h.events.length,year:h.currentYear,...e})}
function roadDiffusion(world,c,year,r){for(let ri=0;ri<world.roads.length;ri++){const road=world.roads[ri],a=road.from,b=road.to,trade=world.history.current.tradeVolumes[ri]||0;if(trade<=0)continue;const strength=clamp(Math.log1p(trade)/18,0,.18);for(const [from,to] of r()<.5?[[a,b],[b,a]]:[[b,a],[a,b]]){if(c.settlementCultureIds[from]!==c.settlementCultureIds[to]&&c.identity[to]<.62&&r()<strength*.055){c.settlementCultureIds[to]=c.settlementCultureIds[from];c.identity[to]=.42;c.stats.cultureShifts++;if(r()<.22)pushEvent(world,{type:'culture_shift',importance:1,settlementIds:[to],title:`Cultural shift in ${world.settlements[to].name}`,text:`Migration and trade make ${c.cultures[c.settlementCultureIds[to]]?.name} customs dominant.`})}if(c.settlementReligionIds[from]!==c.settlementReligionIds[to]&&c.tolerance[to]>.35&&r()<strength*.075*c.fervor[from]){c.settlementReligionIds[to]=c.settlementReligionIds[from];c.fervor[to]=round(.38+r()*.25,3);c.stats.conversions++;if(r()<.18)pushEvent(world,{type:'conversion',importance:1,settlementIds:[to],title:`New faith spreads in ${world.settlements[to].name}`,text:`${c.religions[c.settlementReligionIds[to]]?.name} becomes the largest local tradition.`})}}}}
function politicalAssimilation(world,c,year,r){for(let sid=0;sid<world.settlements.length;sid++){const rid=world.history.current.settlementKingdomIds[sid],rc=c.realmCultureIds[rid],rr=c.realmReligionIds[rid],pros=world.history.current.settlementProsperity[sid]||.5,st=world.history.current.realmState[rid]?.stability??50;if(rc!=null&&c.settlementCultureIds[sid]!==rc){c.identity[sid]=round(clamp(c.identity[sid]+(st<35?.006:-.003)+(r()-.5)*.008,.1,1),3);if(c.identity[sid]<.26&&r()<.035){c.settlementCultureIds[sid]=rc;c.identity[sid]=.48;c.stats.cultureShifts++}}else c.identity[sid]=round(clamp(c.identity[sid]+.003+(pros-.5)*.002,0,1),3);if(rr!=null&&c.settlementReligionIds[sid]!==rr&&c.tolerance[sid]<.42)c.fervor[sid]=round(clamp(c.fervor[sid]-.004,0,1),3);else c.fervor[sid]=round(clamp(c.fervor[sid]+(r()-.5)*.008,0,1),3);c.tolerance[sid]=round(clamp(c.tolerance[sid]+(r()-.5)*.006+(pros-.5)*.001,0,1),3)}}
function maybeSchism(world,c,year,r){const active=c.religions.filter(x=>x.active);if(active.length>=24||r()>.018)return;const candidates=active.filter(rel=>{let followers=0,heat=0;for(let i=0;i<c.settlementReligionIds.length;i++)if(c.settlementReligionIds[i]===rel.id){followers+=pop(world,i);heat+=c.fervor[i]}return followers>10000&&heat>1});if(!candidates.length)return;const parent=pick(r,candidates),eligible=[];for(let sid=0;sid<world.settlements.length;sid++)if(c.settlementReligionIds[sid]===parent.id&&c.fervor[sid]>.62)eligible.push(sid);if(!eligible.length)return;const origin=pick(r,eligible),child=createReligion(world,c,{rng:r,parentId:parent.id,originSettlementId:origin,holySiteIds:[origin],fervor:55+r()*30,authority:25+r()*35});let changed=0;for(const sid of eligible)if(r()<.18+c.fervor[sid]*.22){c.settlementReligionIds[sid]=child.id;changed++}if(changed){c.stats.schisms++;pushEvent(world,{type:'religious_schism',importance:2,settlementIds:[origin],title:`The ${child.name} emerges`,text:`A schism within the ${parent.name} begins at ${world.settlements[origin].name} and spreads to ${changed} settlements.`})}}
function maybeCultureSplit(world,c,year,r){if(c.cultures.filter(x=>x.active).length>=30||r()>.012)return;const sids=[];for(let sid=0;sid<world.settlements.length;sid++){const rid=world.history.current.settlementKingdomIds[sid],dom=c.realmCultureIds[rid];if(c.settlementCultureIds[sid]!==dom&&c.identity[sid]>.78)sids.push(sid)}if(!sids.length)return;const origin=pick(r,sids),parent=c.cultures[c.settlementCultureIds[origin]],rid=world.history.current.settlementKingdomIds[origin],child=createCulture(world,c,{rng:r,parentId:parent?.id??null,originRealmId:rid,originSettlementId:origin,traditions:shuffle(r,[...(parent?.traditions||[]),...TRADITIONS]).slice(0,3),values:shuffle(r,[...(parent?.values||[]),...VALUES]).slice(0,2)});let changed=0;for(let sid=0;sid<world.settlements.length;sid++){if(c.settlementCultureIds[sid]===parent?.id&&world.history.current.settlementKingdomIds[sid]===rid&&r()<.22){c.settlementCultureIds[sid]=child.id;c.identity[sid]=round(.7+r()*.25,3);changed++}}if(changed)pushEvent(world,{type:'cultural_revival',importance:2,settlementIds:[origin],realmIds:[rid],title:`${child.name} identity takes shape`,text:`A distinct culture descends from ${parent?.name||'older traditions'} around ${world.settlements[origin].name}.`})}
function updateInstitutions(world,c,year,r){for(const x of c.cultures.filter(x=>x.active)){let followers=0;for(let sid=0;sid<c.settlementCultureIds.length;sid++)if(c.settlementCultureIds[sid]===x.id)followers+=pop(world,sid);x.prestige=round(clamp(x.prestige*.997+Math.log1p(followers)*.018+(r()-.5)*.6,0,160),1);x.cohesion=round(clamp(x.cohesion+(r()-.5)*1.2,5,100),1)}for(const x of c.religions.filter(x=>x.active)){let f=0,n=0;for(let sid=0;sid<c.settlementReligionIds.length;sid++)if(c.settlementReligionIds[sid]===x.id){f+=c.fervor[sid];n++}const avg=n?f/n:.3;x.fervor=round(clamp(x.fervor*.985+avg*1.5+(r()-.5)*1.1,2,100),1);x.authority=round(clamp(x.authority+(avg-.5)*.35+(r()-.5)*.8,2,100),1)}}
function simulateCultureYear(world,c,year){c.currentYear=year;const r=rngFor(world,year);recomputeRealms(world,c);roadDiffusion(world,c,year,r);politicalAssimilation(world,c,year,r);maybeSchism(world,c,year,r);maybeCultureSplit(world,c,year,r);updateInstitutions(world,c,year,r);recomputeRealms(world,c);takeSnapshot(world,c,false)}
function takeSnapshot(world,c,force=false){const interval=Math.max(5,world.history?.snapshotInterval||5);if(!force&&c.currentYear%interval!==0)return null;const snap={year:c.currentYear,cultureIds:[...c.settlementCultureIds],religionIds:[...c.settlementReligionIds],identity:c.identity.map(x=>round(x,2)),fervor:c.fervor.map(x=>round(x,2)),realmCultureIds:{...c.realmCultureIds},realmReligionIds:{...c.realmReligionIds},stats:{...c.stats}};const last=c.snapshots.at(-1);if(last?.year===snap.year)c.snapshots[c.snapshots.length-1]=snap;else c.snapshots.push(snap);return snap}
function simulateYears(world,years,options={}){const c=initialize(world),n=Math.max(0,Math.round(Number(years)||0));if(!baseSimulator)throw new Error('Base simulation unavailable');for(let i=0;i<n;i++){baseSimulator(world,1,options);simulateCultureYear(world,c,world.history.currentYear)}takeSnapshot(world,c,true);return c}
function simulateTo(world,target,options={}){const c=initialize(world),t=Math.max(world.history.currentYear,Math.round(Number(target)||0));return simulateYears(world,t-world.history.currentYear,options)}
function setBaseSimulator(fn){if(typeof fn==='function')baseSimulator=fn;return api}
function snapshotAt(world,year){const c=initialize(world),target=Math.min(c.currentYear,Math.max(c.startYear,Math.round(Number(year)||0)));let best=c.snapshots[0];for(const s of c.snapshots)if(s.year<=target&&s.year>=best.year)best=s;return best}
function viewFrom(world,c,s){return{year:s.year,isPresent:s.year===c.currentYear,cultures:c.cultures.map(x=>({...x})),religions:c.religions.map(x=>({...x,holySiteIds:[...x.holySiteIds],tenets:[...x.tenets]})),settlementCultureIds:[...s.cultureIds],settlementReligionIds:[...s.religionIds],identity:[...s.identity],fervor:[...s.fervor],realmCultureIds:{...s.realmCultureIds},realmReligionIds:{...s.realmReligionIds},stats:{...s.stats}}}
function currentView(world){const c=initialize(world),s={year:c.currentYear,cultureIds:c.settlementCultureIds,religionIds:c.settlementReligionIds,identity:c.identity,fervor:c.fervor,realmCultureIds:c.realmCultureIds,realmReligionIds:c.realmReligionIds,stats:c.stats};return viewFrom(world,c,s)}
function viewAt(world,year){const c=initialize(world);if(year>=c.currentYear)return currentView(world);return viewFrom(world,c,snapshotAt(world,year))}
function fingerprint(world){const c=initialize(world);let h=2166136261>>>0,s=`${c.currentYear}|${c.stats.cultureShifts}|${c.stats.conversions}|${c.stats.schisms}|${c.settlementCultureIds.join(',')}|${c.settlementReligionIds.join(',')}`;for(const ch of s){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function validate(world){const e=[],c=world?.culture,n=world?.settlements?.length||0;if(!c||c.schemaVersion!==SCHEMA)return['culture schema'];if(c.currentYear!==world.history?.currentYear)e.push('culture/history year mismatch');if(c.settlementCultureIds.length!==n||c.settlementReligionIds.length!==n)e.push('settlement culture arrays');for(const id of c.settlementCultureIds)if(!c.cultures[id]){e.push('invalid culture');break}for(const id of c.settlementReligionIds)if(!c.religions[id]){e.push('invalid religion');break}if(!c.snapshots.length||c.snapshots.at(-1).year!==c.currentYear)e.push('culture snapshot');return[...new Set(e)]}
const api={VERSION,SCHEMA,initialize,simulateYears,simulateTo,setBaseSimulator,currentView,viewAt,snapshotAt,fingerprint,validate};
return api;
});