(function(root,factory){
  const api=factory(root&&root.WorldForgeMunicipal,root&&root.WorldForgeHousing,root&&root.WorldForgeHouseholds,root&&root.WorldForgeWorkforce,root&&root.WorldForgeCity);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeEmergency=api;
})(typeof window!=='undefined'?window:globalThis,function(Municipal,Housing,Households,Workforce,City){
'use strict';
if(!Municipal||!Housing||!Households||!Workforce)throw new Error('WorldForge v2.6 requires Municipal, Housing, Households and Workforce');
const VERSION='2.6.0',SCHEMA=1,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
const PATHOGENS=[
 {id:'river_fever',name:'River Fever',fatality:.018,transmission:.72,waterborne:true},
 {id:'grey_pox',name:'Grey Pox',fatality:.026,transmission:.82,crowding:true},
 {id:'dockside_flux',name:'Dockside Flux',fatality:.013,transmission:.9,waterborne:true,trade:true},
 {id:'red_cough',name:'Red Cough',fatality:.02,transmission:1.02,crowding:true},
 {id:'marsh_ague',name:'Marsh Ague',fatality:.011,transmission:.64,waterborne:true}
];
const runtime=new WeakMap(),perf=new WeakMap();
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rand(w,tag,year,sid){return hash(`${w.seed||w.settings?.seed||w.name||'world'}|${tag}|${year}|${sid}`)/4294967295}
function absYear(w){return Workforce.absYear(w)}
function state(w){if(!w.emergency||w.emergency.schemaVersion!==SCHEMA)w.emergency={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:absYear(w),profiles:[],incidents:[],annual:[],archives:[],revision:0,lastAppliedYear:null,settings:{retainDetailedYears:1000,maxIncidents:700,historyThreshold:.34},stats:{activeOutbreaks:0,activeFires:0,annualCases:0,annualDeaths:0,fireLoss:0,emergencySpending:0,quarantinedSettlements:0,meanPreparedness:0,archivedYears:0}};const S=w.emergency;S.engineVersion=VERSION;S.profiles=S.profiles||[];S.incidents=S.incidents||[];S.annual=S.annual||[];S.archives=S.archives||[];S.revision=Number(S.revision||0);S.settings={retainDetailedYears:1000,maxIncidents:700,historyThreshold:.34,...S.settings};S.stats={activeOutbreaks:0,activeFires:0,annualCases:0,annualDeaths:0,fireLoss:0,emergencySpending:0,quarantinedSettlements:0,meanPreparedness:0,archivedYears:0,...S.stats};return S}
function owner(w,sid){return w.history?.current?.settlementKingdomIds?.[sid]??w.settlements?.[sid]?.kingdomId??null}
function blank(sid){return{settlementId:Number(sid),lastYear:null,preparedness:0,responseCapacity:0,quarantine:false,emergencyReserve:0,annualDeaths:0,annualCases:0,annualFireLoss:0,emergencySpending:0,disease:{pathogenId:null,susceptible:0,infected:0,recovered:0,newCases:0,deaths:0,severity:0},fire:{active:false,severity:0,deaths:0,propertyLoss:0},hazards:{disease:0,fire:0},districtAlerts:[]}}
function buildRuntime(w,force=false){const S=state(w),year=absYear(w),municipal=w.municipal?.profiles||[],housing=w.housing?.profiles||[],households=w.households?.profiles||[],markets=w.workforce?.markets||[],cities=w.cities?.cities||[],treasury=w.treasury?.realms||[],sig=`${year}|${w.municipal?.revision||0}|${w.housing?.revision||0}|${w.households?.revision||0}|${w.workforce?.revision||0}|${municipal.length}|${housing.length}|${households.length}|${markets.length}|${cities.length}|${treasury.length}|${S.profiles.length}`;let r=runtime.get(w);if(!force&&r&&r.signature===sig)return r;const by=(a,key)=>new Map(a.map(x=>[Number(key(x)),x])),municipalBy=by(municipal,x=>x.settlementId),housingBy=by(housing,x=>x.settlementId),householdBy=by(households,x=>x.settlementId),marketBy=by(markets,x=>x.settlementId),cityBy=by(cities,x=>x.settlementId??x.id),treasuryBy=by(treasury,x=>x.realmId),profileBy=by(S.profiles,x=>x.settlementId);r={signature:sig,municipalBy,housingBy,householdBy,marketBy,cityBy,treasuryBy,profileBy};runtime.set(w,r);const p=perf.get(w)||{cacheBuilds:0,reads:0,profileHits:0};p.cacheBuilds++;perf.set(w,p);return r}
function syncProfiles(w){const S=state(w),valid=new Set((w.settlements||[]).map(x=>Number(x.id))),by=new Map(S.profiles.map(x=>[Number(x.settlementId),x]));for(const sid of valid)if(!by.has(sid))S.profiles.push(blank(sid));S.profiles=S.profiles.filter(p=>valid.has(Number(p.settlementId)));runtime.delete(w);buildRuntime(w,true);return S}
function profileState(w,sid){sid=Number(sid);const S=state(w),r=buildRuntime(w);let p=r.profileBy.get(sid);if(!p){p=blank(sid);S.profiles.push(p);r.profileBy.set(sid,p)}const q=perf.get(w)||{cacheBuilds:0,reads:0,profileHits:0};q.profileHits++;perf.set(w,q);return p}
function hazards(w,sid){sid=Number(sid);const r=buildRuntime(w),mp=r.municipalBy.get(sid),hp=r.housingBy.get(sid),hh=r.householdBy.get(sid),m=r.marketBy.get(sid),c=r.cityBy.get(sid);if(!mp||!hp||!hh||!m)return null;const cov=mp.coverage||{},urban=['Capital','City','Town'].includes(c?.type||w.settlements?.[sid]?.type),connectivity=clamp((urban?.48:.2)+Number(cov.transit||0)*.28+Number(cov.roads||0)*.16+Number(cov.lighting||0)*.08,0,1),disease=clamp(Number(mp.healthRisk||0)*.56+Number(hp.overcrowdingRate||0)*.16+(1-Number(cov.sanitation||0))*.11+(1-Number(cov.water||0))*.09+connectivity*.08,0,1),fire=clamp(Number(mp.fireRisk||0)*.68+Number(hp.densityIndex||0)*.09+Number(hp.slumShare||0)*.11+(1-Number(cov.fire||0))*.07+(1-Number(cov.water||0))*.05,0,1),response=clamp(.1+Number(cov.healthcare||0)*.24+Number(cov.fire||0)*.23+Number(cov.roads||0)*.1+Number(mp.publicWorksCapacity||0)*.15+Number(mp.utilityReliability||0)*.1+Number(hh.educationIndex||0)*.08,0,1),preparedness=clamp(response*.7+Number(mp.serviceIndex||0)*.2+(1-Number(mp.inequality||0))*.1,0,1);return{mp,hp,hh,m,c,cov,connectivity,disease,fire,response,preparedness}}
function pathogenFor(w,year,sid){return PATHOGENS[hash(`${w.seed||w.name}|pathogen|${year}|${sid}`)%PATHOGENS.length]}
function recordHistory(w,incident){if(!w.history?.events||incident.severity<state(w).settings.historyThreshold)return;const exists=w.history.events.some(e=>e.emergencyIncidentId===incident.id);if(exists)return;const rid=owner(w,incident.settlementId),name=w.settlements?.[incident.settlementId]?.name||`Settlement ${incident.settlementId}`,isDisease=incident.type==='disease_outbreak';w.history.events.push({id:w.history.events.length,year:w.history.currentYear,absoluteYear:incident.year,type:isDisease?'epidemic':'urban_fire',importance:incident.severity>.65?3:2,realmIds:rid==null?[]:[rid],settlementIds:[incident.settlementId],emergencyIncidentId:incident.id,title:isDisease?`${incident.name} outbreak in ${name}`:`Great Fire of ${name}`,text:isDisease?`${name} records ${Math.round(incident.cases||0)} cases and ${Math.round(incident.deaths||0)} deaths as emergency authorities ${incident.quarantine?'impose quarantine and ':''}mobilize public-health services.`:`A major urban fire strikes ${name}, causing ${Math.round(incident.deaths||0)} deaths and ${round(incident.propertyLoss||0,1)} in assessed property losses.`})}
function recordIncident(w,incident){const S=state(w);if(S.incidents.some(x=>x.id===incident.id))return;S.incidents.push(incident);if(S.incidents.length>S.settings.maxIncidents)S.incidents.splice(0,S.incidents.length-S.settings.maxIncidents);recordHistory(w,incident)}
function districtAlerts(h,p){const rows=p.mp?.districts||[];return rows.map(d=>({districtId:d.districtId,name:d.name,kind:d.kind,healthRisk:round(Number(d.healthRisk||0),4),fireRisk:round(Number(d.fireRisk||0),4),alert:Math.max(Number(d.healthRisk||0),Number(d.fireRisk||0))>.62?'critical':Math.max(Number(d.healthRisk||0),Number(d.fireRisk||0))>.42?'watch':'normal'})).sort((a,b)=>Math.max(b.healthRisk,b.fireRisk)-Math.max(a.healthRisk,a.fireRisk)).slice(0,8)}
function chargeEmergency(w,sid,cost,h){cost=Math.max(0,cost);let remaining=cost,local=0,realm=0;const reserve=Math.max(0,Number(h.mp.budget?.reserve||0));local=Math.min(reserve,remaining);if(local>0){h.mp.budget.reserve=round(reserve-local,3);remaining-=local}const account=buildRuntime(w).treasuryBy.get(Number(owner(w,sid)));if(remaining>0&&account){realm=Math.min(remaining,Math.max(0,Number(account.treasury||0))*.02);account.treasury=round(Math.max(0,Number(account.treasury||0)-realm),2);remaining-=realm}return{spent:round(local+realm,3),local:round(local,3),realm:round(realm,3),unfunded:round(remaining,3)}}
function simulateEmergencyYear(w,year=absYear(w)){const S=initialize(w);if(S.lastAppliedYear===year&&S.profiles.every(p=>p.lastYear===year))return S;const r=buildRuntime(w,true);let activeOutbreaks=0,activeFires=0,annualCases=0,annualDeaths=0,fireLoss=0,emergencySpending=0,quarantined=0,prepTotal=0,weight=0;for(const m of w.workforce?.markets||[]){const sid=Number(m.settlementId),h=hazards(w,sid);if(!h)continue;const p=profileState(w,sid),pop=Math.max(20,Math.round(Number(w.history?.current?.settlementPopulation?.[sid]??m.population??100))),prevInf=Math.max(0,Number(p.disease?.infected||0)),prevRec=Math.max(0,Math.min(pop-prevInf,Number(p.disease?.recovered||0)*.88)),pathogen=PATHOGENS.find(x=>x.id===p.disease?.pathogenId)||pathogenFor(w,year,sid),sus=Math.max(0,pop-prevInf-prevRec),outbreakRoll=rand(w,'outbreak',year,sid),trigger=prevInf>=1||h.disease>.76||outbreakRoll<h.disease*.085,seedCases=trigger&&prevInf<1?Math.max(1,Math.round(pop*(.00035+h.disease*.0016))):0,priorQuarantine=Boolean(p.quarantine),contact=pathogen.transmission*(.7+h.disease*.6+Number(h.hp.overcrowdingRate||0)*.55)*(1-h.response*.28-(priorQuarantine?.18:0)),transmitted=prevInf>0?Math.min(pop*.09,prevInf*contact*(sus/Math.max(1,pop))):0,newCases=Math.max(0,Math.min(sus,Math.round(seedCases+transmitted))),recoveries=Math.min(prevInf,Math.round(prevInf*(.48+Number(h.cov.healthcare||0)*.27))),fatality=pathogen.fatality*(.75+h.disease*.7)*(1-Number(h.cov.healthcare||0)*.46),diseaseDeaths=Math.max(0,Math.min(prevInf+newCases,Math.round((prevInf+newCases)*fatality))),infected=Math.max(0,Math.min(pop,prevInf+newCases-recoveries-diseaseDeaths)),recovered=Math.max(0,Math.min(pop-infected,prevRec+recoveries)),severity=clamp((infected/Math.max(1,pop))*5.2+h.disease*.18+(trigger?.04:0),0,1),quarantine=severity>.23&&infected>Math.max(4,pop*.0025);
 const fireRoll=rand(w,'fire',year,sid),fireTrigger=h.fire>.84||fireRoll<h.fire*.065,fireSeverity=fireTrigger?clamp((.1+h.fire*.62+rand(w,'fire-severity',year,sid)*.22)*(1-h.response*.55),.03,.96):0,fireDeaths=fireTrigger?Math.max(0,Math.round(pop*fireSeverity*(.00012+Number(h.hp.slumShare||0)*.00022)*(1-h.response*.38))):0,propertyBase=Math.max(0,Number(h.hp.propertyTaxBase||0)),propertyLoss=fireTrigger?propertyBase*fireSeverity*(.004+Number(h.hp.densityIndex||0)*.0045):0,totalDeaths=diseaseDeaths+fireDeaths,responseCost=(newCases*.000025+diseaseDeaths*.0012+propertyLoss*.013+fireSeverity*.18)*(1.08-h.response*.24),funding=chargeEmergency(w,sid,responseCost,h);
 p.preparedness=round(h.preparedness,4);p.responseCapacity=round(h.response,4);p.quarantine=quarantine;p.annualDeaths=totalDeaths;p.annualCases=newCases;p.annualFireLoss=round(propertyLoss,3);p.emergencySpending=funding.spent;p.emergencyReserve=round(Number(h.mp.budget?.reserve||0),3);p.hazards={disease:round(h.disease,4),fire:round(h.fire,4)};p.disease={pathogenId:infected>0||newCases>0?pathogen.id:null,susceptible:Math.max(0,pop-infected-recovered),infected,recovered,newCases,deaths:diseaseDeaths,severity:round(severity,4)};p.fire={active:fireTrigger,severity:round(fireSeverity,4),deaths:fireDeaths,propertyLoss:round(propertyLoss,3)};p.districtAlerts=districtAlerts(h,{mp:h.mp});p.lastYear=year;
 if(totalDeaths>0&&w.history?.current?.settlementPopulation){w.history.current.settlementPopulation[sid]=Math.max(20,Math.round(Number(w.history.current.settlementPopulation[sid]||pop)-totalDeaths));m.population=w.history.current.settlementPopulation[sid]}
 if(w.history?.current?.settlementProsperity){const old=Number(w.history.current.settlementProsperity[sid]??.45),shock=severity*.009+fireSeverity*.018+funding.unfunded*.0005;w.history.current.settlementProsperity[sid]=round(clamp(old-shock+h.response*.0015,.05,.98),4)}
 h.hp.propertyIndex=round(clamp(Number(h.hp.propertyIndex||1)*(1-fireSeverity*.012),.3,5),4);h.hp.developmentIndex=round(clamp(Number(h.hp.developmentIndex||.3)-fireSeverity*.008,.04,1.4),4);h.hp.slumShare=round(clamp(Number(h.hp.slumShare||0)+fireSeverity*.004,0,.65),4);h.mp.maintenanceBacklog=round(Math.max(0,Number(h.mp.maintenanceBacklog||0)+fireSeverity*1.8),3);m.migrationPressure=round(clamp(Number(m.migrationPressure||0)+severity*.035+fireSeverity*.04-(quarantine?.015:0),-.4,2),4);
 if(newCases>0||infected>0){activeOutbreaks++;recordIncident(w,{id:`disease:${year}:${sid}`,type:'disease_outbreak',year,settlementId:sid,name:pathogen.name,severity:round(severity,4),cases:newCases,deaths:diseaseDeaths,quarantine,responseSpending:funding.spent})}
 if(fireTrigger){activeFires++;recordIncident(w,{id:`fire:${year}:${sid}`,type:'urban_fire',year,settlementId:sid,name:'Urban Fire',severity:round(fireSeverity,4),deaths:fireDeaths,propertyLoss:round(propertyLoss,3),responseSpending:funding.spent})}
 annualCases+=newCases;annualDeaths+=totalDeaths;fireLoss+=propertyLoss;emergencySpending+=funding.spent;if(quarantine)quarantined++;const q=Math.max(1,Number(h.hh.households||1));prepTotal+=p.preparedness*q;weight+=q}
 S.currentYear=year;S.lastAppliedYear=year;S.revision++;S.stats={...S.stats,activeOutbreaks,activeFires,annualCases,annualDeaths,fireLoss:round(fireLoss,2),emergencySpending:round(emergencySpending,2),quarantinedSettlements:quarantined,meanPreparedness:round(prepTotal/Math.max(1,weight),4)};const row={year,...S.stats},i=S.annual.findIndex(x=>x.year===year);if(i>=0)S.annual[i]=row;else S.annual.push(row);maintenance(w);return S}
function settlementView(w,sid){sid=Number(sid);const p=profileState(w,sid),h=hazards(w,sid);if(!h)return null;const name=w.settlements?.[sid]?.name||`Settlement ${sid}`;return{...p,name,type:h.c?.type||w.settlements?.[sid]?.type||'Settlement',population:Number(w.history?.current?.settlementPopulation?.[sid]??h.m.population??0),municipalCoverage:Number(h.mp.serviceIndex||0),healthcareCoverage:Number(h.cov.healthcare||0),waterCoverage:Number(h.cov.water||0),sanitationCoverage:Number(h.cov.sanitation||0),fireCoverage:Number(h.cov.fire||0),overcrowdingRate:Number(h.hp.overcrowdingRate||0),slumShare:Number(h.hp.slumShare||0)}}
function summary(w){const S=initialize(w);return{year:absYear(w),settlements:S.profiles.length,revision:S.revision,...S.stats}}
function maintenance(w){const S=state(w),cut=absYear(w)-S.settings.retainDetailedYears;if(cut>0){const old=S.annual.filter(x=>x.year<cut);if(old.length){const buckets=new Map;for(const r of old){const start=Math.floor(r.year/250)*250,b=buckets.get(start)||{startYear:start,endYear:start+249,years:0,annualCases:0,annualDeaths:0,fireLoss:0,emergencySpending:0};b.years++;b.annualCases+=Number(r.annualCases||0);b.annualDeaths+=Number(r.annualDeaths||0);b.fireLoss+=Number(r.fireLoss||0);b.emergencySpending+=Number(r.emergencySpending||0);buckets.set(start,b)}for(const b of buckets.values()){const ex=S.archives.find(x=>x.startYear===b.startYear);if(ex)Object.assign(ex,b);else S.archives.push(b)}S.annual=S.annual.filter(x=>x.year>=cut);S.stats.archivedYears+=old.length}}if(S.incidents.length>S.settings.maxIncidents)S.incidents.splice(0,S.incidents.length-S.settings.maxIncidents);return S}
function fingerprint(w){const S=initialize(w),s=JSON.stringify({year:S.currentYear,profiles:S.profiles.map(p=>[p.settlementId,p.preparedness,p.quarantine,p.annualDeaths,p.annualCases,p.annualFireLoss,p.emergencySpending,p.disease,p.fire,p.hazards]),incidents:S.incidents.slice(-120),annual:S.annual.slice(-80),stats:S.stats});return hash(s).toString(16).padStart(8,'0')}
function validate(w){const S=initialize(w),e=[];if(S.profiles.length!==(w.settlements?.length||0))e.push('emergency profile coverage');for(const p of S.profiles){if(p.lastYear==null)continue;for(const [k,v] of Object.entries({preparedness:p.preparedness,response:p.responseCapacity,diseaseHazard:p.hazards?.disease,fireHazard:p.hazards?.fire,diseaseSeverity:p.disease?.severity,fireSeverity:p.fire?.severity}))if(!Number.isFinite(Number(v))||Number(v)<0||Number(v)>1)e.push(`${k} ${p.settlementId}`);if(p.disease?.infected<0||p.disease?.recovered<0||p.annualDeaths<0||p.annualCases<0||p.annualFireLoss<0||p.emergencySpending<0)e.push(`emergency accounting ${p.settlementId}`)}return[...new Set(e)]}
function performance(w){const r=buildRuntime(w),p=perf.get(w)||{cacheBuilds:0,reads:0,profileHits:0};p.reads++;perf.set(w,p);return{...p,indexedMunicipal:r.municipalBy.size,indexedHousing:r.housingBy.size,indexedHouseholds:r.householdBy.size,indexedMarkets:r.marketBy.size,indexedProfiles:r.profileBy.size}}
function initialize(w){if(!w)throw new Error('World required');Municipal.initialize(w);return syncProfiles(w)}
function installBridge(){if(Workforce.__emergencyBridge)return;Workforce.__emergencyBridge=true;const rawYear=Workforce.simulateWorkforceYear.bind(Workforce),rawYears=Workforce.simulateYears.bind(Workforce);Workforce.simulateWorkforceYear=function(w,year=Workforce.absYear(w)){const out=rawYear(w,year);simulateEmergencyYear(w,year);return out};Workforce.simulateYears=function(w,years,options={}){const n=Math.max(0,Math.floor(Number(years)||0));for(let i=0;i<n;i++){rawYears(w,1,options);simulateEmergencyYear(w,absYear(w))}return w.workforce};Workforce.simulateTo=function(w,target,options={}){const t=Math.floor(Number(target)||0),now=absYear(w);if(t<now)throw new Error('Emergency-enabled simulation cannot run backward');return Workforce.simulateYears(w,t-now,options)}}
installBridge();const api={VERSION,SCHEMA,PATHOGENS,initialize,absYear,simulateEmergencyYear,settlementView,summary,fingerprint,validate,profileState,hazards,performance,installBridge};return api;
});