(function(root,factory){
  const api=factory(root&&root.WorldForgeEngine,root&&root.WorldForgeHistory,root&&root.WorldForgeSociety,root&&root.WorldForgeCity,root&&root.WorldForgeAdventure,root&&root.WorldForgeStory,root&&root.WorldForgeWiki,root&&root.WorldForgeCulture,root&&root.WorldForgeFactions);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeEndless=api;
})(typeof window!=='undefined'?window:globalThis,function(Core,History,Society,City,Adventure,Story,Wiki,Culture,Factions){
'use strict';
const VERSION='0.9.0',SCHEMA=1,REBASE_AT=4200,REBASE_SHIFT=3000,MAINTENANCE_STEP=25;
let baseSimulator=Factions?.simulateYears?Factions.simulateYears.bind(Factions):Society?.simulateYears?Society.simulateYears.bind(Society):null;
const TIME_KEYS=new Set(['year','startYear','currentYear','birthYear','deathYear','foundingYear','createdYear','formedYear','collapsedYear','dissolvedYear','originYear','discoveredYear','resolvedYear','endYear','completedYear','failedYear','lastChangeYear','lastUpdatedYear']);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=2)=>Number(Number(v).toFixed(d));
function history(w){return History.initialize(w)}
function initialize(w){history(w);Society?.initialize?.(w);City?.initialize?.(w);Adventure?.initialize?.(w);Story?.initialize?.(w);Culture?.initialize?.(w);Factions?.initialize?.(w);if(w.endless&&w.endless.schemaVersion===SCHEMA){w.endless.engineVersion=VERSION;if(!w.endless.baseSeed)w.endless.baseSeed=w.settings.seed;sync(w);return w.endless}const e={schemaVersion:SCHEMA,engineVersion:VERSION,baseSeed:w.settings.seed,epochOffset:0,absoluteYear:w.history.currentYear,rebases:0,lastRebaseAbsoluteYear:null,retention:{recentDetailedYears:500,midDetailYears:2500,midStep:25,ancientStep:100,archiveRecentYears:10000,archiveMidStep:1000,archiveAncientStep:5000},archive:{eras:[],checkpoints:[],eventCount:0,peopleCompacted:0,housesCompacted:0,gangsCompacted:0,sitesCompacted:0,questsCompacted:0,reignsCompacted:0},performance:{maintenanceRuns:0,lastMaintenanceYear:w.history.currentYear,lastBatchMs:0,lastBatchYears:0},async:{running:false,cancelRequested:false}};w.endless=e;checkpoint(w,true);return e}
function setBaseSimulator(fn){if(typeof fn==='function')baseSimulator=fn;return api}
function absoluteYear(w){const e=initialize(w);return e.epochOffset+w.history.currentYear}
function sync(w){const e=w.endless;e.absoluteYear=e.epochOffset+w.history.currentYear;return e.absoluteYear}
function normalizeYears(v){const n=Number(v);if(!Number.isFinite(n)||n<0)throw new Error('Years must be a finite non-negative number');if(n>Number.MAX_SAFE_INTEGER)throw new Error('Year span exceeds JavaScript safe integer range');return Math.floor(n)}
function withEpochSeed(w,fn){const e=initialize(w),old=w.settings.seed;w.settings.seed=e.epochOffset?`${e.baseSeed}|EPOCH:${e.epochOffset}`:e.baseSeed;try{return fn()}finally{w.settings.seed=old}}
function shiftTimes(value,delta,seen=new Set()){if(!value||typeof value!=='object'||seen.has(value))return;seen.add(value);if(Array.isArray(value)){for(const x of value)shiftTimes(x,delta,seen);return}for(const [k,v] of Object.entries(value)){if(typeof v==='number'&&TIME_KEYS.has(k))value[k]=v-delta;else if(v&&typeof v==='object')shiftTimes(v,delta,seen)}}
function snapshotModules(w){return[w.history,w.society,w.cities,w.adventure,w.story,w.culture,w.factions].filter(Boolean)}
function pruneSnapshotsTiered(w){const e=initialize(w),now=absoluteYear(w);for(const m of snapshotModules(w)){if(!Array.isArray(m.snapshots)||m.snapshots.length<3)continue;const by=new Map();for(const s of m.snapshots){const ay=e.epochOffset+s.year,age=now-ay;let keep=age<=e.retention.recentDetailedYears;if(!keep&&age<=e.retention.midDetailYears)keep=ay%e.retention.midStep===0;if(!keep&&age>e.retention.midDetailYears)keep=ay%e.retention.ancientStep===0;if(s.year===m.currentYear||s.year===0)keep=true;if(keep)by.set(s.year,s)}m.snapshots=[...by.values()].sort((a,b)=>a.year-b.year)}}
function prepareSnapshotsForRebase(w,shift){for(const m of snapshotModules(w)){if(!Array.isArray(m.snapshots)||!m.snapshots.length)continue;let base=null;for(const s of m.snapshots)if(s.year<=shift&&(!base||s.year>base.year))base=s;let keep=m.snapshots.filter(s=>s.year>=shift);if(base&&!keep.some(s=>s.year===shift)){base={...base,year:shift};keep.unshift(base)}m.snapshots=keep.sort((a,b)=>a.year-b.year)}}
function eraBucket(e,absYear){const start=Math.floor(absYear/250)*250;let b=e.archive.eras.find(x=>x.startYear===start);if(!b){b={startYear:start,endYear:start+249,eventCounts:{},majorEvents:[],totalEvents:0};e.archive.eras.push(b);e.archive.eras.sort((a,b)=>a.startYear-b.startYear)}return b}
function archiveOldEvents(w,shift){const e=initialize(w),h=w.history,old=h.events.filter(x=>x.year<shift),keep=h.events.filter(x=>x.year>=shift);for(const ev of old){const abs=e.epochOffset+ev.year,b=eraBucket(e,abs);b.totalEvents++;b.eventCounts[ev.type]=(b.eventCounts[ev.type]||0)+1;if((ev.importance||1)>=2&&b.majorEvents.length<16)b.majorEvents.push({year:abs,type:ev.type,title:ev.title,text:ev.text})}e.archive.eventCount+=old.length;const remap=new Map();keep.forEach((ev,i)=>{remap.set(ev.id,i);ev.id=i});h.events=keep;if(w.adventure){for(const s of w.adventure.sites||[])if(s&&s.sourceEventId!=null)s.sourceEventId=remap.has(s.sourceEventId)?remap.get(s.sourceEventId):null;w.adventure.processedEventIds=h.events.map(x=>x.id)}if(w.story){for(const q of w.story.quests||[])if(q&&q.sourceEventId!=null)q.sourceEventId=remap.has(q.sourceEventId)?remap.get(q.sourceEventId):null;w.story.processedEventIds=h.events.map(x=>x.id)}for(const s of h.snapshots||[])s.eventIndex=h.events.filter(ev=>ev.year<=s.year).length;return old.length}
function compactPeople(w,shift){const s=w.society;if(!s?.people)return 0;let n=0;for(let i=0;i<s.people.length;i++){const p=s.people[i];if(!p||p.archived||p.deathYear==null||p.deathYear>=shift-150)continue;s.people[i]={id:p.id,firstName:p.firstName,surname:p.surname,gender:p.gender,birthYear:p.birthYear,deathYear:p.deathYear,realmId:p.realmId,settlementId:p.settlementId,houseId:p.houseId,occupation:'Archived',status:'Archived',wealth:0,prestige:round(p.prestige||0,1),ambition:'Preserved in the ancient record',traits:[],spouseId:null,parentIds:[],childrenIds:[],friendIds:[],rivalIds:[],titleIds:[],createdYear:p.createdYear,archived:true};n++}for(const h of s.houses||[])if(h)h.memberIds=(h.memberIds||[]).filter(id=>{const p=s.people[id];return p&&!p.archived});for(const t of s.titles||[]){if(!t?.reigns?.length)continue;const old=t.reigns.filter(r=>r.endYear!=null&&r.endYear<shift),keep=t.reigns.filter(r=>r.endYear==null||r.endYear>=shift);if(old.length){t.archivedReigns=(t.archivedReigns||0)+old.length;t.reigns=keep;n+=0;w.endless.archive.reignsCompacted+=old.length}}w.endless.archive.peopleCompacted+=n;return n}
function compactHouses(w,shift){const s=w.society;if(!s?.houses)return 0;let n=0;for(let i=0;i<s.houses.length;i++){const h=s.houses[i];if(!h||h.archived||h.status!=='Extinct'||h.foundingYear>=shift-300)continue;s.houses[i]={id:h.id,name:h.name,shortName:h.shortName,realmId:h.realmId,settlementId:h.settlementId,foundingYear:h.foundingYear,founderId:null,headId:null,prestige:round(h.prestige||0,1),status:'Extinct',rulingTitleIds:[],memberIds:[],archived:true};n++}w.endless.archive.housesCompacted+=n;return n}
function compactCities(w,shift){const c=w.cities;if(!c)return;for(const city of c.cities||[])if(city){city.businesses=(city.businesses||[]).filter(b=>b.active||b.foundedYear>=shift-300)}for(let i=0;i<(c.gangs||[]).length;i++){const g=c.gangs[i];if(!g||g.archived||g.active||g.dissolvedYear==null||g.dissolvedYear>=shift-200)continue;c.gangs[i]={id:g.id,cityId:g.cityId,name:g.name,color:g.color,leaderId:null,foundedYear:g.foundedYear,dissolvedYear:g.dissolvedYear,active:false,specialty:g.specialty,members:0,influence:0,heat:0,treasury:0,territoryIds:[],rivalIds:[],archived:true};w.endless.archive.gangsCompacted++}}
function compactAdventure(w,shift){const a=w.adventure;if(!a?.sites)return;for(let i=0;i<a.sites.length;i++){const s=a.sites[i];if(!s||s.archived||s.active||s.lastChangeYear>=shift-200)continue;a.sites[i]={id:s.id,name:s.name,kind:s.kind,settlementId:s.settlementId,realmId:s.realmId,originYear:s.originYear,sourceEventId:null,gangId:s.gangId,active:false,discovered:s.discovered,danger:0,depth:s.depth,rumor:0,rooms:[],edges:[],loot:[],sourcePersonIds:[],lore:s.lore,visits:s.visits,clears:s.clears,lastChangeYear:s.lastChangeYear,archived:true};w.endless.archive.sitesCompacted++}}
function compactStory(w,shift){const s=w.story;if(!s)return;for(let i=0;i<(s.quests||[]).length;i++){const q=s.quests[i];if(!q||q.archived||q.status==='available'||q.resolvedYear==null||q.resolvedYear>=shift-200)continue;s.quests[i]={id:q.id,title:q.title,createdYear:q.createdYear,resolvedYear:q.resolvedYear,status:q.status,giverPersonId:null,targetPersonId:null,settlementId:q.settlementId,realmId:q.realmId,siteId:q.siteId,gangId:q.gangId,sourceEventId:null,tags:q.tags||[],difficulty:q.difficulty,variables:{},reward:q.reward,nodes:[],edges:[],archived:true};for(const k of Object.keys(s.variables||{}))if(k.startsWith(`quest_${q.id}_`))delete s.variables[k];w.endless.archive.questsCompacted++}for(let i=0;i<(s.dialogues||[]).length;i++){const d=s.dialogues[i],q=s.quests?.[d?.questId];if(d&&q?.archived)s.dialogues[i]={id:d.id,questId:d.questId,personId:null,title:d.title,nodes:[],createdYear:d.createdYear,archived:true}}}
function compactFactions(w,shift){const f=w.factions;if(!f)return;for(let i=0;i<(f.organizations||[]).length;i++){const o=f.organizations[i];if(!o||o.archived||o.active||o.dissolvedYear==null||o.dissolvedYear>=shift-200)continue;f.organizations[i]={id:o.id,name:o.name,type:o.type,baseSettlementId:o.baseSettlementId,realmId:o.realmId,cultureId:o.cultureId,religionId:o.religionId,leaderId:null,memberIds:[],foundingYear:o.foundingYear,dissolvedYear:o.dissolvedYear,active:false,influence:0,wealth:0,zeal:0,aggression:0,goal:o.goal,allyIds:[],rivalIds:[],contracts:o.contracts||0,archived:true}}}
function compactEntities(w,shift){compactPeople(w,shift);compactHouses(w,shift);compactCities(w,shift);compactAdventure(w,shift);compactStory(w,shift);compactFactions(w,shift)}
function rebase(w,shift=REBASE_SHIFT){const e=initialize(w),h=w.history;if(h.currentYear<shift+500)return false;archiveOldEvents(w,shift);prepareSnapshotsForRebase(w,shift);compactEntities(w,shift);for(const m of[w.history,w.society,w.cities,w.adventure,w.story,w.culture,w.factions,w.wiki].filter(Boolean))shiftTimes(m,shift);e.epochOffset+=shift;e.rebases++;e.lastRebaseAbsoluteYear=e.epochOffset+h.currentYear;for(const m of snapshotModules(w))if(typeof m.startYear==='number')m.startYear=0;if(w.adventure)w.adventure.processedEventIds=w.history.events.map(x=>x.id);if(w.story)w.story.processedEventIds=w.history.events.map(x=>x.id);sync(w);pruneSnapshotsTiered(w);return true}
function checkpoint(w,force=false){const e=initialize(w),ay=absoluteYear(w);if(!force&&ay%250!==0)return null;const hv=History.currentView(w),cv=Culture?.currentView?.(w),fv=Factions?.currentView?.(w),row={year:ay,population:hv.metrics.population,trade:hv.metrics.trade,activeRealms:hv.metrics.activeRealms,activeWars:hv.metrics.activeWars,prosperity:hv.metrics.meanProsperity,cultures:cv?.cultures?.filter(x=>x.active).length||0,religions:cv?.religions?.filter(x=>x.active).length||0,organizations:fv?.metrics?.active||0,people:w.society?.people?.filter(p=>p&&p.deathYear==null).length||0};const last=e.archive.checkpoints.at(-1);if(last?.year===ay)e.archive.checkpoints[e.archive.checkpoints.length-1]=row;else e.archive.checkpoints.push(row);pruneArchive(w);return row}
function pruneArchive(w){const e=w.endless,now=absoluteYear(w),r=e.retention;e.archive.checkpoints=e.archive.checkpoints.filter(x=>{const age=now-x.year;if(age<=r.archiveRecentYears)return true;if(age<=50000)return x.year%r.archiveMidStep===0;return x.year%r.archiveAncientStep===0});e.archive.eras=e.archive.eras.filter(x=>{const age=now-x.endYear;if(age<=50000)return true;return x.startYear%r.archiveAncientStep===0})}
function maintenance(w){const e=initialize(w);e.performance.maintenanceRuns++;e.performance.lastMaintenanceYear=absoluteYear(w);pruneSnapshotsTiered(w);checkpoint(w,false);return memoryStats(w)}
function nextStep(w,remaining){const e=initialize(w),local=w.history.currentYear,ay=absoluteYear(w);if(local>=REBASE_AT){rebase(w);return 0}const toRebase=REBASE_AT-local;const mod=ay%MAINTENANCE_STEP,toMaintenance=mod===0?MAINTENANCE_STEP:MAINTENANCE_STEP-mod;return Math.max(1,Math.min(remaining,toRebase,toMaintenance,MAINTENANCE_STEP))}
function simulateYears(w,years,options={}){const e=initialize(w),total=normalizeYears(years);if(!baseSimulator)throw new Error('Base simulation unavailable');let remaining=total;const started=Date.now();while(remaining>0){if(w.history.currentYear>=REBASE_AT){rebase(w);continue}const step=nextStep(w,remaining);if(step<=0)continue;withEpochSeed(w,()=>baseSimulator(w,step,options));remaining-=step;sync(w);if(absoluteYear(w)%MAINTENANCE_STEP===0)maintenance(w)}e.performance.lastBatchMs=Date.now()-started;e.performance.lastBatchYears=total;checkpoint(w,false);return e}
function simulateTo(w,target,options={}){const t=normalizeYears(target),now=absoluteYear(w);if(t<now)throw new Error('Endless simulation cannot run backward');return simulateYears(w,t-now,options)}
async function simulateYearsAsync(w,years,options={}){const e=initialize(w),total=normalizeYears(years),batch=Math.max(1,Math.floor(Number(options.batchSize)||100));e.async.running=true;e.async.cancelRequested=false;let done=0;try{while(done<total&&!e.async.cancelRequested){const n=Math.min(batch,total-done);simulateYears(w,n,options);done+=n;if(typeof options.onProgress==='function')options.onProgress({done,total,absoluteYear:absoluteYear(w),localYear:w.history.currentYear,rebases:e.rebases});await new Promise(resolve=>typeof requestAnimationFrame==='function'?requestAnimationFrame(()=>resolve()):setTimeout(resolve,0))}return{done,total,cancelled:e.async.cancelRequested,absoluteYear:absoluteYear(w)}}finally{e.async.running=false}}
async function simulateToAsync(w,target,options={}){const t=normalizeYears(target),now=absoluteYear(w);if(t<now)throw new Error('Target year must be later than the present');return simulateYearsAsync(w,t-now,options)}
function cancel(w){const e=initialize(w);e.async.cancelRequested=true}
function memoryStats(w){const e=initialize(w),mods=snapshotModules(w),snapshots=mods.reduce((n,m)=>n+(m.snapshots?.length||0),0),events=w.history.events.length,people=w.society?.people?.length||0,peopleArchived=w.society?.people?.filter(p=>p?.archived).length||0,sites=w.adventure?.sites?.length||0,quests=w.story?.quests?.length||0,orgs=w.factions?.organizations?.length||0;return{absoluteYear:absoluteYear(w),localYear:w.history.currentYear,epochOffset:e.epochOffset,rebases:e.rebases,snapshots,events,archivedEvents:e.archive.eventCount,people,peopleArchived,sites,quests,organizations:orgs,checkpoints:e.archive.checkpoints.length,eraArchives:e.archive.eras.length}}
function fingerprint(w){const e=initialize(w),m=memoryStats(w);let h=2166136261>>>0,s=`${m.absoluteYear}|${m.localYear}|${m.epochOffset}|${m.rebases}|${e.archive.eventCount}|${e.archive.peopleCompacted}|${w.history.current.settlementKingdomIds.slice(0,16).join(',')}|${Math.round(History.currentView(w).metrics.population)}`;for(const ch of s){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function validate(w){const e=initialize(w),errors=[];const local=w.history.currentYear;if(e.absoluteYear!==e.epochOffset+local)errors.push('absolute year');for(const [name,m] of Object.entries({society:w.society,cities:w.cities,adventure:w.adventure,story:w.story,culture:w.culture,factions:w.factions}))if(m&&m.currentYear!==local)errors.push(`${name} year mismatch`);if(local>=5000)errors.push('legacy cap boundary reached');if(e.rebases>0&&e.epochOffset<=0)errors.push('epoch offset');if(w.settings.seed!==e.baseSeed)errors.push('base seed mutated');return errors}
const api={VERSION,SCHEMA,REBASE_AT,REBASE_SHIFT,initialize,setBaseSimulator,absoluteYear,simulateYears,simulateTo,simulateYearsAsync,simulateToAsync,cancel,rebase,maintenance,memoryStats,fingerprint,validate};return api;
});