(() => {
'use strict';
const X=window.WorldForgeEndless,S=window.WorldForgeSociety;
if(!X||!S||!window.WorldRenderer)return;
const $=s=>document.querySelector(s),fmt=(n,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const ui={world:null,viewYear:null,running:false};
const baseSim=S.simulateYears.bind(S),baseTo=S.simulateTo?.bind(S);X.setBaseSimulator(baseSim);S.simulateYears=function(world,years,options){X.simulateYears(world,years,options);return world.society};S.simulateTo=function(world,target,options){X.simulateTo(world,target,options);return world.society};S.__worldforgeV09BaseSimulate=baseSim;S.__worldforgeV09BaseTo=baseTo;
function install(){document.title='WorldForge · v0.9 Endless Simulation';const v=$('.version-pill');if(v)v.textContent='v0.9 · ENDLESS SIMULATION';const f=document.querySelector('footer span');if(f)f.textContent='WorldForge v0.9 · Endless Simulation';const sim=$('#simState');if(sim)sim.textContent='ENDLESS EMERGENT SIMULATION READY';const arch=$('.architecture-panel');if(arch){arch.querySelector('h2').textContent='v0.9 Endless Simulation State Contract';arch.querySelector('.status-ready').textContent='ENDLESS CORE READY';arch.querySelector('.architecture-grid').innerHTML='<div><b>Absolute World Clock</b><span>No 5,000-year ceiling · epoch rebasing keeps legacy engines inside stable numeric ranges</span></div><div><b>Bounded History</b><span>Recent detail · tiered snapshots · ancient checkpoints · era summaries</span></div><div><b>Entity Lifecycle</b><span>Old people · houses · gangs · sites · quests · organizations compact into archival skeletons</span></div><div><b>Deterministic Epochs</b><span>Each epoch gets a unique seeded random stream while the public world seed remains unchanged</span></div>';arch.querySelector('.help').textContent='The simulation can continue for practical browser-scale time horizons without linear growth of detailed history. v1.0 will integrate culture, factions and archive-era records into the final encyclopedia and release UI.'}
 const marker=$('.history-charts-panel');if(marker&&!$('#endlessPanel'))marker.insertAdjacentHTML('beforebegin',`<section id="endlessPanel" class="panel endless-panel"><div class="panel-head"><div><span class="eyebrow">ENDLESS WORLD KERNEL</span><h2>Long-Run Simulation & Memory Budget</h2></div><span id="endlessState" class="status-ready">READY</span></div><div class="endless-kpis"><div><span>ABSOLUTE YEAR</span><b id="endlessYear">0</b></div><div><span>LOCAL EPOCH YEAR</span><b id="endlessLocal">0</b></div><div><span>EPOCH OFFSET</span><b id="endlessOffset">0</b></div><div><span>REBASES</span><b id="endlessRebases">0</b></div><div><span>LIVE EVENTS</span><b id="endlessEvents">0</b></div><div><span>ARCHIVED EVENTS</span><b id="endlessArchivedEvents">0</b></div><div><span>SNAPSHOTS</span><b id="endlessSnapshots">0</b></div><div><span>ARCHIVED PEOPLE</span><b id="endlessArchivedPeople">0</b></div><div><span>ERA ARCHIVES</span><b id="endlessEras">0</b></div></div><div class="endless-actions"><button data-endless-years="500">+500 years</button><button data-endless-years="1000">+1,000</button><button data-endless-years="10000" class="primary">+10,000 async</button><button id="endlessCancel" disabled>Cancel</button></div><div class="endless-progress"><div><span id="endlessProgressLabel">Recent history remains detailed; ancient history is progressively summarized.</span><b id="endlessProgressPct">IDLE</b></div><i><b id="endlessProgressBar" style="width:0%"></b></i></div><div class="retention-grid"><div><b>Recent replay</b><span>~500 absolute years at normal detail</span></div><div><b>Middle history</b><span>Tiered 25-year checkpoints</span></div><div><b>Ancient history</b><span>100–5,000 year archive sampling + era summaries</span></div><div><b>Simulation clock</b><span>Absolute years survive internal epoch rebases</span></div></div></section>`);
 const target=$('#targetYearInput');if(target){target.removeAttribute('max');target.setAttribute('min','1');target.setAttribute('step','100');target.title='Absolute world year — no fixed simulation cap';}
 document.querySelectorAll('[data-endless-years]').forEach(b=>b.addEventListener('click',()=>runAsync(Number(b.dataset.endlessYears))));$('#endlessCancel')?.addEventListener('click',()=>{if(ui.world)X.cancel(ui.world)});
 $('#runTargetBtn')?.addEventListener('click',e=>{if(!ui.world)return;e.preventDefault();e.stopImmediatePropagation();const target=Math.floor(Number($('#targetYearInput').value)||0),now=X.absoluteYear(ui.world);if(target<=now){setProgress(`Target must be later than Year ${fmt(now)}.`,0,'INVALID');return}runToAsync(target)},true)
}
function setProgress(text,pct=0,state='RUNNING'){const l=$('#endlessProgressLabel'),p=$('#endlessProgressPct'),bar=$('#endlessProgressBar'),s=$('#endlessState');if(l)l.textContent=text;if(p)p.textContent=state;if(bar)bar.style.width=`${Math.max(0,Math.min(100,pct))}%`;if(s)s.textContent=state}
function refreshYearLabels(){if(!ui.world)return;const e=ui.world.endless,offset=e?.epochOffset||0,abs=X.absoluteYear(ui.world),local=ui.world.history.currentYear,hist=ui.viewYear==null?abs:offset+ui.viewYear;const pairs=[['#currentYear',`YEAR ${fmt(hist)}`],['#timelineYear',`Year ${fmt(hist)}`],['#endlessYear',fmt(abs)],['#endlessLocal',fmt(local)],['#endlessOffset',fmt(offset)]];for(const [sel,text] of pairs){const el=$(sel);if(el)el.textContent=text}for(const sel of['#societyYearBadge','#adventureYear','#storyYear','#wikiYear','#cultureYear','#factionYear']){const el=$(sel);if(el)el.textContent=`YEAR ${fmt(hist)}`}const timeline=$('#timelineSlider');if(timeline){const cap=Math.max(0,local);timeline.max=cap;timeline.min=0}const captions=document.querySelectorAll('.timeline-caption span');if(captions.length>=2){captions[0].textContent=`Year ${fmt(offset)}`;captions[captions.length-1].textContent=`Year ${fmt(abs)}`}}
function render(){if(!ui.world||!$('#endlessPanel'))return;const m=X.memoryStats(ui.world);$('#endlessYear').textContent=fmt(m.absoluteYear);$('#endlessLocal').textContent=fmt(m.localYear);$('#endlessOffset').textContent=fmt(m.epochOffset);$('#endlessRebases').textContent=fmt(m.rebases);$('#endlessEvents').textContent=fmt(m.events);$('#endlessArchivedEvents').textContent=fmt(m.archivedEvents);$('#endlessSnapshots').textContent=fmt(m.snapshots);$('#endlessArchivedPeople').textContent=fmt(m.peopleArchived);$('#endlessEras').textContent=fmt(m.eraArchives);refreshYearLabels()}
function lock(on){ui.running=on;document.querySelectorAll('[data-endless-years],.history-action').forEach(b=>b.disabled=on);if($('#endlessCancel'))$('#endlessCancel').disabled=!on;if($('#runTargetBtn'))$('#runTargetBtn').disabled=on}
async function runAsync(years){if(!ui.world||ui.running)return;lock(true);const start=X.absoluteYear(ui.world);setProgress(`Simulating ${fmt(years)} years from Year ${fmt(start)}…`,0,'RUNNING');try{const result=await X.simulateYearsAsync(ui.world,years,{batchSize:100,onProgress:p=>{const pct=p.total?100*p.done/p.total:100;setProgress(`Year ${fmt(p.absoluteYear)} · ${fmt(p.done)} / ${fmt(p.total)} years · ${p.rebases} rebases`,pct,`${pct.toFixed(0)}%`);render()}});setProgress(result.cancelled?`Stopped at Year ${fmt(result.absoluteYear)}.`:`Reached Year ${fmt(result.absoluteYear)}. Ancient detail compacted automatically.`,100,result.cancelled?'CANCELLED':'COMPLETE');render();$('#presentBtn')?.click()}catch(err){console.error(err);setProgress(`Simulation error: ${err.message}`,0,'ERROR')}finally{lock(false)}}
async function runToAsync(target){if(!ui.world||ui.running)return;lock(true);const start=X.absoluteYear(ui.world);setProgress(`Running from Year ${fmt(start)} to ${fmt(target)}…`,0,'RUNNING');try{const result=await X.simulateToAsync(ui.world,target,{batchSize:100,onProgress:p=>{const pct=p.total?100*p.done/p.total:100;setProgress(`Year ${fmt(p.absoluteYear)} · ${fmt(p.done)} / ${fmt(p.total)} years`,pct,`${pct.toFixed(0)}%`);render()}});setProgress(result.cancelled?`Stopped at Year ${fmt(result.absoluteYear)}.`:`Reached absolute Year ${fmt(result.absoluteYear)}.`,100,result.cancelled?'CANCELLED':'COMPLETE');render();$('#presentBtn')?.click()}catch(err){console.error(err);setProgress(`Simulation error: ${err.message}`,0,'ERROR')}finally{lock(false)}}
install();const proto=window.WorldRenderer.prototype,oldSetWorld=proto.setWorld,oldSetHistoryView=proto.setHistoryView;proto.setWorld=function(world){ui.world=world;X.initialize(world);const r=oldSetWorld.call(this,world);ui.viewYear=null;render();return r};proto.setHistoryView=function(v){const r=oldSetHistoryView.call(this,v);if(this.world){ui.world=this.world;ui.viewYear=v?.isPresent?null:(v?.year??null);render()}return r};window.WorldForgeEndlessUI={version:'0.9.0',render,runAsync,runToAsync,state:ui};
})();

// Creator Toolkit loader. Kept separate from the simulation kernel so the v0.9
// regression surface remains stable while Pages can load the v1 creator layer.
(()=>{
  if(typeof document==='undefined'||window.WorldForgeCreatorSuite)return;
  const css=document.createElement('link');css.rel='stylesheet';css.href='creator-suite.css';document.head.appendChild(css);
  const engine=document.createElement('script');engine.src='creator-suite-engine.js';engine.onload=()=>{
    const ui=document.createElement('script');ui.src='creator-suite-ui.js';ui.onload=()=>{
      const current=window.WorldForgeExtensions?.state?.world||window.WorldForgeEndlessUI?.state?.world;
      if(current&&window.WorldForgeCreatorUI){window.WorldForgeCreatorUI.state.world=current;window.WorldForgeCreatorSuite.initialize(current);window.WorldForgeCreatorSuite.starterPack(current);window.WorldForgeCreatorUI.render();}
      document.title='WorldForge · v1.0 Creator Studio';
      const pill=document.querySelector('.version-pill');if(pill)pill.textContent='v1.0 · CREATOR STUDIO';
      const foot=document.querySelector('footer span');if(foot)foot.textContent='WorldForge v1.0 · Creator Studio';
    };document.head.appendChild(ui);
  };document.head.appendChild(engine);
})();