(()=>{
'use strict';
const H=window.WorldForgeHeritage,W=window.WorldForgeWorldbuilding,P=window.WorldForgeHeritagePixel,UI=window.WorldForgeWorldbuildingUI;if(!H||!W||!P||!UI)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(n,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d}),pct=n=>`${fmt(Number(n||0)*100,1)}%`,words=s=>String(s||'').replaceAll('_',' ');
const state={world:null,relic:null,last:null,raf:0};
function world(){return state.world||UI.state.world||window.WorldForgeWorldOrderUI?.state?.world||window.WorldForgeReleaseUI?.state?.world||null}
function ensure(){const panel=$('#worldbuildingPanel');if(!panel||$('#heritageSection'))return;const archaeology=$('#archaeologySection'),note=panel.querySelector('.worldbuilding-note'),html=`<section id="heritageSection" class="heritage-section"><div class="labor-head"><span>HERITAGE, MUSEUMS & RELICS</span><b>PROTECTION · PROVENANCE · EXPEDITIONS · RESTITUTION</b></div><div id="heritageKpis" class="worldbuilding-kpis heritage-kpis"></div><div class="heritage-toolbar"><label>Relic Focus<select id="heritageRelic"></select></label><button id="heritageExport">Export Heritage Ledger</button></div><div id="heritageRelicEmpty" class="heritage-empty"></div><div id="heritageRelicFocus" class="heritage-focus"><div id="heritageRelicCard" class="heritage-relic-card"></div><article id="heritageProvenance" class="heritage-provenance"></article></div><div class="heritage-grid"><div><div class="labor-head"><span>HERITAGE REGISTRY</span></div><div id="heritageRegistry" class="worldbuilding-landmarks"></div><div class="labor-head"><span>MUSEUM NETWORK</span></div><div id="heritageMuseums" class="worldbuilding-landmarks"></div></div><div><div class="labor-head"><span>ARCHAEOLOGICAL EXPEDITIONS</span></div><div id="heritageExpeditions" class="worldbuilding-landmarks"></div><div class="labor-head"><span>RESTITUTION & HERITAGE SECURITY</span></div><div id="heritageDisputes" class="worldbuilding-landmarks"></div></div></div></section>`;if(archaeology)archaeology.insertAdjacentHTML('afterend',html);else if(note)note.insertAdjacentHTML('beforebegin',html);else panel.insertAdjacentHTML('beforeend',html);$('#heritageRelic').onchange=e=>{state.relic=e.target.value;state.last=null;schedule(true)};$('#heritageExport').onclick=exportLedger}
function mini(items){return`<div class="worldbuilding-mini">${items.map(([k,v])=>`<span><i>${esc(k)}</i><b>${esc(v)}</b></span>`).join('')}</div>`}
function render(force=false){if(document.hidden&&!force)return;const w=world();if(!w)return;state.world=w;ensure();if(!$('#heritageSection'))return;H.initialize(w);const sid=Number(UI.state.settlement||$('#worldbuildingSettlement')?.value||0),profile=W.settlementView(w,sid),local=profile.heritage||H.settlementView(w,sid),sum=H.summary(w),relics=local.relics||[];if(!state.relic||!relics.some(r=>r.id===state.relic))state.relic=relics[0]?.id||null;const relic=relics.find(r=>r.id===state.relic)||null,key=`${sum.revision}|${sid}|${state.relic||'none'}|${local.registrySites?.length||0}|${local.museums?.length||0}|${local.claims?.length||0}|${local.incidents?.length||0}`;if(!force&&key===state.last)return;state.last=key;
 $('#heritageKpis').innerHTML=[['REGISTRY',sum.registrySites],['PROTECTED+',sum.protectedSites],['MUSEUMS',sum.museums],['RELICS',sum.relics],['DISPUTED',sum.disputedRelics],['OPEN CLAIMS',sum.openClaims]].map(([k,v])=>`<div><span>${k}</span><b>${esc(v)}</b></div>`).join('');
 const sel=$('#heritageRelic');sel.innerHTML=relics.length?relics.map(r=>`<option value="${esc(r.id)}" ${r.id===state.relic?'selected':''}>${esc(r.title)}${r.disputed?' · DISPUTED':''}</option>`).join(''):'<option value="">No relic records</option>';$('#heritageRelicEmpty').innerHTML=relic?'':`<article><small>NO LOCAL RELIC RECORD</small><p>This settlement has no catalogued relic or museum-held object in the current heritage layer.</p></article>`;$('#heritageRelicFocus').style.display=relic?'grid':'none';if(relic){$('#heritageRelicCard').innerHTML=P.renderRelicCard(profile,relic,{width:520,height:250});$('#heritageProvenance').innerHTML=`<small>${esc(words(relic.currentHolder?.type).toUpperCase())} · ${relic.disputed?'DISPUTED OWNERSHIP':'DOCUMENTED CUSTODY'}</small><h3>${esc(relic.title)}</h3><p>Origin: ${esc(relic.originRealmName)}. Current holder realm: ${esc(relic.currentHolder?.realmName||'unknown')}. ${relic.illicitSuspected?'The provenance model flags a possible illicit transfer.':'No deterministic illicit-transfer flag is active.'}</p>${mini([['SIGNIFICANCE',pct(relic.significance)],['CONDITION',pct(relic.condition)],['CONSERVATION',pct(relic.conservationPriority)],['PROVENANCE',(relic.provenance||[]).length+' EVENTS']])}<ol class="heritage-provenance-list">${(relic.provenance||[]).map(p=>`<li><b>${p.year==null?'UNDATED':`Y${esc(p.year)}`}</b> ${esc(words(p.event))}${p.realmId==null?'':` · Realm ${esc(p.realmId)}`}</li>`).join('')}</ol>`}
 const sites=local.registrySites||[];$('#heritageRegistry').innerHTML=sites.length?sites.map(s=>`<article><div><small>${esc(words(s.status).toUpperCase())} · ${esc(words(s.details?.siteType).toUpperCase())}</small><h3>${esc(s.name)}</h3><p>${esc(s.custodian)} · ${s.publicAccess?'public access':'restricted access'}</p></div>${mini([['HERITAGE SCORE',pct(s.score)],['RISK',pct(s.conservationRisk)],['BUDGET',fmt(s.protectionBudget)],['EMERGENCY PLAN',s.emergencyPlan?'YES':'NO']])}</article>`).join(''):'<article><small>NO HERITAGE REGISTRY SITES</small><p>No archaeological site in this settlement currently enters the heritage registry.</p></article>';
 const museums=local.museums||[];$('#heritageMuseums').innerHTML=museums.length?museums.map(m=>`<article><div><small>${esc(m.tier.toUpperCase())} MUSEUM · FOUNDED Y${esc(m.foundedYear)}</small><h3>${esc(m.name)}</h3></div>${mini([['COLLECTION',m.collectionCount],['DISPLAY',m.displayedCount],['SECURITY',pct(m.security)],['CONSERVATION',pct(m.conservation)],['PRESTIGE',pct(m.prestige)],['DISPUTED',m.disputedCount]])}</article>`).join(''):'<article><small>NO MUSEUM</small><p>This settlement does not currently support a dedicated museum institution.</p></article>';
 const expeditions=local.expeditions||[];$('#heritageExpeditions').innerHTML=expeditions.length?expeditions.map(e=>`<article><div><small>${esc(words(e.status).toUpperCase())} · ${esc(words(e.permitStatus).toUpperCase())}</small><h3>${esc(e.name)}</h3><p>${esc(e.leadSpecialty)} · team ${esc(e.teamSize)} · season ${esc(e.season)}</p></div>${mini([['PROGRESS',pct(e.progress)],['RISK',pct(e.risk)],['BUDGET',fmt(e.budget)],['FINDS',e.discoveryRelicIds.length]])}</article>`).join(''):'<article><small>NO ACTIVE FIELD PROJECT</small><p>No archaeology expedition is attached to this settlement in the current deterministic cycle.</p></article>';
 const claims=(local.claims||[]).map(c=>`<article><div><small>RESTITUTION · ${esc(words(c.status).toUpperCase())}</small><h3>${esc(c.title)}</h3><p>${esc(c.claimantRealmName)} → ${esc(c.holderRealmName)} · ${esc(words(c.basis))}</p></div>${mini([['TENSION',pct(c.tension)],['PUBLIC SUPPORT',pct(c.publicSupport)],['OPENED',`Y${c.openedYear}`]])}</article>`),incidents=(local.incidents||[]).map(i=>`<article><div><small>${esc(words(i.type).toUpperCase())} · ${esc(i.status.toUpperCase())}</small><h3>Heritage security incident</h3><p>${esc(i.description)}</p></div>${mini([['YEAR',`Y${i.year}`],['SEVERITY',pct(i.severity)],['DETECTED',i.detected?'YES':'NO'],['RECOVERED',i.recovered?'YES':'NO']])}</article>`);$('#heritageDisputes').innerHTML=(claims.length||incidents.length)?[...claims,...incidents].join(''):'<article><small>NO LOCAL DISPUTE OR SECURITY INCIDENT</small><p>No restitution claim, looting case, smuggling case or rescue operation is linked to this settlement.</p></article>';
 const status=$('#worldbuildingPanel .status-ready');if(status)status.textContent='v4.3';const pill=$('.version-pill');if(pill)pill.textContent='v4.3 · HERITAGE, MUSEUMS & RELICS';const foot=document.querySelector('footer span');if(foot)foot.textContent='WorldForge v4.3 · Heritage, Museums & Relics';const note=$('#worldbuildingPanel .worldbuilding-note');if(note)note.textContent='v4.3 extends living ruins into protected heritage, museum collections, relic provenance, field expeditions, restitution disputes and heritage-security incidents while retaining deterministic Pixel Civilization rendering.';document.title=`${w.name} · Heritage, Museums & Relics · WorldForge v4.3`}
function schedule(force=false){if(state.raf)return;state.raf=requestAnimationFrame(()=>{state.raf=0;render(force)})}
function exportLedger(){const w=world();if(!w)return;H.initialize(w);const data={version:'4.3',world:w.name,year:W.absYear(w),summary:H.summary(w),registrySites:w.heritage.registrySites,museums:w.heritage.museums,relics:w.heritage.relics,expeditions:w.heritage.expeditions,claims:w.heritage.claims,incidents:w.heritage.incidents,annual:w.heritage.annual.slice(-500),fingerprint:H.fingerprint(w)};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${String(w.name||'worldforge').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-heritage-ledger-y${W.absYear(w)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const observer=new MutationObserver(()=>schedule());observer.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule(true)});setInterval(()=>{if(!document.hidden)schedule()},7000);window.WorldForgeHeritageUI={state,render,schedule};setTimeout(()=>schedule(true),1600);
})();