(function(root,factory){
  const api=factory(root&&root.WorldForgeWorkforce,root&&root.WorldForgeHistory,root&&root.WorldForgeResources,root&&root.WorldForgeInstitutions,root&&root.WorldForgeMilitary,root&&root.WorldForgeTreasury,root&&root.WorldForgeCity);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeHouseholds=api;
})(typeof window!=='undefined'?window:globalThis,function(Workforce,History,Resources,Institutions,Military,Treasury,City){
'use strict';
if(!Workforce)throw new Error('WorldForge v2.3 requires WorldForgeWorkforce');
const VERSION='2.3.0',SCHEMA=1,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
const CLASSES=[
 {id:'landless_poor',name:'Landless Poor',tier:0,description:'Households with insecure work, little property and high exposure to food or rent shocks.'},
 {id:'laborers',name:'Laborers',tier:1,description:'Agricultural, extraction, industrial and construction wage households.'},
 {id:'artisans',name:'Artisans',tier:2,description:'Skilled craft, food-processing, service and transport households.'},
 {id:'merchants',name:'Merchants',tier:3,description:'Commercial, maritime, logistics and finance households tied to exchange networks.'},
 {id:'professionals',name:'Professionals',tier:4,description:'Educated health, knowledge, engineering, education and administrative households.'},
 {id:'clergy',name:'Clergy',tier:4,description:'Religious households supported by temples, archives and community institutions.'},
 {id:'minor_nobility',name:'Minor Nobility',tier:5,description:'Landholding and office-holding elite households below the ruling aristocracy.'},
 {id:'aristocracy',name:'Aristocracy',tier:6,description:'The narrow ruling and high-property stratum centered on capitals and wealthy cities.'}
];
const CLASS_MAP=new Map(CLASSES.map(x=>[x.id,x]));
const sectorClass={Agriculture:'laborers',Extraction:'laborers',Industry:'laborers',Construction:'laborers','Food Processing':'artisans',Crafts:'artisans',Services:'artisans',Transport:'artisans',Maritime:'merchants',Logistics:'merchants',Commerce:'merchants',Finance:'merchants',Health:'professionals',Knowledge:'professionals',Education:'professionals',Engineering:'professionals',Administration:'professionals','Public Service':'professionals',Religion:'clergy','Military Support':'professionals',Military:'laborers',Culture:'professionals'};
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed);return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function seedOf(w){return w.endless?.baseSeed||String(w.settings?.seed||'WORLD').split('|EPOCH:')[0]}
function keyed(w,y,s){return rng(`${seedOf(w)}|HOUSEHOLDS|${y}|${s}`)}
function absYear(w){return Workforce.absYear(w)}
function state(w){if(!w.households||w.households.schemaVersion!==SCHEMA)w.households={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:absYear(w),profiles:[],annual:[],archives:[],settings:{retainDetailedYears:1000,sampleHouseholds:10},stats:{households:0,povertyHouseholds:0,births:0,deaths:0,meanLifeExpectancy:0,meanLiteracy:0,meanEducation:0,meanDisposableIncome:0,mobilityRate:0,archivedYears:0}};const S=w.households;S.engineVersion=VERSION;S.profiles=S.profiles||[];S.annual=S.annual||[];S.archives=S.archives||[];S.settings={retainDetailedYears:1000,sampleHouseholds:10,...S.settings};S.stats={households:0,povertyHouseholds:0,births:0,deaths:0,meanLifeExpectancy:0,meanLiteracy:0,meanEducation:0,meanDisposableIncome:0,mobilityRate:0,archivedYears:0,...S.stats};return S}
function market(w,sid){return Workforce.marketState(w,sid)}
function prosperity(w,sid){return Number(w.history?.current?.settlementProsperity?.[sid]??.45)}
function city(w,sid){return w.cities?.cities?.[sid]||null}
function resourceMarket(w,sid){return w.resources?.markets?.find(x=>x.settlementId===sid)||Resources?.market?.(w,sid)||null}
function facilities(w,sid){return(w.institutions?.facilities||[]).filter(f=>f.status==='active'&&f.settlementId===sid)}
function countFacility(w,sid,type){return facilities(w,sid).filter(f=>f.typeId===type).length}
function underSiege(w,sid){return(w.military?.sieges||[]).some(s=>s.status==='active'&&s.settlementId===sid)}
function profileState(w,sid){const S=state(w);let p=S.profiles.find(x=>x.settlementId===sid);if(!p){p={settlementId:sid,lastYear:null,households:0,averageHouseholdSize:0,dependents:0,employedAdults:0,meanIncome:0,foodCost:0,housingCost:0,disposableIncome:0,meanSavings:0,meanDebt:0,povertyRate:0,classShares:{},birthRate:0,deathRate:0,births:0,deaths:0,naturalChange:0,populationAdjustment:0,lifeExpectancy:0,literacyRate:0,educationIndex:0,apprentices:0,journeymen:0,masters:0,professionals:0,mobilityRate:0,samples:[]};S.profiles.push(p)}return p}
function syncProfiles(w){const S=state(w);for(const s of w.settlements||[])profileState(w,s.id);S.profiles=S.profiles.filter(p=>w.settlements?.[p.settlementId]);return S}
function classDistribution(w,m){const weights=Object.fromEntries(CLASSES.map(c=>[c.id,0]));weights.landless_poor=Math.max(1,m.unemployed+Math.max(0,m.laborForce*.035-m.vacancies*.1));for(const[id,j]of Object.entries(m.jobs||{})){const def=Workforce.JOB_MAP.get(id);if(!def||!j.workers)continue;weights[sectorClass[def.sector]||'artisans']+=j.workers}const pop=Math.max(1,m.population),pros=prosperity(w,m.settlementId),urban=['Capital','City','Town'].includes(w.settlements?.[m.settlementId]?.type);weights.minor_nobility+=pop*(.003+pros*.004+(urban?.002:0));weights.aristocracy+=pop*(.0005+pros*.0015+(w.settlements?.[m.settlementId]?.capital?.002:0));const total=Math.max(1,Object.values(weights).reduce((a,b)=>a+b,0)),shares={};for(const c of CLASSES)shares[c.id]=round(weights[c.id]/total,5);const sum=Object.values(shares).reduce((a,b)=>a+b,0);shares.laborers=round(Math.max(0,(shares.laborers||0)+(1-sum)),5);return shares}
function educationState(w,m){const sid=m.settlementId,lib=countFacility(w,sid,'library'),uni=countFacility(w,sid,'university'),archive=countFacility(w,sid,'temple_archive'),hospital=countFacility(w,sid,'hospital'),pros=prosperity(w,sid),educationIndex=clamp(.12+pros*.42+Math.min(.16,lib*.055)+Math.min(.24,uni*.12)+Math.min(.06,archive*.025),.08,.96),literacy=clamp(.18+educationIndex*.7+Math.min(.06,uni*.02),.12,.97),apprentices=Math.round(m.workingAge*(.018+educationIndex*.035)),journeymen=Math.round(m.employed*(.06+educationIndex*.11)),masters=Math.round(m.employed*(.009+educationIndex*.026)),professionals=Object.entries(m.jobs||{}).reduce((n,[id,j])=>{const d=Workforce.JOB_MAP.get(id);return n+(d&&['Health','Knowledge','Education','Engineering','Administration','Finance'].includes(d.sector)?Number(j.workers||0):0)},0);return{educationIndex:round(educationIndex,4),literacyRate:round(literacy,4),apprentices,journeymen,masters,professionals,hospital}}
function economics(w,m,classShares){const sid=m.settlementId,c=city(w,sid),rm=resourceMarket(w,sid),pros=prosperity(w,sid),households=Math.max(1,Math.round(m.population/(3.65+(1-pros)*.85))),workersPerHousehold=(m.employed+Math.max(0,m.conscripted*.35))/households,meanIncome=Math.max(.2,m.wageIndex*workersPerHousehold*(1+classShares.merchants*.22+classShares.professionals*.16+classShares.minor_nobility*.5+classShares.aristocracy*1.1)),foodSecurity=clamp(Number(rm?.foodSecurity??1),.08,1.4),price=clamp(Number(c?.priceIndex||100)/100,.45,3.6),foodCost=(.58+.5*(1-foodSecurity))*price*(1+.18*(m.children/Math.max(1,m.population))),housingCost=(['Capital','City'].includes(w.settlements?.[sid]?.type)?.42:.26)*price*(.9+pros*.35),disposable=meanIncome-foodCost-housingCost,poverty=clamp(.08+(m.laborForce?m.unemployed/m.laborForce:0)*1.45+Math.max(0,.82-foodSecurity)*.72+Math.max(0,-disposable)*.2-classShares.professionals*.12-classShares.merchants*.08,.015,.82),savings=Math.max(0,disposable)*(.45+pros*.25),debt=Math.max(0,-disposable)*1.8+poverty*.22;return{households,averageHouseholdSize:round(m.population/households,2),dependents:m.children+m.elders,employedAdults:m.employed,meanIncome:round(meanIncome,3),foodCost:round(foodCost,3),housingCost:round(housingCost,3),disposableIncome:round(disposable,3),meanSavings:round(savings,3),meanDebt:round(debt,3),povertyRate:round(poverty,4)}}
function demographics(w,m,econ,edu){const sid=m.settlementId,rm=resourceMarket(w,sid),pros=prosperity(w,sid),food=clamp(Number(rm?.foodSecurity??1),.05,1.4),siege=underSiege(w,sid),recruit=m.recruitmentPressure||0,birthRate=clamp(.0205+(.58-pros)*.008+Math.max(0,food-.85)*.004-econ.povertyRate*.006-edu.educationIndex*.0035-recruit*.008-(siege?.007:0),.006,.04),deathRate=clamp(.0108+(1-pros)*.005+Math.max(0,.8-food)*.022+econ.povertyRate*.006+recruit*.004+(siege?.016:0)-Math.min(.004,edu.hospital*.0017),.005,.065),population=Math.max(0,m.population),births=Math.round(population*birthRate),deaths=Math.round(population*deathRate),naturalChange=births-deaths,lifeExpectancy=clamp(43+pros*15+food*5+edu.hospital*2.6+edu.educationIndex*3-econ.povertyRate*8-recruit*6-(siege?9:0),28,78);return{birthRate:round(birthRate,5),deathRate:round(deathRate,5),births,deaths,naturalChange,lifeExpectancy:round(lifeExpectancy,1)}}
function sampleHouseholds(w,m,p,year){const rr=keyed(w,year,`samples:${m.settlementId}`),classes=CLASSES.map(c=>({c,w:Math.max(0,p.classShares[c.id]||0)})),n=Math.max(4,Math.min(16,state(w).settings.sampleHouseholds||10)),out=[];function pick(){let x=rr(),acc=0;for(const q of classes){acc+=q.w;if(x<=acc)return q.c}return classes.at(-1).c}for(let i=0;i<n;i++){const c=pick(),size=Math.max(1,Math.min(8,Math.round(p.averageHouseholdSize+(rr()-.5)*3))),dependents=Math.max(0,Math.min(size-1,Math.round(size*(.22+rr()*.32)))),tier=1+c.tier*.22,income=round(Math.max(.05,p.meanIncome*tier*(.68+rr()*.62)),2),expense=round((p.foodCost+p.housingCost)*(size/Math.max(1,p.averageHouseholdSize))*(.82+rr()*.35),2);out.push({id:`${m.settlementId}-${year}-${i}`,classId:c.id,className:c.name,size,dependents,income,expense,balance:round(income-expense,2)})}return out}
function applyEducationFeedback(m,p){const bonus=clamp((p.educationIndex-.35)*.045,-.01,.028);m.skillIndex=round(clamp(Number(m.skillIndex||.3)*(1+bonus),.08,1.1),3);for(const j of Object.values(m.jobs||{}))j.skill=round(clamp(Number(j.skill||.3)*(1+bonus),.08,1),3)}
function simulateHouseholdYear(w,year=absYear(w),options={}){Workforce.initialize(w);const S=syncProfiles(w),advancing=Number(year)>Number(S.currentYear),applyPopulation=options.applyPopulation??advancing;let totalHouseholds=0,poor=0,births=0,deaths=0,life=0,literacy=0,education=0,disp=0,mobility=0,popAdj=0;for(const m of w.workforce.markets){const p=profileState(w,m.settlementId),previous={...(p.classShares||{})},classes=classDistribution(w,m),edu=educationState(w,m),econ=economics(w,m,classes),demo=demographics(w,m,econ,edu);Object.assign(p,econ,edu,demo,{classShares:classes,lastYear:year});p.mobilityRate=round(CLASSES.reduce((n,c)=>n+Math.abs((classes[c.id]||0)-(previous[c.id]||classes[c.id]||0)),0)/2,5);p.samples=sampleHouseholds(w,m,p,year);const neutralNet=.012,populationCorrection=applyPopulation?Math.round(m.population*clamp((p.birthRate-p.deathRate-neutralNet)*.32,-.007,.007)):0;p.populationAdjustment=populationCorrection;popAdj+=populationCorrection;if(populationCorrection&&w.history?.current?.settlementPopulation){const sid=m.settlementId;w.history.current.settlementPopulation[sid]=Math.max(20,Number(w.history.current.settlementPopulation[sid]||m.population)+populationCorrection);m.population=Math.max(20,m.population+populationCorrection)}applyEducationFeedback(m,p);totalHouseholds+=p.households;poor+=p.households*p.povertyRate;births+=p.births;deaths+=p.deaths;life+=p.lifeExpectancy*p.households;literacy+=p.literacyRate*p.households;education+=p.educationIndex*p.households;disp+=p.disposableIncome*p.households;mobility+=p.mobilityRate*p.households}S.currentYear=year;S.stats={...S.stats,households:totalHouseholds,povertyHouseholds:Math.round(poor),births,deaths,meanLifeExpectancy:round(life/Math.max(1,totalHouseholds),2),meanLiteracy:round(literacy/Math.max(1,totalHouseholds),4),meanEducation:round(education/Math.max(1,totalHouseholds),4),meanDisposableIncome:round(disp/Math.max(1,totalHouseholds),3),mobilityRate:round(mobility/Math.max(1,totalHouseholds),5)};const row={year,households:totalHouseholds,povertyHouseholds:Math.round(poor),births,deaths,populationAdjustment:popAdj,meanLifeExpectancy:S.stats.meanLifeExpectancy,meanLiteracy:S.stats.meanLiteracy,meanEducation:S.stats.meanEducation,meanDisposableIncome:S.stats.meanDisposableIncome,mobilityRate:S.stats.mobilityRate},i=S.annual.findIndex(x=>x.year===year);if(i>=0)S.annual[i]=row;else S.annual.push(row);maintenance(w);return S}
function settlementView(w,sid){const p=profileState(w,Number(sid)),m=Workforce.settlementView(w,Number(sid));if(!m)return null;return{...p,name:m.name,type:m.type,population:m.population,laborForce:m.laborForce,employed:m.employed,unemployed:m.unemployed,conscripted:m.conscripted,classes:CLASSES.map(c=>({...c,share:p.classShares?.[c.id]||0,households:Math.round(p.households*(p.classShares?.[c.id]||0))})).sort((a,b)=>b.households-a.households)}}
function classView(w,id){const c=CLASS_MAP.get(id);if(!c)return null;const places=syncProfiles(w).profiles.map(p=>({p,share:p.classShares?.[id]||0})).filter(x=>x.share>0).map(x=>({settlementId:x.p.settlementId,name:w.settlements?.[x.p.settlementId]?.name,share:x.share,households:Math.round(x.p.households*x.share)})).sort((a,b)=>b.households-a.households);return{...c,totalHouseholds:places.reduce((n,x)=>n+x.households,0),places}}
function summary(w){const S=initialize(w);return{year:absYear(w),settlements:S.profiles.length,classes:CLASSES.length,...S.stats,povertyRate:S.stats.households?S.stats.povertyHouseholds/S.stats.households:0}}
function maintenance(w){const S=state(w),cut=absYear(w)-S.settings.retainDetailedYears;if(cut<=0)return S;const old=S.annual.filter(x=>x.year<cut);if(!old.length)return S;const buckets=new Map;for(const r of old){const start=Math.floor(r.year/250)*250,b=buckets.get(start)||{startYear:start,endYear:start+249,years:0,households:0,births:0,deaths:0,meanLifeExpectancy:0,meanLiteracy:0};b.years++;b.households+=r.households;b.births+=r.births;b.deaths+=r.deaths;b.meanLifeExpectancy+=r.meanLifeExpectancy;b.meanLiteracy+=r.meanLiteracy;buckets.set(start,b)}for(const b of buckets.values()){b.households=Math.round(b.households/b.years);b.meanLifeExpectancy=round(b.meanLifeExpectancy/b.years,2);b.meanLiteracy=round(b.meanLiteracy/b.years,4);const ex=S.archives.find(x=>x.startYear===b.startYear);if(ex)Object.assign(ex,b);else S.archives.push(b)}S.annual=S.annual.filter(x=>x.year>=cut);S.stats.archivedYears+=old.length;return S}
function fingerprint(w){const S=initialize(w),s=JSON.stringify({year:S.currentYear,profiles:S.profiles.map(p=>[p.settlementId,p.households,p.povertyRate,p.birthRate,p.deathRate,p.lifeExpectancy,p.educationIndex,p.literacyRate,p.disposableIncome,p.mobilityRate,Object.entries(p.classShares||{})]),annual:S.annual.slice(-80),stats:S.stats});return hash(s).toString(16).padStart(8,'0')}
function validate(w){const S=initialize(w),e=[];if(S.profiles.length!==(w.settlements?.length||0))e.push('household profile coverage');for(const p of S.profiles){const sum=Object.values(p.classShares||{}).reduce((a,b)=>a+Number(b||0),0);if(p.lastYear!=null&&Math.abs(sum-1)>.02)e.push(`class accounting ${p.settlementId}`);if(p.households<0||p.povertyRate<0||p.povertyRate>1)e.push(`household accounting ${p.settlementId}`);if(p.lastYear!=null&&(p.lifeExpectancy<20||p.lifeExpectancy>90))e.push(`life expectancy ${p.settlementId}`)}return[...new Set(e)]}
function initialize(w){if(!w)throw new Error('World required');Workforce.initialize(w);return syncProfiles(w)}
function installBridge(){if(Workforce.__householdBridge)return;Workforce.__householdBridge=true;const rawYear=Workforce.simulateWorkforceYear.bind(Workforce),rawYears=Workforce.simulateYears.bind(Workforce);Workforce.simulateWorkforceYear=function(w,year=Workforce.absYear(w)){const out=rawYear(w,year);simulateHouseholdYear(w,year);return out};Workforce.simulateYears=function(w,years,options={}){const n=Math.max(0,Math.floor(Number(years)||0));for(let i=0;i<n;i++){rawYears(w,1,options);simulateHouseholdYear(w,absYear(w))}return w.workforce};Workforce.simulateTo=function(w,target,options={}){const t=Math.floor(Number(target)||0),now=absYear(w);if(t<now)throw new Error('Household-enabled simulation cannot run backward');return Workforce.simulateYears(w,t-now,options)}}
installBridge();const api={VERSION,SCHEMA,CLASSES,CLASS_MAP,initialize,absYear,simulateHouseholdYear,settlementView,classView,summary,fingerprint,validate,profileState,installBridge};return api;
});