(function(root,factory){
  const api=factory(
    root&&root.WorldForgeHistory,
    root&&root.WorldForgeCity,
    root&&root.WorldForgeKnowledge,
    root&&root.WorldForgeArtifacts,
    root&&root.WorldForgeTechnology,
    root&&root.WorldForgeResources
  );
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeInstitutions=api;
})(typeof window!=='undefined'?window:globalThis,function(History,City,Knowledge,Artifacts,Technology,Resources){
'use strict';

const VERSION='1.9.0',SCHEMA=1;
const PRODUCTS=[
  {id:'flour',name:'Flour',category:'Food',unit:'sacks'},
  {id:'bread',name:'Bread',category:'Food',unit:'lots'},
  {id:'lumber',name:'Lumber',category:'Material',unit:'loads'},
  {id:'steel',name:'Steel',category:'Metal',unit:'ingots'},
  {id:'tools',name:'Tools',category:'Industrial',unit:'sets'},
  {id:'weapons',name:'Weapons',category:'Military',unit:'sets'},
  {id:'ships',name:'Ships',category:'Strategic',unit:'hulls'},
  {id:'medicine',name:'Prepared Medicine',category:'Health',unit:'lots'},
  {id:'manuscripts',name:'Manuscripts',category:'Knowledge',unit:'volumes'}
];
const PRODUCT_MAP=new Map(PRODUCTS.map(x=>[x.id,x]));
const TYPES=[
  {id:'farm',name:'Managed Farms',category:'Extraction',priority:10,description:'Organized fields, irrigation and seed stores amplify staple output.'},
  {id:'ranch',name:'Ranches',category:'Extraction',priority:11,description:'Managed herds supply livestock, hides and draft power.'},
  {id:'fishery',name:'Fisheries',category:'Extraction',priority:12,description:'Coastal and river fisheries turn water access into food reserves.'},
  {id:'lumber_camp',name:'Lumber Camps',category:'Extraction',priority:13,description:'Managed forestry supplies construction timber.'},
  {id:'mine',name:'Mines',category:'Extraction',priority:14,description:'Mines extract iron, copper and coal from local deposits.'},
  {id:'granary',name:'Granary',category:'Logistics',priority:20,description:'Protected staple reserves are released during market shortages.'},
  {id:'warehouse',name:'Warehouse',category:'Logistics',priority:21,description:'Warehousing buffers strategic materials and reduces market stress.'},
  {id:'market_hall',name:'Market Hall',category:'Civic',priority:22,description:'Market administration improves allocation and local commercial resilience.'},
  {id:'mill',name:'Mill',category:'Industry',priority:30,description:'Mills turn grain and rice into durable flour.'},
  {id:'bakery',name:'Bakery Quarter',category:'Industry',priority:31,description:'Bakeries convert flour and salt into urban staple food.'},
  {id:'sawmill',name:'Sawmill',category:'Industry',priority:32,description:'Sawmills convert timber into construction-grade lumber.'},
  {id:'foundry',name:'Foundry',category:'Industry',priority:33,description:'Foundries combine iron and coal into higher-value steel.'},
  {id:'smithy',name:'Smithy Complex',category:'Industry',priority:34,description:'Smithies convert steel and lumber into tools and weapons.'},
  {id:'shipyard',name:'Shipyard',category:'Industry',priority:35,description:'Shipyards consume lumber and steel to build strategic hulls.'},
  {id:'hospital',name:'Hospital',category:'Institution',priority:40,description:'Hospitals consume medicine and improve health resilience.'},
  {id:'library',name:'Library',category:'Institution',priority:41,description:'Libraries preserve written knowledge and documentary evidence.'},
  {id:'university',name:'University',category:'Institution',priority:42,description:'Universities convert prosperity and books into sustained research.'},
  {id:'museum',name:'Museum',category:'Institution',priority:43,description:'Museums preserve artifacts, provenance and material memory.'},
  {id:'temple_archive',name:'Temple Archive',category:'Institution',priority:44,description:'Sacred archives preserve religious and political memory.'},
  {id:'observatory',name:'Observatory',category:'Institution',priority:45,description:'Observatories deepen navigation, astronomy and scientific research.'}
];
const TYPE_MAP=new Map(TYPES.map(x=>[x.id,x]));
const GREAT_WORKS=[
  {id:'great_library',name:'Great Library',baseType:'library',requirements:{timber:65,iron:18,copper:8,lumber:42,steel:10},prestige:96},
  {id:'grand_university',name:'Grand University',baseType:'university',requirements:{timber:55,iron:24,copper:10,lumber:36,steel:12},prestige:94},
  {id:'royal_hospital',name:'Royal Hospital',baseType:'hospital',requirements:{timber:46,iron:20,copper:12,lumber:28,steel:8},prestige:88},
  {id:'imperial_shipyard',name:'Imperial Shipyard',baseType:'shipyard',requirements:{timber:90,iron:42,copper:8,lumber:60,steel:24},prestige:93},
  {id:'national_museum',name:'National Museum',baseType:'museum',requirements:{timber:42,iron:16,copper:16,lumber:30,steel:8},prestige:90},
  {id:'sacred_archive',name:'Sacred Archive',baseType:'temple_archive',requirements:{timber:38,iron:12,copper:14,lumber:26,steel:6},prestige:89},
  {id:'great_observatory',name:'Great Observatory',baseType:'observatory',requirements:{timber:38,iron:26,copper:24,lumber:24,steel:14},prestige:92},
  {id:'great_granary',name:'Great Granary',baseType:'granary',requirements:{timber:58,iron:16,lumber:34,steel:6},prestige:84}
];
const GREAT_MAP=new Map(GREAT_WORKS.map(x=>[x.id,x]));
let baseSimulator=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const round=(v,d=3)=>Number(Number(v).toFixed(d));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed);return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function seedOf(w){return w.endless?.baseSeed||String(w.settings?.seed||'WORLD').split('|EPOCH:')[0]}
function keyed(w,y,salt){return rng(`${seedOf(w)}|INSTITUTIONS|${y}|${salt}`)}
function absYear(w){return(w.endless?.epochOffset||0)+Number(w.history?.currentYear||0)}
function setBaseSimulator(fn){if(typeof fn==='function')baseSimulator=fn;return api}
function realmId(w,sid){return w.history?.current?.settlementKingdomIds?.[sid]??w.settlements?.[sid]?.kingdomId??null}
function population(w,sid){return Math.max(20,Number(w.history?.current?.settlementPopulation?.[sid]||w.settlements?.[sid]?.population||200))}
function prosperity(w,sid){return Number(w.history?.current?.settlementProsperity?.[sid]??w.cities?.cities?.[sid]?.prosperity??.45)}
function market(w,sid){return Resources?.market?.(w,sid)||null}
function industryStock(w,sid){const m=market(w,sid);if(!m)return null;m.processed=m.processed||{};m.processedProduction=m.processedProduction||{};m.processedConsumption=m.processedConsumption||{};for(const p of PRODUCTS)if(m.processed[p.id]==null)m.processed[p.id]=0;return m}
function techAdoption(w,rid,id){const r=w.technology?.realms?.find(x=>x.realmId===rid);return Number(r?.known?.[id]?.adoption||0)}
function techEffects(w,rid){try{return Technology?.realmView?.(w,rid)?.effects||{}}catch{return{}}}
function activeWarForRealm(w,rid){for(const wid of w.history?.current?.activeWarIds||[]){const q=w.history?.wars?.[wid];if(q&&(q.attackerId===rid||q.defenderId===rid))return true}return false}
function pushHistory(w,e){const h=History.initialize(w);h.events.push({id:h.events.length,year:h.currentYear,absoluteYear:absYear(w),...e});return h.events.at(-1)}
function makeFacility(w,typeId,sid,year=absYear(w),opts={}){const I=initialize(w),type=TYPE_MAP.get(typeId);if(!type)throw new Error(`Unknown institution type: ${typeId}`);const rid=realmId(w,sid),same=I.facilities.filter(x=>x.settlementId===sid&&x.typeId===typeId&&x.status!=='destroyed').length,id=I.nextId++;const f={id,typeId,settlementId:sid,realmId:rid,foundedYear:year,name:opts.name||`${w.settlements?.[sid]?.name||`Settlement ${sid}`} ${type.name}${same?` ${same+1}`:''}`,status:opts.status||'active',condition:opts.condition??1,level:opts.level||1,prestige:opts.prestige||20+Math.round(prosperity(w,sid)*30),workers:opts.workers||Math.max(6,Math.round(Math.pow(population(w,sid),.45)*(2+type.priority/40))),throughput:0,reserve:{grain:0,rice:0},collection:{sourceIds:[],artifactIds:[]},foundedByRealmId:rid,greatWorkId:opts.greatWorkId||null,construction:opts.construction||null,lastYear:-1};I.facilities.push(f);I.stats.built++;return f}
function seedFacilities(w){const I=w.institutions;for(const s of w.settlements||[]){const m=market(w,s.id),pop=population(w,s.id),capital=!!s.capital,urban=['Capital','City','Town'].includes(s.type),suit=m?.suitability||{};makeFacility(w,'market_hall',s.id,0,{prestige:25});makeFacility(w,'granary',s.id,0,{prestige:22});if((suit.grain||0)>.2||(suit.rice||0)>.25)makeFacility(w,'farm',s.id,0);if((suit.livestock||0)>.28)makeFacility(w,'ranch',s.id,0);if((suit.fish||0)>.34)makeFacility(w,'fishery',s.id,0);if((suit.timber||0)>.28)makeFacility(w,'lumber_camp',s.id,0);if(Math.max(suit.iron||0,suit.copper||0,suit.coal||0)>.23)makeFacility(w,'mine',s.id,0);if((suit.grain||0)>.2||(suit.rice||0)>.22)makeFacility(w,'mill',s.id,0);if(pop>700)makeFacility(w,'bakery',s.id,0);if((suit.timber||0)>.3)makeFacility(w,'sawmill',s.id,0);if((suit.iron||0)>.18)makeFacility(w,'smithy',s.id,0);if(urban)makeFacility(w,'warehouse',s.id,0);if(pop>3000&&((suit.iron||0)>.25||(suit.coal||0)>.2))makeFacility(w,'foundry',s.id,0);if(pop>3200&&(suit.fish||0)>.45)makeFacility(w,'shipyard',s.id,0);if(capital||pop>5000)makeFacility(w,'hospital',s.id,0);if(capital||pop>6500)makeFacility(w,'library',s.id,0);if(capital&&pop>5000)makeFacility(w,'university',s.id,0);if(capital&&pop>6500)makeFacility(w,'museum',s.id,0);if(capital)makeFacility(w,'temple_archive',s.id,0);if(capital&&pop>7500)makeFacility(w,'observatory',s.id,0)}I.seeded=true}
function initialize(w){if(!w)throw new Error('World required');History?.initialize?.(w);City?.initialize?.(w);Knowledge?.initialize?.(w);Artifacts?.initialize?.(w);Technology?.initialize?.(w);Resources?.initialize?.(w);if(!w.institutions||w.institutions.schemaVersion!==SCHEMA)w.institutions={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:absYear(w),nextId:1,facilities:[],greatWorks:[],incidents:[],annual:[],archives:[],realmAssets:{},settings:{maxIncidents:900,retainDetailedYears:1200,greatWorkMinYear:55},stats:{built:0,destroyed:0,greatWorksStarted:0,greatWorksCompleted:0,processed:0,research:0,knowledgePreserved:0,knowledgeLost:0,artifactsProtected:0,shipsBuilt:0,weaponsMade:0,archivedYears:0}};const I=w.institutions;I.engineVersion=VERSION;I.nextId=I.nextId||1;I.facilities=I.facilities||[];I.greatWorks=I.greatWorks||[];I.incidents=I.incidents||[];I.annual=I.annual||[];I.archives=I.archives||[];I.realmAssets=I.realmAssets||{};I.settings={maxIncidents:900,retainDetailedYears:1200,greatWorkMinYear:55,...I.settings};I.stats={built:0,destroyed:0,greatWorksStarted:0,greatWorksCompleted:0,processed:0,research:0,knowledgePreserved:0,knowledgeLost:0,artifactsProtected:0,shipsBuilt:0,weaponsMade:0,archivedYears:0,...I.stats};if(!I.seeded)seedFacilities(w);for(const s of w.settlements||[])industryStock(w,s.id);return I}
function facility(w,id){return initialize(w).facilities.find(x=>x.id===Number(id))||null}
function facilitiesAt(w,sid,{activeOnly=false}={}){return initialize(w).facilities.filter(x=>x.settlementId===Number(sid)&&(!activeOnly||x.status==='active'))}
function consumeBase(w,sid,id,amount){const m=market(w,sid);if(!m)return 0;const have=Math.max(0,Number(m.inventory?.[id]||0)),q=Math.min(have,Math.max(0,amount));m.inventory[id]=round(have-q,3);return q}
function consumeProduct(w,sid,id,amount){const m=industryStock(w,sid);if(!m)return 0;const have=Math.max(0,Number(m.processed[id]||0)),q=Math.min(have,Math.max(0,amount));m.processed[id]=round(have-q,3);m.processedConsumption[id]=round((m.processedConsumption[id]||0)+q,3);return q}
function addBase(w,sid,id,amount){const m=market(w,sid);if(!m)return 0;m.inventory[id]=round(Math.max(0,Number(m.inventory[id]||0)+amount),3);return amount}
function addProduct(w,sid,id,amount){const m=industryStock(w,sid);if(!m)return 0;m.processed[id]=round(Math.max(0,Number(m.processed[id]||0)+amount),3);m.processedProduction[id]=round((m.processedProduction[id]||0)+amount,3);w.institutions.stats.processed+=amount;return amount}
function factor(w,f){const fx=techEffects(w,f.realmId),cond=clamp(f.condition,0,1),level=1+(f.level-1)*.18,pros=.75+prosperity(w,f.settlementId)*.45,tech=1+Number(fx.engineering||0)*.8+Number(fx.food||0)*.35;return cond*level*pros*tech*(f.greatWorkId?1.45:1)}
function extraction(w,f,year){const m=market(w,f.settlementId),rr=keyed(w,year,`extract:${f.id}`),q=(.6+rr()*.5)*factor(w,f);if(!m)return 0;if(f.typeId==='farm'){const id=(m.suitability.rice||0)>(m.suitability.grain||0)*1.15?'rice':'grain';return addBase(w,f.settlementId,id,q*(.6+Number(m.suitability[id]||0)))}if(f.typeId==='ranch')return addBase(w,f.settlementId,'livestock',q*(.5+Number(m.suitability.livestock||0)));if(f.typeId==='fishery')return addBase(w,f.settlementId,'fish',q*(.5+Number(m.suitability.fish||0)));if(f.typeId==='lumber_camp')return addBase(w,f.settlementId,'timber',q*(.5+Number(m.suitability.timber||0)));if(f.typeId==='mine'){const id=['iron','copper','coal'].sort((a,b)=>(m.suitability[b]||0)-(m.suitability[a]||0))[0];return addBase(w,f.settlementId,id,q*(.45+Number(m.suitability[id]||0)))}return 0}
function granary(w,f){const m=market(w,f.settlementId);if(!m)return;const cap=18*f.level*(f.greatWorkId?4:1);for(const id of ['grain','rice']){const short=Number(m.shortages?.[id]||0),stock=Number(m.inventory?.[id]||0),reserve=Number(f.reserve[id]||0);if(short<.12&&stock>6&&reserve<cap){const q=Math.min(stock*.035,cap-reserve);m.inventory[id]=round(stock-q,3);f.reserve[id]=round(reserve+q,3)}else if(short>.4&&reserve>.05){const q=Math.min(reserve,2.5+short*8*f.level);f.reserve[id]=round(reserve-q,3);m.inventory[id]=round(stock+q,3);m.shortages[id]=round(short*.62,3);const c=Resources.MAP?.get?.(id);if(c)m.prices[id]=round(c.basePrice*(1+m.shortages[id]*2.2),2);m.foodSecurity=round(Math.max(Number(m.foodSecurity||0),.55+q*.02),3);m.foodDays=round(Math.max(Number(m.foodDays||0),80+q*7),1)}}}
function processFacility(w,f,year){const sid=f.settlementId,fac=factor(w,f),cap=(.7+f.level*.45)*fac;let out=0;if(['farm','ranch','fishery','lumber_camp','mine'].includes(f.typeId))out=extraction(w,f,year);else if(f.typeId==='granary')granary(w,f);else if(f.typeId==='mill'){const g=consumeBase(w,sid,'grain',cap*.9),r=g<cap*.35?consumeBase(w,sid,'rice',cap*.55):0;out=addProduct(w,sid,'flour',(g+r)*.82)}else if(f.typeId==='bakery'){const flour=consumeProduct(w,sid,'flour',cap),salt=consumeBase(w,sid,'salt',cap*.09);const q=Math.min(flour,salt/.09||0);if(q>0){if(flour>q)addProduct(w,sid,'flour',flour-q);out=addProduct(w,sid,'bread',q*.96)}}else if(f.typeId==='sawmill'){const t=consumeBase(w,sid,'timber',cap);out=addProduct(w,sid,'lumber',t*.76)}else if(f.typeId==='foundry'){const iron=consumeBase(w,sid,'iron',cap),coal=consumeBase(w,sid,'coal',cap*.48),q=Math.min(iron,coal/.48||0);if(iron>q)addBase(w,sid,'iron',iron-q);out=addProduct(w,sid,'steel',q*.72)}else if(f.typeId==='smithy'){const steel=consumeProduct(w,sid,'steel',cap*.72),lumber=consumeProduct(w,sid,'lumber',cap*.22),q=Math.min(steel/.72||0,lumber/.22||0);if(q>0){const tools=addProduct(w,sid,'tools',q*.42),weapons=addProduct(w,sid,'weapons',q*.34);out=tools+weapons;w.institutions.stats.weaponsMade+=weapons}}else if(f.typeId==='shipyard'){const lumber=consumeProduct(w,sid,'lumber',cap*1.8),steel=consumeProduct(w,sid,'steel',cap*.55),q=Math.min(lumber/1.8||0,steel/.55||0);if(q>0){out=addProduct(w,sid,'ships',q*.075);w.institutions.stats.shipsBuilt+=out}}else if(f.typeId==='hospital'){const herbs=Math.min(consumeBase(w,sid,'wine',cap*.12)+consumeBase(w,sid,'salt',cap*.08),cap*.2);out=addProduct(w,sid,'medicine',herbs*.8);const h=w.history?.current;if(h?.settlementProsperity){h.settlementProsperity[sid]=round(clamp(Number(h.settlementProsperity[sid]||.4)+.0008*fac,.05,.98),4)}}else if(f.typeId==='market_hall'){const m=market(w,sid);if(m)m.marketStress=round(Math.max(0,Number(m.marketStress||0)-.008*fac),3)}else if(f.typeId==='warehouse'){const m=market(w,sid);if(m)m.marketStress=round(Math.max(0,Number(m.marketStress||0)-.004*fac),3)}else if(f.typeId==='library'||f.typeId==='temple_archive')preserveKnowledge(w,f,year);else if(f.typeId==='museum')preserveArtifacts(w,f,year);else if(f.typeId==='university'||f.typeId==='observatory')out=research(w,f,year);f.throughput=round(out,3);f.lastYear=year;return out}
function preserveKnowledge(w,f,year){const K=Knowledge?.initialize?.(w);if(!K)return 0;const pool=(K.sources||[]).filter(s=>!s.destroyedYear&&s.originRealmId===f.realmId&&!f.collection.sourceIds.includes(s.id)).sort((a,b)=>(b.reliability||0)-(a.reliability||0)||a.id-b.id),take=Math.min(f.greatWorkId?8:3,pool.length);for(const s of pool.slice(0,take)){f.collection.sourceIds.push(s.id);s.archiveStrength=Math.max(Number(s.archiveStrength||0),f.greatWorkId?.98:.82);s.preservedByInstitutionId=f.id;w.institutions.stats.knowledgePreserved++}return take}
function preserveArtifacts(w,f,year){const A=Artifacts?.initialize?.(w);if(!A)return 0;const pool=(A.items||[]).filter(a=>a.status!=='destroyed'&&a.status!=='lost'&&!f.collection.artifactIds.includes(a.id)&&(a.originRealmId===f.realmId||a.ownerId===f.realmId)).sort((a,b)=>(b.prestige||0)-(a.prestige||0)||a.id-b.id),take=Math.min(f.greatWorkId?5:2,pool.length);for(const a of pool.slice(0,take)){f.collection.artifactIds.push(a.id);a.preservedByInstitutionId=f.id;a.condition=round(Math.min(1,Number(a.condition||.7)+.01),3);w.institutions.stats.artifactsProtected++}return take}
function research(w,f,year){const r=w.technology?.realms?.find(x=>x.realmId===f.realmId);if(!r)return 0;const rows=Technology?.realmView?.(w,f.realmId)?.rows||[],candidate=rows.filter(x=>!x.known&&x.unlocked).sort((a,b)=>a.tech.tier-b.tech.tier||a.tech.id.localeCompare(b.tech.id))[0],boost=(f.typeId==='observatory'?1.15:.9)*factor(w,f)*(f.greatWorkId?1.7:1);r.innovationScore=Number(r.innovationScore||0)+boost*.35;if(candidate){r.progress[candidate.tech.id]=round(Number(r.progress[candidate.tech.id]||0)+boost,3);w.institutions.stats.research+=boost}if(f.typeId==='university'&&keyed(w,year,`manuscript:${f.id}`)()<.35)addProduct(w,f.settlementId,'manuscripts',.4*factor(w,f));return boost}
function assetsFor(w,rid){const I=initialize(w),key=String(rid);if(!I.realmAssets[key])I.realmAssets[key]={weapons:0,ships:0,tools:0,research:0,health:0,logistics:0};return I.realmAssets[key]}
function updateAssets(w){const I=initialize(w);I.realmAssets={};for(const f of I.facilities.filter(x=>x.status==='active')){const a=assetsFor(w,f.realmId),m=industryStock(w,f.settlementId);if(!m)continue;a.weapons+=Number(m.processed.weapons||0);a.ships+=Number(m.processed.ships||0);a.tools+=Number(m.processed.tools||0);if(f.typeId==='university'||f.typeId==='observatory')a.research+=f.level*(f.greatWorkId?2:1);if(f.typeId==='hospital')a.health+=f.level*(f.greatWorkId?2:1);if(['granary','warehouse','market_hall','shipyard'].includes(f.typeId))a.logistics+=f.level*(f.greatWorkId?2:1)}for(const a of Object.values(I.realmAssets))for(const k of Object.keys(a))a[k]=round(a[k],2)}
function beginGreatWork(w,rid,greatWorkId,sid=null,year=absYear(w)){const I=initialize(w),g=GREAT_MAP.get(greatWorkId);if(!g)return null;if(I.greatWorks.some(x=>x.realmId===rid&&x.greatWorkId===greatWorkId&&x.status!=='destroyed'))return null;const realm=w.history?.realms?.[rid],target=sid??realm?.capitalId??w.history?.current?.settlementKingdomIds?.findIndex(x=>x===rid);if(target==null||target<0)return null;const name=`${realm?.shortName||'Royal'} ${g.name}`,f=makeFacility(w,g.baseType,target,year,{name,status:'constructing',condition:1,level:3,prestige:g.prestige,greatWorkId,construction:{required:{...g.requirements},delivered:{},progress:0,startedYear:year}});const rec={facilityId:f.id,greatWorkId,realmId:rid,settlementId:target,name,status:'constructing',startedYear:year,completedYear:null};I.greatWorks.push(rec);I.stats.greatWorksStarted++;pushHistory(w,{type:'great_work_started',importance:2,realmIds:[rid],settlementIds:[target],title:`Construction begins on ${name}`,text:`${realm?.shortName||'The realm'} begins a generational civic project: ${name}.`,institutionIds:[f.id]});return rec}
function progressConstruction(w,f,year){if(!f.construction||f.status!=='constructing')return;const req=f.construction.required,del=f.construction.delivered,sid=f.settlementId;let total=0,done=0;for(const [id,need] of Object.entries(req)){total+=need;const have=Number(del[id]||0),left=Math.max(0,need-have);if(left<=0){done+=need;continue}let q=0;if(PRODUCT_MAP.has(id))q=consumeProduct(w,sid,id,Math.min(left,2.2+f.level));else q=consumeBase(w,sid,id,Math.min(left,2.8+f.level));del[id]=round(have+q,3);done+=Math.min(need,del[id])}f.construction.progress=round(done/Math.max(1,total),4);if(f.construction.progress>=.999){f.status='active';f.condition=1;f.level=Math.max(f.level,3);const rec=w.institutions.greatWorks.find(x=>x.facilityId===f.id);if(rec){rec.status='active';rec.completedYear=year}w.institutions.stats.greatWorksCompleted++;pushHistory(w,{type:'great_work_completed',importance:3,realmIds:[f.realmId],settlementIds:[f.settlementId],title:`${f.name} is completed`,text:`After years of material investment, ${f.name} opens as a lasting institution.`,institutionIds:[f.id]})}}
function maybeStartGreatWork(w,year){const I=initialize(w);if(year<I.settings.greatWorkMinYear||year%17!==0)return;for(const rs of w.history?.current?.realmState||[]){if(!rs||rs.active===false)continue;const rid=rs.id,existing=I.greatWorks.filter(x=>x.realmId===rid&&x.status!=='destroyed').length;if(existing>=2)continue;const rr=keyed(w,year,`great:${rid}`);if(rr()>.24+prosperity(w,w.history?.realms?.[rid]?.capitalId??0)*.24)continue;const available=GREAT_WORKS.filter(g=>!I.greatWorks.some(x=>x.realmId===rid&&x.greatWorkId===g.id&&x.status!=='destroyed'));if(!available.length)continue;const weighted=available.filter(g=>{if(g.baseType==='shipyard')return techAdoption(w,rid,'shipbuilding')>.18;if(g.baseType==='university'||g.baseType==='observatory')return techAdoption(w,rid,'writing')>.25;return true});const pool=weighted.length?weighted:available,choice=pool[Math.floor(rr()*pool.length)];beginGreatWork(w,rid,choice.id,null,year)}}
function knowledgeLoss(w,f,year,cause){const K=Knowledge?.initialize?.(w);if(!K)return 0;let lost=0;for(const id of f.collection?.sourceIds||[]){const s=K.sources?.[id];if(!s||s.destroyedYear)continue;s.destroyedYear=year;s.destroyedBy=cause;s.archiveStrength=0;const c=K.claims?.find(x=>x.key===s.claimKey);if(c)c.sourceIds=(c.sourceIds||[]).filter(x=>x!==id);lost++}w.institutions.stats.knowledgeLost+=lost;return lost}
function artifactLoss(w,f,year,cause){const A=Artifacts?.initialize?.(w);if(!A)return 0;let lost=0;for(const id of f.collection?.artifactIds||[]){const a=A.items?.find(x=>x.id===id);if(!a||a.status==='destroyed')continue;a.status='lost';a.lostYear=year;a.preservedByInstitutionId=null;a.provenance=a.provenance||[];a.provenance.push({year,action:'lost',note:`Lost when ${f.name} suffered ${cause}.`});lost++}return lost}
function damageInstitution(w,id,severity=.35,cause='fire',year=absYear(w)){const f=facility(w,id);if(!f||f.status==='destroyed')return null;const I=initialize(w),before=f.condition;f.condition=round(clamp(before-Math.abs(severity),0,1),3);if(f.condition<=.12){f.status='destroyed';I.stats.destroyed++;const knowledgeLost=['library','temple_archive','university'].includes(f.typeId)?knowledgeLoss(w,f,year,cause):0,artifactsLost=f.typeId==='museum'?artifactLoss(w,f,year,cause):0;const g=I.greatWorks.find(x=>x.facilityId===f.id);if(g)g.status='destroyed';I.incidents.push({id:I.incidents.length,year,type:'institution_destroyed',facilityId:f.id,settlementId:f.settlementId,realmId:f.realmId,cause,severity:1,knowledgeLost,artifactsLost,title:`${f.name} is destroyed`});pushHistory(w,{type:'institution_destroyed',importance:f.greatWorkId?3:2,realmIds:[f.realmId],settlementIds:[f.settlementId],title:`${f.name} is destroyed`,text:`${cause} destroys ${f.name}${knowledgeLost?`, erasing ${knowledgeLost} preserved sources`:''}${artifactsLost?`, scattering ${artifactsLost} artifacts`:''}.`,institutionIds:[f.id]})}else{f.status='damaged';I.incidents.push({id:I.incidents.length,year,type:'institution_damaged',facilityId:f.id,settlementId:f.settlementId,realmId:f.realmId,cause,severity,knowledgeLost:0,artifactsLost:0,title:`${f.name} is damaged`})}return f}
function incidents(w,year){const I=initialize(w);for(const f of I.facilities.filter(x=>x.status==='active')){const war=activeWarForRealm(w,f.realmId),crime=Number(w.cities?.cities?.[f.settlementId]?.crimeRate||0)/100,rr=keyed(w,year,`incident:${f.id}`),risk=.0007+crime*.0015+(war?.006:0);if(rr()<risk){const cause=war&&rr()<.72?'wartime destruction':crime>.6&&rr()<.45?'arson':'fire';damageInstitution(w,f.id,.22+rr()*(war?.55:.32),cause,year)}}if(I.incidents.length>I.settings.maxIncidents)I.incidents.splice(0,I.incidents.length-I.settings.maxIncidents)}
function repair(w,year){for(const f of initialize(w).facilities.filter(x=>x.status==='damaged')){const m=market(w,f.settlementId),q=consumeBase(w,f.settlementId,'timber',.35*f.level)+consumeBase(w,f.settlementId,'iron',.12*f.level);if(q>.1){f.condition=round(Math.min(1,f.condition+.04+q*.018),3);if(f.condition>.72)f.status='active'}}}
function buildExpansion(w,year){if(year%12!==0)return;for(const s of w.settlements||[]){const sid=s.id,pop=population(w,sid),rid=realmId(w,sid),types=new Set(facilitiesAt(w,sid,{activeOnly:true}).map(x=>x.typeId));const add=id=>{if(!types.has(id)){makeFacility(w,id,sid,year);types.add(id)}};if(pop>2200)add('warehouse');if(pop>3200)add('hospital');if(pop>4500&&techAdoption(w,rid,'writing')>.2)add('library');if(pop>6500&&techAdoption(w,rid,'universities')>.15)add('university');if(pop>6000&&techAdoption(w,rid,'medicine')>.18)add('hospital');if(pop>7000&&techAdoption(w,rid,'shipbuilding')>.2&&(market(w,sid)?.suitability?.fish||0)>.35)add('shipyard');if(pop>6000&&techAdoption(w,rid,'ironworking')>.2)add('foundry');if(pop>8000&&techAdoption(w,rid,'navigation')>.25)add('observatory')}}
function applyBread(w){for(const s of w.settlements||[]){const m=industryStock(w,s.id);if(!m)continue;const bread=Number(m.processed.bread||0);if(bread<=0)continue;const use=Math.min(bread,Math.max(.15,population(w,s.id)*.00008));m.processed.bread=round(bread-use,3);m.processedConsumption.bread=round((m.processedConsumption.bread||0)+use,3);m.foodSecurity=round(Math.max(Number(m.foodSecurity||0),Math.min(1.6,Number(m.foodSecurity||0)+use*.025)),3);m.foodDays=round(Math.min(720,Number(m.foodDays||0)+use*2.8),1);m.marketStress=round(Math.max(0,Number(m.marketStress||0)-use*.0018),3)}}
function simulateInstitutionYear(w,year=absYear(w)){const I=initialize(w);I.currentYear=year;for(const m of I.facilities.map(x=>industryStock(w,x.settlementId)).filter(Boolean)){m.processedProduction={};m.processedConsumption={}}for(const f of I.facilities.filter(x=>x.status==='constructing'))progressConstruction(w,f,year);for(const f of I.facilities.filter(x=>x.status==='active').sort((a,b)=>(TYPE_MAP.get(a.typeId)?.priority||99)-(TYPE_MAP.get(b.typeId)?.priority||99)||a.id-b.id))processFacility(w,f,year);applyBread(w);repair(w,year);buildExpansion(w,year);maybeStartGreatWork(w,year);incidents(w,year);updateAssets(w);const active=I.facilities.filter(x=>x.status==='active'),products=productTotals(w),rec={year,active:active.length,greatWorks:I.greatWorks.filter(x=>x.status==='active').length,underConstruction:I.greatWorks.filter(x=>x.status==='constructing').length,processed:Object.values(products).reduce((n,x)=>n+x.stock,0),knowledgePreserved:I.stats.knowledgePreserved,shipsBuilt:I.stats.shipsBuilt,weaponsMade:I.stats.weaponsMade};I.annual.push(rec);compact(w);return rec}
function simulateYears(w,years=1,opts={}){initialize(w);const n=Math.max(0,Math.floor(Number(years)||0));for(let i=0;i<n;i++){if(baseSimulator)baseSimulator(w,1,opts);else if(Resources?.simulateYears)Resources.simulateYears(w,1,opts);simulateInstitutionYear(w,absYear(w))}return w.institutions}
function simulateTo(w,target,opts={}){const y=absYear(w),t=Math.max(y,Math.floor(Number(target)||y));return simulateYears(w,t-y,opts)}
function productTotals(w){initialize(w);const out={};for(const p of PRODUCTS)out[p.id]={stock:0,production:0,consumption:0};for(const m of w.resources?.markets||[])for(const p of PRODUCTS){out[p.id].stock+=Number(m.processed?.[p.id]||0);out[p.id].production+=Number(m.processedProduction?.[p.id]||0);out[p.id].consumption+=Number(m.processedConsumption?.[p.id]||0)}for(const v of Object.values(out))for(const k of Object.keys(v))v[k]=round(v[k],3);return out}
function settlementView(w,sid){const fs=facilitiesAt(w,sid),m=industryStock(w,sid);return{settlement:w.settlements?.[sid],realmId:realmId(w,sid),facilities:fs,active:fs.filter(x=>x.status==='active'),products:PRODUCTS.map(p=>({product:p,stock:Number(m?.processed?.[p.id]||0),production:Number(m?.processedProduction?.[p.id]||0),consumption:Number(m?.processedConsumption?.[p.id]||0)})),greatWorks:w.institutions.greatWorks.filter(x=>x.settlementId===sid),baseMarket:Resources?.settlementView?.(w,sid)||null}}
function summary(w){const I=initialize(w),p=productTotals(w),active=I.facilities.filter(x=>x.status==='active');return{facilities:I.facilities.length,active:active.length,destroyed:I.facilities.filter(x=>x.status==='destroyed').length,greatWorks:I.greatWorks.filter(x=>x.status==='active').length,underConstruction:I.greatWorks.filter(x=>x.status==='constructing').length,products:PRODUCTS.length,processed:round(Object.values(p).reduce((n,x)=>n+x.stock,0),2),knowledgePreserved:I.stats.knowledgePreserved,knowledgeLost:I.stats.knowledgeLost,artifactsProtected:I.stats.artifactsProtected,shipsBuilt:round(I.stats.shipsBuilt,2),weaponsMade:round(I.stats.weaponsMade,2),archives:I.archives.length}}
function compact(w){const I=initialize(w),cut=I.currentYear-I.settings.retainDetailedYears;if(cut<=0)return;const old=I.annual.filter(x=>x.year<cut);if(!old.length)return;const buckets=new Map();for(const x of old){const start=Math.floor(x.year/250)*250,key=String(start);if(!buckets.has(key))buckets.set(key,{start,end:start+249,years:0,activeTotal:0,greatWorksMax:0,processedTotal:0});const b=buckets.get(key);b.years++;b.activeTotal+=x.active;b.greatWorksMax=Math.max(b.greatWorksMax,x.greatWorks);b.processedTotal+=x.processed}for(const b of buckets.values()){const ex=I.archives.find(x=>x.start===b.start);const row={start:b.start,end:b.end,years:b.years,meanActive:round(b.activeTotal/b.years,2),greatWorks:b.greatWorksMax,processed:round(b.processedTotal,2)};if(ex)Object.assign(ex,row);else I.archives.push(row)}I.stats.archivedYears+=old.length;I.annual=I.annual.filter(x=>x.year>=cut);I.archives.sort((a,b)=>a.start-b.start)}
function validate(w){const e=[],I=initialize(w);if(!Array.isArray(I.facilities))e.push('facilities');for(const f of I.facilities){if(!TYPE_MAP.has(f.typeId))e.push(`type:${f.id}`);if(!w.settlements?.[f.settlementId])e.push(`settlement:${f.id}`);if(f.condition<0||f.condition>1)e.push(`condition:${f.id}`)}for(const m of w.resources?.markets||[])for(const p of PRODUCTS)if(Number(m.processed?.[p.id]||0)<0)e.push(`negative:${m.settlementId}:${p.id}`);return[...new Set(e)]}
function fingerprint(w){const I=initialize(w),fac=I.facilities.map(f=>`${f.id}:${f.typeId}:${f.settlementId}:${f.status}:${round(f.condition,2)}:${f.level}:${f.greatWorkId||''}:${round(f.construction?.progress||0,2)}`).join('|'),p=Object.entries(productTotals(w)).map(([k,v])=>`${k}:${round(v.stock,2)}`).join('|'),g=I.greatWorks.map(x=>`${x.greatWorkId}:${x.realmId}:${x.status}:${x.completedYear||''}`).join('|');return hash(`${seedOf(w)}|${I.currentYear}|${fac}|${p}|${g}|${I.stats.knowledgeLost}|${round(I.stats.shipsBuilt,2)}`).toString(16).padStart(8,'0')}
const api={VERSION,SCHEMA,TYPES,TYPE_MAP,PRODUCTS,PRODUCT_MAP,GREAT_WORKS,GREAT_MAP,initialize,setBaseSimulator,absYear,facility,facilitiesAt,makeFacility,beginGreatWork,damageInstitution,simulateInstitutionYear,simulateYears,simulateTo,productTotals,settlementView,summary,compact,validate,fingerprint};
return api;
});