(()=>{
'use strict';
const L=window.WorldForgeLivingWiki;
if(!L||!window.WorldRenderer)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>Number(n||0).toLocaleString();
const state={world:null,viewYear:null,lastFingerprint:null};
function currentWorld(){return state.world||window.WorldForgeCanonBridgeUI?.state?.world||window.WorldForgeCreatorUI?.state?.world||window.WorldForgeReleaseUI?.state?.world||window.WorldForgeEndlessUI?.state?.world||null}
function currentViewYear(){const r=window.WorldForgeReleaseUI?.state?.viewYear;if(r!=null)return r;const e=window.WorldForgeEndlessUI?.state?.viewYear;if(e!=null)return e;return state.viewYear}
function ensureHero(){const panel=$('#wikiPanel');if(!panel)return null;if(!$('#livingWikiHero')){const head=panel.querySelector('.panel-head');head?.insertAdjacentHTML('afterend',`<div id="livingWikiHero" class="living-wiki-hero" data-sigil="✦"><div class="living-wiki-title"><span id="livingWikiKicker" class="eyebrow">LIVING WIKI · AUTO THEME</span><h2 id="livingWikiName">Living Chronicle</h2><div id="livingWikiEra" class="living-era"></div><blockquote id="livingWikiMotto"></blockquote><p id="livingWikiNarrative"></p><div id="livingWikiPulse" class="living-wiki-pulse"></div></div><div class="living-wiki-actions"><button id="livingWikiExport">Export Themed HTML</button><button id="livingWikiRefresh">Re-read World</button></div></div><div id="livingWikiFeatured" class="living-wiki-featured"></div>`);$('#livingWikiExport')?.addEventListener('click',exportHtml);$('#livingWikiRefresh')?.addEventListener('click',()=>render(true))}return panel}
function shelves(m){return m.groups.slice(0,8).map(g=>`${g.label} ${g.count}`).join(' · ')}
function render(force=false){const world=currentWorld(),panel=ensureHero();if(!world||!panel)return;state.world=world;const year=currentViewYear(),fp=L.fingerprint(world,year);if(!force&&fp===state.lastFingerprint)return;state.lastFingerprint=fp;const m=L.model(world,year),a=m.analysis,t=m.theme,met=a.metrics;panel.dataset.livingTheme=t.id;panel.classList.remove(...L.THEME_IDS.map(x=>`living-theme-${x}`));panel.classList.add(`living-theme-${t.id}`);$('#livingWikiHero').dataset.sigil=t.sigil;$('#livingWikiKicker').textContent=`LIVING WIKI · ${t.name.toUpperCase()} · AUTO THEME`;$('#livingWikiName').textContent=world.name;$('#livingWikiEra').textContent=`${t.era} · Year ${fmt(a.year)}`;$('#livingWikiMotto').textContent=t.motto;$('#livingWikiNarrative').textContent=m.narrative+` Preferred shelves: ${shelves(m)}.`;$('#livingWikiPulse').innerHTML=[['REALMS',met.activeRealms],['WARS',met.activeWars],['STABILITY',Math.round(met.stability)],['PROSPERITY',`${Math.round(met.prosperity*100)}%`],['CRIME',Math.round(met.crime)],['ARCHIVES',met.archives]].map(([k,v])=>`<div><span>${k}</span><b>${esc(v)}</b></div>`).join('');$('#livingWikiFeatured').innerHTML=a.topEvents.slice(0,5).map(e=>`<div class="living-feature"><span>YEAR ${fmt(e.year)} · ${esc(String(e.type||'event').replaceAll('_',' '))}</span><b>${esc(e.title)}</b><p>${esc(e.text).slice(0,150)}</p></div>`).join('')||`<div class="living-feature"><span>FOUNDING RECORD</span><b>The archive is quiet</b><p>No major recent event has yet displaced the founding chronicle.</p></div>`;reorderTypes(t.order);document.title=`${world.name} · ${t.era} · WorldForge v1.2`;const pill=$('.version-pill');if(pill)pill.textContent='v1.2 · LIVING WIKI';const foot=document.querySelector('footer span');if(foot)foot.textContent='WorldForge v1.2 · Living Wiki'}
function reorderTypes(order){const s=$('#wikiType');if(!s)return;const current=s.value,opts=[...s.options],all=opts.find(o=>o.value==='all'),map=new Map(opts.map(o=>[o.value,o]));s.innerHTML='';if(all)s.appendChild(all);for(const t of order){const o=map.get(t);if(o){s.appendChild(o);map.delete(t)}}for(const o of opts)if(o.value!=='all'&&map.has(o.value)){s.appendChild(o);map.delete(o.value)}if([...s.options].some(o=>o.value===current))s.value=current}
function exportHtml(){const world=currentWorld();if(!world)return;const m=L.model(world,currentViewYear()),html=L.exportHTML(world,currentViewYear()),blob=new Blob([html],{type:'text/html;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${String(world.name||'world').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()}-${m.theme.id}-living-wiki.html`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}
const proto=window.WorldRenderer.prototype,oldSet=proto.setWorld,oldHist=proto.setHistoryView;proto.setWorld=function(world){state.world=world;state.viewYear=null;state.lastFingerprint=null;const r=oldSet.call(this,world);setTimeout(()=>render(true),0);return r};proto.setHistoryView=function(v){const r=oldHist.call(this,v);if(this.world){state.world=this.world;state.viewYear=v?.isPresent?null:(v?.year??null);state.lastFingerprint=null;setTimeout(()=>render(true),0)}return r};
setInterval(()=>render(false),1400);setTimeout(()=>render(true),60);
window.WorldForgeLivingWikiUI={version:'1.2.0',state,render,exportHtml};
})();