(function(root,factory){
  const api=factory(root&&root.WorldForgeHousing,root&&root.WorldForgeHouseholds,root&&root.WorldForgeWorkforce,root&&root.WorldForgeInstitutions,root&&root.WorldForgeTreasury,root&&root.WorldForgeCity);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeMunicipal=api;
})(typeof window!=='undefined'?window:globalThis,function(Housing,Households,Workforce,Institutions,Treasury,City){
'use strict';
if(!Housing||!Households||!Workforce)throw new Error('WorldForge v2.5 requires Housing, Households and Workforce');
const VERSION='2.5.0',SCHEMA=1,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
const SERVICES=[
 {id:'water',name:'Water Supply',weight:1.18,depreciation:.012},
 {id:'sanitation',name:'Sanitation & Sewerage',weight:1.2,depreciation:.014},
 {id:'roads',name:'Roads & Streets',weight:1.12,depreciation:.018},
 {id:'waste',name:'Waste Collection',weight:.82,depreciation:.014},
 {id:'fire',name:'Fire Protection',weight:.78,depreciation:.01},
 {id:'education',name:'Schools & Education',weight:1.03,depreciation:.008},
 {id:'healthcare',name:'Clinics & Public Health',weight:1.08,depreciation:.009},
 {id:'transit',name:'Public Transport',weight:.68,depreciation:.016},
 {id:'lighting',name:'Street Lighting',weight:.58,depreciation:.015}
];
const SERVICE_MAP=new Map(SERVICES.map(x=>[x.id,x])),runtime=new WeakMap(),perf=new WeakMap();
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function absYear(w){return Workforce.absYear(w)}
function state(w){if(!w.municipal||w.municipal.schemaVersion!==SCHEMA)w.municipal={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:absYear(w),profiles:[],annual:[],archives:[],revision:0,lastAppliedYear:null,settings:{retainDetailedYears:1000,maxDistrictRows:2600,propertyTaxRate:.018},stats:{revenue:0,spending:0,realmGrants:0,backlog:0,meanCoverage:0,meanInequality:0,meanHealthRisk:0,meanFireRisk:0,archivedYears:0}};const S=w.municipal;S.engineVersion=VERSION;S.profiles=S.profiles||[];S.annual=S.annual||[];S.archives=S.archives||[];S.revision=Number(S.revision||0);S.settings={retainDetailedYears:1000,maxDistrictRows:2600,propertyTaxRate:.018,...S.settings};S.stats={revenue:0,spending:0,realmGrants:0,backlog:0,meanCoverage:0,meanInequality:0,meanHealthRisk:0,meanFireRisk:0,archivedYears:0,...S.stats};return S}
function owner(w,sid){return w.history?.current?.settlementKingdomIds?.[sid]??w.settlements?.[sid]?.kingdomId??null}
function buildRuntime(w,force=false){const S=state(w),year=absYear(w),housing=w.housing?.profiles||[],households=w.households?.profiles||[],markets=w.workforce?.markets||[],cities=w.cities?.cities||[],facilities=w.institutions?.facilities||[],treasury=w.treasury?.realms||[],technology=w.technology?.realms||[],sig=`${year}|${housing.length}|${households.length}|${markets.length}|${cities.length}|${facilities.length}|${treasury.length}|${technology.length}|${S.profiles.length}`;let r=runtime.get(w);if(!force&&r&&r.signature===sig)return r;const by=(a,key)=>new Map(a.map(x=>[Number(key(x)),x])),housingBy=by(housing,x=>x.settlementId),householdBy=by(households,x=>x.settlementId),marketBy=by(markets,x=>x.settlementId),cityBy=by(cities,x=>x.settlementId??x.id),treasuryBy=by(treasury,x=>x.realmId),techByRealm=by(technology,x=>x.realmId),profileBy=by(S.profiles,x=>x.settlementId),facilityCounts=new Map();for(const f of facilities){if(f.status!=='active')continue;const sid=Number(f.settlementId);let m=facilityCounts.get(sid);if(!m){m=new Map;facilityCounts.set(sid,m)}m.set(f.typeId,(m.get(f.typeId)||0)+1)}r={signature:sig,housingBy,householdBy,marketBy,cityBy,treasuryBy,techByRealm,profileBy,facilityCounts};runtime.set(w,r);const p=perf.get(w)||{cacheBuilds:0,profileHits:0,reads:0};p.cacheBuilds++;perf.set(w,p);return r}
function blank(sid){return{settlementId:Number(sid),lastYear:null,budget:{propertyTax:0,fees:0,realmGrant:0,revenue:0,spending:0,balance:0,reserve:0},serviceStock:{},coverage:{},demand:{},maintenanceBacklog:0,serviceIndex:0,inequality:0,healthRisk:0,fireRisk:0,educationAccess:0,utilityReliability:0,publicWorksCapacity:0,districts:[]}}
function profileState(w,sid){sid=Number(sid);const S=state(w),r=buildRuntime(w);let p=r.profileBy.get(sid);if(!p){p=blank(sid);S.profiles.push(p);r.profileBy.set(sid,p)}const m=perf.get(w)||{cacheBuilds:0,profileHits:0,reads:0};m.profileHits++;perf.set(w,m);return p}
function syncProfiles(w){const S=state(w),valid=new Set((w.settlements||[]).map(x=>Number(x.id))),by=new Map(S.profiles.map(x=>[Number(x.settlementId),x]));for(const sid of valid)if(!by.has(sid))S.profiles.push(blank(sid));S.profiles=S.profiles.filter(p=>valid.has(Number(p.settlementId)));runtime.delete(w);buildRuntime(w,true);return S}
function countFacility(w,sid,type){return buildRuntime(w).facilityCounts.get(Number(sid))?.get(type)||0}
function sectorWorkers(m,name){return Number(m?.sectors?.[name]?.workers||0)}
function techIndex(w,sid){const rid=owner(w,sid),r=buildRuntime(w).techByRealm.get(Number(rid));if(!r)return .22;const known=Object.values(r.known||{});if(!known.length)return .22;const adoption=known.reduce((n,x)=>n+Number(x?.adoption||0),0)/known.length;return clamp(.18+Math.log2(known.length+1)*.08+adoption*.48,.15,1)}
function demandFor(w,sid,hp,hh,m,c){const pop=Math.max(20,Number(m?.population||hh?.households*4||100)),density=Number(hp?.densityIndex||.5),crowd=Number(hp?.overcrowdingRate||0),urban=['Capital','City','Town'].includes(c?.type||w.settlements?.[sid]?.type),children=Math.max(0,Number(m?.children||pop*.22)),elders=Math.max(0,Number(m?.elders||pop*.08)),scale=Math.sqrt(pop)/12;return{
 water:scale*(1+density*.3+crowd*.35),sanitation:scale*(1+density*.55+crowd*.55),roads:scale*(urban?1.2:.72)*(1+density*.25),waste:scale*(urban?1.15:.65)*(1+crowd*.45),fire:scale*(urban?1.1:.62)*(1+density*.45),education:Math.sqrt(children+1)/4.2,healthcare:scale*.72+Math.sqrt(elders+1)/5,transit:scale*(urban?.9:.22)*(1+density*.52),lighting:scale*(urban?.78:.18)*(1+density*.35)} }
function capacityInputs(w,sid,m){const publicWorkers=sectorWorkers(m,'Public Service')+sectorWorkers(m,'Administration'),construction=sectorWorkers(m,'Construction'),engineering=sectorWorkers(m,'Engineering'),health=sectorWorkers(m,'Health'),education=sectorWorkers(m,'Education'),transport=sectorWorkers(m,'Transport')+sectorWorkers(m,'Logistics'),hospitals=countFacility(w,sid,'hospital'),universities=countFacility(w,sid,'university'),libraries=countFacility(w,sid,'library'),marketHalls=countFacility(w,sid,'market_hall'),tech=techIndex(w,sid);return{publicWorkers,construction,engineering,health,education,transport,hospitals,universities,libraries,marketHalls,tech}}
function baseCoverage(id,w,sid,hp,hh,m,c,x){const pros=Number(w.history?.current?.settlementProsperity?.[sid]??.45),urban=['Capital','City','Town'].includes(c?.type||w.settlements?.[sid]?.type),common=.14+pros*.34+x.tech*.2+Math.min(.16,(x.publicWorkers+x.engineering)/Math.max(80,Number(m?.laborForce||100))*2);if(id==='education')return clamp(common+x.universities*.1+x.libraries*.045+Math.min(.16,x.education/Math.max(50,m?.laborForce||100)*2),.08,.96);if(id==='healthcare')return clamp(common+x.hospitals*.13+Math.min(.18,x.health/Math.max(50,m?.laborForce||100)*2),.08,.97);if(id==='roads')return clamp(common+Math.min(.18,x.construction/Math.max(80,m?.laborForce||100)*1.6)+(urban?.06:0),.08,.96);if(id==='transit')return clamp(common*.62+Math.min(.2,x.transport/Math.max(80,m?.laborForce||100)*1.8)+(urban?.08:0),.03,.9);if(id==='lighting')return clamp(common*.56+x.tech*.2+(urban?.07:0),.02,.92);if(id==='fire')return clamp(common*.74+x.marketHalls*.025,.05,.94);return clamp(common+(urban?.03:0)-Number(hp?.slumShare||0)*.12,.06,.96)}
function municipalBudget(w,sid,hp,hh,m,p){const rid=owner(w,sid),a=buildRuntime(w).treasuryBy.get(Number(rid)),pros=Number(w.history?.current?.settlementProsperity?.[sid]??.45),propertyTax=Math.max(0,Number(hp?.propertyTaxBase||0))*state(w).settings.propertyTaxRate*.012,fees=Math.max(.05,Number(m?.population||0)*pros*.000022),desiredGrant=Math.max(0,Number(m?.population||0)*.000012+Number(hp?.dwellings||0)*.000016),realmGrant=a?Math.min(desiredGrant,Math.max(0,Number(a.treasury||0))*.012):0,revenue=propertyTax+fees+realmGrant,reserve=Math.max(0,Number(p.budget?.reserve||0)),available=revenue+reserve*.08,spending=available*.88,balance=revenue-spending;return{propertyTax:round(propertyTax,3),fees:round(fees,3),realmGrant:round(realmGrant,3),revenue:round(revenue,3),spending:round(spending,3),balance:round(balance,3),reserve:round(Math.max(0,reserve+balance),3),account:a}}
function districtRows(w,sid,p,hp,c){const rows=hp?.districts||[],cityDistricts=c?.districts||[],wealthBy=new Map(cityDistricts.map(d=>[String(d.id),Number(d.wealth??.45)]));if(!rows.length)return[];return rows.map(d=>{const wealth=wealthBy.get(String(d.districtId))??.45,low=['Slums','Low Quarter','Outskirts'].includes(String(d.kind||'')),high=['Wealthy Quarter','Government','Old Town'].includes(String(d.kind||'')),bias=clamp(.78+wealth*.34+(high?.08:0)-(low?.13:0),.55,1.18),coverage={};for(const s of SERVICES)coverage[s.id]=round(clamp(Number(p.coverage[s.id]||0)*bias-(Number(d.overcrowdingRate||0)*.08),0,1),4);const vals=Object.values(coverage),serviceIndex=vals.reduce((a,b)=>a+b,0)/Math.max(1,vals.length);return{districtId:d.districtId,name:d.name,kind:d.kind,serviceIndex:round(serviceIndex,4),coverage,inequalityGap:round(Math.max(0,p.serviceIndex-serviceIndex),4),healthRisk:round(clamp((1-coverage.water)*.22+(1-coverage.sanitation)*.34+(1-coverage.healthcare)*.24+Number(d.overcrowdingRate||0)*.2,0,1),4),fireRisk:round(clamp((1-coverage.fire)*.38+(1-coverage.water)*.18+(1-coverage.roads)*.16+Number(d.densityIndex||0)*.08,0,1),4)}})}
function simulateMunicipalYear(w,year=absYear(w)){const S=initialize(w);if(S.lastAppliedYear===year&&S.profiles.every(p=>p.lastYear===year))return S;buildRuntime(w,true);let revenue=0,spending=0,grants=0,backlog=0,coverageTotal=0,ineqTotal=0,healthTotal=0,fireTotal=0,weight=0;for(const m of w.workforce?.markets||[]){const sid=Number(m.settlementId),r=buildRuntime(w),hp=r.housingBy.get(sid),hh=r.householdBy.get(sid),c=r.cityBy.get(sid),p=profileState(w,sid);if(!hp||!hh||hp.lastYear==null)continue;const d=demandFor(w,sid,hp,hh,m,c),x=capacityInputs(w,sid,m),b=municipalBudget(w,sid,hp,hh,m,p),totalWeight=SERVICES.reduce((n,s)=>n+s.weight*(d[s.id]||1),0),stock={...p.serviceStock},cov={};for(const s of SERVICES){const demand=Math.max(.05,d[s.id]||.05),initial=stock[s.id]==null?demand*baseCoverage(s.id,w,sid,hp,hh,m,c,x):Number(stock[s.id]),investment=b.spending*(s.weight*demand/Math.max(.01,totalWeight)),eff=.68+x.tech*.34+Math.min(.22,(x.publicWorkers+x.engineering)/Math.max(100,m.laborForce||100)*2),next=Math.max(0,initial*(1-s.depreciation)+investment*eff*.42);stock[s.id]=round(next,4);cov[s.id]=round(clamp(next/demand,0,1),4)}p.serviceStock=stock;p.coverage=cov;p.demand=Object.fromEntries(Object.entries(d).map(([k,v])=>[k,round(v,4)]));p.budget={propertyTax:b.propertyTax,fees:b.fees,realmGrant:b.realmGrant,revenue:b.revenue,spending:b.spending,balance:b.balance,reserve:b.reserve};if(b.account&&b.realmGrant>0)b.account.treasury=round(Math.max(0,Number(b.account.treasury||0)-b.realmGrant),2);const vals=SERVICES.map(s=>cov[s.id]),serviceIndex=vals.reduce((a,b)=>a+b,0)/vals.length,maintenance=SERVICES.reduce((n,s)=>n+Math.max(0,(d[s.id]||0)-(stock[s.id]||0)),0),healthRisk=clamp((1-cov.water)*.2+(1-cov.sanitation)*.3+(1-cov.waste)*.12+(1-cov.healthcare)*.25+Number(hp.overcrowdingRate||0)*.13,0,1),fireRisk=clamp((1-cov.fire)*.38+(1-cov.water)*.16+(1-cov.roads)*.18+Number(hp.densityIndex||0)*.08+Number(hp.slumShare||0)*.2,0,1);p.maintenanceBacklog=round(maintenance,3);p.serviceIndex=round(serviceIndex,4);p.healthRisk=round(healthRisk,4);p.fireRisk=round(fireRisk,4);p.educationAccess=cov.education;p.utilityReliability=round((cov.water+cov.sanitation+cov.waste+cov.lighting)/4,4);p.publicWorksCapacity=round(clamp(.25+x.tech*.28+Math.min(.35,(x.construction+x.engineering+x.publicWorkers)/Math.max(100,m.laborForce||100)*2),0,1),4);p.districts=districtRows(w,sid,p,hp,c);const districtValues=p.districts.map(q=>q.serviceIndex),mean=districtValues.length?districtValues.reduce((a,b)=>a+b,0)/districtValues.length:serviceIndex;p.inequality=round(districtValues.length?districtValues.reduce((n,v)=>n+Math.abs(v-mean),0)/districtValues.length:0,4);p.lastYear=year;
 const serviceLift=(serviceIndex-.5);hh.lifeExpectancy=round(clamp(Number(hh.lifeExpectancy||45)+serviceLift*.65-healthRisk*.18,25,85),1);hh.deathRate=round(clamp(Number(hh.deathRate||.012)*(1+healthRisk*.012-serviceLift*.01),.004,.08),5);hh.educationIndex=round(clamp(Number(hh.educationIndex||.3)+(cov.education-.5)*.006,.05,1),4);hh.literacyRate=round(clamp(Number(hh.literacyRate||.3)+(cov.education-.5)*.004,.05,1),4);hp.propertyIndex=round(clamp(Number(hp.propertyIndex||1)*(1+serviceLift*.003),.35,5),4);hp.developmentIndex=round(clamp(Number(hp.developmentIndex||.3)+Math.max(-.004,serviceLift*.005),.05,1.4),4);hp.slumShare=round(clamp(Number(hp.slumShare||0)+Math.max(0,.45-serviceIndex)*.004-Math.max(0,serviceIndex-.68)*.002,0,.6),4);m.migrationPressure=round(clamp(Number(m.migrationPressure||0)-serviceLift*.012+p.inequality*.008,-.4,2),4);if(c){c.serviceIndex=p.serviceIndex;c.infrastructureBacklog=p.maintenanceBacklog;c.healthRisk=p.healthRisk;c.fireRisk=p.fireRisk;c.crimeRate=round(clamp(Number(c.crimeRate||0)-Math.max(0,cov.lighting-.5)*.35+Math.max(0,.4-cov.waste)*.2,0,100),2)}
 const q=Math.max(1,Number(hh.households||1));revenue+=b.revenue;spending+=b.spending;grants+=b.realmGrant;backlog+=p.maintenanceBacklog;coverageTotal+=p.serviceIndex*q;ineqTotal+=p.inequality*q;healthTotal+=p.healthRisk*q;fireTotal+=p.fireRisk*q;weight+=q}
 S.currentYear=year;S.lastAppliedYear=year;S.revision++;S.stats={...S.stats,revenue:round(revenue,2),spending:round(spending,2),realmGrants:round(grants,2),backlog:round(backlog,2),meanCoverage:round(coverageTotal/Math.max(1,weight),4),meanInequality:round(ineqTotal/Math.max(1,weight),4),meanHealthRisk:round(healthTotal/Math.max(1,weight),4),meanFireRisk:round(fireTotal/Math.max(1,weight),4)};const row={year,...S.stats},i=S.annual.findIndex(x=>x.year===year);if(i>=0)S.annual[i]=row;else S.annual.push(row);maintenance(w);return S}
function settlementView(w,sid){sid=Number(sid);const p=profileState(w,sid),h=Housing.settlementView(w,sid),hh=Households.settlementView(w,sid);if(!h||!hh)return null;return{...p,name:h.name,type:h.type,population:h.population,households:h.households,povertyRate:hh.povertyRate,overcrowdingRate:h.overcrowdingRate,slumShare:h.slumShare,services:SERVICES.map(s=>({...s,coverage:p.coverage?.[s.id]||0,demand:p.demand?.[s.id]||0,stock:p.serviceStock?.[s.id]||0}))}}
function summary(w){const S=initialize(w);return{year:absYear(w),settlements:S.profiles.length,revision:S.revision,...S.stats}}
function maintenance(w){const S=state(w),cut=absYear(w)-S.settings.retainDetailedYears;if(cut<=0)return S;const old=S.annual.filter(x=>x.year<cut);if(!old.length)return S;const buckets=new Map;for(const r of old){const start=Math.floor(r.year/250)*250,b=buckets.get(start)||{startYear:start,endYear:start+249,years:0,revenue:0,spending:0,meanCoverage:0,meanInequality:0,meanHealthRisk:0};b.years++;b.revenue+=Number(r.revenue||0);b.spending+=Number(r.spending||0);b.meanCoverage+=Number(r.meanCoverage||0);b.meanInequality+=Number(r.meanInequality||0);b.meanHealthRisk+=Number(r.meanHealthRisk||0);buckets.set(start,b)}for(const b of buckets.values()){b.revenue=round(b.revenue/b.years,2);b.spending=round(b.spending/b.years,2);b.meanCoverage=round(b.meanCoverage/b.years,4);b.meanInequality=round(b.meanInequality/b.years,4);b.meanHealthRisk=round(b.meanHealthRisk/b.years,4);const ex=S.archives.find(x=>x.startYear===b.startYear);if(ex)Object.assign(ex,b);else S.archives.push(b)}S.annual=S.annual.filter(x=>x.year>=cut);S.stats.archivedYears+=old.length;return S}
function fingerprint(w){const S=initialize(w),s=JSON.stringify({year:S.currentYear,profiles:S.profiles.map(p=>[p.settlementId,p.serviceIndex,p.maintenanceBacklog,p.inequality,p.healthRisk,p.fireRisk,p.budget,Object.entries(p.coverage||{}),Object.entries(p.serviceStock||{})]),annual:S.annual.slice(-80),stats:S.stats});return hash(s).toString(16).padStart(8,'0')}
function validate(w){const S=initialize(w),e=[];if(S.profiles.length!==(w.settlements?.length||0))e.push('municipal profile coverage');for(const p of S.profiles){if(p.lastYear==null)continue;for(const s of SERVICES){const c=Number(p.coverage?.[s.id]);if(!Number.isFinite(c)||c<0||c>1)e.push(`service coverage ${p.settlementId}:${s.id}`)}if(p.serviceIndex<0||p.serviceIndex>1)e.push(`service index ${p.settlementId}`);if(p.maintenanceBacklog<0||p.healthRisk<0||p.fireRisk<0)e.push(`municipal accounting ${p.settlementId}`)}return[...new Set(e)]}
function performance(w){const r=buildRuntime(w),p=perf.get(w)||{cacheBuilds:0,profileHits:0,reads:0};p.reads++;perf.set(w,p);return{...p,indexedHousing:r.housingBy.size,indexedHouseholds:r.householdBy.size,indexedMarkets:r.marketBy.size,indexedCities:r.cityBy.size,indexedTechnology:r.techByRealm.size,indexedProfiles:r.profileBy.size}}
function initialize(w){if(!w)throw new Error('World required');if(!w.housing)Housing.initialize(w);if(!w.households)Households.initialize(w);if(!w.workforce)Workforce.initialize(w);if(!w.institutions)Institutions?.initialize?.(w);if(!w.treasury)Treasury?.initialize?.(w);const S=state(w),settlements=w.settlements||[];if(S.profiles.length===settlements.length){const valid=new Set(settlements.map(x=>Number(x.id)));if(S.profiles.every(p=>valid.has(Number(p.settlementId)))){buildRuntime(w);return S}}return syncProfiles(w)}
function installBridge(){if(Workforce.__municipalBridge)return;Workforce.__municipalBridge=true;const rawYear=Workforce.simulateWorkforceYear.bind(Workforce),rawYears=Workforce.simulateYears.bind(Workforce);Workforce.simulateWorkforceYear=function(w,year=Workforce.absYear(w)){const out=rawYear(w,year);simulateMunicipalYear(w,year);return out};Workforce.simulateYears=function(w,years,options={}){const n=Math.max(0,Math.floor(Number(years)||0));for(let i=0;i<n;i++){rawYears(w,1,options);simulateMunicipalYear(w,absYear(w))}return w.workforce};Workforce.simulateTo=function(w,target,options={}){const t=Math.floor(Number(target)||0),now=absYear(w);if(t<now)throw new Error('Municipal-enabled simulation cannot run backward');return Workforce.simulateYears(w,t-now,options)}}
installBridge();const api={VERSION,SCHEMA,SERVICES,SERVICE_MAP,initialize,absYear,simulateMunicipalYear,settlementView,summary,fingerprint,validate,profileState,performance,installBridge};return api;
});