(function(root,factory){
  const api=factory(root&&root.WorldForgeResources,root&&root.WorldForgeHouseholds,root&&root.WorldForgeMilitary,root&&root.WorldForgeMunicipal,root&&root.WorldForgeEmergency,root&&root.WorldForgeWorkforce);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeNutrition=api;
})(typeof window!=='undefined'?window:globalThis,function(Resources,Households,Military,Municipal,Emergency,Workforce){
'use strict';
if(!Resources||!Households||!Municipal||!Emergency||!Workforce)throw new Error('WorldForge v2.7 requires Resources, Households, Municipal, Emergency and Workforce');
const VERSION='2.7.0',SCHEMA=1,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
const STAGES=[
 {id:0,name:'Secure',min:.78},{id:1,name:'Stressed',min:.65},{id:2,name:'Crisis',min:.50},{id:3,name:'Emergency',min:.36},{id:4,name:'Famine',min:.22},{id:5,name:'Catastrophe',min:0}
];
const runtime=new WeakMap(),perf=new WeakMap();
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function absYear(w){return Workforce.absYear(w)}
function owner(w,sid){return w.history?.current?.settlementKingdomIds?.[sid]??w.settlements?.[sid]?.kingdomId??null}
function state(w){if(!w.nutrition||w.nutrition.schemaVersion!==SCHEMA)w.nutrition={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:absYear(w),profiles:[],incidents:[],convoys:[],annual:[],archives:[],revision:0,lastAppliedYear:null,settings:{retainDetailedYears:1000,maxIncidents:700,maxConvoys:900,historyThreshold:4,reliefIntensity:1},stats:{crisisSettlements:0,famineSettlements:0,malnourished:0,severelyMalnourished:0,nutritionDeaths:0,reliefDelivered:0,reliefSpending:0,refugeeCampPopulation:0,meanNutrition:0,archivedYears:0}};const S=w.nutrition;S.engineVersion=VERSION;S.profiles=S.profiles||[];S.incidents=S.incidents||[];S.convoys=S.convoys||[];S.annual=S.annual||[];S.archives=S.archives||[];S.revision=Number(S.revision||0);S.settings={retainDetailedYears:1000,maxIncidents:700,maxConvoys:900,historyThreshold:4,reliefIntensity:1,...S.settings};S.stats={crisisSettlements:0,famineSettlements:0,malnourished:0,severelyMalnourished:0,nutritionDeaths:0,reliefDelivered:0,reliefSpending:0,refugeeCampPopulation:0,meanNutrition:0,archivedYears:0,...S.stats};return S}
function blank(sid){return{settlementId:Number(sid),lastYear:null,nutritionIndex:1,foodAccess:1,affordability:1,dietDiversity:1,malnutritionRate:0,severeMalnutritionRate:0,famineStage:0,famineStageName:'Secure',rationing:false,reliefNeeded:0,reliefReceived:0,reliefShortfall:0,reliefSpending:0,nutritionDeaths:0,refugeeCampPopulation:0,displacedThisYear:0,pressures:{siege:0,blockade:0,poverty:0,price:0,disease:0},basket:{priceIndex:1,foodSecurity:1,foodDays:365,stockEquivalent:0,availableFoods:0}}}
function buildRuntime(w,force=false){const S=state(w),year=absYear(w),markets=w.resources?.markets||[],households=w.households?.profiles||[],municipal=w.municipal?.profiles||[],emergency=w.emergency?.profiles||[],workforce=w.workforce?.markets||[],treasury=w.treasury?.realms||[],sieges=w.military?.sieges||[],blockades=w.military?.blockades||[],sig=`${year}|${w.resources?.currentYear||0}|${w.households?.revision||0}|${w.municipal?.revision||0}|${w.emergency?.revision||0}|${w.workforce?.revision||0}|${markets.length}|${households.length}|${municipal.length}|${emergency.length}|${treasury.length}|${sieges.length}|${blockades.length}|${S.profiles.length}`;let r=runtime.get(w);if(!force&&r&&r.signature===sig)return r;const by=(a,key)=>new Map(a.map(x=>[Number(key(x)),x])),resourceBy=by(markets,x=>x.settlementId),householdBy=by(households,x=>x.settlementId),municipalBy=by(municipal,x=>x.settlementId),emergencyBy=by(emergency,x=>x.settlementId),workforceBy=by(workforce,x=>x.settlementId),treasuryBy=by(treasury,x=>x.realmId),profileBy=by(S.profiles,x=>x.settlementId),sieged=new Set(),blockaded=new Set();for(const x of sieges)if(x.status==='active'||x.status==null)sieged.add(Number(x.settlementId));for(const x of blockades)if(x.status==='active'||x.status==null)blockaded.add(Number(x.settlementId));r={signature:sig,resourceBy,householdBy,municipalBy,emergencyBy,workforceBy,treasuryBy,profileBy,sieged,blockaded};runtime.set(w,r);const p=perf.get(w)||{cacheBuilds:0,reads:0,profileHits:0,donorSearches:0};p.cacheBuilds++;perf.set(w,p);return r}
function syncProfiles(w){const S=state(w),valid=new Set((w.settlements||[]).map(x=>Number(x.id))),by=new Map(S.profiles.map(x=>[Number(x.settlementId),x]));for(const sid of valid)if(!by.has(sid))S.profiles.push(blank(sid));S.profiles=S.profiles.filter(p=>valid.has(Number(p.settlementId)));runtime.delete(w);buildRuntime(w,true);return S}
function profileState(w,sid){sid=Number(sid);const S=state(w),r=buildRuntime(w);let p=r.profileBy.get(sid);if(!p){p=blank(sid);S.profiles.push(p);r.profileBy.set(sid,p)}const q=perf.get(w)||{cacheBuilds:0,reads:0,profileHits:0,donorSearches:0};q.profileHits++;perf.set(w,q);return p}
function foodBasket(m){let weightedPrice=0,weight=0,stock=0,available=0,shortage=0;for(const id of Resources.FOOD_IDS||[]){const c=Resources.MAP.get(id);if(!c)continue;const f=Math.max(.05,Number(c.food||0)),base=Math.max(.01,Number(c.basePrice||1)),price=Math.max(.01,Number(m?.prices?.[id]??base)),inv=Math.max(0,Number(m?.inventory?.[id]||0));weightedPrice+=(price/base)*f;weight+=f;stock+=inv*f;if(inv>.03)available++;shortage+=Number(m?.shortages?.[id]||0)*f}const priceIndex=weight?weightedPrice/weight:1,meanShortage=weight?shortage/weight:0,foodSecurity=clamp(Number(m?.foodSecurity??(1-meanShortage)),.02,1.5),foodDays=clamp(Number(m?.foodDays??foodSecurity*365),0,730),diversity=clamp(available/Math.max(1,(Resources.FOOD_IDS||[]).length),0,1);return{priceIndex,stockEquivalent:stock,foodSecurity,foodDays,dietDiversity:diversity,meanShortage}}
function stageFor(n){for(const s of STAGES)if(n>=s.min)return s;return STAGES.at(-1)}
function conditions(w,sid){sid=Number(sid);const r=buildRuntime(w),m=r.resourceBy.get(sid),hh=r.householdBy.get(sid),mu=r.municipalBy.get(sid),em=r.emergencyBy.get(sid),wf=r.workforceBy.get(sid);if(!m||!hh||!mu||!em||!wf)return null;const b=foodBasket(m),poverty=clamp(Number(hh.povertyRate||0),0,1),income=Math.max(.05,Number(hh.meanIncome||.2)),disposable=Number(hh.disposableIncome||0),pricePressure=clamp((b.priceIndex-1)/3.5,0,1),affordability=clamp(1-pricePressure*.54-poverty*.32-Math.max(0,-disposable)/(income+1)*.18,.04,1),siege=r.sieged.has(sid)?1:0,blockade=r.blockaded.has(sid)?1:0,logisticsPenalty=clamp(siege*.28+blockade*.2,0,.42),foodAccess=clamp(b.foodSecurity*.55+affordability*.27+b.dietDiversity*.18-logisticsPenalty,.02,1),diseasePressure=clamp(Number(em.disease?.severity||0)*.5+Number(em.hazards?.disease||0)*.22,0,1),healthBuffer=clamp(Number(mu.coverage?.healthcare||0)*.45+Number(mu.coverage?.water||0)*.22+Number(mu.coverage?.sanitation||0)*.18+Number(hh.educationIndex||0)*.15,0,1),nutrition=clamp(foodAccess*.64+b.dietDiversity*.16+affordability*.12+healthBuffer*.08-diseasePressure*.08,.02,1),malnutrition=clamp((.74-nutrition)*1.35+poverty*.11+diseasePressure*.08+logisticsPenalty*.16,0,.92),severe=clamp((.49-nutrition)*1.25+Math.max(0,malnutrition-.35)*.44+logisticsPenalty*.1,0,.68),stage=stageFor(nutrition);return{m,hh,mu,em,wf,b,poverty,pricePressure,affordability,siege,blockade,diseasePressure,healthBuffer,foodAccess,nutrition,malnutrition,severe,stage}}
function foodEquivalent(m){return foodBasket(m).stockEquivalent}
function takeFood(m,amount){let remain=Math.max(0,amount),taken=0;const ids=(Resources.FOOD_IDS||[]).slice().sort((a,b)=>Number(m.inventory?.[b]||0)*(Resources.MAP.get(b)?.food||0)-Number(m.inventory?.[a]||0)*(Resources.MAP.get(a)?.food||0));for(const id of ids){if(remain<=.0001)break;const c=Resources.MAP.get(id),f=Math.max(.05,Number(c?.food||0)),inv=Math.max(0,Number(m.inventory?.[id]||0)),eq=inv*f,use=Math.min(eq,remain),qty=use/f;if(qty>0){m.inventory[id]=round(Math.max(0,inv-qty),4);taken+=use;remain-=use}}return taken}
function addFood(m,amount){let remain=Math.max(0,amount),added=0;const ids=(Resources.FOOD_IDS||[]).slice().sort((a,b)=>(Resources.MAP.get(b)?.food||0)-(Resources.MAP.get(a)?.food||0));if(!ids.length)return 0;for(let i=0;i<ids.length&&remain>.0001;i++){const id=ids[i],c=Resources.MAP.get(id),f=Math.max(.05,Number(c?.food||0)),share=i===ids.length-1?remain:remain/(ids.length-i),qty=share/f;m.inventory[id]=round(Math.max(0,Number(m.inventory?.[id]||0))+qty,4);added+=share;remain-=share}return added}
function chooseDonor(w,sid,need){const r=buildRuntime(w),rid=owner(w,sid),q=perf.get(w)||{cacheBuilds:0,reads:0,profileHits:0,donorSearches:0};q.donorSearches++;perf.set(w,q);let best=null;for(const [id,m] of r.resourceBy){if(id===sid)continue;const same=owner(w,id)===rid,b=foodBasket(m),reserve=Math.max(.12,Number(r.workforceBy.get(id)?.population||100)*.0026),surplus=Math.max(0,b.stockEquivalent-reserve);if(surplus<=.05||b.foodSecurity<.72)continue;const score=surplus*(same?1.35:1)*(1+Math.max(0,b.foodSecurity-.8));if(!best||score>best.score)best={sid:id,m,surplus,score,same}}return best&&Math.min(need,best.surplus)>0?best:null}
function chargeRelief(w,sid,cost,c){let remaining=Math.max(0,cost),local=0,realm=0;const reserve=Math.max(0,Number(c.mu.budget?.reserve||0));local=Math.min(reserve,remaining*.35);if(local>0){c.mu.budget.reserve=round(reserve-local,3);remaining-=local}const account=buildRuntime(w).treasuryBy.get(Number(owner(w,sid)));if(account&&remaining>0){realm=Math.min(remaining,Math.max(0,Number(account.treasury||0))*.018);account.treasury=round(Math.max(0,Number(account.treasury||0)-realm),2);remaining-=realm}return{spent:round(local+realm,3),local:round(local,3),realm:round(realm,3),unfunded:round(remaining,3)}}
function deliverRelief(w,sid,need,c,year){if(need<=.02)return{requested:0,loaded:0,delivered:0,spent:0,shortfall:0,donor:null};const donor=chooseDonor(w,sid,need*1.25);if(!donor)return{requested:round(need,3),loaded:0,delivered:0,spent:0,shortfall:round(need,3),donor:null};const loaded=takeFood(donor.m,Math.min(need*1.15,donor.surplus)),routeFactor=clamp(1-c.siege*.5-c.blockade*.38,.18,1),delivered=loaded*routeFactor,loss=loaded-delivered;addFood(c.m,delivered);const price=Math.max(.5,c.b.priceIndex),cost=delivered*price*.055+loss*.018,funding=chargeRelief(w,sid,cost,c),convoy={id:`relief:${year}:${donor.sid}:${sid}`,year,from:donor.sid,to:sid,requested:round(need,3),loaded:round(loaded,3),delivered:round(delivered,3),loss:round(loss,3),routeFactor:round(routeFactor,3),spending:funding.spent,unfunded:funding.unfunded,sameRealm:donor.same};const S=state(w);if(!S.convoys.some(x=>x.id===convoy.id))S.convoys.push(convoy);return{requested:need,loaded,delivered,spent:funding.spent,shortfall:Math.max(0,need-delivered),donor:donor.sid,convoy}}
function recordHistory(w,p,incident){if(p.famineStage<state(w).settings.historyThreshold||!w.history?.events)return;const sid=p.settlementId,exists=w.history.events.some(e=>(e.absoluteYear??e.year)===incident.year&&e.type==='famine'&&(e.settlementIds||[]).includes(sid));if(exists)return;const name=w.settlements?.[sid]?.name||`Settlement ${sid}`,rid=owner(w,sid);w.history.events.push({id:w.history.events.length,year:w.history.currentYear,absoluteYear:incident.year,type:'famine',importance:p.famineStage>=5?3:2,realmIds:rid==null?[]:[rid],settlementIds:[sid],nutritionIncidentId:incident.id,title:`Famine in ${name}`,text:`${name} enters ${p.famineStageName.toLowerCase()} conditions. Malnutrition affects ${Math.round(p.malnutritionRate*100)}% of residents; authorities ${p.rationing?'impose rationing and ':''}organize humanitarian relief.`})}
function recordIncident(w,p,year){if(p.famineStage<2)return;const S=state(w),id=`nutrition:${year}:${p.settlementId}`;if(S.incidents.some(x=>x.id===id))return;const x={id,year,settlementId:p.settlementId,type:p.famineStage>=4?'famine_crisis':'food_crisis',stage:p.famineStage,stageName:p.famineStageName,nutritionIndex:p.nutritionIndex,malnutritionRate:p.malnutritionRate,severeMalnutritionRate:p.severeMalnutritionRate,nutritionDeaths:p.nutritionDeaths,reliefReceived:p.reliefReceived,reliefShortfall:p.reliefShortfall,refugeeCampPopulation:p.refugeeCampPopulation};S.incidents.push(x);if(S.incidents.length>S.settings.maxIncidents)S.incidents.splice(0,S.incidents.length-S.settings.maxIncidents);recordHistory(w,p,x)}
function simulateNutritionYear(w,year=absYear(w)){const S=initialize(w);if(S.lastAppliedYear===year&&S.profiles.every(p=>p.lastYear===year))return S;buildRuntime(w,true);let crisis=0,famine=0,mal=0,severe=0,deaths=0,delivered=0,spending=0,camps=0,nutTotal=0,weight=0;for(const wf of w.workforce?.markets||[]){const sid=Number(wf.settlementId),c=conditions(w,sid);if(!c)continue;const p=profileState(w,sid),pop=Math.max(20,Math.round(Number(w.history?.current?.settlementPopulation?.[sid]??wf.population??100))),rationing=c.stage.id>=2||Boolean(c.siege)||Boolean(c.blockade),need=Math.max(0,pop*.0032*Math.max(0,.72-c.nutrition)*(1+c.stage.id*.18))*state(w).settings.reliefIntensity,relief=c.stage.id>=2?deliverRelief(w,sid,need,c,year):{requested:need,delivered:0,spent:0,shortfall:need},reliefBoost=clamp(Number(relief.delivered||0)/Math.max(.1,need)*.16,0,.16),nutrition=clamp(c.nutrition+reliefBoost,.02,1),malnutrition=clamp(c.malnutrition-reliefBoost*.72,0,.92),severeMalnutrition=clamp(c.severe-reliefBoost*.48,0,.68),stage=stageFor(nutrition),mortalityPressure=Math.max(0,(3-stage.id)*0)+Math.max(0,stage.id-2),deathRate=stage.id>=3?clamp(.0012*mortalityPressure+severeMalnutrition*.012+c.diseasePressure*.003,0,.025):0,nutritionDeaths=Math.min(Math.max(0,pop-20),Math.round(pop*deathRate)),displaced=Math.round(pop*Math.max(0,stage.id-2)*.0018*(1-Math.min(1,Number(relief.delivered||0)/Math.max(.1,need)))),campPrev=Math.max(0,Number(p.refugeeCampPopulation||0)*.72),campPop=Math.round(campPrev+displaced);
 p.nutritionIndex=round(nutrition,4);p.foodAccess=round(c.foodAccess+reliefBoost*.6,4);p.affordability=round(c.affordability,4);p.dietDiversity=round(c.b.dietDiversity,4);p.malnutritionRate=round(malnutrition,4);p.severeMalnutritionRate=round(severeMalnutrition,4);p.famineStage=stage.id;p.famineStageName=stage.name;p.rationing=rationing;p.reliefNeeded=round(need,3);p.reliefReceived=round(Number(relief.delivered||0),3);p.reliefShortfall=round(Math.max(0,need-Number(relief.delivered||0)),3);p.reliefSpending=round(Number(relief.spent||0),3);p.nutritionDeaths=nutritionDeaths;p.displacedThisYear=displaced;p.refugeeCampPopulation=campPop;p.pressures={siege:c.siege,blockade:c.blockade,poverty:round(c.poverty,4),price:round(c.pricePressure,4),disease:round(c.diseasePressure,4)};p.basket={priceIndex:round(c.b.priceIndex,4),foodSecurity:round(c.b.foodSecurity,4),foodDays:round(c.b.foodDays,1),stockEquivalent:round(foodEquivalent(c.m),3),availableFoods:Math.round(c.b.dietDiversity*Math.max(1,(Resources.FOOD_IDS||[]).length))};p.lastYear=year;
 if(nutritionDeaths>0&&w.history?.current?.settlementPopulation){w.history.current.settlementPopulation[sid]=Math.max(20,Math.round(Number(w.history.current.settlementPopulation[sid]||pop)-nutritionDeaths));wf.population=w.history.current.settlementPopulation[sid]}
 if(w.history?.current?.settlementProsperity){const old=Number(w.history.current.settlementProsperity[sid]??.45),shock=Math.max(0,stage.id-1)*.004+severeMalnutrition*.012;w.history.current.settlementProsperity[sid]=round(clamp(old-shock,.05,.98),4)}
 wf.migrationPressure=round(clamp(Number(wf.migrationPressure||0)+Math.max(0,stage.id-1)*.022+campPop/Math.max(1,pop)*.08,-.4,2),4);c.em.nutritionRisk=round(clamp(malnutrition*.7+severeMalnutrition*.3+campPop/Math.max(1,pop)*.18,0,1),4);c.em.refugeeCampPopulation=campPop;c.mu.humanitarianPressure=round(clamp(Math.max(0,stage.id-1)/4+campPop/Math.max(1,pop),0,1.5),4);
 recordIncident(w,p,year);if(stage.id>=2)crisis++;if(stage.id>=4)famine++;mal+=Math.round(pop*malnutrition);severe+=Math.round(pop*severeMalnutrition);deaths+=nutritionDeaths;delivered+=Number(relief.delivered||0);spending+=Number(relief.spent||0);camps+=campPop;nutTotal+=nutrition*pop;weight+=pop}
 S.currentYear=year;S.lastAppliedYear=year;S.revision++;S.stats={...S.stats,crisisSettlements:crisis,famineSettlements:famine,malnourished:mal,severelyMalnourished:severe,nutritionDeaths:deaths,reliefDelivered:round(delivered,2),reliefSpending:round(spending,2),refugeeCampPopulation:camps,meanNutrition:round(nutTotal/Math.max(1,weight),4)};const row={year,...S.stats},i=S.annual.findIndex(x=>x.year===year);if(i>=0)S.annual[i]=row;else S.annual.push(row);maintenance(w);return S}
function settlementView(w,sid){sid=Number(sid);const p=profileState(w,sid),c=conditions(w,sid);if(!c)return null;return{...p,name:w.settlements?.[sid]?.name||`Settlement ${sid}`,type:w.settlements?.[sid]?.type||'Settlement',population:Number(w.history?.current?.settlementPopulation?.[sid]??c.wf.population??0),povertyRate:c.poverty,foodSecurity:Number(c.m.foodSecurity??p.basket.foodSecurity),healthRisk:Number(c.mu.healthRisk||0),activeDisease:Number(c.em.disease?.infected||0)}}
function summary(w){const S=initialize(w);return{year:absYear(w),settlements:S.profiles.length,revision:S.revision,...S.stats}}
function maintenance(w){const S=state(w),cut=absYear(w)-S.settings.retainDetailedYears;if(cut>0){const old=S.annual.filter(x=>x.year<cut);if(old.length){const buckets=new Map;for(const r of old){const start=Math.floor(r.year/250)*250,b=buckets.get(start)||{startYear:start,endYear:start+249,years:0,nutritionDeaths:0,reliefDelivered:0,reliefSpending:0,crisisYears:0};b.years++;b.nutritionDeaths+=Number(r.nutritionDeaths||0);b.reliefDelivered+=Number(r.reliefDelivered||0);b.reliefSpending+=Number(r.reliefSpending||0);if(Number(r.crisisSettlements||0)>0)b.crisisYears++;buckets.set(start,b)}for(const b of buckets.values()){const ex=S.archives.find(x=>x.startYear===b.startYear);if(ex)Object.assign(ex,b);else S.archives.push(b)}S.annual=S.annual.filter(x=>x.year>=cut);S.stats.archivedYears+=old.length}}if(S.incidents.length>S.settings.maxIncidents)S.incidents.splice(0,S.incidents.length-S.settings.maxIncidents);if(S.convoys.length>S.settings.maxConvoys)S.convoys.splice(0,S.convoys.length-S.settings.maxConvoys);return S}
function fingerprint(w){const S=initialize(w),s=JSON.stringify({year:S.currentYear,profiles:S.profiles.map(p=>[p.settlementId,p.nutritionIndex,p.malnutritionRate,p.severeMalnutritionRate,p.famineStage,p.rationing,p.reliefReceived,p.reliefShortfall,p.nutritionDeaths,p.refugeeCampPopulation,p.basket]),incidents:S.incidents.slice(-120),convoys:S.convoys.slice(-160),annual:S.annual.slice(-80),stats:S.stats});return hash(s).toString(16).padStart(8,'0')}
function validate(w){const S=initialize(w),e=[];if(S.profiles.length!==(w.settlements?.length||0))e.push('nutrition profile coverage');for(const p of S.profiles){if(p.lastYear==null)continue;for(const [k,v] of Object.entries({nutrition:p.nutritionIndex,foodAccess:p.foodAccess,affordability:p.affordability,diversity:p.dietDiversity,malnutrition:p.malnutritionRate,severe:p.severeMalnutritionRate}))if(!Number.isFinite(Number(v))||Number(v)<0||Number(v)>1)e.push(`${k} ${p.settlementId}`);if(!Number.isInteger(p.famineStage)||p.famineStage<0||p.famineStage>5)e.push(`famine stage ${p.settlementId}`);if(p.reliefReceived<0||p.reliefShortfall<0||p.nutritionDeaths<0||p.refugeeCampPopulation<0)e.push(`nutrition accounting ${p.settlementId}`)}for(const m of w.resources?.markets||[])for(const id of Resources.FOOD_IDS||[])if(Number(m.inventory?.[id]||0)<-.0001)e.push(`negative relief inventory ${m.settlementId}:${id}`);return[...new Set(e)]}
function performance(w){const r=buildRuntime(w),p=perf.get(w)||{cacheBuilds:0,reads:0,profileHits:0,donorSearches:0};p.reads++;perf.set(w,p);return{...p,indexedMarkets:r.resourceBy.size,indexedHouseholds:r.householdBy.size,indexedMunicipal:r.municipalBy.size,indexedEmergency:r.emergencyBy.size,indexedProfiles:r.profileBy.size,sieged:r.sieged.size,blockaded:r.blockaded.size}}
function initialize(w){if(!w)throw new Error('World required');Emergency.initialize(w);const S=state(w),expected=w.settlements?.length||0;if(S.profiles.length!==expected)return syncProfiles(w);const ids=new Set(S.profiles.map(p=>Number(p.settlementId)));if((w.settlements||[]).some(s=>!ids.has(Number(s.id))))return syncProfiles(w);buildRuntime(w);return S}
function installBridge(){if(Workforce.__nutritionBridge)return;Workforce.__nutritionBridge=true;const rawYear=Workforce.simulateWorkforceYear.bind(Workforce),rawYears=Workforce.simulateYears.bind(Workforce);Workforce.simulateWorkforceYear=function(w,year=Workforce.absYear(w)){const out=rawYear(w,year);simulateNutritionYear(w,year);return out};Workforce.simulateYears=function(w,years,options={}){const n=Math.max(0,Math.floor(Number(years)||0));for(let i=0;i<n;i++){rawYears(w,1,options);simulateNutritionYear(w,absYear(w))}return w.workforce};Workforce.simulateTo=function(w,target,options={}){const t=Math.floor(Number(target)||0),now=absYear(w);if(t<now)throw new Error('Nutrition-enabled simulation cannot run backward');return Workforce.simulateYears(w,t-now,options)}}
installBridge();const api={VERSION,SCHEMA,STAGES,initialize,absYear,simulateNutritionYear,settlementView,summary,fingerprint,validate,profileState,conditions,foodBasket,performance,installBridge};return api;
});
