(() => {
'use strict';
const R=window.WorldForgeRelease,W=window.WorldForgeWiki,C=window.WorldForgeCulture,F=window.WorldForgeFactions,X=window.WorldForgeEndless;
if(!R||!W||!C||!F||!X||!window.WorldRenderer)return;
const $=s=>document.querySelector(s),fmt=(n,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const ui={world:null,viewYear:null};
function install(){document.title='WorldForge · v1.0 Living World';const v=$('.version-pill');if(v)v.textContent='v1.0 · LIVING WORLD';const f=document.querySelector('footer span');if(f)f.textContent='WorldForge v1.0 · Living World';const sim=$('#simState');if(sim)sim.textContent='WORLDFORGE v1.0 · ENDLESS LIVING WORLD READY';const arch=$('.architecture-panel');if(arch){arch.querySelector('h2').textContent='WorldForge v1.0 Release State Contract';arch.querySelector('.status-ready').textContent='v1.0 INTEGRATED';arch.querySelector('.architecture-grid').innerHTML='<div><b>Living Simulation</b><span>World · history · society · cities · culture · religion · factions · economy · crime</span></div><div><b>Emergent Adventure</b><span>Historical ruins · procedural dungeons · encounters · loot · quests · dialogue</span></div><div><b>Endless Chronicle</b><span>Absolute clock · epoch rebasing · tiered retention · archive compaction</span></div><div><b>Universal Encyclopedia</b><span>People · realms · cultures · faiths · organizations · sites · quests · ancient eras</span></div>';arch.querySelector('.help').textContent='WorldForge v1.0 is the integrated release. Every major simulation layer shares one deterministic save state and one long-run world clock.'}
 const road=$('.version-roadmap');if(road)road.innerHTML='<span class="done">v0.1 WORLD</span><span class="done">v0.2 HISTORY</span><span class="done">v0.3 SOCIETY</span><span class="done">v0.4 CITIES</span><span class="done">v0.5 ADVENTURE</span><span class="done">v0.6 STORY</span><span class="done">v0.7 CULTURE</span><span class="done">v0.8 FACTIONS</span><span class="done">v0.9 ENDLESS</span><span class="done release">v1.0 LIVING WORLD</span>';
 const types=$('#wikiType');if(types){[['culture','Cultures'],['religion','Religions'],['organization','Organizations'],['era','Ancient eras']].forEach(([value,text])=>{if(![...types.options].some(o=>o.value===value)){const o=document.createElement('option');o.value=value;o.textContent=text;types.appendChild(o)}})}
 const marker=$('.architecture-panel');if(marker&&!$('#releasePanel'))marker.insertAdjacentHTML('beforebegin',`<section id="releasePanel" class="panel release-panel"><div class="panel-head"><div><span class="eyebrow">WORLDFORGE v1.0</span><h2>Integrated Living World</h2></div><span class="release-seal">RELEASE</span></div><div class="release-kpis"><div><span>WORLD AGE</span><b id="releaseYear">0</b></div><div><span>CULTURES</span><b id="releaseCultures">—</b></div><div><span>FAITHS</span><b id="releaseFaiths">—</b></div><div><span>ORGANIZATIONS</span><b id="releaseOrgs">—</b></div><div><span>ACTIVE REALMS</span><b id="releaseRealms">—</b></div><div><span>NOTABLE PEOPLE</span><b id="releasePeople">—</b></div><div><span>ARCHIVED EVENTS</span><b id="releaseArchive">—</b></div><div><span>ERA ARCHIVES</span><b id="releaseEras">—</b></div></div><div class="release-stack"><span>GEOGRAPHY</span><i>→</i><span>HISTORY</span><i>→</i><span>SOCIETY</span><i>→</i><span>CULTURE</span><i>→</i><span>FACTIONS</span><i>→</i><span>CITIES</span><i>→</i><span>ADVENTURE</span><i>→</i><span>STORY</span><i>→</i><span>ENCYCLOPEDIA</span></div><p>The world no longer ends at a fixed year. Recent centuries stay richly replayable while ancient detail is compressed into persistent historical summaries and checkpoints.</p></section>`);
 ['input','change'].forEach(type=>$('#wikiSearch')?.addEventListener(type,()=>setTimeout(fixWikiYear,0)));$('#wikiType')?.addEventListener('change',()=>setTimeout(fixWikiYear,0));$('#wikiResults')?.addEventListener('click',()=>setTimeout(fixWikiYear,0));$('#wikiArticle')?.addEventListener('click',()=>setTimeout(fixWikiYear,0))
}
function fixWikiYear(){if(!ui.world)return;const el=$('#wikiYear');if(el){const abs=ui.viewYear==null?X.absoluteYear(ui.world):(ui.world.endless?.epochOffset||0)+ui.viewYear;el.textContent=`YEAR ${fmt(abs)}`}}
function render(){if(!ui.world||!$('#releasePanel'))return;const cv=ui.viewYear==null?C.currentView(ui.world):C.viewAt(ui.world,ui.viewYear),fv=ui.viewYear==null?F.currentView(ui.world):F.viewAt(ui.world,ui.viewYear),m=X.memoryStats(ui.world),hv=ui.viewYear==null?window.WorldForgeHistory.currentView(ui.world):window.WorldForgeHistory.viewAt(ui.world,ui.viewYear),sv=ui.viewYear==null?SView():window.WorldForgeSociety.viewAt(ui.world,ui.viewYear);$('#releaseYear').textContent=fmt(ui.viewYear==null?m.absoluteYear:(ui.world.endless?.epochOffset||0)+ui.viewYear);$('#releaseCultures').textContent=fmt(cv.cultures.filter(x=>x.active).length);$('#releaseFaiths').textContent=fmt(cv.religions.filter(x=>x.active).length);$('#releaseOrgs').textContent=fmt(fv.metrics.active);$('#releaseRealms').textContent=fmt(hv.metrics.activeRealms);$('#releasePeople').textContent=fmt(sv.stats.livingNotables);$('#releaseArchive').textContent=fmt(m.archivedEvents);$('#releaseEras').textContent=fmt(m.eraArchives);fixWikiYear()}
function SView(){return window.WorldForgeSociety.currentView(ui.world)}
install();const proto=window.WorldRenderer.prototype,oldSetWorld=proto.setWorld,oldSetHistoryView=proto.setHistoryView;proto.setWorld=function(world){ui.world=world;X.initialize(world);const r=oldSetWorld.call(this,world);ui.viewYear=null;render();return r};proto.setHistoryView=function(v){const r=oldSetHistoryView.call(this,v);if(this.world){ui.world=this.world;ui.viewYear=v?.isPresent?null:(v?.year??null);render()}return r};window.WorldForgeReleaseUI={version:'1.0.0',render,state:ui};
})();

// v1.1 Living Canon bootstrap. The creator toolkit may already be loading from
// the v0.9 compatibility loader; this waits for existing scripts rather than
// racing duplicate copies, then layers the bidirectional bridge on top.
(()=>{
  if(typeof document==='undefined')return;
  const addStyle=href=>{if(document.querySelector(`link[href="${href}"]`))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)};
  const waitGlobal=(name,src)=>new Promise((resolve,reject)=>{if(window[name])return resolve(window[name]);let s=[...document.scripts].find(x=>x.getAttribute('src')===src);if(!s){s=document.createElement('script');s.src=src;document.head.appendChild(s)}let n=0;const t=setInterval(()=>{if(window[name]){clearInterval(t);resolve(window[name])}else if(++n>160){clearInterval(t);reject(new Error(`Timed out loading ${name}`))}},25)});
  async function boot(){try{addStyle('creator-suite.css');addStyle('canon-bridge.css');await waitGlobal('WorldForgeCreatorSuite','creator-suite-engine.js');await waitGlobal('WorldForgeCreatorUI','creator-suite-ui.js');await waitGlobal('WorldForgeCanonBridge','canon-bridge-engine.js');if(!window.__canonWikiAdapterLoaded){window.__canonWikiAdapterLoaded=true;const s=document.createElement('script');s.src='canon-wiki-adapter.js';document.head.appendChild(s);await new Promise(r=>{s.onload=r;s.onerror=r})}await waitGlobal('WorldForgeCanonBridgeUI','canon-bridge-ui.js');const world=window.WorldForgeExtensions?.state?.world||window.WorldForgeEndlessUI?.state?.world||window.WorldForgeReleaseUI?.state?.world;if(world){window.WorldForgeCreatorUI.state.world=world;window.WorldForgeCreatorSuite.initialize(world);window.WorldForgeCreatorSuite.starterPack(world);window.WorldForgeCanonBridge.initialize(world);window.WorldForgeCanonBridge.syncSimulationToAuthoring(world);window.WorldForgeCreatorUI.render();window.WorldForgeCanonBridgeUI.state.world=world;window.WorldForgeCanonBridgeUI.render()}document.title='WorldForge · v1.1 Living Canon';const pill=document.querySelector('.version-pill');if(pill)pill.textContent='v1.1 · LIVING CANON';const foot=document.querySelector('footer span');if(foot)foot.textContent='WorldForge v1.1 · Living Canon'}catch(e){console.error('Living Canon bootstrap failed',e)}}
  boot();
})();