(()=>{
'use strict';
const R=window.WorldForgeResources,T=window.WorldForgeTechnology,X=window.WorldForgeEndless,S=window.WorldForgeSociety;
if(!R||!T||!window.WorldRenderer)return;
const $=s=>document.querySelector(s),fmt=(n,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d}),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={world:null,viewYear:null,commodity:'grain',settlementId:null,query:'',last:null};
const base=T.simulateYears?.bind(T);if(base)R.setBaseSimulator(base);if(X?.setBaseSimulator&&base)X.setBaseSimulator((w,y,o)=>R.simulateYears(w,y,o));else if(S&&base){S.simulateYears=(w,y,o)=>{R.simulateYears(w,y,o);return w.society};S.simulateTo=(w,y,o)=>{R.simulateTo(w,y,o);return w.society}}
function world(){return state.world||window.WorldForgeTechnologyUI?.state?.world||window.WorldForgeArtifactUI?.state?.world||window.WorldForgeReleaseUI?.state?.world||null}
function viewedYear(w){return state.viewYear==null?R.absYear(w):(w.endless?.epochOffset||0)+Number(state.viewYear||0)}
function ensure(){if($('#resourcePanel'))return;const anchor=$('#technologyPanel')||$('#artifactPanel')||$('#calendarClimatePanel')||$('.architecture-panel');if(!anchor)return;anchor.insertAdjacentHTML('afterend',`<section id="resourcePanel" class="panel resource-panel"><div class="panel-head"><div><span class="eyebrow">RESOURCES · AGRICULTURE · SUPPLY CHAINS</span><h2>The World Market</h2></div><span class="status-ready">v1.8</span></div><div id="resourceKpis" class="resource-kpis"></div><div class="resource-toolbar"><label>Settlement<input id="resourceSearch" placeholder="Search markets…"></label><button id="resourceExport">Export Economic Ledger</button></div><div class="resource-layout"><div><div class="resource-section-head"><span>COMMODITY BOARD</span></div><div id="commodityGrid" class="commodity-grid"></div><div class="resource-section-head" style="margin-top:12px"><span>MARKETS</span></div><div id="marketList" class="market-list"></div></div><div id="resourceDetail" class="resource-detail"></div></div><div class="resource-bottom"><div><div class="resource-section-head"><span>SUPPLY CHAIN FLOWS</span></div><div id="resourceFlows" class="resource-feed"></div></div><div><div class="resource-section-head"><span>SHORTAGES & SHOCKS</span></div><div id="resourceShocks" class="resource-feed"></div></div></div><p class="resource-legend">Production is local. Weather and technology alter yields; roads, navigation, banking, crime and war alter distribution. A food shortage therefore emerges from physical stock and transport rather than a decorative event roll.</p></section>`);$('#resourceSearch').oninput=e=>{state.query=e.target.value;render(true)};$('#commodityGrid').onclick=e=>{const b=e.target.closest('[data-commodity]');if(b){state.commodity=b.dataset.commodity;render(true)}};$('#marketList').onclick=e=>{const b=e.target.closest('[data-market]');if(b){state.settlementId=Number(b.dataset.market);render(true)}};$('#resourceExport').onclick=exportLedger}
function stressClass(v){return v>.55?'stress-high':v>.22?'stress-mid':''}
function render(force=false){const w=world();if(!w)return;state.world=w;ensure();if(!$('#resourcePanel'))return;R.initialize(w);const y=viewedYear(w),sum=R.summary(w),key=`${R.fingerprint(w)}|${y}|${state.commodity}|${state.settlementId}|${state.query}`;if(!force&&key===state.last)return;state.last=key;if(state.settlementId==null||!w.settlements[state.settlementId])state.settlementId=0;
 $('#resourceKpis').innerHTML=[['WORLD YEAR',fmt(R.absYear(w))],['MARKETS',sum.markets],['COMMODITIES',sum.commodities],['MEAN FOOD SECURITY',`${fmt(sum.meanFoodSecurity*100)}%`],['STRESSED MARKETS',sum.stressedMarkets],['CRITICAL FOOD',sum.criticalMarkets],['CARGO MOVED',fmt(sum.transported,1)],['FAMINES',sum.famines]].map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join('');
 $('#commodityGrid').innerHTML=R.COMMODITIES.map(c=>{const t=R.commodityTotals(w,c.id);return`<button class="commodity-card ${state.commodity===c.id?'active':''}" data-commodity="${c.id}"><span class="ico">${c.icon}</span><span><small>${esc(c.category.toUpperCase())}</small><b>${esc(c.name)}</b><small>${fmt(t.meanPrice,2)} avg · ${fmt(t.meanShortage*100)}% shortage</small></span></button>`}).join('');
 const q=state.query.trim().toLowerCase(),markets=R.initialize(w).markets.map(m=>R.settlementView(w,m.settlementId)).filter(v=>!q||v.settlement.name.toLowerCase().includes(q)).sort((a,b)=>b.marketStress-a.marketStress||a.settlement.name.localeCompare(b.settlement.name));if(!markets.some(v=>v.settlement.id===state.settlementId)&&markets[0])state.settlementId=markets[0].settlement.id;
 $('#marketList').innerHTML=markets.map(v=>`<button class="market-row ${v.settlement.id===state.settlementId?'active':''}" data-market="${v.settlement.id}"><span><b>${esc(v.settlement.name)}</b><small>${esc(v.settlement.type)} · ${esc(w.history?.realms?.[v.realmId]?.shortName||'Independent')}</small></span><span class="${stressClass(v.marketStress)}"><b>${fmt(v.foodDays)}d</b><small>${fmt(v.marketStress*100)}% stress</small></span></button>`).join('')||'<p>No markets match this search.</p>';
 renderDetail(w);renderFlows(w,y);renderShocks(w,y);const pill=$('.version-pill');if(pill)pill.textContent='v1.8 · RESOURCES & SUPPLY CHAINS';const foot=document.querySelector('footer span');if(foot)foot.textContent='WorldForge v1.8 · Resources, Agriculture & Supply Chains';document.title=`${w.name} · World Market · WorldForge v1.8`}
function renderDetail(w){const v=R.settlementView(w,state.settlementId),host=$('#resourceDetail');if(!v){host.innerHTML='<p>Select a market.</p>';return}const food=v.foodSecurity>.8?'food-ok':v.foodSecurity>.45?'food-warn':'food-bad',rows=[...v.rows].sort((a,b)=>b.shortage-a.shortage||b.price-a.price);host.innerHTML=`<span class="eyebrow">LOCAL MARKET · ${esc(w.history?.realms?.[v.realmId]?.shortName||'INDEPENDENT')}</span><h2>${esc(v.settlement.name)}</h2><div class="resource-detail-grid"><div><span>POPULATION</span><b>${fmt(v.population)}</b></div><div><span>FOOD SECURITY</span><b class="${food}">${fmt(v.foodSecurity*100)}%</b></div><div><span>RESERVES</span><b>${fmt(v.foodDays)} days</b></div><div><span>MARKET STRESS</span><b class="${stressClass(v.marketStress)}">${fmt(v.marketStress*100)}%</b></div></div><table class="stock-table"><thead><tr><th>Commodity</th><th>Stock</th><th>Price</th><th>Produced</th><th>Imported</th><th>Exported</th><th>Shortage</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.commodity.icon} ${esc(x.commodity.name)}<div class="shortage-meter"><i style="width:${Math.round(x.shortage*100)}%"></i></div></td><td>${fmt(x.stock,1)}</td><td>${fmt(x.price,2)}</td><td>${fmt(x.production,1)}</td><td>${fmt(x.imports,1)}</td><td>${fmt(x.exports,1)}</td><td class="${stressClass(x.shortage)}">${fmt(x.shortage*100)}%</td></tr>`).join('')}</tbody></table>`}
function renderFlows(w,y){const c=R.MAP.get(state.commodity),flows=R.supplyChain(w,state.commodity,120).filter(x=>x.year<=y).slice(0,40);$('#resourceFlows').innerHTML=flows.map(f=>`<article class="supply-path"><span>${c?.icon||'◆'}</span><span><b>${esc(w.settlements[f.from]?.name||String(f.from))} → ${esc(w.settlements[f.to]?.name||String(f.to))}</b><small>Year ${fmt(f.year)} · ${esc(f.method)} · price gap ${fmt(f.priceGap,2)}</small></span><b>${fmt(f.quantity,1)}</b></article>`).join('')||`<article><b>No recent ${esc(c?.name||state.commodity)} shipments.</b><small>Trade appears when a market holds surplus and another market offers enough price/shortage pressure.</small></article>`}
function renderShocks(w,y){const shocks=(w.resources?.shocks||[]).filter(x=>x.year<=y).slice(-40).reverse();$('#resourceShocks').innerHTML=shocks.map(x=>`<article><span>YEAR ${fmt(x.year)} · ${esc(x.type.replaceAll('_',' ').toUpperCase())}</span><b>${esc(x.title)}</b><small>${esc(w.settlements?.[x.settlementId]?.name||'World market')} · severity ${fmt(x.severity*100)}%</small></article>`).join('')||'<article><b>No major resource shocks in this view.</b></article>'}
function exportLedger(){const w=world();if(!w)return;const y=R.absYear(w),commodities=R.COMMODITIES.map(c=>({c,t:R.commodityTotals(w,c.id)})),markets=R.initialize(w).markets.map(m=>R.settlementView(w,m.settlementId)).sort((a,b)=>b.marketStress-a.marketStress),html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(w.name)} · Economic Ledger</title><style>body{margin:0;background:#0f1513;color:#e9eadf;font:15px/1.55 system-ui}.wrap{max-width:1150px;margin:auto;padding:32px}.mast{border:1px solid #6b6040;background:#171c18;padding:28px;border-radius:22px}.mast h1{font:700 clamp(40px,7vw,74px)/1.05 Georgia,serif;color:#e0c777;margin:.15em 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:10px;margin:20px 0}article{border:1px solid #324039;background:#121916;border-radius:13px;padding:16px}small{color:#8fa19a}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #2b3632;text-align:right}th:first-child,td:first-child{text-align:left}</style></head><body><main class="wrap"><header class="mast"><small>WORLDFORGE v1.8 · ECONOMIC LEDGER · YEAR ${fmt(y)}</small><h1>${esc(w.name)}</h1><p>Physical production, inventories, prices, shortages and trade routes across the living world.</p></header><section class="grid">${commodities.map(({c,t})=>`<article><small>${esc(c.category.toUpperCase())}</small><h2>${c.icon} ${esc(c.name)}</h2><p>${esc(c.description)}</p><b>${fmt(t.stock,1)} stock · ${fmt(t.meanPrice,2)} mean price</b><p>${fmt(t.production,1)} produced · ${fmt(t.meanShortage*100)}% mean shortage</p></article>`).join('')}</section><h2>Markets</h2><table><thead><tr><th>Settlement</th><th>Realm</th><th>Food days</th><th>Security</th><th>Stress</th></tr></thead><tbody>${markets.map(v=>`<tr><td>${esc(v.settlement.name)}</td><td>${esc(w.history?.realms?.[v.realmId]?.shortName||'Independent')}</td><td>${fmt(v.foodDays)}</td><td>${fmt(v.foodSecurity*100)}%</td><td>${fmt(v.marketStress*100)}%</td></tr>`).join('')}</tbody></table></main></body></html>`;const blob=new Blob([html],{type:'text/html;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${String(w.name).replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-year-${y}-economic-ledger.html`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}
const ef=$('#eventFilter');if(ef){for(const [v,t] of[['commodity_shortage','Commodity shortages'],['trade_boom','Trade booms'],['famine','Food crises']])if(![...ef.options].some(o=>o.value===v)){const o=document.createElement('option');o.value=v;o.textContent=t;ef.appendChild(o)}}
const proto=window.WorldRenderer.prototype,oldSet=proto.setWorld,oldHist=proto.setHistoryView;proto.setWorld=function(w){state.world=w;state.viewYear=null;state.settlementId=null;state.last=null;R.initialize(w);const r=oldSet.call(this,w);setTimeout(()=>render(true),0);return r};proto.setHistoryView=function(v){const r=oldHist.call(this,v);if(this.world){state.world=this.world;state.viewYear=v?.isPresent?null:(v?.year??null);state.last=null;setTimeout(()=>render(true),0)}return r};setInterval(()=>render(false),1800);setTimeout(()=>render(true),360);window.WorldForgeResourceUI={version:'1.8.0',state,render,exportLedger};
})();