(function(root,factory){
  const api=factory(
    root&&root.WorldForgeHistory,
    root&&root.WorldForgeCity,
    root&&root.WorldForgeCalendar,
    root&&root.WorldForgeTechnology
  );
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeResources=api;
})(typeof window!=='undefined'?window:globalThis,function(History,City,Calendar,Technology){
'use strict';

const VERSION='1.8.0',SCHEMA=1;
const COMMODITIES=[
  {id:'grain',name:'Grain',category:'Food',basePrice:8,demand:.00042,spoil:.055,bulk:1,food:1,icon:'🌾',description:'Staple cereals, flour and bread grain.'},
  {id:'rice',name:'Rice',category:'Food',basePrice:10,demand:.00024,spoil:.045,bulk:1,food:.95,icon:'🍚',description:'Water-intensive staple grain favored by warm wet regions.'},
  {id:'fish',name:'Fish',category:'Food',basePrice:12,demand:.00018,spoil:.16,bulk:.8,food:.8,icon:'🐟',description:'Coastal, river and wetland protein supply.'},
  {id:'livestock',name:'Livestock',category:'Food',basePrice:18,demand:.00011,spoil:.025,bulk:1.5,food:1.15,icon:'🐄',description:'Meat, dairy, hides and draft animals.'},
  {id:'timber',name:'Timber',category:'Material',basePrice:16,demand:.00013,spoil:.005,bulk:1.8,food:0,icon:'🪵',description:'Construction wood, ship timber, fuel and tools.'},
  {id:'iron',name:'Iron',category:'Metal',basePrice:31,demand:.000055,spoil:0,bulk:1.4,food:0,icon:'⛓',description:'Strategic metal for tools, weapons and machinery.'},
  {id:'copper',name:'Copper',category:'Metal',basePrice:29,demand:.000038,spoil:0,bulk:1.3,food:0,icon:'◈',description:'Conductive and alloying metal used in tools, coinage and craft.'},
  {id:'salt',name:'Salt',category:'Strategic',basePrice:20,demand:.00007,spoil:0,bulk:.7,food:0,icon:'◇',description:'Preservative and strategic food-processing commodity.'},
  {id:'coal',name:'Coal',category:'Fuel',basePrice:24,demand:.000065,spoil:0,bulk:1.6,food:0,icon:'⬟',description:'Dense fuel for advanced metallurgy and mechanical industry.'},
  {id:'wine',name:'Wine',category:'Luxury',basePrice:26,demand:.000038,spoil:.012,bulk:.8,food:.12,icon:'🍷',description:'High-value agricultural luxury and trade good.'}
];
const MAP=new Map(COMMODITIES.map(x=>[x.id,x]));
const FOOD_IDS=COMMODITIES.filter(x=>x.food>0).map(x=>x.id);
let baseSimulator=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const round=(v,d=3)=>Number(Number(v).toFixed(d));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed);return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function seedOf(w){return w.endless?.baseSeed||String(w.settings?.seed||'WORLD').split('|EPOCH:')[0]}
function keyed(w,y,salt){return rng(`${seedOf(w)}|RESOURCE|${y}|${salt}`)}
function absYear(w){return(w.endless?.epochOffset||0)+Number(w.history?.currentYear||0)}
function setBaseSimulator(fn){if(typeof fn==='function')baseSimulator=fn;return api}
function tile(w,s){const i=Math.round(s.y)*w.settings.width+Math.round(s.x);return{biome:w.layers.biome[i]||'grassland',elevation:Number(w.layers.elevation[i]||0),temperature:Number(w.layers.temperature[i]||.5),moisture:Number(w.layers.moisture[i]||.5),bits:Number(w.layers.resources[i]||0)}}
function coastal(w,s){const W=w.settings.width,H=w.settings.height,sea=w.settings.seaLevel;for(let oy=-1;oy<=1;oy++)for(let ox=-1;ox<=1;ox++){if(!ox&&!oy)continue;const y=Math.round(s.y)+oy;if(y<0||y>=H)continue;const x=(Math.round(s.x)+ox+W)%W,i=y*W+x;if(w.layers.elevation[i]<sea)return true}return false}
function riverNear(w,s){for(const r of w.rivers||[])for(const p of r.path||[]){let dx=Math.abs(p.x-s.x);dx=Math.min(dx,w.settings.width-dx);if(Math.hypot(dx,p.y-s.y)<=2.2)return true}return false}
function suitability(w,s,id){const t=tile(w,s),coast=coastal(w,s),river=riverNear(w,s),b=t.biome,m=t.moisture,temp=t.temperature,bits=t.bits;
  if(id==='grain')return clamp(.18+(['grassland','steppe','savanna'].includes(b)?.62:0)+(b==='forest'?.18:0)+m*.18-(b==='desert'?.25:0),.05,1.2);
  if(id==='rice')return clamp(.03+(['wetland','rainforest'].includes(b)?.72:0)+(river?.34:0)+Math.max(0,temp-.52)*.65+m*.24,.02,1.25);
  if(id==='fish')return clamp(.03+(coast?.72:0)+(river?.42:0)+(b==='wetland'?.32:0),.02,1.3);
  if(id==='livestock')return clamp(.12+(['grassland','steppe','savanna','tundra'].includes(b)?.58:0)+(b==='forest'?.18:0)+(1-Math.abs(m-.45))*.14,.05,1.1);
  if(id==='timber')return clamp(.05+(['forest','taiga','rainforest'].includes(b)?.88:0)+((bits&2)? .30:0),.03,1.25);
  if(id==='iron')return clamp(.03+((bits&1)?.86:0)+(['mountain','alpine'].includes(b)?.34:0)+Math.max(0,t.elevation-.62)*.35,.02,1.2);
  if(id==='copper')return clamp(.025+((bits&8)?.75:0)+(['mountain','alpine','steppe'].includes(b)?.28:0),.02,1.05);
  if(id==='salt')return clamp(.03+(coast?.48:0)+(b==='desert'?.46:0)+((bits&8)?.24:0),.02,1.05);
  if(id==='coal')return clamp(.02+((bits&1)?.48:0)+(['mountain','taiga','forest'].includes(b)?.34:0)+((bits&8)?.22:0),.015,1.0);
  if(id==='wine')return clamp(.025+(['grassland','steppe','savanna'].includes(b)?.34:0)+Math.max(0,temp-.42)*.46+(1-Math.abs(m-.43))*.17,.02,1.0);
  return .1;
}
function realmId(w,sid){return w.history?.current?.settlementKingdomIds?.[sid]??w.settlements?.[sid]?.kingdomId??null}
function population(w,sid){return Math.max(20,Number(w.history?.current?.settlementPopulation?.[sid]||w.settlements?.[sid]?.population||200))}
function techEffects(w,rid){if(rid==null||!Technology?.realmView)return{};try{return Technology.realmView(w,rid)?.effects||{}}catch{return{}}}
function activeWarBetween(w,a,b){if(a==null||b==null||a===b)return false;for(const wid of w.history?.current?.activeWarIds||[]){const q=w.history?.wars?.[wid];if(q&&((q.attackerId===a&&q.defenderId===b)||(q.attackerId===b&&q.defenderId===a)))return true}return false}
function initialMarket(w,s){const pop=population(w,s.id),inventory={},prices={},suitabilityMap={};for(const c of COMMODITIES){const suit=suitability(w,s,c.id);suitabilityMap[c.id]=round(suit);const need=Math.max(.15,pop*c.demand*12);inventory[c.id]=round(need*(1.3+suit*2.2),2);prices[c.id]=c.basePrice}return{settlementId:s.id,inventory,prices,suitability:suitabilityMap,production:{},consumption:{},imports:{},exports:{},shortages:{},foodSecurity:1,foodDays:365,marketStress:0,lastYear:-1}}
function initialize(w){
 if(!w)throw new Error('World required');History?.initialize?.(w);City?.initialize?.(w);Calendar?.initialize?.(w);Technology?.initialize?.(w);
 if(!w.resources||w.resources.schemaVersion!==SCHEMA)w.resources={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:absYear(w),markets:[],flows:[],shocks:[],annual:[],archives:[],settings:{maxFlows:1400,maxShocks:700,retainDetailedYears:1000,tradeIntensity:.55},stats:{produced:0,consumed:0,transported:0,shortages:0,famines:0,tradeBooms:0,warDisruptions:0,spoiled:0,archivedYears:0}};
 const R=w.resources;R.engineVersion=VERSION;R.markets=R.markets||[];R.flows=R.flows||[];R.shocks=R.shocks||[];R.annual=R.annual||[];R.archives=R.archives||[];R.settings={maxFlows:1400,maxShocks:700,retainDetailedYears:1000,tradeIntensity:.55,...R.settings};R.stats={produced:0,consumed:0,transported:0,shortages:0,famines:0,tradeBooms:0,warDisruptions:0,spoiled:0,archivedYears:0,...R.stats};
 const by=new Map(R.markets.map(x=>[x.settlementId,x]));for(const s of w.settlements||[])if(!by.has(s.id)){const m=initialMarket(w,s);R.markets.push(m);by.set(s.id,m)}R.markets.sort((a,b)=>a.settlementId-b.settlementId);return R
}
function market(w,sid){return initialize(w).markets.find(x=>x.settlementId===Number(sid))||null}
function annualClimate(w,sid){const cur=w.calendarClimate?.current;if(cur?.settlement){const x=cur.settlement.find(q=>q.id===sid);if(x)return x}return{cropYield:1,foodStress:0,drought:0,flood:0,storm:0,winterSeverity:0,heat:0}}
function demandFor(w,sid,c){const pop=population(w,sid),city=w.cities?.cities?.[sid],pros=Number(w.history?.current?.settlementProsperity?.[sid]??city?.prosperity??.45),lux=c.category==='Luxury'?(.45+pros*1.4):1;return Math.max(.05,pop*c.demand*lux*12)}
function productionFor(w,sid,c,year){const m=market(w,sid),s=w.settlements[sid],rid=realmId(w,sid),fx=techEffects(w,rid),cl=annualClimate(w,sid),rr=keyed(w,year,`prod:${sid}:${c.id}`),suit=Number(m.suitability[c.id]||.1),pop=population(w,sid);let tech=1,weather=1;
 if(c.id==='grain'||c.id==='rice'||c.id==='wine'){tech+=Number(fx.food||0)*1.45;weather*=cl.cropYield??1}
 if(c.id==='livestock'){tech+=Number(fx.food||0)*.7;weather*=cl.drought>.6?.8:1}
 if(c.id==='fish')tech+=Number(fx.navigation||0)*.25;
 if(['iron','copper','coal'].includes(c.id))tech+=Number(fx.engineering||0)*.75+Number(fx.artifact||0)*.35;
 if(c.id==='timber')tech+=Number(fx.engineering||0)*.18;
 const scale=Math.pow(pop,0.72)*.035,noise=.88+rr()*.24;return round(Math.max(0,suit*scale*tech*weather*noise),3)
}
function refreshPrices(w,m){for(const c of COMMODITIES){const need=demandFor(w,m.settlementId,c),stock=Number(m.inventory[c.id]||0),coverage=stock/Math.max(.1,need),shortage=clamp(1-coverage,0,1),glut=clamp(coverage-2,0,3),stress=1+shortage*2.8-glut*.16;m.shortages[c.id]=round(shortage);m.prices[c.id]=round(clamp(c.basePrice*stress,Math.max(1,c.basePrice*.55),c.basePrice*5.5),2)}}
function produceConsume(w,year){const R=initialize(w);for(const m of R.markets){m.production={};m.consumption={};m.imports={};m.exports={};const sid=m.settlementId;for(const c of COMMODITIES){const prod=productionFor(w,sid,c,year),demand=demandFor(w,sid,c),before=Number(m.inventory[c.id]||0),spoiled=before*c.spoil;m.inventory[c.id]=Math.max(0,before-spoiled+prod);R.stats.spoiled+=spoiled;R.stats.produced+=prod;m.production[c.id]=round(prod,3);const consume=Math.min(m.inventory[c.id],demand);m.inventory[c.id]=Math.max(0,m.inventory[c.id]-consume);m.consumption[c.id]=round(consume,3);R.stats.consumed+=consume}refreshPrices(w,m)}}
function transfer(w,from,to,c,capacity,year,method){const a=market(w,from),b=market(w,to);if(!a||!b)return 0;const needA=demandFor(w,from,c),needB=demandFor(w,to,c),reserve=needA*.65,available=Math.max(0,Number(a.inventory[c.id]||0)-reserve),gap=Number(b.prices[c.id]||c.basePrice)-Number(a.prices[c.id]||c.basePrice),shortB=Number(b.shortages[c.id]||0);if(available<=.02||gap<=c.basePrice*.08&&shortB<.18)return 0;const desired=Math.max(shortB*needB*.65,gap/c.basePrice*needB*.18),qty=Math.min(available,desired,capacity/Math.max(.4,c.bulk));if(qty<=.02)return 0;const loss=method==='sea'?qty*.015:qty*.008;a.inventory[c.id]-=qty;b.inventory[c.id]+=Math.max(0,qty-loss);a.exports[c.id]=round((a.exports[c.id]||0)+qty,3);b.imports[c.id]=round((b.imports[c.id]||0)+qty-loss,3);w.resources.stats.transported+=qty;w.resources.flows.push({id:`${year}:${from}:${to}:${c.id}:${w.resources.flows.length}`,year,from,to,commodityId:c.id,quantity:round(qty,3),loss:round(loss,3),method,fromRealmId:realmId(w,from),toRealmId:realmId(w,to),priceGap:round(gap,2)});return qty}
function roadTrade(w,year){const seen=new Set();for(const r of w.roads||[]){const a=r.from,b=r.to,key=a<b?`${a}:${b}`:`${b}:${a}`;if(seen.has(key))continue;seen.add(key);const ra=realmId(w,a),rb=realmId(w,b),war=activeWarBetween(w,ra,rb),crime=((w.cities?.cities?.[a]?.crimeRate||0)+(w.cities?.cities?.[b]?.crimeRate||0))/200,fa=techEffects(w,ra),fb=techEffects(w,rb),roadTech=(Number(fa.trade||0)+Number(fb.trade||0)+Number(fa.navigation||0)+Number(fb.navigation||0))/2;let cap=(1.8+roadTech*9)*(1-crime*.35)*(war?.22:1)*w.resources.settings.tradeIntensity;if(war)w.resources.stats.warDisruptions++;for(const c of COMMODITIES){const A=market(w,a),B=market(w,b);if(!A||!B)continue;const pa=A.prices[c.id],pb=B.prices[c.id];if(pa<=pb)transfer(w,a,b,c,cap,year,'road');else transfer(w,b,a,c,cap,year,'road')}}}
function seaTrade(w,year){const coasts=(w.settlements||[]).filter(s=>coastal(w,s));if(coasts.length<2)return;for(let i=0;i<coasts.length;i++){const a=coasts[i].id,b=coasts[(i+1+Math.floor(coasts.length/3))%coasts.length].id;if(a===b)continue;const ra=realmId(w,a),rb=realmId(w,b),fa=techEffects(w,ra),fb=techEffects(w,rb),nav=Math.min(Number(fa.navigation||0),Number(fb.navigation||0));if(nav<.035)continue;const war=activeWarBetween(w,ra,rb),cap=(1.2+nav*13)*(war?.18:1)*w.resources.settings.tradeIntensity;for(const c of COMMODITIES){const A=market(w,a),B=market(w,b);if(A.prices[c.id]<=B.prices[c.id])transfer(w,a,b,c,cap,year,'sea');else transfer(w,b,a,c,cap,year,'sea')}}}
function foodMetrics(w,m){let stock=0,annualNeed=0;for(const id of FOOD_IDS){const c=MAP.get(id);stock+=Number(m.inventory[id]||0)*c.food;annualNeed+=demandFor(w,m.settlementId,c)*c.food}const ratio=stock/Math.max(.1,annualNeed),security=clamp(ratio/.78,0,1.35);m.foodSecurity=round(security);m.foodDays=round(clamp(ratio*365,0,999),0);return{ratio,security}}
function pushHistory(w,e){const h=History.initialize(w);h.events.push({id:h.events.length,year:h.currentYear,absoluteYear:absYear(w),...e});return h.events.at(-1)}
function feedbackAndEvents(w,year){const R=w.resources,candidates=[];for(const m of R.markets){refreshPrices(w,m);const f=foodMetrics(w,m),sid=m.settlementId,rid=realmId(w,sid),city=w.cities?.cities?.[sid],pros=w.history?.current?.settlementProsperity?.[sid]??city?.prosperity??.45;const stress=clamp((.62-f.security)/.62,0,1);m.marketStress=round(stress);if(stress>.22){R.stats.shortages++;const delta=stress*.018;w.history.current.settlementProsperity[sid]=round(clamp(Number(pros)-delta,.04,.98),4);if(city){city.priceIndex=round(clamp(Number(city.priceIndex||100)+stress*9,45,320),2);city.unemployment=round(clamp(Number(city.unemployment||.08)+stress*.006,0,.7),4);city.crimeRate=round(clamp(Number(city.crimeRate||0)+stress*1.25,0,100),2)}const rs=w.history?.current?.realmState?.[rid];if(rs)rs.stability=round(clamp(Number(rs.stability??50)-stress*.8,0,100),2)}
 if(f.security<.32)candidates.push({severity:1-f.security,type:'famine',importance:f.security<.18?3:2,sid,rid,title:`Food crisis in ${w.settlements[sid].name}`,text:`Staple reserves fall to roughly ${m.foodDays} days of supply. Prices surge and households ration food.`});
 const worst=COMMODITIES.map(c=>({c,s:Number(m.shortages[c.id]||0)})).sort((a,b)=>b.s-a.s)[0];if(worst&&worst.s>.84&&!worst.c.food)candidates.push({severity:worst.s*.72,type:'commodity_shortage',importance:1,sid,rid,title:`${worst.c.name} shortage at ${w.settlements[sid].name}`,text:`Local stocks of ${worst.c.name.toLowerCase()} are critically low, disrupting trade and production.`,commodityId:worst.c.id})}
 const flows=R.flows.filter(x=>x.year===year),by=new Map();for(const f of flows)by.set(f.from,(by.get(f.from)||0)+f.quantity);for(const [sid,q] of by)if(q>10)candidates.push({severity:Math.min(1,q/45),type:'trade_boom',importance:1,sid,rid:realmId(w,sid),title:`Trade surge through ${w.settlements[sid].name}`,text:'Surplus goods move outward through an unusually active exchange network.'});
 candidates.sort((a,b)=>b.severity-a.severity);for(const e of candidates.slice(0,5)){pushHistory(w,{type:e.type,importance:e.importance,settlementIds:[e.sid],realmIds:e.rid==null?[]:[e.rid],commodityIds:e.commodityId?[e.commodityId]:[],title:e.title,text:e.text});R.shocks.push({year,type:e.type,settlementId:e.sid,realmId:e.rid,commodityId:e.commodityId||null,severity:round(e.severity),title:e.title});if(e.type==='famine')R.stats.famines++;if(e.type==='trade_boom')R.stats.tradeBooms++}
 R.shocks=R.shocks.slice(-R.settings.maxShocks);R.flows=R.flows.slice(-R.settings.maxFlows)}
function commodityTotals(w,id){const R=initialize(w),c=MAP.get(id);if(!c)return null;let stock=0,prod=0,cons=0,imports=0,exports=0,short=0,price=0;for(const m of R.markets){stock+=m.inventory[id]||0;prod+=m.production[id]||0;cons+=m.consumption[id]||0;imports+=m.imports[id]||0;exports+=m.exports[id]||0;short+=m.shortages[id]||0;price+=m.prices[id]||c.basePrice}return{id,name:c.name,stock:round(stock,2),production:round(prod,2),consumption:round(cons,2),imports:round(imports,2),exports:round(exports,2),meanShortage:round(short/Math.max(1,R.markets.length)),meanPrice:round(price/Math.max(1,R.markets.length),2)}}
function recordYear(w,year){const R=w.resources,flows=R.flows.filter(x=>x.year===year);R.annual.push({year,totalStock:round(COMMODITIES.reduce((n,c)=>n+(commodityTotals(w,c.id)?.stock||0),0),2),transported:round(flows.reduce((n,x)=>n+x.quantity,0),2),meanFoodSecurity:round(R.markets.reduce((n,m)=>n+m.foodSecurity,0)/Math.max(1,R.markets.length)),shortageMarkets:R.markets.filter(m=>m.marketStress>.22).length,famines:R.shocks.filter(x=>x.year===year&&x.type==='famine').length});R.currentYear=year;compact(w)}
function compact(w){const R=initialize(w),now=R.currentYear||absYear(w),cut=now-R.settings.retainDetailedYears;if(R.annual.length<=R.settings.retainDetailedYears+80)return R;const old=R.annual.filter(x=>x.year<cut);R.annual=R.annual.filter(x=>x.year>=cut);for(const x of old){const start=Math.floor(x.year/250)*250;let a=R.archives.find(z=>z.startYear===start);if(!a){a={startYear:start,endYear:start+249,years:0,stockSum:0,transported:0,foodSecuritySum:0,shortageMarkets:0,famines:0};R.archives.push(a)}a.years++;a.stockSum+=x.totalStock;a.transported+=x.transported;a.foodSecuritySum+=x.meanFoodSecurity;a.shortageMarkets+=x.shortageMarkets;a.famines+=x.famines;R.stats.archivedYears++}R.archives.sort((a,b)=>a.startYear-b.startYear);if(R.archives.length>220)R.archives=R.archives.slice(-220);return R}
function simulateResourceYear(w,year=absYear(w)){initialize(w);produceConsume(w,year);roadTrade(w,year);seaTrade(w,year);feedbackAndEvents(w,year);recordYear(w,year);return w.resources}
function simulateYears(w,years,options={}){initialize(w);const n=Math.max(0,Math.floor(Number(years)||0));if(!baseSimulator)throw new Error('Resource base simulator unavailable');for(let i=0;i<n;i++){baseSimulator(w,1,options);simulateResourceYear(w,absYear(w))}return w.resources}
function simulateTo(w,target,options={}){const n=Math.max(0,Math.floor(Number(target)||0)-absYear(w));return simulateYears(w,n,options)}
function settlementView(w,sid){const m=market(w,sid);if(!m)return null;return{settlement:w.settlements[sid],realmId:realmId(w,sid),population:population(w,sid),foodSecurity:m.foodSecurity,foodDays:m.foodDays,marketStress:m.marketStress,rows:COMMODITIES.map(c=>({commodity:c,stock:round(m.inventory[c.id]||0,2),price:round(m.prices[c.id]||c.basePrice,2),production:round(m.production[c.id]||0,2),consumption:round(m.consumption[c.id]||0,2),imports:round(m.imports[c.id]||0,2),exports:round(m.exports[c.id]||0,2),shortage:round(m.shortages[c.id]||0)}))}}
function supplyChain(w,id,limit=80){initialize(w);return w.resources.flows.filter(x=>x.commodityId===id).slice(-limit).reverse()}
function summary(w){const R=initialize(w),foods=R.markets.reduce((n,m)=>n+m.foodSecurity,0)/Math.max(1,R.markets.length),prices=COMMODITIES.map(c=>commodityTotals(w,c.id));return{year:R.currentYear,markets:R.markets.length,commodities:COMMODITIES.length,meanFoodSecurity:round(foods),stressedMarkets:R.markets.filter(m=>m.marketStress>.22).length,criticalMarkets:R.markets.filter(m=>m.foodSecurity<.32).length,transported:round(R.stats.transported,1),famines:R.stats.famines,flows:R.flows.length,archives:R.archives.length,highestPrice:prices.sort((a,b)=>b.meanPrice/a.meanPrice-b.meanPrice/a.meanPrice)[0]||null}}
function fingerprint(w){const R=initialize(w),body=R.markets.map(m=>`${m.settlementId}:${m.foodSecurity}:${COMMODITIES.map(c=>round(m.inventory[c.id]||0,1)).join(',')}`).join('|'),flows=R.flows.slice(-120).map(f=>`${f.year}:${f.from}>${f.to}:${f.commodityId}:${round(f.quantity,1)}`).join('|');return hash(`${R.currentYear}|${body}|${flows}|${R.stats.famines}|${R.stats.shortages}|${R.archives.length}`).toString(16).padStart(8,'0')}
function validate(w){const e=[],R=initialize(w);if(R.markets.length!==(w.settlements||[]).length)e.push('market count');for(const m of R.markets){if(m.settlementId<0||m.settlementId>=w.settlements.length)e.push('market settlement');for(const c of COMMODITIES){if(!Number.isFinite(Number(m.inventory[c.id]))||m.inventory[c.id]<0)e.push('inventory');if(!Number.isFinite(Number(m.prices[c.id]))||m.prices[c.id]<=0)e.push('price')}}for(const f of R.flows)if(!MAP.has(f.commodityId)||f.quantity<0)e.push('flow');return[...new Set(e)]}

const api={VERSION,SCHEMA,COMMODITIES,MAP,FOOD_IDS,initialize,setBaseSimulator,absYear,market,commodityTotals,settlementView,supplyChain,simulateResourceYear,simulateYears,simulateTo,compact,summary,fingerprint,validate,suitability};
return api;
});