(function(root,factory){
  const api=factory(
    root&&root.WorldForgeHistory,
    root&&root.WorldForgeSociety,
    root&&root.WorldForgeCity,
    root&&root.WorldForgeCulture,
    root&&root.WorldForgeFactions,
    root&&root.WorldForgeKnowledge,
    root&&root.WorldForgeArtifacts,
    root&&root.WorldForgeCalendar
  );
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeTechnology=api;
})(typeof window!=='undefined'?window:globalThis,function(History,Society,City,Culture,Factions,Knowledge,Artifacts,Calendar){
'use strict';

const VERSION='1.7.0',SCHEMA=1;
const TECHS=[
  {id:'agriculture',name:'Systematic Agriculture',category:'Food',tier:0,cost:18,prereqs:[],effects:{food:.08,population:.02},description:'Crop rotation, seed selection and organized granaries stabilize food production.'},
  {id:'masonry',name:'Masonry & Civic Works',category:'Engineering',tier:0,cost:22,prereqs:[],effects:{stability:.03,artifact:.02},description:'Durable stone construction enables walls, archives, bridges and monumental works.'},
  {id:'writing',name:'Writing & Recordkeeping',category:'Knowledge',tier:0,cost:20,prereqs:[],effects:{knowledge:.08,research:.05},description:'Durable records allow law, administration and scholarship to survive individual memory.'},
  {id:'bronze_working',name:'Bronze Working',category:'Metallurgy',tier:1,cost:34,prereqs:['agriculture'],effects:{military:.05,artifact:.05},description:'Alloy control improves tools, weapons and prestige objects.'},
  {id:'irrigation',name:'Irrigation Networks',category:'Food',tier:1,cost:42,prereqs:['agriculture','masonry'],effects:{food:.12,stability:.02},description:'Canals, cisterns and water management reduce harvest volatility.'},
  {id:'roads',name:'Engineered Roads',category:'Logistics',tier:1,cost:42,prereqs:['masonry'],effects:{trade:.08,diffusion:.06,military:.02},description:'All-weather roads accelerate commerce, armies and the movement of ideas.'},
  {id:'currency',name:'Standard Currency',category:'Finance',tier:1,cost:40,prereqs:['writing'],effects:{trade:.07,stability:.01},description:'Standard coinage reduces transaction friction and enables more complex markets.'},
  {id:'ironworking',name:'Ironworking',category:'Metallurgy',tier:2,cost:60,prereqs:['bronze_working'],effects:{military:.10,artifact:.10,food:.025},description:'Reliable iron tools and weapons reshape agriculture, construction and war.'},
  {id:'medicine',name:'Institutional Medicine',category:'Health',tier:2,cost:62,prereqs:['writing'],effects:{health:.10,population:.04,stability:.015},description:'Recorded diagnosis, surgery and organized care reduce avoidable mortality.'},
  {id:'shipbuilding',name:'Advanced Shipbuilding',category:'Navigation',tier:2,cost:66,prereqs:['roads','bronze_working'],effects:{trade:.10,navigation:.12,diffusion:.05},description:'Larger, more reliable vessels extend trade and political reach across water.'},
  {id:'siege_engineering',name:'Siege Engineering',category:'Military',tier:2,cost:68,prereqs:['masonry','bronze_working'],effects:{military:.12,engineering:.04},description:'Specialized engines, fortification theory and logistics transform major wars.'},
  {id:'banking',name:'Banking & Credit',category:'Finance',tier:3,cost:86,prereqs:['currency','writing'],effects:{trade:.13,research:.025,stability:.015},description:'Credit networks mobilize capital across distance and time.'},
  {id:'navigation',name:'Celestial Navigation',category:'Navigation',tier:3,cost:88,prereqs:['shipbuilding','writing'],effects:{navigation:.16,trade:.08,diffusion:.06},description:'Celestial observations and standardized methods make long-distance voyages repeatable.'},
  {id:'universities',name:'Universities & Scholarly Orders',category:'Knowledge',tier:3,cost:92,prereqs:['writing','masonry'],effects:{research:.14,knowledge:.08,diffusion:.04},description:'Permanent institutions accumulate, criticize and transmit technical knowledge.'},
  {id:'advanced_agriculture',name:'Agronomic Science',category:'Food',tier:3,cost:96,prereqs:['irrigation','ironworking','writing'],effects:{food:.15,population:.03},description:'Measured soils, selective breeding and specialized tools deepen agricultural productivity.'},
  {id:'printing_press',name:'Printing Press',category:'Knowledge',tier:4,cost:118,prereqs:['universities','ironworking'],effects:{knowledge:.22,diffusion:.18,copies:.32,research:.08},description:'Cheap reproducible texts radically accelerate literacy, scholarship and public memory.'},
  {id:'cartography',name:'Scientific Cartography',category:'Navigation',tier:4,cost:112,prereqs:['navigation','universities'],effects:{navigation:.12,trade:.05,diffusion:.05},description:'Measured maps turn accumulated voyages into reusable geographic knowledge.'},
  {id:'public_sanitation',name:'Public Sanitation',category:'Health',tier:4,cost:120,prereqs:['medicine','masonry'],effects:{health:.16,population:.055,stability:.025},description:'Clean water, drainage and waste systems improve survival in dense settlements.'},
  {id:'mechanical_engineering',name:'Mechanical Engineering',category:'Engineering',tier:4,cost:132,prereqs:['ironworking','universities'],effects:{engineering:.16,artifact:.10,trade:.06,food:.03},description:'Precision mechanisms and formal mechanics multiply productive capacity.'},
  {id:'oceanic_navigation',name:'Oceanic Navigation',category:'Navigation',tier:5,cost:158,prereqs:['navigation','cartography','printing_press'],effects:{navigation:.22,trade:.13,diffusion:.10},description:'Open-ocean route planning links distant regions into persistent exchange networks.'}
];
const TECH_MAP=new Map(TECHS.map(t=>[t.id,t]));
const DOMAINS=[
  {id:'agriculture',label:'Agronomic',effect:'food'},
  {id:'metallurgy',label:'Metallurgical',effect:'artifact'},
  {id:'medicine',label:'Medical',effect:'health'},
  {id:'navigation',label:'Navigational',effect:'navigation'},
  {id:'engineering',label:'Mechanical',effect:'engineering'},
  {id:'scholarship',label:'Scholarly',effect:'research'},
  {id:'finance',label:'Financial',effect:'trade'},
  {id:'logistics',label:'Logistical',effect:'diffusion'},
  {id:'governance',label:'Administrative',effect:'stability'}
];
let baseSimulator=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const round=(v,d=4)=>Number(Number(v).toFixed(d));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed);return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function seedOf(w){return w.endless?.baseSeed||String(w.settings?.seed||'WORLD').split('|EPOCH:')[0]}
function keyed(w,year,salt){return rng(`${seedOf(w)}|TECH|${year}|${salt}`)}
function absYear(w){return(w.endless?.epochOffset||0)+Number(w.history?.currentYear||0)}
function setBaseSimulator(fn){if(typeof fn==='function')baseSimulator=fn;return api}
function activeRealmIds(w){return(w.history?.current?.realmState||[]).filter(Boolean).filter(x=>x.active!==false).map(x=>x.id)}
function ensureRealm(w,rid){
 const t=w.technology;let r=t.realms.find(x=>x.realmId===rid);
 if(!r){r={realmId:rid,known:{},progress:{},domainLevels:{},innovationScore:0,nextBreakthroughYear:90+(hash(`${seedOf(w)}|BT0|${rid}`)%91),lastEffectYear:-1};t.realms.push(r)}
 return r;
}
function initialize(w){
 if(!w)throw new Error('World required');History?.initialize?.(w);Society?.initialize?.(w);City?.initialize?.(w);Culture?.initialize?.(w);Factions?.initialize?.(w);Knowledge?.initialize?.(w);Artifacts?.initialize?.(w);Calendar?.initialize?.(w);
 if(!w.technology||w.technology.schemaVersion!==SCHEMA)w.technology={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:absYear(w),realms:[],inventions:[],diffusion:[],breakthroughs:[],archives:[],settings:{maxDiffusion:800,maxBreakthroughs:700,retainDetailedYears:1800,breakthroughBaseGap:115},stats:{discoveries:0,diffusions:0,espionage:0,breakthroughs:0,printedSources:0,artifactsImproved:0}};
 const t=w.technology;t.engineVersion=VERSION;t.realms=t.realms||[];t.inventions=t.inventions||[];t.diffusion=t.diffusion||[];t.breakthroughs=t.breakthroughs||[];t.archives=t.archives||[];t.settings={maxDiffusion:800,maxBreakthroughs:700,retainDetailedYears:1800,breakthroughBaseGap:115,...t.settings};t.stats={discoveries:0,diffusions:0,espionage:0,breakthroughs:0,printedSources:0,artifactsImproved:0,...t.stats};
 const realms=(w.history?.realms||[]).map(x=>x.id);for(const rid of realms)ensureRealm(w,rid);
 if(!t.seeded){for(const r of t.realms)seedFoundations(w,r);t.seeded=true}
 return t;
}
function seedFoundations(w,r){const rr=keyed(w,0,`foundations:${r.realmId}`);for(const id of ['agriculture','writing','masonry']){const adoption=round(.34+rr()*.28,3);r.known[id]={year:0,method:'founding tradition',sourceRealmId:null,adoption}}
 if(rr()>.52)r.known.bronze_working={year:0,method:'founding craft',sourceRealmId:null,adoption:round(.22+rr()*.22,3)}
}
function knows(r,id,min=.01){return Number(r?.known?.[id]?.adoption||0)>=min}
function prereqsMet(r,tech){return tech.prereqs.every(id=>knows(r,id,.28))}
function realmSettlements(w,rid){const own=w.history?.current?.settlementKingdomIds||[];const out=[];for(let i=0;i<own.length;i++)if(own[i]===rid)out.push(i);return out}
function realmProsperity(w,rid){const ids=realmSettlements(w,rid),p=w.history?.current?.settlementProsperity||[];return ids.length?ids.reduce((n,id)=>n+Number(p[id]||.35),0)/ids.length:.3}
function scholarFactor(w,rid){const orgs=w.factions?.organizations||[];let n=0;for(const o of orgs)if(o.active!==false&&(o.realmId===rid||o.homeRealmId===rid)&&/scholar|academy|scribe|university|temple/i.test(`${o.kind||''} ${o.name||''}`))n++;return Math.min(.22,n*.035)}
function contactScore(w,a,b){if(a===b)return 1;const own=w.history?.current?.settlementKingdomIds||[],roads=w.roads||[];let border=0;for(const rd of roads){const ra=own[rd.from],rb=own[rd.to];if((ra===a&&rb===b)||(ra===b&&rb===a)){border=1;break}}
 let war=0;for(const wid of w.history?.current?.activeWarIds||[]){const q=w.history?.wars?.[wid];if(q&&((q.attackerId===a&&q.defenderId===b)||(q.attackerId===b&&q.defenderId===a))){war=1;break}}
 const pa=realmProsperity(w,a),pb=realmProsperity(w,b);return clamp(.05+border*.34+(pa+pb)*.16+war*.10,0,1)}
function effectsForRealm(w,rid){const r=ensureRealm(w,rid),e={food:0,population:0,stability:0,artifact:0,knowledge:0,research:0,trade:0,diffusion:0,military:0,health:0,navigation:0,engineering:0,copies:0};for(const [id,k] of Object.entries(r.known)){const tech=TECH_MAP.get(id);if(!tech)continue;for(const [name,v] of Object.entries(tech.effects||{}))e[name]=(e[name]||0)+v*clamp(Number(k.adoption)||0,0,1)}for(const [domain,level] of Object.entries(r.domainLevels||{})){const d=DOMAINS.find(x=>x.id===domain);if(d)e[d.effect]=(e[d.effect]||0)+Math.log2(1+Number(level||0))*.012}return Object.fromEntries(Object.entries(e).map(([k,v])=>[k,round(v,4)]))}
function pushHistory(w,e){const h=History.initialize(w);h.events.push({id:h.events.length,year:h.currentYear,absoluteYear:absYear(w),...e});return h.events.at(-1)}
function grantTechnology(w,rid,techId,method='research',sourceRealmId=null,year=absYear(w),silent=false){const t=initialize(w),r=ensureRealm(w,rid),tech=TECH_MAP.get(techId);if(!tech)return null;if(r.known[techId])return r.known[techId];const rec={year,method,sourceRealmId,adoption:method==='research'?.18:.12};r.known[techId]=rec;delete r.progress[techId];const inv={id:t.inventions.length,year,realmId:rid,techId,method,sourceRealmId};t.inventions.push(inv);t.stats.discoveries++;if(method!=='research')t.stats.diffusions++;if(method==='espionage')t.stats.espionage++;
 if(!silent){const realm=w.history?.realms?.[rid]?.shortName||`Realm ${rid}`,source=sourceRealmId==null?'independent research':`${w.history?.realms?.[sourceRealmId]?.shortName||`Realm ${sourceRealmId}`} contact`;const ev=pushHistory(w,{type:'technology_discovered',importance:tech.tier>=4?3:tech.tier>=2?2:1,realmIds:[rid,...(sourceRealmId==null?[]:[sourceRealmId])],title:`${realm} adopts ${tech.name}`,text:`${tech.name} enters practical use through ${method}; its immediate origin is ${source}.`,technologyIds:[techId]});Knowledge?.sync?.(w);if(Artifacts?.createArtifact&&tech.tier>=2){const claim=Knowledge?.initialize?.(w)?.claims?.find(c=>c.key===(Knowledge.eventKey?.(w,ev)));Artifacts.createArtifact(w,{kind:tech.category==='Knowledge'?'codex':tech.category==='Navigation'?'map':tech.category==='Metallurgy'?'weapon':'inscription',name:`Prototype Record of ${tech.name}`,createdYear:year,originSettlementId:w.history?.realms?.[rid]?.capitalId??realmSettlements(w,rid)[0]??0,originRealmId:rid,ownerType:'realm',ownerId:rid,claimKeys:claim?[claim.key]:[],refs:[`technology:${techId}`,`realm:${rid}`],prestige:55+tech.tier*7,contents:`Technical record describing ${tech.name}.`})}}
 return rec}
function researchYear(w,rid,year){const r=ensureRealm(w,rid),e=effectsForRealm(w,rid),pros=realmProsperity(w,rid),rr=keyed(w,year,`research:${rid}`),candidates=TECHS.filter(t=>!r.known[t.id]&&prereqsMet(r,t));if(!candidates.length){r.innovationScore+=2+pros*2+e.research*4;return}
 candidates.sort((a,b)=>a.tier-b.tier||a.cost-b.cost||a.id.localeCompare(b.id));const frontier=candidates.filter(x=>x.tier===candidates[0].tier);const tech=frontier[Math.floor(rr()*frontier.length)],points=3.8+pros*4.5+scholarFactor(w,rid)*8+e.research*6+(rr()-.5)*1.4;r.progress[tech.id]=round((r.progress[tech.id]||0)+Math.max(1,points),3);if(r.progress[tech.id]>=tech.cost)grantTechnology(w,rid,tech.id,'research',null,year)}
function adoptionYear(w,rid){const r=ensureRealm(w,rid),pros=realmProsperity(w,rid),e=effectsForRealm(w,rid);for(const k of Object.values(r.known)){const rate=.012+pros*.010+e.diffusion*.015;k.adoption=round(clamp(Number(k.adoption||0)+rate*(1-Number(k.adoption||0)),0,1),4)}}
function diffuseYear(w,year){const ids=activeRealmIds(w),t=initialize(w);for(const target of ids){const tr=ensureRealm(w,target);for(const tech of TECHS){if(tr.known[tech.id]||!prereqsMet(tr,tech))continue;let best=null;for(const src of ids){if(src===target)continue;const sr=ensureRealm(w,src);if(!knows(sr,tech.id,.48))continue;const contact=contactScore(w,target,src),score=contact*sr.known[tech.id].adoption*(1+effectsForRealm(w,src).diffusion);if(!best||score>best.score)best={src,score,contact}}if(!best)continue;const rr=keyed(w,year,`diffuse:${target}:${best.src}:${tech.id}`),war=best.contact>.45&&(w.history?.current?.activeWarIds||[]).some(wid=>{const q=w.history?.wars?.[wid];return q&&((q.attackerId===target&&q.defenderId===best.src)||(q.defenderId===target&&q.attackerId===best.src))}),chance=clamp(.006+best.score*.055+effectsForRealm(w,target).diffusion*.02,0,.16);if(rr()<chance){const method=war&&rr()<.42?'espionage':best.contact>.38?'trade':'scholarship';grantTechnology(w,target,tech.id,method,best.src,year);t.diffusion.push({id:t.diffusion.length,year,techId:tech.id,fromRealmId:best.src,toRealmId:target,method});if(t.diffusion.length>t.settings.maxDiffusion)t.diffusion=t.diffusion.slice(-t.settings.maxDiffusion)}}}}
function ordinal(n){const s=['th','st','nd','rd'],v=n%100;return`${n}${s[(v-20)%10]||s[v]||s[0]}`}
function createBreakthrough(w,rid,domainId=null,year=absYear(w)){const t=initialize(w),r=ensureRealm(w,rid),rr=keyed(w,year,`breakthrough:${rid}:${t.stats.breakthroughs}`),domain=DOMAINS.find(x=>x.id===domainId)||DOMAINS[Math.floor(rr()*DOMAINS.length)],level=(r.domainLevels[domain.id]||0)+1;r.domainLevels[domain.id]=level;const b={id:t.stats.breakthroughs,year,realmId:rid,domain:domain.id,level,name:`${domain.label} Synthesis ${ordinal(level)}`,effect:domain.effect,magnitude:round(.012/Math.sqrt(level),4)};t.breakthroughs.push(b);t.stats.breakthroughs++;r.innovationScore=0;r.nextBreakthroughYear=year+t.settings.breakthroughBaseGap+35+Math.floor(rr()*145)+Math.floor(level*2.5);pushHistory(w,{type:'technology_breakthrough',importance:level%5===0?2:1,realmIds:[rid],title:b.name,text:`Researchers in ${w.history?.realms?.[rid]?.shortName||`Realm ${rid}`} establish a new ${domain.id} practice beyond the finite foundational technology tree.`,technologyIds:[`breakthrough:${b.id}`]});compact(w);return b}
function maybeBreakthrough(w,rid,year){const r=ensureRealm(w,rid),core=Object.keys(r.known).length,progress=Object.values(r.progress).reduce((a,b)=>a+Number(b||0),0),maturity=core/TECHS.length;r.innovationScore+=.8+maturity*1.8+Math.min(2,progress/250)+effectsForRealm(w,rid).research*2;if(year>=r.nextBreakthroughYear&&(maturity>.45||year>600))return createBreakthrough(w,rid,null,year);return null}
function improveArtifacts(w,year){if(!Artifacts?.initialize)return;const a=Artifacts.initialize(w);for(const item of a.items||[]){if(item.createdYear!==year||item.techAdjustedYear===year)continue;const rid=item.originRealmId;if(rid==null)continue;const e=effectsForRealm(w,rid),boost=clamp(e.artifact*.10+e.engineering*.05,0,.09);if(boost>0){item.durability=round(clamp(item.durability+boost,0,1),3);item.condition=round(clamp(item.condition+boost*.7,0,1),3);item.prestige=round(clamp(item.prestige+boost*45,1,100),1);item.techAdjustedYear=year;a.stats.artifactsImproved=(a.stats.artifactsImproved||0)+1;touchedStat(w,'artifactsImproved')}}}
function touchedStat(w,name){const t=initialize(w);t.stats[name]=(t.stats[name]||0)+1}
function spreadPrintedKnowledge(w,year){if(!Artifacts||!Knowledge)return;const t=initialize(w),items=Artifacts.initialize(w).items||[],ids=activeRealmIds(w);for(const rid of ids){const r=ensureRealm(w,rid),print=r.known.printing_press;if(!print||print.adoption<.35)continue;const rr=keyed(w,year,`print:${rid}`),candidates=items.filter(x=>x.written&&x.status!=='destroyed'&&x.claimKeys?.length&&x.createdYear<=year);if(!candidates.length)continue;const attempts=print.adoption>.72?2:1;for(let i=0;i<attempts;i++){if(rr()>.13+print.adoption*.16)continue;const item=candidates[Math.floor(rr()*candidates.length)],key=item.claimKeys[Math.floor(rr()*item.claimKeys.length)],claim=Knowledge.initialize(w).claims.find(c=>c.key===key);if(!claim)continue;const existing=Knowledge.initialize(w).sources.some(s=>s.claimKey===key&&s.printedByRealmId===rid&&year-s.createdYear<35);if(existing)continue;const s=Knowledge.addSource(w,key,{kind:'scholar',originRealmId:rid,originSettlementId:w.history?.realms?.[rid]?.capitalId??0,createdYear:year,reliability:clamp(item.authenticity*.82,.4,.94),archiveStrength:.86,text:`A printed edition circulating in ${w.history?.realms?.[rid]?.shortName||`Realm ${rid}`} reproduces evidence from ${item.name}.`});s.printedByRealmId=rid;s.artifactId=item.id;s.technologyId='printing_press';t.stats.printedSources++;item.copies=Math.min(item.copies+Math.max(1,Math.round(2+item.copies*.04*print.adoption)),Artifacts.initialize(w).settings.maxCirculation||5000);if(!item.circulationRealms.includes(rid))item.circulationRealms.push(rid)}}}
function applyWorldEffects(w,year){const h=History.initialize(w),ids=activeRealmIds(w),allEffects=ids.map(rid=>[rid,effectsForRealm(w,rid)]),effectMap=new Map(allEffects);for(let sid=0;sid<(w.settlements?.length||0);sid++){const rid=h.current.settlementKingdomIds[sid],e=effectMap.get(rid);if(!e)continue;const p=h.current.settlementProsperity[sid]??.4;h.current.settlementProsperity[sid]=round(clamp(p+.00055*(e.food+e.trade+e.engineering),.04,.99),4);const pop=h.current.settlementPopulation[sid];if(Number.isFinite(pop)){const growth=clamp((e.health+e.population)*.00005,0,.000025);h.current.settlementPopulation[sid]=Math.max(20,Math.round(pop*(1+growth)))}const city=w.cities?.cities?.[sid];if(city){city.priceIndex=round(clamp((city.priceIndex||100)-e.food*.025-e.trade*.02,45,260),2);city.prosperity=round(clamp((city.prosperity??p)+.00035*(e.trade+e.engineering),.04,.99),4)}}for(const [rid,e] of allEffects){const realm=h.current.realmState[rid];if(realm)realm.stability=round(clamp((realm.stability??50)+.006*(e.stability+e.health),0,100),2)}const avgTrade=allEffects.length?allEffects.reduce((n,[,e])=>n+e.trade,0)/allEffects.length:0;if(avgTrade>0)h.current.tradeVolumes=h.current.tradeVolumes.map(v=>round(Number(v||0)*(1+Math.min(.00022,avgTrade*.00008)),2));improveArtifacts(w,year);spreadPrintedKnowledge(w,year)}
function techAge(w){const ids=activeRealmIds(w),known=ids.flatMap(rid=>Object.keys(ensureRealm(w,rid).known));const maxTier=known.length?Math.max(...known.map(id=>TECH_MAP.get(id)?.tier||0)):0;const labels=['Founding Crafts','Early Civic Age','Iron & Institutional Age','Scholastic Age','Print & Mechanical Age','Oceanic Age'];const coreCoverage=ids.length?ids.reduce((n,rid)=>n+Object.keys(ensureRealm(w,rid).known).length/TECHS.length,0)/ids.length:0;if(coreCoverage>.96&&(initialize(w).breakthroughs.length>0))return'Open Innovation Age';return labels[Math.min(maxTier,labels.length-1)]}
function simulateTechnologyYear(w,year=absYear(w)){const t=initialize(w);t.currentYear=year;const ids=activeRealmIds(w);for(const rid of ids){adoptionYear(w,rid);researchYear(w,rid,year)}diffuseYear(w,year);for(const rid of ids)maybeBreakthrough(w,rid,year);applyWorldEffects(w,year);compact(w);return t}
function simulateYears(w,years,options={}){initialize(w);const n=Math.max(0,Math.floor(Number(years)||0));if(!baseSimulator)throw new Error('Technology base simulator unavailable');for(let i=0;i<n;i++){baseSimulator(w,1,options);simulateTechnologyYear(w,absYear(w))}return w.technology}
function simulateTo(w,target,options={}){const y=absYear(w),n=Math.max(0,Math.floor(Number(target)||0)-y);return simulateYears(w,n,options)}
function compact(w){const t=initialize(w),now=absYear(w),cut=now-t.settings.retainDetailedYears;if(t.breakthroughs.length>t.settings.maxBreakthroughs||t.breakthroughs.some(x=>x.year<cut)){const keep=[],old=[];for(const b of t.breakthroughs)((b.year<cut)||(t.breakthroughs.length-old.length>t.settings.maxBreakthroughs&&b.year<now-400)?old:keep).push(b);if(old.length){for(const b of old){const start=Math.floor(b.year/250)*250;let a=t.archives.find(x=>x.startYear===start);if(!a){a={startYear:start,endYear:start+249,breakthroughs:0,domains:{},notable:[]};t.archives.push(a)}a.breakthroughs++;a.domains[b.domain]=(a.domains[b.domain]||0)+1;if(b.level%5===0&&a.notable.length<12)a.notable.push({year:b.year,name:b.name,realmId:b.realmId,domain:b.domain})}t.breakthroughs=keep}}
 t.diffusion=t.diffusion.filter(x=>x.year>=cut).slice(-t.settings.maxDiffusion);t.inventions=t.inventions.filter(x=>x.year>=cut||TECH_MAP.get(x.techId)?.tier>=4).slice(-1600);t.archives.sort((a,b)=>a.startYear-b.startYear);if(t.archives.length>240)t.archives=t.archives.slice(-240)}
function realmView(w,rid){initialize(w);const r=ensureRealm(w,rid),rows=TECHS.map(tech=>({tech,known:r.known[tech.id]||null,progress:r.progress[tech.id]||0,unlocked:prereqsMet(r,tech)}));return{realmId:rid,name:w.history?.realms?.[rid]?.shortName||`Realm ${rid}`,age:techAge(w),effects:effectsForRealm(w,rid),rows,domainLevels:{...r.domainLevels},innovationScore:round(r.innovationScore,2),nextBreakthroughYear:r.nextBreakthroughYear}}
function summary(w){const t=initialize(w),ids=activeRealmIds(w),known=ids.reduce((n,rid)=>n+Object.keys(ensureRealm(w,rid).known).length,0),adoptions=[];for(const rid of ids)for(const k of Object.values(ensureRealm(w,rid).known))adoptions.push(Number(k.adoption||0));return{year:absYear(w),realms:ids.length,known,unique:new Set(ids.flatMap(rid=>Object.keys(ensureRealm(w,rid).known))).size,meanAdoption:round(adoptions.length?adoptions.reduce((a,b)=>a+b,0)/adoptions.length:0,3),discoveries:t.stats.discoveries,diffusions:t.stats.diffusions,breakthroughs:t.stats.breakthroughs,printedSources:t.stats.printedSources,age:techAge(w),archives:t.archives.length}}
function technologyArticle(w,techId){const tech=TECH_MAP.get(techId);if(!tech)return null;const t=initialize(w),realms=t.realms.filter(r=>r.known[techId]).map(r=>({realmId:r.realmId,...r.known[techId]})).sort((a,b)=>a.year-b.year);return{tech,realms,first:realms[0]||null,spread:realms.length}}
function fingerprint(w){const t=initialize(w);let h=2166136261>>>0;const raw=[t.currentYear,t.realms.map(r=>`${r.realmId}:${Object.entries(r.known).sort().map(([id,x])=>`${id}@${x.year}:${round(x.adoption,3)}`).join(',')}:${Object.entries(r.domainLevels).sort().map(([d,l])=>`${d}${l}`).join(',')}`).join('|'),t.breakthroughs.slice(-180).map(b=>`${b.year}:${b.realmId}:${b.domain}:${b.level}`).join('|'),t.archives.map(a=>`${a.startYear}:${a.breakthroughs}`).join('|')].join('||');for(const c of raw){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function validate(w){const t=w?.technology;if(!t||t.schemaVersion!==SCHEMA)return['technology schema'];const errors=[];for(const r of t.realms){if(!Number.isInteger(r.realmId))errors.push('technology realm id');for(const [id,k] of Object.entries(r.known||{})){if(!TECH_MAP.has(id))errors.push('unknown technology id');if(!(k.adoption>=0&&k.adoption<=1))errors.push('technology adoption')}}for(const b of t.breakthroughs)if(!DOMAINS.some(d=>d.id===b.domain)||b.level<1)errors.push('invalid breakthrough');return[...new Set(errors)]}
const api={VERSION,SCHEMA,TECHS,TECH_MAP,DOMAINS,initialize,setBaseSimulator,grantTechnology,createBreakthrough,effectsForRealm,simulateTechnologyYear,simulateYears,simulateTo,realmView,summary,technologyArticle,compact,fingerprint,validate,absYear,contactScore};
return api;
});