(function(root,factory){
  const api=factory(root&&root.WorldForgeHeritage,root&&root.WorldForgeWorldbuilding);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeTourism=api;
})(typeof window!=='undefined'?window:globalThis,function(Heritage,Worldbuilding){
'use strict';
if(!Heritage||!Worldbuilding)throw new Error('WorldForge v4.4 Tourism requires Heritage and Worldbuilding');
const VERSION='4.4.0',SCHEMA=1;
const DESTINATION_TYPES=Object.freeze(['heritage','museum','pilgrimage','festival','mixed']);
const ROUTE_TYPES=Object.freeze(['heritage_circuit','pilgrimage_route','museum_route','festival_route']);
const PRESSURE_STATES=Object.freeze(['low','balanced','busy','overtourism']);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=4)=>Number(Number(v).toFixed(d));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function year(world){return Worldbuilding.absYear(world)}
function settlement(world,sid){return world.settlements?.[Number(sid)]||null}
function realmId(world,sid){const s=settlement(world,sid);return Number.isInteger(s?.kingdomId)?s.kingdomId:(Number.isInteger(world.history?.current?.settlementKingdomIds?.[Number(sid)])?world.history.current.settlementKingdomIds[Number(sid)]:null)}
function realmName(world,rid){return Number.isInteger(rid)?(world.kingdoms?.[rid]?.name||`Realm ${rid}`):'Unaligned'}
function state(world){
 if(!world.tourism||world.tourism.schemaVersion!==SCHEMA)world.tourism={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:year(world),destinations:[],routes:[],festivals:[],accommodation:[],incidents:[],annual:[],revision:0,lastAppliedYear:null,settings:{maxDestinations:36,maxRoutes:14,maxFestivals:18,maxIncidents:28},stats:{destinations:0,annualVisitors:0,pilgrims:0,tourismRevenue:0,localIncome:0,conservationShare:0,overnightCapacity:0,festivals:0,routes:0,overtourismSites:0,incidents:0}};
 const T=world.tourism;T.engineVersion=VERSION;T.destinations=T.destinations||[];T.routes=T.routes||[];T.festivals=T.festivals||[];T.accommodation=T.accommodation||[];T.incidents=T.incidents||[];T.annual=T.annual||[];T.revision=Number(T.revision||0);T.settings={maxDestinations:36,maxRoutes:14,maxFestivals:18,maxIncidents:28,...T.settings};return T
}
function statusWeight(s){return{unlisted:.2,local_register:.38,protected:.58,national_heritage:.78,world_heritage:1}[s]||.2}
function destinationType(site,museums,relics,h){const sacred=/temple|shrine|sanct|cathedral|monastery|mosque|church|pilgrim|sacred/i.test(String(site.name||'')+' '+String(site.details?.siteType||''));const museum=museums.length>0,star=relics.some(r=>r.significance>.78);if(sacred&&museum)return'mixed';if(sacred)return'pilgrimage';if(museum&&star)return'mixed';if(museum)return'museum';return h%5===0?'festival':'heritage'}
function buildDestinations(world){Heritage.initialize(world);const H=world.heritage||{},museums=H.museums||[],relics=H.relics||[],out=[];for(const site of H.registrySites||[]){const h=hash(`${world.seed||world.name}|tourism|${site.id}|${year(world)}`),sid=Number(site.settlementId),s=settlement(world,sid),localMuseums=museums.filter(m=>m.settlementId===sid),localRelics=relics.filter(r=>r.settlementId===sid||r.currentHolder?.id&&localMuseums.some(m=>m.id===r.currentHolder.id)),type=destinationType(site,localMuseums,localRelics,h),access=site.publicAccess?1:.45,prestige=clamp(statusWeight(site.status)*.5+site.score*.28+(localMuseums[0]?.prestige||0)*.14+Math.min(.12,localRelics.filter(r=>r.onDisplay).length*.02),0,1),conflictPenalty=(world.history?.events||[]).slice(-80).some(e=>(e.settlementId===sid||e.settlementIds?.includes?.(sid))&&/war|battle|siege|raid|plague|epidemic/i.test(String(e.type||'')+' '+String(e.title||'')))?.35:0,attractiveness=round(clamp(prestige*.72+access*.18+((h>>>8)%12)/100-conflictPenalty,0,1),3),base=Math.max(40,Math.round((s?.population||world.history?.current?.settlementPopulation?.[sid]||800)*(.025+attractiveness*.16))),visitors=Math.round(base*(.72+((h>>>14)%55)/100)),pilgrimShare=type==='pilgrimage'?.62:type==='mixed'?.28:.03,pilgrims=Math.round(visitors*pilgrimShare),daySpend=8+Math.round(24*attractiveness)+(type==='museum'?6:0),overnightShare=clamp(.18+attractiveness*.45+(type==='pilgrimage'?.1:0),.1,.78),revenue=Math.round(visitors*daySpend*(.75+overnightShare*.65)),capacity=Math.max(100,Math.round(base*(1.05+(s?.capital?.9:0)+(localMuseums.length?.35:0)))),pressure=visitors/Math.max(1,capacity),pressureState=pressure>1.45?'overtourism':pressure>1.05?'busy':pressure>.58?'balanced':'low',conservationShare=Math.round(revenue*(site.status==='world_heritage'?.13:site.status==='national_heritage'?.1:.06)),localIncome=Math.round(revenue*.64),residentSentiment=round(clamp(.68+localIncome/Math.max(1,(s?.population||800)*45)-Math.max(0,pressure-1)*.32-site.conservationRisk*.08,0,1),3);out.push({id:`destination:${site.id}`,heritageSiteId:site.id,archaeologySiteId:site.archaeologySiteId,settlementId:sid,realmId:site.realmId,name:site.name,type,status:site.status,attractiveness,annualVisitors:visitors,pilgrims,visitorSpend:daySpend,revenue,localIncome,conservationShare,capacity,pressure:round(pressure,3),pressureState,residentSentiment,overnightShare:round(overnightShare,3),museumIds:localMuseums.map(m=>m.id),featuredRelicIds:localRelics.sort((a,b)=>b.significance-a.significance).slice(0,4).map(r=>r.id)})}out.sort((a,b)=>b.annualVisitors-a.annualVisitors||String(a.id).localeCompare(String(b.id)));return out.slice(0,state(world).settings.maxDestinations)}
function buildAccommodation(world,destinations){const by=new Map;for(const d of destinations){if(!by.has(d.settlementId))by.set(d.settlementId,[]);by.get(d.settlementId).push(d)}return[...by.entries()].map(([sid,ds])=>{const s=settlement(world,sid),h=hash(`${world.seed||world.name}|lodging|${sid}`),vis=ds.reduce((a,d)=>a+d.annualVisitors,0),need=Math.max(12,Math.round(vis/115)),inns=Math.max(1,Math.round(need/28)),beds=inns*(24+(h%17))+(s?.capital?80:0),occupancy=round(clamp((vis*ds.reduce((a,d)=>a+d.overnightShare,0)/Math.max(1,ds.length))/Math.max(1,beds*220),.08,.97),3),jobs=Math.max(2,Math.round(beds*.24+vis/900)),revenue=Math.round(vis*(6+occupancy*13));return{id:`accommodation:${sid}`,settlementId:Number(sid),realmId:realmId(world,sid),inns,beds,occupancy,jobs,revenue,pressure:occupancy>.88?'strained':occupancy>.65?'busy':'available'}})}
function buildFestivals(world,destinations){return destinations.filter(d=>d.attractiveness>.48).slice(0,state(world).settings.maxFestivals).map((d,i)=>{const h=hash(`${world.seed||world.name}|festival|${d.id}`),religious=d.type==='pilgrimage'||d.type==='mixed'&&h%2===0,attendance=Math.round(d.annualVisitors*(.08+((h>>>9)%18)/100)),season=1+(h%4),economicLift=Math.round(attendance*(5+(h%11))),crowdRisk=round(clamp(attendance/Math.max(100,d.capacity)*.62,0,1),3);return{id:`festival:${d.id}`,destinationId:d.id,settlementId:d.settlementId,realmId:d.realmId,name:religious?`${d.name} Pilgrimage Feast`:`${d.name} Heritage Festival`,kind:religious?'pilgrimage_feast':'heritage_festival',season,attendance,economicLift,crowdRisk,publicSupport:round(clamp(.58+d.residentSentiment*.35-crowdRisk*.15,0,1),3)}})}
function buildRoutes(world,destinations){const groups=new Map;for(const d of destinations){const key=d.realmId??-1;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(d)}const out=[];for(const [rid,ds0] of groups){const ds=[...ds0].sort((a,b)=>b.attractiveness-a.attractiveness);if(ds.length<2)continue;const count=Math.min(3,Math.ceil(ds.length/4));for(let i=0;i<count;i++){const picks=ds.slice(i*3,i*3+4);if(picks.length<2)continue;const pilgrim=picks.filter(x=>x.type==='pilgrimage'||x.type==='mixed').length>=2,type=pilgrim?'pilgrimage_route':picks.some(x=>x.type==='museum')?'museum_route':'heritage_circuit',h=hash(`${world.seed||world.name}|route|${rid}|${i}`),visitors=Math.round(picks.reduce((a,d)=>a+d.annualVisitors,0)*(.12+((h>>>8)%16)/100));out.push({id:`tour-route:${rid}:${i}`,realmId:Number(rid),realmName:realmName(world,Number(rid)),name:pilgrim?`${realmName(world,Number(rid))} Pilgrimage Way`:`${realmName(world,Number(rid))} Cultural Circuit`,type,destinationIds:picks.map(p=>p.id),settlementIds:[...new Set(picks.map(p=>p.settlementId))],annualTravelers:visitors,routeRevenue:Math.round(visitors*(7+h%14)),seasonality:round(.25+((h>>>14)%55)/100,2)})}}return out.sort((a,b)=>b.annualTravelers-a.annualTravelers).slice(0,state(world).settings.maxRoutes)}
function buildIncidents(world,destinations,festivals){const out=[];for(const d of destinations){const h=hash(`${world.seed||world.name}|tourism-incident|${d.id}|${year(world)}`);if(d.pressureState==='overtourism'||d.pressureState==='busy'&&h%5===0){const vandal=h%4===0,type=vandal?'vandalism':'crowding',severity=round(clamp((d.pressure-1)*.48+((h>>>12)%25)/100,.1,.95),3);out.push({id:`tourism-incident:${d.id}:${year(world)}`,destinationId:d.id,settlementId:d.settlementId,year:year(world),type,severity,description:vandal?`Visitor pressure caused damage concerns at ${d.name}.`:`Crowding strained access, lodging and conservation capacity at ${d.name}.`,resolved:severity<.55})}}
 for(const f of festivals){if(f.crowdRisk>.62)out.push({id:`festival-incident:${f.id}:${year(world)}`,destinationId:f.destinationId,settlementId:f.settlementId,year:year(world),type:'festival_crowding',severity:f.crowdRisk,description:`Peak attendance at ${f.name} exceeded comfortable local capacity.`,resolved:false})}return out.slice(0,state(world).settings.maxIncidents)}
function refreshStats(world){const T=state(world),sum=k=>T.destinations.reduce((a,d)=>a+Number(d[k]||0),0),acc=(T.accommodation||[]).reduce((a,x)=>a+Number(x.beds||0),0);T.stats={destinations:T.destinations.length,annualVisitors:sum('annualVisitors'),pilgrims:sum('pilgrims'),tourismRevenue:sum('revenue')+(T.festivals||[]).reduce((a,x)=>a+x.economicLift,0)+(T.routes||[]).reduce((a,x)=>a+x.routeRevenue,0),localIncome:sum('localIncome'),conservationShare:sum('conservationShare'),overnightCapacity:acc,festivals:T.festivals.length,routes:T.routes.length,overtourismSites:T.destinations.filter(d=>d.pressureState==='overtourism').length,incidents:T.incidents.length};return T.stats}
function rebuild(world,force=false){const T=state(world),y=year(world);if(!force&&T.lastAppliedYear===y&&T.destinations.length)return T;Heritage.initialize(world);T.currentYear=y;T.destinations=buildDestinations(world);T.accommodation=buildAccommodation(world,T.destinations);T.festivals=buildFestivals(world,T.destinations);T.routes=buildRoutes(world,T.destinations);T.incidents=buildIncidents(world,T.destinations,T.festivals);refreshStats(world);T.annual=(T.annual||[]).filter(x=>x.year!==y);T.annual.push({year:y,...T.stats});T.annual=T.annual.slice(-160);T.lastAppliedYear=y;T.revision++;return T}
function settlementView(world,sid){rebuild(world);const T=state(world),id=Number(sid);return{destinations:T.destinations.filter(x=>x.settlementId===id),accommodation:T.accommodation.filter(x=>x.settlementId===id),festivals:T.festivals.filter(x=>x.settlementId===id),routes:T.routes.filter(x=>x.settlementIds.includes(id)),incidents:T.incidents.filter(x=>x.settlementId===id)}}
function summary(world){rebuild(world);return{year:state(world).currentYear,revision:state(world).revision,...state(world).stats}}
function fingerprint(world){rebuild(world);const T=state(world),src=JSON.stringify([T.currentYear,T.destinations.map(d=>[d.id,d.annualVisitors,d.pilgrims,d.revenue,d.pressureState]),T.routes.map(r=>[r.id,r.annualTravelers]),T.festivals.map(f=>[f.id,f.attendance]),T.accommodation.map(a=>[a.id,a.beds,a.occupancy]),T.incidents.map(i=>[i.id,i.type,i.severity])]);return hash(src).toString(16).padStart(8,'0')}
function validate(world){const T=state(world),e=[];if(T.engineVersion!==VERSION)e.push('tourism engine version mismatch');if(T.destinations.some(d=>!PRESSURE_STATES.includes(d.pressureState)))e.push('invalid tourism pressure state');if(T.routes.some(r=>!ROUTE_TYPES.includes(r.type)))e.push('invalid tourism route type');if(T.destinations.some(d=>d.annualVisitors<0||d.revenue<0||d.capacity<=0))e.push('invalid destination economics');return e}
function initialize(world,force=false){const T=rebuild(world,force);return T}
function simulateTourismYear(world,y){if(Number.isFinite(y)&&y!==year(world))state(world).lastAppliedYear=null;return rebuild(world,false)}
const baseSettlementView=Worldbuilding.settlementView.bind(Worldbuilding);Worldbuilding.settlementView=function(world,sid){const v=baseSettlementView(world,sid);try{v.tourism=settlementView(world,sid)}catch(_){}return v};Worldbuilding.TOURISM_VERSION=VERSION;Worldbuilding.__tourismBridge=true;
return{VERSION,SCHEMA,DESTINATION_TYPES,ROUTE_TYPES,PRESSURE_STATES,initialize,simulateTourismYear,settlementView,summary,fingerprint,validate,buildDestinations,buildRoutes,buildFestivals,buildAccommodation};
});