(function(root,factory){
  const api=factory(root&&root.WorldForgeHistory,root&&root.WorldForgeResources,root&&root.WorldForgeInstitutions,root&&root.WorldForgeMilitary,root&&root.WorldForgeCity);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeTreasury=api;
})(typeof window!=='undefined'?window:globalThis,function(History,Resources,Institutions,Military,City){
'use strict';
const VERSION='2.1.0',SCHEMA=1,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
let baseSimulator=null;
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed);return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function seedOf(w){return w.endless?.baseSeed||String(w.settings?.seed||'WORLD').split('|EPOCH:')[0]}
function keyed(w,y,s){return rng(`${seedOf(w)}|TREASURY|${y}|${s}`)}
function absYear(w){return(w.endless?.epochOffset||0)+Number(w.history?.currentYear||0)}
function setBaseSimulator(fn){if(typeof fn==='function')baseSimulator=fn;return api}
function owner(w,sid){return w.history?.current?.settlementKingdomIds?.[sid]??w.settlements?.[sid]?.kingdomId??null}
function realmState(w,rid){return w.history?.current?.realmState?.[rid]||null}
function realmName(w,rid){return w.history?.realms?.[rid]?.shortName||`Realm ${rid}`}
function settlements(w,rid){const out=[];for(let i=0;i<(w.settlements?.length||0);i++)if(owner(w,i)===rid)out.push(i);return out}
function activeWar(w,rid){return(w.history?.current?.activeWarIds||[]).some(id=>{const q=w.history.wars?.[id];return q&&q.endYear==null&&(q.attackerId===rid||q.defenderId===rid)})}
function pushHistory(w,e){const h=History.initialize(w);h.events.push({id:h.events.length,year:h.currentYear,absoluteYear:absYear(w),...e});return h.events.at(-1)}
function state(w){if(!w.treasury||w.treasury.schemaVersion!==SCHEMA)w.treasury={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:absYear(w),nextDebtId:1,realms:[],instruments:[],annual:[],archives:[],settings:{retainDetailedYears:1200,maxAnnualRows:6000},stats:{taxCollected:0,tariffsCollected:0,warSpending:0,interestPaid:0,debtIssued:0,debtRepaid:0,defaults:0,debasements:0,inflationCrises:0,archivedYears:0}};const T=w.treasury;T.engineVersion=VERSION;T.nextDebtId=T.nextDebtId||1;T.realms=T.realms||[];T.instruments=T.instruments||[];T.annual=T.annual||[];T.archives=T.archives||[];T.settings={retainDetailedYears:1200,maxAnnualRows:6000,...T.settings};T.stats={taxCollected:0,tariffsCollected:0,warSpending:0,interestPaid:0,debtIssued:0,debtRepaid:0,defaults:0,debasements:0,inflationCrises:0,archivedYears:0,...T.stats};return T}
function account(w,rid,create=true){const T=state(w);let a=T.realms.find(x=>x.realmId===rid);if(!a&&create){const rs=realmState(w,rid)||{},start=Math.max(25,Number(rs.treasury||0)*2+50);a={realmId:rid,treasury:round(start,2),debt:0,taxRate:.11,tariffRate:.05,warSurcharge:.035,interestRate:.035,inflation:.02,debasement:0,coinValue:1,credit:78,moneySupply:round(start*3,2),lastRevenue:0,lastExpense:0,lastBalance:0,warCost:0,defaults:0,consecutiveDeficit:0,lastYear:absYear(w)};T.realms.push(a)}return a||null}
function syncRealms(w){for(const rs of w.history?.current?.realmState||[])if(rs)account(w,rs.id,true)}
function initialize(w){if(!w)throw new Error('World required');History?.initialize?.(w);Resources?.initialize?.(w);Institutions?.initialize?.(w);Military?.initialize?.(w);const T=state(w);syncRealms(w);T.currentYear=absYear(w);return T}
function realmTrade(w,rid){let v=0;for(let i=0;i<(w.roads?.length||0);i++){const r=w.roads[i],a=owner(w,r.from),b=owner(w,r.to);if(a===b)continue;if(a===rid||b===rid)v+=Number(w.history?.current?.tradeVolumes?.[i]||0)}return v}
function realmEconomy(w,rid){const ids=settlements(w,rid);let pop=0,wealth=0,pros=0;for(const sid of ids){pop+=Number(w.history?.current?.settlementPopulation?.[sid]||0);wealth+=Number(w.history?.current?.settlementWealth?.[sid]||0);pros+=Number(w.history?.current?.settlementProsperity?.[sid]||0)}return{ids,pop,wealth,prosperity:ids.length?pros/ids.length:0,trade:realmTrade(w,rid)}}
function forces(w,rid){const armies=(w.military?.armies||[]).filter(x=>x.realmId===rid&&x.status==='active'),fleets=(w.military?.fleets||[]).filter(x=>x.realmId===rid&&x.status==='active');return{armies,fleets,manpower:armies.reduce((n,x)=>n+Number(x.size||0),0),hulls:fleets.reduce((n,x)=>n+Number(x.hulls||0),0),supplyGap:armies.reduce((n,x)=>n+Number(x.size||0)*(1-Number(x.supply||0)),0)}}
function issueDebt(w,a,amount,year,war){const T=initialize(w),q=round(Math.max(0,amount),2);if(q<=0)return null;const lenders=['Merchant Houses','Temple Treasuries','Guild Banks','Provincial Notables','Foreign Creditors'],r=keyed(w,year,`debt:${a.realmId}:${T.nextDebtId}`),d={id:T.nextDebtId++,realmId:a.realmId,type:war?'war_bond':'bank_loan',lender:lenders[Math.floor(r()*lenders.length)],principal:q,issuedPrincipal:q,rate:round(a.interestRate,4),issuedYear:year,maturityYear:year+(war?10:7)+Math.floor(r()*9),status:'active',repaid:0};T.instruments.push(d);a.debt=round(a.debt+q,2);a.treasury=round(a.treasury+q,2);T.stats.debtIssued=round(T.stats.debtIssued+q,2);pushHistory(w,{type:'debt_issued',importance:war?2:1,realmIds:[a.realmId],title:`${realmName(w,a.realmId)} issues ${war?'war bonds':'emergency credit'}`,text:`${q.toFixed(1)} treasury units are borrowed from ${d.lender} at ${(d.rate*100).toFixed(1)}% interest.`});return d}
function repayDebt(w,a,amount){const T=initialize(w);let left=Math.min(Math.max(0,amount),a.debt,a.treasury),paid=0;for(const d of T.instruments.filter(x=>x.realmId===a.realmId&&x.status==='active').sort((x,y)=>x.issuedYear-y.issuedYear||x.id-y.id)){const q=Math.min(left,d.principal);if(q<=0)break;d.principal=round(d.principal-q,2);d.repaid=round(d.repaid+q,2);left-=q;paid+=q;if(d.principal<=.01){d.principal=0;d.status='repaid'}}a.debt=round(Math.max(0,a.debt-paid),2);a.treasury=round(Math.max(0,a.treasury-paid),2);T.stats.debtRepaid=round(T.stats.debtRepaid+paid,2);return paid}
function applyFiscalPressure(w,a,econ,effTax,defaulted=false){const rs=realmState(w,a.realmId);if(rs){const taxPain=Math.max(0,effTax-.14)*18,infPain=Math.max(0,a.inflation-.06)*10,defPain=defaulted?15:0;rs.stability=round(clamp(Number(rs.stability||50)-taxPain-infPain-defPain,0,100),1);rs.treasury=round(Math.max(0,a.treasury),1)}for(const sid of econ.ids){const p=w.history.current.settlementProsperity;const drag=Math.max(0,effTax-.13)*.003+Math.max(0,a.inflation-.05)*.002+(defaulted?.018:0);p[sid]=round(clamp(Number(p[sid]||.4)-drag,.05,1.2),4);const c=w.cities?.cities?.[sid];if(c){c.priceIndex=round(clamp(Number(c.priceIndex||100)*(1+Math.max(0,a.inflation-.02)*.025)+(defaulted?12:0),45,340),2);c.unemployment=round(clamp(Number(c.unemployment||.08)+Math.max(0,a.inflation-.08)*.003+(defaulted?.012:0),0,.7),4)}}}
function defaultRealm(w,a,year,revenue){const T=initialize(w),haircut=.42;for(const d of T.instruments.filter(x=>x.realmId===a.realmId&&x.status==='active')){d.principal=round(d.principal*(1-haircut),2);d.status='restructured'}a.debt=round(a.debt*(1-haircut),2);a.treasury=0;a.inflation=round(clamp(a.inflation+.09,.01,.65),4);a.debasement=round(clamp(a.debasement+.12,0,.75),4);a.coinValue=round(clamp(a.coinValue*.72,.18,1),4);a.credit=8;a.defaults++;a.consecutiveDeficit=0;T.stats.defaults++;pushHistory(w,{type:'sovereign_default',importance:3,realmIds:[a.realmId],title:`Sovereign default in ${realmName(w,a.realmId)}`,text:`Debt service collapses after liabilities reach ${a.debt.toFixed(1)} against annual revenue of ${revenue.toFixed(1)}. Creditors accept restructuring and the coin is sharply devalued.`});return true}
function simulateFiscalYear(w,year=absYear(w)){const T=initialize(w);syncRealms(w);for(const a of T.realms.slice().sort((x,y)=>x.realmId-y.realmId)){const rs=realmState(w,a.realmId);if(!rs)continue;const econ=realmEconomy(w,a.realmId),force=forces(w,a.realmId),war=activeWar(w,a.realmId),effTax=clamp(a.taxRate+(war?a.warSurcharge:0),.04,.32);const tax=econ.pop*Math.max(.25,econ.prosperity)*effTax*.00035;const tariff=econ.trade*a.tariffRate*.0022;const domain=econ.wealth*.022;const revenue=tax+tariff+domain;const armyWages=force.manpower*.0021;const fleetCost=force.hulls*1.45;const logistics=force.supplyGap*.00115;const civil=econ.pop*.000018+econ.ids.length*.45;const interest=a.debt*a.interestRate;const warExpense=armyWages+fleetCost+logistics;const expense=civil+warExpense+interest;let balance=revenue-expense;a.treasury=round(a.treasury+balance,2);a.lastRevenue=round(revenue,2);a.lastExpense=round(expense,2);a.lastBalance=round(balance,2);a.warCost=round(warExpense,2);a.consecutiveDeficit=balance<0?a.consecutiveDeficit+1:0;T.stats.taxCollected=round(T.stats.taxCollected+tax,2);T.stats.tariffsCollected=round(T.stats.tariffsCollected+tariff,2);T.stats.warSpending=round(T.stats.warSpending+warExpense,2);T.stats.interestPaid=round(T.stats.interestPaid+interest,2);
 if(a.treasury<Math.max(5,expense*.12)){const need=Math.max(0,expense*.45-a.treasury);if(need>1)issueDebt(w,a,need*1.08,year,war)}
 const debtRatio=a.debt/Math.max(1,revenue);a.credit=round(clamp(92-debtRatio*7-a.inflation*95+Number(rs.stability||50)*.16,5,96),1);a.interestRate=round(clamp(.025+debtRatio*.006+(100-a.credit)*.00075,.02,.24),4);
 let minted=0;if((a.treasury<expense*.18||a.consecutiveDeficit>=2)&&debtRatio>2.5){minted=Math.min(Math.max(0,expense*.18-a.treasury),revenue*.22+8);if(minted>0){a.moneySupply=round(a.moneySupply+minted,2);a.treasury=round(a.treasury+minted,2);a.debasement=round(clamp(a.debasement+.006+minted/Math.max(100,a.moneySupply)*.08,0,.75),4);T.stats.debasements++;if(a.debasement>.12&&keyed(w,year,`debase:${a.realmId}`)()<.32)pushHistory(w,{type:'coin_debased',importance:2,realmIds:[a.realmId],title:`Coinage debased in ${realmName(w,a.realmId)}`,text:`The mint expands the money supply to finance ${war?'the war':'the treasury deficit'}, reducing confidence in the coin.`})}}
 const deficitPressure=Math.max(0,-balance)/Math.max(1,revenue),surplusPressure=Math.max(0,balance)/Math.max(1,revenue);a.inflation=round(clamp(a.inflation+deficitPressure*.012+debtRatio*.0007+a.debasement*.004-surplusPressure*.006-.002,.005,.65),4);a.coinValue=round(clamp(1-a.inflation*.55-a.debasement*.48,.18,1),4);
 let defaulted=false;if(a.consecutiveDeficit>=3&&debtRatio>9&&a.credit<22)defaulted=defaultRealm(w,a,year,revenue);else if(balance>revenue*.18&&a.debt>0)repayDebt(w,a,Math.min(a.treasury*.08,a.debt*.07,balance*.35));if(a.inflation>.22&&keyed(w,year,`inflation:${a.realmId}`)()<.2){T.stats.inflationCrises++;pushHistory(w,{type:'inflation_crisis',importance:2,realmIds:[a.realmId],title:`Inflation crisis in ${realmName(w,a.realmId)}`,text:`Prices accelerate as debt, deficit finance and coin debasement erode purchasing power.`})}applyFiscalPressure(w,a,econ,effTax,defaulted);a.lastYear=year;T.annual.push({year,realmId:a.realmId,revenue:round(revenue,2),tax:round(tax,2),tariff:round(tariff,2),domain:round(domain,2),expense:round(expense,2),civil:round(civil,2),war:round(warExpense,2),interest:round(interest,2),balance:round(balance,2),treasury:a.treasury,debt:a.debt,inflation:a.inflation,credit:a.credit,coinValue:a.coinValue,minted:round(minted,2),defaulted})}T.currentYear=year;maintenance(w);return T}
function maintenance(w){const T=state(w),cut=absYear(w)-T.settings.retainDetailedYears;if(cut<=0)return T;const old=T.annual.filter(x=>x.year<cut);if(!old.length)return T;const buckets=new Map;for(const r of old){const start=Math.floor(r.year/250)*250,key=`${start}:${r.realmId}`,b=buckets.get(key)||{startYear:start,endYear:start+249,realmId:r.realmId,years:0,revenue:0,expense:0,war:0,interest:0,defaults:0,meanInflation:0,meanDebt:0};b.years++;b.revenue+=r.revenue;b.expense+=r.expense;b.war+=r.war;b.interest+=r.interest;b.defaults+=r.defaulted?1:0;b.meanInflation+=r.inflation;b.meanDebt+=r.debt;buckets.set(key,b)}for(const b of buckets.values()){b.revenue=round(b.revenue,1);b.expense=round(b.expense,1);b.war=round(b.war,1);b.interest=round(b.interest,1);b.meanInflation=round(b.meanInflation/Math.max(1,b.years),4);b.meanDebt=round(b.meanDebt/Math.max(1,b.years),1);const i=T.archives.findIndex(x=>x.startYear===b.startYear&&x.realmId===b.realmId);if(i>=0)T.archives[i]=b;else T.archives.push(b)}T.stats.archivedYears+=new Set(old.map(x=>x.year)).size;T.annual=T.annual.filter(x=>x.year>=cut).slice(-T.settings.maxAnnualRows);return T}
function simulateYears(w,years,options={}){initialize(w);const n=Math.max(0,Math.round(Number(years)||0));for(let i=0;i<n;i++){if(baseSimulator)baseSimulator(w,1,options);else Military?.simulateYears?.(w,1,options);simulateFiscalYear(w,absYear(w))}return w.treasury}
function simulateTo(w,target,options={}){initialize(w);const y=Math.max(absYear(w),Math.round(Number(target)||absYear(w)));return simulateYears(w,y-absYear(w),options)}
function realmView(w,rid){const a=account(w,Number(rid),false);if(!a)return null;const econ=realmEconomy(w,a.realmId),f=forces(w,a.realmId),ins=initialize(w).instruments.filter(x=>x.realmId===a.realmId);return{...a,name:realmName(w,a.realmId),population:econ.pop,prosperity:round(econ.prosperity,3),trade:round(econ.trade,1),activeWar:activeWar(w,a.realmId),manpower:Math.round(f.manpower),hulls:f.hulls,instruments:ins}}
function summary(w){const T=initialize(w),rows=T.realms.map(a=>realmView(w,a.realmId)).filter(Boolean),debt=rows.reduce((n,a)=>n+a.debt,0),cash=rows.reduce((n,a)=>n+a.treasury,0),war=rows.reduce((n,a)=>n+a.warCost,0),infl=rows.length?rows.reduce((n,a)=>n+a.inflation,0)/rows.length:0;return{year:absYear(w),realms:rows.length,treasury:round(cash,1),debt:round(debt,1),warSpending:round(war,1),meanInflation:round(infl,4),defaults:T.stats.defaults,activeDebt:T.instruments.filter(x=>x.status==='active'||x.status==='restructured').length,taxCollected:round(T.stats.taxCollected,1),tariffsCollected:round(T.stats.tariffsCollected,1)}}
function fingerprint(w){const T=initialize(w),s=T.realms.slice().sort((a,b)=>a.realmId-b.realmId).map(a=>`${a.realmId}:${a.treasury}:${a.debt}:${a.inflation}:${a.coinValue}:${a.credit}`).join('|'),d=T.instruments.map(x=>`${x.id}:${x.realmId}:${x.principal}:${x.status}`).join('|');let h=2166136261>>>0;for(const c of `${T.currentYear}|${s}|${d}|${T.stats.defaults}`){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function validate(w){const e=[],T=w?.treasury;if(!T||T.schemaVersion!==SCHEMA)return['treasury schema'];for(const a of T.realms){if(a.realmId==null)e.push('treasury realm');if(!Number.isFinite(a.treasury)||!Number.isFinite(a.debt)||a.debt<0)e.push('treasury balance');if(a.inflation<0||a.coinValue<=0||a.credit<0)e.push('monetary state')}for(const d of T.instruments)if(d.realmId==null||!Number.isFinite(d.principal)||d.principal<0)e.push('debt instrument');return[...new Set(e)]}
const api={VERSION,SCHEMA,initialize,setBaseSimulator,absYear,account,realmView,summary,issueDebt,repayDebt,simulateFiscalYear,simulateYears,simulateTo,maintenance,fingerprint,validate};return api;
});