(function(root,factory){
 const api=factory(root&&root.WorldForgeWarfareSupply,root&&root.WorldForgeNutrition,root&&root.WorldForgeUrbanEvolution);
 if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.WorldForgeWarfarePostWar=api;
})(typeof window!=='undefined'?window:globalThis,function(Warfare,Nutrition,Urban){
'use strict';
if(!Warfare)throw new Error('WorldForge post-war recovery requires Warfare & Supply');
const VERSION='4.9.7',clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
function ownerOf(c){return c?.kingdomId??c?.realmId??c?.factionId??c?.ownerId??null}
function cities(w){return w.cities?.cities||[]}
function yearOf(w,S){return Number(S.currentYear??w.history?.currentYear??0)}
function endedWars(w,year){return Object.values(w.history?.wars||{}).filter(x=>x&&x.endYear!=null&&Number(x.endYear)<=year&&Number(x.endYear)>=year-5)}
function warRealms(w,year){const set=new Set;for(const q of endedWars(w,year)){set.add(String(q.attackerId));set.add(String(q.defenderId))}return set}
function cityPopulation(c){return Math.max(1,Number(c?.population||c?.pop||0))}
function casualtyPressure(S,realm){const aa=(S.armies||[]).filter(a=>String(a.ownerId)===String(realm));const casualties=aa.reduce((n,a)=>n+Number(a.casualties||0),0),field=aa.reduce((n,a)=>n+Number(a.size||0),0);return clamp(casualties/Math.max(300,field+casualties),0,1)}
function cityWarPressure(w,S,c,year){const realm=ownerOf(c);if(realm==null)return 0;const ended=endedWars(w,year).filter(q=>String(q.attackerId)===String(realm)||String(q.defenderId)===String(realm));if(!ended.length)return 0;let p=casualtyPressure(S,realm)*.42;for(const e of (w.history?.events||[]).slice(-240)){const ey=Number(e.absoluteYear??e.year??-9999),hit=e.settlementId===c.id||e.settlementIds?.includes?.(c.id);if(!hit||ey<year-5)continue;const t=`${e.type||''} ${e.title||''}`;if(/siege/i.test(t))p+=.28;else if(/battle|raid|war/i.test(t))p+=.16}return clamp(p,0,1)}
function ensureState(S){S.postWar=S.postWar||{version:VERSION,lastAppliedYear:null,settlements:[],annual:[],stats:{recoveringSettlements:0,displaced:0,refugeeCampPopulation:0,reconstructionPressure:0,returnedManpower:0}};S.postWar.version=VERSION;S.postWar.settlements=S.postWar.settlements||[];S.postWar.annual=S.postWar.annual||[];return S.postWar}
function previousMap(P){return new Map((P.settlements||[]).map(x=>[Number(x.settlementId),x]))}
function nutritionProfile(w,sid){return w.nutrition?.profiles?.find(p=>Number(p.settlementId)===Number(sid))||null}
function urbanSettlement(w,sid){return w.urbanEvolution?.settlements?.find(p=>Number(p.id)===Number(sid))||null}
function applyNutrition(w,row){const p=nutritionProfile(w,row.settlementId);if(!p)return;const base=Math.max(0,Number(p.refugeeCampPopulation||0)),added=Math.max(0,Math.round(row.displacedThisYear*.58));p.displacedThisYear=Math.max(Number(p.displacedThisYear||0),Math.round(row.displacedThisYear));p.refugeeCampPopulation=Math.max(base,Math.round(row.refugeeCampPopulation),added)}
function applyUrban(w,row,year){const U=w.urbanEvolution;if(!U||row.reconstructionPressure<=.04)return;const city=urbanSettlement(w,row.settlementId);if(city){city.postWarReconstructionPressure=round(row.reconstructionPressure);city.postWarDamage=round(row.damage)}const id=`postwar-reconstruction:${row.settlementId}:${year}`;U.projects=U.projects||[];if(!U.projects.some(p=>p.id===id))U.projects.push({id,settlementId:row.settlementId,type:'reconstruction',name:`${city?.name||'Settlement'} Post-War Reconstruction`,status:row.reconstructionPressure>.2?'active':'recovering',progress:round(clamp(1-row.reconstructionPressure,.08,.95),2),source:'warfare-postwar'})}
function restoreManpower(S,row){const pool=S.manpower?.[row.settlementId];if(!pool)return 0;const cap=Math.max(0,Number(pool.capacity||0)),before=Math.max(0,Number(pool.available||0)),returned=Math.min(Math.max(0,cap-before),Math.round(row.demobilizationReturn));if(returned>0)pool.available=before+returned;return returned}
function apply(w,force=false){const S=w.warfareSupply||Warfare.initialize(w),P=ensureState(S),year=yearOf(w,S);if(!force&&P.lastAppliedYear===year)return S;const realms=warRealms(w,year),prev=previousMap(P),rows=[];let displaced=0,camps=0,reconstruction=0,returned=0;for(const c of cities(w)){const realm=ownerOf(c),old=prev.get(Number(c.id)),pressure=cityWarPressure(w,S,c,year),legacy=old?Number(old.reconstructionPressure||0)*.72:0,active=Math.max(pressure,legacy);if(!realms.has(String(realm))&&active<.03)continue;const pop=cityPopulation(c),damage=clamp(active*.72+(old?Number(old.damage||0)*.55:0),0,1),displacedThisYear=Math.round(pop*active*.018),refugeeCampPopulation=Math.round(Math.max(displacedThisYear*.55,(old?.refugeeCampPopulation||0)*.7)),reconstructionPressure=round(clamp(damage*.7+refugeeCampPopulation/Math.max(1,pop)*2.2,0,1)),demobilizationReturn=Math.round(pop*clamp(.002+casualtyPressure(S,realm)*.006,0,.012));const row={settlementId:Number(c.id),realmId:realm,year,damage:round(damage),displacedThisYear,refugeeCampPopulation,reconstructionPressure,demobilizationReturn,recoveryStage:reconstructionPressure>.42?'emergency':reconstructionPressure>.2?'rebuilding':reconstructionPressure>.07?'recovering':'normalized'};row.returnedManpower=restoreManpower(S,row);applyNutrition(w,row);applyUrban(w,row,year);rows.push(row);displaced+=displacedThisYear;camps+=refugeeCampPopulation;reconstruction+=reconstructionPressure;returned+=row.returnedManpower}P.settlements=rows;P.lastAppliedYear=year;P.stats={recoveringSettlements:rows.filter(x=>x.recoveryStage!=='normalized').length,displaced,refugeeCampPopulation:camps,reconstructionPressure:round(rows.length?reconstruction/rows.length:0),returnedManpower:returned};P.annual=P.annual.filter(x=>Number(x.year)!==year);P.annual.push({year,...P.stats});P.annual=P.annual.slice(-160);S.stats=S.stats||{};Object.assign(S.stats,{postWarRecovering:P.stats.recoveringSettlements,postWarDisplaced:displaced,postWarRefugees:camps,reconstructionPressure:P.stats.reconstructionPressure,returnedManpower:returned});S.revision=Number(S.revision||0)+1;return S}
const baseInitialize=Warfare.initialize?.bind(Warfare),baseSim=Warfare.simulateWarfareYear?.bind(Warfare),baseSummary=Warfare.summary?.bind(Warfare),baseCity=Warfare.cityMilitaryView?.bind(Warfare);
if(baseInitialize)Warfare.initialize=function(w,force=false){const s=baseInitialize(w,force);return apply(w,force)||s};
if(baseSim)Warfare.simulateWarfareYear=function(w,y){const s=baseSim(w,y);return apply(w,true)||s};
if(baseSummary)Warfare.summary=function(w){const s=baseSummary(w),p=w.warfareSupply?.postWar?.stats||{};return{...s,postWarRecovering:Number(p.recoveringSettlements||0),postWarDisplaced:Number(p.displaced||0),postWarRefugees:Number(p.refugeeCampPopulation||0),reconstructionPressure:Number(p.reconstructionPressure||0),returnedManpower:Number(p.returnedManpower||0)}};
if(baseCity)Warfare.cityMilitaryView=function(w,id){const v=baseCity(w,id),p=w.warfareSupply?.postWar?.settlements?.find(x=>Number(x.settlementId)===Number(id))||null;return{...v,postWar:p}};
Warfare.applyPostWarRecovery=apply;Warfare.POSTWAR_VERSION=VERSION;
return{VERSION,endedWars,cityWarPressure,apply};
});
