(function(root,factory){
 const api=factory(root&&root.WorldForgeWarfareSupply,root&&root.WorldForgeDiplomacy);
 if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.WorldForgeWarfarePeace=api;
})(typeof window!=='undefined'?window:globalThis,function(Warfare,Diplomacy){
'use strict';
if(!Warfare)throw new Error('WorldForge warfare peace integration requires Warfare & Supply');
const VERSION='4.9.8',GOALS=['border','conquest','punitive','defense','liberation'];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function ownerOf(c){return c?.kingdomId??c?.realmId??c?.factionId??c?.ownerId??null}
function cities(w){return w.cities?.cities||[]}
function warById(w,id){return w.history?.wars?.[id]||null}
function goalFor(w,war){if(war.warGoal)return war.warGoal;const cause=String(war.cause||'').toLowerCase();let g=/defen|invad/.test(cause)?'defense':/liberat|independ/.test(cause)?'liberation':/border|claim/.test(cause)?'border':/punish|raid|retali/.test(cause)?'punitive':GOALS[hash(`${w.settings?.seed||w.seed||'WORLD'}|goal|${war.id}`)%GOALS.length];war.warGoal=g;return g}
function realmCities(w,rid){return cities(w).filter(c=>String(ownerOf(c))===String(rid))}
function battleBalance(S,war){let a=0,d=0;for(const b of S.battles||[]){const aa=(S.armies||[]).find(x=>x.id===b.attackerArmyId),dd=(S.armies||[]).find(x=>x.id===b.defenderArmyId);if(!aa||!dd)continue;if(String(aa.ownerId)===String(war.attackerId)&&String(dd.ownerId)===String(war.defenderId)){a+=Number(b.defenderCasualties||0);d+=Number(b.attackerCasualties||0)}else if(String(aa.ownerId)===String(war.defenderId)&&String(dd.ownerId)===String(war.attackerId)){a+=Number(b.attackerCasualties||0);d+=Number(b.defenderCasualties||0)}}return{attackerInflicted:a,defenderInflicted:d}}
function occupationPressure(w,S,war){const atk=new Set(realmCities(w,war.attackerId).map(c=>Number(c.id))),def=new Set(realmCities(w,war.defenderId).map(c=>Number(c.id)));let onDef=0,onAtk=0;for(const s of S.sieges||[]){const a=(S.armies||[]).find(x=>x.id===s.armyId);if(!a)continue;if(String(a.ownerId)===String(war.attackerId)&&def.has(Number(s.targetCityId)))onDef+=Number(s.pressure||0);if(String(a.ownerId)===String(war.defenderId)&&atk.has(Number(s.targetCityId)))onAtk+=Number(s.pressure||0)}return{onDef,onAtk}}
function navalBalance(S,war){let a=0,d=0;for(const b of S.navalBattles||[]){if(String(b.ownerA)===String(war.attackerId)&&String(b.ownerB)===String(war.defenderId)){a+=Number(b.lossB||0);d+=Number(b.lossA||0)}else if(String(b.ownerB)===String(war.attackerId)&&String(b.ownerA)===String(war.defenderId)){a+=Number(b.lossA||0);d+=Number(b.lossB||0)}}return{attacker:a,defender:d}}
function metrics(w,S,war){const bb=battleBalance(S,war),occ=occupationPressure(w,S,war),nb=navalBalance(S,war),cas=(bb.attackerInflicted-bb.defenderInflicted)/Math.max(500,bb.attackerInflicted+bb.defenderInflicted),siege=(occ.onDef-occ.onAtk)*.34,naval=(nb.attacker-nb.defender)*.22,base=clamp(cas+siege+naval,-1,1),score=round(base*100,1);return{score,attackerPressure:round(clamp((base+1)/2,0,1)),defenderPressure:round(clamp((1-base)/2,0,1)),battleBalance:round(cas),siegeBalance:round(siege),navalBalance:round(naval)}}
function termsFor(w,war,m){const winner=m.score>12?Number(war.attackerId):m.score<-12?Number(war.defenderId):null,loser=winner==null?null:(winner===Number(war.attackerId)?Number(war.defenderId):Number(war.attackerId)),goal=goalFor(w,war),terms={status:winner==null?'white-peace':'settlement',winnerRealmId:winner,loserRealmId:loser,warGoal:goal,reparations:0,prestige:0,borderAdjustment:false,demilitarizedYears:0};if(winner!=null){const intensity=clamp(Math.abs(m.score)/100,.15,1);terms.prestige=round(8+intensity*32,1);terms.reparations=goal==='punitive'?round(20+intensity*80,1):round(8+intensity*34,1);terms.borderAdjustment=(goal==='border'||goal==='conquest'||goal==='liberation')&&intensity>.28;terms.demilitarizedYears=goal==='punitive'&&intensity>.55?3:0}return terms}
function signPeace(w,war,terms,year){if(war.peaceTerms)return war.peaceTerms;war.peaceTerms=terms;war.peaceYear=Number(war.endYear??year);try{if(typeof Diplomacy?.signTreaty==='function')Diplomacy.signTreaty(w,'peace_treaty',war.attackerId,war.defenderId,war.peaceYear,{strength:clamp(.55+Math.abs(Number(war.finalWarScore||0))/200,.55,1),terms:{...terms,warId:war.id}})}catch(_){ }return terms}
function state(S){if(!S.peace)S.peace={version:VERSION,lastAppliedYear:null,activeWars:[],settledWars:[],stats:{activeWarGoals:0,decisiveWars:0,settledWars:0}};S.peace.version=VERSION;return S.peace}
function apply(w,force=false){const S=w.warfareSupply||Warfare.initialize(w);if(!S)return S;const P=state(S),year=Number(S.currentYear??w.history?.currentYear??0);if(!force&&P.lastAppliedYear===year)return S;const active=[];for(const id of w.history?.current?.activeWarIds||[]){const war=warById(w,id);if(!war||war.endYear!=null)continue;const goal=goalFor(w,war),m=metrics(w,S,war);war.warScore=m.score;war.warGoal=goal;active.push({warId:war.id,attackerId:war.attackerId,defenderId:war.defenderId,goal,...m})}
 for(const war of w.history?.wars||[]){if(!war||war.endYear==null||war._wfPeaceIntegrated)continue;const m=metrics(w,S,war);war.finalWarScore=Number.isFinite(Number(war.score))&&Number(war.score)!==0?Number(war.score):m.score;const finalMetrics={...m,score:war.finalWarScore},terms=termsFor(w,war,finalMetrics);signPeace(w,war,terms,year);war._wfPeaceIntegrated=true;P.settledWars.push({warId:war.id,endYear:war.endYear,finalWarScore:war.finalWarScore,warGoal:goalFor(w,war),terms});}
 P.settledWars=P.settledWars.slice(-120);P.activeWars=active;P.lastAppliedYear=year;P.stats={activeWarGoals:active.length,decisiveWars:active.filter(x=>Math.abs(x.score)>=45).length,settledWars:P.settledWars.length};S.stats=S.stats||{};S.stats.activeWarGoals=P.stats.activeWarGoals;S.stats.decisiveWars=P.stats.decisiveWars;S.stats.settledWars=P.stats.settledWars;return S}
const baseInitialize=Warfare.initialize?.bind(Warfare),baseSim=Warfare.simulateWarfareYear?.bind(Warfare),baseSummary=Warfare.summary?.bind(Warfare),baseCity=Warfare.cityMilitaryView?.bind(Warfare);
if(baseInitialize)Warfare.initialize=function(w,force=false){const s=baseInitialize(w,force);return apply(w,force)||s};
if(baseSim)Warfare.simulateWarfareYear=function(w,y){const s=baseSim(w,y);return apply(w,true)||s};
if(baseSummary)Warfare.summary=function(w){const s=baseSummary(w),P=w.warfareSupply?.peace||{};return{...s,activeWarGoals:Number(P.stats?.activeWarGoals||0),decisiveWars:Number(P.stats?.decisiveWars||0),settledWars:Number(P.stats?.settledWars||0)}};
if(baseCity)Warfare.cityMilitaryView=function(w,id){const v=baseCity(w,id),owner=ownerOf(cities(w).find(c=>Number(c.id)===Number(id))),wars=(w.warfareSupply?.peace?.activeWars||[]).filter(x=>String(x.attackerId)===String(owner)||String(x.defenderId)===String(owner));return{...v,warGoals:wars}};
Warfare.applyWarGoalsAndPeace=apply;Warfare.activeWarGoals=w=>{apply(w);return w.warfareSupply?.peace?.activeWars||[]};Warfare.settledWars=w=>{apply(w);return w.warfareSupply?.peace?.settledWars||[]};Warfare.PEACE_VERSION=VERSION;
return{VERSION,GOALS,goalFor,metrics,termsFor,apply};
});
