(function(root,factory){
  const api=factory(root&&root.WorldForgeHistory,root&&root.WorldForgeSociety,root&&root.WorldForgeCity,root&&root.WorldForgeAdventure,root&&root.WorldForgeStory);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeWiki=api;
})(typeof window!=='undefined'?window:globalThis,function(History,Society,City,Adventure,Story){
'use strict';
const VERSION='1.0.0',WIKI_SCHEMA=1;
const TYPES=['realm','settlement','person','house','city','gang','site','quest','dialogue','event'];
function initialize(world){if(!world)throw new Error('World required');History.initialize(world);Society.initialize(world);City.initialize(world);Adventure.initialize(world);Story.initialize(world);if(!world.wiki||world.wiki.schemaVersion!==WIKI_SCHEMA)world.wiki={schemaVersion:WIKI_SCHEMA,engineVersion:VERSION,notes:{},bookmarks:[],authoredArticles:[]};else{world.wiki.engineVersion=VERSION;world.wiki.notes=world.wiki.notes||{};world.wiki.bookmarks=world.wiki.bookmarks||[];world.wiki.authoredArticles=world.wiki.authoredArticles||[]}return world.wiki}
function ref(type,id){return`${type}:${id}`}
function escText(v){return String(v??'')}
function personName(world,id){const p=world.society.people[id];return p?Society.fullName(world.society,p):'Unknown'}
function yearViews(world,year=null){const current=world.history.currentYear,y=year==null?current:Math.max(0,Math.min(current,Math.round(Number(year)||0)));return{year:y,h:y>=current?History.currentView(world):History.viewAt(world,y),s:y>=current?Society.currentView(world):Society.viewAt(world,y),c:y>=current?City.currentView(world):City.viewAt(world,y),a:y>=current?Adventure.currentView(world):Adventure.viewAt(world,y),t:y>=current?Story.currentView(world):Story.viewAt(world,y)}}
function articleBase(type,id,title,subtitle,summary,tags=[],refs=[],year=0,data={}){return{ref:ref(type,id),type,id,title:escText(title),subtitle:escText(subtitle),summary:escText(summary),tags:[...new Set(tags.filter(Boolean).map(String))],refs:[...new Set(refs.filter(Boolean))],year,data}}
function eventRefs(e){const out=[];(e.realmIds||[]).forEach(id=>out.push(ref('realm',id)));(e.settlementIds||[]).forEach(id=>out.push(ref('settlement',id)));(e.personIds||[]).forEach(id=>out.push(ref('person',id)));(e.houseIds||[]).forEach(id=>out.push(ref('house',id)));(e.gangIds||[]).forEach(id=>out.push(ref('gang',id)));(e.siteIds||[]).forEach(id=>out.push(ref('site',id)));(e.questIds||[]).forEach(id=>out.push(ref('quest',id)));return out}
function buildIndex(world,year=null){initialize(world);const v=yearViews(world,year),rows=[];const realmMap=new Map(v.h.realms.map(r=>[r.id,r]));
  for(const r of v.h.realms.filter(x=>x.formedYear<=v.year)){const cap=world.settlements[r.capitalId],title=v.s.titles.find(t=>t.realmId===r.id&&t.active),holder=title?.holderId!=null?personName(world,title.holderId):'no active ruler';rows.push(articleBase('realm',r.id,r.name,`${r.active?'Active':'Historical'} realm · ${r.settlementCount||0} settlements`,`In Year ${v.year}, ${r.name} records ${Math.round(r.population||0).toLocaleString()} people, stability ${Math.round(r.stability||0)}/100 and ${holder}.`,['realm',r.active?'active':'historical'],[cap?ref('settlement',cap.id):null,title?.holderId!=null?ref('person',title.holderId):null,title?.houseId!=null?ref('house',title.houseId):null],v.year,{population:r.population,stability:r.stability,capitalId:r.capitalId}))}
  for(const s of world.settlements){const rid=v.h.settlementKingdomIds[s.id],realm=realmMap.get(rid),cv=v.c.cities[s.id];rows.push(articleBase('settlement',s.id,s.name,`${s.capital?'Capital':s.type} · ${realm?.shortName||'Unruled'}`,`${s.name} has ${Math.round(v.h.settlementPopulation[s.id]||0).toLocaleString()} inhabitants at Year ${v.year}, prosperity ${Math.round((v.h.settlementProsperity[s.id]||0)*100)}% and local crime ${Math.round(cv?.crimeRate||0)}/100.`,['settlement',s.type,s.capital?'capital':null],[realm?ref('realm',rid):null,ref('city',s.id)],v.year,{population:v.h.settlementPopulation[s.id],prosperity:v.h.settlementProsperity[s.id]}))}
  for(const p of world.society.people.filter(p=>p.birthYear<=v.year)){const h=world.society.houses[p.houseId],alive=p.deathYear==null||p.deathYear>v.year;rows.push(articleBase('person',p.id,personName(world,p.id),`${alive?'Living':'Historical'} · ${p.occupation}`,`${personName(world,p.id)} was born in Year ${p.birthYear}${p.deathYear!=null&&p.deathYear<=v.year?` and died in Year ${p.deathYear}`:''}. Traits: ${(p.traits||[]).join(', ')||'unrecorded'}. Ambition: ${p.ambition||'unrecorded'}.`,['person',p.occupation,alive?'living':'deceased'],[p.houseId!=null?ref('house',p.houseId):null,ref('settlement',p.settlementId),ref('realm',p.realmId),p.spouseId!=null?ref('person',p.spouseId):null,...(p.parentIds||[]).map(id=>ref('person',id)),...(p.childrenIds||[]).map(id=>ref('person',id))],v.year,{birthYear:p.birthYear,deathYear:p.deathYear,occupation:p.occupation,prestige:p.prestige,wealth:p.wealth}))}
  for(const h of world.society.houses.filter(h=>h.foundingYear<=v.year)){const head=h.headId!=null?personName(world,h.headId):'no living head';rows.push(articleBase('house',h.id,h.name,`${h.status} house · founded Year ${h.foundingYear}`,`${h.name} traces its recorded line to Year ${h.foundingYear}. Current recorded head: ${head}. Prestige ${Math.round(h.prestige||0)}.`,['house',h.status],[h.headId!=null?ref('person',h.headId):null,h.realmId!=null?ref('realm',h.realmId):null,h.settlementId!=null?ref('settlement',h.settlementId):null,...(h.rulingTitleIds||[]).map(id=>{const t=world.society.titles[id];return t?.holderId!=null?ref('person',t.holderId):null})],v.year,{prestige:h.prestige,status:h.status}))}
  for(const c of v.c.cities){rows.push(articleBase('city',c.id,c.name,`${c.type} · crime ${Math.round(c.crimeRate)}/100`,`${c.name} contains ${c.districts.length} districts and ${c.activeBusinesses} active businesses. Guard strength ${Math.round(c.guardStrength)}/100, corruption ${Math.round(c.corruption)}/100, black market ${Math.round(c.blackMarket)}/100.`,['city',c.type,c.coastal?'coastal':null,c.river?'river':null],[ref('settlement',c.id),c.officials.magistrateId!=null?ref('person',c.officials.magistrateId):null,c.officials.watchCaptainId!=null?ref('person',c.officials.watchCaptainId):null,...v.c.gangs.filter(g=>g.cityId===c.id&&g.active).map(g=>ref('gang',g.id))],v.year,{crimeRate:c.crimeRate,blackMarket:c.blackMarket,districts:c.districts.length,businesses:c.activeBusinesses}))}
  for(const g of v.c.gangs.filter(g=>g.foundedYear<=v.year)){rows.push(articleBase('gang',g.id,g.name,`${g.active?'Active':'Historical'} gang · ${g.specialty}`,`${g.name} operates around ${world.settlements[g.cityId]?.name}. Influence ${Math.round(g.influence)}/100, heat ${Math.round(g.heat)}/100 and ${g.members} members are recorded.`,['gang',g.specialty,g.active?'active':'historical'],[ref('city',g.cityId),g.leaderId!=null?ref('person',g.leaderId):null,...(g.rivalIds||[]).map(id=>ref('gang',id))],v.year,{members:g.members,influence:g.influence,heat:g.heat}))}
  for(const s of v.a.sites.filter(s=>s.originYear<=v.year)){const base=world.adventure.sites[s.id];rows.push(articleBase('site',s.id,s.name,`${s.kind} · danger ${Math.round(s.danger)}/100`,base.lore,['site',s.kind,s.discovered?'discovered':'rumored'],[ref('settlement',s.settlementId),s.gangId!=null?ref('gang',s.gangId):null,s.sourceEventId!=null?ref('event',s.sourceEventId):null,...(base.sourcePersonIds||[]).map(id=>ref('person',id)),...v.t.quests.filter(q=>q.siteId===s.id).map(q=>ref('quest',q.id))],v.year,{danger:s.danger,rooms:s.roomCount,discovered:s.discovered}))}
  for(const q of v.t.quests.filter(q=>q.createdYear<=v.year)){rows.push(articleBase('quest',q.id,q.title,`${q.status} quest · difficulty ${q.difficulty}`,`Given by ${personName(world,q.giverPersonId)} near ${world.settlements[q.settlementId]?.name}. Reward: ${q.reward}. The graph contains ${q.nodes.length} nodes and ${q.edges.length} directed edges.`,['quest',q.status,...q.tags],[ref('person',q.giverPersonId),q.targetPersonId!=null?ref('person',q.targetPersonId):null,ref('settlement',q.settlementId),q.siteId!=null?ref('site',q.siteId):null,q.gangId!=null?ref('gang',q.gangId):null,q.sourceEventId!=null?ref('event',q.sourceEventId):null,...v.t.dialogues.filter(d=>d.questId===q.id).map(d=>ref('dialogue',d.id))],v.year,{status:q.status,difficulty:q.difficulty,reward:q.reward}))}
  for(const d of v.t.dialogues){rows.push(articleBase('dialogue',d.id,d.title,`${d.nodes.length} dialogue nodes`,`A conditional conversation tree spoken by ${personName(world,d.personId)} and linked to Quest #${d.questId}.`,['dialogue','story'],[ref('person',d.personId),ref('quest',d.questId)],v.year,{nodes:d.nodes.length}))}
  for(const e of world.history.events.filter(e=>e.year<=v.year)){rows.push(articleBase('event',e.id,e.title,`Year ${e.year} · ${String(e.type).replaceAll('_',' ')}`,e.text,['event',e.type],eventRefs(e),e.year,{importance:e.importance||1,eventType:e.type}))}
  for(const a of world.wiki.authoredArticles||[])if((a.year??0)<=v.year)rows.push(articleBase('event',`note-${a.id}`,a.title,'Authored world note',a.body,['authored','note'],a.refs||[],a.year??v.year,{authored:true}));
  return rows
}
function scoreArticle(a,q){if(!q)return 1;const terms=q.toLowerCase().trim().split(/\s+/).filter(Boolean),title=a.title.toLowerCase(),body=`${a.subtitle} ${a.summary} ${a.tags.join(' ')}`.toLowerCase();let score=0;for(const t of terms){if(title===t)score+=20;if(title.includes(t))score+=8;if(a.tags.some(x=>x.toLowerCase()===t))score+=5;if(body.includes(t))score+=2}return score}
function search(world,query='',options={}){const rows=buildIndex(world,options.year),type=options.type&&options.type!=='all'?options.type:null,limit=Math.max(1,Math.min(200,Number(options.limit)||60));return rows.filter(a=>!type||a.type===type).map(a=>({a,score:scoreArticle(a,query)})).filter(x=>!query.trim()||x.score>0).sort((x,y)=>y.score-x.score||y.a.year-x.a.year||x.a.title.localeCompare(y.a.title)).slice(0,limit).map(x=>x.a)}
function article(world,articleRef,year=null){return buildIndex(world,year).find(a=>a.ref===articleRef)||null}
function related(world,articleRef,year=null,limit=30){const index=buildIndex(world,year),map=new Map(index.map(a=>[a.ref,a])),a=map.get(articleRef);if(!a)return[];const direct=a.refs.map(r=>map.get(r)).filter(Boolean),back=index.filter(x=>x.refs.includes(articleRef));return[...new Map([...direct,...back].map(x=>[x.ref,x])).values()].slice(0,limit)}
function chronology(world,articleRef,year=null){initialize(world);const y=year==null?world.history.currentYear:Math.min(world.history.currentYear,Number(year)||0);return world.history.events.filter(e=>e.year<=y&&eventRefs(e).includes(articleRef)).map(e=>({year:e.year,type:e.type,title:e.title,text:e.text,ref:ref('event',e.id)}))}
function dashboard(world,year=null){const rows=buildIndex(world,year),counts={};for(const t of TYPES)counts[t]=rows.filter(a=>a.type===t).length;return{year:yearViews(world,year).year,total:rows.length,counts,bookmarks:initialize(world).bookmarks.length,notes:Object.keys(world.wiki.notes).length,authored:world.wiki.authoredArticles.length}}
function setNote(world,articleRef,text){const w=initialize(world);if(text==null||String(text).trim()==='')delete w.notes[articleRef];else w.notes[articleRef]=String(text);return w.notes[articleRef]||''}
function toggleBookmark(world,articleRef){const w=initialize(world),i=w.bookmarks.indexOf(articleRef);if(i>=0)w.bookmarks.splice(i,1);else w.bookmarks.push(articleRef);return w.bookmarks.includes(articleRef)}
function addAuthoredArticle(world,data={}){const w=initialize(world),a={id:w.authoredArticles.length,title:String(data.title||`World Note ${w.authoredArticles.length+1}`),body:String(data.body||''),year:Number.isFinite(Number(data.year))?Number(data.year):world.history.currentYear,refs:[...(data.refs||[])]};w.authoredArticles.push(a);return a}
function exportMarkdown(world,year=null){const v=yearViews(world,year),rows=buildIndex(world,v.year),lines=[`# ${world.name} — WorldForge Encyclopedia`,``,`Generated at Year ${v.year}.`,``, `## Index`];for(const t of TYPES){const group=rows.filter(a=>a.type===t);if(!group.length)continue;lines.push(``,`### ${t[0].toUpperCase()+t.slice(1)} (${group.length})`);for(const a of group.slice(0,500))lines.push(`- **${a.title}** — ${a.subtitle}`)}return lines.join('\n')}
function wikiFingerprint(world,year=null){const rows=buildIndex(world,year);let h=2166136261>>>0;for(const ch of rows.map(a=>`${a.ref}:${a.title}:${a.refs.length}`).join('|')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function validateWiki(world){const errors=[],w=world?.wiki;if(!w||w.schemaVersion!==WIKI_SCHEMA)return['wiki schema'];const rows=buildIndex(world),refs=new Set(rows.map(a=>a.ref));if(rows.length<world.settlements.length)errors.push('wiki index size');for(const a of rows)for(const r of a.refs)if(!refs.has(r)&&!String(r).startsWith('event:'))errors.push('dangling wiki reference');for(const b of w.bookmarks)if(!refs.has(b))errors.push('invalid bookmark');return[...new Set(errors)]}
return{VERSION,WIKI_SCHEMA,TYPES,initialize,buildIndex,search,article,related,chronology,dashboard,setNote,toggleBookmark,addAuthoredArticle,exportMarkdown,wikiFingerprint,validateWiki};
});