(function(root,factory){
  const api=factory(root&&root.WorldForgeHistory,root&&root.WorldForgeCity,root&&root.WorldForgeCulture,root&&root.WorldForgeHousing,root&&root.WorldForgeMunicipal,root&&root.WorldForgeResources,root&&root.WorldForgePolitics,root&&root.WorldForgeWorldOrder,root&&root.WorldForgeWorkforce,root&&root.WorldForgeStructureArchetypes);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeWorldbuilding=api;
})(typeof window!=='undefined'?window:globalThis,function(History,City,Culture,Housing,Municipal,Resources,Politics,WorldOrder,Workforce,Archetypes){
'use strict';
if(!History||!City||!WorldOrder||!Workforce||!Archetypes)throw new Error('WorldForge v4.1 requires History, City, WorldOrder, Workforce and StructureArchetypes');
const VERSION='4.1.0',SCHEMA=1,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=4)=>Number(Number(v).toFixed(d));
const runtime=new WeakMap(),perf=new WeakMap();
const DISTRICTS=['old_town','residential','market','harbor','temple','military','noble','civic','industrial','slums','outskirts'];
const LANDMARK_TYPES=['ruin','battlefield','great_work','lighthouse','bridge','canal','fortified_port','monument'];
const LANDMARK_EVENTS=/war|battle|conquest|siege|collapse|fire|famine|epidemic|plague|disaster/i;
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function absYear(w){return WorldOrder.absYear(w)}
function owner(w,sid){return w.history?.current?.settlementKingdomIds?.[sid]??w.settlements?.[sid]?.kingdomId??null}
function state(w){if(!w.worldbuilding||w.worldbuilding.schemaVersion!==SCHEMA)w.worldbuilding={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:absYear(w),profiles:[],annual:[],archives:[],revision:0,lastAppliedYear:null,settings:{retainDetailedYears:1000,maxDistricts:16,maxLandmarks:10},stats:{settlements:0,capitals:0,ports:0,fortified:0,slumDistricts:0,districts:0,structureUnits:0,landmarks:0,ruins:0,battlefields:0,greatWorks:0,meanCondition:0,meanWealth:0,archivedYears:0}};const S=w.worldbuilding;S.engineVersion=VERSION;S.profiles=S.profiles||[];S.annual=S.annual||[];S.archives=S.archives||[];S.revision=Number(S.revision||0);S.settings={retainDetailedYears:1000,maxDistricts:16,maxLandmarks:10,...S.settings};S.stats={settlements:0,capitals:0,ports:0,fortified:0,slumDistricts:0,districts:0,structureUnits:0,landmarks:0,ruins:0,battlefields:0,greatWorks:0,meanCondition:0,meanWealth:0,archivedYears:0,...S.stats};return S}
function eventSettlementIds(e){const ids=[];if(Number.isInteger(e?.settlementId))ids.push(e.settlementId);for(const id of e?.settlementIds||[])if(Number.isInteger(id))ids.push(id);return[...new Set(ids)]}
function buildRuntime(w,force=false){const S=state(w),sig=`${absYear(w)}|${w.cities?.currentYear||0}|${w.culture?.currentYear||0}|${w.housing?.revision||0}|${w.municipal?.revision||0}|${w.resources?.currentYear||0}|${w.worldOrder?.revision||0}|${w.adventure?.currentYear||0}|${w.institutions?.currentYear||0}|${w.history?.events?.length||0}|${S.revision}|${S.profiles.length}`;let r=runtime.get(w);if(!force&&r&&r.signature===sig)return r;const cityBySid=new Map((w.cities?.cities||[]).map(x=>[Number(x.settlementId??x.id),x])),housingBySid=new Map((w.housing?.profiles||[]).map(x=>[Number(x.settlementId),x])),municipalBySid=new Map((w.municipal?.profiles||[]).map(x=>[Number(x.settlementId),x])),marketBySid=new Map((w.resources?.markets||[]).map(x=>[Number(x.settlementId),x])),workforceBySid=new Map((w.workforce?.profiles||[]).map(x=>[Number(x.settlementId),x])),profileBySid=new Map(S.profiles.map(x=>[Number(x.settlementId),x])),realmPower=new Map((w.worldOrder?.realms||[]).map(x=>[Number(x.realmId),x])),points=new Map,sitesBySid=new Map,greatBySid=new Map,eventsBySid=new Map;
for(let sid=0;sid<(w.settlements?.length||0);sid++){const rid=owner(w,sid),s=w.settlements[sid];if(rid==null||!s)continue;if(!points.has(Number(rid)))points.set(Number(rid),[]);points.get(Number(rid)).push(s)}
for(const s of w.adventure?.sites||[]){if(!s?.active||!Number.isInteger(s.settlementId))continue;if(!sitesBySid.has(s.settlementId))sitesBySid.set(s.settlementId,[]);sitesBySid.get(s.settlementId).push(s)}
for(const f of w.institutions?.facilities||[]){if(f?.greatWorkId==null||f.status==='destroyed'||!Number.isInteger(f.settlementId))continue;if(!greatBySid.has(f.settlementId))greatBySid.set(f.settlementId,[]);greatBySid.get(f.settlementId).push(f)}
for(const e of w.history?.events||[]){if(!LANDMARK_EVENTS.test(String(e?.type||'')))continue;for(const sid of eventSettlementIds(e)){if(!eventsBySid.has(sid))eventsBySid.set(sid,[]);const a=eventsBySid.get(sid);a.push(e);if(a.length>80)a.shift()}}
const centroids=new Map;for(const[rid,arr]of points)centroids.set(rid,{x:arr.reduce((n,p)=>n+p.x,0)/arr.length,y:arr.reduce((n,p)=>n+p.y,0)/arr.length});
r={signature:sig,cityBySid,housingBySid,municipalBySid,marketBySid,workforceBySid,profileBySid,realmPower,centroids,sitesBySid,greatBySid,eventsBySid};runtime.set(w,r);const p=perf.get(w)||{cacheBuilds:0,reads:0,profileBuilds:0,districtBuilds:0,structurePlans:0,landmarkBuilds:0};p.cacheBuilds++;perf.set(w,p);return r}
function biomeStyle(w,sid){const s=w.settlements?.[sid];if(!s||!w.layers?.biome)return'temperate';const x=Math.max(0,Math.min(w.settings.width-1,Math.round(s.x))),y=Math.max(0,Math.min(w.settings.height-1,Math.round(s.y))),b=String(w.layers.biome[y*w.settings.width+x]||'').toLowerCase();if(/desert|arid|savanna/.test(b))return'arid';if(/tundra|ice|snow/.test(b))return'tundra';if(/rain|jungle|tropical/.test(b))return'tropical';if(/mountain|alpine|highland/.test(b))return'highland';if(/steppe|grass|prairie/.test(b))return'steppe';if(/forest|taiga|wood/.test(b))return'forest';return'temperate'}
function cultureStyle(w,sid,coastal=false,river=false){const cid=w.culture?.settlementCultureIds?.[sid]??sid,name=w.culture?.cultures?.[cid]?.name||`culture-${cid}`;if(coastal&&hash(name)%5===0)return'coastal';if(river&&hash(name)%7===0)return'riverine';return Archetypes.CULTURE_STYLES[hash(name)%Archetypes.CULTURE_STYLES.length]}
function normalizeDistrict(kind){const k=String(kind||'').toLowerCase();if(/government|civic/.test(k))return'civic';if(/old town/.test(k))return'old_town';if(/market/.test(k))return'market';if(/docks|river ward|harbor/.test(k))return'harbor';if(/temple|shrine/.test(k))return'temple';if(/military|barrack|garrison/.test(k))return'military';if(/wealthy|noble/.test(k))return'noble';if(/craft|industrial|works/.test(k))return'industrial';if(/slum|low quarter/.test(k))return'slums';if(/outskirts|fields/.test(k))return'outskirts';return'residential'}
function tier(v,labels){const x=clamp(Number(v||0),0,1);return labels[Math.min(labels.length-1,Math.floor(x*labels.length))]}
function context(w,sid){const r=buildRuntime(w),s=w.settlements[sid],city=r.cityBySid.get(sid)||{},housing=r.housingBySid.get(sid)||{},mun=r.municipalBySid.get(sid)||{},work=r.workforceBySid.get(sid)||{},rid=owner(w,sid),power=r.realmPower.get(Number(rid))||{};const pop=Math.max(1,Number(work.population||work.totalPopulation||w.history?.current?.settlementPopulation?.[sid]||city.population||100)),pros=clamp(Number(city.prosperity??w.history?.current?.settlementProsperity?.[sid]??0.45),0,1),slum=clamp(Number(housing.slumShare||0),0,1),over=clamp(Number(housing.overcrowdingRate||0),0,1),service=clamp(Number(mun.serviceIndex??0.45),0,1),shortage=clamp(Number(housing.shortageRate||0),0,1),property=clamp(Number(housing.propertyIndex??1)/1.5,0,1),guard=clamp(Number(city.guardStrength||30)/100,0,1),coastal=!!city.coastal,river=!!city.river,capital=!!s?.capital||city.type==='Capital',tradeHub=Number(city.trade||0)>Math.max(80,pop*0.05),realmImportance=clamp(Number(power.powerShare||0)*2+Number(power.prestige||0)*0.35,0,1);const wealth=clamp(pros*0.42+service*0.18+property*0.16+(1-slum)*0.14+(1-shortage)*0.1,0,1),defense=clamp(guard*0.62+(capital?0.18:0)+realmImportance*0.2,0,1),importance=clamp((Math.log10(pop+10)-2)/3*0.45+(capital?0.28:0)+(tradeHub?0.12:0)+realmImportance*0.2,0,1),condition=clamp(0.92-slum*0.35-over*0.2-shortage*0.18+(service-0.5)*0.22,0,1);let frontier=false;const center=r.centroids.get(Number(rid));if(center&&s){const d=Math.hypot(s.x-center.x,s.y-center.y),diag=Math.hypot(w.settings.width,w.settings.height);frontier=d/Math.max(1,diag)>0.18}return{sid,s,city,housing,mun,work,rid,pop,pros,slum,over,service,shortage,property,guard,coastal,river,capital,tradeHub,realmImportance,wealth,defense,importance,condition,frontier}}
function settlementType(c){if(c.capital)return'capital';if(c.coastal&&c.tradeHub)return'port_city';if(c.defense>0.72&&c.pop>1800)return'fortress_city';if(c.frontier&&c.pop<1800)return'frontier_outpost';const t=String(c.city.type||c.s?.type||'Village').toLowerCase();if(t.includes('city'))return'city';if(t.includes('town'))return'town';if(t.includes('hamlet'))return'hamlet';return'village'}
function structurePlan(kind,share,c){const scale=Math.max(1,Math.sqrt(Math.max(4,Math.min(c.pop*share,50000)))/9),plans=[],add=(type,count)=>{count=Math.max(0,Math.min(c.pop>20000?48:32,Math.round(count)));if(count)plans.push({type,count,condition:round(c.condition,3)})};if(kind==='old_town'){add('house',scale*1.5);add('merchant_house',scale*0.6);add('temple',1);add('well',1)}else if(kind==='residential'){add('house',scale*2);add('poor_house',scale*(0.5+c.slum));add('merchant_house',scale*0.25*c.wealth);add('well',1+scale*0.08)}else if(kind==='market'){add('market_stall',scale*1.5);add('merchant_house',scale*0.6);add('warehouse',scale*0.3);add('well',1)}else if(kind==='harbor'){add('dock',2+scale*0.25);add('warehouse',scale*0.8);add('shipyard',c.tradeHub?2:1);add('market_stall',scale*0.35)}else if(kind==='temple'){add('temple',1+scale*0.12);add('house',scale*0.45);add('well',1)}else if(kind==='military'){add('barracks',1+scale*0.18);add('watchtower',1+c.defense*3);add('wall_segment',c.defense*6);add('gate',c.defense>0.55?1:0)}else if(kind==='noble'){add('noble_house',1+scale*0.38*c.wealth);add('merchant_house',scale*0.35);add('civic_hall',c.capital?1:0)}else if(kind==='civic'){add('civic_hall',1);add('market_stall',scale*0.25);add('well',1);add('noble_house',c.capital?1:0)}else if(kind==='industrial'){add('workshop',scale*1.2);add('warehouse',scale*0.55);add('granary',scale*0.18)}else if(kind==='slums'){add('poor_house',scale*2.6);add('market_stall',scale*0.35);add('well',Math.max(1,scale*0.05))}else if(kind==='outskirts'){add('farm_cluster',scale*1.3);add('house',scale*0.6);add('granary',1+scale*0.14)}else{add('house',scale);add('well',1)}return plans.slice(0,8)}
function districts(w,c){const raw=(c.city.districts||[]).slice(0,state(w).settings.maxDistricts),out=[];if(raw.length){for(const d of raw){const kind=normalizeDistrict(d.kind||d.name),share=clamp(Number(d.populationShare||1/raw.length),0.01,0.8),wealth=clamp(Number(d.wealth??c.wealth),0,1),condition=clamp(c.condition+(wealth-c.wealth)*0.16-(kind==='slums'?0.16:0),0,1);out.push({id:String(d.id??`${c.sid}:${out.length}`),kind,name:String(d.name||kind.replaceAll('_',' ')),x:clamp(Number(d.x??(0.2+(out.length%4)*0.2)),0.06,0.94),y:clamp(Number(d.y??(0.25+Math.floor(out.length/4)*0.2)),0.08,0.92),populationShare:round(share),wealth:round(wealth),condition:round(condition),structures:structurePlan(kind,share,{...c,condition})})}}else{const base=c.pop>9000?['old_town','market','residential','civic','temple','industrial','slums','outskirts']:c.pop>2500?['market','residential','temple','industrial','outskirts']:['residential','market','outskirts'];if(c.coastal||c.river)base.splice(2,0,'harbor');if(c.defense>0.55)base.push('military');const n=base.length;for(let i=0;i<n;i++){const a=i*Math.PI*2/n,kind=base[i],share=1/n,wealthDelta=kind==='slums'?-0.2:(kind==='noble'?0.2:0),wealth=clamp(c.wealth+wealthDelta,0,1),condition=clamp(c.condition-(kind==='slums'?0.15:0),0,1);out.push({id:`${c.sid}:W${i}`,kind,name:kind.replaceAll('_',' '),x:round(0.5+Math.cos(a)*(0.22+0.06*(i%2)),3),y:round(0.5+Math.sin(a)*(0.2+0.05*((i+1)%2)),3),populationShare:round(share),wealth:round(wealth),condition:round(condition),structures:structurePlan(kind,share,{...c,condition})})}}if((c.coastal||c.river)&&c.pop>900&&!out.some(x=>x.kind==='harbor'))out.push({id:`${c.sid}:harbor`,kind:'harbor',name:'Harbor District',x:0.82,y:0.55,populationShare:0.06,wealth:round(c.wealth),condition:round(c.condition),structures:structurePlan('harbor',0.06,c)});const p=perf.get(w)||{cacheBuilds:0,reads:0,profileBuilds:0,districtBuilds:0,structurePlans:0,landmarkBuilds:0};p.districtBuilds++;p.structurePlans+=out.length;perf.set(w,p);return out.slice(0,state(w).settings.maxDistricts)}
function aggregateStructures(ds,c){const m=new Map;for(const d of ds)for(const s of d.structures||[])m.set(s.type,(m.get(s.type)||0)+Number(s.count||0));if(c.defense>0.58){m.set('wall_segment',(m.get('wall_segment')||0)+Math.max(4,Math.round(c.defense*12)));m.set('gate',(m.get('gate')||0)+1);m.set('watchtower',(m.get('watchtower')||0)+Math.max(2,Math.round(c.defense*4)))}return[...m.entries()].map(([type,count])=>({type,count,label:Archetypes.get(type)?.label||type,category:Archetypes.get(type)?.category||'other'})).sort((a,b)=>b.count-a.count||a.type.localeCompare(b.type))}
function siteLandmarkType(kind){const k=String(kind||'').toLowerCase();return/battlefield/.test(k)?'battlefield':'ruin'}
function eventLandmarkType(type){const t=String(type||'').toLowerCase();if(/war|battle|conquest/.test(t))return'battlefield';if(/siege|collapse|fire/.test(t))return'ruin';return'monument'}
function landmarkPosition(seed,index=0){const h=hash(`${seed}|${index}`),a=((h%360)/180)*Math.PI,rad=.31+((h>>>9)%18)/100;return{x:round(clamp(.5+Math.cos(a)*rad,.08,.9),3),y:round(clamp(.53+Math.sin(a)*rad*.75,.12,.9),3)}}
function historicalLandmarks(w,c,year){const r=buildRuntime(w),out=[],seen=new Set,add=(type,name,sourceType,sourceId,originYear,condition,importance,details={})=>{if(!LANDMARK_TYPES.includes(type))return;const key=`${type}:${sourceType}:${sourceId}`;if(seen.has(key))return;seen.add(key);const pos=landmarkPosition(`${w.endless?.baseSeed||w.settings?.seed||'WORLD'}|LANDMARK|${c.sid}|${key}`,out.length);out.push({id:key,type,name:String(name||type.replaceAll('_',' ')),sourceType,sourceId:String(sourceId),originYear:Number.isFinite(Number(originYear))?Number(originYear):null,ageYears:Number.isFinite(Number(originYear))?Math.max(0,year-Number(originYear)):null,condition:round(clamp(Number(condition??.7),0,1),3),importance:round(clamp(Number(importance??.5),0,1),3),x:pos.x,y:pos.y,details})};
for(const s of r.sitesBySid.get(c.sid)||[]){add(siteLandmarkType(s.kind),s.name||s.kind,'adventure_site',s.id,s.originYear,clamp(.72-(Number(s.danger||0)/100)*.18,0.28,.9),clamp(.35+Number(s.danger||0)/180+(s.discovered?.12:0),0,1),{kind:s.kind,discovered:!!s.discovered,danger:Number(s.danger||0),sourceEventId:s.sourceEventId??null})}
for(const f of r.greatBySid.get(c.sid)||[]){add('great_work',f.name||'Great Work','institution',f.id,f.foundedYear,f.condition,clamp(Number(f.prestige||70)/100,0,1),{facilityType:f.typeId,greatWorkId:f.greatWorkId,status:f.status})}
const sourced=new Set(out.map(x=>x.details?.sourceEventId).filter(x=>x!=null).map(Number));for(const e of (r.eventsBySid.get(c.sid)||[]).slice(-18)){if(sourced.has(Number(e.id)))continue;const imp=Number(e.importance||0);if(imp<2&&hash(`${c.sid}|${e.id}|${e.type}`)%4!==0)continue;const type=eventLandmarkType(e.type),title=String(e.title||e.type||'Historical Event');add(type,type==='monument'?`${title} Memorial`:`${title} Site`,'history_event',e.id,e.absoluteYear??e.year,type==='ruin'?.48:type==='battlefield'?.58:.82,clamp(.32+imp*.13,0,1),{eventType:e.type,text:e.text||''})}
if(c.coastal&&c.tradeHub&&c.importance>.28)add('lighthouse',`${c.s?.name||'Settlement'} Sea Beacon`,'infrastructure','lighthouse',Math.max(0,year-Math.max(4,Math.round(c.importance*40))),clamp(.65+c.service*.25,0,1),clamp(.45+c.importance*.35,0,1),{navigation:true});
if(c.river&&c.pop>1200)add('bridge',`${c.s?.name||'Settlement'} River Bridge`,'infrastructure','bridge',Math.max(0,year-Math.max(8,Math.round(c.pop/900))),clamp(.55+c.service*.35,0,1),clamp(.35+c.importance*.3,0,1),{riverCrossing:true});
if(c.river&&c.tradeHub&&c.service>.58&&c.pop>4200)add('canal',`${c.s?.name||'Settlement'} Commercial Canal`,'infrastructure','canal',Math.max(0,year-Math.max(10,Math.round(c.pop/700))),clamp(.5+c.service*.4,0,1),clamp(.42+c.wealth*.32,0,1),{trade:true});
if(c.coastal&&c.defense>.58)add('fortified_port',`${c.s?.name||'Settlement'} Fortified Harbor`,'infrastructure','fortified_port',Math.max(0,year-Math.max(12,Math.round(c.defense*55))),clamp(.6+c.condition*.3,0,1),clamp(.48+c.defense*.35,0,1),{defense:true});
if(c.capital&&c.importance>.55)add('monument',`${c.s?.name||'Capital'} Civic Monument`,'infrastructure','capital_monument',Math.max(0,year-Math.max(15,Math.round(c.importance*70))),clamp(.62+c.service*.28,0,1),clamp(.55+c.importance*.4,0,1),{capital:true});
out.sort((a,b)=>b.importance-a.importance||(a.originYear??year)-(b.originYear??year)||a.id.localeCompare(b.id));const p=perf.get(w)||{cacheBuilds:0,reads:0,profileBuilds:0,districtBuilds:0,structurePlans:0,landmarkBuilds:0};p.landmarkBuilds++;perf.set(w,p);return out.slice(0,state(w).settings.maxLandmarks)}
function buildProfile(w,sid,year){const c=context(w,sid),ds=districts(w,c),structures=aggregateStructures(ds,c),type=settlementType(c),biome=biomeStyle(w,sid),culture=cultureStyle(w,sid,c.coastal,c.river),wealthTier=tier(c.wealth,['impoverished','modest','prosperous','wealthy']),defenseTier=tier(c.defense,['open','guarded','fortified','citadel']),importanceTier=tier(c.importance,['local','regional','major','world_significant']),flags={capital:c.capital,coastal:c.coastal,river:c.river,frontier:c.frontier,fortified:c.defense>0.58,tradeHub:c.tradeHub},architectureStyle=Archetypes.architecture(culture,biome,flags),landmarks=historicalLandmarks(w,c,year),visualIdentity=`${wealthTier} ${architectureStyle.label.toLowerCase()} ${type.replaceAll('_',' ')} in a ${biome} biome${c.defense>0.58?', protected by visible fortifications':''}${c.coastal?', shaped by maritime trade':''}${c.slum>0.2?', with pronounced housing pressure':''}${landmarks.length?`, carrying ${landmarks.length} visible historical or infrastructural landmark${landmarks.length===1?'':'s'}`:''}.`;const p={settlementId:sid,name:c.s?.name||c.city.name||`Settlement ${sid}`,realmId:c.rid,lastYear:year,settlementType:type,cultureStyle:culture,biomeStyle:biome,architectureStyle,wealthTier,defenseTier,importanceTier,population:Math.round(c.pop),wealthIndex:round(c.wealth),defenseIndex:round(c.defense),importanceIndex:round(c.importance),condition:round(c.condition),serviceIndex:round(c.service),slumPressure:round(c.slum),housingPressure:round(Math.max(c.over,c.shortage)),flags,districts:ds,structureSummary:structures,landmarks,visualIdentity,previewSeed:hash(`${w.endless?.baseSeed||w.settings?.seed||'WORLD'}|WORLDBUILD|${sid}|${culture}|${biome}`).toString(16)};const m=perf.get(w)||{cacheBuilds:0,reads:0,profileBuilds:0,districtBuilds:0,structurePlans:0,landmarkBuilds:0};m.profileBuilds++;perf.set(w,m);return p}
function refreshStats(w){const S=state(w),ps=S.profiles;S.stats.settlements=ps.length;S.stats.capitals=ps.filter(x=>x.flags?.capital).length;S.stats.ports=ps.filter(x=>x.flags?.coastal&&x.districts?.some(d=>d.kind==='harbor')).length;S.stats.fortified=ps.filter(x=>x.flags?.fortified).length;S.stats.slumDistricts=ps.reduce((n,x)=>n+(x.districts||[]).filter(d=>d.kind==='slums').length,0);S.stats.districts=ps.reduce((n,x)=>n+(x.districts||[]).length,0);S.stats.structureUnits=ps.reduce((n,x)=>n+(x.structureSummary||[]).reduce((a,b)=>a+b.count,0),0);S.stats.landmarks=ps.reduce((n,x)=>n+(x.landmarks||[]).length,0);S.stats.ruins=ps.reduce((n,x)=>n+(x.landmarks||[]).filter(l=>l.type==='ruin').length,0);S.stats.battlefields=ps.reduce((n,x)=>n+(x.landmarks||[]).filter(l=>l.type==='battlefield').length,0);S.stats.greatWorks=ps.reduce((n,x)=>n+(x.landmarks||[]).filter(l=>l.type==='great_work').length,0);S.stats.meanCondition=round(ps.reduce((n,x)=>n+Number(x.condition||0),0)/Math.max(1,ps.length));S.stats.meanWealth=round(ps.reduce((n,x)=>n+Number(x.wealthIndex||0),0)/Math.max(1,ps.length));return S.stats}
function compact(S){const keep=Math.max(100,Number(S.settings.retainDetailedYears||1000));if(S.annual.length<=keep)return;const cut=S.annual.splice(0,S.annual.length-keep),years=cut.map(x=>x.year);S.archives.push({from:Math.min(...years),to:Math.max(...years),years:cut.length,meanCondition:round(cut.reduce((n,x)=>n+Number(x.meanCondition||0),0)/cut.length),meanWealth:round(cut.reduce((n,x)=>n+Number(x.meanWealth||0),0)/cut.length),meanLandmarks:round(cut.reduce((n,x)=>n+Number(x.landmarks||0),0)/cut.length)});if(S.archives.length>120)S.archives.splice(0,S.archives.length-120);S.stats.archivedYears+=cut.length}
function sync(w){const S=state(w),by=new Map(S.profiles.map(x=>[Number(x.settlementId),x]));S.profiles=S.profiles.filter(x=>Number(x.settlementId)>=0&&Number(x.settlementId)<w.settlements.length);for(let sid=0;sid<w.settlements.length;sid++)if(!by.has(sid))S.profiles.push({settlementId:sid,lastYear:null});runtime.delete(w);buildRuntime(w,true);return S}
function simulateWorldbuildingYear(w,year=absYear(w)){const S=initialize(w),y=Math.floor(Number(year));if(S.lastAppliedYear===y)return S;if(S.lastAppliedYear!=null&&y<S.lastAppliedYear)throw new Error('Worldbuilding simulation cannot run backward');S.profiles=w.settlements.map((_,sid)=>buildProfile(w,sid,y));refreshStats(w);S.currentYear=y;S.lastAppliedYear=y;S.annual.push({year:y,settlements:S.stats.settlements,districts:S.stats.districts,structureUnits:S.stats.structureUnits,landmarks:S.stats.landmarks,ruins:S.stats.ruins,battlefields:S.stats.battlefields,greatWorks:S.stats.greatWorks,ports:S.stats.ports,fortified:S.stats.fortified,slumDistricts:S.stats.slumDistricts,meanCondition:S.stats.meanCondition,meanWealth:S.stats.meanWealth});compact(S);S.revision++;runtime.delete(w);buildRuntime(w,true);return S}
function settlementState(w,sid){const S=initialize(w),id=Number(sid);let p=S.profiles.find(x=>Number(x.settlementId)===id);if(!p||p.lastYear==null||!p.architectureStyle||!Array.isArray(p.landmarks)){p=buildProfile(w,id,absYear(w));const i=S.profiles.findIndex(x=>Number(x.settlementId)===id);if(i>=0)S.profiles[i]=p;else S.profiles.push(p);runtime.delete(w)}return p}
function settlementView(w,sid){return JSON.parse(JSON.stringify(settlementState(w,sid)))}
function summary(w){const S=initialize(w);return{year:S.currentYear,revision:S.revision,...refreshStats(w)}}
function fingerprint(w){const S=initialize(w),data={year:S.currentYear,profiles:S.profiles.map(p=>[p.settlementId,p.settlementType,p.cultureStyle,p.biomeStyle,p.architectureStyle?.id,p.wealthTier,p.defenseTier,p.importanceTier,p.population,p.wealthIndex,p.defenseIndex,p.condition,p.flags,(p.districts||[]).map(d=>[d.id,d.kind,d.x,d.y,d.populationShare,d.wealth,d.condition,(d.structures||[]).map(s=>[s.type,s.count,s.condition])]),(p.structureSummary||[]).map(s=>[s.type,s.count]),(p.landmarks||[]).map(l=>[l.id,l.type,l.originYear,l.condition,l.importance,l.x,l.y]),p.previewSeed]),annual:S.annual.slice(-100),stats:S.stats};return hash(JSON.stringify(data)).toString(16).padStart(8,'0')}
function validate(w){const S=initialize(w),e=[],seen=new Set;if(S.profiles.length!==w.settlements.length)e.push('worldbuilding settlement coverage');for(const p of S.profiles){if(seen.has(p.settlementId))e.push(`duplicate worldbuilding profile ${p.settlementId}`);seen.add(p.settlementId);if(p.lastYear==null)continue;if(!p.name||!p.settlementType)e.push(`profile metadata ${p.settlementId}`);if(!Archetypes.BIOME_STYLES.includes(p.biomeStyle))e.push(`biome style ${p.settlementId}`);if(!Archetypes.CULTURE_STYLES.includes(p.cultureStyle))e.push(`culture style ${p.settlementId}`);if(!p.architectureStyle||!Archetypes.ARCHITECTURE_FAMILIES[p.architectureStyle.id])e.push(`architecture style ${p.settlementId}`);for(const k of['wealthIndex','defenseIndex','importanceIndex','condition','serviceIndex','slumPressure','housingPressure'])if(!Number.isFinite(Number(p[k]))||Number(p[k])<0||Number(p[k])>1)e.push(`${k} ${p.settlementId}`);if(!p.districts?.length)e.push(`district coverage ${p.settlementId}`);for(const d of p.districts||[]){if(!DISTRICTS.includes(d.kind))e.push(`district kind ${p.settlementId}:${d.kind}`);for(const s of d.structures||[])if(!Archetypes.get(s.type)||s.count<0)e.push(`structure ${p.settlementId}:${s.type}`)}for(const l of p.landmarks||[]){if(!LANDMARK_TYPES.includes(l.type))e.push(`landmark type ${p.settlementId}:${l.type}`);if(!Number.isFinite(Number(l.x))||l.x<0||l.x>1||!Number.isFinite(Number(l.y))||l.y<0||l.y>1)e.push(`landmark position ${p.settlementId}:${l.id}`)}}return[...new Set(e)]}
function performance(w){const r=buildRuntime(w),p=perf.get(w)||{cacheBuilds:0,reads:0,profileBuilds:0,districtBuilds:0,structurePlans:0,landmarkBuilds:0};p.reads++;perf.set(w,p);return{...p,indexedCities:r.cityBySid.size,indexedHousing:r.housingBySid.size,indexedMunicipal:r.municipalBySid.size,indexedMarkets:r.marketBySid.size,indexedWorkforce:r.workforceBySid.size,indexedProfiles:r.profileBySid.size,indexedRealmPower:r.realmPower.size,indexedHistoricalSites:[...r.sitesBySid.values()].reduce((n,a)=>n+a.length,0),indexedGreatWorks:[...r.greatBySid.values()].reduce((n,a)=>n+a.length,0),indexedLandscapeEvents:[...r.eventsBySid.values()].reduce((n,a)=>n+a.length,0)}}
function initialize(w){if(!w)throw new Error('World required');if(!w.history)History.initialize(w);if(!w.cities)City.initialize(w);if(!w.culture)Culture?.initialize?.(w);if(!w.housing)Housing?.initialize?.(w);if(!w.municipal)Municipal?.initialize?.(w);if(!w.resources)Resources?.initialize?.(w);if(!w.politics)Politics?.initialize?.(w);if(!w.worldOrder)WorldOrder.initialize(w);const S=state(w);if(S.profiles.length!==w.settlements.length)sync(w);buildRuntime(w);if(S.profiles.some(p=>p.lastYear!=null&&(!p.architectureStyle||!Array.isArray(p.landmarks)))){S.profiles=w.settlements.map((_,sid)=>buildProfile(w,sid,absYear(w)));refreshStats(w);S.revision++;runtime.delete(w);buildRuntime(w,true)}return S}
function installBridge(){if(Workforce.__worldbuildingBridge)return;Workforce.__worldbuildingBridge=true;const rawYear=Workforce.simulateWorkforceYear.bind(Workforce),rawYears=Workforce.simulateYears.bind(Workforce);Workforce.simulateWorkforceYear=function(w,year=Workforce.absYear(w)){const out=rawYear(w,year);simulateWorldbuildingYear(w,year);return out};Workforce.simulateYears=function(w,years,options={}){const n=Math.max(0,Math.floor(Number(years)||0));for(let i=0;i<n;i++){rawYears(w,1,options);simulateWorldbuildingYear(w,absYear(w))}return w.workforce};Workforce.simulateTo=function(w,target,options={}){const t=Math.floor(Number(target)||0),now=absYear(w);if(t<now)throw new Error('Worldbuilding-enabled simulation cannot run backward');return Workforce.simulateYears(w,t-now,options)}}
installBridge();return{VERSION,SCHEMA,LANDMARK_TYPES,initialize,absYear,simulateWorldbuildingYear,settlementState,settlementView,summary,fingerprint,validate,performance,installBridge,buildProfile,biomeStyle,cultureStyle,normalizeDistrict,historicalLandmarks};
});