const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('src/features/warfare/warfare-strategic-map-overlay.js','utf8');
const supplyUI={state:{selectedArmyId:'A:1'},selectArmy(id){this.state.selectedArmyId=id}};
const controls={sync(){}};
const document={querySelector(){return null},addEventListener(){},createElementNS(){throw new Error('render should not be reached without a world')}};
const context={window:{WorldForgeWarfareSupplyUI:supplyUI,WorldForgeWarfareStrategicMapControls:controls,addEventListener(){}},document,setTimeout(){},console,Math};
vm.runInNewContext(source,context,{filename:'warfare-strategic-map-overlay.js'});
const api=context.window.WorldForgeWarfareStrategicMapOverlay;
assert.ok(api,'strategic map overlay API should load');
api.selectFront('F1');
assert.equal(supplyUI.state.selectedArmyId,null,'front selection should clear stale army selection');
assert.equal(api.state.selectedFrontId,'F1');
supplyUI.state.selectedArmyId='A:2';
api.selectCampaign('C1');
assert.equal(supplyUI.state.selectedArmyId,null,'campaign selection should clear stale army selection');
assert.equal(api.state.selectedCampaignId,'C1');
assert.equal(api.state.selectedFrontId,null,'campaign selection should replace front selection');
supplyUI.state.selectedArmyId='A:3';
api.selectOccupation('O1');
assert.equal(supplyUI.state.selectedArmyId,null,'occupation selection should clear stale army selection');
assert.equal(api.state.selectedOccupationId,'O1');
assert.equal(api.state.selectedCampaignId,null,'occupation selection should replace campaign selection');
supplyUI.state.selectedArmyId='A:4';
api.clearSelection();
assert.equal(supplyUI.state.selectedArmyId,null,'clearSelection should clear army selection too');
assert.equal(api.state.selectedOccupationId,null);
console.log('strategic map exclusive selection behavior OK');
