const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('src/features/warfare/warfare-strategic-map-controls.js','utf8');
const store=new Map([['worldforge.strategic-map.preferences.v1',JSON.stringify({layers:{fronts:false,campaigns:true,reinforcements:false,occupations:true},pins:[{type:'front',id:'F1',title:'North Front'}]})]]);
const overlay={state:{layers:{fronts:true,campaigns:true,reinforcements:true,occupations:true},selectedFrontId:null,selectedCampaignId:null,selectedOccupationId:null},render(){},toggleLayer(n){this.state.layers[n]=!this.state.layers[n]},selectFront(id){this.state.selectedFrontId=id;this.state.selectedCampaignId=this.state.selectedOccupationId=null},selectCampaign(id){this.state.selectedCampaignId=id;this.state.selectedFrontId=this.state.selectedOccupationId=null},selectOccupation(id){this.state.selectedOccupationId=id;this.state.selectedFrontId=this.state.selectedCampaignId=null},clearSelection(){this.state.selectedFrontId=this.state.selectedCampaignId=this.state.selectedOccupationId=null}};
const world={warfareSupply:{}};
const supplyUI={state:{selectedArmyId:null},selectArmy(id){this.state.selectedArmyId=id}};
const intel={selectionIntel(){const id=supplyUI.state.selectedArmyId;if(id!=null)return{type:'army',id,title:`Army ${id}`};if(overlay.state.selectedFrontId!=null)return{type:'front',id:overlay.state.selectedFrontId,title:'North Front'};return null},armyIntel(w,id){return{type:'army',id,title:`Army ${id}`}},frontIntel(w,id){return{type:'front',id,title:'North Front'}},campaignIntel(){return null},occupationIntel(){return null}};
const document={querySelector(){return null},addEventListener(){},body:{appendChild(){}}};
const context={window:{WorldForgeWarfareStrategicMapOverlay:overlay,WorldForgeWarfareOperationalIntel:intel,WorldForgeWarfareSupplyUI:supplyUI,WorldForgeWorldbuildingUI:{state:{world}},addEventListener(){}},document,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},setTimeout(){},innerWidth:1200,innerHeight:800,console};
vm.runInNewContext(source,context,{filename:'warfare-strategic-map-controls.js'});
const api=context.window.WorldForgeWarfareStrategicMapControls;
assert.ok(api,'strategic map controls API should load');
assert.equal(overlay.state.layers.fronts,false,'saved fronts filter should restore');
assert.equal(overlay.state.layers.reinforcements,false,'saved reinforcement filter should restore');
overlay.selectFront('F1');
assert.deepEqual(JSON.parse(JSON.stringify(api.selectionRef())),{type:'front',id:'F1'});
api.pinCurrent();
let saved=JSON.parse(store.get('worldforge.strategic-map.preferences.v1'));
assert.equal(saved.pins.length,1,'pinning same target should deduplicate');
supplyUI.state.selectedArmyId='A:7';
api.pinCurrent();
saved=JSON.parse(store.get('worldforge.strategic-map.preferences.v1'));
assert.equal(saved.pins[0].id,'A:7','army IDs containing colons should persist intact');
assert.equal(saved.pins.length,2,'second unique target should be added');
api.removePin('front','F1');
saved=JSON.parse(store.get('worldforge.strategic-map.preferences.v1'));
assert.equal(saved.pins.some(p=>p.type==='front'&&p.id==='F1'),false,'removed pins should not persist');
let pos=api.tooltipPosition(1190,790);
assert.ok(pos.left>=8&&pos.left<=912,'desktop tooltip should stay within horizontal viewport bounds');
assert.ok(pos.top>=8&&pos.top<=622,'desktop tooltip should stay within vertical viewport bounds');
context.innerWidth=240;context.innerHeight=140;
pos=api.tooltipPosition(220,120,224,124);
assert.deepEqual(JSON.parse(JSON.stringify(pos)),{left:8,top:8},'tiny viewports must never produce negative tooltip coordinates');
console.log('strategic map preference behavior OK');
