(function(root,factory){
  const api=factory(root&&root.WorldForgeHistory,root&&root.WorldForgeSociety,root&&root.WorldForgeCity,root&&root.WorldForgeCulture,root&&root.WorldForgeFactions,root&&root.WorldForgeCreatorSuite,root&&root.WorldForgeCanonBridge);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeKnowledge=api;
})(typeof window!=='undefined'?window:globalThis,function(History,Society,City,Culture,Factions,Creator,Canon){
'use strict';
const VERSION='1.4.0',SCHEMA=1;
const MAJOR=new Set(['war','peace','conquest','realm_formed','collapse','succession','succession_crisis','religious_schism','cultural_revival','faction_formed','faction_dissolved','uprising','gang_war','site_discovered','quest_resolved','quest_failed','crisis','famine','trade_boom','canon_character']);
const KIND={official:{rel:.86,speed:.70,decay:.0012,archive:.92},witness:{rel:.78,speed:.48,decay:.0030,archive:.38},merchant:{rel:.68,speed:.82,decay:.0020,archive:.55},temple:{rel:.72,speed:.46,decay:.0011,archive:.88},tavern:{rel:.38,speed:.95,decay:.0060,archive:.08},propaganda:{rel:.32,speed:.88,decay:.0030,archive:.48},inscription:{rel:.90,speed:.12,decay:.00025,archive:.98},scholar:{rel:.84,speed:.58,decay:.0008,archive:.95}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rnd(seed){let x=hash(seed);return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function absYear(w,e=null){if(e&&Number.isFinite(Number(e.absoluteYear)))return Number(e.absoluteYear);return(w.endless?.epochOffset||0)+Number(e?.year??w.history?.currentYear??0)}
function eventKey(w,e){return`${absYear(w,e)}|${e.type||'event'}|${e.title||''}|${(e.realmIds||[]).join(',')}|${(e.settlementIds||[]).join(',')}`}
function refs(e){const out=[];for(const [k,t] of [['realmIds','realm'],['settlementIds','settlement'],['personIds','person'],['houseIds','house'],['gangIds','gang'],['siteIds','site'],['questIds','quest'],['organizationIds','organization']])for(const id of e[k]||[])out.push(`${t}:${id}`);return[...new Set(out)]}
function initDeps(w){History?.initialize?.(w);Society?.initialize?.(w);City?.initialize?.(w);Culture?.initialize?.(w);Factions?.initialize?.(w)}
function initialize(w){
 if(!w)throw new Error('World required');initDeps(w);
 if(!w.knowledge||w.knowledge.schemaVersion!==SCHEMA)w.knowledge={schemaVersion:SCHEMA,engineVersion:VERSION,claims:[],sources:[],archives:[],discoveries:[],archiveThrough:-1,lastSyncYear:-1,settings:{retainYears:850,maxClaims:900,maxSources:3600,autoSync:true},stats:{claimsCreated:0,sourcesCreated:0,claimsArchived:0,rediscoveries:0,propagandaSources:0}};
 const k=w.knowledge;k.engineVersion=VERSION;k.claims=k.claims||[];k.sources=k.sources||[];k.archives=k.archives||[];k.discoveries=k.discoveries||[];k.settings={retainYears:850,maxClaims:900,maxSources:3600,autoSync:true,...k.settings};k.stats={claimsCreated:0,sourcesCreated:0,claimsArchived:0,rediscoveries:0,propagandaSources:0,...k.stats};return k
}
function originSettlement(w,e){if(Number.isInteger(e.settlementIds?.[0]))return e.settlementIds[0];const rid=e.realmIds?.[0];if(Number.isInteger(rid)){const r=w.history?.realms?.[rid];if(Number.isInteger(r?.capitalId))return r.capitalId}return 0}
function sourceText(w,e,kind,polarity,r){const truth=String(e.text||e.title||'An event entered the record.');const realm=e.realmIds?.[0]!=null?w.history.realms?.[e.realmIds[0]]?.shortName:null;const other=e.realmIds?.[1]!=null?w.history.realms?.[e.realmIds[1]]?.shortName:null;if(kind==='official')return `${realm||'The authorities'} record that ${truth}`;if(kind==='witness')return `A witness near ${w.settlements?.[originSettlement(w,e)]?.name||'the scene'} recalls: ${truth}`;if(kind==='merchant')return `A travelling ledger reports disruptions and repeats the account that ${truth}`;if(kind==='temple')return `Temple annals preserve the event as a moral turning point: ${truth}`;if(kind==='inscription')return `A durable inscription states: ${truth}`;if(kind==='scholar')return `A later compiler compares surviving accounts and writes: ${truth}`;if(kind==='propaganda'){const blame=polarity<0?(other||realm||'the enemy'):(realm||'our cause');return `${blame} is blamed in a partisan account that exaggerates responsibility and consequence.`}const twists=['the numbers were far greater than officials admitted','omens were seen before the event','a hidden patron supposedly arranged the outcome','survivors insist the accepted chronology is incomplete','the tale grows with each retelling'];return `${truth} Rumour adds that ${twists[Math.floor(r()*twists.length)]}.`}
function addSource(w,claimKey,data={}){const k=initialize(w),claim=k.claims.find(c=>c.key===claimKey);if(!claim)throw new Error('Unknown claim');const kind=KIND[data.kind]?data.kind:'witness',base=KIND[kind],id=k.sources.length,r=rnd(`${w.settings?.seed}|KNOWLEDGE|${claimKey}|${kind}|${id}`),s={id,claimKey,kind,title:String(data.title||({official:'Official Record',witness:'Witness Account',merchant:'Merchant Letter',temple:'Temple Chronicle',tavern:'Tavern Rumour',propaganda:'Partisan Broadside',inscription:'Stone Inscription',scholar:'Scholarly Compilation'}[kind])),originRealmId:Number.isInteger(data.originRealmId)?data.originRealmId:(claim.realmIds[0]??null),originSettlementId:Number.isInteger(data.originSettlementId)?data.originSettlementId:claim.originSettlementId,authorPersonId:Number.isInteger(data.authorPersonId)?data.authorPersonId:null,createdYear:Number.isFinite(Number(data.createdYear))?Number(data.createdYear):claim.year,reliability:clamp(Number(data.reliability??base.rel),0,1),polarity:clamp(Number(data.polarity??1),-1,1),biasRealmId:Number.isInteger(data.biasRealmId)?data.biasRealmId:null,public:data.public!==false,archiveStrength:clamp(Number(data.archiveStrength??base.archive),0,1),text:String(data.text||sourceText(w,{...claim,eventIds:claim.eventId,text:claim.trueText,title:claim.trueTitle,realmIds:claim.realmIds,settlementIds:claim.settlementIds},kind,Number(data.polarity??1),r))};k.sources.push(s);claim.sourceIds.push(id);k.stats.sourcesCreated++;if(kind==='propaganda')k.stats.propagandaSources++;return s}
function createClaim(w,e){const k=initialize(w),key=eventKey(w,e);if(k.claims.some(c=>c.key===key)||absYear(w,e)<=k.archiveThrough)return null;const r=rnd(`${w.settings?.seed}|CLAIM|${key}`),claim={id:k.stats.claimsCreated,key,eventId:e.id??null,eventType:e.type||'event',trueTitle:String(e.title||'Untitled event'),trueText:String(e.text||''),year:absYear(w,e),localYear:Number(e.year||0),importance:Number(e.importance||1),realmIds:[...(e.realmIds||[])],settlementIds:[...(e.settlementIds||[])],personIds:[...(e.personIds||[])],refs:refs(e),originSettlementId:originSettlement(w,e),originRealmId:e.realmIds?.[0]??null,sourceIds:[],createdBy:'simulation'};k.claims.push(claim);k.stats.claimsCreated++;
 if(claim.realmIds.length)addSource(w,key,{kind:'official',originRealmId:claim.realmIds[0]});
 if(claim.settlementIds.length||claim.personIds.length)addSource(w,key,{kind:'witness',authorPersonId:claim.personIds[0]});
 if(['war','conquest','trade_boom','famine','uprising','gang_war'].includes(claim.eventType)||r()<.48)addSource(w,key,{kind:'merchant'});
 if(/relig|succession|famine|collapse|crisis/.test(claim.eventType)||r()<.24)addSource(w,key,{kind:'temple'});
 if(claim.importance>=2)addSource(w,key,{kind:'tavern',reliability:.28+r()*.18});
 if(claim.importance>=3)addSource(w,key,{kind:'inscription'});
 if(['war','conquest','succession_crisis','uprising','collapse'].includes(claim.eventType)&&claim.realmIds.length){const hostile=claim.realmIds[1]??claim.realmIds[0];addSource(w,key,{kind:'propaganda',originRealmId:hostile,biasRealmId:hostile,polarity:-1,reliability:.22+r()*.18})}
 if(claim.year>80&&r()<.22)addSource(w,key,{kind:'scholar',createdYear:claim.year+20+Math.floor(r()*50)});return claim
}
function roadDistances(w,start){const n=w.settlements?.length||0,d=new Array(n).fill(Infinity);if(!n)return d;start=clamp(Number(start)||0,0,n-1);d[start]=0;const adj=Array.from({length:n},()=>[]);for(const r of w.roads||[]){adj[r.from]?.push(r.to);adj[r.to]?.push(r.from)}const q=[start];for(let qi=0;qi<q.length;qi++){const a=q[qi];for(const b of adj[a])if(d[b]>d[a]+1){d[b]=d[a]+1;q.push(b)}}return d}
function realmDistance(w,sourceSid,realmId,cache){const key=`${sourceSid}|${realmId}`;if(cache.has(key))return cache.get(key);const ds=roadDistances(w,sourceSid);let best=Infinity;for(let sid=0;sid<ds.length;sid++)if(w.history?.current?.settlementKingdomIds?.[sid]===realmId)best=Math.min(best,ds[sid]);if(!Number.isFinite(best))best=8;cache.set(key,best);return best}
function sourceWeight(w,s,realmId,year,cache){if(s.createdYear>year)return{awareness:0,evidence:0};const cfg=KIND[s.kind]||KIND.witness,age=Math.max(0,year-s.createdYear),dist=realmId==null?0:realmDistance(w,s.originSettlementId,realmId,cache),bias=s.biasRealmId==null?1:(s.biasRealmId===realmId?1.16:.74),spread=Math.min(.72,age*cfg.speed*.013),awareness=clamp(s.reliability*.58+spread-dist*.115,0,1),survival=clamp(1-age*cfg.decay*(1-s.archiveStrength*.75),.08,1),evidence=awareness*s.reliability*survival*bias;return{awareness,evidence}}
function viewClaim(w,claimOrKey,realmId=null,year=null){const k=initialize(w),c=typeof claimOrKey==='string'?k.claims.find(x=>x.key===claimOrKey):claimOrKey;if(!c)return null;const y=Number.isFinite(Number(year))?Number(year):absYear(w),cache=new Map(),ss=c.sourceIds.map(id=>k.sources[id]).filter(Boolean).filter(s=>s.createdYear<=y),weighted=ss.map(s=>({s,...sourceWeight(w,s,realmId,y,cache)})),aware=weighted.filter(x=>x.awareness>.12),pos=aware.filter(x=>x.s.polarity>=0).reduce((a,x)=>a+x.evidence*x.s.polarity,0),neg=aware.filter(x=>x.s.polarity<0).reduce((a,x)=>a+x.evidence*Math.abs(x.s.polarity),0),evidence=pos+neg,awareness=aware.length?Math.max(...aware.map(x=>x.awareness)):0,diversity=new Set(aware.filter(x=>x.evidence>.12).map(x=>x.s.kind)).size,agreement=evidence?Math.max(pos,neg)/evidence:0,age=Math.max(0,y-c.year);let status='unknown';if(age>380&&awareness<.11)status='lost';else if(age>240&&diversity<2&&awareness>.10)status='legendary';else if(pos>.55&&neg>.28)status='disputed';else if(evidence>.68&&agreement>.72&&diversity>=2)status='confirmed';else if(awareness>.15)status='disputed';const stance=pos>neg*1.25?'accepts':neg>pos*1.25?'rejects':'uncertain',confidence=clamp(evidence?Math.abs(pos-neg)/(evidence+.25):0,0,1);return{claim:c,realmId,year:y,status,stance,confidence:round(confidence),awareness:round(awareness),diversity,sources:weighted.sort((a,b)=>b.evidence-a.evidence).map(x=>({...x.s,awareness:round(x.awareness),evidence:round(x.evidence)})),truth:{title:c.trueTitle,text:c.trueText},publicTitle:publicTitle(c,status,stance)}}
function publicTitle(c,status,stance){if(status==='lost')return`Lost account: ${c.trueTitle}`;if(status==='legendary')return`Legend of ${c.trueTitle}`;if(status==='disputed')return stance==='rejects'?`Disputed tale: ${c.trueTitle}`:`Contested account: ${c.trueTitle}`;return c.trueTitle}
function audiences(w){const rows=(w.history?.current?.realmState||[]).filter(Boolean).filter(r=>r.active).map(r=>({id:r.id,name:w.history.realms?.[r.id]?.shortName||`Realm ${r.id}`}));return[{id:null,name:'Omniscient / Global'},...rows]}
function feed(w,realmId=null,year=null,limit=60){sync(w);const y=Number.isFinite(Number(year))?Number(year):absYear(w);return initialize(w).claims.filter(c=>c.year<=y).map(c=>viewClaim(w,c,realmId,y)).filter(v=>v&&v.status!=='unknown').sort((a,b)=>{const sr={confirmed:4,disputed:5,legendary:3,lost:1,unknown:0};return(sr[b.status]-sr[a.status])||(b.claim.importance-a.claim.importance)||(b.claim.year-a.claim.year)}).slice(0,Math.max(1,limit))}
function compare(w,claimKey,year=null){return audiences(w).map(a=>({audience:a,...viewClaim(w,claimKey,a.id,year)}))}
function archiveOld(w){const k=initialize(w),now=absYear(w),cut=now-k.settings.retainYears;if(k.claims.length<=k.settings.maxClaims&&cut<=k.archiveThrough)return;const eligible=k.claims.filter(c=>c.year<=cut);if(!eligible.length)return;const boundary=Math.floor(Math.max(...eligible.map(c=>c.year))/250)*250-1;if(boundary<=k.archiveThrough)return;const old=k.claims.filter(c=>c.year<=boundary),by=new Map();for(const c of old){const start=Math.floor(c.year/250)*250,key=start;if(!by.has(key))by.set(key,{startYear:start,endYear:start+249,total:0,types:{},major:[]});const a=by.get(key);a.total++;a.types[c.eventType]=(a.types[c.eventType]||0)+1;if(c.importance>=3&&a.major.length<18)a.major.push({year:c.year,title:c.trueTitle,type:c.eventType,refs:c.refs})}for(const a of by.values()){const ex=k.archives.find(x=>x.startYear===a.startYear);if(ex){ex.total+=a.total;for(const [t,n] of Object.entries(a.types))ex.types[t]=(ex.types[t]||0)+n;ex.major=[...ex.major,...a.major].slice(0,18)}else k.archives.push(a)}const keys=new Set(old.map(c=>c.key));k.claims=k.claims.filter(c=>!keys.has(c.key));k.sources=k.sources.filter(s=>!keys.has(s.claimKey));k.sources.forEach((s,i)=>s.id=i);for(const c of k.claims)c.sourceIds=k.sources.filter(s=>s.claimKey===c.key).map(s=>s.id);k.archiveThrough=boundary;k.stats.claimsArchived+=old.length}
function maybeRediscover(w){const k=initialize(w),now=absYear(w);for(const a of k.archives){if(a.rediscoveredYear!=null)continue;const bucket=Math.floor(now/100),r=rnd(`${w.settings?.seed}|REDISCOVER|${a.startYear}|${bucket}`);const sites=(w.adventure?.sites||[]).filter(s=>s.discovered&&Number(s.originYear||0)>=a.startYear&&Number(s.originYear||0)<=a.endYear);if((sites.length&&r()<.32)||r()<.008){a.rediscoveredYear=now;a.rediscoverySiteId=sites[0]?.id??null;k.discoveries.push({id:k.discoveries.length,year:now,archiveStart:a.startYear,siteId:a.rediscoverySiteId,title:`Fragments of Years ${a.startYear}–${a.endYear} rediscovered`});k.stats.rediscoveries++}}}
function sync(w){const k=initialize(w),events=w.history?.events||[];for(const e of events){const ay=absYear(w,e);if(ay<=k.archiveThrough)continue;const key=eventKey(w,e);if(!k.claims.some(c=>c.key===key))createClaim(w,e)}archiveOld(w);maybeRediscover(w);k.lastSyncYear=absYear(w);return k}
function createInvestigationQuest(w,claimKey,realmId=null){const v=viewClaim(w,claimKey,realmId);if(!v||!Creator?.createDocument)return null;const c=v.claim,doc=Creator.createDocument(w,{type:'Quest',title:`Investigate: ${c.trueTitle}`,summary:`Determine what really happened. Current public status: ${v.status}.`,body:`Conflicting accounts surround an event from Year ${c.year}. Compare witnesses, institutional records and partisan sources before deciding which version deserves to enter the canon.`,tags:['knowledge','rumour','investigation',v.status],refs:c.refs,published:false,fields:{spawnKind:'quest',knowledgeClaimKey:c.key}});try{Canon?.materializeDocument?.(w,doc.id)}catch{}return doc}
function articleKnowledge(w,articleRef,realmId=null,year=null){sync(w);const matches=initialize(w).claims.filter(c=>c.refs.includes(articleRef)||`event:${c.eventId}`===articleRef).map(c=>viewClaim(w,c,realmId,year)).filter(Boolean);if(!matches.length)return{status:'unknown',confidence:0,claims:[]};const rank={confirmed:5,disputed:4,legendary:3,lost:2,unknown:1},top=[...matches].sort((a,b)=>rank[b.status]-rank[a.status]||b.claim.importance-a.claim.importance)[0];return{status:top.status,confidence:top.confidence,claims:matches}}
function fingerprint(w){sync(w);const k=initialize(w);let h=2166136261>>>0;const s=[k.archiveThrough,k.claims.length,k.sources.length,k.archives.length,...k.claims.slice(-120).map(c=>`${c.key}:${c.sourceIds.length}`)].join('|');for(const ch of s){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function validate(w){const k=w?.knowledge;if(!k||k.schemaVersion!==SCHEMA)return['knowledge schema'];const errors=[],keys=new Set(k.claims.map(c=>c.key));for(const s of k.sources)if(!keys.has(s.claimKey))errors.push('orphan source');for(const c of k.claims)if(c.sourceIds.some(id=>!k.sources[id]||k.sources[id].claimKey!==c.key))errors.push('claim source link');if(k.claims.length>k.settings.maxClaims+250)errors.push('claim retention budget');return[...new Set(errors)]}
return{VERSION,SCHEMA,KIND,initialize,sync,createClaim,addSource,viewClaim,audiences,feed,compare,articleKnowledge,createInvestigationQuest,fingerprint,validate,absYear,eventKey};
});