import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';

global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,A=global.WorldForgeAdventure;
assert.ok(E&&H&&S&&C&&A,'all v0.5 engines must be exposed');
const options={seed:'EMBER-CROWN-01',width:160,height:90,seaLevel:.53,age:'mature',settlementTarget:45,kingdomTarget:7};
const make=()=>{const w=E.generateWorld(options);H.initialize(w);S.initialize(w);C.initialize(w);A.initialize(w);return w};
const a=make();
assert.deepEqual(A.validateAdventure(a),[],'Year 0 adventure state must validate');
assert.ok(a.adventure.sites.length>0,'initial sites should exist');
assert.ok(a.adventure.sites.every(s=>s.rooms.length>=5),'dungeons need usable room graphs');
assert.ok(a.adventure.sites.some(s=>s.rooms.some(r=>r.kind==='Boss Chamber')),'sites need boss chambers');
assert.ok(a.adventure.sites.some(s=>s.loot.length>=3),'sites need loot');
const b=make();
A.simulateYears(a,300);
A.simulateYears(b,100);A.simulateYears(b,75);A.simulateYears(b,125);
assert.deepEqual(A.validateAdventure(a),[],'300-year adventure state must validate');
assert.equal(A.adventureFingerprint(a),A.adventureFingerprint(b),'adventure simulation must be chunk-independent deterministic');
assert.equal(C.cityFingerprint(a),C.cityFingerprint(b),'city layer must remain deterministic beneath adventure');
assert.equal(S.societyFingerprint(a),S.societyFingerprint(b),'society layer must remain deterministic beneath adventure');
assert.equal(H.historyFingerprint(a),H.historyFingerprint(b),'history layer must remain deterministic beneath adventure');
assert.ok(a.adventure.sites.length>=10,'long history should contain a useful site catalog');
assert.ok(a.adventure.stats.roomsGenerated>=a.adventure.sites.length*5,'room generation accounting');
assert.ok(a.adventure.snapshots.length>20&&a.adventure.snapshots.length<100,'compact timeline snapshots');
const d=A.dungeonDetail(a,a.adventure.sites[0].id,300);
assert.ok(d&&d.rooms.length&&d.edges.length,'dungeon detail exposes room graph');
assert.ok(d.loot.every(l=>Number.isInteger(l.roomId)),'loot must be placed in rooms');
const historical=A.viewAt(a,100);
assert.ok(historical.year<=100&&historical.sites.length>0,'historical adventure replay');
const raw=E.serialize(a),restored=E.deserialize(raw);H.initialize(restored);S.initialize(restored);C.initialize(restored);A.initialize(restored);
assert.deepEqual(A.validateAdventure(restored),[],'save/export preserves adventure state');
assert.equal(A.adventureFingerprint(restored),A.adventureFingerprint(a),'adventure save identity');
console.log('WorldForge v0.5 deterministic adventure tests passed.');
console.log(JSON.stringify({year:a.adventure.currentYear,sites:a.adventure.sites.length,active:A.currentView(a).stats.sites,known:A.currentView(a).stats.known,rooms:A.currentView(a).stats.rooms,expeditions:a.adventure.stats.expeditions,clears:a.adventure.stats.clears,fingerprint:A.adventureFingerprint(a)}));