import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js','knowledge-engine.js','calendar-engine.js','artifact-engine.js','artifact-wiki-adapter.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,Adv=global.WorldForgeAdventure,Story=global.WorldForgeStory,W=global.WorldForgeWiki,Cult=global.WorldForgeCulture,F=global.WorldForgeFactions,K=global.WorldForgeKnowledge,Cal=global.WorldForgeCalendar,A=global.WorldForgeArtifacts;
assert.ok(E&&H&&S&&C&&Adv&&Story&&W&&Cult&&F&&K&&Cal&&A,'v1.6 artifact dependencies must load');
const opts={seed:'TREASURY-OF-MEMORY-TEST',width:120,height:70,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5};
function make(){const w=E.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);Adv.initialize(w);Story.initialize(w);Cult.initialize(w);F.initialize(w);K.initialize(w);Cal.initialize(w);A.initialize(w);return w}
const world=make();
const war={id:world.history.events.length,year:world.history.currentYear,absoluteYear:25,type:'war',importance:3,realmIds:[0,1],settlementIds:[0],personIds:[],title:'War of the Broken Seal',text:'Two crowns contest the river crossing after a disputed charter.'};
world.history.events.push(war);K.sync(world);A.sync(world);
const item=world.artifacts.items.find(x=>x.sourceEventKey===K.eventKey(world,war));
assert.ok(item,'major historical event must generate a persistent artifact');
assert.ok(item.claimKeys.length===1,'event artifact must link to the objective knowledge claim');
assert.ok(world.knowledge.sources.some(s=>s.artifactId===item.id),'written/material historical objects must be able to become knowledge sources');
assert.ok(item.provenance.length>=1&&item.provenance[0].action==='created','artifact must begin with provenance');
const claimKey=item.claimKeys[0];
const chronicle=A.createArtifact(world,{kind:'chronicle',name:'Chronicle of the Broken Seal',createdYear:25,originSettlementId:0,originRealmId:0,ownerType:'realm',ownerId:0,claimKeys:[claimKey],contents:'A court history of the river war.',prestige:91,durability:.9,authenticity:.94,copies:9});
assert.equal(chronicle.written,true,'chronicles must be classified as written works');
assert.ok(world.knowledge.sources.some(s=>s.artifactId===chronicle.id),'written work must carry an evidentiary source');
A.transfer(world,chronicle.id,'person',0,'gifted to court historian',40);assert.equal(A.find(world,chronicle.id).ownerType,'person');
const site=world.adventure.sites[0];assert.ok(site,'adventure layer must provide at least one possible lost site');
A.lose(world,chronicle.id,site.id,'hidden during a palace evacuation',80);assert.equal(A.find(world,chronicle.id).status,'lost');assert.equal(A.find(world,chronicle.id).siteId,site.id);
const sourcesBefore=world.knowledge.sources.filter(s=>s.artifactId===chronicle.id).length;
A.rediscover(world,chronicle.id,'realm',1,220,'recovered from a sealed library chamber');
assert.equal(A.find(world,chronicle.id).status,'held','rediscovery must restore artifact custody');
assert.ok(world.knowledge.sources.filter(s=>s.artifactId===chronicle.id).length>sourcesBefore,'rediscovery must add fresh material evidence to surviving claims');
assert.ok(world.history.events.some(e=>e.type==='artifact_rediscovered'&&(e.artifactIds||[]).includes(chronicle.id)),'rediscovery must enter world history');
assert.ok(A.find(world,chronicle.id).provenance.some(p=>p.action==='rediscovered'),'rediscovery must enter provenance');
const wikiArtifact=W.article(world,`artifact:${chronicle.id}`);assert.ok(wikiArtifact&&wikiArtifact.type==='artifact','artifacts must enter the Universal Encyclopedia');
assert.ok(W.search(world,'Broken Seal',{type:'artifact',limit:20}).some(x=>x.id===chronicle.id),'artifact wiki search must find written works');
assert.ok(W.chronology(world,`artifact:${chronicle.id}`).some(e=>e.type==='artifact_rediscovered'),'artifact wiki chronology must expose provenance');
Cal.setBaseSimulator(C.simulateYears.bind(C));A.setBaseSimulator(Cal.simulateYears.bind(C));
const direct=make(),chunked=make();A.simulateYears(direct,90);A.simulateYears(chunked,30);A.simulateYears(chunked,25);A.simulateYears(chunked,35);
assert.equal(A.fingerprint(direct),A.fingerprint(chunked),'artifact lifecycle must be chunk independent');
assert.equal(H.historyFingerprint(direct),H.historyFingerprint(chunked),'artifact-enabled world history must remain deterministic');
assert.ok(A.summary(direct).total>0,'long simulation must produce historical objects');
const archiveWorld=make();archiveWorld.endless={epochOffset:2200,baseSeed:opts.seed,absoluteYear:2200};A.initialize(archiveWorld).settings.retainDetailedYears=100;for(let i=0;i<80;i++){const x=A.createArtifact(archiveWorld,{kind:i%2?'letter':'coin',name:`Discarded Object ${i}`,createdYear:i,originSettlementId:0,originRealmId:0,ownerType:'realm',ownerId:0,prestige:20});A.lose(archiveWorld,x.id,null,'forgotten',i+2);x.prestige=20}archiveWorld.artifacts.settings.maxDetailedItems=30;A.compact(archiveWorld);assert.ok(archiveWorld.artifacts.archives.length>0&&archiveWorld.artifacts.stats.archived>0,'old low-prestige objects must compact into bounded era archives');assert.ok(archiveWorld.artifacts.items.length<=30,'artifact detail budget must be enforced');
assert.deepEqual(A.validate(world),[],'artifact state must validate');const fp=A.fingerprint(world),restored=E.deserialize(E.serialize(world));A.initialize(restored);assert.deepEqual(A.validate(restored),[],'artifact state must survive world save/export');assert.equal(A.fingerprint(restored),fp,'artifact fingerprint must survive save/export round-trip');
console.log('WorldForge v1.6 Artifacts, Books & Written Works regression tests passed.');
console.log(JSON.stringify({artifacts:A.summary(world).total,written:A.summary(world).written,knowledgeSources:world.artifacts.stats.knowledgeSources,rediscovered:world.artifacts.stats.rediscovered,archives:archiveWorld.artifacts.archives.length,fingerprint:fp}));