import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','calendar-engine.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,Cal=global.WorldForgeCalendar;
assert.ok(E&&H&&S&&C&&Cal,'v1.5 calendar dependencies must load');
const opts={seed:'LIVING-ALMANAC-TEST',width:120,height:70,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5};
const make=()=>{const w=E.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);Cal.initialize(w);return w};
Cal.setBaseSimulator(C.simulateYears.bind(C));
const direct=make(),chunked=make();
Cal.simulateYears(direct,180);
Cal.simulateYears(chunked,60);Cal.simulateYears(chunked,45);Cal.simulateYears(chunked,75);
assert.equal(Cal.fingerprint(direct),Cal.fingerprint(chunked),'calendar simulation must be chunk independent');
assert.equal(H.historyFingerprint(direct),H.historyFingerprint(chunked),'climate feedback must remain deterministic across chunks');
assert.equal(Cal.absoluteYear(direct),180,'calendar must follow the simulation clock');
assert.deepEqual(Cal.validate(direct),[],'calendar state must validate');
assert.equal(direct.calendarClimate.profiles.length,direct.settlements.length,'every settlement must have a climate profile');
assert.equal(direct.calendarClimate.current.settlement.length,direct.settlements.length,'every settlement must have annual weather');
const almanac=Cal.almanac(direct,0,180);assert.equal(almanac.months.length,12,'almanac must expose all twelve months');
assert.equal(almanac.months.reduce((n,m)=>n+(m.month===11?35:30),0),365,'calendar must contain 365 days');
assert.ok(almanac.months.some(m=>m.season==='Winter')&&almanac.months.some(m=>m.season==='Summer'),'local calendar must contain seasons');
const date=Cal.dateInfo(direct,0,180,5,15);assert.ok(date.moonPhase&&date.weekday,'calendar date must expose moon phase and weekday');
assert.ok(Number.isFinite(date.daylightHours)&&date.daylightHours>=0&&date.daylightHours<=24,'daylight model must stay physical');
const stats=direct.calendarClimate.stats;assert.ok(stats.years===180,'all simulated years must pass through climate feedback');
assert.ok(direct.calendarClimate.phenomena.length>0,'long simulations must record climate or celestial phenomena');
assert.ok(direct.history.events.some(e=>['drought','flood','great_storm','harsh_winter','heatwave','good_harvest','eclipse','comet','aurora'].includes(e.type)),'climate must create real history events');
const control=E.generateWorld(opts);H.initialize(control);S.initialize(control);C.initialize(control);C.simulateYears(control,180);
assert.notEqual(H.historyFingerprint(direct),H.historyFingerprint(control),'harvest and weather feedback must alter later world history');
const beforeArchives=direct.calendarClimate.archives.length;direct.calendarClimate.settings.retainDetailedYears=80;Cal.simulateYears(direct,100);assert.ok(direct.calendarClimate.archives.length>beforeArchives,'old climate detail must compact into era archives');
assert.ok(direct.calendarClimate.yearSummaries.length<230,'climate detail must remain bounded after compaction');
const fp=Cal.fingerprint(direct),restored=E.deserialize(E.serialize(direct));Cal.initialize(restored);assert.deepEqual(Cal.validate(restored),[],'calendar state must survive world save/export');assert.equal(Cal.fingerprint(restored),fp,'calendar fingerprint must survive save/export round-trip');
console.log('WorldForge v1.5 Calendar, Seasons, Weather & Celestial regression tests passed.');
console.log(JSON.stringify({year:Cal.absoluteYear(direct),phenomena:direct.calendarClimate.phenomena.length,archives:direct.calendarClimate.archives.length,droughts:stats.droughts,floods:stats.floods,eclipses:stats.eclipses,comets:stats.comets,fingerprint:fp}));