import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,Culture=global.WorldForgeCulture,F=global.WorldForgeFactions,C=global.WorldForgeCreatorSuite,B=global.WorldForgeCanonBridge;
assert.ok(E&&H&&S&&Culture&&F&&C&&B,'canon bridge dependencies must load');
const world=E.generateWorld({seed:'LIVING-CANON-TEST',width:120,height:70,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5});
H.initialize(world);S.initialize(world);Culture.initialize(world);F.initialize(world);C.initialize(world);B.initialize(world);
const startPeople=world.society.people.length;
const char=C.createDocument(world,{type:'Character',title:'Aria Vale',summary:'Explorer of the eastern marches.',refs:['settlement:0'],fields:{age:31,occupation:'Explorer',prestige:66}});
const charResult=B.materializeDocument(world,char.id);
assert.ok(charResult.ok&&charResult.entityRef.startsWith('person:'),'character card must materialize as a person');
assert.equal(world.society.people.length,startPeople+1,'materialized NPC must enter society state');
assert.equal(world.creatorSuite.documents[char.id].fields.canonEntityRef,charResult.entityRef,'card must store its live entity link');
const oldRealm=world.history.current.settlementKingdomIds[1];
const realm=C.createDocument(world,{type:'Lore',title:'Kingdom of Aster',tags:['realm'],refs:['settlement:1'],fields:{stability:70}});
const realmResult=B.materializeDocument(world,realm.id);
assert.ok(realmResult.ok&&realmResult.entityRef.startsWith('realm:'),'realm lore must materialize as a real realm');
const realmId=Number(realmResult.entityRef.split(':')[1]);
assert.equal(world.history.current.settlementKingdomIds[1],realmId,'authored realm must own its founding settlement');
assert.notEqual(realmId,oldRealm,'authored realm must be a new political entity');
assert.equal(world.history.current.realmState[realmId].active,true,'authored realm must be active in simulation state');
const cultureDoc=C.createDocument(world,{type:'Culture',title:'Asteri',refs:['settlement:1'],fields:{language:'Asteric'}});
const cultureResult=B.materializeDocument(world,cultureDoc.id);assert.ok(cultureResult.ok&&cultureResult.entityRef.startsWith('culture:'));
assert.equal(world.culture.settlementCultureIds[1],Number(cultureResult.entityRef.split(':')[1]),'authored culture must become locally dominant');
const faithDoc=C.createDocument(world,{type:'Deity',title:'The Lantern Covenant',refs:['settlement:1'],fields:{doctrine:'Monotheist'}});
const faithResult=B.materializeDocument(world,faithDoc.id);assert.ok(faithResult.ok&&faithResult.entityRef.startsWith('religion:'));
assert.equal(world.culture.settlementReligionIds[1],Number(faithResult.entityRef.split(':')[1]),'authored faith must enter religion simulation');
const orgDoc=C.createDocument(world,{type:'Organization',title:'Aster Cartographers',refs:['settlement:1'],fields:{organizationType:'Scholar Society',influence:58}});
const orgResult=B.materializeDocument(world,orgDoc.id);assert.ok(orgResult.ok&&orgResult.entityRef.startsWith('organization:'));
assert.equal(world.factions.organizations.at(-1).name,'Aster Cartographers','authored organization must enter faction simulation');
const location=C.createDocument(world,{type:'Location',title:'Glass Observatory',refs:['settlement:1'],summary:'A high observatory above the capital.'});
const landmarkResult=B.materializeDocument(world,location.id);assert.ok(landmarkResult.ok&&landmarkResult.entityRef.startsWith('landmark:'));
assert.ok(world.creatorSuite.mapAnnotations.some(a=>a.canonEntityRef===landmarkResult.entityRef),'materialized landmark must create a map annotation');
const event={id:world.history.events.length,year:world.history.currentYear,type:'war',importance:3,realmIds:[0,realmId],settlementIds:[1],personIds:[Number(charResult.entityRef.split(':')[1])],title:'War of the Lantern Road',text:'A frontier war erupts along the eastern road.'};world.history.events.push(event);
const beforeDocs=world.creatorSuite.documents.length,beforeTimeline=world.creatorSuite.timelineEvents.length,beforeMap=world.creatorSuite.mapAnnotations.length;
const sync1=B.syncSimulationToAuthoring(world);
assert.ok(world.creatorSuite.documents.length>beforeDocs,'major simulation event must generate an authoring card');
assert.ok(world.creatorSuite.timelineEvents.length>beforeTimeline,'major simulation event must generate a timeline entry');
assert.ok(world.creatorSuite.mapAnnotations.length>beforeMap,'major simulation event must generate a map note');
assert.ok(world.canonBridge.suggestions.some(s=>s.title==='War of the Lantern Road'),'major event must create a Quill story suggestion');
const counts=[world.creatorSuite.documents.length,world.creatorSuite.timelineEvents.length,world.creatorSuite.mapAnnotations.length,world.canonBridge.suggestions.length];
B.syncSimulationToAuthoring(world);
assert.deepEqual([world.creatorSuite.documents.length,world.creatorSuite.timelineEvents.length,world.creatorSuite.mapAnnotations.length,world.canonBridge.suggestions.length],counts,'event sync must be idempotent');
const sug=world.canonBridge.suggestions.find(s=>s.title==='War of the Lantern Road');const story=B.promoteSuggestionToStory(world,sug.id);assert.ok(story&&story.sourceEventKey===sug.eventKey,'story suggestion must become a linked Quill draft');
B.refreshLinkedDocuments(world);assert.match(world.creatorSuite.documents[char.id].fields.liveSnapshot,/Explorer/,'linked card must receive a non-destructive live simulation snapshot');
assert.deepEqual(B.validate(world),[],'canon bridge state must validate');
const fp=B.fingerprint(world),restored=E.deserialize(E.serialize(world));C.initialize(restored);B.initialize(restored);assert.deepEqual(B.validate(restored),[],'canon bridge must survive save/export');assert.equal(B.fingerprint(restored),fp,'canon bridge fingerprint must survive round-trip');
console.log('WorldForge Living Canon Bridge regression tests passed.');
console.log(JSON.stringify({links:world.canonBridge.links.length,realms:world.history.realms.length,cultures:world.culture.cultures.length,religions:world.culture.religions.length,organizations:world.factions.organizations.length,synced:sync1.synced,suggestions:world.canonBridge.suggestions.length,fingerprint:fp}));