import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','endless-engine.js','living-wiki-engine.js','creator-suite-engine.js','chronicle-press-engine.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,P=global.WorldForgeChroniclePress;
assert.ok(E&&H&&P,'v1.3 dependencies must load');
const world=E.generateWorld({seed:'HERALDRY-PRESS-TEST',width:120,height:70,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5});
const first=P.issue(world);
assert.ok(first.publication&&first.era&&first.headline,'press identity must exist');
assert.ok(first.heraldry.length>=3,'active realms need heraldry');
assert.ok(first.heraldry.every(h=>h.svg.includes('<svg')&&h.svg.includes('wf-heraldry-svg')),'heraldry must be SVG');
assert.equal(P.fingerprint(world),P.fingerprint(world),'press output must be deterministic');
assert.deepEqual(P.validate(world),[],'v1.3 base issue validates');
const h=H.initialize(world);
const active=h.current.realmState.filter(Boolean).filter(r=>r.active).slice(0,3).map(r=>r.id);
assert.ok(active.length>=3,'test world needs realms');
h.wars.push({id:0,attackerId:active[0],defenderId:active[1],startYear:h.currentYear,endYear:null,score:0,captures:[],cause:'test conflict'});
h.wars.push({id:1,attackerId:active[1],defenderId:active[2],startYear:h.currentYear,endYear:null,score:0,captures:[],cause:'test conflict'});
h.current.activeWarIds=[0,1];
h.events.push({id:h.events.length,year:h.currentYear,type:'war',importance:3,realmIds:[active[0],active[1]],title:'The Test Banner War',text:'Two realms enter open conflict.'});
h.events.push({id:h.events.length,year:h.currentYear,type:'conquest',importance:3,realmIds:[active[1],active[2]],title:'The Red Ford Falls',text:'A frontier changes hands.'});
const iron=P.issue(world);
assert.equal(iron.theme.id,'iron','multiple active wars should drive Iron Chronicle');
assert.equal(iron.publication,'The Iron Gazette','iron age publication name');
assert.match(iron.era,/Many-Banner|Iron Years/,'dynamic era title should reflect war');
assert.ok(iron.heraldry.some(x=>x.atWar),'war participants should show war banners');
const html=P.issueHTML(world);
assert.match(html,/The Iron Gazette/);assert.match(html,/wf-heraldry-svg/);assert.match(html,/WORLD AT A GLANCE/);
const doc=P.archiveIssue(world);
assert.ok(doc&&doc.tags.includes('chronicle-press'),'issue should archive into Creator canon');
assert.equal(P.archiveIssue(world).id,doc.id,'archiving same issue must be idempotent');
assert.deepEqual(P.validate(world),[],'war issue validates');
console.log('WorldForge v1.3 Heraldry & Chronicle Press regression tests passed.');
console.log(JSON.stringify({publication:iron.publication,era:iron.era,heraldry:iron.heraldry.length,warBanners:iron.heraldry.filter(x=>x.atWar).length,fingerprint:P.fingerprint(world)}));