import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,C=global.WorldForgeCreatorSuite;
assert.ok(E&&C,'core and creator suite must load');
const world=E.generateWorld({seed:'CREATOR-SUITE-TEST',width:120,height:70,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5});
C.initialize(world);C.starterPack(world);
assert.ok(world.creatorSuite.documents.length>=2,'starter cards');
assert.ok(world.creatorSuite.stories.length>=1,'starter story');
const card=C.createDocument(world,{type:'Character',title:'Aria Vale',body:'Explorer and chronicler.',published:true,tags:['hero']});
assert.equal(C.searchDocuments(world,'Aria')[0].id,card.id);
C.updateDocument(world,card.id,{summary:'A linked protagonist.'});assert.equal(world.creatorSuite.documents[card.id].summary,'A linked protagonist.');
const ann=C.createAnnotation(world,{kind:'marker',name:'Old Tower',x:12,y:20});assert.equal(ann.kind,'marker');
const zone=C.createAnnotation(world,{kind:'zone',name:'Ashlands',x:20,y:20,radius:8});assert.equal(zone.radius,8);
const rel=C.createRelationship(world,{from:'person:0',to:'realm:0',type:'serves'});assert.ok(rel);
assert.ok(C.derivedRelationships(world).length>=1,'relationship graph should have edges');
const ev=C.createTimelineEvent(world,{year:42,title:'The Lantern Pact'});assert.ok(C.timeline(world).some(x=>x.title==='The Lantern Pact'));
const board=C.createMoodBoard(world,{title:'Tone'});C.addMoodCard(world,board.id,{kind:'text',title:'Mood',content:'Ancient amber ruins'});assert.equal(board.cards.length,1);
const story=C.createStory(world,{title:'A Road in Winter'});C.addChapter(world,story.id,'The Crossing');C.addStoryBlock(world,story.id,1,{type:'dialogue',text:'Who goes there?',effect:'whisper',audioUrl:'https://example.invalid/line.ogg'});C.publishStory(world,story.id,true);assert.ok(C.readerModel(world).stories.some(x=>x.id===story.id));
const sheet=C.createCharacterSheet(world,{name:'Kest',className:'Ranger',abilities:{dex:16}});assert.equal(C.abilityMod(sheet.abilities.dex),3);
const route=C.createTradeRoute(world,{from:0,to:1,goods:['iron','cloth']});assert.ok(route&&route.distance>0);
C.createHomebrewDoc(world,{title:'Rest Rule',body:'Camp before recovery.'});C.addAudio(world,{title:'Forest',url:'https://example.invalid/forest.ogg'});
assert.deepEqual(C.validate(world),[],'creator suite validates');
const fp=C.fingerprint(world);const restored=E.deserialize(E.serialize(world));assert.deepEqual(C.validate(restored),[],'creator suite survives save/export');assert.equal(C.fingerprint(restored),fp,'creator suite fingerprint survives round-trip');
console.log('WorldForge Creator Toolkit regression tests passed.');
console.log(JSON.stringify({documents:world.creatorSuite.documents.length,annotations:world.creatorSuite.mapAnnotations.length,relationships:C.derivedRelationships(world).length,stories:world.creatorSuite.stories.length,published:C.readerModel(world).documents.length+C.readerModel(world).stories.length,fingerprint:fp}));