import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','culture-engine.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCulture;
assert.ok(E&&H&&S&&C,'v0.7 engines must load');
const options={seed:'CULTURE-GATE-07',width:120,height:70,seaLevel:.53,age:'mature',settlementTarget:35,kingdomTarget:6};
const make=()=>{const w=E.generateWorld(options);H.initialize(w);S.initialize(w);C.initialize(w);return w};
const a=make(),b=make();
assert.deepEqual(C.validate(a),[],'Year 0 culture state must validate');
assert.ok(a.culture.cultures.length>=4,'multiple cultures must exist');
assert.ok(a.culture.religions.length>=3,'multiple religions must exist');
assert.equal(a.culture.settlementCultureIds.length,a.settlements.length);
assert.equal(a.culture.settlementReligionIds.length,a.settlements.length);
assert.ok(a.culture.cultures.every(x=>x.traditions.length>=3&&x.values.length>=2),'cultures need traditions and values');
assert.ok(a.culture.religions.every(x=>x.tenets.length>=3&&x.holySiteIds.length),'religions need tenets and holy sites');
C.simulateYears(a,300);C.simulateYears(b,100);C.simulateYears(b,75);C.simulateYears(b,125);
assert.equal(a.history.currentYear,300);assert.equal(a.culture.currentYear,300);
assert.deepEqual(C.validate(a),[],'long-run culture state must validate');
assert.equal(C.fingerprint(a),C.fingerprint(b),'culture simulation must be chunk-independent deterministic');
assert.ok(a.culture.snapshots.length>20,'culture replay snapshots must accumulate');
assert.ok(a.culture.stats.cultureShifts+a.culture.stats.conversions+a.culture.stats.schisms>=0,'cultural dynamics stats must exist');
const v=C.viewAt(a,100);assert.ok(v.year<=100&&v.cultures.length>=4,'historical culture view must resolve');
const raw=E.serialize(a),restored=E.deserialize(raw);H.initialize(restored);S.initialize(restored);C.initialize(restored);assert.deepEqual(C.validate(restored),[]);assert.equal(C.fingerprint(restored),C.fingerprint(a),'culture must survive save/export');
console.log('WorldForge v0.7 culture & religion tests passed.');
console.log(JSON.stringify({year:a.culture.currentYear,cultures:a.culture.cultures.length,religions:a.culture.religions.length,shifts:a.culture.stats.cultureShifts,conversions:a.culture.stats.conversions,schisms:a.culture.stats.schisms,fingerprint:C.fingerprint(a)}));