import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js','knowledge-engine.js','calendar-engine.js','artifact-engine.js','artifact-wiki-adapter.js','technology-engine.js','technology-wiki-adapter.js','resource-engine.js','resource-calibration.js','resource-wiki-adapter.js','institution-engine.js','institution-wiki-adapter.js','military-engine.js','military-wiki-adapter.js','treasury-engine.js','treasury-wiki-adapter.js','workforce-engine.js','workforce-calibration.js','workforce-wiki-adapter.js','household-engine.js','household-wiki-adapter.js','housing-engine.js','housing-wiki-adapter.js','municipal-engine.js','municipal-wiki-adapter.js','emergency-engine.js','emergency-wiki-adapter.js','nutrition-engine.js','nutrition-wiki-adapter.js','politics-engine.js','politics-wiki-adapter.js','diplomacy-engine.js','diplomacy-wiki-adapter.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const Eng=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,F=global.WorldForgeFactions,Cal=global.WorldForgeCalendar,A=global.WorldForgeArtifacts,Tech=global.WorldForgeTechnology,R=global.WorldForgeResources,I=global.WorldForgeInstitutions,Mil=global.WorldForgeMilitary,T=global.WorldForgeTreasury,W=global.WorldForgeWorkforce,HH=global.WorldForgeHouseholds,HG=global.WorldForgeHousing,M=global.WorldForgeMunicipal,E=global.WorldForgeEmergency,N=global.WorldForgeNutrition,P=global.WorldForgePolitics,D=global.WorldForgeDiplomacy,Wiki=global.WorldForgeWiki;
assert.ok(Eng&&H&&S&&C&&F&&Cal&&A&&Tech&&R&&I&&Mil&&T&&W&&HH&&HG&&M&&E&&N&&P&&D&&Wiki,'v2.9 dependencies must load');
assert.ok(W.__laborCalibration&&W.__householdBridge&&W.__housingBridge&&W.__municipalBridge&&W.__emergencyBridge&&W.__nutritionBridge&&W.__politicsBridge&&W.__diplomacyBridge,'v2.9 bridge chain must attach after politics');
assert.deepEqual(Object.keys(D.TREATY_TYPES).sort(),['alliance','defensive_pact','embargo','humanitarian_aid','non_aggression','peace_treaty','sanctions','trade_agreement'].sort(),'v2.9 treaty catalogue must be complete');
Cal.setBaseSimulator(C.simulateYears.bind(C));A.setBaseSimulator(Cal.simulateYears.bind(Cal));Tech.setBaseSimulator(A.simulateYears.bind(A));R.setBaseSimulator(Tech.simulateYears.bind(Tech));I.setBaseSimulator(R.simulateYears.bind(R));Mil.setBaseSimulator(I.simulateYears.bind(I));T.setBaseSimulator(Mil.simulateYears.bind(Mil));W.setBaseSimulator(T.simulateYears.bind(T));
const opts={seed:'DIPLOMACY-V29-TEST',width:112,height:68,seaLevel:.53,age:'mature',settlementTarget:32,kingdomTarget:5};
function setup(){const w=Eng.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);F.initialize(w);Cal.initialize(w);A.initialize(w);Tech.initialize(w);R.initialize(w);I.initialize(w);Mil.initialize(w);T.initialize(w);W.initialize(w);HH.initialize(w);HG.initialize(w);M.initialize(w);E.initialize(w);N.initialize(w);P.initialize(w);D.initialize(w);w.diplomacy.settings.autoTreaties=false;for(const m of w.resources.markets){for(const id of R.FOOD_IDS){m.inventory[id]=Math.max(Number(m.inventory[id]||0),Math.max(70,Number(w.history.current.settlementPopulation[m.settlementId]||100)*.014));m.prices[id]=R.MAP.get(id).basePrice;m.shortages[id]=0}m.foodSecurity=1;m.foodDays=365}W.simulateWorkforceYear(w,W.absYear(w));return w}
const w=setup(),ids=w.history.current.realmState.filter(Boolean).map(x=>x.id),expected=ids.length*(ids.length-1)/2,sum=D.summary(w);
assert.deepEqual(D.validate(w),[],'initial diplomacy state must validate');
assert.equal(w.diplomacy.relations.length,expected,'every active realm pair must receive exactly one diplomatic relation');
assert.equal(w.diplomacy.realms.length,ids.length,'every active realm must receive a foreign-policy profile');
assert.equal(sum.relations,expected,'summary must report relation coverage');
for(const r of w.diplomacy.relations){for(const k of ['trust','fear','rivalry','tradeDependence','borderTension','claimPressure','diplomaticTension','warRisk','allianceAffinity'])assert.ok(r[k]>=0&&r[k]<=1,`${k} must be bounded`);assert.ok(r.goodwill>=-1&&r.goodwill<=1,'goodwill must be bounded');assert.ok(r.tradeAccess>=0&&r.tradeAccess<=1.4,'trade access must be bounded')}
const first=w.diplomacy.relations[0];
assert.equal(Wiki.article(w,`diplomatic_relation:${first.key}`,D.absYear(w))?.type,'diplomatic_relation','diplomatic relations must enter Universal Encyclopedia');
assert.ok(Wiki.search(w,'diplomacy trust',{type:'diplomatic_relation',year:D.absYear(w)}).length>0,'diplomatic relations must be searchable');
const beforePerf=D.performance(w);for(let i=0;i<100;i++)D.relationView(w,first.realmA,first.realmB);const afterPerf=D.performance(w);assert.equal(afterPerf.cacheBuilds,beforePerf.cacheBuilds,'repeated diplomatic reads must reuse runtime indexes');
const sameFp=D.fingerprint(w),sameTreasury=JSON.stringify(w.treasury.realms.map(x=>[x.realmId,x.treasury,x.tariffRate])),samePolitics=P.fingerprint(w);D.simulateDiplomacyYear(w,D.absYear(w));assert.equal(D.fingerprint(w),sameFp,'same-year diplomacy simulation must be idempotent');assert.equal(JSON.stringify(w.treasury.realms.map(x=>[x.realmId,x.treasury,x.tariffRate])),sameTreasury,'same-year diplomacy must not move treasury twice');assert.equal(P.fingerprint(w),samePolitics,'same-year diplomacy must not repeat political feedback');
W.simulateYears(w,3);assert.deepEqual(R.validate(w),[],'resources must remain valid under diplomacy');assert.deepEqual(P.validate(w),[],'politics must remain valid under diplomacy');assert.deepEqual(D.validate(w),[],'diplomacy must remain valid after simulation');assert.ok(w.diplomacy.annual.length>=4,'diplomatic annual ledger must advance with simulation');
const direct=setup(),chunked=setup();W.simulateYears(direct,4);W.simulateYears(chunked,2);W.simulateYears(chunked,2);assert.equal(D.fingerprint(direct),D.fingerprint(chunked),'diplomacy simulation must be deterministic across caller chunk sizes');assert.equal(P.fingerprint(direct),P.fingerprint(chunked),'diplomacy feedback must preserve political chunk determinism');assert.equal(R.fingerprint(direct),R.fingerprint(chunked),'diplomatic trade feedback must preserve resource chunk determinism');assert.equal(W.fingerprint(direct),W.fingerprint(chunked),'diplomacy feedback must preserve workforce chunk determinism');
const fp=D.fingerprint(w),restored=Eng.deserialize(Eng.serialize(w));W.initialize(restored);HH.initialize(restored);HG.initialize(restored);M.initialize(restored);E.initialize(restored);N.initialize(restored);P.initialize(restored);D.initialize(restored);assert.deepEqual(D.validate(restored),[],'diplomacy state must survive save/export');assert.equal(D.fingerprint(restored),fp,'diplomacy fingerprint must survive save/export round-trip');
// Treaties must create material, fiscal and political consequences rather than decorative labels.
const policy=setup(),pair=policy.diplomacy.relations[0],a=pair.realmA,b=pair.realmB;
D.signTreaty(policy,'trade_agreement',a,b,D.absYear(policy),{strength:.9,duration:12});assert.ok(D.treatyActive(policy,'trade_agreement',a,b),'trade agreement must become active');assert.equal(Wiki.article(policy,`treaty:${policy.diplomacy.treaties.at(-1).id}`,D.absYear(policy))?.type,'treaty','treaties must enter Universal Encyclopedia');
const targetMarkets=policy.resources.markets.filter(m=>policy.history.current.settlementKingdomIds[m.settlementId]===b),priceBefore=targetMarkets.reduce((n,m)=>n+R.COMMODITIES.reduce((q,c)=>q+Number(m.prices[c.id]||0),0),0);D.imposeEmbargo(policy,a,b,D.absYear(policy),{strength:.9});D.simulateDiplomacyYear(policy,D.absYear(policy)+1);const priceAfter=targetMarkets.reduce((n,m)=>n+R.COMMODITIES.reduce((q,c)=>q+Number(m.prices[c.id]||0),0),0);assert.ok(priceAfter>priceBefore,'embargo must raise target market price pressure');assert.ok(D.relationView(policy,a,b).tradeAccess<1,'embargo must restrict diplomatic trade access');assert.ok(policy.politics.realms.find(x=>x.realmId===b).grievance>0,'embargo must feed domestic political grievance');
// Humanitarian diplomacy must spend donor treasury and move real food reserves into a crisis realm.
const aid=setup(),aidPair=aid.diplomacy.relations[0],donor=aidPair.realmA,target=aidPair.realmB,targetProfiles=aid.nutrition.profiles.filter(p=>aid.history.current.settlementKingdomIds[p.settlementId]===target);for(const p of targetProfiles){p.famineStage=4;p.famineStageName='Famine';p.malnutritionRate=.62;p.reliefNeeded=3}const targetMs=aid.resources.markets.filter(m=>aid.history.current.settlementKingdomIds[m.settlementId]===target);for(const m of targetMs){for(const id of R.FOOD_IDS)m.inventory[id]=0;m.foodSecurity=.1;m.foodDays=12}const donorAccount=aid.treasury.realms.find(x=>x.realmId===donor),treasuryBefore=donorAccount.treasury,foodBefore=targetMs.reduce((n,m)=>n+N.foodBasket(m).stockEquivalent,0);D.sendHumanitarianAid(aid,donor,target,D.absYear(aid),{strength:1});D.simulateDiplomacyYear(aid,D.absYear(aid)+1);const foodAfter=targetMs.reduce((n,m)=>n+N.foodBasket(m).stockEquivalent,0);assert.ok(donorAccount.treasury<treasuryBefore,'humanitarian aid must spend donor treasury');assert.ok(foodAfter>foodBefore,'humanitarian aid must move real food reserves to the recipient');assert.ok(aid.diplomacy.incidents.some(i=>i.type==='humanitarian_aid'&&i.toRealmId===target),'humanitarian transfer must be recorded');
// Severe rivalry and claims must become a measurable international security crisis.
const crisis=setup(),rel=crisis.diplomacy.relations[0];Object.assign(rel,{trust:.04,goodwill:-.82,fear:.78,rivalry:.96,borderTension:.92,claimPressure:.9,diplomaticTension:.88});D.simulateDiplomacyYear(crisis,D.absYear(crisis)+1);const rv=D.relationView(crisis,rel.realmA,rel.realmB);assert.ok(rv.diplomaticTension>.6,'extreme hostility must sustain high diplomatic tension');assert.ok(rv.warRisk>.5,'extreme hostility must create high war risk');assert.deepEqual(D.validate(crisis),[],'international crisis must remain numerically valid');
console.log('WorldForge v2.9 Diplomacy, Treaties, Trade Agreements & International Relations regression tests passed.');
console.log(JSON.stringify({...D.summary(w),performance:D.performance(w),fingerprint:fp}));