import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js','knowledge-engine.js','calendar-engine.js','artifact-engine.js','artifact-wiki-adapter.js','technology-engine.js','technology-wiki-adapter.js','resource-engine.js','resource-calibration.js','resource-wiki-adapter.js','institution-engine.js','institution-wiki-adapter.js','military-engine.js','military-wiki-adapter.js','treasury-engine.js','treasury-wiki-adapter.js','workforce-engine.js','workforce-calibration.js','workforce-wiki-adapter.js','household-engine.js','household-wiki-adapter.js','housing-engine.js','housing-wiki-adapter.js','municipal-engine.js','municipal-wiki-adapter.js','emergency-engine.js','emergency-wiki-adapter.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const Eng=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,Cal=global.WorldForgeCalendar,A=global.WorldForgeArtifacts,Tech=global.WorldForgeTechnology,R=global.WorldForgeResources,I=global.WorldForgeInstitutions,Mil=global.WorldForgeMilitary,T=global.WorldForgeTreasury,W=global.WorldForgeWorkforce,HH=global.WorldForgeHouseholds,HG=global.WorldForgeHousing,M=global.WorldForgeMunicipal,E=global.WorldForgeEmergency,Wiki=global.WorldForgeWiki;
assert.ok(Eng&&H&&S&&C&&Cal&&A&&Tech&&R&&I&&Mil&&T&&W&&HH&&HG&&M&&E&&Wiki,'v2.6 dependencies must load');
assert.ok(W.__laborCalibration&&W.__householdBridge&&W.__housingBridge&&W.__municipalBridge&&W.__emergencyBridge,'v2.6 bridge chain must attach after municipal services');
assert.equal(E.PATHOGENS.length,5,'v2.6 must expose deterministic disease families');
Cal.setBaseSimulator(C.simulateYears.bind(C));A.setBaseSimulator(Cal.simulateYears.bind(Cal));Tech.setBaseSimulator(A.simulateYears.bind(A));R.setBaseSimulator(Tech.simulateYears.bind(Tech));I.setBaseSimulator(R.simulateYears.bind(R));Mil.setBaseSimulator(I.simulateYears.bind(I));T.setBaseSimulator(Mil.simulateYears.bind(Mil));W.setBaseSimulator(T.simulateYears.bind(T));
const opts={seed:'EMERGENCY-V26-TEST',width:110,height:66,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5};
function setup(){const w=Eng.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);Cal.initialize(w);A.initialize(w);Tech.initialize(w);R.initialize(w);I.initialize(w);Mil.initialize(w);T.initialize(w);W.initialize(w);HH.initialize(w);HG.initialize(w);M.initialize(w);E.initialize(w);for(const m of w.resources.markets){for(const id of ['grain','rice','fish','livestock','timber','iron','copper','salt','coal','wine'])m.inventory[id]=Math.max(Number(m.inventory[id]||0),2500)}W.simulateWorkforceYear(w,W.absYear(w));return w}
const w=setup(),sum=E.summary(w);
assert.deepEqual(E.validate(w),[],'initial emergency state must validate');
assert.equal(w.emergency.profiles.length,w.settlements.length,'every settlement must receive an emergency profile');
assert.ok(sum.meanPreparedness>=0&&sum.meanPreparedness<=1,'preparedness must stay bounded');
for(const p of w.emergency.profiles){assert.ok(p.hazards.disease>=0&&p.hazards.disease<=1,'disease hazard must be bounded');assert.ok(p.hazards.fire>=0&&p.hazards.fire<=1,'fire hazard must be bounded');assert.ok(p.disease.severity>=0&&p.disease.severity<=1,'outbreak severity must be bounded');assert.ok(p.fire.severity>=0&&p.fire.severity<=1,'fire severity must be bounded')}
const sid=w.emergency.profiles[0].settlementId;
assert.ok(Wiki.article(w,`emergency_status:${sid}`,E.absYear(w))?.type==='emergency_status','emergency readiness must enter Universal Encyclopedia');
assert.ok(Wiki.search(w,'preparedness fire',{type:'emergency_status',year:E.absYear(w)}).length>0,'emergency status must be searchable');
const beforePerf=E.performance(w);for(let i=0;i<80;i++)E.settlementView(w,sid);const afterPerf=E.performance(w);assert.equal(afterPerf.cacheBuilds,beforePerf.cacheBuilds,'repeated emergency reads must reuse runtime indexes');
const sameFp=E.fingerprint(w),sameTreasury=JSON.stringify(w.treasury.realms.map(x=>[x.realmId,x.treasury])),samePop=JSON.stringify(w.history.current.settlementPopulation);E.simulateEmergencyYear(w,E.absYear(w));assert.equal(E.fingerprint(w),sameFp,'same-year emergency simulation must be idempotent');assert.equal(JSON.stringify(w.treasury.realms.map(x=>[x.realmId,x.treasury])),sameTreasury,'same-year emergency simulation must not charge response finance twice');assert.equal(JSON.stringify(w.history.current.settlementPopulation),samePop,'same-year emergency simulation must not repeat casualties');
W.simulateYears(w,3);assert.deepEqual(M.validate(w),[],'municipal services must remain valid under emergency feedback');assert.deepEqual(E.validate(w),[],'emergency state must remain valid after simulation');assert.ok(w.emergency.annual.length>=4,'emergency annual ledger must advance with simulation');
const direct=setup(),chunked=setup();W.simulateYears(direct,4);W.simulateYears(chunked,2);W.simulateYears(chunked,2);assert.equal(E.fingerprint(direct),E.fingerprint(chunked),'emergency simulation must be deterministic across caller chunk sizes');assert.equal(M.fingerprint(direct),M.fingerprint(chunked),'emergency feedback must preserve municipal chunk determinism');assert.equal(HG.fingerprint(direct),HG.fingerprint(chunked),'emergency feedback must preserve housing chunk determinism');assert.equal(HH.fingerprint(direct),HH.fingerprint(chunked),'emergency feedback must preserve household chunk determinism');assert.equal(W.fingerprint(direct),W.fingerprint(chunked),'emergency feedback must preserve workforce chunk determinism');
const fp=E.fingerprint(w),restored=Eng.deserialize(Eng.serialize(w));W.initialize(restored);HH.initialize(restored);HG.initialize(restored);M.initialize(restored);E.initialize(restored);assert.deepEqual(E.validate(restored),[],'emergency state must survive save/export');assert.equal(E.fingerprint(restored),fp,'emergency fingerprint must survive save/export round-trip');
const stressed=setup(),stressSid=stressed.emergency.profiles.find(p=>stressed.municipal.profiles.find(x=>x.settlementId===p.settlementId))?.settlementId??0,mp=stressed.municipal.profiles.find(x=>x.settlementId===stressSid),hp=stressed.housing.profiles.find(x=>x.settlementId===stressSid);mp.healthRisk=1;mp.fireRisk=1;mp.coverage.water=0;mp.coverage.sanitation=0;mp.coverage.fire=0;mp.coverage.healthcare=Math.min(.2,Number(mp.coverage.healthcare||0));hp.overcrowdingRate=1;hp.slumShare=.65;hp.densityIndex=1.4;stressed.emergency.lastAppliedYear=null;const stressYear=E.absYear(stressed)+1;E.simulateEmergencyYear(stressed,stressYear);assert.ok(stressed.emergency.incidents.some(i=>i.year===stressYear&&i.settlementId===stressSid&&i.type==='disease_outbreak'),'high health risk must be able to generate a disease outbreak');assert.ok(stressed.emergency.incidents.some(i=>i.year===stressYear&&i.settlementId===stressSid&&i.type==='urban_fire'),'high fire risk must generate an urban fire');assert.ok(stressed.history.events.some(e=>e.absoluteYear===stressYear&&e.type==='urban_fire'),'major urban fires must enter History');
console.log('WorldForge v2.6 Health, Disease, Fire & Emergency Response regression tests passed.');
console.log(JSON.stringify({...E.summary(w),performance:E.performance(w),fingerprint:fp}));