import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','culture-engine.js','faction-engine.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,Ci=global.WorldForgeCity,Cu=global.WorldForgeCulture,F=global.WorldForgeFactions;
assert.ok(E&&H&&S&&Ci&&Cu&&F,'v0.8 engines must load');
const options={seed:'FACTION-GATE-08',width:120,height:70,seaLevel:.53,age:'mature',settlementTarget:35,kingdomTarget:6};
const make=()=>{const w=E.generateWorld(options);H.initialize(w);S.initialize(w);Ci.initialize(w);Cu.initialize(w);F.initialize(w);return w};
const a=make(),b=make();
assert.deepEqual(F.validate(a),[],'Year 0 faction state must validate');
assert.ok(a.factions.organizations.length>=10,'seed organizations must exist');
assert.ok(a.factions.organizations.some(o=>o.memberIds.length),'organizations need named members');
assert.ok(a.factions.organizations.every(o=>F.TYPES.includes(o.type)),'organization types must be recognized');
assert.ok(a.factions.organizations.every(o=>a.culture.cultures[o.cultureId]&&a.culture.religions[o.religionId]),'organizations must link to culture and religion');
F.simulateYears(a,250);F.simulateYears(b,100);F.simulateYears(b,75);F.simulateYears(b,75);
assert.equal(a.history.currentYear,250);assert.equal(a.factions.currentYear,250);assert.equal(a.culture.currentYear,250);
assert.deepEqual(F.validate(a),[],'long-run faction state must remain valid');
assert.equal(F.fingerprint(a),F.fingerprint(b),'faction simulation must be chunk-independent deterministic');
assert.ok(a.factions.snapshots.length>20,'faction timeline snapshots must accumulate');
assert.ok(a.factions.organizations.some(o=>o.influence!==0),'organizations must evolve influence');
assert.ok(a.factions.stats.formed>=10,'formation stats must be retained');
const v=F.viewAt(a,100);assert.ok(v.year<=100&&v.organizations.length,'historical faction view must resolve');
const raw=E.serialize(a),restored=E.deserialize(raw);H.initialize(restored);S.initialize(restored);Ci.initialize(restored);Cu.initialize(restored);F.initialize(restored);assert.deepEqual(F.validate(restored),[]);assert.equal(F.fingerprint(restored),F.fingerprint(a),'factions must survive save/export');
console.log('WorldForge v0.8 factions & organizations tests passed.');
console.log(JSON.stringify({year:a.factions.currentYear,total:a.factions.organizations.length,active:F.currentView(a).metrics.active,members:F.currentView(a).metrics.members,conflicts:a.factions.stats.conflicts,contracts:a.factions.stats.contracts,uprisings:a.factions.stats.uprisings,fingerprint:F.fingerprint(a)}));