import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js','knowledge-engine.js','calendar-engine.js','artifact-engine.js','artifact-wiki-adapter.js','technology-engine.js','technology-wiki-adapter.js','resource-engine.js','resource-calibration.js','resource-wiki-adapter.js','institution-engine.js','institution-wiki-adapter.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,Adv=global.WorldForgeAdventure,Story=global.WorldForgeStory,W=global.WorldForgeWiki,Cult=global.WorldForgeCulture,F=global.WorldForgeFactions,K=global.WorldForgeKnowledge,Cal=global.WorldForgeCalendar,A=global.WorldForgeArtifacts,T=global.WorldForgeTechnology,R=global.WorldForgeResources,I=global.WorldForgeInstitutions;
assert.ok(E&&H&&S&&C&&Adv&&Story&&W&&Cult&&F&&K&&Cal&&A&&T&&R&&I,'v1.9 institution dependencies must load');
const opts={seed:'CIVIC-FOUNDRY-TEST',width:120,height:70,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5};
function make(){const w=E.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);Adv.initialize(w);Story.initialize(w);Cult.initialize(w);F.initialize(w);K.initialize(w);Cal.initialize(w);A.initialize(w);T.initialize(w);R.initialize(w);I.initialize(w);return w}
Cal.setBaseSimulator(C.simulateYears.bind(C));A.setBaseSimulator(Cal.simulateYears.bind(C));T.setBaseSimulator(A.simulateYears.bind(A));R.setBaseSimulator(T.simulateYears.bind(T));I.setBaseSimulator(R.simulateYears.bind(R));
const direct=make(),chunked=make();I.simulateYears(direct,60);I.simulateYears(chunked,20);I.simulateYears(chunked,15);I.simulateYears(chunked,25);
assert.equal(I.fingerprint(direct),I.fingerprint(chunked),'institution simulation must be chunk independent');
assert.equal(H.historyFingerprint(direct),H.historyFingerprint(chunked),'institution-enabled history must remain deterministic');
assert.deepEqual(I.validate(direct),[],'institution state must validate');
const sum=I.summary(direct);assert.ok(sum.facilities>=direct.settlements.length*2,'every settlement must have civic infrastructure');
for(const s of direct.settlements){const types=new Set(I.facilitiesAt(direct,s.id).map(x=>x.typeId));assert.ok(types.has('market_hall')&&types.has('granary'),`${s.name} must have a market hall and granary`)}
const totals=I.productTotals(direct);assert.ok(Object.values(totals).some(x=>x.stock>0||x.production>0),'physical production chains must create processed goods');
const sid=0,m=R.market(direct,sid);for(const id of ['grain','salt','timber','iron','coal','wine'])m.inventory[id]=Number(m.inventory[id]||0)+5000;m.processed=m.processed||{};m.processed.lumber=500;m.processed.steel=500;
for(const type of ['mill','bakery','sawmill','foundry','smithy','shipyard','library','university','museum','hospital'])I.makeFacility(direct,type,sid,I.absYear(direct));I.simulateInstitutionYear(direct,I.absYear(direct)+1);
const local=I.settlementView(direct,sid);assert.ok(local.products.find(x=>x.product.id==='flour').production>0,'mill must convert staple grain into flour');assert.ok(local.products.find(x=>x.product.id==='bread').production>0,'bakery must convert flour and salt into bread');assert.ok(local.products.find(x=>x.product.id==='steel').production>0,'foundry must convert iron and coal into steel');assert.ok(local.products.find(x=>x.product.id==='weapons').production>0,'smithy must convert steel and lumber into weapons');assert.ok(local.products.find(x=>x.product.id==='ships').production>0,'shipyard must convert lumber and steel into ships');
const realmId=direct.history.current.settlementKingdomIds[sid],great=I.beginGreatWork(direct,realmId,'great_library',sid,1000);assert.ok(great,'a realm must be able to commission a Great Library');const gm=R.market(direct,sid);for(const id of ['timber','iron','copper'])gm.inventory[id]=10000;gm.processed.lumber=10000;gm.processed.steel=10000;for(let y=1001;y<1060&&great.status!=='active';y++)I.simulateInstitutionYear(direct,y);assert.equal(great.status,'active','Great Work construction must consume materials and complete');
const gf=I.facility(direct,great.facilityId);assert.ok(gf&&gf.greatWorkId==='great_library','completed Great Work must remain a first-class institution entity');const greatArticle=W.article(direct,`greatwork:${gf.id}`,1060);assert.ok(greatArticle&&greatArticle.type==='greatwork','Great Works must enter the Universal Encyclopedia');const instArticle=W.article(direct,`institution:${gf.id}`,1060);assert.ok(instArticle&&instArticle.type==='institution','institutions must enter the Universal Encyclopedia');
I.simulateInstitutionYear(direct,1061);if(!gf.collection.sourceIds.length){const claim=direct.knowledge.claims.find(c=>c.sourceIds?.length)||direct.knowledge.claims[0];if(claim){K.addSource(direct,claim.key,{kind:'scholar',originRealmId:realmId,reliability:.92,archiveStrength:.9,text:'A preserved civic copy for the Great Library.'});I.simulateInstitutionYear(direct,1062)}}assert.ok(gf.collection.sourceIds.length>0,'Great Library must preserve documentary sources');const sourceId=gf.collection.sourceIds[0],source=direct.knowledge.sources.find(x=>x.id===sourceId),claim=direct.knowledge.claims.find(x=>x.key===source?.claimKey);I.damageInstitution(direct,gf.id,1,'siege fire',1063);assert.equal(gf.status,'destroyed','forced catastrophic damage must destroy an institution');assert.ok(source?.destroyedYear===1063,'destroying a Great Library must physically destroy preserved evidence');if(claim)assert.ok(!claim.sourceIds.includes(sourceId),'destroyed library evidence must disappear from the live claim evidence graph');assert.ok(direct.infrastructure.stats.knowledgeLost>0,'knowledge destruction must be counted');
const museum=I.facilitiesAt(direct,sid).find(x=>x.typeId==='museum'&&x.status==='active');if(museum&&direct.artifacts.items.length){I.simulateInstitutionYear(direct,1064);assert.ok(museum.collection.artifactIds.length>=0,'museum collection state must be persistent')}
const assets=direct.infrastructure.realmAssets[String(realmId)];assert.ok(assets&&assets.weapons>=0&&assets.ships>=0&&assets.research>=0,'institutions must expose realm-level strategic assets for future military/logistics simulation');
const archive=make();archive.infrastructure.currentYear=5000;archive.infrastructure.settings.retainDetailedYears=100;archive.infrastructure.annual=[];for(let y=0;y<700;y++)archive.infrastructure.annual.push({year:y,active:40+y%5,greatWorks:y%80===0?1:0,processed:100+y,knowledgePreserved:y});I.compact(archive);assert.ok(archive.infrastructure.archives.length>0&&archive.infrastructure.stats.archivedYears>0,'old institutional detail must compact into bounded era archives');
const fp=I.fingerprint(direct),restored=E.deserialize(E.serialize(direct));I.initialize(restored);assert.deepEqual(I.validate(restored),[],'institution state must survive world save/export');assert.equal(I.fingerprint(restored),fp,'institution fingerprint must survive save/export round-trip');
console.log('WorldForge v1.9 Institutions, Industry & Great Works regression tests passed.');
console.log(JSON.stringify({year:I.absYear(direct),facilities:I.summary(direct).facilities,greatWorks:I.summary(direct).greatWorks,products:I.PRODUCTS.length,knowledgeLost:direct.infrastructure.stats.knowledgeLost,ships:I.summary(direct).shipsBuilt,weapons:I.summary(direct).weaponsMade,archives:archive.infrastructure.archives.length,fingerprint:fp}));