import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','endless-engine.js','creator-suite-engine.js','canon-bridge-engine.js','release-integration.js','canon-wiki-adapter.js','living-wiki-engine.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,C=global.WorldForgeCulture,F=global.WorldForgeFactions,X=global.WorldForgeEndless,L=global.WorldForgeLivingWiki;
assert.ok(E&&H&&C&&F&&X&&L,'Living Wiki dependencies must load');
const world=E.generateWorld({seed:'LIVING-WIKI-TEST',width:120,height:70,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5});
X.initialize(world);C.initialize(world);F.initialize(world);
const first=L.model(world);
assert.ok(L.THEME_IDS.includes(first.theme.id),'theme must be valid');
assert.ok(first.groups.length>4,'wiki should expose multiple shelves');
assert.ok(first.narrative.includes(world.name),'world pulse narrative should name world');
const html=L.exportHTML(world);
assert.ok(html.startsWith('<!doctype html>'),'HTML export is standalone');
assert.ok(html.includes('WORLDFORGE LIVING WIKI'),'HTML export has living wiki masthead');
assert.ok(html.includes('Search the archive'),'HTML export has client-side search');
assert.ok(html.includes(world.name),'HTML export includes world name');
assert.deepEqual(L.validate(world),[],'Living Wiki validates');
const fp=L.fingerprint(world);
assert.equal(L.fingerprint(world),fp,'theme fingerprint is deterministic without state changes');
// Force a severe active-war state and verify the adaptive classifier reacts.
world.history.current.activeWarIds=[0,1];
world.history.wars[0]={id:0,attackerId:0,defenderId:1,startYear:0,endYear:null,score:0,captures:[]};
world.history.wars[1]={id:1,attackerId:2,defenderId:3,startYear:0,endYear:null,score:0,captures:[]};
for(let i=0;i<5;i++)world.history.events.push({id:world.history.events.length,year:world.history.currentYear,type:'war',importance:3,title:`Test War ${i}`,text:'A major conflict reshapes the political order.',realmIds:[i%4,(i+1)%4]});
const war=L.analyze(world);
assert.equal(war.theme.id,'iron','multiple active wars should produce the Iron Chronicle');
assert.ok(war.topEvents.some(e=>e.type==='war'),'war chronicle should feature recent war events');
const warHtml=L.exportHTML(world);
assert.ok(warHtml.includes('Age of Iron'),'export must reflect current simulation theme');
console.log('WorldForge Living Wiki regression tests passed.');
console.log(JSON.stringify({initialTheme:first.theme.id,warTheme:war.theme.id,groups:first.groups.length,articles:first.total,fingerprint:fp,htmlBytes:html.length}));