import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js','knowledge-engine.js','calendar-engine.js','artifact-engine.js','artifact-wiki-adapter.js','technology-engine.js','technology-wiki-adapter.js','resource-engine.js','resource-calibration.js','resource-wiki-adapter.js','institution-engine.js','institution-wiki-adapter.js','military-engine.js','military-wiki-adapter.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,Adv=global.WorldForgeAdventure,Story=global.WorldForgeStory,W=global.WorldForgeWiki,Cult=global.WorldForgeCulture,F=global.WorldForgeFactions,K=global.WorldForgeKnowledge,Cal=global.WorldForgeCalendar,A=global.WorldForgeArtifacts,T=global.WorldForgeTechnology,R=global.WorldForgeResources,I=global.WorldForgeInstitutions,M=global.WorldForgeMilitary;
assert.ok(E&&H&&S&&C&&Adv&&Story&&W&&Cult&&F&&K&&Cal&&A&&T&&R&&I&&M,'v2.0 military dependencies must load');
Cal.setBaseSimulator(C.simulateYears.bind(C));A.setBaseSimulator(Cal.simulateYears.bind(C));T.setBaseSimulator(A.simulateYears.bind(A));R.setBaseSimulator(T.simulateYears.bind(T));I.setBaseSimulator(R.simulateYears.bind(R));M.setBaseSimulator(I.simulateYears.bind(I));
const opts={seed:'WAR-ROOM-V2-TEST',width:120,height:70,seaLevel:.54,age:'mature',settlementTarget:32,kingdomTarget:5};
function forceCoast(w,sid){const s=w.settlements[sid],W=w.settings.width,H=w.settings.height,sea=w.settings.seaLevel;for(let oy=-2;oy<=2;oy++)for(let ox=-2;ox<=2;ox++){if(!ox&&!oy)continue;const y=Math.max(0,Math.min(H-1,Math.round(s.y)+oy)),x=(Math.round(s.x)+ox+W)%W;if(Math.abs(ox)===2||Math.abs(oy)===2)w.layers.elevation[y*W+x]=Math.min(Number(w.layers.elevation[y*W+x]||1),sea-.08)}}
function setup(){const w=E.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);Adv.initialize(w);Story.initialize(w);Cult.initialize(w);F.initialize(w);K.initialize(w);Cal.initialize(w);A.initialize(w);T.initialize(w);const active=w.history.current.realmState.filter(Boolean).filter(x=>x.active);assert.ok(active.length>=2,'test world requires two realms');const ra=active[0].id,rb=active[1].id,sa=w.history.current.settlementKingdomIds.findIndex(x=>x===ra),sb=w.history.current.settlementKingdomIds.findIndex(x=>x===rb);assert.ok(sa>=0&&sb>=0,'belligerents need settlements');forceCoast(w,sa);forceCoast(w,sb);R.initialize(w);I.initialize(w);for(const m of w.resources.markets){for(const id of ['grain','rice','fish','livestock','timber','iron','copper','salt','coal','wine'])m.inventory[id]=Math.max(Number(m.inventory[id]||0),5000);m.processed=m.processed||{};Object.assign(m.processed,{weapons:500,ships:20,lumber:500,steel:500,bread:100,medicine:50})}w.institutions.realmAssets[String(ra)]={weapons:120,ships:20,tools:30,research:5,health:5,logistics:12};w.institutions.realmAssets[String(rb)]={weapons:120,ships:20,tools:30,research:5,health:5,logistics:12};const id=w.history.wars.length;w.history.wars.push({id,attackerId:ra,defenderId:rb,startYear:w.history.currentYear,endYear:null,score:0,captures:[],cause:'operational regression'});w.history.current.activeWarIds.push(id);M.initialize(w);M.syncWars(w);return{w,warId:id,ra,rb,sa,sb}}
const one=setup();const w=one.w;assert.deepEqual(M.validate(w),[],'initial military state must validate');assert.ok(w.military.armies.filter(x=>x.warId===one.warId&&x.status==='active').length>=2,'active war must raise field armies for both belligerents');assert.ok(w.military.fleets.filter(x=>x.warId===one.warId&&x.status==='active').length>=2,'coastal belligerents with ships must raise fleets');
const a0=w.military.armies.find(x=>x.warId===one.warId&&x.realmId===one.ra),b0=w.military.armies.find(x=>x.warId===one.warId&&x.realmId===one.rb),f0=w.military.fleets.find(x=>x.warId===one.warId&&x.realmId===one.ra),g0=w.military.fleets.find(x=>x.warId===one.warId&&x.realmId===one.rb);assert.ok(a0&&b0&&f0&&g0);const grainBefore=R.market(w,a0.homeSettlementId).inventory.grain,posBefore={x:a0.x,y:a0.y};M.simulateYears(w,1);assert.ok(R.market(w,a0.homeSettlementId).inventory.grain<grainBefore,'field army logistics must physically consume food stocks');assert.ok(Math.hypot(a0.x-posBefore.x,a0.y-posBefore.y)>0,'field armies must move across the world map');assert.ok(Array.isArray(a0.supplyPath)&&a0.supplyOriginId!=null,'army must maintain an explicit supply origin and path');
// Pin both units at the same frontline while keeping legal enemy targets. This exercises combat independent of strategic travel time.
a0.x=w.settlements[one.sb].x+.5;a0.y=w.settlements[one.sb].y+.5;a0.targetSettlementId=one.sb;a0.currentNodeId=one.sb;a0.route=[one.sb];a0.pathIndex=0;a0.segmentProgress=0;a0.size=Math.max(a0.size,9000);a0.supply=1;b0.x=a0.x;b0.y=a0.y;b0.targetSettlementId=one.sa;b0.currentNodeId=one.sa;b0.route=[one.sa];b0.pathIndex=0;b0.segmentProgress=0;b0.size=Math.max(b0.size,8500);b0.supply=1;M.simulateMilitaryYear(w,M.absYear(w)+1);assert.ok(w.military.battles.some(x=>x.type==='land'),'opposing field armies in contact must generate a physical battle');assert.ok(w.military.sieges.some(x=>x.settlementId===one.sb),'an army reaching an enemy settlement must create a siege operation');
// Co-locate the two belligerents' test ports so fleet movement cannot skip the contact-resolution branch.
w.settlements[one.sa].x=(w.settlements[one.sb].x+1)%w.settings.width;w.settlements[one.sa].y=w.settlements[one.sb].y;f0.x=w.settlements[one.sb].x+.5;f0.y=w.settlements[one.sb].y+.5;f0.targetSettlementId=one.sb;f0.hulls=Math.max(f0.hulls,6);f0.supply=1;g0.x=w.settlements[one.sa].x+.5;g0.y=w.settlements[one.sa].y+.5;g0.targetSettlementId=one.sa;g0.hulls=Math.max(g0.hulls,5);g0.supply=1;const enemyMarket=R.market(w,one.sb);enemyMarket.imports=enemyMarket.imports||{};enemyMarket.imports.grain=200;enemyMarket.inventory.grain=Math.max(enemyMarket.inventory.grain,1000);const deniedBefore=w.military.stats.cargoDenied;M.simulateMilitaryYear(w,M.absYear(w)+2);assert.ok(w.military.battles.some(x=>x.type==='naval'),'opposing fleets in contact must generate a naval battle');const survivingRa=w.military.fleets.find(x=>x.realmId===one.ra&&x.warId===one.warId&&x.status==='active');if(survivingRa){survivingRa.x=w.settlements[one.sb].x+.5;survivingRa.y=w.settlements[one.sb].y+.5;survivingRa.targetSettlementId=one.sb;enemyMarket.imports.grain=250;enemyMarket.inventory.grain=Math.max(enemyMarket.inventory.grain,1000);M.simulateMilitaryYear(w,M.absYear(w)+3)}assert.ok(w.military.blockades.some(x=>x.settlementId===one.sb),'fleet at an enemy coastal settlement must establish a blockade');assert.ok(w.military.stats.cargoDenied>deniedBefore,'blockade must physically deny market cargo');
const armyArticle=W.article(w,`army:${a0.id}`);assert.ok(armyArticle&&armyArticle.type==='army','field armies must enter the Universal Encyclopedia');const siege=w.military.sieges.find(x=>x.settlementId===one.sb),siegeArticle=W.article(w,`siege:${siege.id}`,siege.startYear);assert.ok(siegeArticle&&siegeArticle.type==='siege','sieges must enter the Universal Encyclopedia at their historical year');assert.deepEqual(M.validate(w),[],'post-operation military state must validate');
// Deterministic caller chunking check on a fresh war.
const d=setup(),c=setup();M.simulateYears(d.w,4);M.simulateYears(c.w,2);M.simulateYears(c.w,2);assert.equal(M.fingerprint(d.w),M.fingerprint(c.w),'operational simulation must be deterministic across caller chunk sizes');assert.equal(H.historyFingerprint(d.w),H.historyFingerprint(c.w),'military pressure must not make history chunk-dependent');
const fp=M.fingerprint(w),restored=E.deserialize(E.serialize(w));M.initialize(restored);assert.deepEqual(M.validate(restored),[],'military state must survive save/export');assert.equal(M.fingerprint(restored),fp,'military fingerprint must survive save/export round-trip');
console.log('WorldForge v2.0 Armies, Fleets, Sieges & Military Logistics regression tests passed.');
console.log(JSON.stringify({...M.summary(w),armies:w.military.armies.length,fleets:w.military.fleets.length,sieges:w.military.sieges.length,blockades:w.military.blockades.length,fingerprint:fp}));