import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js','knowledge-engine.js','calendar-engine.js','artifact-engine.js','artifact-wiki-adapter.js','technology-engine.js','technology-wiki-adapter.js','resource-engine.js','resource-calibration.js','resource-wiki-adapter.js','institution-engine.js','institution-wiki-adapter.js','military-engine.js','military-wiki-adapter.js','treasury-engine.js','treasury-wiki-adapter.js','workforce-engine.js','workforce-calibration.js','workforce-wiki-adapter.js','household-engine.js','household-wiki-adapter.js','housing-engine.js','housing-wiki-adapter.js','municipal-engine.js','municipal-wiki-adapter.js','emergency-engine.js','emergency-wiki-adapter.js','nutrition-engine.js','nutrition-wiki-adapter.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const Eng=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,Cal=global.WorldForgeCalendar,A=global.WorldForgeArtifacts,Tech=global.WorldForgeTechnology,R=global.WorldForgeResources,I=global.WorldForgeInstitutions,Mil=global.WorldForgeMilitary,T=global.WorldForgeTreasury,W=global.WorldForgeWorkforce,HH=global.WorldForgeHouseholds,HG=global.WorldForgeHousing,M=global.WorldForgeMunicipal,E=global.WorldForgeEmergency,N=global.WorldForgeNutrition,Wiki=global.WorldForgeWiki;
assert.ok(Eng&&H&&S&&C&&Cal&&A&&Tech&&R&&I&&Mil&&T&&W&&HH&&HG&&M&&E&&N&&Wiki,'v2.7 dependencies must load');
assert.ok(W.__laborCalibration&&W.__householdBridge&&W.__housingBridge&&W.__municipalBridge&&W.__emergencyBridge&&W.__nutritionBridge,'v2.7 bridge chain must attach after emergency response');
assert.equal(N.STAGES.length,6,'v2.7 must expose six bounded food-security stages');
// Rebuild the established simulator chain exactly as release regressions do.
Cal.setBaseSimulator(C.simulateYears.bind(C));A.setBaseSimulator(Cal.simulateYears.bind(Cal));Tech.setBaseSimulator(A.simulateYears.bind(A));R.setBaseSimulator(Tech.simulateYears.bind(Tech));I.setBaseSimulator(R.simulateYears.bind(R));Mil.setBaseSimulator(I.simulateYears.bind(I));T.setBaseSimulator(Mil.simulateYears.bind(Mil));W.setBaseSimulator(T.simulateYears.bind(T));
const opts={seed:'NUTRITION-V27-TEST',width:110,height:66,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5};
function setup(){const w=Eng.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);Cal.initialize(w);A.initialize(w);Tech.initialize(w);R.initialize(w);I.initialize(w);Mil.initialize(w);T.initialize(w);W.initialize(w);HH.initialize(w);HG.initialize(w);M.initialize(w);E.initialize(w);N.initialize(w);for(const m of w.resources.markets){for(const id of R.FOOD_IDS){m.inventory[id]=Math.max(Number(m.inventory[id]||0),Math.max(60,Number(w.history.current.settlementPopulation[m.settlementId]||100)*.012));m.prices[id]=R.MAP.get(id).basePrice;m.shortages[id]=0}m.foodSecurity=1;m.foodDays=365}W.simulateWorkforceYear(w,W.absYear(w));return w}
const w=setup(),sum=N.summary(w);
assert.deepEqual(N.validate(w),[],'initial nutrition state must validate');
assert.equal(w.nutrition.profiles.length,w.settlements.length,'every settlement must receive a nutrition profile');
assert.ok(sum.meanNutrition>=0&&sum.meanNutrition<=1,'mean nutrition must stay bounded');
for(const p of w.nutrition.profiles){assert.ok(p.nutritionIndex>=0&&p.nutritionIndex<=1,'nutrition index must be bounded');assert.ok(p.malnutritionRate>=0&&p.malnutritionRate<=1,'malnutrition must be bounded');assert.ok(p.famineStage>=0&&p.famineStage<=5,'famine stage must be bounded')}
const sid=w.nutrition.profiles[0].settlementId;
assert.equal(Wiki.article(w,`nutrition_status:${sid}`,N.absYear(w))?.type,'nutrition_status','nutrition status must enter Universal Encyclopedia');
assert.ok(Wiki.search(w,'food nutrition',{type:'nutrition_status',year:N.absYear(w)}).length>0,'nutrition status must be searchable');
const beforePerf=N.performance(w);for(let i=0;i<80;i++)N.settlementView(w,sid);const afterPerf=N.performance(w);assert.equal(afterPerf.cacheBuilds,beforePerf.cacheBuilds,'repeated nutrition reads must reuse runtime indexes');
const sameFp=N.fingerprint(w),sameTreasury=JSON.stringify(w.treasury.realms.map(x=>[x.realmId,x.treasury])),samePop=JSON.stringify(w.history.current.settlementPopulation),sameFood=JSON.stringify(w.resources.markets.map(m=>R.FOOD_IDS.map(id=>m.inventory[id])));N.simulateNutritionYear(w,N.absYear(w));assert.equal(N.fingerprint(w),sameFp,'same-year nutrition simulation must be idempotent');assert.equal(JSON.stringify(w.treasury.realms.map(x=>[x.realmId,x.treasury])),sameTreasury,'same-year nutrition simulation must not charge relief finance twice');assert.equal(JSON.stringify(w.history.current.settlementPopulation),samePop,'same-year nutrition simulation must not repeat deaths');assert.equal(JSON.stringify(w.resources.markets.map(m=>R.FOOD_IDS.map(id=>m.inventory[id]))),sameFood,'same-year nutrition simulation must not move relief cargo twice');
W.simulateYears(w,3);assert.deepEqual(E.validate(w),[],'emergency response must remain valid under nutrition feedback');assert.deepEqual(N.validate(w),[],'nutrition state must remain valid after simulation');assert.ok(w.nutrition.annual.length>=4,'nutrition annual ledger must advance with simulation');
const direct=setup(),chunked=setup();W.simulateYears(direct,4);W.simulateYears(chunked,2);W.simulateYears(chunked,2);assert.equal(N.fingerprint(direct),N.fingerprint(chunked),'nutrition simulation must be deterministic across caller chunk sizes');assert.equal(E.fingerprint(direct),E.fingerprint(chunked),'nutrition feedback must preserve emergency chunk determinism');assert.equal(M.fingerprint(direct),M.fingerprint(chunked),'nutrition feedback must preserve municipal chunk determinism');assert.equal(HG.fingerprint(direct),HG.fingerprint(chunked),'nutrition feedback must preserve housing chunk determinism');assert.equal(HH.fingerprint(direct),HH.fingerprint(chunked),'nutrition feedback must preserve household chunk determinism');assert.equal(W.fingerprint(direct),W.fingerprint(chunked),'nutrition feedback must preserve workforce chunk determinism');
const fp=N.fingerprint(w),restored=Eng.deserialize(Eng.serialize(w));W.initialize(restored);HH.initialize(restored);HG.initialize(restored);M.initialize(restored);E.initialize(restored);N.initialize(restored);assert.deepEqual(N.validate(restored),[],'nutrition state must survive save/export');assert.equal(N.fingerprint(restored),fp,'nutrition fingerprint must survive save/export round-trip');
// A physically exhausted, poor and besieged settlement must enter a true famine state.
const famine=setup(),fSid=famine.nutrition.profiles[0].settlementId,fm=famine.resources.markets.find(x=>x.settlementId===fSid),fh=famine.households.profiles.find(x=>x.settlementId===fSid);for(const id of R.FOOD_IDS){fm.inventory[id]=0;fm.prices[id]=R.MAP.get(id).basePrice*5.5;fm.shortages[id]=1}fm.foodSecurity=.02;fm.foodDays=1;fh.povertyRate=.82;fh.disposableIncome=-2;famine.military.sieges.push({id:'v27-test-siege',settlementId:fSid,status:'active'});famine.military.blockades.push({id:'v27-test-blockade',settlementId:fSid,status:'active'});for(const m of famine.resources.markets)if(m.settlementId!==fSid)for(const id of R.FOOD_IDS)m.inventory[id]=0;famine.nutrition.lastAppliedYear=null;const famineYear=N.absYear(famine)+1;N.simulateNutritionYear(famine,famineYear);const fpv=famine.nutrition.profiles.find(x=>x.settlementId===fSid);assert.ok(fpv.famineStage>=4,'physical staple exhaustion plus siege/blockade must create famine conditions');assert.equal(fpv.rationing,true,'famine conditions must activate rationing');assert.ok(fpv.malnutritionRate>.4,'famine must create material malnutrition');assert.ok(fpv.nutritionDeaths>0,'severe famine must create bounded excess mortality');assert.ok(famine.nutrition.incidents.some(i=>i.year===famineYear&&i.settlementId===fSid&&i.stage>=4),'famine must create a nutrition crisis incident');assert.ok(famine.history.events.some(e=>(e.absoluteYear??e.year)===famineYear&&e.type==='famine'&&(e.settlementIds||[]).includes(fSid)),'famine must enter canonical History when no resource famine event already exists');
// A shortage with a stocked donor must move physical food rather than inventing aid.
const relief=setup(),rSid=relief.nutrition.profiles[0].settlementId,recipient=relief.resources.markets.find(x=>x.settlementId===rSid),boostedDonor=relief.resources.markets.find(x=>x.settlementId!==rSid);for(const id of R.FOOD_IDS){recipient.inventory[id]=0;recipient.prices[id]=R.MAP.get(id).basePrice*4;recipient.shortages[id]=1;boostedDonor.inventory[id]=Math.max(500,Number(boostedDonor.inventory[id]||0))}recipient.foodSecurity=.08;recipient.foodDays=4;boostedDonor.foodSecurity=1.2;boostedDonor.foodDays=500;const donorBefore=new Map(relief.resources.markets.map(m=>[m.settlementId,R.FOOD_IDS.reduce((n,id)=>n+Number(m.inventory[id]||0)*(R.MAP.get(id).food||0),0)]));relief.nutrition.lastAppliedYear=null;const reliefYear=N.absYear(relief)+1;N.simulateNutritionYear(relief,reliefYear);const convoy=relief.nutrition.convoys.find(c=>c.year===reliefYear&&c.to===rSid);assert.ok(convoy&&convoy.loaded>0&&convoy.delivered>0,'humanitarian crisis with available surplus must launch a physical relief convoy');const actualDonor=relief.resources.markets.find(x=>x.settlementId===convoy.from),actualDonorAfter=R.FOOD_IDS.reduce((n,id)=>n+Number(actualDonor.inventory[id]||0)*(R.MAP.get(id).food||0),0);assert.ok(actualDonorAfter<donorBefore.get(convoy.from),'relief cargo must be removed from the actual donor physical inventory');assert.ok(relief.nutrition.profiles.find(x=>x.settlementId===rSid).reliefReceived>0,'recipient must record delivered relief');assert.deepEqual(N.validate(relief),[],'relief transfer must never create negative food inventory');
console.log('WorldForge v2.7 Food, Nutrition, Famine & Humanitarian Relief regression tests passed.');
console.log(JSON.stringify({...N.summary(w),performance:N.performance(w),fingerprint:fp}));
