import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';

global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety;
const options={seed:'PERF-AUDIT',width:160,height:90,seaLevel:.53,age:'mature',settlementTarget:45,kingdomTarget:7};
const generationStart=performance.now();
const world=E.generateWorld(options);
const generationMs=performance.now()-generationStart;
H.initialize(world);S.initialize(world);
const derivedStart=performance.now();
const historyView=H.currentView(world),historyViewAgain=H.currentView(world),pastView=H.viewAt(world,0),pastViewAgain=H.viewAt(world,0);
const societyView=S.currentView(world),societyViewAgain=S.currentView(world);
const metrics=H.metricsSeries(world),metricsAgain=H.metricsSeries(world);
const derivedMs=performance.now()-derivedStart;
assert.strictEqual(historyView,historyViewAgain,'current history views should be reused');
assert.strictEqual(pastView,pastViewAgain,'historical views should be reused');
assert.strictEqual(societyView,societyViewAgain,'current society views should be reused');
assert.strictEqual(metrics,metricsAgain,'metric series should be reused');
const simulationStart=performance.now();
S.simulateYears(world,25);
const simulationMs=performance.now()-simulationStart;
const expected=world.history.events.filter(e=>e.year<=world.history.currentYear).slice(-5);
assert.deepEqual(H.eventsThrough(world,world.history.currentYear,5),expected,'event pagination must preserve order and limit');
assert.deepEqual(H.validateHistory(world),[],'history must remain valid after benchmark simulation');
assert.deepEqual(S.validateSociety(world),[],'society must remain valid after benchmark simulation');
const report={settlements:world.settlements.length,generationMs:Number(generationMs.toFixed(2)),derivedMs:Number(derivedMs.toFixed(2)),simulation25YearsMs:Number(simulationMs.toFixed(2)),eventCount:world.history.events.length,serializedBytes:E.serialize(world).length};
console.log('performance smoke '+JSON.stringify(report));
