import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js','knowledge-engine.js','calendar-engine.js','artifact-engine.js','artifact-wiki-adapter.js','technology-engine.js','technology-wiki-adapter.js','resource-engine.js','resource-calibration.js','resource-wiki-adapter.js','institution-engine.js','institution-wiki-adapter.js','military-engine.js','military-wiki-adapter.js','treasury-engine.js','treasury-wiki-adapter.js','workforce-engine.js','workforce-calibration.js','workforce-wiki-adapter.js','household-engine.js','household-wiki-adapter.js','housing-engine.js','housing-wiki-adapter.js','municipal-engine.js','municipal-wiki-adapter.js','emergency-engine.js','emergency-wiki-adapter.js','nutrition-engine.js','nutrition-wiki-adapter.js','politics-engine.js','politics-wiki-adapter.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const Eng=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,F=global.WorldForgeFactions,Cal=global.WorldForgeCalendar,A=global.WorldForgeArtifacts,Tech=global.WorldForgeTechnology,R=global.WorldForgeResources,I=global.WorldForgeInstitutions,Mil=global.WorldForgeMilitary,T=global.WorldForgeTreasury,W=global.WorldForgeWorkforce,HH=global.WorldForgeHouseholds,HG=global.WorldForgeHousing,M=global.WorldForgeMunicipal,E=global.WorldForgeEmergency,N=global.WorldForgeNutrition,P=global.WorldForgePolitics,Wiki=global.WorldForgeWiki;
assert.ok(Eng&&H&&S&&C&&F&&Cal&&A&&Tech&&R&&I&&Mil&&T&&W&&HH&&HG&&M&&E&&N&&P&&Wiki,'v2.8 dependencies must load');
assert.ok(W.__laborCalibration&&W.__householdBridge&&W.__housingBridge&&W.__municipalBridge&&W.__emergencyBridge&&W.__nutritionBridge&&W.__politicsBridge,'v2.8 bridge chain must attach after nutrition');
assert.equal(P.STAGES.length,6,'v2.8 must expose six bounded political-order stages');
assert.deepEqual(P.BLOC_KEYS,['commoners','labor','guilds','merchants','professionals','elites'],'v2.8 must expose aggregate political blocs');
Cal.setBaseSimulator(C.simulateYears.bind(C));A.setBaseSimulator(Cal.simulateYears.bind(Cal));Tech.setBaseSimulator(A.simulateYears.bind(A));R.setBaseSimulator(Tech.simulateYears.bind(Tech));I.setBaseSimulator(R.simulateYears.bind(R));Mil.setBaseSimulator(I.simulateYears.bind(I));T.setBaseSimulator(Mil.simulateYears.bind(Mil));W.setBaseSimulator(T.simulateYears.bind(T));
const opts={seed:'POLITICS-V28-TEST',width:110,height:66,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5};
function setup(){const w=Eng.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);F.initialize(w);Cal.initialize(w);A.initialize(w);Tech.initialize(w);R.initialize(w);I.initialize(w);Mil.initialize(w);T.initialize(w);W.initialize(w);HH.initialize(w);HG.initialize(w);M.initialize(w);E.initialize(w);N.initialize(w);P.initialize(w);for(const m of w.resources.markets){for(const id of R.FOOD_IDS){m.inventory[id]=Math.max(Number(m.inventory[id]||0),Math.max(60,Number(w.history.current.settlementPopulation[m.settlementId]||100)*.012));m.prices[id]=R.MAP.get(id).basePrice;m.shortages[id]=0}m.foodSecurity=1;m.foodDays=365}W.simulateWorkforceYear(w,W.absYear(w));return w}
const w=setup(),sum=P.summary(w);
assert.deepEqual(P.validate(w),[],'initial politics state must validate');
assert.equal(w.politics.profiles.length,w.settlements.length,'every settlement must receive a political profile');
assert.equal(w.politics.realms.length,w.history.current.realmState.filter(Boolean).length,'every active realm must receive a political profile');
assert.ok(sum.meanLegitimacy>=0&&sum.meanLegitimacy<=1,'mean legitimacy must stay bounded');
for(const p of w.politics.profiles){for(const k of ['legitimacy','publicOrder','grievance','radicalization','repression','concession','protestPotential','strikePotential','riotRisk'])assert.ok(p[k]>=0&&p[k]<=1,`${k} must be bounded`);assert.ok(p.unrestStage>=0&&p.unrestStage<=5,'unrest stage must be bounded');assert.equal(Object.keys(p.blocs).length,6,'each settlement must expose six political blocs')}
const sid=w.politics.profiles[0].settlementId;
assert.equal(Wiki.article(w,`political_status:${sid}`,P.absYear(w))?.type,'political_status','political status must enter Universal Encyclopedia');
assert.ok(Wiki.search(w,'politics legitimacy',{type:'political_status',year:P.absYear(w)}).length>0,'political status must be searchable');
const beforePerf=P.performance(w);for(let i=0;i<80;i++)P.settlementView(w,sid);const afterPerf=P.performance(w);assert.equal(afterPerf.cacheBuilds,beforePerf.cacheBuilds,'repeated political reads must reuse runtime indexes');
const sameFp=P.fingerprint(w),sameTreasury=JSON.stringify(w.treasury.realms.map(x=>[x.realmId,x.treasury,x.taxRate])),sameStability=JSON.stringify(w.history.current.realmState.map(x=>x&&x.stability));P.simulatePoliticsYear(w,P.absYear(w));assert.equal(P.fingerprint(w),sameFp,'same-year political simulation must be idempotent');assert.equal(JSON.stringify(w.treasury.realms.map(x=>[x.realmId,x.treasury,x.taxRate])),sameTreasury,'same-year politics must not charge responses twice');assert.equal(JSON.stringify(w.history.current.realmState.map(x=>x&&x.stability)),sameStability,'same-year politics must not repeat stability shocks');
W.simulateYears(w,3);assert.deepEqual(N.validate(w),[],'nutrition must remain valid under political feedback');assert.deepEqual(P.validate(w),[],'politics state must remain valid after simulation');assert.ok(w.politics.annual.length>=4,'political annual ledger must advance with simulation');
const direct=setup(),chunked=setup();W.simulateYears(direct,4);W.simulateYears(chunked,2);W.simulateYears(chunked,2);assert.equal(P.fingerprint(direct),P.fingerprint(chunked),'politics simulation must be deterministic across caller chunk sizes');assert.equal(N.fingerprint(direct),N.fingerprint(chunked),'political feedback must preserve nutrition chunk determinism');assert.equal(E.fingerprint(direct),E.fingerprint(chunked),'political feedback must preserve emergency chunk determinism');assert.equal(W.fingerprint(direct),W.fingerprint(chunked),'political feedback must preserve workforce chunk determinism');
const fp=P.fingerprint(w),restored=Eng.deserialize(Eng.serialize(w));W.initialize(restored);HH.initialize(restored);HG.initialize(restored);M.initialize(restored);E.initialize(restored);N.initialize(restored);P.initialize(restored);assert.deepEqual(P.validate(restored),[],'politics state must survive save/export');assert.equal(P.fingerprint(restored),fp,'politics fingerprint must survive save/export round-trip');
// Extreme material and fiscal pressure must become genuine civil disorder and force a state response.
const crisis=setup(),cSid=crisis.politics.profiles[0].settlementId,cRid=crisis.history.current.settlementKingdomIds[cSid],cw=crisis.workforce.markets.find(x=>x.settlementId===cSid),ch=crisis.households.profiles.find(x=>x.settlementId===cSid),cn=crisis.nutrition.profiles.find(x=>x.settlementId===cSid),cm=crisis.municipal.profiles.find(x=>x.settlementId===cSid),ce=crisis.emergency.profiles.find(x=>x.settlementId===cSid),ct=crisis.treasury.realms.find(x=>x.realmId===cRid),crs=crisis.history.current.realmState[cRid];ch.povertyRate=.92;cw.unemployed=Math.round(cw.laborForce*.62);cw.employed=Math.max(0,cw.laborForce-cw.unemployed-cw.conscripted);cn.famineStage=5;cn.famineStageName='Catastrophe';cn.malnutritionRate=.82;cn.rationing=true;ct.taxRate=.3;ct.warSurcharge=.1;ct.inflation=.34;ct.debt=Math.max(500,ct.lastRevenue*14);ct.lastRevenue=Math.max(1,ct.lastRevenue);crs.stability=8;if(cm.coverage)for(const k of Object.keys(cm.coverage))cm.coverage[k]=.08;if(ce.disease)ce.disease.severity=.9;for(const o of crisis.factions.organizations.filter(x=>x.realmId===cRid&&x.type==='Rebel League'))o.influence=96;crisis.politics.lastAppliedYear=null;const cp=crisis.politics.profiles.find(x=>x.settlementId===cSid);cp.lastYear=null;const crisisYear=P.absYear(crisis)+1;P.simulatePoliticsYear(crisis,crisisYear);const cv=P.settlementView(crisis,cSid);assert.ok(cv.unrestStage>=4,'extreme food fiscal and labor pressure must create civil disorder');assert.ok(cv.grievance>.6,'extreme crisis must create material grievance');assert.ok(cv.legitimacy<.5,'extreme crisis must erode legitimacy');assert.ok(crisis.politics.incidents.some(i=>i.year===crisisYear&&i.settlementId===cSid&&['repression','concession'].includes(i.type)),'serious disorder must force a state response');assert.ok(Object.values(cv.blocs).some(b=>b.opposition>.55),'crisis must polarize at least one political bloc');assert.deepEqual(P.validate(crisis),[],'extreme political crisis must remain numerically valid');
console.log('WorldForge v2.8 Politics, Unrest, Legitimacy & Civil Disorder regression tests passed.');
console.log(JSON.stringify({...P.summary(w),performance:P.performance(w),fingerprint:fp}));
