import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','endless-engine.js','release-integration.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,Ci=global.WorldForgeCity,A=global.WorldForgeAdventure,T=global.WorldForgeStory,W=global.WorldForgeWiki,Cu=global.WorldForgeCulture,F=global.WorldForgeFactions,X=global.WorldForgeEndless,R=global.WorldForgeRelease;
assert.ok(E&&H&&S&&Ci&&A&&T&&W&&Cu&&F&&X&&R,'all v1.0 release engines must load');
Cu.setBaseSimulator(T.simulateYears.bind(T));F.setBaseSimulator(Cu.simulateYears.bind(Cu));X.setBaseSimulator(F.simulateYears.bind(F));
const options={seed:'WORLDFORGE-RELEASE-10',width:120,height:70,seaLevel:.53,age:'mature',settlementTarget:28,kingdomTarget:5};
const w=E.generateWorld(options);H.initialize(w);S.initialize(w);Ci.initialize(w);A.initialize(w);T.initialize(w);W.initialize(w);Cu.initialize(w);F.initialize(w);X.initialize(w);
X.simulateYears(w,100);
assert.equal(X.absoluteYear(w),100,'release world clock must advance');
assert.deepEqual(X.validate(w),[],'endless state must validate in release stack');
assert.deepEqual(R.validateWiki(w),[],'release encyclopedia cross-links must validate');
const cultures=R.search(w,'',{type:'culture',limit:200});
const religions=R.search(w,'',{type:'religion',limit:200});
const orgs=R.search(w,'',{type:'organization',limit:200});
assert.ok(cultures.length>=4,'cultures must be first-class encyclopedia entities');
assert.ok(religions.length>=3,'religions must be first-class encyclopedia entities');
assert.ok(orgs.length>=10,'organizations must be first-class encyclopedia entities');
const org=orgs[0],detail=R.article(w,org.ref);assert.ok(detail&&detail.refs.some(r=>r.startsWith('culture:'))&&detail.refs.some(r=>r.startsWith('religion:')),'organization article must cross-link culture and faith');
const rel=R.related(w,org.ref);assert.ok(rel.some(a=>a.type==='culture'||a.type==='religion'||a.type==='settlement'||a.type==='person'),'organization cross-links must resolve');
W.toggleBookmark(w,cultures[0].ref);W.setNote(w,cultures[0].ref,'Release integration note');assert.deepEqual(R.validateWiki(w),[],'new entity bookmarks and notes must validate');
w.endless.archive.eras.push({startYear:0,endYear:99,eventCounts:{war:4,trade_boom:7},majorEvents:[{year:42,type:'war',title:'Archived War',text:'A retained major event.'}],totalEvents:11});
const eras=R.search(w,'',{type:'era',limit:20});assert.ok(eras.some(a=>a.ref==='era:0'),'ancient era archive must be searchable');
const era=R.article(w,'era:0');assert.equal(era.data.totalEvents,11);assert.equal(R.chronology(w,'era:0').length,1,'era article must expose retained major chronology');
const md=R.exportMarkdown(w);for(const heading of['### Culture','### Religion','### Organization','### Era'])assert.ok(md.includes(heading),`${heading} must appear in final export`);assert.ok(md.includes('absolute Year 100'),'Markdown export must use absolute world time');
const raw=E.serialize(w),restored=E.deserialize(raw);H.initialize(restored);S.initialize(restored);Ci.initialize(restored);A.initialize(restored);T.initialize(restored);Cu.initialize(restored);F.initialize(restored);X.initialize(restored);W.initialize(restored);assert.equal(X.absoluteYear(restored),100);assert.ok(R.search(restored,'',{type:'culture'}).length,'release encyclopedia must survive save/export');assert.deepEqual(R.validateWiki(restored),[]);
console.log('WorldForge v1.0 final integration tests passed.');
console.log(JSON.stringify({absoluteYear:X.absoluteYear(w),articles:R.dashboard(w).total,cultures:cultures.length,religions:religions.length,organizations:orgs.length,eras:R.search(w,'',{type:'era'}).length,wikiFingerprint:R.wikiFingerprint(w)}));