import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js','knowledge-engine.js','calendar-engine.js','artifact-engine.js','artifact-wiki-adapter.js','technology-engine.js','technology-wiki-adapter.js','resource-engine.js','resource-calibration.js','resource-wiki-adapter.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,Adv=global.WorldForgeAdventure,Story=global.WorldForgeStory,W=global.WorldForgeWiki,Cult=global.WorldForgeCulture,F=global.WorldForgeFactions,K=global.WorldForgeKnowledge,Cal=global.WorldForgeCalendar,A=global.WorldForgeArtifacts,T=global.WorldForgeTechnology,R=global.WorldForgeResources;
assert.ok(E&&H&&S&&C&&Adv&&Story&&W&&Cult&&F&&K&&Cal&&A&&T&&R,'v1.8 resource dependencies must load');assert.equal(R.BALANCE_VERSION,'1.8.1','v1.8 calibrated market balance must load');
const opts={seed:'WORLD-MARKET-TEST',width:120,height:70,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5};
function make(){const w=E.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);Adv.initialize(w);Story.initialize(w);Cult.initialize(w);F.initialize(w);K.initialize(w);Cal.initialize(w);A.initialize(w);T.initialize(w);R.initialize(w);return w}
Cal.setBaseSimulator(C.simulateYears.bind(C));A.setBaseSimulator(Cal.simulateYears.bind(C));T.setBaseSimulator(A.simulateYears.bind(A));R.setBaseSimulator(T.simulateYears.bind(T));
const direct=make(),chunked=make();R.simulateYears(direct,90);R.simulateYears(chunked,30);R.simulateYears(chunked,25);R.simulateYears(chunked,35);
assert.equal(R.fingerprint(direct),R.fingerprint(chunked),'resource simulation must be chunk independent');
assert.equal(H.historyFingerprint(direct),H.historyFingerprint(chunked),'resource-enabled history must remain deterministic');
assert.deepEqual(R.validate(direct),[],'resource state must validate');
const sum=R.summary(direct);assert.equal(sum.markets,direct.settlements.length,'every settlement must have a physical market');assert.equal(sum.commodities,R.COMMODITIES.length,'commodity catalog must initialize');assert.ok(sum.meanFoodSecurity>=0,'food security must be measurable');assert.ok(direct.resources.stats.famines<direct.settlements.length*9,'normal deterministic world must not collapse into permanent famine spam');
for(const c of R.COMMODITIES){const t=R.commodityTotals(direct,c.id);assert.ok(t.stock>=0&&t.meanPrice>0,`${c.name} must maintain stock and price state`)}
const road=direct.roads[0];assert.ok(road,'test world needs a road');const src=R.market(direct,road.from),dst=R.market(direct,road.to);for(const id of R.FOOD_IDS){src.inventory[id]=id==='grain'?5000:100;dst.inventory[id]=0;src.suitability[id]=1;dst.suitability[id]=0}R.simulateResourceYear(direct,R.absYear(direct)+1);assert.ok(direct.resources.flows.some(f=>f.from===road.from&&f.to===road.to),'surplus and shortage across a road must be able to create cargo flow');
const famine=make();for(const m of famine.resources.markets)for(const id of R.FOOD_IDS){m.inventory[id]=0;m.suitability[id]=0}R.simulateResourceYear(famine,1);assert.ok(famine.history.events.some(e=>e.type==='famine'),'worldwide staple exhaustion must create real famine history');assert.ok(famine.resources.stats.famines>0,'famine statistics must be driven by physical reserves');
const grain=W.article(direct,'commodity:grain',R.absYear(direct));assert.ok(grain&&grain.type==='commodity','commodities must enter Universal Encyclopedia');const marketArticle=W.article(direct,`market:${road.from}`,R.absYear(direct));assert.ok(marketArticle&&marketArticle.type==='market','settlement markets must enter Universal Encyclopedia');
const archive=make();archive.resources.currentYear=5000;archive.resources.settings.retainDetailedYears=100;archive.resources.annual=[];for(let y=0;y<800;y++)archive.resources.annual.push({year:y,totalStock:100+y,transported:y%8,meanFoodSecurity:.8,shortageMarkets:y%3,famines:y%17===0?1:0});R.compact(archive);assert.ok(archive.resources.archives.length>0&&archive.resources.stats.archivedYears>0,'old economic detail must compact into bounded era archives');
const fp=R.fingerprint(direct),restored=E.deserialize(E.serialize(direct));R.initialize(restored);assert.deepEqual(R.validate(restored),[],'resource state must survive world save/export');assert.equal(R.fingerprint(restored),fp,'resource fingerprint must survive save/export round-trip');
console.log('WorldForge v1.8 Resources, Agriculture & Supply Chains regression tests passed.');
console.log(JSON.stringify({year:R.absYear(direct),markets:sum.markets,commodities:sum.commodities,flows:direct.resources.flows.length,famines:direct.resources.stats.famines,transported:Number(direct.resources.stats.transported.toFixed(1)),meanFoodSecurity:sum.meanFoodSecurity,archives:archive.resources.archives.length,fingerprint:fp}));