import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';

global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,A=global.WorldForgeAdventure,T=global.WorldForgeStory;
assert.ok(E&&H&&S&&C&&A&&T,'all v0.6 engines must be exposed');
const options={seed:'EMBER-CROWN-01',width:160,height:90,seaLevel:.53,age:'mature',settlementTarget:45,kingdomTarget:7};
const make=()=>{const w=E.generateWorld(options);H.initialize(w);S.initialize(w);C.initialize(w);A.initialize(w);T.initialize(w);return w};
const a=make();
assert.deepEqual(T.validateStory(a),[],'Year 0 story state must validate');
assert.ok(a.story.quests.length>0,'story engine should seed quests from the world');
assert.ok(a.story.dialogues.length>0,'quests should produce dialogue trees');
assert.ok(a.story.quests.every(q=>q.nodes.length>=5&&q.edges.length>=4),'quests need branching graphs');
assert.ok(a.story.dialogues.every(d=>d.nodes.some(n=>n.choices?.length)),'dialogues need choices');
const custom=T.createCustomQuest(a,{title:'Regression Quest',settlementId:0});
assert.equal(custom.title,'Regression Quest');
const node=T.addQuestNode(a,custom.id,{title:'Custom Branch',text:'Regression branch',from:0});
assert.ok(node&&custom.edges.some(e=>e.to===node.id),'authoring API must add connected nodes');
assert.ok(T.setVariable(a,'test_flag',true),'variable API should accept flags');
assert.equal(a.story.variables.test_flag,true);
const b=make();
// Apply the same authoring actions so deterministic simulation starts from the same authored state.
const customB=T.createCustomQuest(b,{title:'Regression Quest',settlementId:0});T.addQuestNode(b,customB.id,{title:'Custom Branch',text:'Regression branch',from:0});T.setVariable(b,'test_flag',true);
T.simulateYears(a,300);
T.simulateYears(b,100);T.simulateYears(b,75);T.simulateYears(b,125);
assert.deepEqual(T.validateStory(a),[],'300-year story state must validate');
assert.equal(T.storyFingerprint(a),T.storyFingerprint(b),'story simulation must be chunk-independent deterministic');
assert.equal(A.adventureFingerprint(a),A.adventureFingerprint(b),'adventure layer must remain deterministic beneath story');
assert.equal(C.cityFingerprint(a),C.cityFingerprint(b),'city layer remains deterministic');
assert.equal(S.societyFingerprint(a),S.societyFingerprint(b),'society layer remains deterministic');
assert.equal(H.historyFingerprint(a),H.historyFingerprint(b),'history layer remains deterministic');
assert.ok(a.story.stats.questsResolved+a.story.stats.questsFailed>0,'long runs should resolve story opportunities');
assert.ok(a.history.events.some(e=>e.type==='quest_resolved'||e.type==='quest_failed'),'quest outcomes enter the chronicle');
assert.ok(a.story.snapshots.length>20&&a.story.snapshots.length<100,'story snapshots stay compact');
const q=T.questDetail(a,0,300),d=T.dialogueDetail(a,0,300);
assert.ok(q?.giverName&&q.nodes.length,'quest detail resolves entity names and graph');
assert.ok(d?.personName&&d.nodes.length,'dialogue detail resolves speaker and tree');
const historical=T.viewAt(a,100);assert.ok(historical.year<=100&&historical.quests.length>0,'historical story replay works');
const raw=E.serialize(a),restored=E.deserialize(raw);H.initialize(restored);S.initialize(restored);C.initialize(restored);A.initialize(restored);T.initialize(restored);
assert.deepEqual(T.validateStory(restored),[],'save/export preserves story state');
assert.equal(T.storyFingerprint(restored),T.storyFingerprint(a),'story save identity');
console.log('WorldForge v0.6 deterministic story tests passed.');
console.log(JSON.stringify({year:a.story.currentYear,quests:a.story.quests.length,dialogues:a.story.dialogues.length,resolved:a.story.stats.questsResolved,failed:a.story.stats.questsFailed,variables:Object.keys(a.story.variables).length,fingerprint:T.storyFingerprint(a)}));