import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js','knowledge-engine.js','calendar-engine.js','artifact-engine.js','artifact-wiki-adapter.js','technology-engine.js','technology-wiki-adapter.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,Adv=global.WorldForgeAdventure,Story=global.WorldForgeStory,W=global.WorldForgeWiki,Cult=global.WorldForgeCulture,F=global.WorldForgeFactions,K=global.WorldForgeKnowledge,Cal=global.WorldForgeCalendar,A=global.WorldForgeArtifacts,T=global.WorldForgeTechnology;
assert.ok(E&&H&&S&&C&&Adv&&Story&&W&&Cult&&F&&K&&Cal&&A&&T,'v1.7 technology dependencies must load');
const opts={seed:'HALL-OF-DISCOVERY-TEST',width:120,height:70,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5};
function make(){const w=E.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);Adv.initialize(w);Story.initialize(w);Cult.initialize(w);F.initialize(w);K.initialize(w);Cal.initialize(w);A.initialize(w);T.initialize(w);return w}
Cal.setBaseSimulator(C.simulateYears.bind(C));A.setBaseSimulator(Cal.simulateYears.bind(C));T.setBaseSimulator(A.simulateYears.bind(A));
const direct=make(),chunked=make();T.simulateYears(direct,260);T.simulateYears(chunked,80);T.simulateYears(chunked,90);T.simulateYears(chunked,90);
assert.equal(T.fingerprint(direct),T.fingerprint(chunked),'technology simulation must be chunk independent');
assert.equal(H.historyFingerprint(direct),H.historyFingerprint(chunked),'technology-enabled history must remain deterministic');
assert.deepEqual(T.validate(direct),[],'technology state must validate');
const sum=T.summary(direct);assert.ok(sum.unique>=8,'long simulation must unlock a meaningful foundational technology set');assert.ok(sum.discoveries>0,'research must create discoveries');
assert.ok(direct.history.events.some(e=>e.type==='technology_discovered'),'discoveries must enter world history');
assert.ok(direct.artifacts.items.some(a=>(a.refs||[]).some(r=>String(r).startsWith('technology:'))),'major discoveries must create technical artifacts');
const realm=T.realmView(direct,direct.technology.realms[0].realmId);assert.ok(realm.rows.some(x=>x.known),'realm view must expose adopted technology');assert.ok(Object.values(realm.effects).some(v=>v>0),'technology must create real realm capabilities');
const targetRealm=direct.technology.realms[0].realmId;for(const tech of T.TECHS)if(!direct.technology.realms[0].known[tech.id])T.grantTechnology(direct,targetRealm,tech.id,'research',null,T.absYear(direct),true);direct.technology.realms[0].known.printing_press.adoption=.95;
const claim=direct.knowledge.claims.find(c=>c.sourceIds?.length);if(claim){const doc=A.createArtifact(direct,{kind:'chronicle',name:'Printed Test Chronicle',createdYear:T.absYear(direct),originSettlementId:0,originRealmId:targetRealm,ownerType:'realm',ownerId:targetRealm,claimKeys:[claim.key],copies:20,authenticity:.95});const before=direct.knowledge.sources.length;for(let i=0;i<20&&direct.knowledge.sources.length===before;i++)T.simulateTechnologyYear(direct,T.absYear(direct)+i+1);assert.ok(direct.knowledge.sources.length>before,'printing press must be able to generate new circulating documentary evidence');assert.ok(doc.copies>=20,'printing diffusion must never reduce written circulation')}
const b1=T.createBreakthrough(direct,targetRealm,'engineering',1000),b2=T.createBreakthrough(direct,targetRealm,'engineering',1200);assert.equal(b2.level,b1.level+1,'procedural breakthroughs must continue beyond the finite core tree');assert.ok(b2.magnitude<b1.magnitude,'infinite breakthroughs must use diminishing returns');
const techArticle=W.article(direct,'technology:printing_press',T.absYear(direct));assert.ok(techArticle&&techArticle.type==='technology','technologies must enter the Universal Encyclopedia');const breakArticle=W.article(direct,`breakthrough:${b1.id}`,1200);assert.ok(breakArticle&&breakArticle.type==='breakthrough','procedural breakthroughs must enter the Universal Encyclopedia');
const archive=make();archive.endless={epochOffset:5000,baseSeed:opts.seed,absoluteYear:5000};T.initialize(archive).settings.retainDetailedYears=200;for(let i=0;i<50;i++)T.createBreakthrough(archive,archive.technology.realms[0].realmId,T.DOMAINS[i%T.DOMAINS.length].id,i*50);T.compact(archive);assert.ok(archive.technology.archives.length>0,'old procedural innovation must compact into era archives');
const fp=T.fingerprint(direct),restored=E.deserialize(E.serialize(direct));T.initialize(restored);assert.deepEqual(T.validate(restored),[],'technology state must survive save/export');assert.equal(T.fingerprint(restored),fp,'technology fingerprint must survive save/export round-trip');
console.log('WorldForge v1.7 Technology, Inventions & Knowledge Diffusion regression tests passed.');
console.log(JSON.stringify({year:T.absYear(direct),unique:T.summary(direct).unique,discoveries:T.summary(direct).discoveries,diffusions:T.summary(direct).diffusions,breakthroughs:T.summary(direct).breakthroughs,printedSources:T.summary(direct).printedSources,fingerprint:fp}));