import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js','knowledge-engine.js','calendar-engine.js','artifact-engine.js','artifact-wiki-adapter.js','technology-engine.js','technology-wiki-adapter.js','resource-engine.js','resource-calibration.js','resource-wiki-adapter.js','institution-engine.js','institution-wiki-adapter.js','military-engine.js','military-wiki-adapter.js','treasury-engine.js','treasury-wiki-adapter.js','workforce-engine.js','workforce-calibration.js','workforce-wiki-adapter.js','household-engine.js','household-wiki-adapter.js','housing-engine.js','housing-wiki-adapter.js','municipal-engine.js','municipal-wiki-adapter.js','emergency-engine.js','emergency-wiki-adapter.js','nutrition-engine.js','nutrition-wiki-adapter.js','politics-engine.js','politics-wiki-adapter.js','diplomacy-engine.js','diplomacy-wiki-adapter.js','world-order-engine.js','world-order-wiki-adapter.js','structure-archetypes.js','pixel-structure-renderer.js','pixel-art-polish.js','worldbuilding-engine.js','archaeology-engine.js','archaeology-pixel-renderer.js','heritage-engine.js','heritage-pixel-renderer.js','tourism-engine.js','tourism-pixel-renderer.js','worldbuilding-wiki-adapter.js','archaeology-wiki-adapter.js','heritage-wiki-adapter.js','tourism-wiki-adapter.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const Eng=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,Adv=global.WorldForgeAdventure,F=global.WorldForgeFactions,Cal=global.WorldForgeCalendar,Art=global.WorldForgeArtifacts,Tech=global.WorldForgeTechnology,Rsrc=global.WorldForgeResources,I=global.WorldForgeInstitutions,Mil=global.WorldForgeMilitary,Tr=global.WorldForgeTreasury,WF=global.WorldForgeWorkforce,HH=global.WorldForgeHouseholds,HG=global.WorldForgeHousing,M=global.WorldForgeMunicipal,E=global.WorldForgeEmergency,N=global.WorldForgeNutrition,P=global.WorldForgePolitics,D=global.WorldForgeDiplomacy,O=global.WorldForgeWorldOrder,WB=global.WorldForgeWorldbuilding,A=global.WorldForgeArchaeology,HT=global.WorldForgeHeritage,T=global.WorldForgeTourism,PR=global.WorldForgePixelRenderer,TP=global.WorldForgeTourismPixel,Wiki=global.WorldForgeWiki,TW=global.WorldForgeTourismWiki;
assert.ok(T&&TP&&TW);assert.equal(T.VERSION,'4.4.0');assert.equal(PR.TOURISM_VERSION,'4.4.0');assert.ok(WB.__tourismBridge);assert.ok(T.ROUTE_TYPES.includes('pilgrimage_route'));assert.ok(T.PRESSURE_STATES.includes('overtourism'));
Cal.setBaseSimulator(C.simulateYears.bind(C));Art.setBaseSimulator(Cal.simulateYears.bind(Cal));Tech.setBaseSimulator(Art.simulateYears.bind(Art));Rsrc.setBaseSimulator(Tech.simulateYears.bind(Tech));I.setBaseSimulator(Rsrc.simulateYears.bind(Rsrc));Mil.setBaseSimulator(I.simulateYears.bind(I));Tr.setBaseSimulator(Mil.simulateYears.bind(Mil));WF.setBaseSimulator(Tr.simulateYears.bind(Tr));
const opts={seed:'TOURISM-V44-TEST',width:106,height:66,seaLevel:.53,age:'mature',settlementTarget:30,kingdomTarget:5};function setup(){const w=Eng.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);Adv.initialize(w);F.initialize(w);Cal.initialize(w);Art.initialize(w);Tech.initialize(w);Rsrc.initialize(w);I.initialize(w);Mil.initialize(w);Tr.initialize(w);WF.initialize(w);HH.initialize(w);HG.initialize(w);M.initialize(w);E.initialize(w);N.initialize(w);P.initialize(w);D.initialize(w);O.initialize(w);WB.initialize(w);w.diplomacy.settings.autoTreaties=false;w.worldOrder.settings.autoCongress=false;WF.simulateWorkforceYear(w,WF.absYear(w));WB.simulateWorldbuildingYear(w,WB.absYear(w));A.initialize(w,true);HT.initialize(w,true);T.initialize(w,true);return w}
const w=setup(),sid=0,now=WB.absYear(w),realm=w.history.current.settlementKingdomIds[sid],siteId=w.adventure.sites.length,eventId=w.history.events.length;
w.adventure.sites.push({id:siteId,name:'Temple of the Pilgrim Star',kind:'Ancient Ruin',settlementId:sid,realmId:realm,originYear:Math.max(0,now-240),sourceEventId:eventId,active:true,discovered:true,danger:12,rooms:[],loot:[],depth:2,lore:'A sacred route terminus visited by pilgrims and antiquarians.',sourcePersonIds:[],gangId:null,visits:8,clears:0,rumor:'Pilgrims still leave tokens at the old sanctuary.'});w.history.events.push({id:eventId,year:Math.max(0,now-160),absoluteYear:Math.max(0,now-160),type:'festival',importance:5,settlementId:sid,settlementIds:[sid],realmIds:[realm],title:'Feast of the Pilgrim Star',text:'A long-standing pilgrimage feast formed around the old sanctuary.'});w.worldbuilding.profiles[sid]=WB.buildProfile(w,sid,now);w.worldbuilding.revision++;A.initialize(w,true);HT.initialize(w,true);T.initialize(w,true);
const sum=T.summary(w),local=WB.settlementView(w,sid).tourism;assert.ok(sum.destinations>0,'tourism destinations must be derived from heritage');assert.ok(sum.annualVisitors>0&&sum.tourismRevenue>0,'visitor economy must produce visitors and revenue');assert.ok(sum.annualVisitors>=sum.pilgrims,'pilgrims cannot exceed visitors');assert.ok(sum.overnightCapacity>0,'tourism must create lodging capacity');assert.ok(local&&local.destinations.length>0,'settlement view must include tourism');assert.ok(local.destinations.some(d=>d.type==='pilgrimage'||d.type==='mixed'),'sacred fixture must produce pilgrimage tourism');assert.deepEqual(T.validate(w),[],'v4.4 tourism state must validate');
for(const d of w.tourism.destinations){assert.ok(d.capacity>0&&d.revenue>=0&&d.annualVisitors>=0);assert.ok(T.PRESSURE_STATES.includes(d.pressureState))}for(const r of w.tourism.routes)assert.ok(T.ROUTE_TYPES.includes(r.type));
const profile=WB.settlementView(w,sid),svg=PR.renderSettlement(profile,{width:700,height:430});assert.ok(svg.includes('data-worldforge-tourism="4.4.0"')&&svg.includes('data-tourism-overlay="v4.4"'));assert.equal(PR.renderSettlement(profile,{width:700,height:430}),svg,'tourism pixel rendering must be deterministic');
const dest=w.tourism.destinations.find(d=>d.settlementId===sid)||w.tourism.destinations[0];assert.equal(Wiki.article(w,TW.dRef(dest),now)?.type,'tourism_destination');assert.ok(Wiki.search(w,'tourism',{type:'tourism_destination',year:now}).length>0);assert.ok(Wiki.dashboard(w,now).counts.tourism_destination>=1);
const hfp=HT.fingerprint(w),tfp=T.fingerprint(w),wbfp=WB.fingerprint(w),restored=Eng.deserialize(Eng.serialize(w));WF.initialize(restored);HH.initialize(restored);HG.initialize(restored);M.initialize(restored);E.initialize(restored);N.initialize(restored);P.initialize(restored);D.initialize(restored);O.initialize(restored);WB.initialize(restored);A.initialize(restored,true);HT.initialize(restored,true);T.initialize(restored,true);assert.deepEqual(T.validate(restored),[]);assert.equal(T.fingerprint(restored),tfp,'tourism fingerprint must survive round trip');assert.equal(HT.fingerprint(restored),hfp,'v4.4 must preserve heritage fingerprint');assert.equal(WB.fingerprint(restored),wbfp,'v4.4 must preserve worldbuilding fingerprint');const same=T.fingerprint(w);T.simulateTourismYear(w,now);assert.equal(T.fingerprint(w),same,'same-year tourism update must be deterministic');
console.log('WorldForge v4.4 Tourism, Pilgrimage & Cultural Economy regression tests passed.');console.log(JSON.stringify({...T.summary(w),fingerprint:tfp,heritageFingerprint:hfp,worldbuildingFingerprint:wbfp,pilgrimageDestinations:w.tourism.destinations.filter(d=>d.type==='pilgrimage'||d.type==='mixed').length}));