import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js','knowledge-engine.js','calendar-engine.js','artifact-engine.js','artifact-wiki-adapter.js','technology-engine.js','technology-wiki-adapter.js','resource-engine.js','resource-calibration.js','resource-wiki-adapter.js','institution-engine.js','institution-wiki-adapter.js','military-engine.js','military-wiki-adapter.js','treasury-engine.js','treasury-wiki-adapter.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const E=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,Adv=global.WorldForgeAdventure,Story=global.WorldForgeStory,W=global.WorldForgeWiki,Cult=global.WorldForgeCulture,F=global.WorldForgeFactions,K=global.WorldForgeKnowledge,Cal=global.WorldForgeCalendar,A=global.WorldForgeArtifacts,Tech=global.WorldForgeTechnology,R=global.WorldForgeResources,I=global.WorldForgeInstitutions,M=global.WorldForgeMilitary,T=global.WorldForgeTreasury;
assert.ok(E&&H&&S&&C&&Adv&&Story&&W&&Cult&&F&&K&&Cal&&A&&Tech&&R&&I&&M&&T,'v2.1 finance dependencies must load');
Cal.setBaseSimulator(C.simulateYears.bind(C));A.setBaseSimulator(Cal.simulateYears.bind(C));Tech.setBaseSimulator(A.simulateYears.bind(A));R.setBaseSimulator(Tech.simulateYears.bind(Tech));I.setBaseSimulator(R.simulateYears.bind(R));M.setBaseSimulator(I.simulateYears.bind(I));T.setBaseSimulator(M.simulateYears.bind(M));
const opts={seed:'EXCHEQUER-V21-TEST',width:110,height:66,seaLevel:.53,age:'mature',settlementTarget:28,kingdomTarget:5};
function setup(){const w=E.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);Adv.initialize(w);Story.initialize(w);Cult.initialize(w);F.initialize(w);K.initialize(w);Cal.initialize(w);A.initialize(w);Tech.initialize(w);R.initialize(w);I.initialize(w);const active=w.history.current.realmState.filter(Boolean).filter(x=>x.active);assert.ok(active.length>=2);const ra=active[0].id,rb=active[1].id;for(const m of w.resources.markets){for(const id of ['grain','rice','fish','livestock','timber','iron','copper','salt','coal','wine'])m.inventory[id]=Math.max(Number(m.inventory[id]||0),4000);m.processed=m.processed||{};Object.assign(m.processed,{weapons:500,ships:20,lumber:500,steel:500,bread:100,medicine:50})}w.institutions.realmAssets[String(ra)]={weapons:150,ships:20,tools:30,research:5,health:5,logistics:12};w.institutions.realmAssets[String(rb)]={weapons:150,ships:20,tools:30,research:5,health:5,logistics:12};const warId=w.history.wars.length;w.history.wars.push({id:warId,attackerId:ra,defenderId:rb,startYear:w.history.currentYear,endYear:null,score:0,captures:[],cause:'fiscal regression'});w.history.current.activeWarIds.push(warId);M.initialize(w);M.syncWars(w);T.initialize(w);return{w,ra,rb,warId}}
const one=setup(),w=one.w;assert.deepEqual(T.validate(w),[],'initial fiscal state must validate');const acct=T.account(w,one.ra);const army=w.military.armies.find(x=>x.realmId===one.ra&&x.warId===one.warId&&x.status==='active');assert.ok(army,'wartime treasury test requires a field army');army.size=Math.max(90000,army.size);acct.treasury=0;acct.taxRate=.07;acct.warSurcharge=.02;const taxBefore=w.treasury.stats.taxCollected,debtBefore=acct.debt,stabilityBefore=w.history.current.realmState[one.ra].stability;T.simulateFiscalYear(w,T.absYear(w)+1);assert.ok(w.treasury.stats.taxCollected>taxBefore,'state must collect real tax revenue');assert.ok(acct.warCost>0,'field forces must create explicit war expenditure');assert.ok(acct.debt>debtBefore,'wartime deficit must create sovereign debt');assert.ok(w.treasury.instruments.some(d=>d.realmId===one.ra&&d.type==='war_bond'),'wartime borrowing must issue war bonds');assert.ok(acct.interestRate>=.02&&acct.credit<=96,'debt must feed the credit market and borrowing rate');
const big=T.issueDebt(w,acct,Math.max(50000,acct.lastRevenue*20),T.absYear(w)+2,true);assert.ok(big&&big.principal>0);acct.treasury=0;acct.consecutiveDeficit=3;const citySid=w.history.current.settlementKingdomIds.findIndex(x=>x===one.ra),city=w.cities?.cities?.[citySid],priceBefore=city?.priceIndex||100;T.simulateFiscalYear(w,T.absYear(w)+2);assert.ok(acct.defaults>=1,'overleveraged deficit state must be able to sovereign-default');assert.ok(w.treasury.stats.defaults>=1);assert.ok(acct.coinValue<1,'default/debasement must reduce coin value');assert.ok(acct.inflation>.02,'deficit finance must create inflation pressure');assert.ok(w.history.current.realmState[one.ra].stability<stabilityBefore,'fiscal crisis must feed political stability');if(city)assert.ok(city.priceIndex>priceBefore,'fiscal crisis must reach city prices');
const tr=W.article(w,`treasury:${one.ra}`),dr=W.article(w,`debt:${big.id}`);assert.ok(tr&&tr.type==='treasury','realm treasury must enter the Universal Encyclopedia');assert.ok(dr&&dr.type==='debt','sovereign debt must enter the Universal Encyclopedia');assert.ok(W.related(w,tr.ref).some(x=>x.type==='debt'),'treasury article must cross-link debt instruments');assert.deepEqual(T.validate(w),[],'post-crisis fiscal state must validate');
const d=setup(),c=setup();T.simulateYears(d.w,4);T.simulateYears(c.w,2);T.simulateYears(c.w,2);assert.equal(T.fingerprint(d.w),T.fingerprint(c.w),'finance must be deterministic across caller chunk sizes');assert.equal(H.historyFingerprint(d.w),H.historyFingerprint(c.w),'fiscal feedback must remain chunk-independent');const fp=T.fingerprint(w),restored=E.deserialize(E.serialize(w));T.initialize(restored);assert.deepEqual(T.validate(restored),[],'treasury must survive save/export');assert.equal(T.fingerprint(restored),fp,'treasury fingerprint must survive save/export round-trip');
console.log('WorldForge v2.1 Treasury, Taxes, Debt & War Finance regression tests passed.');
console.log(JSON.stringify({...T.summary(w),instruments:w.treasury.instruments.length,fingerprint:fp}));