import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
global.window=global;
for(const f of ['engine.js','history-engine.js','society-engine.js','city-engine.js','adventure-engine.js','story-engine.js','wiki-engine.js','culture-engine.js','faction-engine.js','creator-suite-engine.js','canon-bridge-engine.js','knowledge-engine.js','calendar-engine.js','artifact-engine.js','artifact-wiki-adapter.js','technology-engine.js','technology-wiki-adapter.js','resource-engine.js','resource-calibration.js','resource-wiki-adapter.js','institution-engine.js','institution-wiki-adapter.js','military-engine.js','military-wiki-adapter.js','treasury-engine.js','treasury-wiki-adapter.js','workforce-engine.js','workforce-calibration.js','workforce-wiki-adapter.js','household-engine.js','household-wiki-adapter.js','housing-engine.js','housing-wiki-adapter.js','municipal-engine.js','municipal-wiki-adapter.js','emergency-engine.js','emergency-wiki-adapter.js','nutrition-engine.js','nutrition-wiki-adapter.js','politics-engine.js','politics-wiki-adapter.js','diplomacy-engine.js','diplomacy-wiki-adapter.js','world-order-engine.js','world-order-wiki-adapter.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'),{filename:f});
const Eng=global.WorldForgeEngine,H=global.WorldForgeHistory,S=global.WorldForgeSociety,C=global.WorldForgeCity,F=global.WorldForgeFactions,Cal=global.WorldForgeCalendar,A=global.WorldForgeArtifacts,Tech=global.WorldForgeTechnology,R=global.WorldForgeResources,I=global.WorldForgeInstitutions,Mil=global.WorldForgeMilitary,T=global.WorldForgeTreasury,W=global.WorldForgeWorkforce,HH=global.WorldForgeHouseholds,HG=global.WorldForgeHousing,M=global.WorldForgeMunicipal,E=global.WorldForgeEmergency,N=global.WorldForgeNutrition,P=global.WorldForgePolitics,D=global.WorldForgeDiplomacy,O=global.WorldForgeWorldOrder,Wiki=global.WorldForgeWiki;
assert.ok(Eng&&H&&S&&C&&F&&Cal&&A&&Tech&&R&&I&&Mil&&T&&W&&HH&&HG&&M&&E&&N&&P&&D&&O&&Wiki,'v3.0 dependencies must load');
assert.ok(W.__diplomacyBridge&&W.__worldOrderBridge,'v3.0 bridge must attach after diplomacy');
Cal.setBaseSimulator(C.simulateYears.bind(C));A.setBaseSimulator(Cal.simulateYears.bind(Cal));Tech.setBaseSimulator(A.simulateYears.bind(A));R.setBaseSimulator(Tech.simulateYears.bind(Tech));I.setBaseSimulator(R.simulateYears.bind(R));Mil.setBaseSimulator(I.simulateYears.bind(I));T.setBaseSimulator(Mil.simulateYears.bind(Mil));W.setBaseSimulator(T.simulateYears.bind(T));
const opts={seed:'WORLD-ORDER-V30-TEST',width:112,height:68,seaLevel:.53,age:'mature',settlementTarget:34,kingdomTarget:6};
function setup(){const w=Eng.generateWorld(opts);H.initialize(w);S.initialize(w);C.initialize(w);F.initialize(w);Cal.initialize(w);A.initialize(w);Tech.initialize(w);R.initialize(w);I.initialize(w);Mil.initialize(w);T.initialize(w);W.initialize(w);HH.initialize(w);HG.initialize(w);M.initialize(w);E.initialize(w);N.initialize(w);P.initialize(w);D.initialize(w);O.initialize(w);w.diplomacy.settings.autoTreaties=false;w.worldOrder.settings.autoCongress=false;for(const m of w.resources.markets){for(const id of R.FOOD_IDS){m.inventory[id]=Math.max(Number(m.inventory[id]||0),Math.max(70,Number(w.history.current.settlementPopulation[m.settlementId]||100)*.014));m.prices[id]=R.MAP.get(id).basePrice;m.shortages[id]=0}m.foodSecurity=1;m.foodDays=365}W.simulateWorkforceYear(w,W.absYear(w));O.simulateWorldOrderYear(w,O.absYear(w));return w}
const w=setup(),ids=w.history.current.realmState.filter(Boolean).map(x=>x.id),sum=O.summary(w),ranked=w.worldOrder.realms.slice().sort((a,b)=>a.rank-b.rank);
assert.deepEqual(O.validate(w),[],'initial world-order state must validate');
assert.equal(w.worldOrder.realms.length,ids.length,'every active realm must receive a power profile');
assert.ok(sum.greatPowers>=1,'at least one great power must anchor the world order');
assert.ok(sum.hegemonRealmId!=null,'power ranking must identify a leading realm');
assert.equal(new Set(ranked.map(x=>x.rank)).size,ranked.length,'power ranks must be unique');
assert.ok(Math.abs(ranked.reduce((n,x)=>n+x.powerShare,0)-1)<.002,'realm power shares must normalize to one');
assert.equal(Wiki.article(w,'world_order:current',O.absYear(w))?.type,'world_order','current world order must enter Universal Encyclopedia');
assert.equal(Wiki.article(w,`great_power:${ranked[0].realmId}`,O.absYear(w))?.type,'great_power','leading powers must enter Universal Encyclopedia');
assert.ok(Wiki.search(w,'world order great power',{type:'world_order',year:O.absYear(w)}).length>0,'world order must be searchable');
const perfBefore=O.performance(w);for(let i=0;i<80;i++)O.realmView(w,ranked[0].realmId);const perfAfter=O.performance(w);assert.equal(perfAfter.cacheBuilds,perfBefore.cacheBuilds,'repeated world-order reads must reuse runtime indexes');
const sameFp=O.fingerprint(w),sameD=D.fingerprint(w);O.simulateWorldOrderYear(w,O.absYear(w));assert.equal(O.fingerprint(w),sameFp,'same-year world-order simulation must be idempotent');assert.equal(D.fingerprint(w),sameD,'same-year world-order simulation must not repeat diplomatic feedback');
W.simulateYears(w,3);assert.deepEqual(D.validate(w),[],'diplomacy must remain valid under v3.0');assert.deepEqual(O.validate(w),[],'world order must remain valid after simulation');assert.ok(w.worldOrder.annual.length>=4,'world-order annual ledger must advance with simulation');
const direct=setup(),chunked=setup();W.simulateYears(direct,4);W.simulateYears(chunked,2);W.simulateYears(chunked,2);assert.equal(O.fingerprint(direct),O.fingerprint(chunked),'world-order simulation must be deterministic across caller chunk sizes');assert.equal(D.fingerprint(direct),D.fingerprint(chunked),'world-order feedback must preserve diplomacy chunk determinism');assert.equal(W.fingerprint(direct),W.fingerprint(chunked),'world-order bridge must preserve workforce chunk determinism');
const fp=O.fingerprint(w),restored=Eng.deserialize(Eng.serialize(w));W.initialize(restored);HH.initialize(restored);HG.initialize(restored);M.initialize(restored);E.initialize(restored);N.initialize(restored);P.initialize(restored);D.initialize(restored);O.initialize(restored);assert.deepEqual(O.validate(restored),[],'world-order state must survive save/export');assert.equal(O.fingerprint(restored),fp,'world-order fingerprint must survive save/export round-trip');
// Security treaties must aggregate into a geopolitical bloc instead of remaining isolated pair labels.
const blocWorld=setup(),br=blocWorld.worldOrder.realms.slice().sort((a,b)=>a.rank-b.rank),ba=br[0].realmId,bb=br[1].realmId,bc=br[2]?.realmId;D.signTreaty(blocWorld,'alliance',ba,bb,O.absYear(blocWorld),{duration:20,strength:.9});if(bc!=null)D.signTreaty(blocWorld,'defensive_pact',bb,bc,O.absYear(blocWorld),{duration:18,strength:.85});W.simulateYears(blocWorld,1);const security=blocWorld.worldOrder.blocs.find(b=>b.status==='active'&&b.type==='security_bloc'&&b.members.includes(ba)&&b.members.includes(bb));assert.ok(security,'alliance network must form a security bloc');assert.ok(security.cohesion>=0&&security.cohesion<=1,'bloc cohesion must be bounded');assert.equal(Wiki.article(blocWorld,`geopolitical_bloc:${security.id}`,O.absYear(blocWorld))?.type,'geopolitical_bloc','geopolitical blocs must enter Universal Encyclopedia');
// A much stronger friendly realm must create a measurable sphere-of-influence relation.
const sphereWorld=setup(),sr=sphereWorld.worldOrder.realms.slice().sort((a,b)=>a.rank-b.rank),patron=sr[0].realmId,client=sr.at(-1).realmId,srel=D.relationState(sphereWorld,patron,client);Object.assign(srel,{trust:.96,goodwill:.82,rivalry:.01,warRisk:.01,tradeDependence:.82,tradeAccess:1.25,diplomaticTension:.04});W.simulateYears(sphereWorld,1);const sphere=sphereWorld.worldOrder.spheres.find(s=>s.patronRealmId===patron&&s.clientRealmId===client);assert.ok(sphere,'friendly asymmetric power must create a sphere-of-influence relation');assert.ok(sphere.influence>=.24&&sphere.influence<=1,'sphere influence must be material and bounded');assert.equal(Wiki.article(sphereWorld,`sphere_of_influence:${patron}:${client}`,O.absYear(sphereWorld))?.type,'sphere_of_influence','spheres must enter Universal Encyclopedia');
// Rival blocs can trigger a great-power congress that de-escalates tension and may create a short non-aggression regime.
const congressWorld=setup(),cr=congressWorld.worldOrder.realms.slice().sort((a,b)=>a.rank-b.rank);assert.ok(cr.length>=4,'congress regression requires at least four realms');const [c1,c2,c3,c4]=cr.slice(0,4).map(x=>x.realmId);D.signTreaty(congressWorld,'alliance',c1,c3,O.absYear(congressWorld),{duration:20,strength:.9});D.signTreaty(congressWorld,'alliance',c2,c4,O.absYear(congressWorld),{duration:20,strength:.9});const hostile=D.relationState(congressWorld,c1,c2);Object.assign(hostile,{trust:.03,goodwill:-.9,fear:.88,rivalry:.98,diplomaticTension:.96,warRisk:.82});congressWorld.worldOrder.settings.autoCongress=true;congressWorld.worldOrder.settings.congressChance=1;W.simulateYears(congressWorld,1);const c=congressWorld.worldOrder.congresses.at(-1);assert.ok(c,'severe rival-bloc tension must be eligible for an international congress');assert.ok(c.tensionReduced>=0,'congress must record its de-escalation effect');assert.equal(Wiki.article(congressWorld,`international_congress:${c.id}`,O.absYear(congressWorld))?.type,'international_congress','international congresses must enter Universal Encyclopedia');assert.deepEqual(O.validate(congressWorld),[],'congress outcome must preserve world-order validity');
console.log('WorldForge v3.0 Geopolitical Blocs, Great Powers & World Orders regression tests passed.');
console.log(JSON.stringify({...O.summary(w),performance:O.performance(w),fingerprint:fp}));