const assert=require('assert');
const fs=require('fs');
const charts=require('../../src/rendering/metric-charts.js');
const source=fs.readFileSync('src/rendering/metric-charts.js','utf8');
assert.equal(charts.VERSION,'1.0.5');
assert.equal(typeof charts.render,'function');
assert.doesNotThrow(()=>charts.render({series:[],viewYear:0}));
assert.match(source,/model\.canvas=canvas/,'registered chart models should retain their owning canvas');
assert.match(source,/function pruneModels\(\).*model\.canvas\?\.isConnected===false/s,'detached chart models should have a reusable pruning path');
assert.match(source,/function register\(canvas,model\)\{\s*pruneModels\(\)/,'chart registration should prune detached models during remounts instead of waiting for resize');
assert.match(source,/resizeFrame=0;pruneModels\(\);for\(const model of models\)model\.draw\(\)/,'resize handling should prune detached models before redraw');
assert.match(source,/card\.querySelector\('\.history-chart-tooltip'\)/,'chart remounts should reuse an existing card tooltip');
assert.match(source,/canvas\.__worldforgeMetricTooltip=existing/,'reused tooltips should be rebound to the replacement canvas');
assert.match(source,/cancelAnimationFrame/,'hover scheduling should support cancelling stale animation frames');
assert.match(source,/const cancelHover=.*caf\(hoverFrame\);hoverFrame=0/,'hover cancellation should cancel pending work before clearing its frame id');
assert.match(source,/addEventListener\('pointerleave',cancelHover\)/,'pointer leave should clear hover state');
assert.match(source,/addEventListener\('pointercancel',cancelHover\)/,'pointer cancellation should clear hover state on interrupted touch or pen gestures');
console.log('native metric chart renderer contract OK');
