const assert=require('assert');
const fs=require('fs');
const charts=require('../../src/rendering/metric-charts.js');
const source=fs.readFileSync('src/rendering/metric-charts.js','utf8');
assert.equal(charts.VERSION,'1.0.2');
assert.equal(typeof charts.render,'function');
assert.doesNotThrow(()=>charts.render({series:[],viewYear:0}));
assert.match(source,/model\.canvas=canvas/,'registered chart models should retain their owning canvas');
assert.match(source,/model\.canvas\?\.isConnected===false/,'resize handling should prune models whose canvases left the DOM');
assert.match(source,/card\.querySelector\('\.history-chart-tooltip'\)/,'chart remounts should reuse an existing card tooltip');
assert.match(source,/canvas\.__worldforgeMetricTooltip=existing/,'reused tooltips should be rebound to the replacement canvas');
console.log('native metric chart renderer contract OK');
