(()=>{
'use strict';
const A=window.WorldForgeArchaeology,W=window.WorldForgeWorldbuilding,R=window.WorldForgeArchaeologyPixel,UI=window.WorldForgeWorldbuildingUI;if(!A||!W||!R||!UI)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(n,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d}),pct=n=>`${fmt(Number(n||0)*100,1)}%`;
const state={world:null,site:null,last:null,raf:0};
function world(){return state.world||UI.state.world||window.WorldForgeWorldOrderUI?.state?.world||window.WorldForgeReleaseUI?.state?.world||null}
function ensure(){const panel=$('#worldbuildingPanel');if(!panel||$('#archaeologySection'))return;const note=panel.querySelector('.worldbuilding-note');const html=`<section id="archaeologySection" class="archaeology-section"><div class="labor-head"><span>ARCHAEOLOGY & HISTORICAL LAYERS</span><b>LIVING RUINS · ARTIFACTS · INSCRIPTIONS · THEN VS NOW</b></div><div id="archaeologyKpis" class="worldbuilding-kpis archaeology-kpis"></div><div class="archaeology-toolbar"><label>Site<select id="archaeologySite"></select></label><button id="archaeologyExport">Export Archaeology Ledger</button></div><div id="archaeologyEmpty" class="archaeology-empty"></div><div id="archaeologyContent"><div class="archaeology-reconstruction"><article><small>THEN · RECONSTRUCTION</small><div id="archaeologyThen" class="archaeology-preview"></div></article><article><small>NOW · CURRENT LAYER</small><div id="archaeologyNow" class="archaeology-preview"></div></article></div><div class="labor-head"><span>RUIN LIFECYCLE</span><b>PRISTINE → DAMAGED → RUINED → OVERGROWN → EXCAVATED</b></div><div id="archaeologyLifecycle" class="archaeology-lifecycle"></div><div class="archaeology-grid"><div><div class="labor-head"><span>SITE RECORD</span></div><div id="archaeologySiteRecord"></div><div class="labor-head"><span>ARTIFACTS & INSCRIPTIONS</span></div><div id="archaeologyFinds" class="worldbuilding-landmarks"></div></div><div><div class="labor-head"><span>HISTORICAL STRATIGRAPHY</span></div><div id="archaeologyLayers" class="worldbuilding-landmarks"></div></div></div></div></section>`;if(note)note.insertAdjacentHTML('beforebegin',html);else panel.insertAdjacentHTML('beforeend',html);$('#archaeologySite').onchange=e=>{state.site=e.target.value;state.last=null;schedule(true)};$('#archaeologyExport').onclick=exportLedger}
function render(force=false){if(document.hidden&&!force)return;const w=world();if(!w)return;state.world=w;ensure();if(!$('#archaeologySection'))return;A.initialize(w);const sid=Number(UI.state.settlement||$('#worldbuildingSettlement')?.value||0),profile=W.settlementView(w,sid),arch=profile.archaeology||A.settlementView(w,sid),sum=A.summary(w),sites=arch.sites||[];if(!state.site||!sites.some(s=>s.id===state.site))state.site=sites[0]?.id||null;const site=sites.find(s=>s.id===state.site)||null,key=`${sum.revision}|${sid}|${state.site||'none'}|${sites.length}|${arch.layers?.length||0}`;if(!force&&key===state.last)return;state.last=key;
 $('#archaeologyKpis').innerHTML=[['SITES',sum.sites],['EXCAVATED',sum.excavated],['ARTIFACTS',sum.artifacts],['INSCRIPTIONS',sum.inscriptions],['HISTORICAL LAYERS',sum.historicalLayers],['RECONSTRUCTIONS',sum.reconstructions]].map(([k,v])=>`<div><span>${k}</span><b>${esc(v)}</b></div>`).join('');
 const sel=$('#archaeologySite');sel.innerHTML=sites.length?sites.map(s=>`<option value="${esc(s.id)}" ${s.id===state.site?'selected':''}>${esc(s.name)} · ${esc(s.lifecycleStage.replaceAll('_',' '))}</option>`).join(''):'<option value="">No archaeological sites</option>';
 $('#archaeologyEmpty').innerHTML=sites.length?'':`<article><small>NO ARCHAEOLOGICAL SITE IN THIS SETTLEMENT</small><p>Historical layers can still exist without a major excavatable landmark. Older ruins, battlefields and deteriorated Great Works become archaeology candidates automatically.</p></article>`;$('#archaeologyContent').style.display=site?'block':'none';if(!site)return;
 $('#archaeologyThen').innerHTML=R.renderReconstruction(profile,site,'then',{width:560,height:320,archaeologyLabels:false});$('#archaeologyNow').innerHTML=R.renderReconstruction(profile,site,'now',{width:560,height:320,archaeologyLabels:false});$('#archaeologyLifecycle').innerHTML=R.renderLifecycleStrip(profile,site,{width:820,height:150});
 $('#archaeologySiteRecord').innerHTML=`<article class="archaeology-record"><small>${esc(site.siteType.replaceAll('_',' ').toUpperCase())} · ${esc(site.lifecycleStage.replaceAll('_',' ').toUpperCase())}</small><h3>${esc(site.name)}</h3><p>Modeled archaeological survival derived from the historical landmark, age, environment and current condition. Reconstruction confidence: ${pct(site.reconstruction?.confidence)}.</p><div class="worldbuilding-mini"><span><i>INTEGRITY</i><b>${pct(site.integrity)}</b></span><span><i>VEGETATION</i><b>${pct(site.vegetation)}</b></span><span><i>BURIAL DEPTH</i><b>${fmt(site.burialDepthMeters,2)} m</b></span><span><i>SURVEY CONF.</i><b>${pct(site.surveyConfidence)}</b></span><span><i>EXCAVATION</i><b>${pct(site.excavationProgress)}</b></span><span><i>AGE</i><b>${fmt(site.ageYears)} y</b></span></div></article>`;
 const finds=[...(site.artifacts||[]).map(a=>`<article><div><small>ARTIFACT · ${esc(a.material.toUpperCase())}</small><h3>${esc(a.kind.replaceAll('_',' '))}</h3></div><div class="worldbuilding-mini"><span><i>DATE</i><b>${a.estimatedYear==null?'UNKNOWN':fmt(a.estimatedYear)}</b></span><span><i>CONDITION</i><b>${pct(a.condition)}</b></span><span><i>SIGNIFICANCE</i><b>${pct(a.significance)}</b></span><span><i>STATUS</i><b>${a.catalogued?'CATALOGUED':'IN SITU'}</b></span></div></article>`),...(site.inscriptions||[]).map(i=>`<article><div><small>INSCRIPTION · ${esc(i.script.toUpperCase())}</small><h3>${esc(i.subject)}</h3></div><div class="worldbuilding-mini"><span><i>DATE</i><b>${i.estimatedYear==null?'UNKNOWN':fmt(i.estimatedYear)}</b></span><span><i>LEGIBILITY</i><b>${pct(i.legibility)}</b></span><span><i>TRANSLATION</i><b>${i.translated?'AVAILABLE':'INCOMPLETE'}</b></span></div></article>`)];$('#archaeologyFinds').innerHTML=finds.length?finds.join(''):'<article><small>NO CATALOGUED FINDS</small><p>No artifact or inscription record is exposed for this site in the current deterministic survey.</p></article>';
 $('#archaeologyLayers').innerHTML=(arch.layers||[]).length?arch.layers.map(l=>`<article><div><small>${l.buried?'BURIED':'NEAR SURFACE'} · ${esc(l.dominantUse.replaceAll('_',' ').toUpperCase())}</small><h3>${esc(l.label)}</h3></div><div class="worldbuilding-mini"><span><i>DEPTH</i><b>${fmt(l.depthMeters,2)} m</b></span><span><i>SURVIVAL</i><b>${pct(l.survival)}</b></span><span><i>SOURCES</i><b>${l.sourceRefs.length}</b></span><span><i>SITES</i><b>${l.siteRefs.length}</b></span></div></article>`).join(''):'<article><small>NO STRATIGRAPHIC LAYERS</small><p>No dated settlement-specific historical sources are available to construct a stratigraphic layer.</p></article>';
 const status=$('#worldbuildingPanel .status-ready');if(status)status.textContent='v4.2';const pill=$('.version-pill');if(pill)pill.textContent='v4.2 · LIVING RUINS & ARCHAEOLOGY';const foot=document.querySelector('footer span');if(foot)foot.textContent='WorldForge v4.2 · Living Ruins & Archaeology';const note=$('#worldbuildingPanel .worldbuilding-note');if(note)note.textContent='Pixel settlement previews are deterministic and simulation-driven. v4.2 adds living ruin lifecycles, archaeological stratigraphy, artifact and inscription records, and then-vs-now historical reconstruction.';document.title=`${w.name} · Living Ruins & Archaeology · WorldForge v4.2`}
function schedule(force=false){if(state.raf)return;state.raf=requestAnimationFrame(()=>{state.raf=0;render(force)})}
function exportLedger(){const w=world();if(!w)return;A.initialize(w);const data={version:'4.2',world:w.name,year:W.absYear(w),summary:A.summary(w),settlements:w.archaeology.settlements,annual:w.archaeology.annual.slice(-500),fingerprint:A.fingerprint(w)};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${String(w.name||'worldforge').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-archaeology-ledger-y${W.absYear(w)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const observer=new MutationObserver(()=>schedule());observer.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden)schedule(true)});setInterval(()=>{if(!document.hidden)schedule()},6500);window.WorldForgeArchaeologyUI={state,render,schedule};setTimeout(()=>schedule(true),1400);
})();