(function(root,factory){
  const api=factory(root&&root.WorldForgeEngine,root&&root.WorldForgeHistory,root&&root.WorldForgeSociety,root&&root.WorldForgeCity,root&&root.WorldForgeAdventure);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeStory=api;
})(typeof window!=='undefined'?window:globalThis,function(Core,History,Society,City,Adventure){
'use strict';
const VERSION='0.6.0',STORY_SCHEMA=1;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const capturedAdventureSimulate=Adventure&&Adventure.simulateYears?Adventure.simulateYears.bind(Adventure):null;
const QUEST_VERBS=['Recover','Investigate','Protect','Expose','Negotiate for','Escort','Break','Trace','Rescue','Seal'];
const REWARDS=['coin','prestige','faction favor','rare loot','local influence','dynastic leverage','trade access','secret knowledge'];
function fallbackRng(seed){let h=2166136261>>>0;for(const ch of String(seed)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return function(){h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function rngFor(world,year,salt=''){return(Core?.rngFromSeed||fallbackRng)(`${world.settings.seed}|STORY|${year}|${salt}`)}
function pick(rng,a){return a[Math.floor(rng()*a.length)]}
function history(world){return History.initialize(world)}
function society(world){return Society.initialize(world)}
function adventure(world){return Adventure.initialize(world)}
function fullName(world,id){const p=world.society?.people?.[id];return p?Society.fullName(world.society,p):'Unknown'}
function activePerson(world,id,year){const p=world.society?.people?.[id];return p&&p.birthYear<=year&&(p.deathYear==null||p.deathYear>year)}
function candidatePeople(world,sid,year){return world.society.people.filter(p=>activePerson(world,p.id,year)&&(p.settlementId===sid||p.realmId===world.history.current.settlementKingdomIds[sid])).sort((a,b)=>b.prestige-a.prestige||a.id-b.id)}
function makeQuestNodes(world,q,rng){const place=world.settlements[q.settlementId]?.name||'the region',site=q.siteId!=null?world.adventure.sites[q.siteId]:null,nodes=[{id:0,type:'start',title:'Hook',text:`Speak with ${fullName(world,q.giverPersonId)} in ${place}.`,condition:null,effects:[]},{id:1,type:'objective',title:'Investigate',text:site?`Travel to ${site.name} and investigate the site.`:`Investigate reports around ${place}.`,condition:null,effects:[`flag:quest_${q.id}_investigated=true`]},{id:2,type:'choice',title:'Decision',text:'Choose how to resolve the central conflict.',condition:null,effects:[]}];const peaceful={id:3,type:'reward',title:'Measured Resolution',text:'Resolve the matter with negotiation, evidence or restraint.',condition:`prestige>=${20+Math.floor(rng()*35)}`,effects:[`flag:quest_${q.id}_peaceful=true`,`reward:${pick(rng,REWARDS)}`]},violent={id:4,type:'reward',title:'Forceful Resolution',text:'Resolve the matter through confrontation and direct action.',condition:site?`danger<=${Math.round(clamp(site.danger+18,35,95))}`:'combat_ready=true',effects:[`flag:quest_${q.id}_forceful=true`,`reward:${pick(rng,REWARDS)}`]},failure={id:5,type:'fail',title:'Complication',text:'The attempt fails and creates a new local complication.',condition:null,effects:[`flag:quest_${q.id}_failed=true`]};nodes.push(peaceful,violent,failure);return{nodes,edges:[{from:0,to:1,label:'accept'},{from:1,to:2,label:'continue'},{from:2,to:3,label:'negotiate',condition:peaceful.condition},{from:2,to:4,label:'confront',condition:violent.condition},{from:2,to:5,label:'withdraw'}]}}
function makeDialogue(world,q,rng){const giver=world.society.people[q.giverPersonId],place=world.settlements[q.settlementId]?.name||'this place',site=q.siteId!=null?world.adventure.sites[q.siteId]:null,id=world.story.dialogues.length;return{id,questId:q.id,personId:q.giverPersonId,title:`Conversation with ${fullName(world,q.giverPersonId)}`,nodes:[{id:0,speaker:q.giverPersonId,text:`Something is wrong near ${place}. I need someone who can act without drawing the whole court into it.`,choices:[{text:'Tell me what happened.',next:1,condition:null,effects:[]},{text:'Why trust me?',next:2,condition:'prestige>=25',effects:['flag:earned_trust=true']},{text:'Not interested.',next:3,condition:null,effects:[]}]},{id:1,speaker:q.giverPersonId,text:site?`The trouble leads back to ${site.name}. People who go near it return with stories, when they return at all.`:`The matter touches people with influence in ${place}.`,choices:[{text:'I will investigate.',next:4,condition:null,effects:[`flag:quest_${q.id}_accepted=true`]},{text:'I need payment first.',next:5,condition:'wealth<100',effects:['wealth:+20']}]},{id:2,speaker:q.giverPersonId,text:`Because ${giver?.traits?.includes('honorable')?'you have a reputation for keeping your word':'you are still outside the factions watching this matter'}.`,choices:[{text:'Then I will hear you out.',next:1,condition:null,effects:[]}]},{id:3,speaker:q.giverPersonId,text:'Then forget we spoke.',choices:[]},{id:4,speaker:q.giverPersonId,text:'Good. Bring me facts, not rumors.',choices:[]},{id:5,speaker:q.giverPersonId,text:'Fine. Consider it an advance, not a gift.',choices:[{text:'Agreed.',next:4,condition:null,effects:[`flag:quest_${q.id}_accepted=true`]}]}],createdYear:q.createdYear}}
function createQuest(world,s,data={}){const year=data.year??world.history.currentYear,rng=rngFor(world,year,`quest-${s.quests.length}-${data.sourceEventId??'x'}-${data.siteId??'x'}`),sid=data.settlementId??data.siteId!=null?world.adventure.sites[data.siteId]?.settlementId:0;const settlementId=Number.isInteger(sid)?sid:0,people=candidatePeople(world,settlementId,year),giver=data.giverPersonId??people[0]?.id??0,target=data.targetPersonId??people[1]?.id??null,site=data.siteId!=null?world.adventure.sites[data.siteId]:null,subject=site?.name||world.settlements[settlementId]?.name||'Local Matter';const q={id:s.quests.length,title:data.title||`${pick(rng,QUEST_VERBS)} ${subject}`,createdYear:year,resolvedYear:null,status:'available',giverPersonId:giver,targetPersonId:target,settlementId,realmId:world.history.current.settlementKingdomIds[settlementId],siteId:data.siteId??null,gangId:data.gangId??null,sourceEventId:data.sourceEventId??null,tags:data.tags||[site?'adventure':'world',data.gangId!=null?'crime':'history'].filter(Boolean),difficulty:Math.round(clamp((site?.danger||35)+(rng()-.5)*20,10,95)),variables:{},reward:pick(rng,REWARDS),nodes:[],edges:[]};const graph=makeQuestNodes(world,q,rng);q.nodes=graph.nodes;q.edges=graph.edges;s.quests.push(q);s.stats.questsCreated++;const d=makeDialogue(world,q,rng);s.dialogues.push(d);s.stats.dialoguesCreated++;return q}
function seedStory(world,s,year){const discovered=world.adventure.sites.filter(x=>x.active&&x.discovered).slice().sort((a,b)=>b.danger-a.danger).slice(0,10);for(const site of discovered)createQuest(world,s,{year,siteId:site.id,gangId:site.gangId,sourceEventId:site.sourceEventId});const gangs=world.cities.gangs.filter(g=>g.active).slice(0,6);for(const g of gangs)if(!s.quests.some(q=>q.gangId===g.id))createQuest(world,s,{year,settlementId:g.cityId,gangId:g.id,title:`Break the ${g.name}'s hold on ${world.settlements[g.cityId].name}`,tags:['crime','faction']})}
function initialize(world,options={}){history(world);society(world);City.initialize(world);adventure(world);if(world.story&&world.story.schemaVersion===STORY_SCHEMA){normalize(world,world.story);return world.story}const year=world.history.currentYear,s={schemaVersion:STORY_SCHEMA,engineVersion:VERSION,startYear:year,currentYear:year,quests:[],dialogues:[],variables:{prestige:35,wealth:50,combat_ready:true},processedSiteIds:[],processedEventIds:[],snapshots:[],stats:{questsCreated:0,questsResolved:0,questsFailed:0,dialoguesCreated:0,customQuests:0,customNodes:0}};world.story=s;seedStory(world,s,year);s.processedSiteIds=world.adventure.sites.map(x=>x.id);s.processedEventIds=world.history.events.map(e=>e.id);takeSnapshot(world,s,true);return s}
function normalize(world,s){s.engineVersion=VERSION;s.quests=s.quests||[];s.dialogues=s.dialogues||[];s.variables=s.variables||{};s.processedSiteIds=s.processedSiteIds||[];s.processedEventIds=s.processedEventIds||[];s.snapshots=s.snapshots||[];s.stats={questsCreated:0,questsResolved:0,questsFailed:0,dialoguesCreated:0,customQuests:0,customNodes:0,...s.stats};return s}
function pushEvent(world,e){const h=history(world);h.events.push({id:h.events.length,year:h.currentYear,...e})}
function processSources(world,s,year){const knownSites=new Set(s.processedSiteIds);for(const site of world.adventure.sites){if(knownSites.has(site.id))continue;s.processedSiteIds.push(site.id);knownSites.add(site.id);const rng=rngFor(world,year,`new-site-quest-${site.id}`);if(site.discovered&&rng()<.64)createQuest(world,s,{year,siteId:site.id,gangId:site.gangId,sourceEventId:site.sourceEventId})}const knownEvents=new Set(s.processedEventIds);for(const e of world.history.events){if(knownEvents.has(e.id))continue;s.processedEventIds.push(e.id);knownEvents.add(e.id);if(!['succession_crisis','gang_war','conquest','crackdown','collapse'].includes(e.type))continue;const sid=e.settlementIds?.[0];if(!Number.isInteger(sid))continue;const rng=rngFor(world,year,`event-quest-${e.id}`);if(rng()<.28)createQuest(world,s,{year,settlementId:sid,sourceEventId:e.id,gangId:e.gangIds?.[0]??null,tags:['history',e.type]})}}
function resolveQuests(world,s,year){for(const q of s.quests){if(q.status!=='available'||year-q.createdYear<2)continue;const rng=rngFor(world,year,`resolve-${q.id}`),giverAlive=activePerson(world,q.giverPersonId,year),site=q.siteId!=null?world.adventure.sites[q.siteId]:null,chance=clamp(.48+(giverAlive?.08:-.08)+(70-q.difficulty)/180+(site?.clears||0)*.04,.16,.82);if(rng()>.14)continue;if(rng()<chance){q.status='resolved';q.resolvedYear=year;s.stats.questsResolved++;s.variables[`quest_${q.id}_resolved`]=true;pushEvent(world,{type:'quest_resolved',importance:1,settlementIds:[q.settlementId],personIds:[q.giverPersonId,q.targetPersonId].filter(Number.isInteger),siteIds:[q.siteId].filter(Number.isInteger),questIds:[q.id],title:`Quest resolved: ${q.title}`,text:`The thread begun in Year ${q.createdYear} reaches a successful conclusion.`})}else{q.status='failed';q.resolvedYear=year;s.stats.questsFailed++;s.variables[`quest_${q.id}_failed`]=true;pushEvent(world,{type:'quest_failed',importance:1,settlementIds:[q.settlementId],personIds:[q.giverPersonId].filter(Number.isInteger),questIds:[q.id],title:`Quest failed: ${q.title}`,text:'The opportunity closes and leaves consequences for later stories.'})}}}
function metric(s){return{quests:s.quests.length,available:s.quests.filter(q=>q.status==='available').length,resolved:s.quests.filter(q=>q.status==='resolved').length,failed:s.quests.filter(q=>q.status==='failed').length,dialogues:s.dialogues.length,variables:Object.keys(s.variables).length,branches:s.quests.reduce((n,q)=>n+q.edges.length,0)}}
function takeSnapshot(world,s,force=false){const interval=world.history.snapshotInterval||5;if(!force&&s.currentYear%interval!==0)return null;const snap={year:s.currentYear,quests:s.quests.map(q=>[q.id,q.status,q.resolvedYear??-1]),variables:{...s.variables},stats:metric(s)};const last=s.snapshots[s.snapshots.length-1];if(last?.year===snap.year)s.snapshots[s.snapshots.length-1]=snap;else s.snapshots.push(snap);return snap}
function simulateStoryYear(world,s,year){s.currentYear=year;processSources(world,s,year);resolveQuests(world,s,year);takeSnapshot(world,s,false)}
function compactSnapshots(world,s){const interval=world.history.snapshotInterval||5,current=s.currentYear,by=new Map();for(const x of s.snapshots)if(x.year===s.startYear||x.year%interval===0||x.year===current)by.set(x.year,x);s.snapshots=[...by.values()].sort((a,b)=>a.year-b.year)}
function simulateYears(world,years,options={}){const s=initialize(world,options),h=history(world),n=clamp(Math.round(Number(years)||0),0,5000),target=clamp(h.currentYear+n,0,5000);if(!capturedAdventureSimulate)throw new Error('Adventure simulation unavailable');while(h.currentYear<target){capturedAdventureSimulate(world,1,options);simulateStoryYear(world,s,h.currentYear)}compactSnapshots(world,s);takeSnapshot(world,s,true);return s}
function simulateTo(world,targetYear,options={}){const h=history(world),target=clamp(Math.round(Number(targetYear)||0),h.currentYear,5000);return simulateYears(world,target-h.currentYear,options)}
function snapshotAt(world,year){const s=initialize(world),target=clamp(Math.round(Number(year)||0),s.startYear,s.currentYear);let best=s.snapshots[0];for(const x of s.snapshots)if(x.year<=target&&x.year>=best.year)best=x;return best}
function viewFromSnapshot(world,s,snap){return{year:snap.year,isPresent:snap.year===s.currentYear,quests:snap.quests.map(r=>{const q=s.quests[r[0]];return{...q,status:r[1],resolvedYear:r[2]<0?null:r[2]}}),dialogues:s.dialogues.filter(d=>d.createdYear<=snap.year).map(d=>({...d})),variables:{...snap.variables},stats:{...snap.stats}}}
function currentView(world){const s=initialize(world),snap={year:s.currentYear,quests:s.quests.map(q=>[q.id,q.status,q.resolvedYear??-1]),variables:{...s.variables},stats:metric(s)};return viewFromSnapshot(world,s,snap)}
function viewAt(world,year){const s=initialize(world);if(year>=s.currentYear)return currentView(world);return viewFromSnapshot(world,s,snapshotAt(world,year))}
function questDetail(world,id,year=null){const v=year==null?currentView(world):viewAt(world,year),q=v.quests.find(q=>q.id===Number(id));if(!q)return null;return{...q,giverName:fullName(world,q.giverPersonId),targetName:q.targetPersonId!=null?fullName(world,q.targetPersonId):null,settlementName:world.settlements[q.settlementId]?.name,siteName:q.siteId!=null?world.adventure.sites[q.siteId]?.name:null}}
function dialogueDetail(world,id,year=null){const v=year==null?currentView(world):viewAt(world,year),d=v.dialogues.find(d=>d.id===Number(id));if(!d)return null;return{...d,personName:fullName(world,d.personId)}}
function setVariable(world,key,value){const s=initialize(world);if(!String(key).trim())return false;s.variables[String(key).trim()]=value;takeSnapshot(world,s,true);return true}
function createCustomQuest(world,data={}){const s=initialize(world),q=createQuest(world,s,{year:s.currentYear,settlementId:Number.isInteger(data.settlementId)?data.settlementId:0,giverPersonId:Number.isInteger(data.giverPersonId)?data.giverPersonId:undefined,title:data.title||`Untitled Quest ${s.quests.length+1}`,tags:['custom']});s.stats.customQuests++;takeSnapshot(world,s,true);return q}
function addQuestNode(world,questId,data={}){const s=initialize(world),q=s.quests[Number(questId)];if(!q)return null;const node={id:q.nodes.length,type:data.type||'objective',title:data.title||`Node ${q.nodes.length}`,text:data.text||'',condition:data.condition||null,effects:[...(data.effects||[])]};q.nodes.push(node);if(Number.isInteger(data.from)&&q.nodes[data.from])q.edges.push({from:data.from,to:node.id,label:data.label||'continue',condition:data.condition||null});s.stats.customNodes++;takeSnapshot(world,s,true);return node}
function storyFingerprint(world){const s=initialize(world),rows=s.quests.map(q=>`${q.id}:${q.status}:${q.createdYear}:${q.resolvedYear??'x'}:${q.nodes.length}:${q.edges.length}`).join('|');let h=2166136261>>>0;for(const ch of`${s.currentYear}|${s.stats.questsCreated}|${s.stats.questsResolved}|${s.stats.questsFailed}|${s.dialogues.length}|${rows}`){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function validateStory(world){const errors=[],s=world?.story;if(!s||s.schemaVersion!==STORY_SCHEMA)return['story schema'];if(s.currentYear!==world.history?.currentYear)errors.push('story/history year mismatch');if(s.currentYear!==world.adventure?.currentYear)errors.push('story/adventure year mismatch');for(const q of s.quests){if(!world.settlements[q.settlementId])errors.push('quest settlement');const ids=new Set(q.nodes.map(n=>n.id));for(const e of q.edges)if(!ids.has(e.from)||!ids.has(e.to))errors.push('quest edge');if(q.siteId!=null&&!world.adventure.sites[q.siteId])errors.push('quest site')}for(const d of s.dialogues){const ids=new Set(d.nodes.map(n=>n.id));for(const n of d.nodes)for(const c of n.choices||[])if(c.next!=null&&!ids.has(c.next))errors.push('dialogue edge')}if(!s.snapshots.length||s.snapshots[s.snapshots.length-1].year!==s.currentYear)errors.push('story present snapshot');return[...new Set(errors)]}
return{VERSION,STORY_SCHEMA,initialize,simulateYears,simulateTo,currentView,viewAt,snapshotAt,questDetail,dialogueDetail,setVariable,createCustomQuest,addQuestNode,storyFingerprint,validateStory};
});