(function(root,factory){
  const api=factory(root&&root.WorldForgeArchaeology,root&&root.WorldForgeWorldbuilding);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeHeritage=api;
})(typeof window!=='undefined'?window:globalThis,function(Archaeology,Worldbuilding){
'use strict';
if(!Archaeology||!Worldbuilding)throw new Error('WorldForge v4.3 Heritage requires Archaeology and Worldbuilding');
const VERSION='4.3.0',SCHEMA=1;
const HERITAGE_STATUSES=Object.freeze(['unlisted','local_register','protected','national_heritage','world_heritage']);
const HOLDER_TYPES=Object.freeze(['site','museum','state_collection','private_collection']);
const EXPEDITION_STATUSES=Object.freeze(['planned','active','completed','suspended']);
const CLAIM_STATUSES=Object.freeze(['open','negotiating','returned','rejected']);
const INCIDENT_TYPES=Object.freeze(['looting_attempt','smuggling_case','wartime_removal','rescue_operation']);
const baseSimulate=Worldbuilding.simulateWorldbuildingYear.bind(Worldbuilding),baseSettlementView=Worldbuilding.settlementView.bind(Worldbuilding),baseSummary=Worldbuilding.summary.bind(Worldbuilding);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=4)=>Number(Number(v).toFixed(d));
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function year(world){return Worldbuilding.absYear(world)}
function settlement(world,sid){return world.settlements?.[Number(sid)]||null}
function realmId(world,sid){const s=settlement(world,sid);return Number.isInteger(s?.kingdomId)?s.kingdomId:(Number.isInteger(world.history?.current?.settlementKingdomIds?.[Number(sid)])?world.history.current.settlementKingdomIds[Number(sid)]:null)}
function realmName(world,rid){return Number.isInteger(rid)?(world.kingdoms?.[rid]?.name||`Realm ${rid}`):'Unaligned'}
function state(world){
 if(!world.heritage||world.heritage.schemaVersion!==SCHEMA)world.heritage={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:year(world),registrySites:[],museums:[],relics:[],expeditions:[],claims:[],incidents:[],annual:[],revision:0,lastAppliedYear:null,settings:{maxMuseums:14,maxRelics:160,maxExpeditions:18,maxClaims:24,maxIncidents:24},stats:{registrySites:0,protectedSites:0,worldHeritageSites:0,museums:0,relics:0,displayedRelics:0,disputedRelics:0,expeditions:0,activeExpeditions:0,claims:0,openClaims:0,incidents:0,recoveredRelics:0}};
 const H=world.heritage;H.engineVersion=VERSION;H.registrySites=H.registrySites||[];H.museums=H.museums||[];H.relics=H.relics||[];H.expeditions=H.expeditions||[];H.claims=H.claims||[];H.incidents=H.incidents||[];H.annual=H.annual||[];H.revision=Number(H.revision||0);H.settings={maxMuseums:14,maxRelics:160,maxExpeditions:18,maxClaims:24,maxIncidents:24,...H.settings};H.stats={registrySites:0,protectedSites:0,worldHeritageSites:0,museums:0,relics:0,displayedRelics:0,disputedRelics:0,expeditions:0,activeExpeditions:0,claims:0,openClaims:0,incidents:0,recoveredRelics:0,...H.stats};return H
}
function siteScore(world,archSettlement,site){const s=settlement(world,site.settlementId),capital=!!s?.capital,importance=clamp(Number(site.details?.landmarkImportance||.45),0,1),age=clamp(Number(site.ageYears||0)/320,0,1),integrity=clamp(Number(site.integrity||.4),0,1),finds=[...(site.artifacts||[]).map(x=>Number(x.significance||0)),...(site.inscriptions||[]).map(x=>Number(x.legibility||0)*.8)],findScore=finds.length?Math.max(...finds):0,stageBoost=site.lifecycleStage==='excavated'?.1:site.lifecycleStage==='overgrown'?.05:0;return round(clamp(importance*.38+age*.24+integrity*.08+findScore*.2+(capital?.1:0)+stageBoost,0,1),4)}
function statusFor(score){if(score>=.82)return'world_heritage';if(score>=.68)return'national_heritage';if(score>=.52)return'protected';if(score>=.34)return'local_register';return'unlisted'}
function protectionBudget(score,status,capital,h){const tier={unlisted:.25,local_register:.55,protected:1,national_heritage:1.8,world_heritage:2.8}[status]||.25;return Math.round((800+score*4200+(capital?1600:0)+h%900)*tier)}
function buildRegistrySite(world,archSettlement,site){const sid=Number(site.settlementId),s=settlement(world,sid),rid=realmId(world,sid),score=siteScore(world,archSettlement,site),status=statusFor(score),h=hash(`${world.seed||world.name}|${site.id}|heritage`),warLike=site.siteType==='battlefield'||/battle|war|siege/i.test(String(site.sourceType||'')),risk=round(clamp(.18+(1-Number(site.integrity||.5))*.35+Number(site.vegetation||0)*.15+(warLike?.12:0)+((h>>>7)%16)/100-(status==='world_heritage'?.13:status==='national_heritage'?.08:0),.04,.95),3);return{id:`heritage:${site.id}`,archaeologySiteId:site.id,settlementId:sid,name:site.name,realmId:rid,realmName:realmName(world,rid),status,score,protectionBudget:protectionBudget(score,status,!!s?.capital,h),conservationRisk:risk,custodian:status==='unlisted'?'local community':s?.capital?'state heritage office':'municipal heritage office',publicAccess:site.lifecycleStage==='excavated'||score>.55,emergencyPlan:status==='world_heritage'||status==='national_heritage'||risk>.66,lifecycleStage:site.lifecycleStage,originYear:site.originYear,ageYears:site.ageYears,x:site.x,y:site.y,artifactCount:(site.artifacts||[]).length,inscriptionCount:(site.inscriptions||[]).length,details:{siteType:site.siteType,integrity:site.integrity,landmarkImportance:site.details?.landmarkImportance||0,sourceEventId:site.details?.sourceEventId??null}}
}
function museumName(world,sid){const s=settlement(world,sid),n=s?.name||`Settlement ${sid}`;return s?.capital?`${n} National Museum`:`${n} Museum of History`}
function buildMuseums(world,registrySites){const by=new Map;for(const hs of registrySites){if(!by.has(hs.settlementId))by.set(hs.settlementId,[]);by.get(hs.settlementId).push(hs)}const candidates=[...by.entries()].map(([sid,sites])=>{const s=settlement(world,sid),max=Math.max(...sites.map(x=>x.score)),h=hash(`${world.seed||world.name}|museum|${sid}`),priority=max+(s?.capital?.4:0)+Math.min(.2,sites.length*.03);return{sid:Number(sid),sites,max,h,priority}}).sort((a,b)=>b.priority-a.priority||a.sid-b.sid).slice(0,state(world).settings.maxMuseums);return candidates.map(({sid,sites,max,h})=>{const s=settlement(world,sid),rid=realmId(world,sid),tier=s?.capital?'national':max>.7?'regional':'local',security=round(clamp(.48+(tier==='national'?.25:tier==='regional'?.14:.06)+((h>>>6)%16)/100,0,1),3),conservation=round(clamp(.5+max*.28+((h>>>11)%14)/100,0,1),3),prestige=round(clamp(max*.62+(s?.capital?.22:.06)+Math.min(.12,sites.length*.02),0,1),3);return{id:`museum:${sid}`,settlementId:sid,realmId:rid,name:museumName(world,sid),tier,foundedYear:Math.max(0,year(world)-(18+h%73)),capacity:60+(tier==='national'?180:tier==='regional'?100:40)+(h%40),security,conservation,prestige,collectionCount:0,displayedCount:0,storageCount:0,disputedCount:0,heritageSiteIds:sites.map(x=>x.id),x:round(.16+((h>>>16)%67)/100,3),y:round(.18+((h>>>22)%58)/100,3)}})}
function relicTitle(site,kind,material,subject){if(subject)return`${subject} from ${site.name}`;return`${material} ${String(kind||'relic').replaceAll('_',' ')} — ${site.name}`}
function chooseMuseum(museums,sid,rid,h){const home=museums.find(m=>m.settlementId===sid),same=museums.filter(m=>m.realmId===rid),foreign=museums.filter(m=>m.realmId!==rid);if(foreign.length&&h%11===0)return foreign[(h>>>7)%foreign.length];if(home)return home;if(same.length)return same[h%same.length];return museums.length?museums[h%museums.length]:null}
function relicFromFind(world,site,find,type,museums){const sid=Number(site.settlementId),rid=realmId(world,sid),h=hash(`${world.seed||world.name}|${site.id}|${type}|${find.id}`),significance=type==='artifact'?Number(find.significance||.4):clamp(Number(find.legibility||.4)*.72+(find.translated?.16:0),.1,1),museum=chooseMuseum(museums,sid,rid,h),foreign=!!museum&&museum.realmId!==rid;let holderType='site',holderId=site.id,holderRealmId=rid;if(museum&&significance>.56&&h%5!==1){holderType='museum';holderId=museum.id;holderRealmId=museum.realmId}else if(h%9===0){holderType='private_collection';holderId=`private:${(h>>>8)%9}`;holderRealmId=foreign&&museum?museum.realmId:rid}else if(significance>.8&&h%7===0){holderType='state_collection';holderId=`state:${rid}`;holderRealmId=rid}const removal=holderRealmId!==rid,illicit=holderType==='private_collection'&&h%4===0,provenance=[{year:find.estimatedYear??site.originYear??null,event:'created_or_deposited',placeSettlementId:sid,realmId:rid},{year:Math.max(0,year(world)-((h>>>12)%26)),event:site.lifecycleStage==='excavated'?'excavated':'surveyed',placeSettlementId:sid,realmId:rid}];if(holderType!=='site')provenance.push({year:Math.max(0,year(world)-((h>>>18)%12)),event:removal?(h%2?'foreign_transfer':'wartime_removal'):(holderType==='museum'?'museum_accession':'collection_transfer'),placeSettlementId:holderType==='museum'?museum?.settlementId:sid,realmId:holderRealmId});return{id:`relic:${site.id}:${type}:${find.id}`,sourceId:find.id,sourceType:type,archaeologySiteId:site.id,heritageSiteId:`heritage:${site.id}`,settlementId:sid,originRealmId:rid,originRealmName:realmName(world,rid),title:relicTitle(site,find.kind,find.material,find.subject),category:type==='artifact'?find.kind:'inscription',material:type==='artifact'?find.material:'inscribed material',estimatedYear:find.estimatedYear??null,significance:round(significance,3),condition:round(Number(type==='artifact'?find.condition:find.legibility)||.5,3),currentHolder:{type:holderType,id:holderId,realmId:holderRealmId,realmName:realmName(world,holderRealmId)},provenance,illicitSuspected:illicit,disputed:removal||illicit,onDisplay:holderType==='museum'&&h%4!==0,conservationPriority:round(clamp((1-Number(type==='artifact'?find.condition:find.legibility||.5))*.55+significance*.45,0,1),3)} }
function buildRelics(world,registrySites,museums){const archBy=new Map((world.archaeology?.settlements||[]).flatMap(s=>(s.sites||[]).map(site=>[site.id,site]))),out=[];for(const hs of registrySites){const site=archBy.get(hs.archaeologySiteId);if(!site)continue;for(const a of site.artifacts||[])out.push(relicFromFind(world,site,a,'artifact',museums));for(const i of site.inscriptions||[])out.push(relicFromFind(world,site,i,'inscription',museums))}out.sort((a,b)=>b.significance-a.significance||String(a.id).localeCompare(String(b.id)));return out.slice(0,state(world).settings.maxRelics)}
function updateMuseumCollections(museums,relics){for(const m of museums){const held=relics.filter(r=>r.currentHolder.type==='museum'&&r.currentHolder.id===m.id);m.collectionCount=held.length;m.displayedCount=held.filter(r=>r.onDisplay).length;m.storageCount=m.collectionCount-m.displayedCount;m.disputedCount=held.filter(r=>r.disputed).length}return museums}
function buildExpeditions(world,registrySites,museums,relics){const relBySite=new Map;for(const r of relics){if(!relBySite.has(r.archaeologySiteId))relBySite.set(r.archaeologySiteId,[]);relBySite.get(r.archaeologySiteId).push(r)}const candidates=registrySites.filter(s=>s.lifecycleStage!=='pristine'||s.score>.55).sort((a,b)=>b.score-a.score||b.conservationRisk-a.conservationRisk).slice(0,state(world).settings.maxExpeditions);return candidates.map((s,i)=>{const h=hash(`${world.seed||world.name}|expedition|${s.id}`),same=museums.filter(m=>m.realmId===s.realmId),sponsor=same.length?same[h%same.length]:museums[h%Math.max(1,museums.length)],status=s.lifecycleStage==='excavated'?'completed':h%7===0?'suspended':h%3===0?'active':'planned',progress=status==='completed'?1:status==='active'?round(.18+((h>>>8)%62)/100,2):status==='suspended'?round(.1+((h>>>10)%35)/100,2):0,teamSize=5+(h%13),risk=round(clamp(s.conservationRisk*.56+((h>>>13)%30)/100,.08,.95),3);return{id:`expedition:${s.archaeologySiteId}`,heritageSiteId:s.id,archaeologySiteId:s.archaeologySiteId,settlementId:s.settlementId,realmId:s.realmId,name:`${s.name} Field Project`,sponsorMuseumId:sponsor?.id||null,status,permitStatus:status==='suspended'?'review':s.status==='unlisted'?'local permit':'heritage permit',teamSize,budget:1200+Math.round(s.score*6500)+(h%1700),risk,progress,season:1+(h%4),leadSpecialty:['field archaeology','epigraphy','conservation','battlefield archaeology','architectural survey'][(h>>>17)%5],discoveryRelicIds:(relBySite.get(s.archaeologySiteId)||[]).slice(0,3).map(r=>r.id)}})}
function buildClaims(world,relics){const out=[];for(const r of relics){const holderRealm=r.currentHolder.realmId;if(!r.disputed||!Number.isInteger(r.originRealmId)||!Number.isInteger(holderRealm)||holderRealm===r.originRealmId&&!r.illicitSuspected)continue;const h=hash(`${world.seed||world.name}|claim|${r.id}`),status=CLAIM_STATUSES[h%CLAIM_STATUSES.length],basis=r.illicitSuspected?'illicit_excavation':r.provenance.some(p=>p.event==='wartime_removal')?'wartime_removal':r.sourceType==='inscription'?'sacred_or_documentary_origin':'cultural_origin',tension=round(clamp(.3+r.significance*.46+((h>>>9)%20)/100-(status==='returned'?.28:0),.1,1),3);out.push({id:`claim:${r.id}`,relicId:r.id,title:`Restitution claim — ${r.title}`,claimantRealmId:r.originRealmId,claimantRealmName:realmName(world,r.originRealmId),holderRealmId:holderRealm,holderRealmName:realmName(world,holderRealm),basis,status,tension,openedYear:Math.max(0,year(world)-(h%18)),publicSupport:round(clamp(.35+r.significance*.45+((h>>>14)%18)/100,0,1),3)})}return out.sort((a,b)=>b.tension-a.tension).slice(0,state(world).settings.maxClaims)}
function siteWarPressure(world,sid){const events=world.history?.events||[];return events.filter(e=>{const ids=[];if(Number.isInteger(e.settlementId))ids.push(e.settlementId);for(const id of e.settlementIds||[])if(Number.isInteger(id))ids.push(id);return ids.includes(Number(sid))&&/battle|war|siege|conquest|raid|collapse/i.test(String(e.type||'')+' '+String(e.title||''))}).length}
function buildIncidents(world,registrySites,relics){const siteMap=new Map(registrySites.map(s=>[s.archaeologySiteId,s])),out=[];for(const r of relics){const s=siteMap.get(r.archaeologySiteId);if(!s)continue;const h=hash(`${world.seed||world.name}|incident|${r.id}`),war=siteWarPressure(world,s.settlementId)>0,trigger=r.illicitSuspected||s.conservationRisk>.62||r.disputed||war&&r.significance>.65;if(!trigger||h%3===1)continue;const type=war&&h%4===0?'wartime_removal':r.illicitSuspected?'smuggling_case':h%5===0?'rescue_operation':'looting_attempt',recovered=type==='rescue_operation'||h%3===0;out.push({id:`incident:${r.id}`,type,relicId:r.id,heritageSiteId:s.id,settlementId:s.settlementId,realmId:s.realmId,year:Math.max(0,year(world)-(h%14)),severity:round(clamp(.3+r.significance*.4+s.conservationRisk*.3,0,1),3),detected:h%5!==0,recovered,status:recovered?'resolved':'open',description:type==='wartime_removal'?`Conflict pressure displaced ${r.title}.`:type==='smuggling_case'?`Authorities flagged an illicit transfer involving ${r.title}.`:type==='rescue_operation'?`Heritage staff secured ${r.title} during an emergency.`:`A looting attempt targeted ${r.title}.`})}return out.sort((a,b)=>b.severity-a.severity).slice(0,state(world).settings.maxIncidents)}
function refreshStats(world){const H=state(world);H.stats.registrySites=H.registrySites.length;H.stats.protectedSites=H.registrySites.filter(s=>!['unlisted','local_register'].includes(s.status)).length;H.stats.worldHeritageSites=H.registrySites.filter(s=>s.status==='world_heritage').length;H.stats.museums=H.museums.length;H.stats.relics=H.relics.length;H.stats.displayedRelics=H.relics.filter(r=>r.onDisplay).length;H.stats.disputedRelics=H.relics.filter(r=>r.disputed).length;H.stats.expeditions=H.expeditions.length;H.stats.activeExpeditions=H.expeditions.filter(e=>e.status==='active').length;H.stats.claims=H.claims.length;H.stats.openClaims=H.claims.filter(c=>c.status==='open'||c.status==='negotiating').length;H.stats.incidents=H.incidents.length;H.stats.recoveredRelics=H.incidents.filter(i=>i.recovered).length;return H.stats}
function sync(world,force=false){Archaeology.initialize(world);const H=state(world),y=year(world),sig=`${y}|${world.archaeology?.revision||0}|${world.history?.events?.length||0}|${world.settlements?.length||0}`;if(!force&&H._signature===sig)return H;const registry=[];for(const a of world.archaeology?.settlements||[])for(const site of a.sites||[])registry.push(buildRegistrySite(world,a,site));H.registrySites=registry.sort((a,b)=>b.score-a.score||String(a.id).localeCompare(String(b.id)));H.museums=buildMuseums(world,H.registrySites);H.relics=buildRelics(world,H.registrySites,H.museums);updateMuseumCollections(H.museums,H.relics);H.expeditions=buildExpeditions(world,H.registrySites,H.museums,H.relics);H.claims=buildClaims(world,H.relics);H.incidents=buildIncidents(world,H.registrySites,H.relics);H.currentYear=y;H._signature=sig;H.revision++;refreshStats(world);return H}
function settlementView(world,sid){sync(world);const id=Number(sid),H=state(world),museumIds=new Set(H.museums.filter(m=>m.settlementId===id).map(m=>m.id)),siteIds=new Set(H.registrySites.filter(s=>s.settlementId===id).map(s=>s.id)),archIds=new Set(H.registrySites.filter(s=>s.settlementId===id).map(s=>s.archaeologySiteId));return{settlementId:id,name:settlement(world,id)?.name||`Settlement ${id}`,registrySites:H.registrySites.filter(s=>s.settlementId===id),museums:H.museums.filter(m=>m.settlementId===id),relics:H.relics.filter(r=>r.settlementId===id||museumIds.has(r.currentHolder.id)),expeditions:H.expeditions.filter(e=>e.settlementId===id),claims:H.claims.filter(c=>H.relics.some(r=>r.id===c.relicId&&(r.settlementId===id||museumIds.has(r.currentHolder.id)))),incidents:H.incidents.filter(i=>i.settlementId===id||archIds.has(i.archaeologySiteId)||siteIds.has(i.heritageSiteId))}}
function decorateProfile(world,profile){if(!profile)return profile;profile.heritage=settlementView(world,profile.settlementId);return profile}
function summary(world){sync(world);return{year:state(world).currentYear,revision:state(world).revision,...refreshStats(world)}}
function simulateHeritageYear(world,y=year(world)){const H=sync(world,true),n=Math.floor(Number(y));if(H.lastAppliedYear===n)return H;H.currentYear=n;H.lastAppliedYear=n;const s=refreshStats(world);H.annual.push({year:n,registrySites:s.registrySites,protectedSites:s.protectedSites,museums:s.museums,relics:s.relics,disputedRelics:s.disputedRelics,activeExpeditions:s.activeExpeditions,openClaims:s.openClaims,incidents:s.incidents});if(H.annual.length>1000)H.annual.splice(0,H.annual.length-1000);return H}
function fingerprint(world){const H=sync(world),data={year:H.currentYear,registry:H.registrySites.map(s=>[s.id,s.status,s.score,s.protectionBudget,s.conservationRisk]),museums:H.museums.map(m=>[m.id,m.tier,m.security,m.conservation,m.prestige,m.collectionCount,m.disputedCount]),relics:H.relics.map(r=>[r.id,r.significance,r.condition,r.currentHolder.type,r.currentHolder.id,r.currentHolder.realmId,r.disputed,r.illicitSuspected,r.provenance.map(p=>[p.year,p.event,p.realmId])]),expeditions:H.expeditions.map(e=>[e.id,e.status,e.progress,e.risk,e.sponsorMuseumId]),claims:H.claims.map(c=>[c.id,c.status,c.basis,c.tension]),incidents:H.incidents.map(i=>[i.id,i.type,i.status,i.recovered,i.severity])};return hash(JSON.stringify(data)).toString(16).padStart(8,'0')}
function validate(world){const H=sync(world),e=[],ids=new Set;const add=(id,label)=>{if(ids.has(id))e.push(`duplicate ${label} ${id}`);ids.add(id)};for(const s of H.registrySites){add(s.id,'heritage site');if(!HERITAGE_STATUSES.includes(s.status))e.push(`heritage status ${s.id}`);for(const k of['score','conservationRisk'])if(!Number.isFinite(Number(s[k]))||Number(s[k])<0||Number(s[k])>1)e.push(`${k} ${s.id}`)}for(const m of H.museums){add(m.id,'museum');for(const k of['security','conservation','prestige'])if(!Number.isFinite(Number(m[k]))||m[k]<0||m[k]>1)e.push(`${k} ${m.id}`)}for(const r of H.relics){add(r.id,'relic');if(!HOLDER_TYPES.includes(r.currentHolder?.type))e.push(`holder ${r.id}`);if(!Number.isFinite(Number(r.significance))||r.significance<0||r.significance>1)e.push(`significance ${r.id}`)}for(const x of H.expeditions){add(x.id,'expedition');if(!EXPEDITION_STATUSES.includes(x.status))e.push(`expedition status ${x.id}`)}for(const c of H.claims){add(c.id,'claim');if(!CLAIM_STATUSES.includes(c.status))e.push(`claim status ${c.id}`)}for(const i of H.incidents){add(i.id,'incident');if(!INCIDENT_TYPES.includes(i.type))e.push(`incident type ${i.id}`)}return[...new Set(e)]}
function installBridge(){if(Worldbuilding.__heritageBridge)return;Worldbuilding.__heritageBridge=true;Worldbuilding.simulateWorldbuildingYear=function(world,y=year(world)){const out=baseSimulate(world,y);simulateHeritageYear(world,y);return out};Worldbuilding.settlementView=function(world,sid){return decorateProfile(world,baseSettlementView(world,sid))};Worldbuilding.summary=function(world){const b=baseSummary(world),h=summary(world);return{...b,heritageSites:h.registrySites,protectedHeritageSites:h.protectedSites,worldHeritageSites:h.worldHeritageSites,museums:h.museums,relics:h.relics,disputedRelics:h.disputedRelics,heritageExpeditions:h.expeditions,restitutionClaims:h.claims,heritageIncidents:h.incidents}};Worldbuilding.HERITAGE_VERSION=VERSION}
installBridge();
return{VERSION,SCHEMA,HERITAGE_STATUSES,HOLDER_TYPES,EXPEDITION_STATUSES,CLAIM_STATUSES,INCIDENT_TYPES,initialize:sync,simulateHeritageYear,settlementView,decorateProfile,summary,fingerprint,validate,statusFor,siteScore,buildRegistrySite,buildMuseums,buildRelics,buildExpeditions,buildClaims,buildIncidents,installBridge};
});