(function(root,factory){
  const api=factory(
    root&&root.WorldForgeHistory,
    root&&root.WorldForgeFactions,
    root&&root.WorldForgeTreasury,
    root&&root.WorldForgeWorkforce,
    root&&root.WorldForgeResources,
    root&&root.WorldForgeNutrition,
    root&&root.WorldForgePolitics,
    root&&root.WorldForgeMilitary
  );
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeDiplomacy=api;
})(typeof window!=='undefined'?window:globalThis,function(History,Factions,Treasury,Workforce,Resources,Nutrition,Politics,Military){
'use strict';
if(!History||!Treasury||!Workforce||!Resources||!Nutrition||!Politics)throw new Error('WorldForge v2.9 requires History, Treasury, Workforce, Resources, Nutrition and Politics');
const VERSION='2.9.0',SCHEMA=1,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
const TREATY_TYPES={
 trade_agreement:{name:'Trade Agreement',duration:18,trade:.34,trust:.035,goodwill:.045},
 non_aggression:{name:'Non-Aggression Pact',duration:16,trust:.045,goodwill:.025},
 defensive_pact:{name:'Defensive Pact',duration:20,trust:.055,goodwill:.04},
 alliance:{name:'Alliance',duration:28,trust:.075,goodwill:.06},
 embargo:{name:'Embargo',duration:7,trade:-.58,trust:-.08,goodwill:-.12},
 sanctions:{name:'Sanctions',duration:6,trade:-.36,trust:-.06,goodwill:-.09},
 peace_treaty:{name:'Peace Treaty',duration:14,trust:.025,goodwill:.055},
 humanitarian_aid:{name:'Humanitarian Aid Accord',duration:3,trust:.04,goodwill:.09}
};
const runtime=new WeakMap(),perf=new WeakMap();
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed);return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function seedOf(w){return w.endless?.baseSeed||String(w.settings?.seed||'WORLD').split('|EPOCH:')[0]}
function keyed(w,y,s){return rng(`${seedOf(w)}|DIPLOMACY|${y}|${s}`)}
function absYear(w){return Workforce.absYear(w)}
function realmName(w,rid){return w.history?.realms?.[rid]?.shortName||w.history?.current?.realmState?.[rid]?.name||`Realm ${rid}`}
function owner(w,sid){return w.history?.current?.settlementKingdomIds?.[sid]??w.settlements?.[sid]?.kingdomId??null}
function pairKey(a,b){a=Number(a);b=Number(b);return a<b?`${a}:${b}`:`${b}:${a}`}
function pairIds(a,b){a=Number(a);b=Number(b);return a<b?[a,b]:[b,a]}
function activeRealmIds(w){return(w.history?.current?.realmState||[]).filter(Boolean).map(x=>Number(x.id)).sort((a,b)=>a-b)}
function activeWarBetween(w,a,b){for(const id of w.history?.current?.activeWarIds||[]){const q=w.history?.wars?.[id];if(q&&q.endYear==null&&((q.attackerId===a&&q.defenderId===b)||(q.attackerId===b&&q.defenderId===a)))return q}return null}
function state(w){
 if(!w.diplomacy||w.diplomacy.schemaVersion!==SCHEMA)w.diplomacy={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:absYear(w),relations:[],realms:[],treaties:[],incidents:[],annual:[],archives:[],revision:0,lastAppliedYear:null,nextTreatyId:1,settings:{retainDetailedYears:1000,maxIncidents:900,maxTreaties:1200,autoTreaties:true,tradeTransferRate:.045,aidIntensity:1},stats:{activeTreaties:0,tradeAgreements:0,alliances:0,nonAggressionPacts:0,embargoes:0,sanctions:0,aidMissions:0,peaceTreaties:0,highWarRisk:0,meanTrust:0,meanTension:0,meanTradeAccess:0,aidSpending:0,foodTransferred:0,diplomaticIncidents:0,archivedYears:0}};
 const S=w.diplomacy;S.engineVersion=VERSION;S.relations=S.relations||[];S.realms=S.realms||[];S.treaties=S.treaties||[];S.incidents=S.incidents||[];S.annual=S.annual||[];S.archives=S.archives||[];S.revision=Number(S.revision||0);S.nextTreatyId=Number(S.nextTreatyId||1);S.settings={retainDetailedYears:1000,maxIncidents:900,maxTreaties:1200,autoTreaties:true,tradeTransferRate:.045,aidIntensity:1,...S.settings};S.stats={activeTreaties:0,tradeAgreements:0,alliances:0,nonAggressionPacts:0,embargoes:0,sanctions:0,aidMissions:0,peaceTreaties:0,highWarRisk:0,meanTrust:0,meanTension:0,meanTradeAccess:0,aidSpending:0,foodTransferred:0,diplomaticIncidents:0,archivedYears:0,...S.stats};return S
}
function blankRealm(rid){return{realmId:Number(rid),lastYear:null,diplomaticReputation:.55,treatyReliability:.72,isolation:.35,foreignPressure:.1,tradeExposure:.15,aidGiven:0,aidReceived:0,activeTreaties:0,allies:0,rivals:0}}
function blankRelation(w,a,b){const [x,y]=pairIds(a,b),r=keyed(w,0,`initial:${x}:${y}`),good=(r()-.5)*.16;return{key:pairKey(x,y),realmA:x,realmB:y,lastYear:null,trust:round(.4+r()*.2,4),goodwill:round(good,4),fear:round(.08+r()*.18,4),rivalry:round(.12+r()*.22,4),tradeDependence:0,borderTension:.08,claimPressure:.05,diplomaticTension:.18,warRisk:.04,allianceAffinity:.12,tradeAccess:1,activeWar:false,lastIncident:null}}
function buildRuntime(w,force=false){const S=state(w),year=absYear(w),tr=w.treasury?.realms||[],pr=w.politics?.realms||[],mk=w.resources?.markets||[],nu=w.nutrition?.profiles||[],flows=w.resources?.flows||[],arms=w.military?.armies||[],fleets=w.military?.fleets||[],sig=`${year}|${w.politics?.revision||0}|${w.nutrition?.revision||0}|${w.resources?.currentYear||0}|${flows.length}|${tr.length}|${arms.length}|${fleets.length}|${S.relations.length}|${S.treaties.length}|${S.revision}`;let r=runtime.get(w);if(!force&&r&&r.signature===sig)return r;const by=(a,key)=>new Map(a.map(x=>[Number(key(x)),x])),marketsByRealm=new Map,nutritionByRealm=new Map,tradeByPair=new Map,totalTradeByRealm=new Map,borderPairs=new Set;
 for(const m of mk){const rid=owner(w,m.settlementId);if(rid==null)continue;const a=marketsByRealm.get(Number(rid))||[];a.push(m);marketsByRealm.set(Number(rid),a)}
 for(const p of nu){const rid=owner(w,p.settlementId);if(rid==null)continue;const a=nutritionByRealm.get(Number(rid))||[];a.push(p);nutritionByRealm.set(Number(rid),a)}
 for(const f of flows.slice(-Math.min(flows.length,900))){const a=Number(f.fromRealmId),b=Number(f.toRealmId);if(!Number.isFinite(a)||!Number.isFinite(b)||a===b)continue;const q=Math.max(0,Number(f.quantity||0)),k=pairKey(a,b);tradeByPair.set(k,(tradeByPair.get(k)||0)+q);totalTradeByRealm.set(a,(totalTradeByRealm.get(a)||0)+q);totalTradeByRealm.set(b,(totalTradeByRealm.get(b)||0)+q)}
 for(const road of w.roads||[]){const a=owner(w,road.from),b=owner(w,road.to);if(a!=null&&b!=null&&a!==b)borderPairs.add(pairKey(a,b))}
 const forceByRealm=new Map;for(const a of arms){if(a.status&&a.status!=='active')continue;const rid=Number(a.realmId),v=Math.max(0,Number(a.size||0))*Math.max(.2,Number(a.readiness??a.morale??.7));forceByRealm.set(rid,(forceByRealm.get(rid)||0)+v)}for(const f of fleets){if(f.status&&f.status!=='active')continue;const rid=Number(f.realmId),v=Math.max(0,Number(f.hulls||0))*120*Math.max(.2,Number(f.readiness??.7));forceByRealm.set(rid,(forceByRealm.get(rid)||0)+v)}
 r={signature:sig,treasury:by(tr,x=>x.realmId),politics:by(pr,x=>x.realmId),relations:new Map(S.relations.map(x=>[x.key,x])),realmProfiles:by(S.realms,x=>x.realmId),marketsByRealm,nutritionByRealm,tradeByPair,totalTradeByRealm,borderPairs,forceByRealm};runtime.set(w,r);const p=perf.get(w)||{cacheBuilds:0,reads:0,relationHits:0,treatyEvaluations:0,tradeTransfers:0};p.cacheBuilds++;perf.set(w,p);return r
}
function sync(w){const S=state(w),ids=activeRealmIds(w),valid=new Set(ids),pairs=new Set;const rb=new Map(S.relations.map(x=>[x.key,x])),rp=new Map(S.realms.map(x=>[Number(x.realmId),x]));for(const rid of ids)if(!rp.has(rid))S.realms.push(blankRealm(rid));for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const k=pairKey(ids[i],ids[j]);pairs.add(k);if(!rb.has(k))S.relations.push(blankRelation(w,ids[i],ids[j]))}S.realms=S.realms.filter(x=>valid.has(Number(x.realmId)));S.relations=S.relations.filter(x=>pairs.has(x.key));for(const t of S.treaties)if(t.status==='active'&&(!valid.has(Number(t.realmA))||!valid.has(Number(t.realmB))))t.status='lapsed';runtime.delete(w);buildRuntime(w,true);return S}
function relationState(w,a,b){const S=initialize(w),k=pairKey(a,b),r=buildRuntime(w);let q=r.relations.get(k);if(!q){q=blankRelation(w,a,b);S.relations.push(q);r.relations.set(k,q)}const p=perf.get(w)||{cacheBuilds:0,reads:0,relationHits:0,treatyEvaluations:0,tradeTransfers:0};p.relationHits++;perf.set(w,p);return q}
function realmState(w,rid){rid=Number(rid);const S=initialize(w),r=buildRuntime(w);let q=r.realmProfiles.get(rid);if(!q){q=blankRealm(rid);S.realms.push(q);r.realmProfiles.set(rid,q)}return q}
function treatyActive(w,type,a,b){const k=pairKey(a,b);return state(w).treaties.find(t=>t.status==='active'&&t.type===type&&t.pairKey===k)||null}
function activeTreaties(w,a,b){const k=pairKey(a,b);return state(w).treaties.filter(t=>t.status==='active'&&t.pairKey===k)}
function realmNutrition(w,rid){const arr=buildRuntime(w).nutritionByRealm.get(Number(rid))||[];if(!arr.length)return{famine:0,malnutrition:0,reliefNeed:0};return{famine:arr.reduce((n,x)=>n+Number(x.famineStage||0),0)/(arr.length*5),malnutrition:arr.reduce((n,x)=>n+Number(x.malnutritionRate||0),0)/arr.length,reliefNeed:arr.reduce((n,x)=>n+Number(x.reliefNeeded||0),0)}}
function realmPower(w,rid){return Math.max(1,Number(buildRuntime(w).forceByRealm.get(Number(rid))||0)+Number(w.history?.current?.realmState?.[rid]?.militaryPower||0))}
function relationConditions(w,a,b){const r=buildRuntime(w),q=relationState(w,a,b),pa=r.politics.get(Number(a))||{},pb=r.politics.get(Number(b))||{},ta=r.treasury.get(Number(a))||{},tb=r.treasury.get(Number(b))||{},na=realmNutrition(w,a),nb=realmNutrition(w,b),powerA=realmPower(w,a),powerB=realmPower(w,b),fear=clamp(Math.abs(powerA-powerB)/Math.max(powerA,powerB),0,1),trade=Number(r.tradeByPair.get(q.key)||0),totalA=Number(r.totalTradeByRealm.get(Number(a))||0),totalB=Number(r.totalTradeByRealm.get(Number(b))||0),tradeDep=clamp(trade/Math.max(1,(totalA+totalB)*.5),0,1),border=r.borderPairs.has(q.key)?1:0,war=activeWarBetween(w,Number(a),Number(b)),instability=clamp((Number(pa.revolutionRisk||0)+Number(pb.revolutionRisk||0)+Number(pa.secessionRisk||0)+Number(pb.secessionRisk||0))/4,0,1),fiscal=clamp((Number(ta.debt||0)/Math.max(1,Number(ta.lastRevenue||1))+Number(tb.debt||0)/Math.max(1,Number(tb.lastRevenue||1)))/20,0,1);return{q,pa,pb,ta,tb,na,nb,powerA,powerB,fear,tradeDep,border,war,instability,fiscal}}
function pushHistory(w,e){const h=History.initialize(w);h.events.push({id:h.events.length,year:h.currentYear,absoluteYear:absYear(w),...e});return h.events.at(-1)}
function recordIncident(w,type,year,a,b,data={}){const S=state(w),k=pairKey(a,b),id=`diplomacy:${type}:${year}:${k}:${data.side??''}`;if(S.incidents.some(x=>x.id===id))return null;const x={id,type,year,pairKey:k,realmA:Number(a),realmB:Number(b),...data};S.incidents.push(x);if(S.incidents.length>S.settings.maxIncidents)S.incidents.splice(0,S.incidents.length-S.settings.maxIncidents);S.stats.diplomaticIncidents++;return x}
function signTreaty(w,type,a,b,year=absYear(w),options={}){if(!TREATY_TYPES[type])throw new Error(`Unknown treaty type: ${type}`);a=Number(a);b=Number(b);if(a===b)throw new Error('Treaty requires two realms');const S=initialize(w),[x,y]=pairIds(a,b),k=pairKey(x,y),existing=treatyActive(w,type,x,y);if(existing)return existing;const def=TREATY_TYPES[type],duration=Math.max(1,Math.floor(Number(options.duration??def.duration))),t={id:S.nextTreatyId++,type,name:def.name,pairKey:k,realmA:x,realmB:y,signedYear:Number(year),expiresYear:Number(year)+duration,status:'active',strength:round(clamp(Number(options.strength??.7),.1,1),3),imposedBy:options.imposedBy==null?null:Number(options.imposedBy),targetRealmId:options.targetRealmId==null?null:Number(options.targetRealmId),lastAppliedYear:null,terms:options.terms||{}};S.treaties.push(t);if(S.treaties.length>S.settings.maxTreaties){const removable=S.treaties.findIndex(z=>z.status!=='active');if(removable>=0)S.treaties.splice(removable,1)}const rel=relationState(w,x,y);rel.trust=round(clamp(rel.trust+Number(def.trust||0)*t.strength,0,1),4);rel.goodwill=round(clamp(rel.goodwill+Number(def.goodwill||0)*t.strength,-1,1),4);recordIncident(w,'treaty_signed',year,x,y,{treatyId:t.id,treatyType:type});if(['alliance','defensive_pact','peace_treaty','trade_agreement','humanitarian_aid'].includes(type))pushHistory(w,{type:'treaty_signed',importance:type==='alliance'||type==='peace_treaty'?2:1,realmIds:[x,y],title:`${realmName(w,x)} and ${realmName(w,y)} sign ${def.name}`,text:`The two realms formalize a ${def.name.toLowerCase()} in year ${year}.`});S.revision++;runtime.delete(w);return t}
function terminateTreaty(w,id,year=absYear(w),reason='expired'){const S=initialize(w),t=S.treaties.find(x=>x.id===Number(id));if(!t||t.status!=='active')return t||null;t.status=reason==='expired'?'expired':'terminated';t.endedYear=Number(year);t.endReason=reason;recordIncident(w,'treaty_ended',year,t.realmA,t.realmB,{treatyId:t.id,treatyType:t.type,reason});S.revision++;runtime.delete(w);return t}
function imposeEmbargo(w,from,to,year=absYear(w),options={}){return signTreaty(w,options.sanctions?'sanctions':'embargo',from,to,year,{...options,imposedBy:Number(from),targetRealmId:Number(to)})}
function foodEquivalent(m){return Number(Nutrition.foodBasket(m)?.stockEquivalent||0)}
function takeFood(m,amount){let remain=Math.max(0,amount),taken=0;const ids=(Resources.FOOD_IDS||[]).slice().sort((a,b)=>Number(m.inventory?.[b]||0)*(Resources.MAP.get(b)?.food||0)-Number(m.inventory?.[a]||0)*(Resources.MAP.get(a)?.food||0));for(const id of ids){if(remain<=.0001)break;const c=Resources.MAP.get(id),f=Math.max(.05,Number(c?.food||0)),inv=Math.max(0,Number(m.inventory?.[id]||0)),eq=inv*f,use=Math.min(eq,remain),qty=use/f;if(qty>0){m.inventory[id]=round(Math.max(0,inv-qty),4);taken+=use;remain-=use}}return taken}
function addFood(m,amount){let remain=Math.max(0,amount),added=0;const ids=(Resources.FOOD_IDS||[]).slice().sort((a,b)=>(Resources.MAP.get(b)?.food||0)-(Resources.MAP.get(a)?.food||0));for(let i=0;i<ids.length&&remain>.0001;i++){const id=ids[i],c=Resources.MAP.get(id),f=Math.max(.05,Number(c?.food||0)),share=i===ids.length-1?remain:remain/(ids.length-i),qty=share/f;m.inventory[id]=round(Math.max(0,Number(m.inventory?.[id]||0))+qty,4);added+=share;remain-=share}return added}
function transferFood(w,fromRid,toRid,amount,year,reason){const r=buildRuntime(w),donors=(r.marketsByRealm.get(Number(fromRid))||[]).slice().sort((a,b)=>Number(b.foodSecurity||0)-Number(a.foodSecurity||0)),targets=(r.marketsByRealm.get(Number(toRid))||[]).slice().sort((a,b)=>Number(a.foodSecurity||1)-Number(b.foodSecurity||1));if(!donors.length||!targets.length)return 0;let remain=Math.max(0,amount),moved=0;for(const d of donors){if(remain<=.001)break;const basket=Nutrition.foodBasket(d),reserve=Math.max(.2,basket.stockEquivalent*.68),available=Math.max(0,basket.stockEquivalent-reserve);if(available<=.01||Number(d.foodSecurity||0)<.72)continue;const q=takeFood(d,Math.min(remain,available));if(q<=0)continue;const target=targets[0],delivered=q*.985;addFood(target,delivered);moved+=delivered;remain-=q;d.exports=d.exports||{};target.imports=target.imports||{};d.exports.diplomatic_food=round(Number(d.exports.diplomatic_food||0)+q,3);target.imports.diplomatic_food=round(Number(target.imports.diplomatic_food||0)+delivered,3)}if(moved>0){const p=perf.get(w)||{cacheBuilds:0,reads:0,relationHits:0,treatyEvaluations:0,tradeTransfers:0};p.tradeTransfers++;perf.set(w,p);state(w).stats.foodTransferred=round(state(w).stats.foodTransferred+moved,3);recordIncident(w,reason,year,fromRid,toRid,{fromRealmId:Number(fromRid),toRealmId:Number(toRid),food:round(moved,3)})}return moved}
function applyMarketPenalty(w,targetRid,strength){for(const m of buildRuntime(w).marketsByRealm.get(Number(targetRid))||[]){m.marketStress=round(clamp(Number(m.marketStress||0)+.015*strength,0,1),4);for(const c of Resources.COMMODITIES||[]){const base=Number(c.basePrice||1),cur=Number(m.prices?.[c.id]??base);m.prices[c.id]=round(clamp(cur*(1+.012*strength),base*.55,base*5.5),2)}}}
function applyPoliticsFeedback(w,rid,{positive=0,negative=0,merchant=0}={}){const rr=w.politics?.realms?.find(x=>Number(x.realmId)===Number(rid));if(rr){rr.legitimacy=round(clamp(Number(rr.legitimacy||.5)+positive-negative*.7,0,1),4);rr.grievance=round(clamp(Number(rr.grievance||.2)+negative-positive*.45,0,1),4);rr.publicOrder=round(clamp(Number(rr.publicOrder||.5)+positive*.25-negative*.3,0,1),4)}for(const p of w.politics?.profiles||[]){if(Number(p.realmId)!==Number(rid))continue;p.legitimacy=round(clamp(Number(p.legitimacy||.5)+positive*.7-negative*.55,0,1),4);p.grievance=round(clamp(Number(p.grievance||.2)+negative*.75-positive*.35,0,1),4);if(p.blocs?.merchants&&merchant){p.blocs.merchants.grievance=round(clamp(Number(p.blocs.merchants.grievance||0)+merchant,0,1),4);p.blocs.merchants.opposition=round(clamp(Number(p.blocs.merchants.opposition||0)+merchant*.7,0,1),4)}}}
function applyTreaty(w,t,year){if(t.status!=='active'||t.lastAppliedYear===year)return;const rel=relationState(w,t.realmA,t.realmB),def=TREATY_TYPES[t.type],strength=Number(t.strength||.7);rel.tradeAccess=round(clamp(rel.tradeAccess+Number(def.trade||0)*strength,0,1.4),4);if(t.type==='trade_agreement'){const na=realmNutrition(w,t.realmA),nb=realmNutrition(w,t.realmB);const from=na.famine<=nb.famine?t.realmA:t.realmB,to=from===t.realmA?t.realmB:t.realmA,need=Math.abs(na.famine-nb.famine)+Math.abs(na.malnutrition-nb.malnutrition);if(need>.04)transferFood(w,from,to,clamp(need*4*state(w).settings.tradeTransferRate*10,.05,2.5)*strength,year,'treaty_trade_flow');applyPoliticsFeedback(w,t.realmA,{positive:.0025*strength});applyPoliticsFeedback(w,t.realmB,{positive:.0025*strength})}
 if(t.type==='embargo'||t.type==='sanctions'){const target=t.targetRealmId??t.realmB;applyMarketPenalty(w,target,(t.type==='embargo'?1:.65)*strength);applyPoliticsFeedback(w,target,{negative:.0075*strength,merchant:.012*strength});const imposer=t.imposedBy??t.realmA;applyPoliticsFeedback(w,imposer,{negative:.0015*strength})}
 if(t.type==='non_aggression'){rel.rivalry=round(clamp(rel.rivalry-.018*strength,0,1),4);rel.borderTension=round(clamp(rel.borderTension-.022*strength,0,1),4)}
 if(t.type==='defensive_pact'||t.type==='alliance'){rel.trust=round(clamp(rel.trust+.01*strength,0,1),4);rel.fear=round(clamp(rel.fear-.008*strength,0,1),4)}
 if(t.type==='peace_treaty'){rel.rivalry=round(clamp(rel.rivalry-.035*strength,0,1),4);rel.borderTension=round(clamp(rel.borderTension-.04*strength,0,1),4);rel.claimPressure=round(clamp(rel.claimPressure-.025*strength,0,1),4)}
 if(t.type==='humanitarian_aid'){const donor=t.imposedBy??t.realmA,target=t.targetRealmId??t.realmB,a=buildRuntime(w).treasury.get(Number(donor)),need=realmNutrition(w,target),budget=Math.min(Math.max(0,Number(a?.treasury||0))*.008,(1+need.famine*4+need.malnutrition*2)*state(w).settings.aidIntensity);if(a&&budget>.05){a.treasury=round(Math.max(0,Number(a.treasury||0)-budget),2);const moved=transferFood(w,donor,target,clamp(budget*.42,.08,4),year,'humanitarian_aid');state(w).stats.aidSpending=round(state(w).stats.aidSpending+budget,2);realmState(w,donor).aidGiven=round(Number(realmState(w,donor).aidGiven||0)+budget,2);realmState(w,target).aidReceived=round(Number(realmState(w,target).aidReceived||0)+budget,2);applyPoliticsFeedback(w,target,{positive:.006*strength+Math.min(.006,moved*.002)});rel.goodwill=round(clamp(rel.goodwill+.018*strength,-1,1),4)}}
 t.lastAppliedYear=year
}
function sendHumanitarianAid(w,from,to,year=absYear(w),options={}){return signTreaty(w,'humanitarian_aid',from,to,year,{...options,imposedBy:Number(from),targetRealmId:Number(to),duration:options.duration??3})}
function evaluateRelation(w,rel,year){const c=relationConditions(w,rel.realmA,rel.realmB),ts=activeTreaties(w,rel.realmA,rel.realmB),has=type=>ts.some(t=>t.type===type),rr=keyed(w,year,rel.key),tradeBoost=has('trade_agreement')?.13:0,peace=has('non_aggression')||has('peace_treaty'),allied=has('alliance')||has('defensive_pact'),hostile=has('embargo')||has('sanctions');rel.activeWar=!!c.war;rel.tradeDependence=round(clamp(rel.tradeDependence*.62+c.tradeDep*.38+tradeBoost,0,1),4);rel.fear=round(clamp(rel.fear*.72+c.fear*.28+(c.war?.08:0),0,1),4);rel.borderTension=round(clamp(rel.borderTension*.78+c.border*.055+(c.war?.18:0)+(hostile?.045:0)-(peace?.035:0),0,1),4);const instabilityClaim=c.instability*.08+(c.border?.025:0);rel.claimPressure=round(clamp(rel.claimPressure*.88+instabilityClaim+(c.war?.06:0)-(peace?.012:0),0,1),4);rel.rivalry=round(clamp(rel.rivalry*.95+(c.war?.09:0)+(hostile?.035:0)+rel.claimPressure*.015-(allied?.035:0)-(peace?.018:0),0,1),4);const trustDrift=(allied?.012:0)+(has('trade_agreement')?.006:0)+(peace?.006:0)-(hostile?.018:0)-(c.war?.05:0);rel.trust=round(clamp(rel.trust*.995+trustDrift,0,1),4);rel.goodwill=round(clamp(rel.goodwill*.97+(allied?.012:0)+(has('trade_agreement')?.008:0)-(hostile?.02:0)-(c.war?.04:0),-1,1),4);const hostility=rel.rivalry*.28+rel.borderTension*.2+rel.claimPressure*.18+rel.fear*.08+Math.max(0,-rel.goodwill)*.12+(1-rel.trust)*.1+(c.war?.28:0)+(hostile?.12:0),cooperation=rel.trust*.16+Math.max(0,rel.goodwill)*.12+rel.tradeDependence*.1+(allied?.12:0)+(peace?.08:0);rel.diplomaticTension=round(clamp(hostility-cooperation,0,1),4);rel.warRisk=round(clamp((rel.diplomaticTension-.22)*.9+rel.rivalry*.18+rel.claimPressure*.16+rel.borderTension*.12+(c.war?.45:0),0,1),4);rel.allianceAffinity=round(clamp(rel.trust*.42+Math.max(0,rel.goodwill)*.25+rel.tradeDependence*.18+(1-rel.rivalry)*.1-rel.diplomaticTension*.22,0,1),4);let access=1+rel.tradeDependence*.12+(has('trade_agreement')?.22:0)+(allied?.08:0)-(has('sanctions')?.4:0)-(has('embargo')?.72:0)-(c.war?.72:0);rel.tradeAccess=round(clamp(access,0,1.4),4);rel.lastYear=year;
 const p=perf.get(w)||{cacheBuilds:0,reads:0,relationHits:0,treatyEvaluations:0,tradeTransfers:0};p.treatyEvaluations++;perf.set(w,p);
 if(rel.diplomaticTension>.72&&rr()<.13){const inc=recordIncident(w,'diplomatic_crisis',year,rel.realmA,rel.realmB,{severity:round(rel.diplomaticTension,3),warRisk:rel.warRisk});if(inc){rel.lastIncident=inc.id;pushHistory(w,{type:'diplomatic_crisis',importance:rel.warRisk>.72?2:1,realmIds:[rel.realmA,rel.realmB],title:`Diplomatic crisis: ${realmName(w,rel.realmA)} and ${realmName(w,rel.realmB)}`,text:`Rivalry, claims and border tension push relations toward confrontation; estimated war risk reaches ${Math.round(rel.warRisk*100)}%.`})}}
 if(!state(w).settings.autoTreaties||c.war)return rel;
 if(!has('trade_agreement')&&rel.trust>.5&&rel.diplomaticTension<.48&&(rel.tradeDependence>.08||c.tradeDep>.03)&&rr()<.18)signTreaty(w,'trade_agreement',rel.realmA,rel.realmB,year);
 if(!has('non_aggression')&&!allied&&rel.trust>.46&&rel.diplomaticTension>.24&&rel.diplomaticTension<.58&&rr()<.08)signTreaty(w,'non_aggression',rel.realmA,rel.realmB,year);
 if(!has('defensive_pact')&&!has('alliance')&&rel.allianceAffinity>.57&&rel.fear>.18&&rel.diplomaticTension<.38&&rr()<.055)signTreaty(w,'defensive_pact',rel.realmA,rel.realmB,year);
 if(!has('alliance')&&rel.allianceAffinity>.7&&rel.trust>.68&&rel.goodwill>.1&&rel.diplomaticTension<.28&&rr()<.035)signTreaty(w,'alliance',rel.realmA,rel.realmB,year);
 if(!hostile&&rel.rivalry>.62&&rel.diplomaticTension>.6&&rr()<.11){const imposer=c.powerA>=c.powerB?rel.realmA:rel.realmB,target=imposer===rel.realmA?rel.realmB:rel.realmA;imposeEmbargo(w,imposer,target,year,{strength:.55+rr()*.35})}
 const needA=c.na.famine+c.na.malnutrition*.5,needB=c.nb.famine+c.nb.malnutrition*.5;if(!has('humanitarian_aid')&&Math.abs(needA-needB)>.28&&rel.goodwill>-.25&&rr()<.22){const donor=needA<needB?rel.realmA:rel.realmB,target=donor===rel.realmA?rel.realmB:rel.realmA,acct=buildRuntime(w).treasury.get(Number(donor));if(Number(acct?.treasury||0)>8)sendHumanitarianAid(w,donor,target,year,{strength:.55+rr()*.35})}
 return rel
}
function aggregateRealms(w,year){const S=state(w);for(const rp of S.realms){const rels=S.relations.filter(x=>x.realmA===rp.realmId||x.realmB===rp.realmId),active=S.treaties.filter(t=>t.status==='active'&&(t.realmA===rp.realmId||t.realmB===rp.realmId)),hostile=active.filter(t=>['embargo','sanctions'].includes(t.type)&&t.targetRealmId===rp.realmId).length,allies=new Set(active.filter(t=>['alliance','defensive_pact'].includes(t.type)).map(t=>t.realmA===rp.realmId?t.realmB:t.realmA)),rivals=rels.filter(x=>x.rivalry>.62||x.diplomaticTension>.68).length;rp.lastYear=year;rp.activeTreaties=active.length;rp.allies=allies.size;rp.rivals=rivals;rp.tradeExposure=round(rels.length?rels.reduce((n,x)=>n+x.tradeDependence,0)/rels.length:0,4);rp.foreignPressure=round(clamp(rels.length?rels.reduce((n,x)=>n+x.diplomaticTension,0)/rels.length+hostile*.08:0,0,1),4);rp.isolation=round(clamp(1-(rels.length?rels.reduce((n,x)=>n+x.tradeAccess,0)/(rels.length*1.2):0),0,1),4);rp.treatyReliability=round(clamp(Number(rp.treatyReliability||.72)+(active.length?.002:-.001)-hostile*.001,0,1),4);rp.diplomaticReputation=round(clamp(.58+Number(rp.treatyReliability||.72)*.2-Number(rp.foreignPressure||0)*.12+Number(rp.aidGiven||0)*.001,0,1),4)}
}
function expireTreaties(w,year){for(const t of state(w).treaties)if(t.status==='active'&&Number(t.expiresYear)<=Number(year))terminateTreaty(w,t.id,year,'expired')}
function applyAllTreaties(w,year){const S=state(w);for(const t of S.treaties.filter(x=>x.status==='active').sort((a,b)=>a.id-b.id))applyTreaty(w,t,year)}
function autoPeaceConferences(w,year){for(const rel of state(w).relations){if(!rel.activeWar)continue;const a=buildRuntime(w).politics.get(rel.realmA)||{},b=buildRuntime(w).politics.get(rel.realmB)||{},exhaust=clamp((Number(a.revolutionRisk||0)+Number(b.revolutionRisk||0)+Number(a.grievance||0)+Number(b.grievance||0))/4,0,1),r=keyed(w,year,`peace:${rel.key}`);if(exhaust>.48&&r()<.12&&!treatyActive(w,'peace_treaty',rel.realmA,rel.realmB)){signTreaty(w,'peace_treaty',rel.realmA,rel.realmB,year,{strength:.55+r()*.3,duration:8});recordIncident(w,'peace_conference',year,rel.realmA,rel.realmB,{severity:round(exhaust,3)})}}}
function recomputeStats(w){const S=state(w),active=S.treaties.filter(t=>t.status==='active'),avg=(arr,key)=>arr.length?arr.reduce((n,x)=>n+Number(x[key]||0),0)/arr.length:0;S.stats.activeTreaties=active.length;S.stats.tradeAgreements=active.filter(t=>t.type==='trade_agreement').length;S.stats.alliances=active.filter(t=>t.type==='alliance'||t.type==='defensive_pact').length;S.stats.nonAggressionPacts=active.filter(t=>t.type==='non_aggression').length;S.stats.embargoes=active.filter(t=>t.type==='embargo').length;S.stats.sanctions=active.filter(t=>t.type==='sanctions').length;S.stats.aidMissions=active.filter(t=>t.type==='humanitarian_aid').length;S.stats.peaceTreaties=active.filter(t=>t.type==='peace_treaty').length;S.stats.highWarRisk=S.relations.filter(r=>r.warRisk>=.6).length;S.stats.meanTrust=round(avg(S.relations,'trust'),4);S.stats.meanTension=round(avg(S.relations,'diplomaticTension'),4);S.stats.meanTradeAccess=round(avg(S.relations,'tradeAccess'),4);return S.stats}
function simulateDiplomacyYear(w,year=absYear(w)){const S=initialize(w);year=Math.floor(Number(year)||0);if(S.lastAppliedYear===year)return S;expireTreaties(w,year);for(const rel of S.relations.slice().sort((a,b)=>a.key.localeCompare(b.key)))evaluateRelation(w,rel,year);autoPeaceConferences(w,year);applyAllTreaties(w,year);aggregateRealms(w,year);recomputeStats(w);S.currentYear=year;S.lastAppliedYear=year;S.revision++;S.annual.push({year,activeTreaties:S.stats.activeTreaties,tradeAgreements:S.stats.tradeAgreements,alliances:S.stats.alliances,embargoes:S.stats.embargoes,sanctions:S.stats.sanctions,aidMissions:S.stats.aidMissions,highWarRisk:S.stats.highWarRisk,meanTrust:S.stats.meanTrust,meanTension:S.stats.meanTension,meanTradeAccess:S.stats.meanTradeAccess,aidSpending:S.stats.aidSpending,foodTransferred:S.stats.foodTransferred});runtime.delete(w);maintenance(w);return S}
function relationView(w,a,b){const q=relationState(w,a,b),ts=activeTreaties(w,a,b);return{...q,realmAName:realmName(w,q.realmA),realmBName:realmName(w,q.realmB),treaties:ts.map(t=>({id:t.id,type:t.type,name:t.name,signedYear:t.signedYear,expiresYear:t.expiresYear,imposedBy:t.imposedBy,targetRealmId:t.targetRealmId,strength:t.strength})),conditions:relationConditions(w,q.realmA,q.realmB)}}
function realmView(w,rid){const p=realmState(w,rid),rels=state(w).relations.filter(x=>x.realmA===Number(rid)||x.realmB===Number(rid)).map(x=>relationView(w,x.realmA,x.realmB));return{...p,name:realmName(w,rid),relations:rels.sort((a,b)=>b.diplomaticTension-a.diplomaticTension),treaties:state(w).treaties.filter(t=>t.status==='active'&&(t.realmA===Number(rid)||t.realmB===Number(rid)))}}
function summary(w){const S=initialize(w);recomputeStats(w);return{version:VERSION,year:S.currentYear,revision:S.revision,relations:S.relations.length,realms:S.realms.length,...S.stats}}
function maintenance(w){const S=state(w),cut=absYear(w)-S.settings.retainDetailedYears;if(cut>0){const old=S.annual.filter(x=>x.year<cut);if(old.length){const buckets=new Map;for(const row of old){const start=Math.floor(row.year/250)*250,b=buckets.get(start)||{startYear:start,endYear:start+249,years:0,treaties:0,embargoes:0,aidMissions:0,highWarRisk:0,meanTrust:0,meanTension:0};b.years++;b.treaties+=Number(row.activeTreaties||0);b.embargoes+=Number(row.embargoes||0);b.aidMissions+=Number(row.aidMissions||0);b.highWarRisk+=Number(row.highWarRisk||0);b.meanTrust+=Number(row.meanTrust||0);b.meanTension+=Number(row.meanTension||0);buckets.set(start,b)}for(const b of buckets.values()){b.meanTrust=round(b.meanTrust/Math.max(1,b.years),4);b.meanTension=round(b.meanTension/Math.max(1,b.years),4);const ex=S.archives.find(x=>x.startYear===b.startYear);if(ex)Object.assign(ex,b);else S.archives.push(b)}S.annual=S.annual.filter(x=>x.year>=cut);S.stats.archivedYears+=old.length}}if(S.incidents.length>S.settings.maxIncidents)S.incidents.splice(0,S.incidents.length-S.settings.maxIncidents);if(S.treaties.length>S.settings.maxTreaties){const active=S.treaties.filter(x=>x.status==='active'),closed=S.treaties.filter(x=>x.status!=='active').slice(-(S.settings.maxTreaties-active.length));S.treaties=[...closed,...active]}return S}
function fingerprint(w){const S=initialize(w),s=JSON.stringify({year:S.currentYear,relations:S.relations.map(r=>[r.key,r.trust,r.goodwill,r.fear,r.rivalry,r.tradeDependence,r.borderTension,r.claimPressure,r.diplomaticTension,r.warRisk,r.allianceAffinity,r.tradeAccess,r.activeWar]),realms:S.realms.map(r=>[r.realmId,r.diplomaticReputation,r.treatyReliability,r.isolation,r.foreignPressure,r.tradeExposure,r.aidGiven,r.aidReceived,r.activeTreaties,r.allies,r.rivals]),treaties:S.treaties.map(t=>[t.id,t.type,t.pairKey,t.status,t.signedYear,t.expiresYear,t.imposedBy,t.targetRealmId,t.strength,t.lastAppliedYear]),incidents:S.incidents.slice(-180),annual:S.annual.slice(-80),stats:S.stats});return hash(s).toString(16).padStart(8,'0')}
function validate(w){const S=initialize(w),e=[],ids=activeRealmIds(w),expected=ids.length*(ids.length-1)/2;if(S.relations.length!==expected)e.push('diplomacy relation coverage');if(S.realms.length!==ids.length)e.push('diplomacy realm coverage');const seen=new Set;for(const r of S.relations){if(seen.has(r.key))e.push(`duplicate relation ${r.key}`);seen.add(r.key);for(const[k,v]of Object.entries({trust:r.trust,fear:r.fear,rivalry:r.rivalry,tradeDependence:r.tradeDependence,borderTension:r.borderTension,claimPressure:r.claimPressure,diplomaticTension:r.diplomaticTension,warRisk:r.warRisk,allianceAffinity:r.allianceAffinity}))if(!Number.isFinite(Number(v))||Number(v)<0||Number(v)>1)e.push(`${k} ${r.key}`);if(!Number.isFinite(Number(r.goodwill))||r.goodwill<-1||r.goodwill>1)e.push(`goodwill ${r.key}`);if(!Number.isFinite(Number(r.tradeAccess))||r.tradeAccess<0||r.tradeAccess>1.4)e.push(`tradeAccess ${r.key}`)}for(const t of S.treaties){if(!TREATY_TYPES[t.type])e.push(`treaty type ${t.id}`);if(!['active','expired','terminated','lapsed'].includes(t.status))e.push(`treaty status ${t.id}`)}for(const rp of S.realms)for(const k of['diplomaticReputation','treatyReliability','isolation','foreignPressure','tradeExposure'])if(!Number.isFinite(Number(rp[k]))||Number(rp[k])<0||Number(rp[k])>1)e.push(`${k} realm ${rp.realmId}`);return[...new Set(e)]}
function performance(w){const r=buildRuntime(w),p=perf.get(w)||{cacheBuilds:0,reads:0,relationHits:0,treatyEvaluations:0,tradeTransfers:0};p.reads++;perf.set(w,p);return{...p,indexedTreasuries:r.treasury.size,indexedPolitics:r.politics.size,indexedRelationPairs:r.relations.size,indexedRealmProfiles:r.realmProfiles.size,indexedMarketRealms:r.marketsByRealm.size,indexedNutritionRealms:r.nutritionByRealm.size,indexedTradePairs:r.tradeByPair.size,borderPairs:r.borderPairs.size}}
function initialize(w){if(!w)throw new Error('World required');Politics.initialize(w);Treasury.initialize(w);Resources.initialize(w);Nutrition.initialize(w);Factions?.initialize?.(w);Military?.initialize?.(w);const S=state(w),ids=activeRealmIds(w),expected=ids.length*(ids.length-1)/2;if(S.realms.length!==ids.length||S.relations.length!==expected)return sync(w);buildRuntime(w);return S}
function installBridge(){if(Workforce.__diplomacyBridge)return;Workforce.__diplomacyBridge=true;const rawYear=Workforce.simulateWorkforceYear.bind(Workforce),rawYears=Workforce.simulateYears.bind(Workforce);Workforce.simulateWorkforceYear=function(w,year=Workforce.absYear(w)){const out=rawYear(w,year);simulateDiplomacyYear(w,year);return out};Workforce.simulateYears=function(w,years,options={}){const n=Math.max(0,Math.floor(Number(years)||0));for(let i=0;i<n;i++){rawYears(w,1,options);simulateDiplomacyYear(w,absYear(w))}return w.workforce};Workforce.simulateTo=function(w,target,options={}){const t=Math.floor(Number(target)||0),now=absYear(w);if(t<now)throw new Error('Diplomacy-enabled simulation cannot run backward');return Workforce.simulateYears(w,t-now,options)}}
installBridge();const api={VERSION,SCHEMA,TREATY_TYPES,initialize,absYear,simulateDiplomacyYear,relationState,realmState,relationView,realmView,summary,fingerprint,validate,performance,signTreaty,terminateTreaty,imposeEmbargo,sendHumanitarianAid,activeTreaties,treatyActive,relationConditions,installBridge};return api;
});