(() => {
'use strict';
const F=window.WorldForgeFactions,C=window.WorldForgeCulture,S=window.WorldForgeSociety;
if(!F||!C||!S||!window.WorldRenderer)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(n,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const ui={world:null,viewYear:null,selectedId:null,filter:'all'};
const baseSim=S.simulateYears.bind(S),baseTo=S.simulateTo?.bind(S);F.setBaseSimulator(baseSim);S.simulateYears=function(world,years,options){F.simulateYears(world,years,options);return world.society};S.simulateTo=function(world,target,options){F.simulateTo(world,target,options);return world.society};S.__worldforgeV08BaseSimulate=baseSim;S.__worldforgeV08BaseTo=baseTo;
function install(){document.title='WorldForge · v0.8 Factions & Organizations';const v=$('.version-pill');if(v)v.textContent='v0.8 · FACTIONS & ORGANIZATIONS';const f=document.querySelector('footer span');if(f)f.textContent='WorldForge v0.8 · Factions & Organizations';const sim=$('#simState');if(sim)sim.textContent='LIVING WORLD + ORGANIZATION SIMULATION READY';const arch=$('.architecture-panel');if(arch){arch.querySelector('h2').textContent='v0.8 Factions & Organizations State Contract';arch.querySelector('.status-ready').textContent='FACTIONS READY';arch.querySelector('.architecture-grid').innerHTML='<div><b>Organizations</b><span>Guilds · holy orders · cults · mercenaries · scholars · political blocs · rebels</span></div><div><b>Membership</b><span>Real NPC leaders and members · recruitment · succession · decline</span></div><div><b>Power Networks</b><span>Influence · wealth · allies · rivals · contracts · faction conflicts</span></div><div><b>System Effects</b><span>Trade · treasury · faith authority · crime · war service · realm stability · uprisings</span></div>';arch.querySelector('.help').textContent='v0.9 replaces the short-horizon simulation assumptions with an endless-simulation kernel, rolling historical retention, memory compaction and long-run emergent balancing.'}
 const marker=$('.history-charts-panel');if(marker&&!$('#factionPanel'))marker.insertAdjacentHTML('beforebegin',`<section id="factionPanel" class="panel faction-panel"><div class="panel-head"><div><span class="eyebrow">ORGANIZATION ENGINE</span><h2>Institutions, Factions & Power</h2></div><span id="factionYear" class="badge">YEAR 0</span></div><div class="faction-kpis"><div><span>ACTIVE ORGS</span><b id="factionActive">—</b></div><div><span>MEMBERS</span><b id="factionMembers">—</b></div><div><span>MEAN INFLUENCE</span><b id="factionInfluence">—</b></div><div><span>CONFLICTS</span><b id="factionConflicts">—</b></div><div><span>WAR CONTRACTS</span><b id="factionContracts">—</b></div><div><span>UPRISINGS</span><b id="factionUprisings">—</b></div></div><p class="faction-note">Organizations recruit existing notable people and exert pressure on the same economy, faith, criminal and political systems that created them.</p></section><section class="panel faction-panel"><div class="panel-head"><div><span class="eyebrow">POWER NETWORK</span><h2>Organization Ledger</h2></div><select id="factionFilter"><option value="all">All organizations</option>${F.TYPES.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select></div><div class="faction-grid"><div id="factionList" class="faction-list"></div><div id="factionDetail" class="faction-detail"></div></div></section>`);
 const ef=$('#eventFilter');if(ef){[['faction_formed','Organizations founded'],['faction_dissolved','Organizations dissolved'],['faction_succession','Faction succession'],['faction_conflict','Faction conflicts'],['mercenary_contract','Mercenary contracts'],['guild_boom','Guild booms'],['uprising','Uprisings']].forEach(([value,text])=>{if(![...ef.options].some(o=>o.value===value)){const o=document.createElement('option');o.value=value;o.textContent=text;ef.appendChild(o)}})}
 $('#factionFilter')?.addEventListener('change',e=>{ui.filter=e.target.value;render()});$('#factionList')?.addEventListener('click',e=>{const b=e.target.closest('[data-org]');if(b){ui.selectedId=Number(b.dataset.org);render()}})
}
function view(){if(!ui.world)return null;return ui.viewYear==null||ui.viewYear>=ui.world.factions.currentYear?F.currentView(ui.world):F.viewAt(ui.world,ui.viewYear)}
function person(id){return F.personName(ui.world,id)}
function realm(id){return ui.world.history.realms[id]?.shortName||`Realm ${id}`}
function render(){const v=view();if(!v||!$('#factionPanel'))return;$('#factionYear').textContent=`YEAR ${v.year}`;$('#factionActive').textContent=fmt(v.metrics.active);$('#factionMembers').textContent=fmt(v.metrics.members);$('#factionInfluence').textContent=`${fmt(v.metrics.meanInfluence,1)}/100`;$('#factionConflicts').textContent=fmt(v.metrics.conflicts);$('#factionContracts').textContent=fmt(v.metrics.contracts);$('#factionUprisings').textContent=fmt(v.metrics.uprisings);let rows=v.organizations.filter(x=>x.active&&(ui.filter==='all'||x.type===ui.filter)).sort((a,b)=>b.influence-a.influence||b.wealth-a.wealth);if(ui.selectedId==null||!rows.some(x=>x.id===ui.selectedId))ui.selectedId=rows[0]?.id??null;$('#factionList').innerHTML=rows.map(o=>`<button class="faction-card ${o.id===ui.selectedId?'active':''}" data-org="${o.id}"><div><span>${esc(o.type.toUpperCase())}</span><h3>${esc(o.name)}</h3><small>${esc(ui.world.settlements[o.baseSettlementId]?.name)} · ${esc(realm(o.realmId))}</small></div><strong>${fmt(o.influence)}</strong></button>`).join('')||'<div class="empty">No active organizations match this filter.</div>';const o=v.organizations.find(x=>x.id===ui.selectedId);if(!o){$('#factionDetail').innerHTML='<div class="empty">No organization selected.</div>';return}const cult=ui.world.culture.cultures[o.cultureId],faith=ui.world.culture.religions[o.religionId],allies=o.allyIds.map(id=>ui.world.factions.organizations[id]?.name).filter(Boolean),rivals=o.rivalIds.map(id=>ui.world.factions.organizations[id]?.name).filter(Boolean);$('#factionDetail').innerHTML=`<span class="eyebrow">${esc(o.type.toUpperCase())}</span><h2>${esc(o.name)}</h2><p>${esc(o.goal)}</p><div class="faction-stat-grid"><div><span>Leader</span><b>${esc(person(o.leaderId))}</b></div><div><span>Base</span><b>${esc(ui.world.settlements[o.baseSettlementId]?.name)}</b></div><div><span>Influence</span><b>${fmt(o.influence)}/100</b></div><div><span>Wealth</span><b>${fmt(o.wealth)}</b></div><div><span>Members</span><b>${fmt(o.memberCount??o.memberIds.length)}</b></div><div><span>Founded</span><b>Year ${o.foundingYear}</b></div><div><span>Culture</span><b>${esc(cult?.name||'—')}</b></div><div><span>Faith</span><b>${esc(faith?.name||'—')}</b></div></div><h3>Network</h3><div class="network-row"><div><span>Allies</span><p>${allies.map(esc).join(' · ')||'None recorded'}</p></div><div><span>Rivals</span><p>${rivals.map(esc).join(' · ')||'None recorded'}</p></div></div><h3>Known membership</h3><div class="member-tags">${o.memberIds.slice(0,16).map(id=>`<span>${esc(person(id))}</span>`).join('')||'<span>No surviving named members</span>'}</div>`}
install();const proto=window.WorldRenderer.prototype,oldSetWorld=proto.setWorld,oldSetHistoryView=proto.setHistoryView;proto.setWorld=function(world){ui.world=world;F.initialize(world);const r=oldSetWorld.call(this,world);ui.viewYear=null;render();return r};proto.setHistoryView=function(v){const r=oldSetHistoryView.call(this,v);if(this.world){ui.world=this.world;ui.viewYear=v?.year??null;render()}return r};window.WorldForgeFactionUI={version:'0.8.0',render,state:ui};
})();