(function(root,factory){
  const api=factory(root&&root.WorldForgeEngine,root&&root.WorldForgeHistory,root&&root.WorldForgeSociety,root&&root.WorldForgeCity,root&&root.WorldForgeCulture);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeFactions=api;
})(typeof window!=='undefined'?window:globalThis,function(Core,History,Society,City,Culture){
'use strict';
const VERSION='0.8.0',SCHEMA=1,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=2)=>Number(Number(v).toFixed(d));
let baseSimulator=Culture?.simulateYears?Culture.simulateYears.bind(Culture):Society?.simulateYears?Society.simulateYears.bind(Society):null;
const TYPES=['Merchant Guild','Craft Guild','Holy Order','Cult','Mercenary Company','Political Faction','Scholar Society','Rebel League'];
const A=['Gilded','Iron','Ivory','Ashen','Verdant','Silver','Black','Crimson','Azure','Old','Radiant','Silent','Crowned','Free','Hidden','Golden','Broken','Star'];
const B={
'Merchant Guild':['Exchange','Caravan','Ledger','Consortium','Factors','Company'],
'Craft Guild':['Hammer','Masons','Artificers','Wheel','Forge','Hands'],
'Holy Order':['Vigil','Temple Guard','Pilgrims','Oath','Sanctuary','Keepers'],
'Cult':['Circle','Veil','Mysteries','Witnesses','Coven','Whisper'],
'Mercenary Company':['Lances','Company','Blades','Shields','Banner','Wolves'],
'Political Faction':['Assembly','Caucus','League','Reformers','Court','Patriots'],
'Scholar Society':['Academy','Quills','Observatory','Archivists','Collegium','Scribes'],
'Rebel League':['Liberators','Front','League','Sons','Daughters','Rising']};
const GOALS={
'Merchant Guild':['control regional trade','secure road privileges','reduce tariffs','dominate wholesale markets'],
'Craft Guild':['protect skilled labor','monopolize workshops','standardize craft law','win court patronage'],
'Holy Order':['defend holy sites','expand charitable institutions','protect pilgrims','enforce sacred obligations'],
'Cult':['spread hidden doctrine','gain elite converts','control forbidden rites','preserve secret revelation'],
'Mercenary Company':['win lucrative contracts','gain military prestige','secure a permanent charter','control strategic strongholds'],
'Political Faction':['shape succession policy','expand council power','centralize royal authority','reform taxation'],
'Scholar Society':['collect lost knowledge','found academies','map the known world','influence court education'],
'Rebel League':['break provincial rule','depose the ruling elite','win local autonomy','organize a separatist state']};
function fallbackRng(seed){let h=2166136261>>>0;for(const c of String(seed)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return function(){h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function rngFor(w,y,s=''){return(Core?.rngFromSeed||fallbackRng)(`${w.settings.seed}|FACTIONS|${y}|${s}`)}
function pick(r,a){return a[Math.floor(r()*a.length)]}
function history(w){return History.initialize(w)}
function culture(w){return Culture.initialize(w)}
function cityState(w){return City.initialize(w)}
function aliveAt(p,y){return!!p&&p.birthYear<=y&&(p.deathYear==null||p.deathYear>y)}
function personName(w,id){const p=w.society?.people?.[id];return p?Society.fullName(w.society,p):'Unknown'}
function orgName(r,type,existing){for(let i=0;i<60;i++){const n=`The ${pick(r,A)} ${pick(r,B[type])}`;if(!existing.some(x=>x.name===n))return n}return`${type} ${existing.length+1}`}
function cityById(w,id){return w.cities?.cities?.[id]||null}
function owner(w,sid){return w.history.current.settlementKingdomIds[sid]}
function roleScore(type,p,local){let s=local?40:0;s+=p.prestige*.25+p.wealth*.06;if(type==='Merchant Guild'&&p.occupation==='Merchant')s+=45;if(type==='Craft Guild'&&['Artisan','Architect'].includes(p.occupation))s+=40;if(type==='Holy Order'&&p.occupation==='Priest')s+=48;if(type==='Cult'&&['Priest','Scholar'].includes(p.occupation))s+=24;if(type==='Mercenary Company'&&p.occupation==='Soldier')s+=48;if(type==='Political Faction'&&['Magistrate','Diplomat','Steward','Ruler'].includes(p.occupation))s+=42;if(type==='Scholar Society'&&p.occupation==='Scholar')s+=50;if(type==='Rebel League'&&['Soldier','Explorer','Merchant'].includes(p.occupation))s+=22;return s}
function candidates(w,sid,type,y,exclude=new Set()){const rid=owner(w,sid),arr=w.society.people.filter(p=>aliveAt(p,y)&&!exclude.has(p.id)&&(p.settlementId===sid||p.realmId===rid));arr.sort((a,b)=>roleScore(type,b,b.settlementId===sid)-roleScore(type,a,a.settlementId===sid)||a.id-b.id);return arr}
function createOrg(w,f,data={}){const y=data.year??f.currentYear,r=data.rng||rngFor(w,y,`org-${f.organizations.length}`),sid=data.settlementId??Math.floor(r()*w.settlements.length),type=data.type||pick(r,TYPES),rid=owner(w,sid),pool=candidates(w,sid,type,y),leader=pool[0]||null,cv=culture(w),org={id:f.organizations.length,name:orgName(r,type,f.organizations),type,baseSettlementId:sid,realmId:rid,cultureId:cv.settlementCultureIds[sid]??0,religionId:cv.settlementReligionIds[sid]??0,leaderId:leader?.id??null,memberIds:[],foundingYear:y,dissolvedYear:null,active:true,influence:round(18+r()*42,1),wealth:round(30+r()*100,1),zeal:round(20+r()*60,1),aggression:round(10+r()*55,1),goal:pick(r,GOALS[type]),allyIds:[],rivalIds:[],contracts:0};if(leader)org.memberIds.push(leader.id);for(const p of pool.slice(1,1+Math.floor(4+r()*10)))if(r()<.72)org.memberIds.push(p.id);f.organizations.push(org);f.stats.formed++;pushEvent(w,{type:'faction_formed',importance:1,realmIds:[rid],settlementIds:[sid],personIds:[org.leaderId].filter(Number.isInteger),organizationIds:[org.id],title:`${org.name} is founded`,text:`A new ${type.toLowerCase()} forms in ${w.settlements[sid].name}, seeking to ${org.goal}.`});return org}
function initialize(w){history(w);Society.initialize(w);cityState(w);culture(w);if(w.factions&&w.factions.schemaVersion===SCHEMA){w.factions.engineVersion=VERSION;return w.factions}const y=w.history.currentYear,f={schemaVersion:SCHEMA,engineVersion:VERSION,startYear:y,currentYear:y,organizations:[],snapshots:[],stats:{formed:0,dissolved:0,leadershipChanges:0,conflicts:0,contracts:0,reforms:0,uprisings:0,guildBooms:0}};w.factions=f;const r=rngFor(w,y,'seed'),ranked=[...w.cities.cities].sort((a,b)=>b.population-a.population),target=clamp(Math.round(w.settlements.length*.42),10,28);for(let i=0;i<target;i++){const c=ranked[i%Math.max(1,ranked.length)],weights=c.type==='Capital'?['Political Faction','Merchant Guild','Holy Order','Scholar Society','Mercenary Company']:c.crimeRate>50?['Cult','Merchant Guild','Rebel League','Mercenary Company']:['Merchant Guild','Craft Guild','Holy Order','Scholar Society'];createOrg(w,f,{rng:r,settlementId:c.id,type:pick(r,weights),year:y})}linkRelations(w,f,y);takeSnapshot(w,f,true);return f}
function pushEvent(w,e){const h=history(w);h.events.push({id:h.events.length,year:h.currentYear,...e})}
function organizationEnvironment(w,o){const c=cityById(w,o.baseSettlementId),rs=w.history.current.realmState[o.realmId],cv=w.culture,alignedCulture=cv.realmCultureIds[o.realmId]===o.cultureId,alignedReligion=cv.realmReligionIds[o.realmId]===o.religionId;return{c,rs,alignedCulture,alignedReligion,war:w.history.current.activeWarIds.some(id=>{const x=w.history.wars[id];return x&&(x.attackerId===o.realmId||x.defenderId===o.realmId)})}}
function refreshLeader(w,f,o,y,r){if(aliveAt(w.society.people[o.leaderId],y))return;const used=new Set(f.organizations.filter(x=>x.active&&x.id!==o.id).map(x=>x.leaderId).filter(Number.isInteger)),pool=candidates(w,o.baseSettlementId,o.type,y,used),next=pool[0]||null;o.leaderId=next?.id??null;if(next&&!o.memberIds.includes(next.id))o.memberIds.unshift(next.id);f.stats.leadershipChanges++;if(next)pushEvent(w,{type:'faction_succession',importance:1,realmIds:[o.realmId],settlementIds:[o.baseSettlementId],personIds:[next.id],organizationIds:[o.id],title:`New leader of ${o.name}`,text:`${personName(w,next.id)} takes command of the organization.`})}
function refreshMembers(w,o,y,r){o.memberIds=o.memberIds.filter(id=>aliveAt(w.society.people[id],y));const desired=clamp(Math.round(4+o.influence*.16),4,22);if(o.memberIds.length<desired){const ex=new Set(o.memberIds),pool=candidates(w,o.baseSettlementId,o.type,y,ex);for(const p of pool){if(o.memberIds.length>=desired)break;if(r()<.42)o.memberIds.push(p.id)}}}
function updateOrg(w,f,o,y){if(!o.active)return;const r=rngFor(w,y,`org-${o.id}`);o.realmId=owner(w,o.baseSettlementId);refreshLeader(w,f,o,y,r);refreshMembers(w,o,y,r);const e=organizationEnvironment(w,o),pros=e.c?.prosperity??.5,trade=Math.log1p(e.c?.trade||0),crime=(e.c?.crimeRate||20)/100,st=(e.rs?.stability??50)/100;let delta=(pros-.5)*2+(r()-.5)*4.2+(o.memberIds.length-6)*.08;if(e.alignedCulture)delta+=.3;if(e.alignedReligion&&['Holy Order','Cult'].includes(o.type))delta+=.5;if(o.type==='Merchant Guild')delta+=trade*.045;if(o.type==='Craft Guild')delta+=(e.c?.businessHealth||.5)-.45;if(o.type==='Cult')delta+=crime*.8;if(o.type==='Rebel League')delta+=(1-st)*1.8;if(o.type==='Mercenary Company'&&e.war)delta+=1.5;o.influence=round(clamp(o.influence+delta,0,100),1);const income=o.type==='Merchant Guild'?trade*1.8:o.type==='Mercenary Company'&&e.war?7+o.influence*.08:o.type==='Craft Guild'?pros*4:1.5;o.wealth=round(clamp(o.wealth+income-o.memberIds.length*.09+(r()-.5)*6,0,2000),1);o.zeal=round(clamp(o.zeal+(r()-.5)*3+(o.type==='Cult'?.5:0),0,100),1);
 if(e.rs){if(o.type==='Political Faction')e.rs.stability=round(clamp(e.rs.stability+(o.influence>60?.08:-.025),0,100),1);if(o.type==='Rebel League')e.rs.stability=round(clamp(e.rs.stability-o.influence*.0025,0,100),1);if(o.type==='Merchant Guild')e.rs.treasury=round(Math.max(0,e.rs.treasury+o.influence*.004),1)}
 if(o.type==='Holy Order'&&e.alignedReligion){const rel=w.culture.religions[o.religionId];if(rel)rel.authority=round(clamp(rel.authority+o.influence*.0008,0,100),1)}
 if(o.type==='Cult'&&o.influence>55&&r()<.025){const sid=o.baseSettlementId;w.culture.fervor[sid]=round(clamp(w.culture.fervor[sid]+.04,0,1),3)}
 if(o.type==='Mercenary Company'&&e.war&&r()<.035){o.contracts++;f.stats.contracts++;o.wealth=round(o.wealth+35+r()*80,1);pushEvent(w,{type:'mercenary_contract',importance:1,realmIds:[o.realmId],settlementIds:[o.baseSettlementId],personIds:[o.leaderId].filter(Number.isInteger),organizationIds:[o.id],title:`${o.name} takes a war contract`,text:`The company enters military service during an active conflict.`})}
 if(o.type==='Merchant Guild'&&o.influence>68&&r()<.018){f.stats.guildBooms++;if(e.c)e.c.prosperity=round(clamp(e.c.prosperity+.01,0,1.2),4);pushEvent(w,{type:'guild_boom',importance:1,realmIds:[o.realmId],settlementIds:[o.baseSettlementId],organizationIds:[o.id],title:`Commercial ascendancy of ${o.name}`,text:'The guild secures favorable contracts and expands regional commerce.'})}
 if(o.type==='Rebel League'&&o.influence>72&&e.rs?.stability<35&&r()<.025){f.stats.uprisings++;e.rs.stability=round(clamp(e.rs.stability-(5+r()*9),0,100),1);pushEvent(w,{type:'uprising',importance:2,realmIds:[o.realmId],settlementIds:[o.baseSettlementId],personIds:[o.leaderId].filter(Number.isInteger),organizationIds:[o.id],title:`Uprising backed by ${o.name}`,text:`The organization mobilizes supporters around ${w.settlements[o.baseSettlementId].name}, sharply weakening local authority.`})}
 if(o.influence<3&&o.memberIds.length<3&&r()<.12)dissolve(w,f,o,y,'The organization loses its remaining influence and membership.')}
function dissolve(w,f,o,y,reason){if(!o.active)return;o.active=false;o.dissolvedYear=y;f.stats.dissolved++;pushEvent(w,{type:'faction_dissolved',importance:1,realmIds:[o.realmId],settlementIds:[o.baseSettlementId],organizationIds:[o.id],title:`${o.name} dissolves`,text:reason})}
function linkRelations(w,f,y){const active=f.organizations.filter(x=>x.active);for(const o of active){const same=active.filter(x=>x.id!==o.id&&(x.realmId===o.realmId||x.baseSettlementId===o.baseSettlementId));o.allyIds=o.allyIds.filter(id=>f.organizations[id]?.active);o.rivalIds=o.rivalIds.filter(id=>f.organizations[id]?.active);for(const x of same){if(o.allyIds.includes(x.id)||o.rivalIds.includes(x.id))continue;const r=rngFor(w,y,`relation-${Math.min(o.id,x.id)}-${Math.max(o.id,x.id)}`),faith=o.religionId===x.religionId,cultureSame=o.cultureId===x.cultureId,competitive=(o.type===x.type)||(['Merchant Guild','Craft Guild'].includes(o.type)&&['Merchant Guild','Craft Guild'].includes(x.type));if((faith&&cultureSame&&!competitive&&r()<.10)||r()<.012){o.allyIds.push(x.id);if(!x.allyIds.includes(o.id))x.allyIds.push(o.id)}else if((competitive&&r()<.14)||(!faith&&['Cult','Holy Order'].includes(o.type)&&r()<.14)){o.rivalIds.push(x.id);if(!x.rivalIds.includes(o.id))x.rivalIds.push(o.id)}}}}
function conflicts(w,f,y){const r=rngFor(w,y,'conflicts');for(const o of f.organizations.filter(x=>x.active)){for(const rid of o.rivalIds){if(rid<=o.id)continue;const x=f.organizations[rid];if(!x?.active||x.realmId!==o.realmId)continue;if(r()<.006+(o.aggression+x.aggression)/22000){f.stats.conflicts++;o.influence=round(clamp(o.influence+(r()-.5)*8,0,100),1);x.influence=round(clamp(x.influence+(r()-.5)*8,0,100),1);const c=cityById(w,o.baseSettlementId);if(c)c.crimeRate=round(clamp(c.crimeRate+1+r()*3,0,100),1);pushEvent(w,{type:'faction_conflict',importance:1,realmIds:[o.realmId],settlementIds:[o.baseSettlementId],organizationIds:[o.id,x.id],personIds:[o.leaderId,x.leaderId].filter(Number.isInteger),title:`Faction struggle: ${o.name} vs ${x.name}`,text:'Competing organizations clash over influence, patronage and local control.'})}}}}
function maybeForm(w,f,y){const active=f.organizations.filter(x=>x.active);if(active.length>=48)return;const r=rngFor(w,y,'formation');if(r()>.025)return;const ranked=[...w.cities.cities].sort((a,b)=>(b.population+b.crimeRate*150)-(a.population+a.crimeRate*150)),c=pick(r,ranked.slice(0,Math.min(12,ranked.length))),rs=w.history.current.realmState[owner(w,c.id)],types=c.crimeRate>55?['Cult','Rebel League','Mercenary Company','Merchant Guild']:rs?.stability<38?['Political Faction','Rebel League','Holy Order']:['Merchant Guild','Craft Guild','Scholar Society','Holy Order','Political Faction'];createOrg(w,f,{rng:r,settlementId:c.id,type:pick(r,types),year:y});linkRelations(w,f,y)}
function simulateFactionYear(w,f,y){f.currentYear=y;for(const o of f.organizations)updateOrg(w,f,o,y);conflicts(w,f,y);maybeForm(w,f,y);if(y%10===0)linkRelations(w,f,y);takeSnapshot(w,f,false)}
function rows(f){return f.organizations.map(o=>[o.id,o.active?1:0,o.realmId,o.baseSettlementId,o.leaderId??-1,round(o.influence,1),round(o.wealth,1),o.memberIds.length,o.dissolvedYear??-1])}
function metrics(f){const a=f.organizations.filter(x=>x.active);return{active:a.length,total:f.organizations.length,meanInfluence:round(a.reduce((n,x)=>n+x.influence,0)/Math.max(1,a.length),1),members:a.reduce((n,x)=>n+x.memberIds.length,0),conflicts:f.stats.conflicts,contracts:f.stats.contracts,uprisings:f.stats.uprisings}}
function takeSnapshot(w,f,force=false){const interval=Math.max(5,w.history?.snapshotInterval||5);if(!force&&f.currentYear%interval!==0)return null;const s={year:f.currentYear,organizations:rows(f),stats:{...f.stats},metrics:metrics(f)};const last=f.snapshots.at(-1);if(last?.year===s.year)f.snapshots[f.snapshots.length-1]=s;else f.snapshots.push(s);return s}
function simulateYears(w,years,options={}){const f=initialize(w),n=Math.max(0,Math.round(Number(years)||0));if(!baseSimulator)throw new Error('Base simulation unavailable');for(let i=0;i<n;i++){baseSimulator(w,1,options);simulateFactionYear(w,f,w.history.currentYear)}takeSnapshot(w,f,true);return f}
function simulateTo(w,target,options={}){initialize(w);const t=Math.max(w.history.currentYear,Math.round(Number(target)||0));return simulateYears(w,t-w.history.currentYear,options)}
function setBaseSimulator(fn){if(typeof fn==='function')baseSimulator=fn;return api}
function snapshotAt(w,year){const f=initialize(w),target=Math.min(f.currentYear,Math.max(f.startYear,Math.round(Number(year)||0)));let best=f.snapshots[0];for(const s of f.snapshots)if(s.year<=target&&s.year>=best.year)best=s;return best}
function viewFrom(w,f,s){const orgs=s.organizations.map(row=>{const o=f.organizations[row[0]];return{...o,active:!!row[1],realmId:row[2],baseSettlementId:row[3],leaderId:row[4]<0?null:row[4],influence:row[5],wealth:row[6],memberCount:row[7],dissolvedYear:row[8]<0?null:row[8]}});return{year:s.year,isPresent:s.year===f.currentYear,organizations:orgs,stats:{...s.stats},metrics:{...s.metrics}}}
function currentView(w){const f=initialize(w),s={year:f.currentYear,organizations:rows(f),stats:{...f.stats},metrics:metrics(f)};return viewFrom(w,f,s)}
function viewAt(w,year){const f=initialize(w);if(year>=f.currentYear)return currentView(w);return viewFrom(w,f,snapshotAt(w,year))}
function fingerprint(w){const f=initialize(w);let h=2166136261>>>0,s=`${f.currentYear}|${f.stats.formed}|${f.stats.conflicts}|${f.organizations.map(o=>`${o.id}:${o.active?1:0}:${o.realmId}:${o.leaderId}:${Math.round(o.influence)}:${o.memberIds.length}`).join('|')}`;for(const ch of s){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,'0')}
function validate(w){const e=[],f=w?.factions;if(!f||f.schemaVersion!==SCHEMA)return['faction schema'];if(f.currentYear!==w.history?.currentYear)e.push('faction/history year mismatch');for(const o of f.organizations){if(!w.settlements[o.baseSettlementId])e.push('organization base');if(o.leaderId!=null&&!w.society.people[o.leaderId])e.push('organization leader');if(!w.culture.cultures[o.cultureId])e.push('organization culture');if(!w.culture.religions[o.religionId])e.push('organization religion');for(const id of o.memberIds)if(!w.society.people[id]){e.push('organization member');break}}if(!f.snapshots.length||f.snapshots.at(-1).year!==f.currentYear)e.push('faction snapshot');return[...new Set(e)]}
const api={VERSION,SCHEMA,TYPES,initialize,simulateYears,simulateTo,setBaseSimulator,currentView,viewAt,snapshotAt,fingerprint,validate,personName};return api;
});