(function(root,factory){
  const api=factory(root&&root.WorldForgeEngine,root&&root.WorldForgeHistory);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeSociety=api;
})(typeof window!=='undefined'?window:globalThis,function(Core,History){
'use strict';

const VERSION='0.3.0';
const SOCIETY_SCHEMA=1;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const round=(v,d=2)=>Number(Number(v).toFixed(d));
const pairKey=(a,b)=>a<b?`${a}:${b}`:`${b}:${a}`;
const FIRST_M=['Aldren','Beren','Cedric','Darian','Edric','Faelan','Garrick','Hadrian','Ivor','Kael','Leoric','Marek','Nolan','Orrin','Perrin','Roderic','Stellan','Tavian','Ulric','Varen','Wulfric'];
const FIRST_F=['Aelia','Brina','Celia','Daria','Elira','Fiora','Gwenna','Helena','Isolde','Kaia','Liora','Mara','Nerys','Orla','Petra','Rhea','Selene','Talia','Una','Vera','Ysra'];
const FIRST_N=['Aren','Bryn','Ceri','Dale','Ember','Fenn','Gale','Hale','Iria','Jory','Kest','Lyn','Meri','Neri','Oren','Pax','Ren','Sage','Tarin','Vale'];
const SURN_A=['Ash','Black','Bright','Cinder','Dawn','Ember','Frost','Gold','Grey','High','Iron','Moon','Night','Oak','Raven','Red','River','Silver','Star','Stone','Storm','Thorn','Vale','West','White','Wolf'];
const SURN_B=['brook','crest','fall','ford','gard','hall','hart','keep','mere','mont','moor','reach','ridge','run','shield','spire','stead','vale','ward','watch','wick','wood'];
const OCCUPATIONS=['Merchant','Scholar','Soldier','Priest','Artisan','Steward','Healer','Explorer','Magistrate','Architect','Farmer','Diplomat'];
const TRAITS=['ambitious','brave','cautious','charismatic','compassionate','cunning','diligent','generous','gregarious','honorable','patient','pragmatic','proud','scholarly','stern','temperate'];
const AMBITIONS=['build a lasting legacy','expand the family fortune','serve the realm','master a craft','gain political influence','found a great institution','win military renown','protect the family','travel beyond the known roads','be remembered by history'];
const LAWS=['Absolute Primogeniture','Male-preference Primogeniture','House Seniority','Council Elective'];

function fallbackRng(seed){let h=2166136261>>>0;for(const c of String(seed)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return function(){h+=0x6D2B79F5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function rngFor(world,year,salt=''){return (Core?.rngFromSeed||fallbackRng)(`${world.settings.seed}|SOCIETY|${year}|${salt}`)}
function pick(rng,a){return a[Math.floor(rng()*a.length)]}
function shuffled(rng,a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function history(world){if(!History)throw new Error('WorldForgeHistory is required');return History.initialize(world)}
function activeRealmIds(world){return world.history.current.realmState.filter(Boolean).filter(r=>r.active).map(r=>r.id)}
function ownerAt(world,sid){return world.history.current.settlementKingdomIds[sid]}
function realmName(world,id){return world.history.realms[id]?.shortName||`Realm ${id}`}
function ageAt(p,year){return year-p.birthYear}
function aliveAt(p,year){return p.birthYear<=year&&(p.deathYear==null||p.deathYear>year)}
function livingPeople(s,year=s.currentYear){return s.people.filter(p=>aliveAt(p,year))}
function person(s,id){return Number.isInteger(id)?s.people[id]||null:null}
function house(s,id){return Number.isInteger(id)&&id>=0?s.houses[id]||null:null}
function title(s,id){return Number.isInteger(id)&&id>=0?s.titles[id]||null:null}
function fullName(s,p){if(!p)return'Unknown';const h=house(s,p.houseId);return `${p.firstName} ${h?h.shortName:p.surname}`}
function firstName(rng,gender){return pick(rng,gender==='M'?FIRST_M:gender==='F'?FIRST_F:FIRST_N)}
function surname(rng){return pick(rng,SURN_A)+pick(rng,SURN_B)}
function uniqueSurname(s,rng){const used=new Set(s.houses.map(h=>h.shortName));for(let i=0;i<80;i++){const n=surname(rng);if(!used.has(n))return n}return`Lineage ${s.houses.length+1}`}
function realmCapital(world,id){const meta=world.history.realms[id];return meta?.capitalId??world.history.current.settlementKingdomIds.findIndex(x=>x===id)}
function addUnique(a,v){if(v==null||a.includes(v))return;a.push(v)}
function removeValue(a,v){const i=a.indexOf(v);if(i>=0)a.splice(i,1)}
function pushHistoryEvent(world,e){const h=history(world);h.events.push({id:h.events.length,year:h.currentYear,...e})}
function setRelation(world,a,b,value){if(a===b)return;world.history.current.relations[pairKey(a,b)]=clamp(round(value,1),-100,100)}
function getRelation(world,a,b){return a===b?100:Number(world.history.current.relations[pairKey(a,b)]??0)}

function createHouse(world,s,data={}){
  const rng=data.rng||rngFor(world,s.currentYear,`house-${s.houses.length}`),shortName=data.shortName||uniqueSurname(s,rng);
  const h={id:s.houses.length,name:`House ${shortName}`,shortName,realmId:data.realmId??null,settlementId:data.settlementId??null,foundingYear:data.foundingYear??s.currentYear,founderId:null,headId:null,prestige:round(data.prestige??(30+rng()*35),1),status:data.status||'Noble',rulingTitleIds:[],memberIds:[]};
  s.houses.push(h);s.stats.housesFormed++;return h
}
function createPerson(world,s,data={}){
  const rng=data.rng||rngFor(world,s.currentYear,`person-${s.people.length}`),gender=data.gender||pick(rng,['M','F','N']),houseObj=house(s,data.houseId),p={
    id:s.people.length,firstName:data.firstName||firstName(rng,gender),surname:data.surname||houseObj?.shortName||surname(rng),gender,
    birthYear:data.birthYear??(s.currentYear-(18+Math.floor(rng()*38))),deathYear:data.deathYear??null,realmId:data.realmId??0,settlementId:data.settlementId??0,houseId:data.houseId??null,
    occupation:data.occupation||pick(rng,OCCUPATIONS),status:data.status||'Notable',wealth:round(data.wealth??(15+rng()*85),1),prestige:round(data.prestige??(18+rng()*55),1),
    ambition:data.ambition||pick(rng,AMBITIONS),traits:data.traits||shuffled(rng,TRAITS).slice(0,2),spouseId:data.spouseId??null,parentIds:[...(data.parentIds||[])],childrenIds:[],friendIds:[],rivalIds:[],titleIds:[],
    createdYear:s.currentYear
  };
  s.people.push(p);if(houseObj)addUnique(houseObj.memberIds,p.id);for(const pid of p.parentIds){const par=person(s,pid);if(par)addUnique(par.childrenIds,p.id)}s.stats.notablesCreated++;return p
}
function marry(world,s,a,b,year,reason='marriage'){
  if(!a||!b||a.id===b.id||a.spouseId!=null||b.spouseId!=null)return false;a.spouseId=b.id;b.spouseId=a.id;addUnique(a.friendIds,b.id);addUnique(b.friendIds,a.id);s.stats.marriages++;
  const dynastic=house(s,a.houseId)?.status==='Ruling'||house(s,b.houseId)?.status==='Ruling'||a.realmId!==b.realmId;
  if(a.realmId!==b.realmId){const r=getRelation(world,a.realmId,b.realmId);setRelation(world,a.realmId,b.realmId,r+5)}
  if(dynastic)pushHistoryEvent(world,{type:'marriage',importance:a.realmId!==b.realmId?2:1,realmIds:[...new Set([a.realmId,b.realmId])],personIds:[a.id,b.id],houseIds:[a.houseId,b.houseId].filter(Number.isInteger),title:'Dynastic marriage',text:`${fullName(s,a)} and ${fullName(s,b)} marry${a.realmId!==b.realmId?`, linking ${realmName(world,a.realmId)} and ${realmName(world,b.realmId)}`:''}.`});
  return true
}
function titleStyle(world,realmId){const n=(world.history.realms[realmId]?.name||'').toLowerCase();if(n.includes('principality'))return{m:'Prince',f:'Princess',n:'Princeps',seat:'Principality'};if(n.includes('march'))return{m:'Margrave',f:'Margravine',n:'Margrave',seat:'March'};if(n.includes('league')||n.includes('republic')||n.includes('free state'))return{m:'First Consul',f:'First Consul',n:'First Consul',seat:'High Office'};if(n.includes('dominion')||n.includes('highland'))return{m:'High Lord',f:'High Lady',n:'High Ruler',seat:'High Seat'};return{m:'King',f:'Queen',n:'Sovereign',seat:'Crown'}}
function rulerLabel(style,p){return p.gender==='M'?style.m:p.gender==='F'?style.f:style.n}
function createRealmDynasty(world,s,realmId,year,reason='founding'){
  const rng=rngFor(world,year,`dynasty-${realmId}-${s.houses.length}`),sid=realmCapital(world,realmId),short=uniqueSurname(s,rng),h=createHouse(world,s,{rng,shortName:short,realmId,settlementId:sid,foundingYear:year,prestige:68+rng()*22,status:'Ruling'});
  const rulerAge=30+Math.floor(rng()*20),ruler=createPerson(world,s,{rng,houseId:h.id,realmId,settlementId:sid,birthYear:year-rulerAge,occupation:'Ruler',status:'Ruler',prestige:72+rng()*20,wealth:90+rng()*110});h.founderId=ruler.id;h.headId=ruler.id;
  const spouse=createPerson(world,s,{rng,houseId:null,realmId,settlementId:sid,birthYear:year-(25+Math.floor(rng()*19)),occupation:'Courtier',status:'Consort',prestige:45+rng()*25,wealth:50+rng()*70});marry(world,s,ruler,spouse,year,'founding union');
  const childCount=2+Math.floor(rng()*3);for(let i=0;i<childCount;i++){const a=Math.max(0,Math.floor(rng()*Math.min(26,rulerAge-16))),c=createPerson(world,s,{rng,houseId:h.id,realmId,settlementId:sid,birthYear:year-a,occupation:a<16?'Ward':pick(rng,['Courtier','Soldier','Scholar','Diplomat']),status:'Dynast',prestige:32+rng()*35,wealth:20+rng()*50,parentIds:[ruler.id,spouse.id]});if(i===0)c.prestige+=8}
  const style=titleStyle(world,realmId),t={id:s.titles.length,realmId,name:`${style.seat} of ${realmName(world,realmId)}`,style,law:pick(rng,LAWS),active:true,holderId:ruler.id,heirId:null,houseId:h.id,createdYear:year,dissolvedYear:null,reigns:[{holderId:ruler.id,startYear:year,endYear:null}],claims:[]};s.titles.push(t);addUnique(ruler.titleIds,t.id);addUnique(h.rulingTitleIds,t.id);s.stats.successions+=reason==='succession'?1:0;refreshTitleClaims(world,s,t,year);
  if(reason==='realm_formed')pushHistoryEvent(world,{type:'dynasty_founded',importance:2,realmIds:[realmId],personIds:[ruler.id],houseIds:[h.id],titleId:t.id,title:`${h.name} takes the ${style.seat.toLowerCase()}`,text:`${rulerLabel(style,ruler)} ${fullName(s,ruler)} becomes the first recorded ruler of ${realmName(world,realmId)}.`});return t
}
function createMinorHouses(world,s,count,year){const rng=rngFor(world,year,'minor-houses'),realms=activeRealmIds(world);for(let i=0;i<count;i++){const rid=realms[i%realms.length],ids=world.settlements.map((x,j)=>ownerAt(world,j)===rid?j:null).filter(Number.isInteger),sid=ids[Math.floor(rng()*Math.max(1,ids.length))]??realmCapital(world,rid),h=createHouse(world,s,{rng,realmId:rid,settlementId:sid,foundingYear:year,prestige:36+rng()*34,status:'Noble'}),founder=createPerson(world,s,{rng,houseId:h.id,realmId:rid,settlementId:sid,birthYear:year-(24+Math.floor(rng()*34)),occupation:pick(rng,['Merchant','Magistrate','Soldier','Steward','Scholar']),status:'House Head',prestige:42+rng()*35,wealth:45+rng()*95});h.founderId=founder.id;h.headId=founder.id}}
function weightedSettlement(world,rng){const pop=world.history.current.settlementPopulation,total=pop.reduce((a,b)=>a+Math.sqrt(Math.max(1,b)),0);let r=rng()*total;for(let i=0;i<pop.length;i++){r-=Math.sqrt(Math.max(1,pop[i]));if(r<=0)return i}return pop.length-1}
function createCommonNotables(world,s,target,year){const rng=rngFor(world,year,'notables');while(livingPeople(s,year).length<target){const sid=weightedSettlement(world,rng),rid=ownerAt(world,sid),p=createPerson(world,s,{rng,realmId:rid,settlementId:sid,birthYear:year-(16+Math.floor(rng()*49)),occupation:pick(rng,OCCUPATIONS),status:'Notable',prestige:15+rng()*58,wealth:10+rng()*100});if(rng()<.18&&ageAt(p,year)>=20){const h=createHouse(world,s,{rng,realmId:rid,settlementId:sid,foundingYear:year,prestige:25+rng()*30,status:'Landed'});p.houseId=h.id;p.surname=h.shortName;addUnique(h.memberIds,p.id);h.founderId=p.id;h.headId=p.id}}}
function seedRelationships(world,s,year){const rng=rngFor(world,year,'relationships'),alive=livingPeople(s,year);for(const p of alive){const pool=alive.filter(q=>q.id!==p.id&&q.realmId===p.realmId&&Math.abs(ageAt(q,year)-ageAt(p,year))<24);if(pool.length&&rng()<.72){const q=pick(rng,pool);addUnique(p.friendIds,q.id);addUnique(q.friendIds,p.id)}if(pool.length&&rng()<.35){const q=pick(rng,pool);if(!p.friendIds.includes(q.id)){addUnique(p.rivalIds,q.id);addUnique(q.rivalIds,p.id)}}}}
function initialize(world,options={}){
  const h=history(world);if(world.society&&world.society.schemaVersion===SOCIETY_SCHEMA)return world.society;const year=h.currentYear;
  const s={schemaVersion:SOCIETY_SCHEMA,engineVersion:VERSION,startYear:year,currentYear:year,targetLiving:clamp(Math.round(Number(options.targetLiving)||Math.max(80,world.settlements.length*2.5)),50,220),people:[],houses:[],titles:[],snapshots:[],stats:{notablesCreated:0,housesFormed:0,births:0,deaths:0,marriages:0,successions:0,successionCrises:0,dynasticMarriages:0}};world.society=s;
  for(const rid of activeRealmIds(world))createRealmDynasty(world,s,rid,year,'founding');createMinorHouses(world,s,Math.max(3,activeRealmIds(world).length),year);createCommonNotables(world,s,s.targetLiving,year);seedRelationships(world,s,year);recompute(world,s,year);takeSnapshot(world,s,true);return s
}
function isCloseKin(s,a,b){if(a.parentIds.includes(b.id)||b.parentIds.includes(a.id))return true;if(a.parentIds.some(x=>b.parentIds.includes(x)))return true;return false}
function eligibleClaimants(world,s,t,year,deceasedId=null){return livingPeople(s,year).filter(p=>p.realmId===t.realmId&&ageAt(p,year)>=14&&p.id!==deceasedId).map(p=>({personId:p.id,score:claimScore(s,p,t,year,deceasedId)})).filter(x=>x.score>12).sort((a,b)=>b.score-a.score||a.personId-b.personId)}
function claimScore(s,p,t,year,deceasedId){const d=person(s,deceasedId??t.holderId),h=house(s,p.houseId);let score=p.prestige*.45+clamp(ageAt(p,year),14,70)*.18+(h?.prestige||0)*.18;if(d){if(p.parentIds.includes(d.id))score+=78;else if(d.parentIds.some(x=>p.parentIds.includes(x)))score+=54;if(p.houseId!=null&&p.houseId===d.houseId)score+=36}if(p.houseId===t.houseId)score+=20;if(t.law==='Male-preference Primogeniture'&&p.gender==='M')score+=12;if(t.law==='House Seniority')score+=ageAt(p,year)*.55;if(t.law==='Council Elective')score+=p.prestige*.42;return round(score,1)}
function refreshTitleClaims(world,s,t,year,deceasedId=null){t.claims=eligibleClaimants(world,s,t,year,deceasedId).slice(0,6);t.heirId=t.claims[0]?.personId??null;for(const p of s.people)if(p.occupation==='Heir'&&!s.titles.some(x=>x.active&&x.heirId===p.id))p.occupation=ageAt(p,year)<16?'Ward':p.status==='Ruler'?'Ruler':'Courtier';const heir=person(s,t.heirId);if(heir&&heir.occupation!=='Ruler')heir.occupation='Heir';return t.claims}
function resolveSuccession(world,s,t,year,deceasedId){const candidates=eligibleClaimants(world,s,t,year,deceasedId),oldHouse=t.houseId;let winner=candidates[0]?person(s,candidates[0].personId):null;if(!winner){const pool=livingPeople(s,year).filter(p=>p.realmId===t.realmId&&ageAt(p,year)>=18).sort((a,b)=>b.prestige-a.prestige);winner=pool[0]||createPerson(world,s,{realmId:t.realmId,settlementId:realmCapital(world,t.realmId),birthYear:year-28,occupation:'Ruler',status:'Ruler',prestige:70,wealth:80});if(winner.houseId==null){const h=createHouse(world,s,{realmId:t.realmId,settlementId:winner.settlementId,foundingYear:year,prestige:62,status:'Ruling'});winner.houseId=h.id;winner.surname=h.shortName;h.memberIds.push(winner.id);h.founderId=winner.id;h.headId=winner.id}}
  const oldReign=t.reigns[t.reigns.length-1];if(oldReign&&oldReign.endYear==null)oldReign.endYear=year;t.holderId=winner.id;t.houseId=winner.houseId;t.reigns.push({holderId:winner.id,startYear:year,endYear:null});addUnique(winner.titleIds,t.id);winner.status='Ruler';winner.occupation='Ruler';winner.prestige=round(clamp(winner.prestige+10,0,160),1);const nh=house(s,winner.houseId);if(nh){nh.status='Ruling';nh.realmId=t.realmId;addUnique(nh.rulingTitleIds,t.id);nh.prestige=round(clamp(nh.prestige+8,0,180),1)}const oh=house(s,oldHouse);if(oh&&oldHouse!==winner.houseId&&oh.rulingTitleIds.every(id=>id===t.id||!title(s,id)?.active))oh.status='Noble';s.stats.successions++;
  const style=t.style;pushHistoryEvent(world,{type:'succession',importance:3,realmIds:[t.realmId],personIds:[deceasedId,winner.id].filter(Number.isInteger),houseIds:[oldHouse,winner.houseId].filter(Number.isInteger),titleId:t.id,title:`${fullName(s,winner)} succeeds to ${t.name}`,text:`${rulerLabel(style,winner)} ${fullName(s,winner)} takes the ${style.seat.toLowerCase()} under ${t.law}.`});
  if(candidates.length>1&&candidates[1].score>58&&candidates[0].score-candidates[1].score<16){const rival=person(s,candidates[1].personId);addUnique(winner.rivalIds,rival.id);addUnique(rival.rivalIds,winner.id);const rs=world.history.current.realmState[t.realmId];if(rs)rs.stability=round(clamp(rs.stability-(8+Math.min(14,(16-(candidates[0].score-candidates[1].score))*.6)),0,100),1);s.stats.successionCrises++;pushHistoryEvent(world,{type:'succession_crisis',importance:3,realmIds:[t.realmId],personIds:[winner.id,rival.id],houseIds:[winner.houseId,rival.houseId].filter(Number.isInteger),titleId:t.id,title:`Succession crisis in ${realmName(world,t.realmId)}`,text:`${fullName(s,rival)} contests ${fullName(s,winner)}'s succession. Competing claims destabilize the realm.`})}
  refreshTitleClaims(world,s,t,year);return winner
}
function inheritWealth(s,p){const heirs=p.childrenIds.map(id=>person(s,id)).filter(Boolean).filter(x=>aliveAt(x,s.currentYear));if(heirs.length){const each=p.wealth*.72/heirs.length;for(const q of heirs)q.wealth=round(q.wealth+each,1)}else{const sp=person(s,p.spouseId);if(sp&&aliveAt(sp,s.currentYear))sp.wealth=round(sp.wealth+p.wealth*.65,1)}}
function mortality(age){if(age<45)return.002;if(age<55)return.006;if(age<65)return.018;if(age<75)return.05;if(age<85)return.12;return.28}
function processDeaths(world,s,year,rng){for(const p of [...livingPeople(s,year-1)]){const age=ageAt(p,year);if(age<1)continue;const atWar=world.history.current.activeWarIds.some(wid=>{const w=world.history.wars[wid];return w&&(w.attackerId===p.realmId||w.defenderId===p.realmId)}),risk=mortality(age)+(atWar&&['Soldier','Ruler','Heir'].includes(p.occupation)?.004:0);if(rng()>risk)continue;p.deathYear=year;p.status='Dead';s.stats.deaths++;inheritWealth(s,p);const high=p.titleIds.length||p.occupation==='Heir'||p.prestige>88||house(s,p.houseId)?.headId===p.id;if(high)pushHistoryEvent(world,{type:'death',importance:p.titleIds.length?2:1,realmIds:[p.realmId],personIds:[p.id],houseIds:[p.houseId].filter(Number.isInteger),title:`Death of ${fullName(s,p)}`,text:`${fullName(s,p)} dies at age ${age}${p.titleIds.length?' while holding high office':''}.`});for(const tid of [...p.titleIds]){const t=title(s,tid);if(t?.active&&t.holderId===p.id)resolveSuccession(world,s,t,year,p.id)}}}
function processMarriages(world,s,year,rng){const candidates=shuffled(rng,livingPeople(s,year).filter(p=>p.spouseId==null&&ageAt(p,year)>=18&&ageAt(p,year)<=48));const used=new Set();for(const a of candidates){if(used.has(a.id)||rng()>.045)continue;const pool=candidates.filter(b=>!used.has(b.id)&&b.id!==a.id&&b.spouseId==null&&!isCloseKin(s,a,b)&&ageAt(b,year)>=18&&ageAt(b,year)<=50&&(b.realmId===a.realmId||getRelation(world,a.realmId,b.realmId)>22));if(!pool.length)continue;pool.sort((x,y)=>{const ax=(x.realmId===a.realmId?0:12)+Math.abs(ageAt(a,year)-ageAt(x,year))-(house(s,x.houseId)?.prestige||0)*.05,ay=(y.realmId===a.realmId?0:12)+Math.abs(ageAt(a,year)-ageAt(y,year))-(house(s,y.houseId)?.prestige||0)*.05;return ax-ay});const b=pool[Math.floor(rng()*Math.min(4,pool.length))];if(marry(world,s,a,b,year)){used.add(a.id);used.add(b.id);if(a.realmId!==b.realmId)s.stats.dynasticMarriages++}}}
function processBirths(world,s,year,rng){const alive=livingPeople(s,year);if(alive.length>s.targetLiving*1.45)return;const pairs=alive.filter(p=>p.spouseId!=null&&p.id<p.spouseId).map(p=>[p,person(s,p.spouseId)]).filter(x=>x[1]&&aliveAt(x[1],year));for(const [a,b] of pairs){const aa=ageAt(a,year),ab=ageAt(b,year);if(aa<18||ab<18||aa>55||ab>55)continue;const trackedKids=a.childrenIds.filter(id=>{const q=person(s,id);return q&&q.parentIds.includes(b.id)}).length,high=house(s,a.houseId)?.status==='Ruling'||house(s,b.houseId)?.status==='Ruling',chance=(high?.15:.055)*Math.max(.18,1-trackedKids*.18);if(rng()>chance)continue;if(!high&&livingPeople(s,year).length>=s.targetLiving*1.08&&rng()<.78)continue;const parentHouse=house(s,a.houseId)?a.houseId:house(s,b.houseId)?b.houseId:null,realmId=a.realmId,settlementId=a.settlementId,child=createPerson(world,s,{rng,houseId:parentHouse,realmId,settlementId,birthYear:year,occupation:'Ward',status:'Child',prestige:high?25+rng()*28:10+rng()*20,wealth:0,parentIds:[a.id,b.id]});s.stats.births++;if(high)pushHistoryEvent(world,{type:'birth',importance:1,realmIds:[realmId],personIds:[child.id,a.id,b.id],houseIds:[parentHouse].filter(Number.isInteger),title:`Birth in ${house(s,parentHouse)?.name||'a notable family'}`,text:`${fullName(s,child)} is born to ${fullName(s,a)} and ${fullName(s,b)}.`})}}
function processCareers(world,s,year,rng){for(const p of livingPeople(s,year)){const age=ageAt(p,year);if(age===16&&p.occupation==='Ward'){p.occupation=pick(rng,OCCUPATIONS);p.status=house(s,p.houseId)?'Dynast':'Notable'}if(age>20&&!['Ruler','Heir','Ward'].includes(p.occupation)&&rng()<.012){const choices=p.traits.includes('scholarly')?['Scholar','Magistrate','Diplomat']:p.traits.includes('brave')?['Soldier','Explorer','Magistrate']:OCCUPATIONS;p.occupation=pick(rng,choices)}p.wealth=round(clamp(p.wealth+(p.occupation==='Merchant'?1.4:p.occupation==='Ruler'?2.2:.35)+(rng()-.5)*1.8,0,500),1);p.prestige=round(clamp(p.prestige+(p.occupation==='Ruler'?.8:p.occupation==='Heir'?.35:.08)+(rng()-.5)*.7,0,180),1)}}
function processRelationships(world,s,year,rng){const alive=livingPeople(s,year);for(const p of alive){if(rng()<.016){const pool=alive.filter(q=>q.id!==p.id&&q.realmId===p.realmId&&!isCloseKin(s,p,q));if(pool.length){const q=pick(rng,pool);if(rng()<.68){addUnique(p.friendIds,q.id);addUnique(q.friendIds,p.id);removeValue(p.rivalIds,q.id);removeValue(q.rivalIds,p.id)}else{addUnique(p.rivalIds,q.id);addUnique(q.rivalIds,p.id)}}}}}
function ensureActiveRealmTitles(world,s,year){const active=new Set(activeRealmIds(world));for(const t of s.titles){if(t.active&&!active.has(t.realmId)){t.active=false;t.dissolvedYear=year;const reign=t.reigns[t.reigns.length-1];if(reign&&reign.endYear==null)reign.endYear=year}}
  for(const rid of active){if(!s.titles.some(t=>t.active&&t.realmId===rid))createRealmDynasty(world,s,rid,year,'realm_formed')}}
function enrichHistoryEvents(world,s,year){const h=history(world);for(const e of h.events){if(e.year!==year||e.societyLinked)continue;const ids=[...new Set((e.realmIds||[]).map(rid=>s.titles.find(t=>t.active&&t.realmId===rid)?.holderId).filter(Number.isInteger))];if(ids.length){e.personIds=[...new Set([...(e.personIds||[]),...ids])];const names=ids.map(id=>fullName(s,person(s,id)));if(['war','peace','alliance','conquest','crisis','realm_formed'].includes(e.type))e.text+=` Principal figures: ${names.join(' and ')}.`}e.societyLinked=true}}
function recompute(world,s,year=s.currentYear){for(const h of s.houses){const living=h.memberIds.map(id=>person(s,id)).filter(Boolean).filter(p=>aliveAt(p,year));living.sort((a,b)=>b.prestige-a.prestige||ageAt(b,year)-ageAt(a,year));h.headId=living[0]?.id??null;h.livingMembers=living.length;const avg=living.length?living.reduce((n,p)=>n+p.prestige,0)/living.length:0;h.prestige=round(clamp(h.prestige*.992+avg*.008,0,180),1);if(!living.length)h.status='Extinct'}for(const t of s.titles.filter(x=>x.active))refreshTitleClaims(world,s,t,year)}
function takeSnapshot(world,s,force=false){const interval=world.history?.snapshotInterval||5;if(!force&&s.currentYear%interval!==0)return null;const snap={year:s.currentYear,living:livingPeople(s).map(p=>[p.id,p.realmId,p.settlementId,p.houseId??-1,p.occupation,round(p.wealth,1),round(p.prestige,1),p.status]),titles:s.titles.map(t=>[t.id,t.realmId,t.active?1:0,t.holderId??-1,t.heirId??-1,t.houseId??-1,t.law,t.dissolvedYear??-1]),houses:s.houses.map(h=>[h.id,round(h.prestige,1),h.headId??-1,h.realmId??-1,h.status,h.livingMembers||0]),stats:{livingNotables:livingPeople(s).length,houses:s.houses.filter(h=>h.status!=='Extinct').length,activeTitles:s.titles.filter(t=>t.active).length,successions:s.stats.successions,crises:s.stats.successionCrises}};const last=s.snapshots[s.snapshots.length-1];if(last?.year===snap.year)s.snapshots[s.snapshots.length-1]=snap;else s.snapshots.push(snap);return snap}
function syncResidences(world,s,year){for(const p of livingPeople(s,year)){const held=s.titles.find(t=>t.active&&t.holderId===p.id);if(held){p.realmId=held.realmId;const cap=realmCapital(world,held.realmId);if(Number.isInteger(cap)&&cap>=0)p.settlementId=cap}else{const owner=ownerAt(world,p.settlementId);if(Number.isInteger(owner)&&owner>=0)p.realmId=owner}}}
function patchHistorySnapshot(world,year){const h=history(world),snap=[...h.snapshots].reverse().find(x=>x.year===year);if(!snap)return;for(const row of snap.realms||[]){const rs=h.current.realmState[row.id];if(rs){row.stability=round(rs.stability||0,1);row.treasury=round(rs.treasury||0,1);row.military=round(rs.military||0,1);row.prestige=round(rs.prestige||0,1)}}}
function simulateSocietyYear(world,s,year){s.currentYear=year;const rng=rngFor(world,year);ensureActiveRealmTitles(world,s,year);syncResidences(world,s,year);processDeaths(world,s,year,rng);processMarriages(world,s,year,rng);processBirths(world,s,year,rng);processCareers(world,s,year,rng);processRelationships(world,s,year,rng);recompute(world,s,year);enrichHistoryEvents(world,s,year);patchHistorySnapshot(world,year);takeSnapshot(world,s,false)}
function compactHistorySnapshots(world){const h=history(world),interval=h.snapshotInterval||5,current=h.currentYear;const by=new Map();for(const x of h.snapshots)if(x.year===0||x.year%interval===0||x.year===current)by.set(x.year,x);h.snapshots=[...by.values()].sort((a,b)=>a.year-b.year)}
function simulateYears(world,years,options={}){const s=initialize(world,options),h=history(world),n=clamp(Math.round(Number(years)||0),0,5000),target=clamp(h.currentYear+n,0,5000);if(s.currentYear!==h.currentYear){s.currentYear=h.currentYear;recompute(world,s,s.currentYear);takeSnapshot(world,s,true)}while(h.currentYear<target){History.simulateYears(world,1);simulateSocietyYear(world,s,h.currentYear)}compactHistorySnapshots(world);takeSnapshot(world,s,true);return s}
function simulateTo(world,targetYear,options={}){const h=history(world),target=clamp(Math.round(Number(targetYear)||0),h.currentYear,5000);return simulateYears(world,target-h.currentYear,options)}
function snapshotAt(world,year){const s=initialize(world),target=clamp(Math.round(Number(year)||0),s.startYear,s.currentYear);let best=s.snapshots[0];for(const x of s.snapshots)if(x.year<=target&&x.year>=best.year)best=x;return best}
function viewFromSnapshot(world,s,snap){const living=snap.living.map(row=>{const p=person(s,row[0]);return{id:row[0],firstName:p.firstName,surname:p.surname,gender:p.gender,birthYear:p.birthYear,deathYear:p.deathYear,realmId:row[1],settlementId:row[2],houseId:row[3]<0?null:row[3],occupation:row[4],wealth:row[5],prestige:row[6],status:row[7],spouseId:p.spouseId,parentIds:[...p.parentIds],childrenIds:[...p.childrenIds],friendIds:[...p.friendIds],rivalIds:[...p.rivalIds],traits:[...p.traits],ambition:p.ambition}});const titles=snap.titles.map(row=>{const t=title(s,row[0]);return{id:row[0],realmId:row[1],name:t.name,style:t.style,active:!!row[2],holderId:row[3]<0?null:row[3],heirId:row[4]<0?null:row[4],houseId:row[5]<0?null:row[5],law:row[6],dissolvedYear:row[7]<0?null:row[7],claims:t.claims||[]}});const houses=snap.houses.map(row=>{const h=house(s,row[0]);return{id:row[0],name:h.name,shortName:h.shortName,prestige:row[1],headId:row[2]<0?null:row[2],realmId:row[3]<0?null:row[3],status:row[4],livingMembers:row[5],foundingYear:h.foundingYear,founderId:h.founderId,rulingTitleIds:[...h.rulingTitleIds]}});return{year:snap.year,isPresent:snap.year===s.currentYear,living,titles,houses,stats:{...snap.stats}}}
function currentView(world){const s=initialize(world);const snap={year:s.currentYear,living:livingPeople(s).map(p=>[p.id,p.realmId,p.settlementId,p.houseId??-1,p.occupation,round(p.wealth,1),round(p.prestige,1),p.status]),titles:s.titles.map(t=>[t.id,t.realmId,t.active?1:0,t.holderId??-1,t.heirId??-1,t.houseId??-1,t.law,t.dissolvedYear??-1]),houses:s.houses.map(h=>[h.id,round(h.prestige,1),h.headId??-1,h.realmId??-1,h.status,h.livingMembers||0]),stats:{livingNotables:livingPeople(s).length,houses:s.houses.filter(h=>h.status!=='Extinct').length,activeTitles:s.titles.filter(t=>t.active).length,successions:s.stats.successions,crises:s.stats.successionCrises}};return viewFromSnapshot(world,s,snap)}
function viewAt(world,year){const s=initialize(world);if(year>=s.currentYear)return currentView(world);return viewFromSnapshot(world,s,snapshotAt(world,year))}
function familyGraph(world,personId,year=null){const s=initialize(world),y=year==null?s.currentYear:year,p=person(s,personId);if(!p||p.birthYear>y)return null;const ids=new Set([p.id,...p.parentIds,...p.childrenIds]);if(p.spouseId!=null)ids.add(p.spouseId);return{focusId:p.id,people:[...ids].map(id=>person(s,id)).filter(Boolean).filter(q=>q.birthYear<=y).map(q=>({id:q.id,name:fullName(s,q),relation:q.id===p.id?'Self':p.parentIds.includes(q.id)?'Parent':p.childrenIds.includes(q.id)?'Child':q.id===p.spouseId?'Spouse':'Kin',birthYear:q.birthYear,deathYear:q.deathYear,alive:aliveAt(q,y),occupation:q.occupation,houseId:q.houseId}))}}
function societyFingerprint(world){const s=initialize(world),living=livingPeople(s).slice().sort((a,b)=>a.id-b.id).map(p=>`${p.id}:${p.houseId??'x'}:${p.realmId}:${p.occupation}:${Math.round(p.prestige)}`).join('|'),titles=s.titles.map(t=>`${t.id}:${t.active?1:0}:${t.holderId}:${t.heirId}:${t.houseId}:${t.reigns.length}`).join('|'),houses=s.houses.map(h=>`${h.id}:${h.headId}:${Math.round(h.prestige)}:${h.status}`).join('|');let x=2166136261>>>0;for(const c of`${s.currentYear}|${s.stats.births}|${s.stats.deaths}|${s.stats.marriages}|${s.stats.successions}|${s.stats.successionCrises}|${living}|${titles}|${houses}`){x^=c.charCodeAt(0);x=Math.imul(x,16777619)}return(x>>>0).toString(16).padStart(8,'0')}
function validateSociety(world){const errors=[],s=world?.society;if(!s||s.schemaVersion!==SOCIETY_SCHEMA)return['society schema'];if(s.currentYear!==world.history?.currentYear)errors.push('society/history year mismatch');for(let i=0;i<s.people.length;i++){const p=s.people[i];if(p.id!==i)errors.push('person id');if(p.houseId!=null&&!s.houses[p.houseId])errors.push('person house');if(p.spouseId!=null&&person(s,p.spouseId)?.spouseId!==p.id)errors.push('spouse reciprocity');for(const cid of p.childrenIds)if(!person(s,cid)?.parentIds.includes(p.id))errors.push('parent child link')}for(const h of s.houses)for(const id of h.memberIds)if(person(s,id)?.houseId!==h.id)errors.push('house member link');for(const t of s.titles.filter(t=>t.active)){const holder=person(s,t.holderId);if(!holder||!aliveAt(holder,s.currentYear))errors.push('active title holder');if(holder&&holder.realmId!==t.realmId)errors.push('ruler realm link')}if(!s.snapshots.length||s.snapshots[s.snapshots.length-1].year!==s.currentYear)errors.push('society present snapshot');return[...new Set(errors)]}

return{VERSION,SOCIETY_SCHEMA,initialize,simulateYears,simulateTo,currentView,viewAt,snapshotAt,familyGraph,fullName,aliveAt,ageAt,societyFingerprint,validateSociety};
});