(function(root,factory){
 const api=factory(root&&root.WorldForgeWarfareSupply);
 if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.WorldForgeWarfareNaval=api;
})(typeof window!=='undefined'?window:globalThis,function(Warfare){
'use strict';
if(!Warfare)throw new Error('WorldForge naval warfare requires Warfare & Supply');
const VERSION='4.9.5',clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
function coords(c){const x=Number(c?.x??c?.mapX??c?.lon),y=Number(c?.y??c?.mapY??c?.lat);return Number.isFinite(x)&&Number.isFinite(y)?{x,y}:null}
function cityMap(w){return new Map((w.cities?.cities||[]).map(c=>[Number(c.id),c]))}
function hostile(a,b){return a&&b&&a.ownerId!=null&&b.ownerId!=null&&String(a.ownerId)!==String(b.ownerId)}
function distance(a,b){return a&&b?Math.hypot(Number(a.x)-Number(b.x),Number(a.y)-Number(b.y)):Infinity}
function lerp(a,b,t){return{x:round(a.x+(b.x-a.x)*t,2),y:round(a.y+(b.y-a.y)*t,2)}}
function nearestHostileFleet(fleets,f){const fp=f.position||f.homePosition;if(!fp)return null;return fleets.filter(x=>x!==f&&hostile(f,x)&&(x.position||x.homePosition)).map(x=>({fleet:x,d:distance(fp,x.position||x.homePosition)})).sort((a,b)=>a.d-b.d||String(a.fleet.id).localeCompare(String(b.fleet.id)))[0]?.fleet||null}
function nearestHostileCoast(w,f){const cities=(w.cities?.cities||[]).filter(c=>c.coastal&&String(c.kingdomId??c.realmId??c.factionId??c.ownerId??'')!==String(f.ownerId??''));const fp=f.homePosition||f.position;if(!fp)return null;return cities.filter(c=>coords(c)).map(c=>({city:c,d:distance(fp,coords(c))})).sort((a,b)=>a.d-b.d||Number(a.city.id)-Number(b.city.id))[0]?.city||null}
function assignMission(w,f,fleets,previous){const cities=cityMap(w),home=cities.get(Number(f.homeCityId)),homePos=coords(home)||f.position;if(!homePos)return f;f.homePosition=homePos;const enemy=nearestHostileFleet(fleets,f),enemyCoast=nearestHostileCoast(w,f);let targetPos=null,targetType='patrol',targetFleetId=null,targetCityId=null;if(enemy){targetPos=enemy.position||enemy.homePosition;targetType='intercept';targetFleetId=enemy.id}else if(enemyCoast){targetPos=coords(enemyCoast);targetType='raid';targetCityId=Number(enemyCoast.id)}
const sameTarget=previous&&previous.targetFleetId===targetFleetId&&previous.targetCityId===targetCityId&&previous.mission===targetType,base=Number(sameTarget?previous.movementProgress:0),speed=round(clamp(.06+Number(f.strength||0)*.14+Number(f.supply||0)*.12,.05,.28)),progress=targetPos?round(clamp(base+speed,0,1)):0;f.mission=targetType;f.targetFleetId=targetFleetId;f.targetCityId=targetCityId;f.movementSpeed=speed;f.movementProgress=progress;f.destination=targetPos;f.position=targetPos?lerp(homePos,targetPos,progress):homePos;f.status=Number(f.strength||0)<.22?'crippled':Number(f.supply||0)<.3?'low-supply':progress>0&&progress<1?'underway':targetType==='intercept'?'engaging':f.status;return f;}
function battlePairKey(a,b){return[a.id,b.id].sort().join('|')}
function resolveBattles(w,S){const fleets=S.fleets||[],seen=new Set(),battles=[];for(const a of fleets){if(Number(a.strength||0)<=.12)continue;const b=nearestHostileFleet(fleets,a);if(!b||Number(b.strength||0)<=.12)continue;const key=battlePairKey(a,b);if(seen.has(key))continue;seen.add(key);const d=distance(a.position,b.position),threshold=10+Math.max(Number(a.strength||0),Number(b.strength||0))*14;if(!Number.isFinite(d)||d>threshold)continue;const ap=Math.max(.01,Number(a.strength||0))*(.55+Number(a.supply||0)*.45),bp=Math.max(.01,Number(b.strength||0))*(.55+Number(b.supply||0)*.45),ratio=ap/Math.max(.01,bp),aLoss=clamp(.045+(1/Math.max(.45,ratio))*.07,.04,.24),bLoss=clamp(.045+Math.max(.45,ratio)*.07,.04,.24),aBefore=Number(a.strength||0),bBefore=Number(b.strength||0);a.strength=round(clamp(aBefore*(1-aLoss),0,1));b.strength=round(clamp(bBefore*(1-bLoss),0,1));a.supply=round(clamp(Number(a.supply||0)-.045,0,1));b.supply=round(clamp(Number(b.supply||0)-.045,0,1));const winner=a.strength===b.strength?'draw':a.strength>b.strength?a:b,loser=winner==='draw'?null:(winner===a?b:a);a.status=a.strength<.22?'crippled':'battle-damaged';b.status=b.strength<.22?'crippled':'battle-damaged';if(loser){loser.mission='retreat';loser.targetFleetId=null;loser.targetCityId=loser.homeCityId;loser.movementProgress=round(clamp(1-Number(loser.movementProgress||0),0,1));const home=coords(cityMap(w).get(Number(loser.homeCityId)));if(home)loser.destination=home}
battles.push({id:`naval:${S.currentYear}:${key}`,year:S.currentYear,type:'naval-interception',fleetAId:a.id,fleetBId:b.id,ownerA:a.ownerId,ownerB:b.ownerId,distance:round(d,2),strengthABefore:round(aBefore),strengthBBefore:round(bBefore),strengthAAfter:a.strength,strengthBAfter:b.strength,lossA:round(aLoss),lossB:round(bLoss),outcome:winner==='draw'?'draw':winner.id,position:{x:round((a.position.x+b.position.x)/2,2),y:round((a.position.y+b.position.y)/2,2)}})}return battles;}
function applySeaControl(S){const byOwner={};for(const f of S.fleets||[]){if(f.ownerId==null)continue;const k=String(f.ownerId);byOwner[k]=(byOwner[k]||0)+Number(f.strength||0)*(.55+Number(f.supply||0)*.45)}const total=Object.values(byOwner).reduce((n,x)=>n+x,0)||1;S.seaControl=Object.fromEntries(Object.entries(byOwner).map(([k,v])=>[k,round(v/total)]));return S.seaControl}
function apply(w,force=false){const S=w.warfareSupply||Warfare.initialize(w);if(!S?.fleets)return S;const year=Number(S.currentYear??0);if(!force&&S.naval?.lastAppliedYear===year)return S;const previous=new Map((S.naval?.fleets||[]).map(f=>[f.id,f]));for(const f of S.fleets)assignMission(w,f,S.fleets,previous.get(f.id));const battles=resolveBattles(w,S);S.navalBattles=[...(S.navalBattles||[]).filter(b=>Number(b.year)!==year),...battles].slice(-160);const seaControl=applySeaControl(S);S.naval={version:VERSION,lastAppliedYear:year,fleets:S.fleets.map(f=>({id:f.id,mission:f.mission,targetFleetId:f.targetFleetId,targetCityId:f.targetCityId,movementProgress:f.movementProgress,position:f.position})),battlesThisYear:battles.length,activeInterceptions:S.fleets.filter(f=>f.mission==='intercept').length,underway:S.fleets.filter(f=>f.status==='underway').length,seaControl};S.stats=S.stats||{};S.stats.navalBattles=battles.length;S.stats.activeInterceptions=S.naval.activeInterceptions;S.stats.underwayFleets=S.naval.underway;S.stats.seaControl=seaControl;return S;}
const baseSummary=Warfare.summary?.bind(Warfare),baseCity=Warfare.cityMilitaryView?.bind(Warfare);
if(baseSummary)Warfare.summary=function(w){const s=baseSummary(w),S=w.warfareSupply||{};return{...s,navalBattles:Number(S.stats?.navalBattles||0),activeInterceptions:Number(S.stats?.activeInterceptions||0),underwayFleets:Number(S.stats?.underwayFleets||0),seaControl:S.stats?.seaControl||{}}};
if(baseCity)Warfare.cityMilitaryView=function(w,id){const v=baseCity(w,id),S=w.warfareSupply||{};const fleet=(S.fleets||[]).find(f=>Number(f.homeCityId)===Number(id))||v.fleet;return{...v,fleet,navalBattles:(S.navalBattles||[]).filter(b=>b.fleetAId===fleet?.id||b.fleetBId===fleet?.id)};};
Warfare.applyNavalWarfare=apply;Warfare.NAVAL_VERSION=VERSION;
return{VERSION,assignMission,resolveBattles,applySeaControl,apply};
});
