(() => {
'use strict';
const C=window.WorldForgeCity,S=window.WorldForgeSociety;
if(!C||!S||!window.WorldRenderer)return;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const ui={world:null,viewYear:null,selectedCityId:null,selectedDistrictId:null,hit:[]};
const DISTRICT_COLORS={Government:'#776749','Old Town':'#756552',Market:'#a77d45',Residential:'#6f765a',Crafts:'#7f6a51',Temple:'#8b805c','Wealthy Quarter':'#85734d',Slums:'#574b42',Outskirts:'#59654d',Docks:'#536d70','River Ward':'#55736a','Low Quarter':'#5e5147','Village Green':'#71865c',Homes:'#6b7056',Fields:'#7b7d4e',Shrine:'#81775e'};

function installPanels(){
  document.title='WorldForge · v0.4 Cities & Crime';
  const version=$('.version-pill');if(version)version.textContent='v0.4 · CITIES & CRIME';
  const footer=document.querySelector('footer span');if(footer)footer.textContent='WorldForge v0.4 · Cities & Crime';
  const sim=$('#simState');if(sim)sim.textContent='HISTORY + SOCIETY + CITY READY';
  const architecture=$('.architecture-panel');if(architecture){const h=architecture.querySelector('h2');if(h)h.textContent='v0.4 Cities & Crime State Contract';const status=architecture.querySelector('.status-ready');if(status)status.textContent='CITY SYSTEM READY';const grid=architecture.querySelector('.architecture-grid');if(grid)grid.innerHTML='<div><b>Procedural Cities</b><span>District layouts · roads · business locations · civic roles</span></div><div><b>Local Economy</b><span>Business health · unemployment · prices · trade · prosperity</span></div><div><b>Law & Underworld</b><span>Guards · corruption · crime · gangs · territory · black markets</span></div><div><b>Named Integration</b><span>Magistrates · watch captains · merchants · gang leaders drawn from society NPCs</span></div>';const help=architecture.querySelector('.help');if(help)help.textContent='v0.5 can derive dungeons, ruins, hideouts, loot and encounters from these persistent city districts, criminal factions, wars and historical events.'}
  const marker=$('.history-charts-panel');if(!marker||$('#cityOverviewPanel'))return;
  marker.insertAdjacentHTML('beforebegin',`<section id="cityOverviewPanel" class="panel city-overview-panel"><div class="panel-head"><div><span class="eyebrow">CITY ENGINE</span><h2>Cities, Economy & Public Order</h2></div><span id="cityYearBadge" class="badge">YEAR 0</span></div><div class="city-kpis"><div><span>URBAN CENTERS</span><b id="cityUrbanCenters">—</b></div><div><span>BUSINESSES</span><b id="cityBusinesses">—</b></div><div><span>ACTIVE GANGS</span><b id="cityActiveGangs">—</b></div><div><span>MEAN CRIME</span><b id="cityMeanCrime">—</b></div><div><span>BLACK MARKET</span><b id="cityBlackMarket">—</b></div><div><span>ARRESTS</span><b id="cityArrests">—</b></div></div><p class="city-note">Every settlement has a deterministic district plan. Urban prosperity, unemployment, guards, corruption, prices and organized crime evolve with the same historical timeline.</p></section><section class="panel city-explorer-panel"><div class="panel-head city-explorer-head"><div><span class="eyebrow">PROCEDURAL CITY GENERATOR</span><h2 id="cityTitle">City Explorer</h2></div><div class="filters"><select id="citySelect"></select><select id="citySort"><option value="population">Largest</option><option value="crime">Highest crime</option><option value="trade">Trade hub</option><option value="name">Name</option></select></div></div><div class="city-explorer-grid"><div class="city-map-card"><canvas id="cityCanvas" width="900" height="560" aria-label="Procedurally generated city district map"></canvas><div id="districtFocus" class="district-focus">Select a district on the city plan.</div></div><div class="city-side"><div id="cityMetrics" class="city-metrics"></div><div><span class="eyebrow">LOCAL POWER</span><div id="cityOfficials" class="city-officials"></div></div><div><span class="eyebrow">DISTRICTS</span><div id="cityDistricts" class="city-districts"></div></div></div></div></section><section class="panel underworld-panel"><div class="panel-head"><div><span class="eyebrow">UNDERWORLD</span><h2>Gangs, Territory & Black Markets</h2></div><span class="muted-note">Named leaders · persistent factions · historical events</span></div><div class="underworld-grid"><div><h3>Active factions in selected city</h3><div id="gangList" class="gang-list"></div></div><div><h3>Businesses & local economy</h3><div id="businessList" class="business-list"></div></div></div></section>`);
  const ef=$('#eventFilter');if(ef){[['crime','Crime'],['smuggling','Smuggling'],['extortion','Extortion'],['gang_war','Gang wars'],['crackdown','Crackdowns'],['gang_formed','New gangs'],['gang_dissolved','Gang dissolutions'],['gang_succession','Gang succession'],['business_boom','Business booms']].forEach(([v,t])=>{if(![...ef.options].some(o=>o.value===v)){const o=document.createElement('option');o.value=v;o.textContent=t;ef.appendChild(o)}})}
  $('#citySelect')?.addEventListener('change',e=>{ui.selectedCityId=Number(e.target.value);ui.selectedDistrictId=null;render()});$('#citySort')?.addEventListener('change',()=>render());$('#cityCanvas')?.addEventListener('pointerdown',e=>{const canvas=e.currentTarget,r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height,hit=ui.hit.find(h=>x>=h.x&&x<=h.x+h.w&&y>=h.y&&y<=h.y+h.h);if(hit){ui.selectedDistrictId=hit.id;render()}})
}
function personName(id){return id==null?'Unfilled office':C.fullName(ui.world,id)}
function cityView(){if(!ui.world)return null;const c=ui.world.cities;if(!c)return null;return ui.viewYear==null||ui.viewYear>=c.currentYear?C.currentView(ui.world):C.viewAt(ui.world,ui.viewYear)}
function selectedDetail(v){if(!v)return null;const id=ui.selectedCityId??v.cities.slice().sort((a,b)=>b.population-a.population)[0]?.id??0;ui.selectedCityId=v.cities[id]?id:v.cities[0]?.id??0;return C.cityDetail(ui.world,ui.selectedCityId,v.year)}
function render(){const v=cityView();if(!v)return;const m=v.stats;$('#cityYearBadge').textContent=`YEAR ${v.year}`;$('#cityUrbanCenters').textContent=fmt(m.urbanCenters);$('#cityBusinesses').textContent=fmt(m.businesses);$('#cityActiveGangs').textContent=fmt(m.activeGangs);$('#cityMeanCrime').textContent=`${fmt(m.meanCrime,1)}/100`;$('#cityBlackMarket').textContent=`${fmt(m.blackMarket,1)}/100`;$('#cityArrests').textContent=fmt(m.arrests);const select=$('#citySelect'),sort=$('#citySort')?.value||'population',current=String(ui.selectedCityId??'');let cities=[...v.cities];cities.sort(sort==='crime'?(a,b)=>b.crimeRate-a.crimeRate:sort==='trade'?(a,b)=>b.trade-a.trade:sort==='name'?(a,b)=>a.name.localeCompare(b.name):(a,b)=>b.population-a.population);select.innerHTML=cities.map(c=>`<option value="${c.id}">${esc(c.name)} · ${esc(c.type)}</option>`).join('');if(cities.some(c=>String(c.id)===current))select.value=current;else{ui.selectedCityId=cities[0]?.id??0;select.value=String(ui.selectedCityId)}const city=selectedDetail(v);if(!city)return;select.value=String(city.id);$('#cityTitle').textContent=city.name;renderCityMetrics(city,v);renderOfficials(city);renderDistricts(city);renderGangs(city);renderBusinesses(city);drawCity(city,v)}
function renderCityMetrics(c,v){$('#cityMetrics').innerHTML=`<div class="city-meta"><span>${esc(c.type.toUpperCase())} · YEAR ${v.year}${c.coastal?' · COASTAL':''}${c.river?' · RIVER':''}</span><b>${fmt(c.population)} inhabitants</b></div><dl><dt>Prosperity</dt><dd>${fmt(c.prosperity*100,0)}%</dd><dt>Trade</dt><dd>${fmt(c.trade,0)}</dd><dt>Unemployment</dt><dd>${fmt(c.unemployment*100,1)}%</dd><dt>Price index</dt><dd>${fmt(c.priceIndex,1)}</dd><dt>Guard strength</dt><dd>${fmt(c.guardStrength,0)}/100</dd><dt>Corruption</dt><dd>${fmt(c.corruption,0)}/100</dd><dt>Crime rate</dt><dd>${fmt(c.crimeRate,0)}/100</dd><dt>Black market</dt><dd>${fmt(c.blackMarket,0)}/100</dd></dl>`}
function renderOfficials(c){const rows=[['Magistrate',c.officials.magistrateId],['Watch Captain',c.officials.watchCaptainId],['Merchant Patron',c.officials.merchantPatronId]];$('#cityOfficials').innerHTML=rows.map(([r,id])=>`<div><span>${r}</span><b>${esc(personName(id))}</b></div>`).join('')}
function renderDistricts(c){$('#cityDistricts').innerHTML=c.districts.map(d=>`<button data-district="${esc(d.id)}" class="${ui.selectedDistrictId===d.id?'active':''}"><i style="background:${DISTRICT_COLORS[d.kind]||'#6b6b58'}"></i><span>${esc(d.name)}</span><small>${fmt(d.populationShare*c.population)} pop.</small></button>`).join('');$('#cityDistricts').querySelectorAll('[data-district]').forEach(b=>b.addEventListener('click',()=>{ui.selectedDistrictId=b.dataset.district;render()}));const d=c.districts.find(x=>x.id===ui.selectedDistrictId);$('#districtFocus').innerHTML=d?`<b>${esc(d.name)}</b> · ${fmt(d.populationShare*c.population)} residents · relative wealth ${fmt(d.wealth*100,0)}/100 · criminal attraction ${fmt(d.criminalAttraction*100,0)}/100`:'Select a district on the city plan.'}
function renderGangs(c){const gs=c.gangs.filter(g=>g.active);$('#gangList').innerHTML=gs.length?gs.sort((a,b)=>b.influence-a.influence).map(g=>`<article class="gang-card"><div class="gang-title"><i style="background:${g.color}"></i><div><span>${esc(g.specialty.toUpperCase())}</span><h3>${esc(g.name)}</h3><p>Led by ${esc(personName(g.leaderId))}</p></div></div><div class="gang-bars"><label>Influence <i><b style="width:${Math.min(100,g.influence)}%"></b></i><strong>${fmt(g.influence,0)}</strong></label><label>Heat <i><b style="width:${Math.min(100,g.heat)}%"></b></i><strong>${fmt(g.heat,0)}</strong></label></div><dl><dt>Members</dt><dd>${fmt(g.members)}</dd><dt>Treasury</dt><dd>${fmt(g.treasury,0)}</dd><dt>Territory</dt><dd>${g.territoryIds.length} districts</dd><dt>Founded</dt><dd>Year ${g.foundedYear}</dd></dl></article>`).join(''):'<div class="empty">No active organized-crime faction is recorded in this settlement.</div>'}
function renderBusinesses(c){const active=c.businesses.filter(b=>b.active),rows=active.slice().sort((a,b)=>b.tier-a.tier||b.health-a.health).slice(0,16);$('#businessList').innerHTML=rows.length?rows.map(b=>{const d=c.districts.find(x=>x.id===b.districtId);return`<div class="business-row"><div><b>${esc(b.name)}</b><small>${esc(b.sector)} · ${esc(d?.name||'Unknown district')}</small></div><span>${b.ownerId!=null?esc(personName(b.ownerId)):'collective'}</span><strong>T${b.tier}</strong></div>`}).join(''):'<div class="empty">No active businesses recorded.</div>'}
function drawCity(c,v){const canvas=$('#cityCanvas');if(!canvas)return;const ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#111713';ctx.fillRect(0,0,W,H);const cx=W*.5,cy=H*.49,R=Math.min(W,H)*.40;ctx.strokeStyle='#756c55';ctx.lineWidth=10;ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='rgba(220,205,164,.18)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(cx,cy,R-10,0,Math.PI*2);ctx.stroke();const pos=id=>{const d=c.districts.find(x=>x.id===id);return d?{x:W*(.12+d.x*.76),y:H*(.11+d.y*.76)}:null};ctx.lineCap='round';for(const [a,b] of c.roads){const A=pos(a),B=pos(b);if(!A||!B)continue;ctx.strokeStyle='#8e8060';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke();ctx.strokeStyle='#3a352a';ctx.lineWidth=2;ctx.stroke()}ui.hit=[];for(const d of c.districts){const p=pos(d.id),dw=Math.max(76,d.w*W*.72),dh=Math.max(50,d.h*H*.72),x=p.x-dw/2,y=p.y-dh/2;ctx.fillStyle=DISTRICT_COLORS[d.kind]||'#656554';ctx.strokeStyle=ui.selectedDistrictId===d.id?'#f1d78e':'#282a22';ctx.lineWidth=ui.selectedDistrictId===d.id?5:3;ctx.fillRect(x,y,dw,dh);ctx.strokeRect(x,y,dw,dh);ui.hit.push({id:d.id,x,y,w:dw,h:dh});const gangs=c.gangs.filter(g=>g.active&&g.territoryIds.includes(d.id));gangs.forEach((g,i)=>{ctx.strokeStyle=g.color;ctx.lineWidth=4;ctx.setLineDash([10,6]);ctx.strokeRect(x+4+i*5,y+4+i*5,dw-8-i*10,dh-8-i*10);ctx.setLineDash([])});ctx.fillStyle='#f0ead6';ctx.font='700 15px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';wrapLabel(ctx,d.name,p.x,p.y,dw-12)}ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.fillStyle='rgba(235,226,198,.72)';ctx.font='700 13px system-ui';ctx.fillText(`${c.name.toUpperCase()} · ${c.type.toUpperCase()} · YEAR ${v.year}`,22,30);ctx.fillStyle='rgba(235,226,198,.48)';ctx.font='12px system-ui';ctx.fillText('Dashed outlines indicate gang territory. District positions are deterministic for the world seed.',22,H-20)}
function wrapLabel(ctx,text,x,y,max){const words=String(text).split(' ');if(words.length<2||ctx.measureText(text).width<=max){ctx.fillText(text,x,y);return}let a='',b='';for(const w of words){const t=(a+' '+w).trim();if(!b&&ctx.measureText(t).width<=max)a=t;else b=(b+' '+w).trim()}ctx.fillText(a,x,y-9);ctx.fillText(b,x,y+9)}

installPanels();
const originalSocietySimulate=S.simulateYears.bind(S),originalSocietyTo=S.simulateTo?.bind(S);
S.simulateYears=function(world,years,options){C.simulateYears(world,years,options);return world.society};
S.simulateTo=function(world,target,options){C.simulateTo(world,target,options);return world.society};
S.__worldforgeV04OriginalSimulate=originalSocietySimulate;S.__worldforgeV04OriginalTo=originalSocietyTo;
const proto=window.WorldRenderer.prototype,oldSetWorld=proto.setWorld,oldSetHistoryView=proto.setHistoryView;
proto.setWorld=function(world){ui.world=world;C.initialize(world);const r=oldSetWorld.call(this,world);ui.viewYear=null;render();return r};
proto.setHistoryView=function(view){const r=oldSetHistoryView.call(this,view);if(this.world){ui.world=this.world;ui.viewYear=view?.year??null;render()}return r};
window.WorldForgeCityUI={render,selectCity(id){ui.selectedCityId=Number(id);render()},state:ui};
})();