(()=>{
'use strict';
const U=window.WorldForgeUrbanEvolution,W=window.WorldForgeWorldbuilding;if(!U||!W)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pct=n=>`${(Number(n||0)*100).toFixed(0)}%`;
let last='',comparison='latest';function currentWorld(){return window.WorldForgeWorldbuildingUI?.state?.world||window.WorldForgeWorldOrderUI?.state?.world||window.WorldForgeReleaseUI?.state?.world||null}
function ensure(){const panel=$('#worldbuildingPanel');if(!panel||$('#urbanEvolutionSection'))return;const host=panel.querySelector('.worldbuilding-layout>div')||panel;host.insertAdjacentHTML('beforeend',`<div id="urbanEvolutionSection"><div class="labor-head"><span>LIVING CITY EVOLUTION</span><b>DISTRICT LIFECYCLE · SPRAWL · RECONSTRUCTION</b></div><div id="urbanEvolutionSummary" class="worldbuilding-kpis"></div><div class="worldbuilding-toolbar"><label>Compare with<select id="urbanEvolutionCompare"><option value="latest">Previous retained snapshot</option></select></label></div><div id="urbanEvolutionDistricts" class="worldbuilding-districts"></div><div class="labor-head"><span>HISTORICAL COMPARISON</span><b>STATE CHANGES · DAMAGE · OUTSIDE-WALL GROWTH</b></div><div id="urbanEvolutionHistory" class="worldbuilding-landmarks"></div><div id="urbanEvolutionProjects" class="worldbuilding-landmarks"></div></div>`);$('#urbanEvolutionCompare').onchange=e=>{comparison=e.target.value;last='';render(true)}}
function snapshotFor(world,sid){const rows=(world.urbanEvolution?.districtHistory||[]).filter(x=>x.settlements?.some(s=>s.id===sid));if(!rows.length)return null;if(comparison==='latest')return rows.length>1?rows[rows.length-2]:rows[0];return rows.find(x=>String(x.year)===comparison)||rows[0]}
function renderHistory(world,v,sid){const rows=(world.urbanEvolution?.districtHistory||[]).filter(x=>x.settlements?.some(s=>s.id===sid));const sel=$('#urbanEvolutionCompare');if(sel){const opts=[`<option value="latest" ${comparison==='latest'?'selected':''}>Previous retained snapshot</option>`].concat(rows.slice(0,-1).reverse().map(x=>`<option value="${x.year}" ${String(x.year)===comparison?'selected':''}>Year ${x.year}</option>`));sel.innerHTML=opts.join('')}const snap=snapshotFor(world,sid),host=$('#urbanEvolutionHistory');if(!snap){host.innerHTML='<article><small>NO HISTORICAL SNAPSHOT</small><p>Advance the world simulation to retain additional urban states for comparison.</p></article>';return}const old=snap.settlements.find(s=>s.id===sid),curr=new Map(v.districts.map(d=>[String(d.id),d])),changes=[];for(const row of old?.districts||[]){const [id,state,damage,outside]=row,d=curr.get(String(id));if(!d)continue;if(d.state!==state||Math.abs(Number(d.damage||0)-Number(damage||0))>.05||Boolean(d.outsideWalls)!==Boolean(outside))changes.push({d,oldState:state,oldDamage:Number(damage||0),oldOutside:Boolean(outside)})}host.innerHTML=changes.length?changes.map(x=>`<article><div><small>YEAR ${snap.year} → ${esc(x.d.state.toUpperCase())}</small><h3>${esc(x.d.name)}</h3></div><div class="worldbuilding-mini"><span><i>STATE</i><b>${esc(String(x.oldState).toUpperCase())} → ${esc(x.d.state.toUpperCase())}</b></span><span><i>DAMAGE</i><b>${pct(x.oldDamage)} → ${pct(x.d.damage)}</b></span><span><i>WALLS</i><b>${x.oldOutside?'OUTSIDE':'INSIDE'} → ${x.d.outsideWalls?'OUTSIDE':'INSIDE'}</b></span></div></article>`).join(''):`<article><small>NO MATERIAL DISTRICT CHANGE</small><p>${esc(v.name)} has no retained district-state change relative to year ${snap.year}.</p></article>`}
function render(force=false){const world=currentWorld();if(!world)return;ensure();if(!$('#urbanEvolutionSection'))return;U.initialize(world);const sid=Number(window.WorldForgeWorldbuildingUI?.state?.settlement||0),v=U.settlementView(world,sid);if(!v)return;const key=`${world.urbanEvolution?.revision}|${sid}|${v.expansionStage}|${v.ruinedDistricts}|${v.rebuildingDistricts}|${comparison}`;if(!force&&key===last)return;last=key;const projects=(world.urbanEvolution?.projects||[]).filter(p=>p.settlementId===sid);$('#urbanEvolutionSummary').innerHTML=[['EXPANSION',v.expansionStage.replaceAll('_',' ')],['SPRAWL',pct(v.sprawl)],['WALL PRESSURE',pct(v.wallPressure)],['SKYLINE',pct(v.skyline)],['GROWING',v.growingDistricts],['RUINED',v.ruinedDistricts],['REBUILDING',v.rebuildingDistricts]].map(([k,x])=>`<div><span>${k}</span><b>${esc(x)}</b></div>`).join('');$('#urbanEvolutionDistricts').innerHTML=v.districts.map(d=>`<article data-urban-state="${esc(d.state)}"><div><small>${esc(d.role.replaceAll('_',' ').toUpperCase())} · ${esc(d.state.toUpperCase())}${d.outsideWalls?' · OUTSIDE WALLS':''}</small><h3>${esc(d.name)}</h3></div><div class="worldbuilding-mini"><span><i>DENSITY</i><b>${pct(Math.min(1,d.density))}</b></span><span><i>GROWTH</i><b>${pct(d.growth)}</b></span><span><i>DECLINE</i><b>${pct(d.decline)}</b></span><span><i>DAMAGE</i><b>${pct(d.damage)}</b></span></div></article>`).join('');renderHistory(world,v,sid);$('#urbanEvolutionProjects').innerHTML=projects.length?projects.map(p=>`<article><div><small>${esc(p.type.replaceAll('_',' ').toUpperCase())} · ${esc(p.status.toUpperCase())}</small><h3>${esc(p.name)}</h3></div><div class="worldbuilding-mini"><span><i>PROGRESS</i><b>${pct(p.progress)}</b></span></div></article>`).join(''):'<article><small>NO MAJOR URBAN WORKS</small><p>This settlement has no active reconstruction, wall expansion or visitor-infrastructure project.</p></article>';const pill=document.querySelector('.version-pill');if(pill)pill.textContent='v4.5 · LIVING CITIES'}
const observer=new MutationObserver(()=>render());observer.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('visibilitychange',()=>{if(!document.hidden)render(true)});setInterval(()=>{if(!document.hidden)render()},5000);setTimeout(()=>render(true),1400);window.WorldForgeUrbanUI={render};
})();
