(function(root,factory){
  const api=factory(root&&root.WorldForgeHistory,root&&root.WorldForgeResources,root&&root.WorldForgeInstitutions,root&&root.WorldForgeMilitary,root&&root.WorldForgeTreasury,root&&root.WorldForgeSociety,root&&root.WorldForgeCity,root&&root.WorldForgeTechnology);
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(root)root.WorldForgeWorkforce=api;
})(typeof window!=='undefined'?window:globalThis,function(History,Resources,Institutions,Military,Treasury,Society,City,Technology){
'use strict';
const VERSION='2.2.0',SCHEMA=1,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),round=(v,d=3)=>Number(Number(v).toFixed(d));
let baseSimulator=null;
const J=(id,name,sector,skill,wage,description,opts={})=>({id,name,sector,skill,wage,description,...opts});
const JOBS=[
J('field_farmer','Field Farmer','Agriculture',.24,.72,'Cultivates grain and field crops; demand follows managed farms and arable land.',{facilities:['farm'],rural:true}),
J('rice_farmer','Paddy Farmer','Agriculture',.28,.75,'Maintains irrigated rice fields in wet lowlands.',{facilities:['farm'],resource:'rice',rural:true}),
J('shepherd','Shepherd','Agriculture',.25,.73,'Tends sheep and goats across pasture and uplands.',{facilities:['ranch'],resource:'livestock',rural:true}),
J('cattle_herder','Cattle Herder','Agriculture',.3,.8,'Raises cattle for food, hides and draft power.',{facilities:['ranch'],resource:'livestock',rural:true}),
J('beekeeper','Beekeeper','Agriculture',.34,.9,'Maintains apiaries and pollination around productive rural settlements.',{rural:true,specialist:true}),
J('vintner','Vintner','Agriculture',.42,1.02,'Cultivates grapes and manages wine production.',{resource:'wine',specialist:true}),
J('fisher','Fisher','Maritime',.3,.8,'Operates small fishing craft and shore fisheries.',{facilities:['fishery'],resource:'fish',coastal:true}),
J('salt_worker','Salt Worker','Extraction',.28,.77,'Harvests and processes salt from coastal pans or mineral deposits.',{resource:'salt',specialist:true}),
J('logger','Logger','Extraction',.3,.82,'Fells and prepares timber for construction and industry.',{facilities:['lumber_camp'],resource:'timber',rural:true}),
J('charcoal_burner','Charcoal Burner','Extraction',.38,.93,'Produces charcoal for metalworking and high-temperature furnaces.',{facilities:['foundry','smithy'],resource:'timber',specialist:true}),
J('iron_miner','Iron Miner','Extraction',.35,.94,'Extracts iron ore for foundries and smithies.',{facilities:['mine'],resource:'iron'}),
J('copper_miner','Copper Miner','Extraction',.36,.95,'Extracts copper ore for tools, coinage and craftwork.',{facilities:['mine'],resource:'copper'}),
J('coal_miner','Coal Miner','Extraction',.4,1.02,'Extracts coal for foundries and heavy industry.',{facilities:['mine'],resource:'coal'}),
J('quarry_worker','Quarry Worker','Extraction',.34,.9,'Cuts building stone for roads, walls and public works.',{specialist:true}),
J('miller','Miller','Food Processing',.38,.96,'Operates grain mills and maintains milling machinery.',{facilities:['mill']}),
J('baker','Baker','Food Processing',.34,.92,'Turns flour into bread for urban and military consumption.',{facilities:['bakery']}),
J('butcher','Butcher','Food Processing',.34,.93,'Processes livestock for urban markets and preserved provisions.'),
J('brewer','Brewer','Food Processing',.4,1.0,'Produces ale and preserved beverages for settlements and garrisons.',{specialist:true}),
J('sawyer','Sawyer','Industry',.4,.99,'Cuts timber into standardized lumber.',{facilities:['sawmill']}),
J('foundry_worker','Foundry Worker','Industry',.48,1.12,'Smelts ore and manages furnaces for bulk metal production.',{facilities:['foundry']}),
J('blacksmith','Blacksmith','Crafts',.58,1.3,'Forges tools, fittings and general metal goods.',{facilities:['smithy']}),
J('armorer','Armorer','Crafts',.68,1.5,'Produces and repairs military armor and protective equipment.',{facilities:['smithy'],specialist:true,wartime:true}),
J('weaponsmith','Weaponsmith','Crafts',.7,1.55,'Forges weapons and maintains military arsenals.',{facilities:['smithy'],specialist:true,wartime:true}),
J('carpenter','Carpenter','Crafts',.5,1.14,'Builds structures, wagons, fittings and wooden machinery.'),
J('cooper','Cooper','Crafts',.48,1.08,'Makes barrels used for food, water, wine and long-distance transport.',{specialist:true,trade:true}),
J('tanner','Tanner','Crafts',.44,1.02,'Processes hides into leather for civilian and military use.'),
J('potter','Potter','Crafts',.42,1.0,'Produces ceramic vessels, storage jars and building material.'),
J('glassblower','Glassblower','Crafts',.64,1.42,'Creates glassware and optical components for prosperous cities.',{specialist:true,urban:true}),
J('stone_mason','Stone Mason','Construction',.56,1.24,'Builds masonry structures, walls, bridges and monuments.'),
J('road_builder','Road Builder','Construction',.38,1.02,'Constructs and repairs roads and military transport routes.',{trade:true}),
J('dockworker','Dockworker','Maritime',.32,.9,'Loads and unloads ships, warehouses and waterfront cargo.',{coastal:true,trade:true}),
J('shipwright','Shipwright','Maritime',.64,1.48,'Builds hulls and maintains vessels in shipyards.',{facilities:['shipyard'],coastal:true}),
J('caulker','Ship Caulker','Maritime',.58,1.36,'Seals hull seams and performs specialist ship maintenance.',{facilities:['shipyard'],coastal:true,specialist:true}),
J('ropemaker','Ropemaker','Maritime',.46,1.08,'Produces rope and cordage for ships, cranes and haulage.',{facilities:['shipyard'],coastal:true,specialist:true}),
J('sailmaker','Sailmaker','Maritime',.52,1.2,'Cuts and repairs sails for merchant and naval vessels.',{facilities:['shipyard'],coastal:true,specialist:true}),
J('ship_chandler','Ship Chandler','Maritime',.5,1.18,'Supplies vessels with provisions, tools, rope and stores.',{coastal:true,trade:true,specialist:true}),
J('merchant_sailor','Merchant Sailor','Maritime',.46,1.12,'Crews trading vessels and transports cargo between ports.',{coastal:true,trade:true}),
J('harbor_pilot','Harbor Pilot','Maritime',.76,1.8,'Guides vessels through local channels, shoals and harbor approaches.',{coastal:true,specialist:true,rare:true}),
J('lighthouse_keeper','Lighthouse Keeper','Maritime',.52,1.22,'Maintains coastal navigation lights and watches dangerous approaches.',{coastal:true,specialist:true,rare:true}),
J('ferryman','Ferryman','Transport',.34,.9,'Carries people and goods across rivers and short waterways.',{trade:true,specialist:true}),
J('wagoner','Wagoner','Transport',.34,.91,'Hauls bulk cargo between settlements and warehouses.',{trade:true}),
J('caravan_master','Caravan Master','Transport',.6,1.4,'Organizes long-distance overland merchant convoys.',{trade:true,specialist:true}),
J('warehouse_keeper','Warehouse Keeper','Logistics',.42,1.02,'Records, stores and releases cargo from warehouses.',{facilities:['warehouse']}),
J('granary_keeper','Granary Keeper','Logistics',.42,1.02,'Maintains strategic food reserves and controls spoilage.',{facilities:['granary']}),
J('quartermaster','Military Quartermaster','Military Support',.64,1.48,'Organizes army food, equipment and transport supplies.',{wartime:true,specialist:true}),
J('siege_engineer','Siege Engineer','Military Support',.78,1.88,'Designs field fortifications, siege works and military machinery.',{wartime:true,specialist:true,rare:true}),
J('army_surgeon','Army Surgeon','Military Support',.82,2.0,'Treats battlefield casualties and manages military medical stations.',{wartime:true,facilities:['hospital'],specialist:true,rare:true}),
J('soldier','Professional Soldier','Military',.42,1.15,'Serves as a trained full-time soldier outside temporary levies.',{wartime:true}),
J('city_guard','City Guard','Public Service',.38,1.0,'Polices streets, markets and gates and responds to civil disorder.'),
J('customs_inspector','Customs Inspector','Public Service',.56,1.3,'Assesses imports, cargo declarations and customs duties.',{coastal:true,trade:true,specialist:true}),
J('tax_assessor','Tax Assessor','Public Service',.6,1.38,'Values taxable activity and maintains state revenue rolls.',{capital:true,specialist:true}),
J('moneyer','Moneyer','Finance',.68,1.58,'Strikes and verifies coinage under treasury authority.',{capital:true,specialist:true,rare:true}),
J('banker','Banker','Finance',.7,1.7,'Provides credit, settles accounts and finances trade and state debt.',{urban:true,trade:true,specialist:true}),
J('merchant','Merchant','Commerce',.48,1.22,'Trades local and imported goods through markets and shops.',{trade:true}),
J('market_broker','Market Broker','Commerce',.58,1.38,'Matches buyers and sellers and organizes bulk contracts.',{urban:true,trade:true,specialist:true}),
J('innkeeper','Innkeeper','Services',.38,1.0,'Operates lodging, food and meeting space for travelers and locals.'),
J('healer','Healer','Health',.62,1.45,'Provides general medical treatment and public health care.',{facilities:['hospital']}),
J('apothecary','Apothecary','Health',.66,1.55,'Prepares medicines, compounds and preserved medical supplies.',{facilities:['hospital'],specialist:true}),
J('midwife','Midwife','Health',.58,1.32,'Provides maternal and infant care within the settlement.',{specialist:true}),
J('scribe','Scribe','Knowledge',.58,1.3,'Keeps legal, commercial and administrative records.',{facilities:['library','temple_archive']}),
J('archivist','Archivist','Knowledge',.7,1.58,'Catalogues and preserves records, books and historical evidence.',{facilities:['library','temple_archive'],specialist:true}),
J('bookbinder','Bookbinder','Knowledge',.58,1.32,'Binds manuscripts and printed works for long-term use.',{facilities:['library'],specialist:true}),
J('illuminator','Manuscript Illuminator','Knowledge',.68,1.52,'Produces decorated manuscripts for elite, religious and scholarly patrons.',{facilities:['library','temple_archive'],specialist:true,rare:true}),
J('scholar','Scholar','Knowledge',.74,1.72,'Conducts teaching, research and formal scholarship.',{facilities:['university']}),
J('cartographer','Cartographer','Knowledge',.76,1.78,'Produces navigational and administrative maps from surveys and observations.',{facilities:['university','observatory'],specialist:true,rare:true}),
J('astronomer','Astronomer','Knowledge',.82,1.92,'Studies celestial motion for calendars and navigation.',{facilities:['observatory'],specialist:true,rare:true}),
J('museum_curator','Museum Curator','Culture',.72,1.65,'Catalogues and protects artifacts and public collections.',{facilities:['museum'],specialist:true}),
J('priest','Priest','Religion',.55,1.26,'Provides worship, ritual and community administration.',{facilities:['temple_archive']}),
J('relic_keeper','Relic Keeper','Religion',.68,1.5,'Maintains sacred relics, inventories and pilgrimage objects.',{facilities:['temple_archive'],specialist:true,rare:true}),
J('teacher','Teacher','Education',.62,1.4,'Provides literacy and general instruction to urban populations.',{facilities:['university','library']}),
J('civil_engineer','Civil Engineer','Engineering',.74,1.78,'Plans bridges, roads, waterworks and major civic construction.',{urban:true,specialist:true}),
J('surveyor','Surveyor','Engineering',.64,1.48,'Measures land, roads, boundaries and construction sites.',{trade:true,specialist:true}),
J('magistrate_clerk','Court Clerk','Administration',.58,1.3,'Maintains court records and assists judicial administration.',{urban:true}),
J('civil_servant','Civil Servant','Administration',.52,1.2,'Carries out routine state administration, permits and record keeping.',{capital:true}),
J('gravedigger','Gravedigger','Services',.25,.76,'Maintains burial grounds and performs interments.',{specialist:true}),
J('fire_watch','Fire Watch','Public Service',.32,.9,'Patrols dense districts for fires and organizes emergency response.',{urban:true,specialist:true})
];
const JOB_MAP=new Map(JOBS.map(x=>[x.id,x]));
const SECTORS=[...new Set(JOBS.map(x=>x.sector))];
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=hash(seed);return()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function seedOf(w){return w.endless?.baseSeed||String(w.settings?.seed||'WORLD').split('|EPOCH:')[0]}
function keyed(w,y,s){return rng(`${seedOf(w)}|WORKFORCE|${y}|${s}`)}
function absYear(w){return(w.endless?.epochOffset||0)+Number(w.history?.currentYear||0)}
function setBaseSimulator(fn){if(typeof fn==='function')baseSimulator=fn;return api}
function owner(w,sid){return w.history?.current?.settlementKingdomIds?.[sid]??w.settlements?.[sid]?.kingdomId??null}
function realmName(w,rid){return w.history?.realms?.[rid]?.shortName||`Realm ${rid}`}
function pop(w,sid){return Math.max(0,Number(w.history?.current?.settlementPopulation?.[sid]||w.settlements?.[sid]?.population||0))}
function prosperity(w,sid){return Number(w.history?.current?.settlementProsperity?.[sid]??.45)}
function market(w,sid){return Resources?.market?.(w,sid)||null}
function facilities(w,sid){return (w.institutions?.facilities||[]).filter(f=>f.settlementId===sid&&f.status==='active')}
function facilityCount(w,sid,id){return facilities(w,sid).filter(f=>f.typeId===id).length}
function isCoastal(w,sid){const s=w.settlements?.[sid];if(!s)return false;const W=w.settings.width,H=w.settings.height,sea=w.settings.seaLevel,x0=Math.round(s.x),y0=Math.round(s.y);for(let oy=-2;oy<=2;oy++)for(let ox=-2;ox<=2;ox++){if(!ox&&!oy)continue;const y=y0+oy;if(y<0||y>=H)continue;const x=(x0+ox+W)%W;if(Number(w.layers.elevation[y*W+x])<sea)return true}return false}
function activeWar(w,rid){return(w.history?.current?.activeWarIds||[]).some(id=>{const q=w.history?.wars?.[id];return q&&q.endYear==null&&(q.attackerId===rid||q.defenderId===rid)})}
function realmArmyManpower(w,rid){return(w.military?.armies||[]).filter(a=>a.status==='active'&&a.realmId===rid).reduce((n,a)=>n+Number(a.size||0),0)}
function pushHistory(w,e){const h=History.initialize(w);h.events.push({id:h.events.length,year:h.currentYear,absoluteYear:absYear(w),...e});return h.events.at(-1)}
function state(w){if(!w.workforce||w.workforce.schemaVersion!==SCHEMA)w.workforce={schemaVersion:SCHEMA,engineVersion:VERSION,currentYear:absYear(w),markets:[],movements:[],annual:[],archives:[],realmMobilization:{},settings:{retainDetailedYears:1000,maxMovements:1600},stats:{employed:0,unemployed:0,conscripted:0,vacancies:0,migrants:0,refugees:0,specialists:0,laborCrises:0,archivedYears:0}};const W=w.workforce;W.engineVersion=VERSION;W.markets=W.markets||[];W.movements=W.movements||[];W.annual=W.annual||[];W.archives=W.archives||[];W.realmMobilization=W.realmMobilization||{};W.settings={retainDetailedYears:1000,maxMovements:1600,...W.settings};W.stats={employed:0,unemployed:0,conscripted:0,vacancies:0,migrants:0,refugees:0,specialists:0,laborCrises:0,archivedYears:0,...W.stats};return W}
function initialize(w){if(!w)throw new Error('World required');History?.initialize?.(w);Resources?.initialize?.(w);Institutions?.initialize?.(w);Military?.initialize?.(w);Treasury?.initialize?.(w);Society?.initialize?.(w);City?.initialize?.(w);const W=state(w);syncMarkets(w);return W}
function laborDemography(w,sid){const p=pop(w,sid),health=(w.institutions?.facilities||[]).some(f=>f.settlementId===sid&&f.status==='active'&&f.typeId==='hospital')?.03:0,children=round(p*clamp(.245-health,.19,.28),0),elders=round(p*clamp(.105+health*.6,.08,.16),0),workingAge=Math.max(0,p-children-elders),participation=clamp(.69+prosperity(w,sid)*.08,0.62,.8),laborForce=Math.round(workingAge*participation);return{population:Math.round(p),children,elders,workingAge:Math.round(workingAge),laborForce}}
function marketState(w,sid){const W=state(w);let m=W.markets.find(x=>x.settlementId===sid);if(!m){m={settlementId:sid,realmId:owner(w,sid),population:0,children:0,workingAge:0,elders:0,laborForce:0,employed:0,unemployed:0,conscripted:0,vacancies:0,wageIndex:1,skillIndex:.4,workforceFill:1,recruitmentPressure:0,migrationPressure:0,refugees:0,jobs:{},sectors:{},specialJobs:[],lastYear:absYear(w)};W.markets.push(m)}return m}
function syncMarkets(w){const W=state(w);for(const s of w.settlements||[]){const m=marketState(w,s.id);m.realmId=owner(w,s.id)}W.markets=W.markets.filter(m=>w.settlements?.[m.settlementId]);return W}
function suitability(w,sid,id){return Number(market(w,sid)?.suitability?.[id]||0)}
function jobDemand(w,sid,job){const s=w.settlements[sid],p=pop(w,sid),fac=facilities(w,sid),rid=owner(w,sid),urban=['Capital','City','Town'].includes(s.type),coast=isCoastal(w,sid),war=activeWar(w,rid),cap=!!s.capital||w.history?.realms?.[rid]?.capitalId===sid,trade=Math.max(0,Number(market(w,sid)?.exports||0)+Number(market(w,sid)?.imports||0));let d=0;
 const fc=id=>fac.filter(f=>f.typeId===id).length;
 if(job.facilities?.length)d+=job.facilities.reduce((n,id)=>n+fc(id),0)*(5+Math.pow(Math.max(100,p),.33)*1.3);
 if(job.resource)d+=suitability(w,sid,job.resource)*Math.pow(Math.max(100,p),.48)*.48;
 if(job.rural)d+=Math.pow(Math.max(100,p),.48)*.18;
 if(job.urban&&urban)d+=Math.pow(Math.max(100,p),.5)*.24;
 if(job.coastal&&coast)d+=Math.pow(Math.max(100,p),.5)*.22;
 if(job.trade)d+=Math.pow(Math.max(100,p),.45)*(.12+Math.min(.4,trade*.0001));
 if(job.capital&&cap)d+=Math.pow(Math.max(100,p),.45)*.26;
 if(job.wartime&&war)d+=Math.pow(Math.max(100,p),.48)*.2;
 switch(job.id){
  case'merchant':d+=Math.pow(p,.52)*.42;break;case'innkeeper':d+=Math.pow(p,.5)*.2;break;case'city_guard':d+=Math.pow(p,.52)*(urban?.28:.11);break;case'soldier':d+=war?Math.pow(p,.5)*.24:Math.pow(p,.45)*.04;break;case'butcher':d+=Math.pow(p,.49)*.16;break;case'carpenter':d+=Math.pow(p,.5)*.22;break;case'stone_mason':d+=Math.pow(p,.48)*.16;break;case'potter':d+=Math.pow(p,.47)*.13;break;case'tanner':d+=Math.pow(p,.46)*.1;break;case'midwife':d+=Math.max(1,p/2300);break;case'gravedigger':d+=Math.max(1,p/4200);break;case'fire_watch':d+=urban?Math.max(1,p/3600):0;break;case'civil_engineer':d+=urban&&p>3500?1+p/9000:0;break;case'surveyor':d+=p>1800?1+p/12000:0;break;case'banker':d+=urban&&p>5000?1+p/10000:0;break;case'market_broker':d+=urban&&p>2500?1+p/8000:0;break;case'quarry_worker':d+=p>800?Math.pow(p,.42)*.14:0;break;case'beekeeper':d+=suitability(w,sid,'grain')>.25?Math.max(1,p/7000):0;break;case'ferryman':d+=(w.rivers||[]).length&&p>900?Math.max(1,p/8500):0;break;
 }
 if(job.rare)d*=.38;else if(job.specialist)d*=.64;
 if(job.coastal&&!coast)d=0;if(job.capital&&!cap)d=0;if(job.wartime&&!war&&['quartermaster','siege_engineer','army_surgeon'].includes(job.id))d=0;
 if(job.id==='harbor_pilot'&&(!coast||p<2500))d=0;if(job.id==='lighthouse_keeper'&&(!coast||p<1800))d=0;if(job.id==='moneyer'&&!cap)d=0;if(job.id==='astronomer'&&!fc('observatory'))d=0;if(job.id==='cartographer'&&!fc('university')&&!fc('observatory'))d=0;if(job.id==='siege_engineer'&&Number(Technology?.realmView?.(w,rid)?.effects?.engineering||0)<.04)d*=.45;
 return Math.max(0,Math.round(d))}
function allocateConscription(w,realmId,markets){const total=realmArmyManpower(w,realmId),eligible=markets.reduce((n,m)=>n+m.laborForce,0),target=Math.min(total,Math.floor(eligible*.22));let left=target;const weighted=markets.map(m=>{const s=w.settlements[m.settlementId],rural=!['Capital','City'].includes(s.type),weight=Math.max(1,m.laborForce)*(rural?1.18:.88);return{m,weight}}),sum=weighted.reduce((n,x)=>n+x.weight,0);for(let i=0;i<weighted.length;i++){const {m,weight}=weighted[i],q=i===weighted.length-1?left:Math.min(left,Math.round(target*weight/Math.max(1,sum)));m.conscripted=Math.min(m.laborForce,q);left-=m.conscripted}state(w).realmMobilization[String(realmId)]={manpower:total,conscripted:target,laborForce:eligible,rate:eligible?target/eligible:0};return target}
function allocateJobs(w,m,year){const sid=m.settlementId,rid=m.realmId,rr=keyed(w,year,`jobs:${sid}`),available=Math.max(0,m.laborForce-m.conscripted),demand=JOBS.map(job=>({job,demand:jobDemand(w,sid,job)})).filter(x=>x.demand>0),totalDemand=demand.reduce((n,x)=>n+x.demand,0);m.jobs={};m.sectors={};m.specialJobs=[];let employed=0;
 const laborScale=totalDemand>available?available/totalDemand:1;
 for(const x of demand){const ideal=x.demand,workers=Math.min(ideal,Math.floor(ideal*laborScale)),vacancies=Math.max(0,ideal-workers),fill=ideal?workers/ideal:1,scarcity=clamp(1-fill,0,1),wage=round(x.job.wage*(.82+prosperity(w,sid)*.38)*(1+scarcity*.65)*(1+(rr()-.5)*.06),2),skill=round(clamp(x.job.skill*(.82+prosperity(w,sid)*.3)+(rr()-.5)*.05,.08,1),3);m.jobs[x.job.id]={workers,vacancies,demand:ideal,wage,skill,fill:round(fill,3)};employed+=workers;const sec=m.sectors[x.job.sector]||(m.sectors[x.job.sector]={workers:0,vacancies:0});sec.workers+=workers;sec.vacancies+=vacancies;if(x.job.specialist&&workers>0)m.specialJobs.push(x.job.id)}
 m.employed=Math.min(available,employed);m.unemployed=Math.max(0,available-m.employed);m.vacancies=Object.values(m.jobs).reduce((n,j)=>n+j.vacancies,0);m.workforceFill=totalDemand?round(m.employed/Math.max(1,Math.min(totalDemand,available)),3):1;m.wageIndex=round(Object.values(m.jobs).length?Object.values(m.jobs).reduce((n,j)=>n+j.wage*j.workers,0)/Math.max(1,m.employed):1,3);m.skillIndex=round(Object.values(m.jobs).length?Object.values(m.jobs).reduce((n,j)=>n+j.skill*j.workers,0)/Math.max(1,m.employed):.3,3);m.recruitmentPressure=round(m.laborForce?m.conscripted/m.laborForce:0,4);m.lastYear=year;
 for(const f of facilities(w,sid)){const defs=JOBS.filter(j=>j.facilities?.includes(f.typeId)),need=defs.reduce((n,j)=>n+Number(m.jobs[j.id]?.demand||0),0),have=defs.reduce((n,j)=>n+Number(m.jobs[j.id]?.workers||0),0);f.workforceFactor=round(need?clamp(have/need,.28,1.08):1,3);f.actualWorkers=Math.round(have);if(f.workers!=null)f.staffingGap=Math.max(0,Math.round(Number(f.workers||0)-have))}
 return m}
function migrationPressure(w,m){const city=w.cities?.cities?.[m.settlementId],mk=market(w,m.settlementId),siege=(w.military?.sieges||[]).some(s=>s.status==='active'&&s.settlementId===m.settlementId),unemp=m.laborForce?m.unemployed/m.laborForce:0,vac=m.laborForce?m.vacancies/m.laborForce:0,food=Math.max(0,.8-Number(mk?.foodSecurity||1)),crime=Number(city?.crimeRate||0)/100,fiscal=w.treasury?.realms?.find(a=>a.realmId===m.realmId),fiscalStress=fiscal?Math.max(0,Number(fiscal.inflation||0)-.08)+(100-Number(fiscal.credit||80))/500:0;return round(clamp(unemp*.9+m.recruitmentPressure*.75+food*.65+crime*.25+fiscalStress+(siege?.75:0)-vac*.28-prosperity(w,m.settlementId)*.16,-.25,1.8),4)}
function movePeople(w,year){const W=state(w),rows=W.markets;for(const m of rows)m.migrationPressure=migrationPressure(w,m);const sources=rows.filter(m=>m.migrationPressure>.18&&m.population>350),targets=rows.filter(m=>m.migrationPressure<.12&&m.vacancies>0).sort((a,b)=>a.migrationPressure-b.migrationPressure||b.vacancies-a.vacancies);for(const src of sources.sort((a,b)=>b.migrationPressure-a.migrationPressure).slice(0,12)){const s=w.settlements[src.settlementId],siege=(w.military?.sieges||[]).some(x=>x.status==='active'&&x.settlementId===src.settlementId),candidates=targets.filter(t=>t.settlementId!==src.settlementId&&(!siege||t.realmId===src.realmId||t.realmId!==src.realmId));if(!candidates.length)continue;const dst=candidates.find(t=>t.realmId===src.realmId)||candidates[0],d=w.settlements[dst.settlementId],q=Math.max(1,Math.min(Math.round(src.population*(siege?.012:.0025)*clamp(src.migrationPressure,.2,1.5)),Math.round(dst.vacancies*.8)+4,Math.round(src.population*.02)));if(q<1)continue;w.history.current.settlementPopulation[src.settlementId]=Math.max(20,Number(w.history.current.settlementPopulation[src.settlementId]||0)-q);w.history.current.settlementPopulation[dst.settlementId]=Number(w.history.current.settlementPopulation[dst.settlementId]||0)+q;src.population-=q;dst.population+=q;const refugee=!!siege||src.realmId!==dst.realmId;dst.refugees=Number(dst.refugees||0)+(refugee?q:0);W.movements.push({year,from:src.settlementId,to:dst.settlementId,people:q,kind:refugee?'refugee':'labor_migration',reason:siege?'siege':src.recruitmentPressure>.12?'conscription':src.unemployed>src.laborForce*.12?'unemployment':'opportunity'});W.stats.migrants+=q;if(refugee)W.stats.refugees+=q;if(refugee&&q>=Math.max(20,src.population*.003))pushHistory(w,{type:'refugee_movement',importance:1,settlementIds:[src.settlementId,dst.settlementId],realmIds:[src.realmId,dst.realmId].filter(Number.isInteger),title:`Refugees leave ${s.name}`,text:`About ${q.toLocaleString()} people flee toward ${d.name} amid ${siege?'siege conditions':'economic and military pressure'}.`})}if(W.movements.length>W.settings.maxMovements)W.movements.splice(0,W.movements.length-W.settings.maxMovements)}
function enrichNotables(w){const s=w.society;if(!s)return;for(const p of s.people||[]){if(p.notableProfession||p.deathYear!=null)continue;const m=state(w).markets.find(x=>x.settlementId===p.settlementId),pool=m?Object.entries(m.jobs).filter(([,v])=>v.workers>0).map(([id,v])=>({id,v,def:JOB_MAP.get(id)})).filter(x=>x.def):[];let preferred=pool;const broad=String(p.occupation||'').toLowerCase();if(broad.includes('scholar'))preferred=pool.filter(x=>['Knowledge','Education','Engineering'].includes(x.def.sector));else if(broad.includes('soldier'))preferred=pool.filter(x=>x.def.sector.includes('Military')||x.id==='city_guard');else if(broad.includes('merchant'))preferred=pool.filter(x=>['Commerce','Finance','Transport','Maritime'].includes(x.def.sector));else if(broad.includes('healer'))preferred=pool.filter(x=>x.def.sector==='Health');else if(broad.includes('priest'))preferred=pool.filter(x=>x.def.sector==='Religion');else if(broad.includes('farmer'))preferred=pool.filter(x=>x.def.sector==='Agriculture');else if(broad.includes('artisan')||broad.includes('architect'))preferred=pool.filter(x=>['Crafts','Construction','Engineering','Industry'].includes(x.def.sector));if(!preferred.length)preferred=pool;if(preferred.length){preferred.sort((a,b)=>(b.def.skill-a.def.skill)||a.id.localeCompare(b.id));const rr=keyed(w,p.createdYear??p.birthYear,`notable-job:${p.id}`),x=preferred[Math.floor(rr()*Math.min(5,preferred.length))];p.notableProfession=x.def.name;p.professionId=x.id}}}
function applyLaborFeedback(w,m){const city=w.cities?.cities?.[m.settlementId],p=w.history?.current?.settlementProsperity;if(!p)return;const unemp=m.laborForce?m.unemployed/m.laborForce:0,shortage=m.laborForce?m.vacancies/m.laborForce:0,drag=Math.max(0,m.recruitmentPressure-.06)*.012+Math.max(0,unemp-.12)*.008,boost=Math.min(.004,Math.max(0,shortage-.08)*.006);p[m.settlementId]=round(clamp(Number(p[m.settlementId]||.4)-drag+boost,.04,1.2),4);if(city){city.unemployment=round(clamp(unemp,0,.72),4);city.priceIndex=round(clamp(Number(city.priceIndex||100)*(1+Math.max(0,shortage-.1)*.006+Math.max(0,m.recruitmentPressure-.1)*.005),45,360),2)}}
function simulateWorkforceYear(w,year=absYear(w)){const W=initialize(w);syncMarkets(w);for(const m of W.markets){Object.assign(m,laborDemography(w,m.settlementId));m.realmId=owner(w,m.settlementId);m.conscripted=0;m.refugees=Math.max(0,Number(m.refugees||0)*.92)}const byRealm=new Map;for(const m of W.markets){const a=byRealm.get(m.realmId)||[];a.push(m);byRealm.set(m.realmId,a)}for(const[rid,rows]of byRealm)if(rid!=null)allocateConscription(w,rid,rows);for(const m of W.markets){allocateJobs(w,m,year);applyLaborFeedback(w,m)}movePeople(w,year);enrichNotables(w);const employed=W.markets.reduce((n,m)=>n+m.employed,0),unemployed=W.markets.reduce((n,m)=>n+m.unemployed,0),conscripted=W.markets.reduce((n,m)=>n+m.conscripted,0),vacancies=W.markets.reduce((n,m)=>n+m.vacancies,0),specialists=W.markets.reduce((n,m)=>n+m.specialJobs.reduce((q,id)=>q+Number(m.jobs[id]?.workers||0),0),0);W.stats.employed=employed;W.stats.unemployed=unemployed;W.stats.conscripted=conscripted;W.stats.vacancies=vacancies;W.stats.specialists=specialists;W.currentYear=year;W.annual.push({year,employed,unemployed,conscripted,vacancies,migrants:W.movements.filter(x=>x.year===year).reduce((n,x)=>n+x.people,0),meanWage:round(W.markets.reduce((n,m)=>n+m.wageIndex,0)/Math.max(1,W.markets.length),3),meanFill:round(W.markets.reduce((n,m)=>n+m.workforceFill,0)/Math.max(1,W.markets.length),3)});const crisis=W.markets.find(m=>m.recruitmentPressure>.18&&m.vacancies>m.laborForce*.15);if(crisis&&keyed(w,year,`labor-crisis:${crisis.settlementId}`)()<.2){W.stats.laborCrises++;pushHistory(w,{type:'labor_shortage',importance:1,settlementIds:[crisis.settlementId],realmIds:[crisis.realmId].filter(Number.isInteger),title:`Labor shortage in ${w.settlements[crisis.settlementId].name}`,text:`Heavy recruitment and ${crisis.vacancies.toLocaleString()} unfilled positions strain workshops, farms and public services.`})}maintenance(w);return W}
function simulateYears(w,years,options={}){initialize(w);const n=Math.max(0,Math.floor(Number(years)||0));for(let i=0;i<n;i++){if(baseSimulator)baseSimulator(w,1,options);else History?.simulateYears?.(w,1,options);simulateWorkforceYear(w,absYear(w))}return w.workforce}
function simulateTo(w,target,options={}){const t=Math.floor(Number(target)||0),now=absYear(w);if(t<now)throw new Error('Workforce simulation cannot run backward');return simulateYears(w,t-now,options)}
function maintenance(w){const W=state(w),cut=absYear(w)-W.settings.retainDetailedYears;if(cut<=0)return W;const old=W.annual.filter(x=>x.year<cut);if(!old.length)return W;const buckets=new Map;for(const r of old){const start=Math.floor(r.year/250)*250,b=buckets.get(start)||{startYear:start,endYear:start+249,years:0,employed:0,unemployed:0,conscripted:0,migrants:0,meanWage:0};b.years++;b.employed+=r.employed;b.unemployed+=r.unemployed;b.conscripted+=r.conscripted;b.migrants+=r.migrants;b.meanWage+=r.meanWage;buckets.set(start,b)}for(const b of buckets.values()){b.meanWage=round(b.meanWage/Math.max(1,b.years),3);const ex=W.archives.find(x=>x.startYear===b.startYear);if(ex)Object.assign(ex,b);else W.archives.push(b)}W.annual=W.annual.filter(x=>x.year>=cut);W.stats.archivedYears+=old.length;return W}
function settlementView(w,sid){const m=marketState(w,Number(sid)),s=w.settlements?.[sid];if(!s)return null;const jobs=Object.entries(m.jobs||{}).map(([id,v])=>({job:JOB_MAP.get(id),...v})).filter(x=>x.job).sort((a,b)=>b.workers-a.workers||b.vacancies-a.vacancies);return{...m,name:s.name,type:s.type,jobs,topJobs:jobs.slice(0,6),specialProfessions:jobs.filter(x=>x.job.specialist&&x.workers>0),unemploymentRate:m.laborForce?m.unemployed/m.laborForce:0}}
function professionView(w,id){const job=JOB_MAP.get(id);if(!job)return null;const places=state(w).markets.map(m=>({m,v:m.jobs?.[id]})).filter(x=>x.v?.workers>0).sort((a,b)=>b.v.workers-a.v.workers).map(x=>({settlementId:x.m.settlementId,name:w.settlements[x.m.settlementId]?.name,workers:x.v.workers,vacancies:x.v.vacancies,wage:x.v.wage}));return{...job,totalWorkers:places.reduce((n,x)=>n+x.workers,0),totalVacancies:places.reduce((n,x)=>n+x.vacancies,0),places}}
function summary(w){const W=initialize(w),labor=W.markets.reduce((n,m)=>n+m.laborForce,0);return{year:absYear(w),settlements:W.markets.length,laborForce:labor,employed:W.stats.employed,unemployed:W.stats.unemployed,unemploymentRate:labor?W.stats.unemployed/labor:0,conscripted:W.stats.conscripted,recruitmentRate:labor?W.stats.conscripted/labor:0,vacancies:W.stats.vacancies,migrants:W.stats.migrants,refugees:W.stats.refugees,specialists:W.stats.specialists,professions:JOBS.length}}
function fingerprint(w){const W=initialize(w),s=JSON.stringify({year:W.currentYear,markets:W.markets.map(m=>[m.settlementId,m.population,m.laborForce,m.employed,m.unemployed,m.conscripted,m.vacancies,m.wageIndex,m.skillIndex,Object.entries(m.jobs).map(([id,v])=>[id,v.workers,v.vacancies,v.wage])]),movements:W.movements.slice(-300),annual:W.annual.slice(-80),stats:W.stats});return hash(s).toString(16).padStart(8,'0')}
function validate(w){const W=initialize(w),e=[];if(W.markets.length!==(w.settlements?.length||0))e.push('workforce market coverage');for(const m of W.markets){if(m.employed+m.unemployed+m.conscripted>m.laborForce+2)e.push(`labor accounting ${m.settlementId}`);if(m.population<0||m.laborForce<0)e.push(`negative workforce ${m.settlementId}`);for(const id of Object.keys(m.jobs||{}))if(!JOB_MAP.has(id))e.push(`unknown profession ${id}`)}for(const q of W.movements)if(!w.settlements?.[q.from]||!w.settlements?.[q.to])e.push('migration endpoint');return[...new Set(e)]}
const api={VERSION,SCHEMA,JOBS,JOB_MAP,SECTORS,initialize,setBaseSimulator,absYear,simulateWorkforceYear,simulateYears,simulateTo,settlementView,professionView,summary,fingerprint,validate,marketState,jobDemand,isCoastal};
return api;
});